### ISSUE TITLE
An error is reported in the web interface of zabbix:Unable to determine current Zabbix database version: the table "dbversion" was not found.

### ISSUE THREAD

**Issue by cyyyrcyx** [zabbix/zabbix-docker#1000]
https://www.zabbix.com/documentation/current/en/manual/installation/containers
docker-compose -f ./docker-compose_v3_alpine_mysql_latest.yaml up -d
An error is reported in the web interface of zabbix:Unable to determine current Zabbix database version: the table "dbversion" was not found.
Database error
Unable to determine current Zabbix database version: the table "dbversion" was not found.

**Comment by neogan74** [comment]
Did you check container logs?
Is web interface properly connected to DB container or host?
