### ISSUE TITLE
Can't acess Zabbix API from Postman

### ISSUE THREAD

**Issue by HorselessName** [zabbix/zabbix-docker#1001]
Hello. I'm trying to do some testing on the Zabbix API but i'm getting a error:

192.168.17.24 "POST /api_jsonrpc.php HTTP/1.1" 412 5 "-" "PostmanRuntime/7.29.2" "-" ## This is a problem

I also use Grafana, and on Grafana this doesnt happen
172.20.240.0 "POST /api_jsonrpc.php HTTP/1.1" 200 26270 "-" "Grafana/grafana-zabbix" "-" ## This is OK

I went to Docker Hub and gave it a read there on the documentation but didn't find anything regarding permissions and allowing IP addresses, and also nothing about this error.

Help?

**Comment by dotneft** [comment]
Does this one work:
```
curl -H "Content-Type: application/json-rpc" -X POST http://<Zabbix web>/api_jsonrpc.php -d '{"jsonrpc":"2.0","method":"user.login","params":{"user":"Admin","password":"zabbix"},"auth":null,"id":1}'
```
