### ISSUE TITLE
Grafana integration

### ISSUE THREAD

**Issue by neorivs** [zabbix/zabbix-docker#1005]
##### SUMMARY
Hi. I'm new to Docker. I tried to add in the **docker-compose-v3_ubuntu_mysql_latest.yaml** the configuration for a Grafana container:
![photo_2022-08-10_13-34-56](https://user-images.githubusercontent.com/110980372/183892448-407a1e86-2877-4e76-b4df-d5c24cf8e875.jpg)

But when I try to add Zabbix datasource, I get this error:
![photo_2022-08-10_13-35-05](https://user-images.githubusercontent.com/110980372/183892653-4ea64171-28a0-473a-83b5-f2058adc2232.jpg)

I tried using **zabbix-server** instead of localhost, but the result is the same.

**Comment by dotneft** [comment]
You need to use zabbix-web-nginx-mysql:8080
