### ISSUE TITLE
Regular Expressions - Incorrect regular expression: Passing null to parameter #2 ($subject) of type string is deprecated"

### ISSUE THREAD

**Issue by Rau-N** [zabbix/zabbix-docker#1006]
##### SUMMARY

When accessing the "Regular expressions" page at "Administration" -> "General" -> "Regular Expressions", selecting one of the pre-defined regexps like "File systems for discovery" and going to the "Test" tab it immediately shows the following error in the Result column.

`Incorrect regular expression "^(btrfs|ext2|ext3|ext4|reiser|xfs|ffs|ufs|jfs|jfs2|vxfs|hfs|apfs|refs|ntfs|fat32|zfs)$": "Passing null to parameter #2 ($subject) of type string is deprecated"`

![image](https://user-images.githubusercontent.com/77297962/184087688-907522c5-6b2f-41c0-9abe-6dc36a003a36.png)

This makes checking new regular expressions or modificated ones impossible, but it also seems to not evaluate them correctly during service discovery. For example adding another Windows service name in the "Windows service names for discovery" regexp as an additional expression for excluding from discovery doesn't seem to work.

##### OS / ENVIRONMENT / Used docker-compose files

Docker/Container versions:

zabbix/zabbix-server-mysql:ubuntu-6.0.7 / 6.2.1
zabbix/zabbix-web-apache-mysql:ubuntu-6.0.7 / 6.2.1

OS:

Ubuntu 20.04.4 LTS

##### STEPS TO REPRODUCE

```yaml
Go to "Administration" -> "General" -> "Regular Expressions"
Select any Regexp entry
Select the "Test" tab
```

##### EXPECTED RESULTS

When entering a Test string it should evaluate it correctly according to the regexp, for example returning TRUE, when the regexp matches, also see the screenshot listed below (taken from an older Zabbix non-docker version 4.0.0).

![image](https://user-images.githubusercontent.com/77297962/184088697-a8fdc1bb-d7af-4b4e-a4bb-3b4463f4ef82.png)

##### ACTUAL RESULTS

When entering any Test string it always results into the error `"Passing null to parameter #2 ($subject) of type string is deprecated"`, also see the screenshot listed below. After some research I figured out that this error seems to be a PHP 8.x related error, due to changes in parametrization of a certain function not accepting the "null" value anymore.

![image](https://user-images.githubusercontent.com/77297962/184089525-8dbb8ca4-2390-4540-ae8b-d7fee88d4f02.png)

**Comment by dotneft** [comment]
Hello! Please register issue in our bug tracker: https://support.zabbix.com/

**Comment by dotneft** [comment]
Registered https://support.zabbix.com/browse/ZBX-21476
