### ISSUE TITLE
Error running zabbix windows agent on Kubernetes version 1.24 / 1.23 with containerd enabled

### ISSUE THREAD

**Issue by SachinL9** [zabbix/zabbix-docker#1010]
##### SUMMARY
We recently upgraded AKS cluster to Kubernetes version 1.24, post which zabbix agents on windows nodes go into CrashLoopBackOff status. This was working with k8s version 1.22

Could this be related to **containerd** runtime that we have shifted to in 1.24 k8s upgrade?
In earlier k8s version (1,22) we had docker as the Container Runtime.

Error message shown in kubectl describe zabbix agent pod:
```
Message:      failed to start containerd task "3f45bcaf586568f5f030ca2bfce8f587e49ba11e99b68fb0aeff828f3e293d61": hcs::System::CreateProcess 3f45bcaf586568f5f030ca2bfce8f587e49ba11e99b68fb0aeff828f3e293d61: The system cannot find the file specified.: unknown
```

##### OS / ENVIRONMENT / Used docker-compose files

Zabbix image tried: zabbix/zabbix-agent2:ltsc2019-5.0-latest and zabbix/zabbix-agent2:ltsc2019-6.0-latest
Both are giving same error.
Same images worked fine before upgrade.

##### STEPS TO REPRODUCE

Upgrade kubernetes to version 1,23 or later and ensure to use containerd as Container Runtime instead of docker. This should cause zabbix windows agents to fail with above errors.

```yaml

```

##### EXPECTED RESULTS

Zabbix agents should run fine on windows nodes irrespective of container runtime.

##### ACTUAL RESULTS

```paste below

Error shown in kubectl describe zabbix pod:

Containers:
  zabbix-agent-windows:
    Container ID:   containerd://3f45bcaf586568f5f030ca2bfce8f587e49ba11e99b68fb0aeff828f3e293d61
    Image:          zabbix/zabbix-agent2:ltsc2019-6.0-latest
    Image ID:       docker.io/zabbix/zabbix-agent2@sha256:58ac151b44969ac567bf601e555f2535c18403525b96a5eb403856e09fdc9a6c
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       RunContainerError
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to start containerd task "3f45bcaf586568f5f030ca2bfce8f587e49ba11e99b68fb0aeff828f3e293d61": hcs::System::CreateProcess 3f45bcaf586568f5f030ca2bfce8f587e49ba11e99b68fb0aeff828f3e293d61: The system cannot find the file specified.: unknown
      Exit Code:    128

```

**Comment by dotneft** [comment]
Looks like the problem is described in https://github.com/containerd/containerd/issues/5067. May I ask you to try escaped cmd?

**Comment by SachinL9** [comment]
Happy to try. Can you please guide which branch/dockerfile should I work on?

**Comment by dotneft** [comment]
This one: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/. Redefine existing one with escaped one.

**Comment by SachinL9** [comment]
Apologies for not being clear.
To try creating new zabbix image with suggested fix (escaped cmd), which zabbix-docker repo should I use?

Is this the correct dockerfile to try the change?
https://github.com/zabbix/zabbix-docker/blob/6.2/Dockerfiles/agent2/windows/Dockerfile

**Comment by dotneft** [comment]
You do not need to create new image. Just replace existing CMD:  https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/. Specify new command in kubernetes yaml.

**Comment by dotneft** [comment]
did you try replace CMD?
