### ISSUE TITLE
about alertscript cant execute python script

### ISSUE THREAD

**Issue by ga-s** [zabbix/zabbix-docker#1011]
##### SUMMARY

we used python2 and now python3 to send alert message to wechat robot, but the zabbix container does not support it. i saw the wiki, there are two way to reslove it, one is webhook, another is rebuild the image. i tried, webhook cant send msg to robot but only to group which will make us cant receive msg in wechat but in wechat enterprise, its unacceptable. rebuild the image then the network inside the great wall answers no no no,i cant delete  modulers with the no one by one.

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

so, may i ask a favor that official make some images with python3 and python3-request packages in it as a choice? 
thanks for till now
##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
I'm sorry, but we provide only minimal set of required components.
