### ISSUE TITLE
cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)

### ISSUE THREAD

**Issue by mariano-daniel** [zabbix/zabbix-docker#1012]
##### SUMMARY

Hello, I have checked all documentation, forums and even the Discord channel, but sadly not getting many answers.

* I am running Docker version 20.10.17, build 100c701 on macOS Catalina 10.15.7 (19H1922)
* I git cloned zabbix-docker branch 6.0 and ran the following commands:
`docker-compose --profile=all -f docker-compose_v3_alpine_mysql_latest.yaml pull` 
`docker-compose --profile=all -f docker-compose_v3_alpine_mysql_latest.yaml up`

All containers run except: 
* zabbix-docker_zabbix-proxy-mysql_1
* zabbix-docker_zabbix-server_1
* zabbix-docker_db_data_mysql_1

[Here there's a dump of all the outputs I get](https://pastebin.com/y9n2mf1s). I haven't changed anything on the config files, as I am not sure how to push a previous DB version through Docker.

Anyone can help me? It would be greatly appreciated! 🙏

**Comment by mariano-daniel** [comment]
Update: I managed to get past the DB version error, I had to wipe everything from Docker AND from git. Now I'm running into `zabbix-server_1            |      7:20220916:180617.869 cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)` . 

Is there a way to re-download the zabbix DB without having to redo everything?

**Comment by dotneft** [comment]
your DB is corrupted, recreate it. If you do not worry about current data, just remove zbx_env.

**Comment by mariano-daniel** [comment]
Hello Alexey! Thanks for the tip. Do you know what’s the best way to recreate the DB in Docker? (sorry for the n00b question, just googled about it, so many different ways to do it but nothing has worked so far.

Thanks again!

Mariano.

**Comment by dotneft** [comment]
```
docker-compose --profile=all -f docker-compose_v3_alpine_mysql_latest.yaml kill
rm -rf zbx_env
docker-compose --profile=all -f docker-compose_v3_alpine_mysql_latest.yaml up -d
```
like this

**Comment by mariano-daniel** [comment]
Thanks a lot @dotneft ! I will definitely keep this thread on my bookmarks for future reference. Thank you! 🙏
