### ISSUE TITLE
Issues in setting up monitoring for docker environments 

### ISSUE THREAD

**Issue by derkaan** [zabbix/zabbix-docker#1014]
##### SUMMARY

Monitoring docker environments are reported as "Docker: Service is down".
The proposed solution [here](https://github.com/zabbix/zabbix-docker/issues/756) unfortunately didn't helped to solve the issue.

My setup is based on this repo and I cloned on my server 
```bash
git clone https://github.com/zabbix/zabbix-docker.git
```

 branch is on 
```bash
git branch
* 6.2
```

##### OS / ENVIRONMENT / Used docker-compose files

I'm using following docker-compose file to start my environment: docker-compose_v3_alpine_pgsql_latest.yaml
This is the command I use to start things up:
```bash
docker compose -f ./docker-compose_v3_alpine_pgsql_latest.yaml up -d
```

Host 
```bash
uname -a
Linux zabbix 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
```

docker version
```bash
docker -v
Docker version 20.10.18, build b40c2f6
```

docker compose version
```bash
docker compose version
Docker Compose version v2.10.2
```

##### CONFIGURATION

On the host itself I've installed the zabbix agent 2 according to the instructions [here](https://www.zabbix.com/de/download?zabbix=6.2&os_distribution=debian&os_version=11&components=agent2&db=&ws=)

```bash
wget https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-2%2Bdebian11_all.deb
dpkg -i zabbix-release_6.2-2+debian11_all.deb
apt update
apt install zabbix-agent2 zabbix-agent2-plugin-mongodb
systemctl restart zabbix-agent2
systemctl enable zabbix-agent2
```

Afterward I did follwoing adjustment in /etc/zabbix/zabbix_agent2.conf
```bash
Server=127.0.0.1,<HOST_SERVER_IP>,<zabbix-docker_zbx_net_frontend_IP>
```

##### STEPS TO REPRODUCE

After starting the zabbix environment as noted above, I've used  the web frontend to...
- setup a new host
- Add "Docker by Zabix agent 2" in templates
- add to "Linux servers" group
- Interface "Agent" + IP Address of the host

As this setup has ended up in "Docker: Service is down", I tried to make a call on the console.

Logged into the zabbix server (docker)
```bash
docker compose exec --user root zabbix-server bash
```
Tried to execute following command:
```bash
zabbix_get -s <IP_OF_THE_TO_BE_MONITORED_SERVER> -k docker.info
```

This unfortunately returned this msg 
```bash 
ZBX_NOTSUPPORTED: Cannot fetch data: Get "http://1.28/info": dial unix /var/run/docker.sock: connect: permission denied.
```

##### EXPECTED RESULTS

Expectation was to see the running docker images with all the details. Currently the graphs are listed but all are empty.

##### Help

Am I missing a step or config to get docker monitoring up and running?
Any help is highly appreciated.

**Comment by dotneft** [comment]
Please check https://github.com/zabbix/zabbix-docker/issues/917
