### ISSUE TITLE
upgraded the proxy image from centos 7 to centos stream 8 but when the container is started seeing a message "Impossible to use MYSQL as root password is not defined".The older version never asked for a root password for MYSQL. How can i create one and pass it as a environment variable to the docker run command. Please help!

### ISSUE THREAD

**Issue by pbvnb** [zabbix/zabbix-docker#1020]
![Capture](https://user-images.githubusercontent.com/114737608/195420745-60291852-0b8d-486b-9899-b215ef027cd3.PNG)

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
You need just specify MYSQL_USER.

**Comment by pbvnb** [comment]
Hi Alexey,

Glad you replied me …we are sending the user already in the docker run
command .please refer the screen shot

**Comment by dotneft** [comment]
Screenshot does not show env variables you specified, please, show what env vars you specified.

**Comment by pbvnb** [comment]
Sure please check this one

**Comment by dotneft** [comment]
Nothing attached...

**Comment by pbvnb** [comment]
hi ,

can u see now

**Comment by dotneft** [comment]
no. check web, do not use mail messages

**Comment by pbvnb** [comment]
Hi , 

I am attaching here 
![Capture1](https://user-images.githubusercontent.com/114737608/195427304-250254da-f2d7-4edd-bbe6-e15bc555f758.PNG)

**Comment by dotneft** [comment]
Probably you use some custom image, it is impossible to have such error with specified MYSQL_USER: https://github.com/zabbix/zabbix-docker/blob/6.2/Dockerfiles/proxy-mysql/centos/docker-entrypoint.sh#L162

**Comment by pbvnb** [comment]
Do you think sending you the docker file which is used for the base image helps ?

**Comment by dotneft** [comment]
We support only our official images. What do you have in entrypoint shell script on the line I specified in the previous comment?

**Comment by pbvnb** [comment]
It's the same infact copied the same script..
I can use the official image directly but the issue is with these lines

COPY --from=builder ["/tmp/zabbix-${ZBX_VERSION}/src/zabbix_proxy/zabbix_proxy", "/usr/sbin/zabbix_proxy"]
COPY --from=builder ["/tmp/zabbix-${ZBX_VERSION}/src/zabbix_get/zabbix_get", "/usr/bin/zabbix_get"]
COPY --from=builder ["/tmp/zabbix-${ZBX_VERSION}/src/zabbix_sender/zabbix_sender", "/usr/bin/zabbix_sender"]
COPY --from=builder ["/tmp/zabbix-${ZBX_VERSION}/conf/zabbix_proxy.conf", "/etc/zabbix/zabbix_proxy.conf"]
COPY --from=builder ["/tmp/zabbix-${ZBX_VERSION}/database/mysql/create_proxy.sql.gz", "/usr/share/doc/zabbix-proxy-mysql/create.sql.gz"]

while building the continer these throws errors any advice on this ?

**Comment by dotneft** [comment]
you need specify our builder image in BUILD_BASE_IMAGE build argument.

**Comment by pbvnb** [comment]
I am using 5.0.25 version but seeing the below error while doing a container build

Sending build context to Docker daemon  30.72kB
Step 1/25 : ARG MAJOR_VERSION=5.0
Step 2/25 : ARG ZBX_VERSION=${MAJOR_VERSION}.25
Step 3/25 : ARG BUILD_BASE_IMAGE=zabbix-build-mysql:centos-${ZBX_VERSION}
Step 4/25 : FROM ${BUILD_BASE_IMAGE} as builder
pull access denied for zabbix-build-mysql, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[ ?0 h010081006198.zab-pxy-dev.aws-ue1-a.vdc3.npcloud.zone   root 1 !1088 &0 20:39:30 ]

**Comment by dotneft** [comment]
what build arguments did you specify for image building?

**Comment by pbvnb** [comment]
docker build --pull --rm -f Dockerfile -t  zabbix-proxy-mysql:centostreamy8-5.0.25 .

This is the command used

**Comment by dotneft** [comment]
As I told before, you need specify build argument:
```
docker build --pull --rm --build-arg BUILD_BASE_IMAGE=zabbix/zabbix-build-mysql:centos-5.0.25 -f Dockerfile -t zabbix-proxy-mysql:centostreamy8-5.0.25 .
```
