### ISSUE TITLE
Zabbix-Frontend 

### ISSUE THREAD

**Issue by iman-namjooyan** [zabbix/zabbix-docker#1025]
##### SUMMARY

Hello
I used the project linked below to setup Zabbix. But unfortunately, Zabbix-Frontend connects and disconnects the pod connection to Zabbix-Server every 2 seconds.

[https://github.com/bezarsnba/zabbix-on-kubernetes](url)

##### OS / ENVIRONMENT / Used docker-compose files

**Kubernets 1.24**
Docker image list:
- zabbix/zabbix-server-mysql:6.0-ol-latest
- zabbix/zabbix-web-apache-mysql:6.0-ol-latest
- docker pull mariadb:10.5.17

##### CONFIGURATION

**Manifest files:**
[configmaps.yaml](https://gist.github.com/IMAN-NAMJOOYAN/6187c0dd751f4a65f5fefc1dce98b11c#file-configmaps-yaml)
[zabbix-frontend-yaml](https://gist.github.com/IMAN-NAMJOOYAN/6187c0dd751f4a65f5fefc1dce98b11c#file-zabbix-frontend-yaml)
[zabbix-server-yaml](https://gist.github.com/IMAN-NAMJOOYAN/6187c0dd751f4a65f5fefc1dce98b11c#file-zabbix-server-yaml)

**Comment by dotneft** [comment]
Sorry, but what is the problem?
