### ISSUE TITLE
zabbix agent docker swarm - docker compose

### ISSUE THREAD

**Issue by layer3lv** [zabbix/zabbix-docker#1027]
Please fix the docker agent compose env.

ZBX_SERVER_HOST env. updates both the Zabbix server and the active server simultaneously! but parameters should be updated separately because incoming connections to the Zabbix agent connect from the ingress network!

**Comment by dotneft** [comment]
it works with simple configuration. What i difference in your config? With ingress network current compose file is not full...

**Comment by layer3lv** [comment]
> it works with a simple configuration. What i the difference in your config? With the ingress network current compose file is not full...

I don't have problems start Zabbix agent in the docker swarm

ENV.
ZBX_SERVER_HOST:proxy,10.0.0.2

p.s
I didn't find a way to set something like this Server: proxy,10.0.0.2
Active checks: proxy (because ZBX_SERVER_HOST set hosts in server and active checks the same by default when I start the agent.)

log:
** Using 'proxy,10.0.0.2' servers for passive checks
 ** Using 'proxy,10.0.0.2:10051' servers for active checks

**Comment by dotneft** [comment]
Use ZBX_PASSIVESERVERS instead of ZBX_SERVER_HOST. If you use ZBX_SERVER_HOST, it is applied to both Active and Passive params.
