### ISSUE TITLE
**** MySQL server is not available. Waiting 5 seconds...

### ISSUE THREAD

**Issue by vinodk99** [zabbix/zabbix-docker#1029]
While running docker start -it b30c899693bda

##### ACTUAL RESULTS
** Preparing Zabbix server
** Using MYSQL_USER variable from ENV
** Using MYSQL_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: mysql
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...

**Comment by dotneft** [comment]
I recommend you check mysql container availability from Zabbix server / frontend containers.

**Comment by smanzo** [comment]
I am also experiencing this from a fresh docker-compose install. Only changes made to the YML were entering the MYSQL_USER, MYSQL_USER_PASSWORD, and MYSQL_ROOT_PASSWORD env.vars.

Confirmed occurring for both docker-compose_v3_alpine_mysql_latest.yaml and docker-compose_v3_ubuntu_mysql_latest.yaml

**Comment by jiriks74** [comment]
> I am also experiencing this from a fresh docker-compose install. Only changes made to the YML were entering the MYSQL_USER, MYSQL_USER_PASSWORD, and MYSQL_ROOT_PASSWORD env.vars.
> 
> Confirmed occurring for both docker-compose_v3_alpine_mysql_latest.yaml and docker-compose_v3_ubuntu_mysql_latest.yaml

I have this issue as well. NONE of the provided configurations work and all I changed were the passwords and port for frontend (from `80:80` to `8880:80` as `80` is used)
