### ISSUE TITLE
web-nginx-pgsql

### ISSUE THREAD

**Issue by sander110419** [zabbix/zabbix-docker#1031]
##### SUMMARY
It seems the [web-nginx-pgsql](https://github.com/zabbix/zabbix-docker/tree/6.2/Dockerfiles/web-nginx-pgsql) is built upon the [build-mysql](https://github.com/zabbix/zabbix-docker/tree/6.2/Dockerfiles/build-mysql) instead of the [build-pgsql](https://github.com/zabbix/zabbix-docker/tree/6.2/Dockerfiles/build-pgsql) for ubuntu.
This makes that we have to maintain another image just for the frontend.
For alpine, centos and ol releases the base image is correctly set to [build-pgsql](https://github.com/zabbix/zabbix-docker/tree/6.2/Dockerfiles/build-pgsql).
Building [web-nginx-pgsql](https://github.com/zabbix/zabbix-docker/tree/6.2/Dockerfiles/web-nginx-pgsql) with the [build-pgsql](https://github.com/zabbix/zabbix-docker/tree/6.2/Dockerfiles/build-pgsql) base image does work perfectly, so I don't know if there is a specific need to keep [build-mysql](https://github.com/zabbix/zabbix-docker/tree/6.2/Dockerfiles/build-mysql) as the default base image.

**Comment by dotneft** [comment]
Agree! Will be fixed soon.

**Comment by dotneft** [comment]
Fixed!
