### ISSUE TITLE
couldn't open udp6:1162 -- errno 97 snmptrap container

### ISSUE THREAD

**Issue by michelaldaher** [zabbix/zabbix-docker#1032]
i got this error while deploying snmp trap container, i have tried both alpine and ubuntu.

the command used:

sudo docker run --privileged --detach --name zabbix-snmptraps -t \
      -v /zabbix/zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw \
      -v /zabbix/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro \
      -p 162:1162/udp \
      --restart unless-stopped \
      -d zabbix/zabbix-snmptraps:alpine-6.2-latest

the error in the logs:

couldn't open udp6:1162 -- errno 97 ("Address family not supported by protocol")

**Comment by dotneft** [comment]
Try to attach to the container custom snmptrapperd configuration file without TCPv6 configuration.

**Comment by zilion2000** [comment]
Can anyone provide where this custom configuration can be found? Or how to create one. I can't find any info on the net.
