### ISSUE TITLE
zabbix-agent2:latest alpine version missing postgresql/mongodb plugins

### ISSUE THREAD

**Issue by neothematrix** [zabbix/zabbix-docker#1033]
hi,
it seems that recently, postgresql and mongodb plugins for Zabbix Agent 2 were [moved to loadable plugins instead of built-in](https://support.zabbix.com/browse/ZBX-21855).
The result is that the alpine image for zabbix-agent2 lost support for postgresql and mongodb monitoring because those two plugins are not included.
Is it possible to update these alpine images and include the plugins again?
thanks!

**Comment by dotneft** [comment]
Known issue, will be fixed soon!

**Comment by dotneft** [comment]
added!
