### ISSUE TITLE
cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)

### ISSUE THREAD

**Issue by rbuffi** [zabbix/zabbix-docker#1034]
When running zabbix-docker on kubernetes using the kubernetes.yaml I get the following error:

cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)

Already tried to delete and recreate database according to zabbix documentation, (I have not run the databse creation script.)

**Comment by dotneft** [comment]
Try to increase timeout for liveness check of Zabbix server to avoid restart it during DB schema deployment.
