### ISSUE TITLE
alerts are not working on the zabbix-server(docker-compose) v6.2 and v6.

### ISSUE THREAD

**Issue by MakeUsWhole** [zabbix/zabbix-docker#1036]
when setting up an alert via telegram : Couldn't resolve host name: Could not resolve host:
when setting up an alert via email : couldn't resolve host name: getaddrinfo() thread failed to start zabbix server

**Comment by dotneft** [comment]
looks like the problem with DNS...

**Comment by MakeUsWhole** [comment]
i do some tests 
docker run busybox nslookup google.com 

Server:         8.8.8.8
Address:        8.8.8.8:53

Non-authoritative answer:
Name:   google.com
Address: 142.251.1.100
Name:   google.com
Address: 142.251.1.113
Name:   google.com
Address: 142.251.1.101
Name:   google.com
Address: 142.251.1.102
Name:   google.com
Address: 142.251.1.139
Name:   google.com
Address: 142.251.1.138

*** Can't find google.com: No answer

nslookup google.com

Non-authoritative answer:
Name:   google.com
Address: 142.251.1.113
Name:   google.com
Address: 142.251.1.138
Name:   google.com
Address: 142.251.1.100
Name:   google.com
Address: 142.251.1.101
Name:   google.com
Address: 142.251.1.102
Name:   google.com
Address: 142.251.1.139
Name:   google.com
Address: 2a00:1450:4010:c1e::71
Name:   google.com
Address: 2a00:1450:4010:c1e::65
Name:   google.com
Address: 2a00:1450:4010:c1e::8b
Name:   google.com
Address: 2a00:1450:4010:c1e::8a

docker run --rm busybox:1.28 nslookup example.com

Server:    8.8.8.8
Address 1: 8.8.8.8 dns.google

Name:      example.com
Address 1: 2606:2800:220:1:248:1893:25c8:1946
Address 2: 93.184.216.34

what's the problem here, I don't know?
when test telegam alert :
Sending failed: Error: cannot get URL: Couldn't resolve host name..

**Comment by dotneft** [comment]
check DNS what exactly use telegram alert script.
