### ISSUE TITLE
sh: sudo: not found

### ISSUE THREAD

**Issue by dpearceMN** [zabbix/zabbix-docker#1037]
##### SUMMARY
Using Docker hub images (https://hub.docker.com/r/zabbix/zabbix-server-mysql)

##### OS / ENVIRONMENT / Used docker-compose files
Ubuntu v22 in Docker 20.10.21 using the "docker run" commands listed in https://hub.docker.com/r/zabbix/zabbix-server-mysql
script: https://castinganet.net/posts/Docker-Zabbix/

##### STEPS TO REPRODUCE
Added a host with a Zabbix agent. Click on that host or the Zabbix server itself and "detect operating system". 

##### EXPECTED RESULTS
OS information.

##### ACTUAL RESULTS
Got an error message: "sh: sudo: not found"

**Comment by dotneft** [comment]
fixed
