### ISSUE TITLE
Incorrect image 

### ISSUE THREAD

**Issue by Elbrus12** [zabbix/zabbix-docker#1038]
Ports 8080/tcp and 8443/tcp open, but in it is written that ports 10051 are being opened

**Comment by dotneft** [comment]
sorry, what?

**Comment by Elbrus12** [comment]
The documentation states that the server itself runs on ports 10051, but in docker, at startup, for some reason it opens 8080 and 8443

**Comment by dotneft** [comment]
could you show me that?
