### ISSUE TITLE
Allow container start without MySQL root credentials

### ISSUE THREAD

**Issue by ezekieldas** [zabbix/zabbix-docker#1039]
##### SUMMARY

I'm near certain that MySQL root user is only necessary at installation. I'm looking for a means to not provide the root credentials and return my non-Docker MySQL database to root@localhost only. 

##### OS / ENVIRONMENT / Used docker-compose files

I'm using compose file https://github.com/zabbix/zabbix-docker/blob/6.2/docker-compose_v3_alpine_mysql_latest.yaml with running containers:

zabbix-docker-zabbix-web-nginx-mysql-1   
zabbix-docker-zabbix-server-1

I've defined my db with:

```
env_vars/.env_db_mysql:
DB_SERVER_HOST=sql001.welovezabbix.net
```

##### STEPS TO REPRODUCE

If `env_vars/.MYSQL_ROOT_PASSWORD` is either null / no contents or contains the default `root_pwd` the `zabbix-docker-zabbix-server-1` will NOT start. The `zabbix-docker-zabbix-server-1` will start ONLY IF I provide my functional production root password. This applies to consecutive starts following the initial installation when I believe it is not / should not be necessary. 

I'm not certain what this does and I'd like to better understand: 

```
env_vars/.env_db_mysql:
MYSQL_ALLOW_EMPTY_PASSWORD=true
```

...and I think there's something here but I can't quite figure it out: 

https://github.com/zabbix/zabbix-docker/blob/6.2/Dockerfiles/server-mysql/alpine/docker-entrypoint.sh#L170

##### EXPECTED RESULTS

I'm 99.6% certain non-Docker Zabbix did not require the root password beyond the initial db creation, schema apply. I'd like to find a means to not require my db root password to the Docker based Zabbix.

**Comment by dotneft** [comment]
Just do not specify root password :-) It is required only if DB is not created.
