### ISSUE TITLE
How to set password and login in docker container?

### ISSUE THREAD

**Issue by Elbrus12** [zabbix/zabbix-docker#1041]
I want to set password and login in docker container, can i do that?

**Comment by dotneft** [comment]
password and login for what?

**Comment by Elbrus12** [comment]
For administrator's authorization in Zabbix

**Comment by dotneft** [comment]
It is default: Admin / zabbix.

**Comment by Elbrus12** [comment]
For security, it would be nice if you add the ability to set different password

**Comment by dotneft** [comment]
Sorry, but not, we provide the same set of possibilities and features like default installed application. If you would like to have something custom:
1. You can create image based on ours
2. Add init image for any changes you need in DB

**Comment by Elbrus12** [comment]
okey, thank you!
