### ISSUE TITLE
Connection from Web Interface to DB container fails using docker-compose

### ISSUE THREAD

**Issue by sebelk** [zabbix/zabbix-docker#1042]
##### SUMMARY

Zabbix web-interface stays on unhealthy status.

##### OS / ENVIRONMENT / Used docker-compose files

* Docker version 20.10.22, build 3a2c30b
* Using  commit 11da3748a3218539f1f73d249f4ee6add7458c9d (HEAD -> 6.2, origin/HEAD, origin/6.2)
*  OS: Fedora release 37 
* Using docker-compose_v3_alpine_mysql_latest.yaml

##### STEPS TO REPRODUCE

`docker-compose --verbose  -f ./docker-compose_v3_alpine_mysql_latest.yaml up`

##### EXPECTED RESULTS

Zabbix web-interface container gets up and running

##### ACTUAL RESULTS

```paste below
docker ps

CONTAINER ID   IMAGE                                             COMMAND                  CREATED          STATUS                             PORTS                                                                            NAMES
96c12f25162a   zabbix/zabbix-web-nginx-mysql:alpine-6.2-latest   "docker-entrypoint.sh"   43 seconds ago   Up 40 seconds (health: starting)   0.0.0.0:80->8080/tcp, :::80->8080/tcp, 0.0.0.0:443->8443/tcp, :::443->8443/tcp   zabbix-docker_zabbix-web-nginx-mysql_1
0225227c4018   zabbix/zabbix-server-mysql:alpine-6.2-latest      "/sbin/tini -- /usr/…"   44 seconds ago   Up 42 seconds                      0.0.0.0:10051->10051/tcp, :::10051->10051/tcp                                    zabbix-docker_zabbix-server_1
253f044212ff   mysql:8.0-oracle                                  "docker-entrypoint.s…"   45 seconds ago   Up 43 seconds                                                                
```

And
```paste below
docker logs zabbix-docker_zabbix-web-nginx-mysql_1 

**** MySQL server is not available. Waiting 5 seconds...
``` 

And it persists so forever...

That issue was reported earlier at #1029 . However it was closed, and is not clear at least for me. Please could help and tell me:
- Is there a bug on zabbix-docker_mysql-server_1 container ?
- Is supposed that it works out of the box? If not,  what changes should be made? 
- Did I do something wrong?
- As note aside, I've tried with apache service instead nginx one, even using other docker-compose files provided in the repo and it didn't worked either, always it failed with the same error. On other hand, podman containers mentioned at [5 Installation from containers](https://www.zabbix.com/documentation/current/en/manual/installation/containers) works fine.

Thanks in advance

**Comment by rusomenace** [comment]
Can confirm the same problem, clone repo and run in docker compose docker-compose_v3_ubuntu_mysql_latest.yaml.
Besides the error on CPU reservations only 3 containers come up: 
```

CONTAINER ID   IMAGE                                             COMMAND                  CREATED         STATUS                   PORTS                                                                            NAMES
6fb58d56773f   zabbix/zabbix-web-nginx-mysql:ubuntu-6.2-latest   "docker-entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)   0.0.0.0:80->8080/tcp, :::80->8080/tcp, 0.0.0.0:443->8443/tcp, :::443->8443/tcp   zabbix-docker_zabbix-web-nginx-mysql_1
ddadc3e4d337   zabbix/zabbix-server-mysql:ubuntu-6.2-latest      "/usr/bin/tini -- /u…"   5 minutes ago   Up 5 minutes             0.0.0.0:10051->10051/tcp, :::10051->10051/tcp                                    zabbix-docker_zabbix-server_1
5cd2b12f1765   mysql:8.0-oracle                                  "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes                                                                                              zabbix-docker_mysql-server_1
                               
```
Wont pull other images and spin up containers

Thanks

**Comment by dotneft** [comment]
How many do you want? I checked a few times the same, no problems at all.

**Comment by vaughngx4** [comment]
Having the same issue. I must admit though as someone who develops with Docker, I can't find any reason that it shouldn't work. Everything looks fine, MYSQL server is up and listening on port 3306, containers are on the correct networks. Something very specific is going wrong.

EDIT: I can ping the MYSQL container as `mysql-server` from the zabbix-server container but the server refuses to connect.

**Comment by dotneft** [comment]
Try manually connect from Zabbix server to the MySQL container.

**Comment by vaughngx4** [comment]
@dotneft Forgive me, but how would one go about manually connecting?

**Comment by vaughngx4** [comment]
So, using a modified version of a compose yaml I found [here](https://techviewleo.com/how-to-run-zabbix-server-in-docker-containers/) I was able to get this in the server logs:

```
** Creating 'zabbix' user in MySQL database
** Database 'zabbix' already exists. Please be careful with database COLLATE!
** Creating 'zabbix' schema in MySQL
```

In the web UI I get this message:
```
Database error

The Zabbix database version does not match current requirements. Your database version: 6020000. Required version: 6000000. Please contact your system administrator.
```

I've read elsewhere that now I just need to wait, understandable. Hope this helps.

EDIT: The yaml in the link above mixes `latest` and `6.0` tags, after changing them to `latest` everything seems to be working, waiting on the database to populate.

**Comment by vaughngx4** [comment]
No luck. Not sure what's going wrong.

**Comment by dotneft** [comment]
Check mysql availability using standard mysql client from Zabbix server and vanilla docker-compose files.

**Comment by vaughngx4** [comment]
@dotneft When using defaults aside from a few env vars for database password I am face with the same error as OP. 

```
**** MySQL server is not available. Waiting 5 seconds...
```
endlessly.

The command `docker exec zabbix-docker-zabbix-server-1 ping -c3 mysql-server` returns:
```
PING mysql-server (172.16.239.2) 56(84) bytes of data.
64 bytes from zabbix-docker-mysql-server-1.zabbix-docker_zbx_net_backend (172.16.239.2): icmp_seq=1 ttl=64 time=0.137 ms
64 bytes from zabbix-docker-mysql-server-1.zabbix-docker_zbx_net_backend (172.16.239.2): icmp_seq=2 ttl=64 time=0.107 ms
64 bytes from zabbix-docker-mysql-server-1.zabbix-docker_zbx_net_backend (172.16.239.2): icmp_seq=3 ttl=64 time=0.094 ms
```

**Comment by vaughngx4** [comment]
I think I know what you mean by connect manually, I ran this command: 
```
docker exec zabbix-docker-zabbix-server-1 mysql -u zabbix -pMyStrongPassword -h mysql-server zabbix
```
and got the a response of:
```
ERROR 2002 (HY000): Can't connect to server on 'mysql-server' (115)
```

**Comment by vaughngx4** [comment]
The database looks good.

In logs:
```
2023-02-15 11:21:15+00:00 [Note] [Entrypoint]: Creating database zabbix
2023-02-15 11:21:16+00:00 [Note] [Entrypoint]: Creating user zabbix
2023-02-15 11:21:17+00:00 [Note] [Entrypoint]: Giving user zabbix access to schema zabbix
```

Inspecting container:
```
"ExposedPorts": {
                "3306/tcp": {},
                "33060/tcp": {}
            },
```

However, with a `docker ps | grep zabbix`, the MYSQL container is not showing any exposed ports
```
da3880512663   zabbix/zabbix-web-nginx-mysql:alpine-6.2-latest   "docker-entrypoint.sh"   4 hours ago    Up 4 hours (unhealthy)   8080/tcp, 8443/tcp                                                                 zabbix-docker-zabbix-web-nginx-mysql-1
7b28cfa5ab77   zabbix/zabbix-server-mysql:alpine-6.2-latest      "/sbin/tini -- /usr/…"   4 hours ago    Up 4 hours               0.0.0.0:10051->10051/tcp, :::10051->10051/tcp                                      zabbix-docker-zabbix-server-1
7432bbc835f7   mysql:8.0-oracle                                  "docker-entrypoint.s…"   4 hours ago    Up 4 hours                                                                                                  zabbix-docker-mysql-server-1
```

**Comment by dotneft** [comment]
So port 3306 is not available on mysql server. Check network details for both containers.

**Comment by vaughngx4** [comment]
Okay so the MYSQL is not listening on any ports. Here is the `NetworkSettings` portion of my `docker inspect` on the sql container:

```
{
  "Bridge": "",
  "SandboxID": "123123123",
  "HairpinMode": false,
  "LinkLocalIPv6Address": "",
  "LinkLocalIPv6PrefixLen": 0,
  "Ports": {},
  "SandboxKey": "/var/run/docker/netns/fcee0bdfaa08",
  "SecondaryIPAddresses": null,
  "SecondaryIPv6Addresses": null,
  "EndpointID": "",
  "Gateway": "",
  "GlobalIPv6Address": "",
  "GlobalIPv6PrefixLen": 0,
  "IPAddress": "",
  "IPPrefixLen": 0,
  "IPv6Gateway": "",
  "MacAddress": "",
  "Networks": {
    "zabbix-docker_zbx_net_backend": {
      "IPAMConfig": {},
      "Links": null,
      "Aliases": [
        "zabbix-docker-mysql-server-1",
        "mysql-server",
        "zabbix-database",
        "mysql-database",
        "dcde6e5fd2f8"
      ],
      "NetworkID": "123123123",
      "EndpointID": "123123123",
      "Gateway": "172.16.239.1",
      "IPAddress": "172.16.239.2",
      "IPPrefixLen": 24,
      "IPv6Gateway": "",
      "GlobalIPv6Address": "",
      "GlobalIPv6PrefixLen": 0,
      "MacAddress": "12:12:12:12:12:12",
      "DriverOpts": null
    }
  }
}

```
`"Ports": {},` isn't a good sign.

**Comment by vaughngx4** [comment]
I read somewhere about mysql listening on 127.0.0.1 by default but these are official images I would assume they listen on 0.0.0.0

**Comment by vaughngx4** [comment]
Is there any more information I can provide to assist with this issue? I've tried a few different MYSQL tags and the Postgres compose files with the same result. Using `Docker version 20.10.18, build b40c2f6`.

**Comment by dotneft** [comment]
check "zabbix-docker_zbx_net_backend" network details

**Comment by vaughngx4** [comment]
`docker network inspect zabbix-docker_zbx_net_backend`

```
[
    {
        "Name": "zabbix-docker_zbx_net_backend",
        "Id": "9a675c8959e430b5472d6a2f01ffcbbe0b2fe8331cb10212140c9b45459e60a9",
        "Created": "2023-02-17T15:58:50.415931929+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.239.0/24"
                }
            ]
        },
        "Internal": true,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "9066dcf58269a6e09d0a81123f702c95ce2da092e717ca81f270b8f613ca6a01": {
                "Name": "zabbix-docker-zabbix-server-1",
                "EndpointID": "e43f04133a81e690e25df92a3095b7d8d28c8cf49731da3625c33662d9375deb",
                "MacAddress": "02:42:ac:10:ef:03",
                "IPv4Address": "172.16.239.3/24",
                "IPv6Address": ""
            },
            "b187cc1b961193d3c7cfb90c065114f19b33646beaab1710815ce910e3973d3b": {
                "Name": "zabbix-docker-zabbix-web-nginx-mysql-1",
                "EndpointID": "095fea59bf43b70eef5e68b8705e01a7cc69a775c7997430f73e68ca531b3051",
                "MacAddress": "02:42:ac:10:ef:04",
                "IPv4Address": "172.16.239.4/24",
                "IPv6Address": ""
            },
            "f5247345df53d1c712944b2eaea79855092d4872f74a98f08eee02b6ee3303cf": {
                "Name": "zabbix-docker-mysql-server-1",
                "EndpointID": "764fc8031e4c75490e1857d080011df0e7a17c02970754431eb17f0e080599a1",
                "MacAddress": "02:42:ac:10:ef:02",
                "IPv4Address": "172.16.239.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.enable_ipv6": "false"
        },
        "Labels": {
            "com.docker.compose.network": "zbx_net_backend",
            "com.docker.compose.project": "zabbix-docker",
            "com.docker.compose.version": "2.10.2"
        }
    }
]
```

**Comment by dotneft** [comment]
It is ""Internal": true", that is why you can not reach.

**Comment by dollarstar** [comment]
If you set "internal: false" then the containers can interact with each other in this network, if you set "true" then the containers do not see each other. But the ping between them on this network goes.
Question: How does it work for all those who write that everything is fine?
By default, this parameter is in branches 6.2, 6.0 and 5.0 (I didn’t look for it anymore).

**Comment by dotneft** [comment]
It works because default compose files contain two networks, one for internal (between containers), another for frontend area.

**Comment by ghost** [comment]
sorry but why is this closed as the question of @sebelk and @vaughngx4 is clearly unanswered! 

also we have a frech ubuntu 22.04 with docker version 24.0.2. and alpine with mysql nor alpine with pgsql are working for us with the seame error. We cant ping the mysql from the zabbix-server nor can we connect via mysql-client from the zabbix-server to the mysql-server

![image](https://github.com/zabbix/zabbix-docker/assets/557/50d69fb4-1ea3-43cb-bb3c-e871c2ec2762)

![image](https://github.com/zabbix/zabbix-docker/assets/557/2be307fd-21d0-4e60-bb01-31b62bc15920)

**Comment by kernbug** [comment]
@marvin https://docs.docker.com/network/

**Comment by ghost** [comment]
> @marvin https://docs.docker.com/network/

thx ... so this means all the yml files are useless? and they dont work out of the box? 

all we did is used a fresh ubuntu with the yml files provided.

**Comment by kernbug** [comment]
Provided yaml files works as designed. If custom network configuration is used - you need to configure this by yourself.

**Comment by ghost** [comment]
> Provided yaml files works as designed. If custom network configuration is used - you need to configure this by yourself.

although you didnt seem to look into my comment included screenshots (which show you that this is the default network configuration) and as i also wrote in my comment "we used a fresh ubuntu with the repo out of the box and it didnt work" you didnt seem to bother to read it. but well at least you made a comment although not really helpfull! 

Thank you for nothing then. Although you are trying to help maybe reading the provided information might change the way you provide responses instead of sending out "automatic response" like "did you google it?" ....

**Comment by dollarstar** [comment]
@marvin 
In my post above it says what parameter needs to be changed.
Please try and subscribe.

P.S. I realized that it is useless to argue with them. it's easier to write that you are doing everything wrong than to check it yourself.

**Comment by ghost** [comment]
> `docker network inspect zabbix-docker_zbx_net_backend`

thank you finally a productive answer! this doesnt work for me though as i had checked it before. i tried --force-recreate and it shows as internal false but still doesnt work. in the mysql-server the server ist up and via the mysql-docker container i can connect to the DB but not from the zabbix-server container. 

![image](https://github.com/zabbix/zabbix-docker/assets/557/01377084-222d-4ef8-b4a4-5fea89a516cf)

i will try my luck any further. thank you anyway!

**Comment by dotneft** [comment]
everything works fine on vanilla Ubuntu 22.04 with official docker:
```
    1  apt update
    2  apt upgrade
    3  sudo apt-get install ca-certificates curl gnupg
    4  sudo install -m 0755 -d /etc/apt/keyrings
    5  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    6  sudo chmod a+r /etc/apt/keyrings/docker.gpg
    7  echo   "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" |   sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    8  sudo apt-get update
    9  git
   10  git clone https://github.com/zabbix/zabbix-docker.git
   11  cd zabbix-docker/
   12  docker compose -f docker-compose_v3_ubuntu_mysql_latest.yaml up -d
   13  docker ps
   14  docker logs -f zabbix-docker-zabbix-server-1
```
I'm not sure where from you installed compose, because in my case:
```
"com.docker.compose.version": "2.18.1"
```
