### ISSUE TITLE
zabbix-web-nginx-pgsql alpine image delay in statistics loading

### ISSUE THREAD

**Issue by UntestedEngineer** [zabbix/zabbix-docker#1045]
##### SUMMARY
When using the zabbix-web-nginx-pgsql alpine based image there is a noticeable delay in statistics rendering/loading in the UI.  When using the ubuntu based image the noticeable delay is not there.

##### OS / ENVIRONMENT / Used docker-compose files
Version 6.2.6 alpine and 6.2.6 ubuntu running in a k3s cluster

##### CONFIGURATION

- PGSQL (15.1) also runs in a container with iSCSI backed persistent volume
- CPU Limits on the deployment 256m CPU, 500m Memory

##### STEPS TO REPRODUCE
Deploy the alpine based image, load the web UI
Deploy the ubuntu based image, load the web UI

##### EXPECTED RESULTS
I expect the stat rendering/loading time to be the same as the ubuntu based image

##### ACTUAL RESULTS
When using the alpine based image the stat loading time is a couple of seconds slower (which is a noticeable difference).

**Comment by dotneft** [comment]
What kind of delay? Please explain with a bit more information.

**Comment by UntestedEngineer** [comment]
When the web page loads all the data that is populated from the backend database query takes longer to load when using the Alpine docker image.

For example here is a snippet of my dashboard:
![image](https://user-images.githubusercontent.com/106830292/218540217-18394849-d963-4645-9df1-bea3291643ad.png)

All of that data takes a few seconds longer to load when using the Alpine docker image.  Using the Ubuntu docker image there are no issues.  The backend PGSQL database is also in a container mounted from iSCSi persistent storage for block level access.

**Comment by kernbug** [comment]
Frontend supports Debug output with load time for SQL/page rendering for comparison, not like "i feel it's slow".  Put user in a Debug user group and show Debug for the same page from both images type. 
https://www.zabbix.com/documentation/current/en/manual/web_interface/debug_mode

Or use web browser Developer tools can be used to see the difference.
