### ISSUE TITLE
Failed to accept an incoming connection: connection from "9.42.x.x" rejected, allowed hosts: "zabbix-server"

### ISSUE THREAD

**Issue by reshamchaney** [zabbix/zabbix-docker#1046]
##### SUMMARY

I have installed zabbix on OpenShift cluster. I am trying to monitor a host(vm) outside the cluster but the zabbix server is unable to connect to it. In the `/etc/zabbix/zabbix_agentd.conf` file I have mentioned the DNS name of the server `zabbix-server` but it looks like there server is trying to connect through a different public IP.  I am not sure what this IP is. I need your help in understanding that.

##### OS / ENVIRONMENT / Used docker-compose files

I applied the kubernetes.yaml file present in this repo - https://github.com/zabbix/zabbix-docker/blob/6.2/kubernetes.yaml - on an OpenShift cluster.

##### CONFIGURATION

In the `/etc/zabbix/zabbix_agentd.conf` file `Server=zabbix-server`. 

##### STEPS TO REPRODUCE

Apply the kubernetes.yaml file on Openshift cluster and try to monitor any external vm.

##### EXPECTED RESULTS

The zabbix server should be able to connect to the vm.

##### ACTUAL RESULTS

Zabbix server logs.
```[root@api.ftm-garuda-dev.cp.fyre.ibm.com ~]# oc logs zabbix-server-647cbf66c7-r222h | grep Host
Defaulted container "zabbix-server" out of: zabbix-server, zabbix-snmptraps
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBHost": 'mysql-server'...added
   287:20230120:060843.131 Zabbix agent item "system.cpu.load[all,avg5]" on host "Host-C" failed: first network error, wait for 15 seconds
   289:20230120:060858.592 Zabbix agent item "system.cpu.num" on host "Host-C" failed: another network error, wait for 15 seconds
   289:20230120:060913.843 Zabbix agent item "system.sw.arch" on host "Host-C" failed: another network error, wait for 15 seconds
   289:20230120:060929.095 temporarily disabling Zabbix agent checks on host "Host-C": interface unavailable
```

Logs from the agent installed on the vm.

```paste below
350446:20230122:103232.230 failed to accept an incoming connection: connection from "9.42.x.x" rejected, allowed hosts: "zabbix-server"
350444:20230122:103332.525 failed to accept an incoming connection: connection from "9.42.x.x" rejected, allowed hosts: "zabbix-server"
350445:20230122:103432.819 failed to accept an incoming connection: connection from "9.42.x.x" rejected, allowed hosts: "zabbix-server"
350446:20230122:103533.114 failed to accept an incoming connection: connection from "9.42.x.x" rejected, allowed hosts: "zabbix-server"
```

**Comment by dotneft** [comment]
The last part of error messages from the agent completely transparently says what is the problem and where from Zabbix tries to connect :-)

**Comment by reshamchaney** [comment]
If I add this IP in `/etc/zabbix/zabbix_agentd.conf` it will work. Agreed! But what IP is this? Is this a service? Or any node/pod IP? It keeps on changing. Everytime I cannot change this id in the conf file. I need something stable.
```
350445:20230122:095723.815 failed to accept an incoming connection: connection from "9.42.106.212" rejected, allowed hosts: "zabbix-server"
350446:20230122:095824.139 failed to accept an incoming connection: connection from "9.42.106.212" rejected, allowed hosts: "zabbix-server"
350445:20230122:095924.369 failed to accept an incoming connection: connection from "9.42.106.212" rejected, allowed hosts: "zabbix-server"
350446:20230122:100024.605 failed to accept an incoming connection: connection from "9.42.106.212" rejected, allowed hosts: "zabbix-server"
350446:20230122:100124.797 failed to accept an incoming connection: connection from "9.42.106.212" rejected, allowed hosts: "zabbix-server"
350445:20230122:100225.094 failed to accept an incoming connection: connection from "9.42.106.217" rejected, allowed hosts: "zabbix-server"
350444:20230122:100325.384 failed to accept an incoming connection: connection from "9.42.106.210" rejected, allowed hosts: "zabbix-server"
350444:20230122:100425.620 failed to accept an incoming connection: connection from "9.42.106.210" rejected, allowed hosts: "zabbix-server"
350446:20230122:100525.835 failed to accept an incoming connection: connection from "9.42.106.219" rejected, allowed hosts: "zabbix-server"
350446:20230122:100626.135 failed to accept an incoming connection: connection from "9.42.106.210" rejected, allowed hosts: "zabbix-server"
350444:20230122:100726.455 failed to accept an incoming connection: connection from "9.42.106.219" rejected, allowed hosts: "zabbix-server"
350445:20230122:100826.772 failed to accept an incoming connection: connection from "9.42.106.219" rejected, allowed hosts: "zabbix-server"
350446:20230122:100927.050 failed to accept an incoming connection: connection from "9.42.106.219" rejected, allowed hosts: "zabbix-server"
350446:20230122:101027.366 failed to accept an incoming connection: connection from "9.42.106.210" rejected, allowed hosts: "zabbix-server"
350445:20230122:101127.683 failed to accept an incoming connection: connection from "9.42.106.210" rejected, allowed hosts: "zabbix-server"
350444:20230122:101227.981 failed to accept an incoming connection: connection from "9.42.106.210" rejected, allowed hosts: "zabbix-server"
350446:20230122:101328.293 failed to accept an incoming connection: connection from "9.42.106.210" rejected, allowed hosts: "zabbix-server"
350446:20230122:101428.612 failed to accept an incoming connection: connection from "9.42.106.219" rejected, allowed hosts: "zabbix-server"
350445:20230122:101528.907 failed to accept an incoming connection: connection from "9.42.106.219" rejected, allowed hosts: "zabbix-server"
```

**Comment by dotneft** [comment]
I do not know what is the IP. It is your infrastructure. Maybe you have load balancer...

**Comment by reshamchaney** [comment]
No. I do not have any load balancer.

**Comment by clembIsEnder** [comment]
Heyy @dotneft,
I have the same problem.. (I think)
I want to run a strings store on my Zabbix agent. And the trigger is directly on Zabbix web.

> 72103:20240307:144604.200 agent #5 started [active checks #1]
>  72103:20240307:144604.203 Unable to connect to [.21]:10051 [cannot connect to [[.21]:10051]: [113] No route to host]
>  72103:20240307:144604.204 Unable to send heartbeat message to [.21]:10051 [cannot connect to [[.21]:10051]: [113] No route to host]
>  72103:20240307:144604.206 Unable to connect to [.21]:10051 [cannot connect to [[.21]:10051]: [113] No route to host]
>  72103:20240307:144604.207 Active check configuration update started to fail
>  72102:20240307:145045.799 failed to accept an incoming connection: connection from ".90" rejected, allowed hosts: "10.129.102.21"
>  72102:20240307:145344.605 Executing command 'sudo -u lmtest /etc/zabbix/zabbix_shells/start_all_lmxt.ksh'

.90 = This is my old Zabbix server (which I no longer use and I have in no case put its IP address in my new configurations)
.21 = This is my new Zabbix server
The logs come from my Zabbix agent (.27)

In the last line, we see that he is launching himself. But in fact, it is like "blocked" and cannot launch this and therefore cannot restart my tasks
>  72102:20240307:145344.605 Executing command 'sudo -u lmtest /etc/zabbix/zabbix_shells/start_all_lmxt.ksh'

If someone has an idea
ty
