### ISSUE TITLE
Unable to Run Official Zabbix Server Docker Container

### ISSUE THREAD

**Issue by opulasli414** [zabbix/zabbix-docker#1048]
I am trying to run official Zabbix server container in my kubernetes environment. Zabbix frontend runs smoothly but I am facing with issues on Zabbix server. I am running the container with below environment variables. I am sure that these values are correct because I am also using them in my Zabbix frontend container.
- MYSQL_USER
- MYSQL_DATABASE
- MYSQL_PASSWORD
- DB_SERVER_HOST

When I inject the Zabbix server container into kubernetes, the container is failing due to "CrashLoopBackOff" error in kubernetes. When I check the logs of the failed container, it's like below.

zabbix_server [7]: cannot initialize IPC services: Failed to stat the specified path "/run/zabbix": [2] No such file or directory.

I could not be able to solve it. Also I could not find much content on internet about this issue. I'd be glad if you can make some suggestions about it.

**Comment by dotneft** [comment]
What version do you use?

**Comment by opulasli414** [comment]
@dotneft , this issue is resolved. I was using the latest version but it was from 2 weeks ago from now on. I started to use the latest version (which is released latest) and the issue resolved.
