### ISSUE TITLE
[doc] Explain how to run zabbix-agent with docker compose examples

### ISSUE THREAD

**Issue by weakcamel** [zabbix/zabbix-docker#1050]
##### SUMMARY

The docker-compose examples provided in this repository are very helpful to deploy a Zabbix container set yet are also quite complex. It's not quite clear how they're supposed to be used which - I believe - causes people to ask how to launch a zabbix agent, e.g.

* https://github.com/zabbix/zabbix-docker/issues/850
* https://github.com/zabbix/zabbix-docker/issues/889

It would be great to have it mentioned either in https://github.com/zabbix/zabbix-docker/blob/6.2/README.md or at least as comments inside the docker-compose files.

##### OS / ENVIRONMENT / Used docker-compose files

6.2.6 templates

##### STEPS TO REPRODUCE

n/a

##### EXPECTED RESULTS
n/a

##### ACTUAL RESULTS

n/a

**Comment by dotneft** [comment]
Sorry, what kind of comments do you want?

**Comment by weakcamel** [comment]
A note in the section of README mentioning templates would IMO be useful, e.g.:

> Templates support several [Compose  profiles](https://docs.docker.com/compose/profiles/). Minimal set of services is brought up by default, to start additional components e.g. Zabbix Agent use profile 'full' or 'all'.

**Comment by dotneft** [comment]
These compose files are prepared as example how components are related. So, it is not a good idea to use them in production and without check the listing. Minimal set is completely good for most of cases of tests.

**Comment by weakcamel** [comment]
Those templates are quite complex and it would be really helpful to have at least a bit of a hint to help people understand them, no matter how they're going to use them eventually.

> So, it is not a good idea to use them in production and without check the listing. 

So maybe that should be part of the readme too? How are people supposed to know that if it's not documented?

I did read them and working out relationship of the services was quite cumbersome, especially that e.g. Ubuntu+Postgres+Nginx template includes also MySQL and Apache services for no sensible reason whatsoever.

> Minimal set is completely good for most of cases of tests.

And yet, this question about Zabbix Agent keeps coming back as an issue which means
* maintainers will be wasting time answering that frequent question
* end users get frustrated by the lack of clear documentation and for some of them it's quite likely they'll just look at another monitoring solutions.

**Comment by dotneft** [comment]
I added asked information, but it is quite standard usage of compose files. If you want to start something just start it:
```
docker compose -f compose.yaml up -d zabbix-agent
```
You can do that without profiles at all.

**Comment by carlsue** [comment]
execute docker-compose with --profile=full or --profile=all.

or

delete profile
