### ISSUE TITLE
Reports -> Action log not working

### ISSUE THREAD

**Issue by Max4025** [zabbix/zabbix-docker#1051]
##### SUMMARY

Most functions works fine for me, but there is no action log even if I do executed some remote commands.
![Snipaste_2023-01-30_14-37-28](https://user-images.githubusercontent.com/22543057/215406400-f1061608-0c37-4464-8da8-5a63bf8f9988.png)

##### OS / ENVIRONMENT / Used docker-compose files

System: Centos 7.5.1804
Docker version 20.10.2 and docker-compose version v2.11.2
Using template: docker-compose_v3_centos_mysql_local.yaml

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
Could you show an example screenshot with executed action today?

**Comment by dotneft** [comment]
what zabbix version do you have?

**Comment by Max4025** [comment]
Sorry, It's Zabbix 5.0.28 and zabbix-agent 4.0.44 on some older servers.
Just executed a global script, such as Ping or Traceroute, I do recalled that this will be recorded in Zabbix 4.0.x
![Snipaste_2023-01-30_15-01-57 (1)](https://user-images.githubusercontent.com/22543057/215409893-4a97858f-362e-4712-b306-5b6dc9550bf8.png)

**Comment by dotneft** [comment]
If you execute it manually it is not added to action log. Because action log is log for actions only.

**Comment by Max4025** [comment]
Okay, I see...
Is Autoregistration action will be recorded? All of my agents added by auto registration yet there is no action log.

**Comment by dotneft** [comment]
Please check our official documentation about what exactly is recorded: https://www.zabbix.com/documentation/current/en/manual/web_interface/frontend_sections/reports/action_log
```
details of operations (notifications, remote commands) executed within an action
```
