### ISSUE TITLE
Zabbix Docker Container on Kubernetes HealthCheck Issue

### ISSUE THREAD

**Issue by opulasli414** [zabbix/zabbix-docker#1052]
I am using official Zabbix server (mysql) docker container in Kubernetes. It's exposed via AWS Ingress resource. The AWS Application Load Balancer sends healthcheck requests to Zabbix server pods. I have tried the 10051 and "/" path as healthcheck but it did not work. Could you please tell me which path is used for healthcheck in Zabbix server containers?

**Comment by dotneft** [comment]
Try to use TCP check.

**Comment by opulasli414** [comment]
Hi @dotneft , we are using TCP healthcheck on Kubernetes but it's not possible to use TCP healthchecks in AWS Application Load Balancer. Only HTTP and HTTPS methods are allowed for healthchecks in AWS ALB. That's why I am looking for a path to use as whitelist path.

**Comment by dotneft** [comment]
In this case AWS ALB is not correct way for Zabbix server. Check another.

**Comment by dotneft** [comment]
In this case AWS ALB is not correct way for Zabbix server. Check another.
