### ISSUE TITLE
unable to run docker compose zabbix yaml files

### ISSUE THREAD

**Issue by ayubwaheed** [zabbix/zabbix-docker#1053]
vagrant@ubuntu-focal:~$ docker compose version
**Docker Compose version v2.15.1**
vagrant@ubuntu-focal:~$ ls
Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos  zabbix-docker
vagrant@ubuntu-focal:~$ cd zabbix-docker/
vagrant@ubuntu-focal:~/zabbix-docker$ ls
Dockerfiles  build.sh                                    docker-compose_v3_alpine_pgsql_local.yaml   docker-compose_v3_centos_pgsql_local.yaml  docker-compose_v3_ol_pgsql_local.yaml       docker-compose_v3_ubuntu_pgsql_local.yaml
LICENSE      docker-compose_v3_alpine_mysql_latest.yaml  docker-compose_v3_centos_mysql_latest.yaml  docker-compose_v3_ol_mysql_latest.yaml     docker-compose_v3_ubuntu_mysql_latest.yaml  env_vars
README.md    docker-compose_v3_alpine_mysql_local.yaml   docker-compose_v3_centos_mysql_local.yaml   docker-compose_v3_ol_mysql_local.yaml      docker-compose_v3_ubuntu_mysql_local.yaml   kubernetes.yaml
build.json   docker-compose_v3_alpine_pgsql_latest.yaml  docker-compose_v3_centos_pgsql_latest.yaml  docker-compose_v3_ol_pgsql_latest.yaml     docker-compose_v3_ubuntu_pgsql_latest.yaml
vagrant@ubuntu-focal:~/zabbix-docker$ **docker-compose -f docker-compose_v3_ubuntu_mysql_latest.yaml up -d**
ERROR: The Compose file './docker-compose_v3_ubuntu_mysql_latest.yaml' is invalid because:
Unsupported config option for services.zabbix-agent: 'profiles'
Unsupported config option for services.zabbix-java-gateway: 'profiles'
Unsupported config option for services.zabbix-proxy-mysql: 'profiles'
Unsupported config option for services.zabbix-proxy-sqlite3: 'profiles'
Unsupported config option for services.zabbix-snmptraps: 'profiles'
Unsupported config option for services.zabbix-web-apache-mysql: 'profiles'
Unsupported config option for services.zabbix-web-service: 'profiles'

![docker -compose](https://user-images.githubusercontent.com/91366401/215910170-8b46b25e-1b1c-46df-a978-cbc65d07d127.PNG)

**Comment by dotneft** [comment]
docker compose version
while you execute docker-compose...
anyway... I checked 2.15.1 version, it does not have such errors.

**Comment by kernbug** [comment]
Follow: https://docs.docker.com/compose/install/linux/ to install: 'docker-compose-plugin'. 
After install: https://github.com/docker/compose-switch if you want continue to use old style docker-compose invocation.

Old docker-compose (v1) will not work  with new docker compose plugin architecture. 

Or execute docker compose (v2) in a correct way: https://docs.docker.com/compose/features-uses/.
