### ISSUE TITLE
Unable to Run Multiple Zabbix Server Containers in Kubernetes

### ISSUE THREAD

**Issue by opulasli414** [zabbix/zabbix-docker#1055]
I am unable to launch multiple Zabbix server containers in Kubernetes. Only one server container is running without an issue but the rest is failing with "CrashLoopBackOff" error in Kubernetes. This is happening because of the HA configuration in Zabbix Server container. I can see that I can set the below values for HA. I tried both of the allowed values but it did not work. Could you please comment on this issue if you are using multiple Zabbix containers in Kubernetes?

ZBX_AUTOHANODENAME=fqdn # Allowed values: fqdn, hostname. Available since 6.0.0

**Comment by dotneft** [comment]
any logs?

**Comment by opulasli414** [comment]
Here is the log lines where issue has started:

   198:20230202:132526.360 [Z3001] connection to database 'zabbixdb' failed: [1040] Too many connections
   198:20230202:132526.360 Cannot connect to the database. Exiting...
   201:20230202:132526.361 [Z3001] connection to database 'zabbixdb' failed: [1040] Too many connections
   201:20230202:132526.361 Cannot connect to the database. Exiting...
   182:20230202:132526.362 HA manager has been paused
   211:20230202:132526.363 server #29 started [poller #4]
   197:20230202:132526.363 [Z3001] connection to database 'zabbixdb' failed: [1040] Too many connections
   197:20230202:132526.363 Cannot connect to the database. Exiting...
   187:20230202:132526.365 cannot read alert manager service request
   186:20230202:132526.366 cannot read alert manager service request
   188:20230202:132526.366 cannot read alert manager service request
   213:20230202:132526.367 server #31 started [unreachable poller #1]
   191:20230202:132526.369 cannot read preprocessing service request
   194:20230202:132526.370 cannot read LLD manager service request
   214:20230202:132526.371 server #32 started [trapper #1]
   212:20230202:132526.372 server #30 started [poller #5]
     6:20230202:132526.456 syncing trend data...
     6:20230202:132526.456 syncing trend data done
   182:20230202:132526.476 HA manager has been stopped
     6:20230202:132526.477 Zabbix Server stopped. Zabbix 6.2.6 (revision 6981d8b).

**Comment by dotneft** [comment]
I think the error is quite clear :-)

**Comment by opulasli414** [comment]
Error is clear but I could not find the solution online :) even if I add the variable related to the HANODENAME, it does not work. Anyway, thanks @dotneft

**Comment by dotneft** [comment]
the problem is not related to HA, you need increase max amount of connections for DB.

**Comment by opulasli414** [comment]
here are the further logs. I also increased the DB size but it did not help. It's about HANodeName configuration.

 7:20230202:160825.561 HA manager error: multiple servers have been started without configuring "HANodeName" parameter
   183:20230202:160825.574 HA manager has been stopped
     7:20230202:160825.575 Zabbix Server stopped. Zabbix 6.2.6 (revision 6981d8b).

**Comment by dotneft** [comment]
ZBX_AUTOHANODENAME=fqdn
ZBX_AUTONODEADDRESS=fqdn
must be enough
