### ISSUE TITLE
Zabbix Server Listener not working on IP Address from server - Only works on Docker Network.

### ISSUE THREAD

**Issue by HorselessName** [zabbix/zabbix-docker#1058]
##### SUMMARY

I am running a _Zabbix Server_ container, but I am not being able to communicate on its listening port - Locally even.

##### OS / ENVIRONMENT / Used docker-compose files
This is the command I am currently using to run it:

```
docker run -d --name zabbix-server \
 --restart always \
 --link zabbix-snmptraper:zabbix-snmptraps --volumes-from zabbix-snmptraper \
 -p 192.168.1.248:10052:10051 \
 -e MYSQL_DATABASE="zabbix" \
 -e MYSQL_USER="zabbix" \
 -e MYSQL_PASSWORD="aro@123" \
 -e ZBX_LISTENPORT=10052 \
 -e ZBX_HOUSEKEEPINGFREQUENCY=12 \
 -e ZBX_LOGSLOWQUERIES=1000 \
 -e ZBX_STARTPOLLERSUNREACHABLE=1 \
 -e ZBX_STARTPINGERS=5 \
 -e ZBX_STARTTRAPPERS=1 \
 -e ZBX_STARTDBSYNCERS=3 \
 -e ZBX_STARTDISCOVERERS=4 \
 -e ZBX_STARTPOLLERS=10 \
 -e ZBX_TIMEOUT=30 \
 -e ZBX_VALUECACHESIZE=32M \
 -e ZBX_CACHESIZE=48M \
 -e ZBX_MAXHOUSEKEEPERDELETE=432000 \
 -e ZBX_ENABLE_SNMP_TRAPS=true \
 -e MYSQL_ROOT_PASSWORD="my_root_pass_of_mysql..." \
 -e DB_SERVER_HOST="mysql-server" \
 -e DB_SERVER_PORT="3306" \
 -v /etc/localtime:/etc/localtime:ro \
 -v /mnt/dados/zabbix/external_scripts:/usr/lib/zabbix/externalscripts \
--network=zabbix-net \
zabbix/zabbix-server-mysql:5.4-ubuntu-latest
```

##### CONFIGURATION
This is being run on a Debian 11.

##### STEPS TO REPRODUCE
Basically, the container is UP and running.
The passive queries are all working - I can gather data from Zabbix to other Zabbix Agents.
The problem happens when I try to do a query from outside to Zabbix Server itself... (Active queries.)

My deduction was that the docker container did not create the necessary routes for this, so I must specify something or there is some configuration missing.

##### EXPECTED RESULTS
When doing a telnet to 10052 on my Zabbix Server, the expected result is a OK Connected.

##### ACTUAL RESULTS
Locally, on my own Zabbix Server, when I did:
sudo telnet 192.168.1.248 10052

I got `telnet: Unable to connect to remote host: Connection refused`

Crazy thing is that when doing this on the IP address of the DOCKER NETWORK, from `docker inspect zabbix-server` "IPAddress": "172.18.0.4":

`sudo telnet 172.18.0.4 10052`

Trying 172.18.0.4...
Connected to 172.18.0.4.

It worked. So there is a routing problem with this container.
But most containers when running create the rules or at least show it in logs or docs. how to do it.
But I could not find this anywhere...

Can you please help me?

**Comment by spyhunter493** [comment]
I'm going to assume that because your specifying an IP address on the host side you have correctly set up the network interface on the host?

with that log message:

> telnet: Unable to connect to remote host: Connection refused

The connection is being refused, which would indicate a firewall refusing the connection, vs a routing problem or the service not listening, being NORMALLY a timeout error.

if you run this on your host `netstat -anop | grep 10052` and see something like : LISTEN /docker-proxy means the problem is the host firewall, if you don't get any output then the problem is within docker.

you could also test by `docker port zabbix-server ` if you see some thing like:   10051->192.168.1.248:10052  then docker has mapped the ports correctly and the problem is the host interface, i which case i suggest looking there, can't be much more help with out more detail on your host setup.

**Comment by randallflores** [comment]
Was there any resolution on this?

I'm seeing the same problem. there is no output using the netstat command listed above by @spyhuntergenral
docker port command does show the expected ports to be exposed as exposed.

Initially, I was using docker-compose, but then I thought I was doing something wrong, so I used the listed run command on the docker hub page for zabbix/zabbix-appliance. 

That run command is: 
- `docker run --name some-zabbix-appliance -p 80:80 -p 10051:10051 -d zabbix/zabbix-appliance:tag` 
- I am using the `centos-3.0-latest` tag

While on the docker host, I run docker inspect against the zabbix container and I see the IP assigned is 172.17.0.3.
If I ping this address, I do get a response
if I try to telnet over 10052 or port 80, I get "telnet: Unable to connect to remote host: Connection refused"

![image](https://user-images.githubusercontent.com/31718948/227276646-183bb123-59ea-435f-b54c-e5b72dd1d8c6.png)
![image](https://user-images.githubusercontent.com/31718948/227276864-81352fde-0786-46b0-bea8-10e29b5f50e0.png)
![image](https://user-images.githubusercontent.com/31718948/227276970-b9dc62a6-19af-4d61-b7cf-4b1c4667fef6.png)

**Comment by dotneft** [comment]
You have 10051 port, not 10052. Also appliance is quite long time is not supported. I recommend you migrate from the solution all-in-one.
