### ISSUE TITLE
SAML SSO

### ISSUE THREAD

**Issue by RonV666** [zabbix/zabbix-docker#1059]
Is it possible to use SAML for SSO with this docker build (zabbix/zabbix-server-mysql      alpine-6.2-latest )? I am trying to figure out where and how I can specify the certificates for the saml provider and im not sure how to proceed or how to configure the docker to read them on startup.

**Comment by RonV666** [comment]
nevermind, delete

**Comment by bmcgonag** [comment]
@RonV666  did you find something specific in the documentation that helped you with this?  Having the same question.  I have the certs on the server in the container, but not sure how to tell it where to look for them.
