### ISSUE TITLE
Zabbix agent read values wrong

### ISSUE THREAD

**Issue by geostant** [zabbix/zabbix-docker#106]
It seems that the agent inside the docker report wrong values,
seems that all the values are wrong.

In particular - disk space, memory, average load

**Comment by dotneft** [comment]
Did you use privileged mode + share /proc?

**Comment by geostant** [comment]
privileged yes,
proc... no :)

**Comment by geostant** [comment]
found out that the container mount point is /data/proc
so I've mounted /proc /dev /sys
to /data/proc /data/dev /data/sys
yet... I can see only a single CPU meterics

I'm running now stress test on 10 CPUs (out of 32), on TOP APP I can see load average of 10
while in zabbix server shows just 0.2 (probably a single CPU which isn't under stress)

**Comment by geostant** [comment]
Seems that zabbix divide the load average by the number of CPUs
current last minute load average shows 9.88 while zabbix shows 0.29 (we got 32 cores machine)

Since I'm using a template,
is there a way to override it and multiple it back by the number of CPUs ?

**Comment by dotneft** [comment]
Not sure, it depends on item you use. Please try to check Zabbix agent on host system. Do you see the same measurements?
