### ISSUE TITLE
zabbix-server image MIB error

### ISSUE THREAD

**Issue by weakcamel** [zabbix/zabbix-docker#1061]
##### SUMMARY

Zabbix-server image 6.2.7 (and 6.2.6) in default SNMP configuration include upstream Ubuntu mibs.

One of them is malformed, causing logs to be polluted with error messages

```
root@zabbix:/opt/zabbix_server# docker-compose logs | grep INTEGER | tail
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
```

I understand that this is a known issue with Ubuntu MIBs: https://serverfault.com/questions/936119/snmp-mibs-on-ubuntu-error-in-mibs which isn't a Zabbix problem per se, however the extra noise in logs makes it harder to troubleshoot actual problems.

Edit: Removed the suggestion to fix by re-running `download-mibs` as it turned out not to be effective.

##### CONFIGURATION

https://github.com/zabbix/zabbix-docker/blob/6.2/docker-compose_v3_ubuntu_pgsql_latest.yaml

##### STEPS TO REPRODUCE

Just start the image with SNMP enabled.

##### EXPECTED RESULTS

no SNMP errors

##### ACTUAL RESULTS

```
root@zabbix:/opt/zabbix_server# docker-compose logs   | grep INTEGER | tail
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
zabbix_server-zabbix-server-1           | Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
```

**Comment by weakcamel** [comment]
For the record - my attempt to run `download-mibs` didn't fix the problems. The MIB in question would need to be patched apparently, e.g. with the unofficial fix https://docs.linuxconsulting.mn.it/notes/net-snmp-errors

**Comment by dotneft** [comment]
Sorry, it is better to use only official packages. if you would like you can extend the image and add your own MIB files.

**Comment by weakcamel** [comment]
> Sorry, it is better to use only official packages.

By installing and running `download-mibs` in Dockerfile the MIBs are already patched - they're not the same as installed by official packages anyway. The problem is that they come with syntax error anyway.

Fair enought though, I fixed it on my end by bind-mounting the fixed file. I just thought you'd be interested in improving Zabbix user/admin experience -  all those errors reflect badly on Zabbix project (even if it is not to blame for those errors) - apparently I was wrong.

**Comment by dotneft** [comment]
It is known problem with Ubuntu. Feel free to use any other image variant. We can not use non-official methods very long time known problem to solve them. Ubuntu image is not only one :-)
