### ISSUE TITLE
Unable to assign custom group to LDAP user

### ISSUE THREAD

**Issue by phinzin** [zabbix/zabbix-docker#1063]
##### SUMMARY

Hi Team, i am very interested in LDAP authentication features
Just one doubt, how do i assign group / roles to an authenticated LDAP user manually.

##### OS / ENVIRONMENT / Used docker-compose files

yaml file: docker-compose_v3_alpine_mysql_latest.yaml
zabbix docker compose version: 6.4

##### STEPS TO REPRODUCE

Configure LDAP authentication & enable JIT
by default, who ever authenticated via LDAP will be assigned to Internal Group.

login with an LDAP account (e.g user1).
logout
login with Admin account
Create new Group (e.g: Group B). and assign user1 to Group B
logout Admin 
login user1
logout user1 -> login with Admin and verify group B 's membership

```yaml

```

##### EXPECTED RESULTS

Group B should have 1 member is user1
##### ACTUAL RESULTS

No members in Group B & user1 's group is reset to Internal

```paste below

```

**Comment by dotneft** [comment]
Sorry, but how is it related to container images?

**Comment by dimir** [comment]
Did you check [Documentation](https://www.zabbix.com/documentation/current/en/manual/web_interface/frontend_sections/users/authentication/ldap)?
