### ISSUE TITLE
SenderFrequency deprecation

### ISSUE THREAD

**Issue by signatev** [zabbix/zabbix-docker#1064]
##### SUMMARY
README.md of server container in section "Other variables" contains ZBX_SENDERFREQUENCY which 
corresponds to SenderFrequency that was removed from configuration in [3.4.0](https://www.zabbix.com/documentation/3.4/en/manual/installation/upgrade_notes_340?hl=SenderFrequency)

##### OS / ENVIRONMENT / Used docker-compose files
Any server container

##### EXPECTED RESULTS
Please remove this variable and config option from any docker-entrypoints and readme files

##### ACTUAL RESULTS
There is no effect if this variable exists in docker-compose file or in docker run options. Everytime container runs it says "_Updating '/etc/zabbix/zabbix_server.conf' parameter "SenderFrequency": ''...removed_"

**Comment by dotneft** [comment]
Thank you! Fixed.
