### ISSUE TITLE
Cannot fetch data [Zabbix 6.4]

### ISSUE THREAD

**Issue by paborita** [zabbix/zabbix-docker#1067]
I am geting this error when i try to configure the ceph in zabbix 

 failed to execute direct exporter task for key 'ceph.df.details["https://localhost:8003","zabbix","zabbix_pass"]' error: 'Cannot fetch data: Post "https://zabbix:***@localhost:8003/request?wait=1": http: server gave HTTP response to HTTPS client.'

Changing localhost to ip address and also using its dns name still getting the same error: 

- failed to execute direct exporter task for key 'ceph.status["https://localhost:8003","zabbix","zabbix_pass"]' error: 'Cannot fetch data: Post "https://zabbix:***@localhost:8003/request?wait=1": http: server gave HTTP response to HTTPS client.'

- sending passive check response: ZBX_NOTSUPPORTED: 'Cannot fetch data: Post "https://zabbix:***@localhost:8003/request?wait=1": http: server gave HTTP response to HTTPS client.' to 'xxx.xxx.xxx.xxx -zabbix server ip.'

**Comment by dotneft** [comment]
Please be advised that this section of the tracker is for reports related to Docker images only. You can use our IRC channel or community forum ([https://www.zabbix.com/forum](https://www.zabbix.com//forum)) for assistance. With that said, we are closing this ticket. Thank you for understanding.

PS: The error is quite clear and tell you what is the problem.
