### ISSUE TITLE
Install on Synology NAS wtih Docker-Compose via Portainer

### ISSUE THREAD

**Issue by LorneCash** [zabbix/zabbix-docker#1070]
I would like to install Zabbix on my Synology NAS using Docker-Compose via Portainer but it looks really complicated.  I'm sure I coudld figure it out but it would be great if you would you please consider making a separate .yml for Synology NAS or provide instructions on how to modify one of the existing ones please.

**Comment by dotneft** [comment]
Sorry, but currently we do not have such feature in our roadmap and I do not think that we will do it for Synology. We already have a lot of compose files.
