### ISSUE TITLE
Add php-mcrypt to images

### ISSUE THREAD

**Issue by Aleksandr1705** [zabbix/zabbix-docker#1071]
##### EXPECTED RESULTS
To sign and encrypt SAML requests.

**Comment by dotneft** [comment]
do you have any example, is it missing currently?

**Comment by Aleksandr1705** [comment]
![image](https://user-images.githubusercontent.com/32997216/233317191-cff57da8-8a72-4f6b-9503-1f868eb07c95.png)

From 
https://github.com/SAML-Toolkits/php-saml

Dependencies
php >= 5.3.3 and some core extensions like php-xml, php-date, php-zlib.
openssl. Install the openssl library. It handles x509 certificates.
**mcrypt. Install that library and its php driver if you're going to handle encrypted data (nameID, assertions).**
gettext. Install that library and its php driver. It handles translations.
curl. Install that library and its php driver if you plan to use the IdP Metadata parser.

**Comment by dotneft** [comment]
I just worry about: https://www.php.net/manual/en/migration71.deprecated.php

**Comment by Aleksandr1705** [comment]
How we can use signed and encrypted requests in saml?

**Comment by dotneft** [comment]
what version of Zabbix frontend do you use?

**Comment by Aleksandr1705** [comment]
Sorry, our mistake. We used incorrect private key.

**Comment by dotneft** [comment]
Ok, thank you!
