### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to server on 'mysql-server' (115)

### ISSUE THREAD

**Issue by smarkm** [zabbix/zabbix-docker#1072]
Use `docker-compose_v3_alpine_mysql_latest.yaml` to start compose, `mysql-server` can not access from other containers. 
version: 6.4

1. from other container can ping `mysql-server`
2. from other container use mysql connect got error: `ERROR 2002 (HY000): Can't connect to server on 'mysql-server' (115)`
3. nc -z -h mysql-server 3306 failed
4. from `mysql-server` can connect self in local

Anyone facing the same issue？

**Comment by investlab** [comment]
Same issue.
Can't connect to Postgres server.

**Comment by smarkm** [comment]
> Same issue. Can't connect to Postgres server.

Getting a way to change the `internal: true` of the network `zbx_net_backend`  to false can resolve this issue. https://index.freecoop.net/Docker-Zabbix-dc38ae6045cc407fa3d06a7eb5ea6728
