### ISSUE TITLE
Unraid app install issue its starting the service before the sql is made"cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)"

### ISSUE THREAD

**Issue by AeroSouls** [zabbix/zabbix-docker#1073]
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HANodeName": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "NodeAddress": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "User": 'zabbix'...updated
Starting Zabbix Server. Zabbix 6.4.2 (revision 83c2f61).
Press Ctrl+C to exit.

     7:20230426:175525.987 Starting Zabbix Server. Zabbix 6.4.2 (revision 83c2f61).
     7:20230426:175525.987 ****** Enabled features ******
     7:20230426:175525.987 SNMP monitoring:           YES
     7:20230426:175525.987 IPMI monitoring:           YES
     7:20230426:175525.987 Web monitoring:            YES
     7:20230426:175525.987 VMware monitoring:         YES
     7:20230426:175525.987 SMTP authentication:       YES
     7:20230426:175525.987 ODBC:                      YES
     7:20230426:175525.987 SSH support:               YES
     7:20230426:175525.987 IPv6 support:              YES
     7:20230426:175525.987 TLS support:               YES
     7:20230426:175525.987 ******************************
     7:20230426:175525.987 using configuration file: /etc/zabbix/zabbix_server.conf
     7:20230426:175525.987 In zbx_load_modules()
     7:20230426:175525.987 End of zbx_load_modules():SUCCEED
     7:20230426:175525.987 In zbx_ipc_service_start() service:rtc
     7:20230426:175525.987 In zbx_ipc_socket_open()
     7:20230426:175525.987 End of zbx_ipc_socket_open():FAIL
     7:20230426:175525.987 End of zbx_ipc_service_start():SUCCEED
     7:20230426:175525.987 In zbx_db_get_database_type()
     7:20230426:175525.987 In zbx_db_connect() flag:0
     7:20230426:175525.990 End of zbx_db_connect():0
     7:20230426:175525.990 query [txnlev:0] [select userid from users limit 1]
     7:20230426:175525.994 no records in "users" table
     7:20230426:175525.994 End of zbx_db_get_database_type():ZBX_DB_PROXY
     7:20230426:175525.994 cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)

##### SUMMARY
 cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)

##### OS / ENVIRONMENT / Used docker-compose files
Unraid OS using app installer

##### CONFIGURATION
default plus database info and IP
https://i.imgur.com/CBfiSsv.png

##### STEPS TO REPRODUCE
Installing it at all.

I have set my docker live check to 120s I have set debug to 5 and still have the issues on install. 
I have dropped the DB many times made new ones and removed and reinstalled the app with no luck does it everytime

**Comment by dotneft** [comment]
db is broken, remove is and start again.

**Comment by AeroSouls** [comment]
> 

I have it does it every time

**Comment by AeroSouls** [comment]
Finally seem to maybe found a work around once its failed go back into setting using root access to sql add a 2 to the dbname it rebuilds but doesn't stop it that way it seems. Will let you know if this works fully or not
