### ISSUE TITLE
zbx_shmem_realloc(): out of memory (requested 16 bytes)

### ISSUE THREAD

**Issue by Hardylee18** [zabbix/zabbix-docker#1076]
Zabbix 6.2.7  “zbx_shmem_realloc(): out of memory (requested 16 bytes)” error message. Setting the environment variable “-e ZBX_CACHESIZE=‘4096M’” also does not allow the container to start.

**Comment by dotneft** [comment]
Full log please from the container with -e ZBX_CACHESIZE=4096M.

**Comment by Hardylee18** [comment]
Error log information：
     7:20230509:155747.855 Starting Zabbix Server. Zabbix 6.2.7 (revision d7e8df5).
     7:20230509:155747.855 ****** Enabled features ******
     7:20230509:155747.855 SNMP monitoring:           YES
     7:20230509:155747.855 IPMI monitoring:           YES
     7:20230509:155747.855 Web monitoring:            YES
     7:20230509:155747.855 VMware monitoring:         YES
     7:20230509:155747.855 SMTP authentication:       YES
     7:20230509:155747.855 ODBC:                      YES
     7:20230509:155747.855 SSH support:               YES
     7:20230509:155747.855 IPv6 support:              YES
     7:20230509:155747.855 TLS support:               YES
     7:20230509:155747.855 ******************************
     7:20230509:155747.855 using configuration file: /etc/zabbix/zabbix_server.conf
     7:20230509:155747.859 Zabbix supports only "utf8_bin,utf8mb3_bin,utf8mb4_bin" collation(s). Database "zabbix" has default collation "utf8mb3_unicode_ci"
     7:20230509:155747.864 character set name or collation name that is not supported by Zabbix found in 483 column(s) of database "zabbix"
     7:20230509:155747.864 only character set(s) "utf8,utf8mb3,utf8mb4" and corresponding collation(s) "utf8_bin,utf8mb3_bin,utf8mb4_bin" should be used in database
     7:20230509:155747.866 current database version (mandatory/optional): 06020000/06020014
     7:20230509:155747.866 required mandatory version: 06020000
   204:20230509:155747.874 starting HA manager
   204:20230509:155747.879 HA manager started in active mode
     7:20230509:155747.884 server #0 started [main process]
   205:20230509:155747.884 server #1 started [service manager #1]
   206:20230509:155747.884 server #2 started [configuration syncer #1]
   206:20230509:155748.261 __mem_malloc: skipped 0 asked 24 skip_min 18446744073709551615 skip_max 0
   206:20230509:155748.261 === memory statistics for configuration cache ===
   206:20230509:155748.261 min chunk size: 18446744073709551615 bytes
   206:20230509:155748.261 max chunk size:          0 bytes
   206:20230509:155748.261 memory of total size 29217312 bytes fragmented into 271047 chunks
   206:20230509:155748.261 of those,          0 bytes are in        0 free chunks
   206:20230509:155748.261 of those,   29217312 bytes are in   271047 used chunks
   206:20230509:155748.261 of those,    4336736 bytes are used by allocation overhead
   206:20230509:155748.261 ================================
   206:20230509:155748.261 backtrace is not available for this platform
   206:20230509:155748.261 [file:dbconfig.c,line:94] __zbx_shmem_realloc(): out of memory (requested 16 bytes)
   206:20230509:155748.261 [file:dbconfig.c,line:94] __zbx_shmem_realloc(): please increase CacheSize configuration parameter
     7:20230509:155748.268 One child process died (PID:206,exitcode/signal:1). Exiting ...
   204:20230509:155748.876 HA manager has been paused
   204:20230509:155748.902 HA manager has been stopped
     7:20230509:155748.903 Zabbix Server stopped. Zabbix 6.2.7 (revision d7e8df5).

Command to start the container：
	 -e ZBX_CACHESIZE=4096M \
	 -e ZBX_VMWARECACHESIZE=512M \
	 -e ZBX_HISTORYCACHESIZE=512M \
	 -e ZBX_HISTORYINDEXCACHESIZE=64M \
	 -e ZBX_TRENDCACHESIZE=64M \
	 -e ZBX_TRENDFUNCTIONCACHESIZE=64M \
	 -e ZBX_VALUECACHESIZE=64M \

**Comment by dotneft** [comment]
full please, with information about start section (where params are updating).

**Comment by Hardylee18** [comment]
Command to start the container：      
       docker run --name zabbix-server-mysql -t \
      -e DB_SERVER_HOST="mysql-server" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="******" \
      -e MYSQL_ROOT_PASSWORD="******" \
      -e ZBX_CACHESIZE=4096M \
      -e ZBX_VMWARECACHESIZE=512M \
      -e ZBX_HISTORYCACHESIZE=512M \
      -e ZBX_HISTORYINDEXCACHESIZE=64M \
      -e ZBX_TRENDCACHESIZE=64M \
      -e ZBX_TRENDFUNCTIONCACHESIZE=64M \
      -e ZBX_VALUECACHESIZE=64M \
      --link mysql-server:mysql \
      -p 10051:10051 \
      -v /etc/localtime:/etc/localtime:ro \
      -v /datas/docker/zabbix_server/alertscripts:/usr/lib/zabbix/alertscripts \
      -v /datas/docker/zabbix_server/externalscripts:/usr/lib/zabbix/externalscripts \
	 -v /datas/docker/zabbix_server/zabbix:/etc/zabbix \
      -d zabbix/zabbix-server-mysql:latest
Thank you.

**Comment by Hardylee18** [comment]
I removed the -v /datas/docker/zabbix_server/zabbix:/etc/zabbix command and it works fine.
Can you tell me which environment variable is in effect? Thanks!

**Comment by dotneft** [comment]
This one ZBX_CACHESIZE. I do not recommend you use volume /etc/zabbix. It contains Zabbix server configuration file.

**Comment by Hardylee18** [comment]
Thanks for the help, now it can start successfully
