### ISSUE TITLE
Error when build alpine image

### ISSUE THREAD

**Issue by GordymaJunior** [zabbix/zabbix-docker#1079]
##### SUMMARY
Using `docker-compose_v3_alpine_mysql_local.yaml`  branche 6.0 for build image.  
Error: `yaml: unmarshal errors:
  line 378: mapping key "deploy" already defined at line 364`
Worked when removed line 364, 365 in yaml.

##### OS / ENVIRONMENT / Used docker-compose files
Docker Compose version v2.17.2
Docker version 23.0.3, build 3e7cbfd
Ubuntu 22.04.1 LTS
docker-compose_v3_alpine_mysql_local.yaml

##### STEPS TO REPRODUCE

docker compose -f docker-compose_v3_alpine_mysql_local.yaml build zabbix-build-base

##### EXPECTED RESULTS

Build image. 

##### ACTUAL RESULTS

```yaml: unmarshal errors:
  line 378: mapping key "deploy" already defined at line 364
```

**Comment by dotneft** [comment]
Thank you! Will check it.

**Comment by dotneft** [comment]
Fixed!
