### ISSUE TITLE
Applicable for K8s?

### ISSUE THREAD

**Issue by alfista-sk** [zabbix/zabbix-docker#1083]
Hi,
I have only sone question or problems:

1. if I can use it for Kubernetes too, and if you have any manual how to install it there?
2. If you use with PGSQL also TimescaleDB
3. If you have thinked to add the Grafana too
4. And all to start in separate pods.

Thanks for help.

**Comment by kernbug** [comment]
Hello.

1. https://kubernetes.io/docs/tutorials/kubernetes-basics/
2. You can use TimescaleDB backend
3. Grafana has own images, out of scope
4. https://kubernetes.io/docs/tutorials/kubernetes-basics/

Please be advised that this section is for bug reports only. 

The case you have submitted can not be qualified as one.
