### ISSUE TITLE
/usr/sbin/fping: can't create socket (must run as root?)

### ISSUE THREAD

**Issue by Hativ** [zabbix/zabbix-docker#1084]
We're using the zabbix-proxy-sqlite3:alpine-6.0-latest docker image for linux/arm64 on a MikroTik router, using the container feature of RouterOS (7.9.1).

For simple icmpping checks we get the following error:
/usr/sbin/fping: can't create socket (must run as root?)

**Comment by dotneft** [comment]
Could you try to use NET_RAW capability? Or / and sysctl option "net.ipv4.ping_group_range = 0 2000"?

**Comment by Hativ** [comment]
Setting the capability is not possible:
```
bash-5.1# setcap cap_net_raw+ep /usr/sbin/fping
Failed to set capabilities on file '/usr/sbin/fping': Not supported
```

Error is gone after setting the sysctl option in the container:
```
sysctl -w "net.ipv4.ping_group_range=0 2000"
```

BUT Zabbix reports it as down. Pinging from the container principally works:
```
bash-5.1# fping 192.168.0.28 -s
192.168.0.28 is alive

       1 targets
       1 alive
       0 unreachable
       0 unknown addresses

       0 timeouts (waiting for response)
       1 ICMP Echos sent
       1 ICMP Echo Replies received
       0 other ICMP received

 0.546 ms (min round trip time)
 0.546 ms (avg round trip time)
 0.546 ms (max round trip time)
        0.001 sec (elapsed real time)
```

When executing fping as zabbix user (or any other user than root), the destination is unreachable:
```
bash-5.1# sudo -u zabbix fping 192.168.0.28 -s
192.168.0.28 is unreachable

       1 targets
       0 alive
       1 unreachable
       0 unknown addresses

       4 timeouts (waiting for response)
       4 ICMP Echos sent
       0 ICMP Echo Replies received
       0 other ICMP received

 0.000 ms (min round trip time)
 0.000 ms (avg round trip time)
 0.000 ms (max round trip time)
        4.067 sec (elapsed real time)
```

Any idea?

**Comment by dividerus** [comment]
Hello! Yes, issue is resolved after SUID set for /usr/sbin/fping inside the container. Use shell to the container and
#chmod u+s /usr/sbin/fping

After that, all worked well w/o any errors.

**Comment by mbirth** [comment]
@dotneft Any chance you could add `chmod u+s /usr/sbin/fping` to the server build scripts? This seems to remove the need for messing with the capabilities for me.

**Comment by Hativ** [comment]
`chmod u+s /usr/sbin/fping` solved it for me. But now I have to run it after every update. Therefore I would also like to see it integrated into the image, @dotneft.

**Comment by advorsky73** [comment]
same issue here... error after update

**Comment by dotneft** [comment]
Please describe your environment, user, groups, limitations, restrictions?

**Comment by advorsky73** [comment]
i am running zabbix/zabbix-server-mysql on unraid from the appstore. all default, no changes.
the issue started on 7.12.2024 after an upgrade as it seems.

**Comment by dotneft** [comment]
do you have such issue with all variants of images's OS?

**Comment by advorsky73** [comment]
what variations?

**Comment by dotneft** [comment]
alpine, centos, ol, rhel, ubuntu...

**Comment by advorsky73** [comment]
i am not running any variants. as i already stated i run the official image zabbix/zabbix-server-mysql deployed from the unraid appstore. The unraid version i am using is 6.12.13

**Comment by dotneft** [comment]
Each Zabbix image have multiple variants, including zabbix/zabbix-server-mysql.

**Comment by advorsky73** [comment]
That is ALL I see besides the env vars and mappings in Unraid:

Name: Zabbix-Server
Overview:
 Zabbix server is the central process of Zabbix software.
 The server performs the polling and trapping of data, it calculates triggers, sends notifications to users. It is the central 
 component to which Zabbix agents and proxies report data on availability and integrity of systems. The server can itself remotely 
 check networked services (such as web servers and mail servers) using simple service checks.
 ATTENTION: If you want to reload the configuration please type in your unRAID terminal: 'docker exec -ti 
 NAME_OF_YOUR_ZABBIXSERVERCONTAINTER zabbix_server -R config_cache_reload' (without quotes eg: docker exec -ti 
 Zabbix-Server zabbix_server -R config_cache_reload).
 VARIABLES: If you need other variables here is a complete list of all variables: https://hub.docker.com/r/zabbix/zabbix-server- 
 mysql
Additional Requirements: None Listed
Repository: zabbix/zabbix-server-mysql
Network Type: Host
Console shell command: Shell
Privileged: On

If you tell me how to determine more information for you, I am glad to comply ;)
Other than that my guess its the default if not specified otherwise...

**Comment by dotneft** [comment]
So you use Alpine variant. Please try different, tags for other variants are specified in the link https://hub.docker.com/r/zabbix/zabbix-server-mysql. Just be careful with version, when specify tag.

**Comment by advorsky73** [comment]
any recommendation? e.g. does exist an ubuntu-latest? ah found it. ubuntu-trunk. I will test that one.

**Comment by dotneft** [comment]
I recommend you check each variant of OS, just find one without fping issue...

**Comment by advorsky73** [comment]
it works on ubuntu-trunk. maybe you could fix the alpine one as well? as its the default?

**Comment by advorsky73** [comment]
I switched to ubuntu-latest to avoid daily updates and it still works.

**Comment by TyzzyT** [comment]
Same issue here, but not on MikroTik container but regular Docker implementation on a Debian based machines. Issue started with alpine docker container on December 5th. I switched to Ubuntu docker container and it's working again.

**Comment by dom6770** [comment]
Same for me. I used the image zabbix/zabbix-server-pgsql with no tags (so latest tag) and got this error. After switching tu ubuntu-latest it works again. Seems that the alpine image has this issue.

**Comment by gossamer2** [comment]
I'm using zabbix-server-mysql:latest and the problem exists here. The "chmod u+s /usr/sbin/fping" command temporarily fixes it until next version gets pushed.

**Comment by GavinTan** [comment]
This problem still exists with alpine-trunk and alpine-latest, don't alpine mirrors fix this anymore?

**Comment by dotneft** [comment]
Please check documentation: 
`Zabbix server has possibility to execute fping utility to perform ICMP checks. When containers are running in rootless mode or with specific restrictions environment, you may face errors related to fping: fping: Operation not permitted or lost all packets to all resources in this case add --cap-add=net_raw to docker run or podman run commands. Additionally fping executing in non-root environments can require sysctl modification: net.ipv4.ping_group_range=0 1995 where 1995 is zabbix GID.`

**Comment by GavinTan** [comment]
> 请检查文档： `Zabbix server has possibility to execute fping utility to perform ICMP checks. When containers are running in rootless mode or with specific restrictions environment, you may face errors related to fping: fping: Operation not permitted or lost all packets to all resources in this case add --cap-add=net_raw to docker run or podman run commands. Additionally fping executing in non-root environments can require sysctl modification: net.ipv4.ping_group_range=0 1995 where 1995 is zabbix GID.`
This only appears in the alpine image, the ubuntu-latest centos-latest image works fine, is this something to do with the container runtime environment?

**Comment by GavinTan** [comment]
> Please check documentation: `Zabbix server has possibility to execute fping utility to perform ICMP checks. When containers are running in rootless mode or with specific restrictions environment, you may face errors related to fping: fping: Operation not permitted or lost all packets to all resources in this case add --cap-add=net_raw to docker run or podman run commands. Additionally fping executing in non-root environments can require sysctl modification: net.ipv4.ping_group_range=0 1995 where 1995 is zabbix GID.`

This only appears in the alpine image, the ubuntu-latest centos-latest image works fine, is this something to do with the container runtime environment?

**Comment by dotneft** [comment]
In alpine container there are different ACL rules for the binary file by default.

**Comment by sahps** [comment]
Does this mean the alpine variant is not supported? The documentation to resolve fping doesn't work, and the real fix is to `chmod u+s /usr/sbin/fping`

I'd hope that Zabbix would update their Dockerfile for the base build to add this permission change. But until then we can use an in-line dockerfile to build our own fixed alpine variant.

Snippet of my docker-compose.yml

```
  zabbix-server:
    build:
      context: .
      dockerfile_inline: |
        FROM zabbix/zabbix-server-mysql:alpine-7.2-latest
        USER root
        RUN chmod u+s /usr/sbin/fping
        USER zabbix
    container_name: zabbix-server
```

This fixed all my ping checks

**Comment by osten33** [comment]
> I'd hope that Zabbix would update their Dockerfile for the base build to add this permission change

Surely this should be the way instead of having the workarounds in the documentation? Looks like something similar is already being done for nmap -> https://github.com/zabbix/zabbix-docker/blob/7.2/Dockerfiles/server-pgsql/ubuntu/Dockerfile#L96 
Does anyone have any good ideas on how to fix this when running in environments that don't allow privileged containers?

**Comment by rmaeder** [comment]
Just stumbled on the same issue, new installation, Debian 13, IPv6 disabled.
setting Fping6Location=
to nothing solves it. no need for suid binaries.
