### ISSUE TITLE
Cannot fetch data: Get "http://1.28/info": net/http: HTTP/1.x transport connection broken: malformed HTTP response

### ISSUE THREAD

**Issue by ITMPGIT** [zabbix/zabbix-docker#1085]
##### SUMMARY
Greetings, I am using the GCP compute engine environment with Google Container-Optimized OS (COS), I have the following problem when running a docker container with agent2 for monitoring

##### OS / ENVIRONMENT / Used docker-compose files
- on compute engine instance: Google Container-Optimized OS (COS)
- on container agent: zabbix/zabbix-agent2:6.0.18-ubuntu

Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.1
 Git commit:        e91ed5707e038b02af3b5120fa0835c5bedfd42e
 Built:             Sat Oct 22 09:30:36 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.1
  Git commit:       8728dd2
  Built:            Sat Oct 22 10:10:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        a916309fff0f838eb94e928713dbc3c0d0ac7aa4
 docker-init:
  Version:          0.19.0
  GitCommit:        fec3683b971d9c3ef73f284f176672c44b448662

##### CONFIGURATION

```sh
 docker run --name zabbix-agent2 --restart=always --net=host --privileged --user root -v /var/run/containerd/:/var/run/containerd/:ro -e ZBX_HOSTNAME="instance-dev-test" -e ZBX_SERVER_HOST="zabbix.local" -d zabbix/zabbix-agent2:6.0.18-ubuntu
```

##### STEPS TO REPRODUCE

```yaml

changing the parameter in the file "/etc/zabbix/zabbix_agent2.d/plugins.d/docker.conf"

### Option: Plugins.Docker.Endpoint
#       Docker API endpoint.
#
# Mandatory: no
# Default: unix:///var/run/docker.sock
# Plugins.Docker.Endpoint=unix:///var/run/docker.sock

### Option: Plugins.Docker.Timeout
#       The maximum time (in seconds) for waiting when a request has to be done.
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.Docker.Timeout=<Global timeout>
Plugins.Docker.Endpoint=unix:///var/run/containerd/containerd.sock

```

##### ACTUAL RESULTS

Docker: Get info

Cannot fetch data: Get "http://1.28/info": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00".

```paste below

```

**Comment by dotneft** [comment]
1. do you have enabled selinux on host system?
2. what item key you have such response? May I ask you to switch agent2 to debug mode and show us at least one request and response?

**Comment by ITMPGIT** [comment]
key example: docker.info
I only get information from the host (cpu, ram, disc) and nothing from docker, no selinux


1. Failed: cannot extract value from json by path "$.sync_time": no data matches the specified path
 29694:20230615:081535.530 error reason for "instance-dev-nats-server:docker.containers" changed: Ca                                                            nnot fetch data: Get "http://1.28/containers/json?all=true": net/http: HTTP/1.x transport connection                                                             broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00".
 29695:20230615:081536.533 error reason for "instance-dev-nats-server:docker.data_usage" changed: Ca                                                            nnot fetch data: Get "http://1.28/system/df": net/http: HTTP/1.x transport connection broken: malfor                                                            med HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00".
 29696:20230615:081537.534 error reason for "instance-dev-nats-server:docker.images" changed: Cannot                                                             fetch data: Get "http://1.28/images/json": net/http: HTTP/1.x transport connection broken: malforme                                                            d HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00".
 29694:20230615:081538.537 error reason for "instance-dev-nats-server:docker.info" changed: Cannot f                                                            etch data: Get "http://1.28/info": net/http: HTTP/1.x transport connection broken: malformed HTTP re                                                            sponse "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00".

**Comment by dotneft** [comment]
You need connect to docker.sock instead of containerd.socket. To configure properly docker.sock it is necessary to disable PrivateTmp for docker service. After that:
```
docker run --name zabbix-agent2 --start=always --net=host --privileged --user 0:0 -v /run/docker.sock:/run/docker.sock:rw -v /home/alexey_pustovalov/docker.conf:/etc/zabbix/zabbix_agent2.d/plugins.d/docker.conf -e ZBX_HOSTNAME="instance-dev-test" -e ZBX_SERVER_HOST="zabbix.local" -d zabbix/zabbix-agent2:6.0.18-ubuntu
```
works fine!

PS: do not forget to update /etc/zabbix/zabbix_agent2.d/plugins.d/docker.conf.

**Comment by ITMPGIT** [comment]
It's works! thanks @dotneft
