### ISSUE TITLE
Trying to configure TLS with Web Apache MySQL image/container?

### ISSUE THREAD

**Issue by kmpeterson** [zabbix/zabbix-docker#1087]
##### SUMMARY

Process to configure https for Web Apache MySQL image is not documented.

##### OS / ENVIRONMENT / Used docker-compose files

Docker image zabbix/zabbix-web-apache-mysql .  RHEL9, Podman.

##### CONFIGURATION

Initial configuration from https://www.zabbix.com/documentation/current/en/manual/installation/containers is working.  Cannot determine the "correct" way to enable TLS.  
##### STEPS TO REPRODUCE

The documentation is silent on enabling TLS support for the web interface, other than that the indicating that `/etc/ssl/apache2` is a mount point for the certificate files, which are `ssl.key` and `ssl.cert`, respectively.  It's also silent on the fact that 8443 is exposed as the TLS port (though this is implicit in the Nginx example).  
##### EXPECTED RESULTS

I'd be happily surprised if either simply placing those files in that location meant that I could access https://xxx:8443 .  However, I'd _expect_ that there would be more to do here and I'm trying to understand that.

##### ACTUAL RESULTS

Unable to connect on 8443, and what seems to be a not-unusual message about determining the server name.  

```Jun 18 13:12:04 a023545234.kmpeterson.com systemd[1]: Starting Podman container-zabbix-web.service...
Jun 18 13:12:04 a023545234.kmpeterson.com podman[2299724]: 
Jun 18 13:12:05 a023545234.kmpeterson.com podman[2299724]: 2023-06-18 13:12:04.999956792 -0400 EDT m=+0.136669049 container create ffe070e95b2ea2376de96e475ab3a34fd0dff65d0b89f3a940b1dc88fb7ccc06 (image=d>
Jun 18 13:12:05 a023545234.kmpeterson.com podman[2299724]: 2023-06-18 13:12:04.909344539 -0400 EDT m=+0.046056793 image pull  docker.io/zabbix/zabbix-web-apache-mysql:latest
Jun 18 13:12:05 a023545234.kmpeterson.com podman[2299724]: 2023-06-18 13:12:05.025004113 -0400 EDT m=+0.161716371 container init ffe070e95b2ea2376de96e475ab3a34fd0dff65d0b89f3a940b1dc88fb7ccc06 (image=doc>
Jun 18 13:12:05 a023545234.kmpeterson.com systemd[1]: Started Podman container-zabbix-web.service.
Jun 18 13:12:05 a023545234.kmpeterson.com podman[2299724]: 2023-06-18 13:12:05.029023322 -0400 EDT m=+0.165735580 container start ffe070e95b2ea2376de96e475ab3a34fd0dff65d0b89f3a940b1dc88fb7ccc06 (image=do>
Jun 18 13:12:05 a023545234.kmpeterson.com podman[2299724]: ffe070e95b2ea2376de96e475ab3a34fd0dff65d0b89f3a940b1dc88fb7ccc06
Jun 18 13:12:05 a023545234.kmpeterson.com zabbix-web[2299771]: ** Deploying Zabbix web-interface (Apache) with MySQL database
Jun 18 13:12:05 a023545234.kmpeterson.com zabbix-web[2299771]: ** Using MYSQL_USER variable from ENV
Jun 18 13:12:05 a023545234.kmpeterson.com zabbix-web[2299771]: ** Using MYSQL_PASSWORD variable from ENV
Jun 18 13:12:05 a023545234.kmpeterson.com zabbix-web[2299771]: ********************
Jun 18 13:12:05 a023545234.kmpeterson.com zabbix-web[2299771]: * DB_SERVER_HOST: 127.0.0.1
Jun 18 13:12:05 a023545234.kmpeterson.com zabbix-web[2299771]: * DB_SERVER_PORT: 3306
Jun 18 13:12:05 a023545234.kmpeterson.com zabbix-web[2299771]: * DB_SERVER_DBNAME: zabbix
Jun 18 13:12:05 a023545234.kmpeterson.com zabbix-web[2299771]: ********************
Jun 18 13:12:05 a023545234.kmpeterson.com zabbix-web[2299771]: **** MySQL server is not available. Waiting 5 seconds...
Jun 18 13:12:10 a023545234.kmpeterson.com zabbix-web[2299771]: ** Adding Zabbix virtual host (HTTP)
Jun 18 13:12:10 a023545234.kmpeterson.com zabbix-web[2299771]: **** Impossible to enable SSL support for Apache2. Certificates are missed.
Jun 18 13:12:10 a023545234.kmpeterson.com zabbix-web[2299771]: ** Preparing Zabbix frontend configuration file
Jun 18 13:12:10 a023545234.kmpeterson.com zabbix-web[2299771]: ########################################################
Jun 18 13:12:10 a023545234.kmpeterson.com zabbix-web[2299771]: ** Executing '/usr/sbin/httpd -D FOREGROUND'
Jun 18 13:12:10 a023545234.kmpeterson.com zabbix-web[2299771]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 2606:19b:280:01bf::a000:1. Set the 'ServerName' >
Jun 18 13:12:10 a023545234.kmpeterson.com zabbix-web[2299771]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 2606:19b:280:01bf::a000:1. Set the 'ServerName' >
Jun 18 13:12:10 a023545234.kmpeterson.com zabbix-web[2299771]: [Sun Jun 18 17:12:10.138442 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Unix) PHP/8.1.19 configured -- resuming normal operati>
Jun 18 13:12:10 a023545234.kmpeterson.com zabbix-web[2299771]: [Sun Jun 18 17:12:10.138463 2023] [core:notice] [pid 1] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
Jun 18 13:12:23 a023545234.kmpeterson.com zabbix-web[2299771]: 2601:19b:200:5974::10 - - [18/Jun/2023:17:12:23 +0000] "POST /zabbix.php?action=latest.view.refresh HTTP/1.1" 200 23 "https://zabbix" ...

```
##### QUESTIONS AND COMMENTS
+ I apologize for not being as familiar with Alpine as I am with Deb and RHEL, but from what I can tell there's no TLS configuration at all in the running container (no cipher suites specs, no references to the TLS configuration, etc.).
+ I ran down the possibility that there was a permissions issue on the certificate files, but modifying the owner to UIDs `100` or `1997` didn't change the (lack of) results.  
+ I noticed a reference to an Alpine build of Apache that required the certs to be prefixed with the server name, but it's not clear what the server is using. 
+ I also checked the DockerHub landing page - https://hub.docker.com/r/zabbix/zabbix-web-apache-mysql - which repeats the direction to place the requisite files in (the volume linked to) `/etc/ssl/apache2` and has other interesting but unfortunately non-relevant information.  I also find it confusing that the general Zabbix documents doesn't distinguish the task of configuring/using TLS for server/database/agent communication and for securing the web interface.  I'd be happy to submit a comment there once I get to that point.

If there's literally a better way to approach this that I've missed, I'd be grateful to learn about that as well.  I appreciate the help!

**Comment by dotneft** [comment]
Hello!

`The documentation is silent on enabling TLS support for the web interface, other than that the indicating that /etc/ssl/apache2 is a mount point for the certificate files, which are ssl.key and ssl.cert, respectively.`
because it is enough for TLS feature enable.

`I apologize for not being as familiar with Alpine as I am with Deb and RHEL, but from what I can tell there's no TLS configuration at all in the running container (no cipher suites specs, no references to the TLS configuration, etc.).`
SSL configuration is here: https://github.com/zabbix/zabbix-docker/blob/6.4/Dockerfiles/web-apache-mysql/alpine/conf/etc/zabbix/apache_ssl.conf

**Comment by kmpeterson** [comment]
Thanks for your response...

In my _running container_, there is a symlink: `/etc/apache2/conf.d/zabbix.conf` -> `/etc/zabbix/apache.conf`.  

I'm assuming there is code somewhere that generates that link, based on... what?  The `apache_ssl.conf` does exist, also in `/etc/zabbix` but it's clear that the operative file is not the one with the SSL/TLS directives.  

An `Include` directive in the `zabbix.conf` would work as well of course.  So, I'm missing a step?

**Comment by dotneft** [comment]
If you add volume with /etc/ssl/apache2/ssl.crt and /etc/ssl/apache2/ssl.key it will automatically enable SSL.

**Comment by kmpeterson** [comment]
Yep, I thought it might be that simple.  But:

```
$ podman exec -it zabbix-web /bin/bash
zabbix:/usr/share/zabbix$ ls -al /etc/ssl/apache2
total 8
drwxr-xr-x    2 zabbix   zabbix          37 Jun 17 21:48 .
drwxr-xr-x    1 root     root           140 Jun  2 07:07 ..
-rw-r--r--    1 apache   apache        1501 Jun 17 21:48 ssl.cert
-rw-------    1 apache   apache         241 Jun 17 21:48 ssl.key
zabbix:/usr/share/zabbix$ ls -al /etc/apache2/conf.d
total 28
drwxrwxr-x    1 zabbix   root            25 Jun 18 20:38 .
drwxrwxr-x    1 zabbix   root            20 Jun  2 07:07 ..
-rw-rw-r--    1 zabbix   root          1191 Apr 11 16:07 info.conf
-rw-rw-r--    1 zabbix   root          5078 Apr 11 16:07 languages.conf
-rw-rw-r--    1 zabbix   root          4444 Jun  2 07:07 mpm.conf
-rw-rw-r--    1 zabbix   root           378 May 12 09:42 php81-module.conf
-rw-rw-r--    1 zabbix   root           732 Apr 11 16:07 userdir.conf
lrwxrwxrwx    1 zabbix   zabbix          23 Jun 18 20:38 zabbix.conf -> /etc/zabbix/apache.conf
$ ^D
exit
```

Here is how the container is being run:
```
podman run --name zabbix-web -t \
       --env=ZBX_SERVER_HOST="127.0.0.1" \
       --env=DB_SERVER_HOST="127.0.0.1" \
       --env=MYSQL_DATABASE="zabbix" \
       --env=MYSQL_USER="zabbix" \
       --env=MYSQL_PASSWORD=${MYSQL_PASSWORD} \
       --env=MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} \
       --volume=${ZABBIX_PKI_VOL}:/etc/ssl/apache2:ro,Z \
       --env=ZBX_SERVER_NAME="MonZ" \
       --restart=always \
       --pod=zabbix \
       --detach \
       docker.io/zabbix/zabbix-web-apache-mysql:latest
```

So, I _still_ think I'm missing something. I still get `5c330a145cab **** Impossible to enable SSL support for Apache2. Certificates are missed.` when the container is created.  Any ideas?

**Comment by dotneft** [comment]
ssl.crt instead of ssl.cert.

**Comment by kmpeterson** [comment]
Alas, I'm unable to find a trendy giphy to insert with a "slaps head" - but you get the idea.  Thanks.
