### ISSUE TITLE
ADD net-snmp-tools ZABBIX PROXY SQLITE3 6.0 ALPINE >

### ISSUE THREAD

**Issue by Math-benites** [zabbix/zabbix-docker#1088]
docker file of this file covers a very restricted package over SNMP , net-snmp-agent-libs , in view of the net-snmp-tools package , which has snmpset , for script automation.

##### SUMMARY
When using a script inside the zabbix server for proxy, I realized that the installed snmp package refers to net-snmp-agent-libs , something very simple not containing all packages like snmpset

##### OS / ENVIRONMENT / Used docker-compose files
Dockerfiles/proxy-sqlite3/alpine/Dockerfile

##### CONFIGURATION
build done by adding "net-snmp-tools"

##### EXPECTED RESULTS OK
snmpbulkget    snmpdelta      snmpgetnext    snmpping       snmptable      snmptrap       snmpwalk
snmpbulkwalk   snmpdf         snmpinform     snmpset        snmptest       snmpusm
snmpconf       snmpget        snmpnetstat    snmpstatus     snmptranslate  snmpvacm

##### ACTUAL RESULTS OFICIAL ZABBIX DOCKER FILE
snmpwalk

**Comment by Math-benites** [comment]
dockerhub doctorfree/zabbix-build-sqlite3:lastest with  "net-snmp-tools" package

**Comment by dotneft** [comment]
hmm... why do you need these tools? especially in "build" image?
