### ISSUE TITLE
Provided docker-compose files trigger errors relating to ip_local_port_range

### ISSUE THREAD

**Issue by michaelkrieger** [zabbix/zabbix-docker#1090]
##### SUMMARY
Default docker-compose files trigger errors relating to ip_local_port_range

##### OS / ENVIRONMENT / Used docker-compose files
Debian 11.7 / Kernel 5.10.0-24-amd64

##### STEPS TO REPRODUCE

Use one of the existing docker-compose files which include:
```
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
```
##### EXPECTED RESULTS

I would expect no errors

##### ACTUAL RESULTS
An error is shown on the console stating "ip_local_port_range: prefer different parity for start/end values"

##### RECOMMENDATION
As per [ip-sysctl.txt]( https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt)

> _If possible, it is better these numbers have different parity
> (one even and one odd value)._

Updating all of the compose files to meet the recommendation of [ip-sysctl.txt]( https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt) and simply using 64999 or similar will avoid these unnecessary errors.

**Comment by dotneft** [comment]
Fixed! Thank you!
