### ISSUE TITLE
Current 6.4.5 Tagged Images Appear to be Zabbix 6.4.4 

### ISSUE THREAD

**Issue by newlandk** [zabbix/zabbix-docker#1091]
##### SUMMARY
At least some of the 6.4.5 tagged images appear to actually be 6.4.4. Running the images locally confirm through the UI and server logs that it appears to be running 6.4.4.

Edit: Good call @leroyz84, it appears the 6.4 branch is 2 commits ahead of 6.4.5 release (at the moment) and that commit includes the version bumps. https://github.com/zabbix/zabbix-docker/compare/6.4.5...6.4

https://hub.docker.com/layers/zabbix/zabbix-server-pgsql/ubuntu-6.4.5/images/sha256-bf56d40eab82abf894052febdd36eb83612cc8bd42fb1de558558567306eac11?context=explore

![image](https://github.com/zabbix/zabbix-docker/assets/6456000/83724352-cf1e-4302-969a-ed4ac822e6c6)

**Comment by leroyz84** [comment]
it looks like the tag was wrong:
https://github.com/zabbix/zabbix-docker/tree/6.4.5/Dockerfiles/agent/alpine
on the main 6.4  it's there
https://github.com/zabbix/zabbix-docker/commit/631cf2c12ed09ae30ac132681f944361ce5def11

**Comment by dotneft** [comment]
Known issue. Please wait next release!
