### ISSUE TITLE
Azure SSO Passwordless Login failure 'X509, MultiFactor'  - Request to add requestedAuthnContext to ZBX_SSO_Setting

### ISSUE THREAD

**Issue by zleffel** [zabbix/zabbix-docker#1092]
With Azure SSO and Number matching enabled, passwordless authentications fail unless the SSO Settings are re-written to include $SSO['SETTINGS'] = [
'security' => [
'requestedAuthnContext' => false
]
];​

Is there a way to add this to the ZBX_SSO_Setting in the env_web similar to this.
ZBX_SSO_SETTINGS={"strict":false, "baseURL":"https://someawesomeurl.com/", "use_proxy_headers":true, "requestedAuthnContext":false}

**Comment by jp-harvey** [comment]
@zleffel there is! (formatted for readability)
```
ZBX_SSO_SETTINGS={
  "strict":false, 
  "baseURL":"https://someawesomeurl.com/", 
  "use_proxy_headers":true,
  "security": {
    "requestedAuthnContext": false
  }
}
```

**Comment by dotneft** [comment]
Thank you! @zleffel please confirm that solution works for you.

**Comment by zleffel** [comment]
Team,

Thank you very much, this has resolved the issue we were experiencing.

**Comment by itzaudro** [comment]
Hello,

I'm experiencing same thing as zleffel. I have added the line you mention to my .env_web file and redeployed containers but I'm still getting "AADSTS75011: Authentication method 'MultiFactor, Fido' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'. Contact the Zabbix application owner."

This occurs when using passwordless sign on for FIDO2 or Microsoft Authenticator passwordless signon.
