### ISSUE TITLE
6.0.20 Oracle Linux image stuck on 6.0.19

### ISSUE THREAD

**Issue by zeduperes** [zabbix/zabbix-docker#1093]
##### SUMMARY

Seems that 6.0.20-OL is wrong... Zabbix Server, Frontend and Proxy still showing 6.0.19 after update to 6.0.20.

##### OS / ENVIRONMENT / Used docker-compose files

Docker version 20.10.22, build 3a2c30b
docker-compose version 1.29.2, build unknown
Red Hat Enterprise Linux release 8.7 (Ootpa)

Images used with problem:
zabbix/zabbix-web-nginx-mysql:ol-6.0.20
zabbix/zabbix-server-mysql:ol-6.0.20
zabbix/zabbix-proxy-sqlite3:ol-6.0.20

##### STEPS TO REPRODUCE

```yaml
docker logs -f zabbix-proxy
docker logs -f zabbix-server
```

##### EXPECTED RESULTS

Update to 6.0.20

##### ACTUAL RESULTS

Still on 6.0.19 after update

```paste below
Starting Zabbix Proxy (active) [test]. Zabbix 6.0.19 (revision 998f864)
Starting Zabbix Server. Zabbix 6.0.19 (revision 998f864).

```

**Comment by dotneft** [comment]
Known issue. Please wait next release!
