### ISSUE TITLE
Incorrect zabbix version in docker images alpine-6.4.5

### ISSUE THREAD

**Issue by shk3bq4d** [zabbix/zabbix-docker#1094]
Hello!

##### SUMMARY

Something got wrong in the image building process as the application version does not match the image tag. At least for the following two images:
* `zabbix/zabbix-server-mysql:alpine-6.4.5` (`sha256:0fc59276e42b5372c9b8b0acf0500240a6a14d52c21aef12e631b0d3c2ad4324`)
* `zabbix/zabbix-web-nginx-mysql:alpine-6.4.5` (`sha256:00ccbd1edbf3ef352a7e22bd30e7fe4c8c3f8f9483f1d10ca15db8a0127480a5`)

##### STEPS TO REPRODUCE

```sh
docker run -it --pull always --entrypoint "" zabbix/zabbix-server-mysql:alpine-6.4.5 env | grep ZBX_VERSION
alpine-6.4.5: Pulling from zabbix/zabbix-server-mysql
4db1b89c0bd1: Already exists
a49bba8317a7: Pull complete
3b7e245ca232: Pull complete
f357596d96f9: Pull complete
7f0273870d35: Pull complete
f60d951beaf9: Pull complete
cd82dddfb894: Pull complete
4f4fb700ef54: Pull complete
64f991ea4721: Pull complete
Digest: sha256:0fc59276e42b5372c9b8b0acf0500240a6a14d52c21aef12e631b0d3c2ad4324
Status: Downloaded newer image for zabbix/zabbix-server-mysql:alpine-6.4.5
ZBX_VERSION=6.4.4
```

##### EXPECTED RESULT
The environment variable, which from what I can see, correctly reflects the application version deployed in those faulty image, should match the image tag name, but they don't (6.4.4 != 6.4.5)

Have a good day!

**Comment by dotneft** [comment]
Please check #1091

**Comment by shk3bq4d** [comment]
ok, sorry for the duplicate. I didn't think about checking closed issues as I anticipated the resolution would be different.

Best regards!
