### ISSUE TITLE
Forgot to remove <<<<<<<<HEAD in merge

### ISSUE THREAD

**Issue by info-ctc** [zabbix/zabbix-docker#1095]
Seems like you guys forgot to remove the HEAD statement after merging agent2 

https://github.com/zabbix/zabbix-docker/blob/6.0/Dockerfiles/agent2/ubuntu/docker-entrypoint.sh

LINE 155
<<<<<<< HEAD
=======
    update_config_var $ZBX_AGENT_CONFIG "HeartbeatFrequency" "${ZBX_HEARTBEAT_FREQUENCY}"
    update_config_var $ZBX_AGENT_CONFIG "ForceActiveChecksOnStart" "${ZBX_FORCEACTIVECHECKSONSTART}"
>>>>>>> d4f6f4946 (Fixed missing and incorrect variables)

**Comment by dotneft** [comment]
Fixed. Thank you very much!
