### ISSUE TITLE
Problems with HTTPS

### ISSUE THREAD

**Issue by nomanuser** [zabbix/zabbix-docker#1099]
Hello,
I made the docker compose two times, one with alpine pgsql latest and the other with centos pgsql latest, i used other docker-compose too and i can´t acces to https, when i try acces by https:://localhost or https://localhost:8443 appears a message saying that i can´t acces to that website.

I used lsof -i and the docker is listening on 443 :(

¿How i can acces to zabbix by https?

**Comment by dotneft** [comment]
did you configure SSL certificates?

**Comment by nomanuser** [comment]
> did you configure SSL certificates?

Nop, is this? https://www.zabbix.com/documentation/current/en/manual/encryption/using_certificates

**Comment by dotneft** [comment]
Check documentation: https://github.com/zabbix/zabbix-docker/tree/6.4/Dockerfiles/web-nginx-mysql#etcsslnginx
