### ISSUE TITLE
zabbix-server-pgsql:6.4.8 image missing on docker hub - please rebuild 

### ISSUE THREAD

**Issue by NoCoker** [zabbix/zabbix-docker#1103]
##### SUMMARY
As of the last commit the postgres related images are not build and pushed to docker Hub
Please trigger it :-)

https://hub.docker.com/r/zabbix/zabbix-server-pgsql/tags?page=1&name=6.4.8

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
You can use :latest or by sha. 6.4.8 image for PostgreSQL is broken. Fixed after release.

**Comment by NoCoker** [comment]
OK thanks So Zabbix is not rebuilding the 6.4.8 images for postgres after release - correct !
That mean if i want 6.4.8 i need to build it myself on the latest checkin !

Not nice but ok

**Comment by dotneft** [comment]
No no... you do not need to rebuild. Just use latest tag or by sha: https://hub.docker.com/r/zabbix/zabbix-server-pgsql/tags?page=1&name=6.4-latest
