### ISSUE TITLE
Unable to select configuration. erro ao configurar front end zabbix

### ISSUE THREAD

**Issue by vinilettmann** [zabbix/zabbix-docker#1104]
Pessoal, estou tendo a seguinte dificuldade.
instalei recentemente um servidor zabbix com o DB separado, e ao tentar configurar o mesmo no front-end esta dado o seguinte erro.

Unable to select configuration.

Poderiam me ajudar nessa questão?

**Comment by dotneft** [comment]
Hello! Please describe the problem in English.
