### ISSUE TITLE
ubuntu server image possibly missing        net-snmp-agent-libs 

### ISSUE THREAD

**Issue by bw2305** [zabbix/zabbix-docker#1105]
##### SUMMARY

Couldnt get snmp monitoring up and runing with ubuntu server
possibly missing        net-snmp-agent-libs 
Compared Dockerfiles - 
and saw difference - tested with alpine, same env_vars, same zbx_env: working fine!
##### OS / ENVIRONMENT / Used docker-compose files

docker-compose_v3_ubuntu_pgsql_latest.yaml

##### CONFIGURATION

nothing special, out of the box

##### STEPS TO REPRODUCE

checked with snmpwalk (installed as root) communication was ok, only zabbix didnt do any..
dns ok, via ip ok.

```yaml

```

##### EXPECTED RESULTS

Zabbix should report SNMP as green

##### ACTUAL RESULTS

NO SNMP communication trigger

```paste below

```

**Comment by dotneft** [comment]
what error do you see in Zabbix frontend?

**Comment by bw2305** [comment]
Hello Alexey,

 

in the frontend I see "Timeout while connecting to <ip>:161" when I do a mouse over in Datacollection ->hosts.

After a while in Monitoring -> Problems  Extreme EXOS: No SNMP data collection

show up from the template trigger.

 

Looks like the is no snmp communication at all working, I see (using tcpdump on the docker host)
pings between zabbix and the switch.

 

And a single snmp reqest.

zabbixD.31993 > sw-bwe.we.de.snmp:  C="WE-ro-smnp" GetRequest(32)  E:1916.1.1.1.8.0

zabbixD.54582 > sw-bwe.we.de.snmp:  C="WE-ro-smnp" GetRequest(28)  system.sysObjectID.0


I see it's trying to connect, so probably the lib is actually not missing.

 

and in the server logs a recurring (docker logs -f zbx-zabbix-server-1)

 
Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU
Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU

 

Compared with the alpine: there's no BAD operator message there.

 

Maybe it's not a missing lib, maybe a bad mib file?

 

 

----------

Crosscheck with the ubuntu-version:

added another host. A ups. APC srt5000 template

same timeout


9.330747 IP zabbixD.64768 > ups01.we.de.snmp:  C="WE-ro-smnp" GetRequest(34)  E:318.1.1.1.4.1.1.0

 

 

 

 

------------------------

Test with snmpwalk from *inside* the server container:

 


docker exec -u root -it  zbx-zabbix-server-1 /bin/bash

apt update

apt install snmp


snmpwalk -v 2c -c mySecretReadOnlyCommunityString   sw-bwe.we.de

 

results in:

-------------------

 


Bad operator (INTEGER): At line 73 in /var/lib/mibs/ietf/SNMPv2-PDU  <-------------- ## SAME Mesage here!
SNMPv2-MIB::sysDescr.0 = STRING: ExtremeXOS (X440G2-12p-10G4) version 32.6.1.5 32.6.1.5 by release-manager on Wed 18 Oct 2023 07:02:48 PM UTC
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.1916.2.227
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (32007300) 3 days, 16:54:33.00
SNMPv2-MIB::sysContact.0 = STRING: ***@***.***
SNMPv2-MIB::sysName.0 = STRING: sw-bwe
SNMPv2-MIB::sysLocation.0 = STRING: we-eltville-office-bwe
SNMPv2-MIB::sysServices.0 = INTEGER: 79
IF-MIB::ifNumber.0 = INTEGER: 50

 

But this probably prooves that networking is ok.

tcpdump in parallel fires a lot of traffic running snmpwalk, omitted.

 




 

 

Strange...

 

 

 

With Alpine:




For testing, why I filed this issue, maybe with the wrong conclusion:

I kept the env_vars and zbx_env as is. Then replaced the docker-compose.yaml
with the alpine version and restarted.

So same config, different image: works

 




 

 

BR and MANY THANKS FOR YOUR WORK!!!! - great Zabbix, love it!

 

Bernhard

 

 

 

 

 

esendet: Montag, 13. November 2023 um 14:06 Uhr
Von: "Alexey Pustovalov" ***@***.***>
An: "zabbix/zabbix-docker" ***@***.***>
Cc: "bw2305" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [zabbix/zabbix-docker] ubuntu server image possibly missing net-snmp-agent-libs (Issue #1105)




 

what error do you see in Zabbix frontend?

**Comment by dotneft** [comment]
It looks like SNMP device is not available from Zabbix server / proxy container or incorrect SNMP community.

**Comment by bw2305** [comment]
Ouch!You’re right.Community String.WE-ro-snmp.  I mistyped mn instead of nm - will verify tomorrow.I’ve been looking over and over at it. Ouch, that hurts.Sorry for everything. Ashes on my head.Thanks Bernhard :)On 14.11.23 at 09:47, Alexey Pustovalov wrote:
                
            
            
                
                    From: "Alexey Pustovalov" ***@***.***>Date: 14. November 2023To: "zabbix/zabbix-docker" ***@***.***>Cc: "Author" ***@***.***>,"bw2305" ***@***.***>Subject: Re: [zabbix/zabbix-docker] ubuntu server image possibly missing       net-snmp-agent-libs  (Issue #1105)
                
                
It looks like SNMP device is not available from Zabbix server / proxy container or incorrect SNMP community.

**Comment by bw2305** [comment]
Please take my excuses. SNMP an smnp are not the same. This working. The Bad operator (integer) is still thereThanks BrBernhard :)On 14.11.23 at 09:47, Alexey Pustovalov wrote:
                
            
            
                
                    From: "Alexey Pustovalov" ***@***.***>Date: 14. November 2023To: "zabbix/zabbix-docker" ***@***.***>Cc: "Author" ***@***.***>,"bw2305" ***@***.***>Subject: Re: [zabbix/zabbix-docker] ubuntu server image possibly missing       net-snmp-agent-libs  (Issue #1105)
                
                
It looks like SNMP device is not available from Zabbix server / proxy container or incorrect SNMP community.
