### ISSUE TITLE
SNMPv3 traps

### ISSUE THREAD

**Issue by tenhishadow** [zabbix/zabbix-docker#1112]
##### SUMMARY

Asking for support for SNMPv3

##### OS / ENVIRONMENT / Used docker-compose files

docker-compose_v3_alpine_pgsql_latest.yaml

@dotneft hello, is there any plan to support v3 for traps?

**Comment by dotneft** [comment]
You can use it. Just replace snmptrapd.conf with your own. Just do not remove already existing mandatory options :-)

**Comment by tenhishadow** [comment]
@dotneft точно)
