### ISSUE TITLE
JavaGateway，JavaGatewayPort，StartJavaPollers can not  does not take effect

### ISSUE THREAD

**Issue by ZZZhsb** [zabbix/zabbix-docker#1114]
##### SUMMARY
Hello, I want to use JavaGateway,  my zabbix version is 6.4.4，
i use thie command create container
`docker create --name zabbix-server-mysql -t \
    -e DB_SERVER_HOST="127.0.0.1" \
    -e MYSQL_DATABASE="zabbix" \
    -e MYSQL_USER="root" \
    -e MYSQL_PASSWORD="root" \
    -e ZBX_DBTLSCONNECT="required" \
    -e ZBX_LISTENPORT="19051" \
    -e ZBX_LISTENIP=10.10.20.142 \
    -e ZBX_ALLOWUNSUPPORTEDDBVERSIONS=1 \
    -v /home/work/zabbix/:/etc/zabbix/ \
    --net=host \
    -p 19051:19051 \
    --restart unless-stopped \
    --privileged \
    zabbix/zabbix-server-mysql:centos-6.4.4`。
I start  JavaGateway succeed， 
then i set the config
![image](https://github.com/zabbix/zabbix-docker/assets/73522623/e0942223-1926-46bc-94a6-d2ddbe957eef)
but when I restart zabbix server,the config was removed.
![image](https://github.com/zabbix/zabbix-docker/assets/73522623/cc71ac8c-b4cc-4d17-bb0f-098ff767a073)
and my zabbix_server.conf These configuration items are missing

**Comment by dotneft** [comment]
You must configure all options using environment variables.

**Comment by ZZZhsb** [comment]
Thank you，I use this command it can work
docker create --name zabbix-server-mysql -t \
    -e DB_SERVER_HOST="127.0.0.1" \
    -e MYSQL_DATABASE="zabbix" \
    -e MYSQL_USER="root" \
    -e MYSQL_PASSWORD="root" \
    -e ZBX_DBTLSCONNECT="required" \
    -e ZBX_LISTENPORT="19051" \
    -e ZBX_LISTENIP=10.10.20.142 \
    -e ZBX_JAVAGATEWAY_ENABLE=true \
    -e ZBX_JAVAGATEWAY=10.10.20.142 \
    -e ZBX_JAVAGATEWAYPORT=10052 \
    -v /home/work/zabbix/:/etc/zabbix/ \
    --net=host \
    -p 19051:19051 \
    --restart unless-stopped \
    --privileged \
    zabbix/zabbix-server-mysql:centos-6.4.4
