### ISSUE TITLE
Why the Postgres Compose file also installs mysql?

### ISSUE THREAD

**Issue by Apollon77** [zabbix/zabbix-docker#1115]
##### SUMMARY
I used `docker compose -f docker-compose_v3_alpine_pgsql_latest.yaml up` to install with pgsql version and then he downloaded also mysql-server docker image and also started it.

Why?

Yes the compose file contains it ... but should it not be postgres only?

##### OS / ENVIRONMENT / Used docker-compose files
ubuntu LXC container with docker in it 
File: docker-compose_v3_alpine_pgsql_latest.yaml

##### CONFIGURATION
nothing

**Comment by Apollon77** [comment]
PS: Also strange is that the zabbix_agent which is also defined in the docker file is not started

**Comment by NoYoWiFi** [comment]
你可以参考这个docker-compose配置
https://github.com/NoYoWiFi/zabbix_docker
```
sh update_config-entrypoint_pgsql.sh init
sh update_config-entrypoint_pgsql.sh down
sh update_config-entrypoint_pgsql.sh cp
sh update_config-entrypoint_pgsql.sh start
```

**Comment by miguimartinezzz** [comment]
i have no idea but the very same issue.

**Comment by NoYoWiFi** [comment]
try this
https://jihulab.com/NoYoWiFi/zabbix/-/tree/zabbix_docker
&nbsp;


NoYoWiFi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Miguel ***@***.***&gt;; 
发送时间: 2023年12月29日(星期五) 晚上6:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zabbix/zabbix-docker] Why the Postgres Compose file also installs mysql? (Issue #1115)





 
i have no idea but the very same issue.

**Comment by dotneft** [comment]
the compose file is just an example. It contains all Zabbix components, including Zabbix proxy with MySQL DB. You can manage what exactly you want to use and remove unnecessary components.

**Comment by Apollon77** [comment]
@dotneft Ok, honestly ... then this should be stated very clear in the Readme. With that structure of different files for different "os/db combinations" it clearly lets assue that such a file is exactly for this combination.

**Comment by miguimartinezzz** [comment]
@Apollon77 completely agree. Why would you name a compose file Mysql-whatever if in it you find configurations for MongoDB or PostgreSQL.... It just doesn´t make sense

**Comment by dotneft** [comment]
where do you see postgresql in mysql compose files?

**Comment by Apollon77** [comment]
No the problem was vise versa ... there is mysql in the psql compose files ... needed to choose psql because the mysql one ws not really working at all ...
In the end I switched to a non docker setup

**Comment by dotneft** [comment]
mysql in psql compose files is running only if you specify profile with mysql proxy :-)
