### ISSUE TITLE
Can't configure vault using the environment variables

### ISSUE THREAD

**Issue by Tardo** [zabbix/zabbix-docker#1116]
##### SUMMARY
- ZBX_VAULTDBPATH should not be required when you want to use vault 
  - https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_server#vaultdbpath
  - https://github.com/zabbix/zabbix-docker/blob/46df2b7f5009d4b2fd50e00ba9a63cc24bccba38/Dockerfiles/server-pgsql/ubuntu/docker-entrypoint.sh#L394
- ZBX_VAULTDBPATH does not work with pgsql.
  - https://github.com/zabbix/zabbix-docker/blob/46df2b7f5009d4b2fd50e00ba9a63cc24bccba38/Dockerfiles/server-pgsql/ubuntu/docker-entrypoint.sh#L141

##### OS / ENVIRONMENT / Used docker-compose files
zabbix/zabbix-server-pgsql:ubuntu-6.4-latest

##### CONFIGURATION
- ZBX_VAULTDBPATH: kv/zabbix-db
- ZBX_VAULTURL: http://vault:8200
- VAULT_TOKEN: "{{ secrets.vault_zabbix_token }}"

##### STEPS TO REPRODUCE
Use the environment variables to configure vault

##### EXPECTED RESULTS
Configure vault with or without 'ZBX_VAULTDBPATH'

##### ACTUAL RESULTS
When using ZBX_VAULTDBPATH you cannot connect to the database. If you do not use ZBX_VAULTDBPATH you cannot use vault.

**Comment by dotneft** [comment]
share log file from the container please.
