### ISSUE TITLE
Cannot connect to web service: couldn't connect to server

### ISSUE THREAD

**Issue by krith-ik** [zabbix/zabbix-docker#1118]
##### SUMMARY

Docker zabbix web service is not binding to a port and hence I suspect the error mentioned in the title.

##### CONFIGURATION

Added
ZBX_ALLOWEDIP=10.26.X.X in .env_web_service

Added 
ZBX_STARTREPORTWRITERS=3
ZBX_WEBSERVICEURL=http://10.26.X.X:10053/report in .env_srv

##### EXPECTED RESULTS

zabbix-web-service is associated with a port.

##### ACTUAL RESULTS

![Screenshot 2024-01-09 142629](https://github.com/zabbix/zabbix-docker/assets/110151437/2a76b672-5f30-4e12-859a-3d9f2c90d569)

**Comment by dotneft** [comment]
of course, it uses internal network.

**Comment by krith-ik** [comment]
But I don't see it listed in ports exposed in the VM. Shouldn't it be exposed on port 10053?

![Screenshot 2024-01-09 143918](https://github.com/zabbix/zabbix-docker/assets/110151437/d5e2cc82-2347-4e17-9916-8f83cf8b8f80)

**Comment by dotneft** [comment]
it should not be. It uses backend network and communicates only with frontend container.

**Comment by krith-ik** [comment]
So, the webservice URL should be the Zabbix backend IP like this: ZBX_WEBSERVICEURL=http://172.x.x.x:10053/report in .env_srv ?
Is there any way to check if Zabbix docker web service is working? Could it be firewall issue?

**Comment by dotneft** [comment]
It is better to use DNS instead of IP address.
