### ISSUE TITLE
I hope the proxy-pgsql image can be added to the Dockerfile folder

### ISSUE THREAD

**Issue by NoYoWiFi** [zabbix/zabbix-docker#1119]
##### SUMMARY

What should I do to create a proxy-pgsql image?

##### OS / centos/ proxy-pgsql

There is no proxy-pgsql image in the Dockerfile folder. 

##### STEPS TO REPRODUCE

```yaml
Slightly
```

**Comment by dotneft** [comment]
we do not provide proxy image with PostgreSQL DB, if you need it, you have to prepare Docker files by yourself.
