### ISSUE TITLE
Agent 2 cannot connect  to the socket dbus

### ISSUE THREAD

**Issue by Hronici1** [zabbix/zabbix-docker#1120]
SUMMARY
The agent 2 in docker cannot connect to the socket dbus
Zabbix agent 2 - version 6.4.7

##### OS / ENVIRONMENT / Used docker-compose files
1. Without docker-compose
2. Env: ZBX_HOSTNAME and ZBX_SERVER_HOST

STEPS TO REPRODUCE
1. Run docker

docker run --name zabbix-agent2 -t --net="host" --env-file /opt/zabbix/env --privileged -v /:/host:ro -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro -v /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:rw --restart unless-stopped -d zabbix/zabbix-agent2:latest

2. Create LLD systemd.unit.discovery
3. Check LLD. I get an error 
"Cannot establish connection to any available bus: read unix @->/run/dbus/system_bus_socket: EOF"

![image](https://github.com/zabbix/zabbix-docker/assets/6024171/880b80c9-ea9e-4be7-bb1f-b217780722db)

**Comment by dotneft** [comment]
DBus uses uid for auth: https://github.com/containers/common/blob/main/pkg/cgroups/cgroups_linux.go#L417
So what you need to know is the correct uid on the host and make the dbus client use that one for auth.
For example add uid 1997 to host system or use "``--userns keep-id``" in case of podman.

**Comment by Hronici1** [comment]
> DBus uses uid for auth: https://github.com/containers/common/blob/main/pkg/cgroups/cgroups_linux.go#L417 So what you need to know is the correct uid on the host and make the dbus client use that one for auth. For example add uid 1997 to host system or use "`--userns keep-id`" in case of podman.

Thanks, you help me.  Issue close.
