### ISSUE TITLE
Zabbix agent is not avalable

### ISSUE THREAD

**Issue by YerayAlonso** [zabbix/zabbix-docker#1124]
##### SUMMARY
I get "Linux: Zabbix agent is not available (for 3m)" error after following the official guide.

##### OS / ENVIRONMENT / Used docker-compose files
Clean Ubuntu Server 22.04.3 installation with docker and docker-compose installed following [official documentation](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository).

##### CONFIGURATION
From the guide [here](https://www.zabbix.com/documentation/current/en/manual/installation/containers#docker-compose):
```bash
git clone https://github.com/zabbix/zabbix-docker.git
git checkout 6.4
docker compose -f ./docker-compose_v3_alpine_mysql_latest.yaml up
```

##### STEPS TO REPRODUCE
I can see the dashboard, but with the error mentioned above:

![imagen](https://github.com/zabbix/zabbix-docker/assets/1788228/efa2adc1-c2fe-4141-84f7-2573112cd31a)

##### ACTUAL RESULTS
This is what I get when I run `docker ps`:
```bash
CONTAINER ID   IMAGE                                             COMMAND                  CREATED         STATUS                   PORTS
                                               NAMES
6d5c5abcb977   zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest   "docker-entrypoint.sh"   3 minutes ago   Up 3 minutes (healthy)   0.0.0.0:80->8080/tcp, :::80->8080/tcp, 0.0.0.0:443->8443/tcp, :::443->8443/tcp   zabbix-docker-zabbix-web-nginx-mysql-1
78135fbfd993   zabbix/zabbix-server-mysql:alpine-6.4-latest      "/sbin/tini -- /usr/…"   3 minutes ago   Up 3 minutes             0.0.0.0:10051->10051/tcp, :::10051->10051/tcp                                    zabbix-docker-zabbix-server-1
e670b383eb1c   mysql:8.0-oracle                                  "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes
                                               zabbix-docker-mysql-server-1
```

**Comment by dotneft** [comment]
That is because you do not have Zabbix agents. By default only DB, server, web are running.

**Comment by YerayAlonso** [comment]
Sorry but I don't see how to run the agent. It seems to be defined in the yml.

**Comment by dotneft** [comment]
```
docker compose -f ./docker-compose_v3_alpine_mysql_latest.yaml up -d zabbix-agent
```
Please check documentation: https://docs.docker.com/engine/reference/commandline/compose_up/

**Comment by YerayAlonso** [comment]
Got it working after doing what you suggested and after modifying the "Zabbix server" Host to use `zabbix-agent` DNS instead of `127.0.0.1` IP:

![imagen](https://github.com/zabbix/zabbix-docker/assets/1788228/c617c3fc-3b8f-4cf7-9db1-43122d5c9300)

Thanks!
