### ISSUE TITLE
api_scim.php not working in nginx-web

### ISSUE THREAD

**Issue by Zablove** [zabbix/zabbix-docker#1125]
##### SUMMARY
While implementing a new zabbix environment I was hitting this bug. After some research it became clear that the bug is in the zabbix-web-nginx-* containers. 

##### ISSUE
Setting up AzureAD SSO, working ok, however SCIM Provisioning is not working. 
https://www.zabbix.com/documentation/current/en/manual/appendix/install/azure_ad paragraph SCIM User Provisioning. You need to create an API key and at the Azure site import the key and the Tenant URL https://<zabbix-instance-url>/zabbix/api_scim.php
While hitting the "Test connection" button I get the error:

![error](https://github.com/zabbix/zabbix-docker/assets/87560294/8a797b4f-ea43-458d-b204-3714097dec79)

Seems like the page is redirecting to the frontpage. 

After some tcpdump I found the query performed by Azure and was able to perform tests with curl and it proves the issue:

curl -X GET "https://productionhost/api_scim.php/Users?filter=userName+eq+%2208804361-82b0-4acd-b2ab-1be9fc33e797%22" -H "Authorization: Bearer 6eff65658286c1ff918dc3b9d2212eaefafa1f08f7551ac76c7f7d1427aa1072"

Tested with several environments and the bug (or configuration issue) seems to be in the combination of the web container with NGINX.

##### AFFECTED/NOT AFFECTED ENVIRONMENTS

Virtual machine installation (no docker containers):
Working:
Zabbix 6.4.8 and 6.4.10 icm. apache 
Zabbix 6.4.8 and 6.4.10 icm. nginx

Docker tests:
Not Working:
zabbix-web-nginx-pgsql alpine 6.4.0, 6.4.8 and 6.4.10
zabbix-web-nginx-pgsql ubuntu 6.4.0, 6.4.8 and 6.4.10
zabbix-web-nginx-pgsql alpine 7.0.0 alpha8
Working:
zabbix-web-apache-pgsql alpine 7.0.0 alpha8
zabbix-web-apache-pgsql alpine 6.4.8 and 6.4.10

##### STEPS TO REPRODUCE

Rollout simple docker environment, nothing to configure, no configuration needed at authorization, no SCIM enabling needed, no valid API key needed.

Perform curl request:
```curl -X GET "http://localhost/api_scim.php/Users?filter=userName+eq+%2208804361-82b0-4acd-b2ab-1be9fc33e797%22" -H "Authorization: Bearer 6eff65658286c1ff918dc3b9d2212eaefafa1f08f7551ac76c7f7d1427aa1072"```

Result if request working ok:
```{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Not authorized.","status":403}```

Result if request is not ok:
```< 
<!DOCTYPE html><html lang="en" theme="blue-theme">	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Author" content="Zabbix SIA" /><title>Zabbix docker: Zabbix</title>	
...... > And so on ```

**Comment by dotneft** [comment]
Could you share the container’s log?

**Comment by Zablove** [comment]
Log from container zabbix-web-nginx-mysql 6.4.8 when I perform the request and the output is not ok:

```172.19.0.1 - - [19/Jan/2024:11:20:16 +0000] "GET /api_scim.php/Users?filter=userName+eq+%2208804361-82b0-4acd-b2ab-1be9fc33e797%22 HTTP/1.1" 200 6027 "-" "curl/8.0.1" "-"```

Log from the container zabbix-web-apache-mysql 6.4.8 when I perform the request and the output is ok:
```172.19.0.1 - - [19/Jan/2024:11:25:01 +0000] "GET /api_scim.php/Users?filter=userName+eq+%2208804361-82b0-4acd-b2ab-1be9fc33e797%22 HTTP/1.1" 403 99 "-" "curl/8.0.1"```

Note: Output is ok but api key is not valid so I get an 403. However between the two attempts I had only changed the container from zabbix-web-nginx-mysql to zabbix-web-apache-mysql. Tested with same database and server version.

**Comment by dotneft** [comment]
Thank you! I found the issue. It will be fixed as soon as possible.

**Comment by dotneft** [comment]
Fixed! The update will be available quite soon.

**Comment by Zablove** [comment]
Thanks for the fast and correct response! scim API is working now icm. NGINX.
