### ISSUE TITLE
Feature request - default index_sso.php page

### ISSUE THREAD

**Issue by Zablove** [zabbix/zabbix-docker#1126]
##### SUMMARY
By default, apache and nginx open the index.php page. However, we have a large user base and they all open now the zabbix URL, then need to click "[Sign in with Single Sign-On (SAML)](https://our_domain.example/index_sso.php)" and then will be redirected to SSO login. 
This results in a lot of clicks per year and a lot of (wasted) time. 

##### REQUEST
Implement a variable at the zabbix-web containers that will change the default page index.php in apache or nginx.

##### SUGGESTION
Create a new variable ```SSO_DEFAULT_LOGIN``` that, when enabled, will change the configuration of apache or nginx to use the default page index_sso.php in stead of index.php

**Comment by dotneft** [comment]
Added HTTP_INDEX_FILE variable. Will be available in images quite soon. Thank you!

**Comment by Zablove** [comment]
I can also confirm that this solution works. Thank you!

**Comment by tbblake** [comment]
If I don't set the variable at all when building the container, the built-in apache ssl config sets DirectoryIndex to {HTTP_INDEX_FILE} and make browsing to the webroot display the default apache page.

EDIT:  Very new to docker here, so admittedly I don't even know *how* to set the variable...I just found this issue when updating from zabbix-web-apache-mysql:ol-6.4.10 to zabbix-web-apache-mysql:ol-6.4.11
