### ISSUE TITLE
NanoCPUs can not be set

### ISSUE THREAD

**Issue by dspanc** [zabbix/zabbix-docker#1129]
Synology DS1621+
AMD Ryzen V1500B
DSM 7.2.1-69057 Update 3

When creation of the container, error:
NanoCPUs can not be set, as your kernel does not support CPU CFS scheduler or the cgroup is not mounted

**Comment by dotneft** [comment]
Sorry, and what do you want? Enable CPU CFS scheduler or the cgroup for your system?

**Comment by dspanc** [comment]
I tried to install the docker image from docker-compose_v3_ubuntu_pgsql_latest.yaml on my Synology and got this error

**Comment by kernbug** [comment]
> I tried to install the docker image from docker-compose_v3_ubuntu_pgsql_latest.yaml on my Synology and got this error

This error means that your system is not able to provide required linux kernel functionality to use resource limit options. Ask Synology support to enable it or remove corresponding ('limits') configuration options from the docker compose before starting the container.  

Closing, not a Zabbix issue.
