### ISSUE TITLE
Использование скриптов python для внешних проверок

### ISSUE THREAD

**Issue by ruzmat** [zabbix/zabbix-docker#1130]
Использую docker compose, всё отлично работает кроме выполнение external скриптов т.е. внешних проверок, проверка с использованием python скрипта выдаёт ошибку:

`Value "/usr/bin/env: 'python3': No such file or directory" `

Как оказалось в контейнере zabbix-zabbix-server-1 нету python, установил вручную всё работает но разумеется до перезагрузки контейнера.

Что можно сделать в данной ситуации ?

**Comment by dotneft** [comment]
You need to build your own image with Zabbix image as base.

**Comment by ruzmat** [comment]
Пропадает смысл если каждый образ придется собирать самому, возможно есть вариант в файле указывать пакеты которые должны установить после запуска контейнера, помогите решить проблему пожалуйста.

**Comment by dotneft** [comment]
That is the main goal for images. If you need something additional for your infrastructure, customized things - you build your own image using official one images using some CI / automation. For example you can use hub.docker.com and automate such process. 

Regarding packages installation, usually container is running under non-root user, so you can not install anything into container.
