### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by ruzmat** [zabbix/zabbix-docker#1131]
Hi,
I'm trying to create an image with minor changes using dockerfile, but the docker compose build command gives an error, what could be the problem?

`failed to solve: zabbix-build-pgsql:ubuntu-6.4.11: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`

[docker-compose.txt](https://github.com/zabbix/zabbix-docker/files/14113577/docker-compose.txt)
[Dockerfile.txt](https://github.com/zabbix/zabbix-docker/files/14113578/Dockerfile.txt)

**Comment by dotneft** [comment]
available on hub.docker.com: https://hub.docker.com/layers/zabbix/zabbix-build-pgsql/ubuntu-6.4.11/images/sha256-313dbb619656cd5d6e6fa5e20b868fb0c2e3f433d73cad622cdad5a191dc7583?context=explore. Please check you permissions.

**Comment by ruzmat** [comment]
There was an error in the line dockerfile

ARG BUILD_BASE_IMAGE=zabbix-build-pgsql:ubuntu-${ZBX_VERSION}

Right

ARG BUILD_BASE_IMAGE=zabbix/zabbix-build-pgsql:ubuntu-${ZBX_VERSION}

**Comment by ruzmat** [comment]
When using this dockerfile, the container does not start because no permission for file /usr/bin/docker-entrypoint.sh

after the COPY line I added

RUN chmod +x /usr/bin/docker-entrypoint.sh

Is this dockerfile valid?

**Comment by dotneft** [comment]
Ah... yes, sorry, you need specify hub.docker.com namespace if you do not use local build images.

What is your Dockerfile and log after start?
