### ISSUE TITLE
Missing gzip package instalation in server-mysql/Dockerfile

### ISSUE THREAD

**Issue by kpodvolecky** [zabbix/zabbix-docker#1132]
##### SUMMARY

Running container from server-mysql:6.4.11 image fails due to line 274 in Dockerfiles/server-mysql/rhel/docker-entrypoint.sh which needs zcat command. As it is not in used RHEL 9.3 image.

I started mysql:8.2 container, then zabbix/zabbix-server-mysql-64 from redhat catalog. Starting then fails due to zcat command missing when creating schema.

##### OS / ENVIRONMENT / Used docker-compose files

Tested on arm64 architecture.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
Hm... thank you! Looks like RHEL removed the package from default. Will fix it as soon as possible.

**Comment by dotneft** [comment]
Please check. The issue was resolved!

**Comment by kpodvolecky** [comment]
Tested, works!
Thank you for your very quick response!
