### ISSUE TITLE
zabbix-server cannot ping

### ISSUE THREAD

**Issue by craffael** [zabbix/zabbix-docker#114]
Currently the user "zabbix" in the zabbix-server environment cannot ping a host because of permission problems:

    $ docker run --rm -it --user=100  zabbix/zabbix-server-mysql -c "ping 8.8.8.8"
      PING 8.8.8.8 (8.8.8.8): 56 data bytes
      ping: permission denied (are you root?)

**Comment by craffael** [comment]
It seems that installing iputils [resolves the problem](https://github.com/gliderlabs/docker-alpine/issues/253)

I.e. I suggest to also install the following package: 

    apk add iputils

to resolve the issue.

**Comment by dotneft** [comment]
fixed
