### ISSUE TITLE
zabbix-web-nginx-mysql works with non-root path?

### ISSUE THREAD

**Issue by galindro** [zabbix/zabbix-docker#120]
I'm trying to use a haproxy in front of zabbix-web-nginx-mysql container. My intention is to access zabbix webui through this address: http://i.sb/mon/admin. This is my haproxy.cfg:

```bash
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

    # disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

resolvers docker
    nameserver dns 127.0.0.11:53

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  http-keep-alive
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s


frontend services
    bind *:80
    bind *:443 ssl crt-list /cfg/crt-list.txt
    mode http

    acl url_mon_zabbix-web80 path_dir /mon/admin
    use_backend mon_zabbix-web-be80 if url_mon_zabbix-web80


backend mon_zabbix-web-be80
    mode http
    server mon_zabbix-web mon_zabbix-web:80
```

`mon_zabbix-web` is the DNS name of zabbix-web-nginx-mysql service. I'm running it in a swarm cluster environment.

When I access http://i.sb/mon/admin from web browser, the ui is trying to acess the static content (css,assets,js, etc...) in http://i.sb/mon, causing an error:

![image](https://user-images.githubusercontent.com/4622097/27808829-f1f4d782-6020-11e7-8f52-2cda09989d7d.png)

Am I making a mistake in haproxy.cfg? How could I make this proxy configuration works as I want?

**Comment by volnet** [comment]
I cannot access to my zabbix-web-nginx-web.

I check in my shell here: https://github.com/volnet/zabbix/blob/master/start_all.sh

who can help me?

I try 

1. http://10.211.55.7
2. http://10.211.55.7/mon/admin

but also cannot access to it.

**Comment by dotneft** [comment]
I believe you have incorrect config for haproxy, bu unfortunately it is not related to zabbix images at all.
