### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by artemkamolodets** [zabbix/zabbix-docker#124]
Hello, i'm trying to set up TLS encryption between zabbix server container and several agent instances. 
I have CA\Certificates\Keys, and i was test my configuration on virtual environment (without docker). But in production zabbix working in docker. The problem is after the copying certs\keys into exposed volume on host and starting container,  zabbix_server.conf file is always clearing by initial script:(/run_zabbix_component.sh). I was tryed to set certs\keys location via variables defined in this script, but without luck. 
Please help.

**Comment by ronnicek** [comment]
One solution could be save configuration localy and create volume with configuration from your host to Docker.

**Comment by dotneft** [comment]
Currently it is only one way how to use encryption. Please check zabbix images manual.
