### ISSUE TITLE
php.ini timezone

### ISSUE THREAD

**Issue by dinghao2020** [zabbix/zabbix-docker#125]
Modify timezone  in the /etc/php5/php.ini does not take effect, 
 I will be grateful  if it work.

[program:php-fpm]
command = /usr/bin/php-fpm -F -c /etc/php5/php.ini -y /etc/php5/php-fpm.conf
auto_start = true
autorestart = true

**Comment by Haitianisgood** [comment]
add ”  -e PHP_TZ="some-timezone"  “   when exec 'docker run'

**Comment by dotneft** [comment]
Please check manual.

**Comment by dinghao2020** [comment]
Very appreciate.
