### ISSUE TITLE
New environment variables

### ISSUE THREAD

**Issue by ISnotes** [zabbix/zabbix-docker#1258]
Good afternoon. There is a wonderful article on hardening Zabbix Server. It would be great to see options to be able to configure this in a docker via environment variables:
https://www.zabbix.com/documentation/current/en/manual/installation/requirements/best_practices

**Comment by ISnotes** [comment]
Additionally, it would be great to provide the ability to configure cipher suites

**Comment by dotneft** [comment]
You can configure cipher suites right now. No need to add additional variables.

**Comment by ISnotes** [comment]
Tell me how please

**Comment by dotneft** [comment]
use volume and replace current configuration file

**Comment by ISnotes** [comment]
Thank you. I managed. But to what extent is this the right option in the long term? Some parameters in the file may change with the release of new versions of the web server, in which case one of the updates may break the system

**Comment by dotneft** [comment]
If we will add env variables for each possible change / config option outside of Zabbix, configuration can be much more complex than currently. So if you want to change something outside of Zabbix - use your own config file.

**Comment by ISnotes** [comment]
Thanks for the answers, you helped a lot
