### ISSUE TITLE
upgrade docker zabbix appliance

### ISSUE THREAD

**Issue by Kawabountou** [zabbix/zabbix-docker#1269]
##### SUMMARY
Source : https://github.com/zabbix/zabbix-docker.git
docker-compose used : docker-compose_v3_ubuntu_mysql_6-2.yaml
OS : Debian 10.9

Action performed : 
modification of some value in docker-compose_v3_ubuntu_mysql_6-2.yaml
modification of some value in .env and .env_srv

Hi, 
I contact you because I would like to perform an update of this zabbix appliance.

I try to do a git pull : 
git pull
remote: Enumerating objects: 128, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 128 (delta 90), reused 103 (delta 66), pack-reused 0
Réception d'objets: 100% (128/128), 29.20 Kio | 2.65 Mio/s, fait.
Résolution des deltas: 100% (90/90), complété avec 27 objets locaux.
Depuis https://github.com/zabbix/zabbix-docker
 * [nouvelle branche]    dependabot/github_actions/docker/setup-buildx-action-3.1.0 -> origin/dependabot/github_actions/docker/setup-buildx-action-3.1.0
   6bbdc2d2c..99b66b9f4  trunk      -> origin/trunk
 * [nouvelle branche]    trunk_rhel -> origin/trunk_rhel
Votre information de configuration indique de fusionner avec la référence 'refs/heads/5.4'
du serveur distant, mais cette référence n'a pas été récupérée.

Now, I can't update the folder with git.

Could you help me to update zabbix appliance with git?

Thanks in advance.

Best regards,

Romain

**Comment by dotneft** [comment]
5.4 moved to archive. Please check archive/5.4 branch.

**Comment by Kawabountou** [comment]
Hi and thanks for your reply.

I am not an expert with git.

Is it possible to switch with the main branch?
I would like to update to the last version.

Best regards.

Romain
