### ISSUE TITLE
Graphs not working in zabbix-web-apache-mysql:ubuntu-6.0

### ISSUE THREAD

**Issue by zohairraza** [zabbix/zabbix-docker#1296]
##### SUMMARY
While using zabbix-web-apache-mysql:ubuntu-6.0-latest image (6.0.27) the graph fonts, it just shows empty area. Web server reported this error of PHP Warning:  imagettftext(): Could not find/open font in /usr/share/zabbix/include/graphs.inc.php on line 556. 

The include/defines.php file from zabbix-ui source has DejaVuSans hardcoded however Dockerflies are configured for NotoSansCJKjp-Regular 
define('ZBX_GRAPH_FONT_NAME', 'DejaVuSans'); // font file name

I changed this to NotoSansCJKjp-Regular and it worked

So web-apache-mysql-6.0 needs a fix in the UI since build-mysql image in that branch is using NotoSansCJKjp-Regular font
https://github.com/zabbix/zabbix-docker/blob/6.0/Dockerfiles/build-mysql/ubuntu/Dockerfile#L76

or maybe keep using DejaVuSans in 6.0 branch as it is faster but copy it in the sources instead of symlinking it from Linux distros. They keep changing the location.

This issue is similar to https://github.com/zabbix/zabbix-docker/issues/1077 but for ubuntu image and zabbix-6.0 
##### OS / ENVIRONMENT / Used docker-compose files
zabbix-web-apache-mysql:ubuntu-6.0-latest

##### STEPS TO REPRODUCE
Launch zabbix-web-apache-mysql:ubuntu-6.0-latest container and access graphs, they are not shown correctly

##### EXPECTED RESULTS
Graphs display as they normally do .

##### ACTUAL RESULTS
Fonts are missing and thus white screen

**Comment by dotneft** [comment]
Everything works fine:
```
% docker exec -ti zabbix-trunk3-zabbix-web-apache-mysql-1 cat include/defines.inc.php | grep font
define('ZBX_FONTPATH',				realpath('assets/fonts')); // where to search for font (GD > 2.0.18)
define('ZBX_GRAPH_FONT_NAME',		'NotoSansCJKjp-Regular'); // font file name
define('ZBX_STYLE_MONOSPACE_FONT', 'monospace-font');
```
sha256: 8fb8e156b63c934028d686abeb19bc023869e622d460f7eaea0d8239fcf62149

**Comment by zohairraza** [comment]
Oh I found what was wrong, I had defines file mounted from the UI sources because I needed more rows in Dashboard
    define('DASHBOARD_MAX_ROWS',		1000);

the file from UI source had DejaVuSans
https://github.com/zabbix/zabbix/blob/release/6.0/ui/include/defines.inc.php#L88 

however, this was altered by sed in Dockerfile
https://github.com/zabbix/zabbix-docker/blob/314467157be5ab383709ce4b93ddf61bcc0f0a82/Dockerfiles/build-pgsql/ubuntu/Dockerfile#L81


If there is another way of changing DASHBOARD_MAX_ROWS, please let me know

**Comment by dotneft** [comment]
mount with changed font :-)

**Comment by zohairraza** [comment]
yeah that works for now but not ideal as the UI sources are frequently updated I think. This graph font is an example 

Anyway, thanks for your input. I am closing the ticket
