### ISSUE TITLE
zabbix-web-nginx-pgsql:alpine-latest does not appear to have been updated to 3.4.0

### ISSUE THREAD

**Issue by mhurron** [zabbix/zabbix-docker#131]
zabbix-web-nginx-pgsql does not appear to have been updated to 3.4.0. Installing zabbix-server-pgsql:latest and letting it upgrade the database causes zabbix-web-nginx-pgsql:alpine-latest to fail with the following error:

Database error
		The frontend does not match Zabbix database. Current database version (mandatory/optional): 3040000/3040000. Required mandatory version: 3020000. Contact your system administrator.

Entering the container and changing `define('ZABBIX_DB_VERSION',		3020000);` to `define('ZABBIX_DB_VERSION',		3040000);` allows me to log in but then many SQL errors displayed in place of every widget and the version at the bottom of the screen is 'Zabbix 3.2.6. © 2001–2017, Zabbix SIA'

**Comment by dotneft** [comment]
Sorry for that. Please check again after 30-40 minutes

**Comment by th144** [comment]
I have the same problem with zabbix-web-nginx-mysql

**Comment by dsteinkopf** [comment]
same with zabbix-web-apache-mysql

**Comment by mhurron** [comment]
I see that zabbix-web-nginx-pgsql has been updated and appears to be running correctly. I don't know if you want to keep the issue open because of the other two reports.

**Comment by dotneft** [comment]
fixed.
