### ISSUE TITLE
Zabbix proxy on kubernetes are taking huge memory

### ISSUE THREAD

**Issue by tanmoyrsc** [zabbix/zabbix-docker#1311]
##### SUMMARY
Zabbix proxy container taking 12GB of memory on kubernetes cluster. install zabbix agent and proxy using helm chart on k8s and the zabbix server is running outside of k8s cluster. please share the settings for zabbix proxy to restrict the memory consumption.

##### OS / ENVIRONMENT / Used docker-compose files
K8s Cluster on Ubuntu Linux

Br,
Tanmoy

**Comment by dotneft** [comment]
Please use Zabbix official forum for troubleshooting. This place only for Zabbix images issues.
