### ISSUE TITLE
Monitoring MSSQL database wih zabbix-agent2

### ISSUE THREAD

**Issue by jurek224466** [zabbix/zabbix-docker#1334]
##### SUMMARY

Hi,
I have a problem with configuring MSSQL database monitoring. I added zabbix-agent2 in the container application, but I still cannot monitor the database. I don't know if the latest version of the image has plugins enabled. I don't see anything in the logs and I don't know how to configure it
Link to server image https://hub.docker.com/r/zabbix/zabbix-server-pgsql
Agent link https://hub.docker.com/r/zabbix/zabbix-agent2

##### OS / ENVIRONMENT / Used docker-compose files
Latest version Zabbix server 6.4.13

**Comment by dotneft** [comment]
any errors? What behaviour do you see?
