### ISSUE TITLE
Envarioment variable: EnableGlobalScripts for Zabbix 7.0.0beta3 doesn't exist

### ISSUE THREAD

**Issue by RagnesrocK** [zabbix/zabbix-docker#1339]
##### SUMMARY
Container download: https://github.com/zabbix/zabbix-docker 
Version 6.4

Edit the image tag to work with Zabbix 7.0.0beta3

The problem is that there is no environment variable to enable global scripts on Zabbix Server 7.0.0beta3

By default, in Zabbix 7.0.0beta3, it is disabled

##### OS / ENVIRONMENT / Used docker-compose files
Zabbix server 7.0 (tags: alpine-trunk)

Regards
![zbx7_gs](https://github.com/zabbix/zabbix-docker/assets/117693740/b43dfb3a-b230-4ba3-99f5-566e0f2bbf14)

**Comment by dotneft** [comment]
Fixed! Thank you!

**Comment by RagnesrocK** [comment]
Nice

Will the fix be in the upgrade or how can I do something in my current environment without modifying the docker image?

I tryed this: 
ZBX_ENABLEGLOBALSCRIPTS=1
but it didn't  work

Regards

**Comment by dotneft** [comment]
for me works fine:
```
% docker exec -ti zabbix-docker-zabbix-server-1 env | grep ENABLEGLOBALSCRIPTS
ZBX_ENABLEGLOBALSCRIPTS=1
% docker exec -ti zabbix-docker-zabbix-server-1 cat /etc/zabbix/zabbix_server.conf | grep -i ENABLEGLOBALSCRIPTS
### Option: EnableGlobalScripts
# EnableGlobalScripts=1
EnableGlobalScripts=1
```

**Comment by RagnesrocK** [comment]
In my case it does not work

% docker exec -ti zbx-server env | grep ENABLEGLOBALSCRIPTS
ZBX_ENABLEGLOBALSCRIPTS=1
% docker exec -ti zbx-server cat /etc/zabbix/zabbix_server.conf | grep -i ENABLEGLOBALSCRIPTS
### Option: EnableGlobalScripts
# EnableGlobalScripts=1
EnableGlobalScripts=0

%docker stop zbx-server
zbx-server

%docker rm zbx-server
zbx-server

%docker compose --profile all -f ingenieria_timescaledb_postgres_alpine.yaml build
%docker compose --profile all -f ingenieria_timescaledb_postgres_alpine.yaml up -d

[+] Running 8/8
 ✔ Container zabbix-docker-db_data_pgsql-1  Started                                                                                                                                    0.0s
 ✔ Container zbx-snmptraps                  Running                                                                                                                                    0.0s
 ✔ Container zbx-java-gateway               Running                                                                                                                                    0.0s
 ✔ Container zbx-timesacle-postgres         Running                                                                                                                                    0.0s
 ✔ Container zbx-webservice                 Running                                                                                                                                    0.0s
 ✔ Container zbx-agent                      Running                                                                                                                                    0.0s
 ✔ Container zbx-server                     Started                                                                                                                                    0.0s
 ✔ Container zbx-frontend                   Running   

**is the same result:**

%docker exec -ti zbx-server env | grep ENABLEGLOBALSCRIPTS
ZBX_ENABLEGLOBALSCRIPTS=1


%docker exec -ti zbx-server cat /etc/zabbix/zabbix_server.conf | grep -i ENABLEGLOBALSCRIPTS
### Option: EnableGlobalScripts
# EnableGlobalScripts=1
EnableGlobalScripts=0

I will edit the configuration file directly by connecting to the docker, then I will create a new image and work with this new docker.

Regards

**Comment by dotneft** [comment]
I do not know what is ingenieria_timescaledb_postgres_alpine.yaml, but if you use official containers or current trunk branch from this repo, everything will be ok.
