### ISSUE TITLE
[Request] zabbix-sender for server and proxy

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#137]
On traditional installs it's common that an agent is installed along a server or proxy. As that isn't the case in containers it's not possible for external scripts to use that feature for efficiently send data.

Would be great to include zabbix sender in the server and proxy containers.

**Comment by rockaut** [comment]
Hmm... i never realized that sender isn't even available in the agent containers? Why?

**Comment by dotneft** [comment]
Added. Thank you!

**Comment by dotneft** [comment]
server does not have any other components except zabbix_sender, zabbix_get.

**Comment by TerAnYu** [comment]
I wanted to tell what at the zabbix-appliance installation does not contain zabbix-agent, though when the container was started, it has the configured client - itself(himself).
Also found that in line [143](https://github.com/zabbix/zabbix-docker/blob/4.4/zabbix-appliance/alpine/docker-entrypoint.sh#L143) it is switched off by default.

Or any more there is no need to monitor service (in a container), but only a host or it is necessary to set [zabbix-agent](https://github.com/zabbix/zabbix-docker/tree/4.4/agent/alpine)
