### ISSUE TITLE
cannot use database "zabbix": Zabbix server cannot work with a Zabbix proxy database 

### ISSUE THREAD

**Issue by feixia5712** [zabbix/zabbix-docker#138]
ubuntu 14.04  x86_64

I have a problems,please help
such as
First  install  mysql
docker run --name zabbix-mysql-server --hostname zabbix-mysql-server \
-e MYSQL_ROOT_PASSWORD="123456" \
-e MYSQL_USER="zabbix" \
-e MYSQL_PASSWORD="123456" \
-e MYSQL_DATABASE="zabbix" \
--restart="always"
-p 3306:3306  \
-d \
mysql

Second  install  zabbix-server
docker run  --name zabbix-server-mysql --hostname zabbix-server-mysql \
--link zabbix-mysql-server:mysql \
-e DB_SERVER_HOST="mysql" \
-e MYSQL_USER="zabbix" \
-e MYSQL_DATABASE="zabbix" \
-e MYSQL_PASSWORD="123456" \
-p 10051:10051 \
-d \
zabbix/zabbix-server-mysql

Last  install  zabbix-web-nginx
docker run --name zabbix-web-nginx-mysql --hostname zabbix-web-nginx-mysql \
--link zabbix-mysql-server:mysql \
--link zabbix-server-mysql:zabbix-server \
-e DB_SERVER_HOST="mysql" \
-e MYSQL_USER="zabbix" \
-e MYSQL_PASSWORD="123456" \
-e MYSQL_DATABASE="zabbix" \
-e ZBX_SERVER_HOST="zabbix-server" \
-e PHP_TZ="Asia/Shanghai" \
-p 8000:80 \
-p 8443:443 \
-d \
zabbix/zabbix-web-nginx-mysql

but  i failed
docker  logs  zabbix-server-mysql 
Press Ctrl+C to exit.

   111:20170911:021729.804 Starting Zabbix Server. Zabbix 3.4.1 (revision 71734).
   111:20170911:021729.805 ****** Enabled features ******
   111:20170911:021729.805 SNMP monitoring:           YES
   111:20170911:021729.806 IPMI monitoring:           YES
   111:20170911:021729.806 Web monitoring:            YES
   111:20170911:021729.807 VMware monitoring:         YES
   111:20170911:021729.807 SMTP authentication:       YES
   111:20170911:021729.807 Jabber notifications:       NO
   111:20170911:021729.807 Ez Texting notifications:  YES
   111:20170911:021729.807 ODBC:                      YES
   111:20170911:021729.807 SSH2 support:              YES
   111:20170911:021729.807 IPv6 support:              YES
   111:20170911:021729.807 TLS support:               YES
   111:20170911:021729.807 ******************************
   111:20170911:021729.807 using configuration file: /etc/zabbix/zabbix_server.conf
   111:20170911:021729.817 cannot use database "zabbix": Zabbix server cannot work with a Zabbix proxy database
2017-09-11 02:17:29,818 INFO exited: zabbix-server (exit status 1; not expected)
2017-09-11 02:17:29,818 INFO exited: zabbix-server (exit status 1; not expected)
2017-09-11 02:17:30,821 INFO gave up: zabbix-server entered FATAL state, too many start retries too quickly
2017-09-11 02:17:30,821 INFO gave up: zabbix-server entered FATAL state, too many start retries too quickly

In  web
![image](https://user-images.githubusercontent.com/12670758/30409763-ab41d1da-9939-11e7-970c-015a1603b39c.png)

please  help

**Comment by abudoree** [comment]
when you install mysql-server in first step, you should add 
`--character-set-server=utf8 --collation-server=utf8_bin` when use image  mysql:5.7
like this :
`docker run --name mysql-server -t \`
      `-e MYSQL_DATABASE="zabbix" \`
      `-e MYSQL_USER="zabbix" \`
      `-e MYSQL_PASSWORD="zabbix_pwd" \`
      `-e MYSQL_ROOT_PASSWORD="root_pwd" \`
      `-d mysql:5.7 \`
      `--character-set-server=utf8 --collation-server=utf8_bin`

**Comment by dotneft** [comment]
fixed issue
