### ISSUE TITLE
Database Error: Unable to select configuration.

### ISSUE THREAD

**Issue by emersonramos** [zabbix/zabbix-docker#139]
Hi,

I used docker-compose_v2_ubuntu_mysql_latest.yaml and this error is displayed:

Database Error: Unable to select configuration.

I see at log that zabbix-proxy-mysql_1 and zabbix-proxy-sqlite3_1 are unable to connect to server zabbix-server.

**Comment by feixia5712** [comment]
I have the same problems

**Comment by emersonramos** [comment]
Any idea to fix it?

**Comment by feixia5712** [comment]
no

**Comment by feixia5712** [comment]
I used the previous mirror to succeed, but now die, I suspect that the mirror has done any changes.

**Comment by emersonramos** [comment]
I'm using docker-compose_v2_alpine_pgsql_latest.yaml 

No problem

**Comment by dotneft** [comment]
fixed. Please check it with new versions.

**Comment by rshukayl** [comment]
what change was for this fix?
