### ISSUE TITLE
how to make zabbix-web-nginx-pgsql to start-up and keep running even if zabbix db is not reachable

### ISSUE THREAD

**Issue by ArgyrisKefalas2022** [zabbix/zabbix-docker#1413]
##### SUMMARY
Hi, we have an implemintation with image: `zabbix/zabbix-web-nginx-pgsql:5.2.7-alpine`
We use the above nginx also for serving as reverse proxy for one more application that is running on the same host.
So, I want the container with image: `zabbix/zabbix-web-nginx-pgsql:5.2.7-alpine` to be up and running for serving the other application, even if in case the zabbix db is not deployed or available.

Currently the behaviour is the following, 
When the container with image: `zabbix/zabbix-web-nginx-pgsql:5.2.7-alpine` is starting its using the env parameters ,"POSTGRES_USER","ZBX_SERVER_NAME","POSTGRES_DB" an "POSTGRES_PASSWORD" to connect to the zabbix db,
and if these env parameters are not set, or if the zabbix db is not reachable then it shows this message:
**** PostgreSQL server is not available. Waiting 5 seconds...
and after few attempts it shuts down.

The behaviour that I want to achieve is that the nginx will start and be up and running so that it can serve as reverse proxy for the other application I have, regardless if zabbix db is available or not.
And whenever the db zabbix becomes available then to connect to it. But not to shutdown in case it cannot reach it at the start-up.

Do you have any recommendations? is there some parameter I can use for achieving this?

**Comment by dotneft** [comment]
update docker entrypoint script and remove DB availability, no other methods.

**Comment by ArgyrisKefalas2022** [comment]
Hi @dotneft if I remove the DB availability part from the entrypoint script, and lets say that the next day I will deploy the zabbix db. In this case once the zabbix db will be available and reachable again, is the nginx going to connect with it? Or after the change you propose in the script it is going to totally ignore the zabbix DB?

**Comment by dotneft** [comment]
Just remove this line https://github.com/zabbix/zabbix-docker/blob/archive/5.2/web-nginx-mysql/alpine/docker-entrypoint.sh#L263
but it is not a good idea at all. It is better to use behind Zabbix frontend some transparent proxy. For example, properly configured nginx.
