### ISSUE TITLE
Unable to upgrade from 6.4 to 7.0 Docker compose

### ISSUE THREAD

**Issue by wilcomike** [zabbix/zabbix-docker#1425]
##### SUMMARY
Unable to upgrade from 6.4 to 7.0 Docker compose

ran git pull which failed,

ran git stash then git pull

ran docker compose file see error:

> `user@wcdockerprod02:~/zabbix-docker$ sudo docker-compose -f docker-compose_v3_ubuntu_pgsql_latest.yaml up -d
ERROR: The Compose file '/home/user/zabbix-docker/compose_zabbix_components.yaml' is invalid because:
Unsupported config option for services.agent: 'attach'
Unsupported config option for services.agent2: 'attach'
Unsupported config option for services.java-gateway: 'attach'
Unsupported config option for services.proxy: 'attach'
Unsupported config option for services.server: 'attach'
Unsupported config option for services.snmptraps: 'attach'
Unsupported config option for services.web-apache: 'attach'
Unsupported config option for services.web-nginx: 'attach'
Unsupported config option for services.web-service: 'attach'
services.agent.env_file contains {"path": "./env_vars/.env_agent_override", "required": false}, which is an invalid type, it should be a string
services.agent2.env_file contains {"path": "./env_vars/.env_agent_override", "required": false}, which is an invalid type, it should be a string
services.proxy-mysql.env_file contains {"path": "./env_vars/.env_prx_mysql_override", "required": false}, which is an invalid type, it should be a string
services.java-gateway.env_file contains {"path": "./env_vars/.env_java_override", "required": false}, which is an invalid type, it should be a string
services.proxy-sqlite3.env_file contains {"path": "./env_vars/.env_prx_sqlite3_override", "required": false}, which is an invalid type, it should be a string
services.snmptraps.env_file contains {"path": "./env_vars/.env_snmptraps_override", "required": false}, which is an invalid type, it should be a string
services.server.env_file contains {"path": "./env_vars/.env_srv_override", "required": false}, which is an invalid type, it should be a string
services.web-apache.env_file contains {"path": "./env_vars/.env_web_override", "required": false}, which is an invalid type, it should be a string
services.web-nginx.env_file contains {"path": "./env_vars/.env_web_override", "required": false}, which is an invalid type, it should be a string
services.web-service.env_file contains {"path": "./env_vars/.env_web_service_override", "required": false}, which is an invalid type, it should be a string
`

##### OS / ENVIRONMENT / Used docker-compose files
Existing docker compose installation on 6.4. Ubuntu 22.04

**Comment by dotneft** [comment]
did you try to upgrade your docker / docker compose?

**Comment by wilcomike** [comment]
All packages are already up to date

`user@wcdockerprod02:~/zabbix-docker$ sudo apt update
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 https://esm.ubuntu.com/apps/ubuntu jammy-apps-security InRelease
Hit:7 https://esm.ubuntu.com/apps/ubuntu jammy-apps-updates InRelease
Hit:8 https://esm.ubuntu.com/infra/ubuntu jammy-infra-security InRelease
Hit:9 https://esm.ubuntu.com/infra/ubuntu jammy-infra-updates InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
5 packages can be upgraded. Run 'apt list --upgradable' to see them.
user@wcdockerprod02:~/zabbix-docker$ sudo apt list --upgradable
Listing... Done
bind9-dnsutils/jammy-updates 1:9.18.24-0ubuntu0.22.04.1 amd64 [upgradable from: 1:9.18.18-0ubuntu0.22.04.2]
bind9-host/jammy-updates 1:9.18.24-0ubuntu0.22.04.1 amd64 [upgradable from: 1:9.18.18-0ubuntu0.22.04.2]
bind9-libs/jammy-updates 1:9.18.24-0ubuntu0.22.04.1 amd64 [upgradable from: 1:9.18.18-0ubuntu0.22.04.2]
python3-update-manager/jammy-updates 1:22.04.20 all [upgradable from: 1:22.04.18]
update-manager-core/jammy-updates 1:22.04.20 all [upgradable from: 1:22.04.18]`

**Comment by wilcomike** [comment]
Docker version 26.1.3, build b72abbb
docker-compose version 1.29.2, build unknown

**Comment by dotneft** [comment]
```
% docker version        
Client:
 Version:           25.0.5
 API version:       1.44
 Go version:        go1.21.8
 Git commit:        5dc9bcc
 Built:             Tue Mar 19 15:02:31 2024
 OS/Arch:           darwin/arm64
 Context:           orbstack

Server: Docker Engine - Community
 Engine:
  Version:          25.0.5
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       e63daec
  Built:            Tue Mar 19 15:05:27 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.17
  GitCommit:        3a4de459a68952ffb703bbe7f2290861a75b6b67
 runc:
  Version:          1.1.12
  GitCommit:        51d5e94601ceffbbd85688df1c928ecccbfa4685
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
% docker compose version
Docker Compose version v2.27.0
```
everything is fine. You use pretty old compose version 1, use second version.

**Comment by wilcomike** [comment]
Just found that. was using docker-compose instead of 'docker compose'

**Comment by wilcomike** [comment]
Now that I'm able to run the compose file I'm getting an error regarding the overlapping netowrk address space.


user@wcdockerprod02:~/zabbix-docker$ sudo docker compose -f docker-compose_v3_ubuntu_pgsql_latest.yaml up -d
[+] Running 24/24
 ✔ zabbix-web-nginx-pgsql Pulled13.4s
   ✔ 49b384cc7b4a Pull complete3.9s
   ✔ e883d54d91cd Pull complete6.2s
   ✔ 6d765584ac2a Pull complete6.2s
   ✔ 12bad13b8a09 Pull complete11.8s
   ✔ 4f4fb700ef54 Pull complete11.8s
   ✔ 2d17c5e14b08 Pull complete11.8s
 ✔ zabbix-server Pulled9.6s
   ✔ 75b17cb98649 Pull complete3.8s
   ✔ bb1e66dd401f Pull complete3.8s
   ✔ eaaed24739ec Pull complete3.8s
   ✔ e4b787487e79 Pull complete3.9s
   ✔ 23cf67f501c0 Pull complete7.7s
   ✔ 911e1be06592 Pull complete7.8s
 ✔ postgres-server Pulled7.6s
   ✔ d25f557d7f31 Pull complete0.7s
   ✔ 4a712554db4c Pull complete0.7s
   ✔ f8c427bb79c9 Pull complete0.8s
   ✔ 5e59d3c894f8 Pull complete6.0s
   ✔ 881bc0862104 Pull complete6.1s
   ✔ ea013c8251d9 Pull complete6.1s
   ✔ c987087f7eb2 Pull complete6.1s
   ✔ 9fef4cd307a4 Pull complete6.2s
   ✔ 31d8f278690f Pull complete6.2s
[+] Running 1/0
 ✘ Network zabbix-docker_frontend  Error0.0s
failed to create network zabbix-docker_frontend: Error response from daemon: Pool overlaps with other one on this address space

**Comment by dotneft** [comment]
Fix project name for your installation and try again.
