### ISSUE TITLE
zabbix-agent2 latest missing armv7 builds

### ISSUE THREAD

**Issue by paskal** [zabbix/zabbix-docker#1427]
Hello!

Alpine images for Zabbix v7.0 and `latest` stopped being published for `arm/v7`, and as a result, building for this architecture stopped working in case `latest` or `alpine-latest` was used as a source image and retrieving such tag on this architecture now fails. Is it intentional? If not, could this change be reverted? 

https://hub.docker.com/r/zabbix/zabbix-agent2/tags?page=&page_size=&ordering=&name=alpine
<img width="575" alt="image" src="https://github.com/zabbix/zabbix-docker/assets/712534/b274d171-b5e1-4a3b-8897-09cfcf305a7a">

6.4 alpine images above still have `linux/arm/v7` listed, but 7.0 do not.

**Comment by paskal** [comment]
I found that it was done in 1b2b0f5cf60d34da047049ddb7fadbc14cc6e9ee; unfortunately, I can't find any related discussion.

I have no strong opinion on this topic, as I was building my images based on this for armv7 as it was available. If that's intentional, I can drop such a build from my image.

[<img width="959" alt="image" src="https://github.com/zabbix/zabbix-docker/assets/712534/75ffd068-bcd8-4648-b225-c8a8c7256a80">](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications)

I presume that the most popular device with that architecture is Raspberry Pi. In that case, all devices capable of running zabbix-agent released in 2016 and later support arm64 (armv8), and pragmatically speaking, it's sane decision to drop armv7.

**Comment by dotneft** [comment]
Hello! Ubuntu still supports ARMv7, Alpine supports ARMv7 till Zabbix 6.4. It is too old architecture to support it. Building ARMv7 on Alpine significantly increases building time without any real profit regarding supporting such architecture.
