### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by pschmitt** [zabbix/zabbix-docker#145]
Hi,

it'd be great to have official ARM images. Are there any plans for this?
I managed to build `zabbix-proxy-sqlite3-alpine` by simply using `resin/raspberrypi3-alpine:3.4` as a base image: https://gist.github.com/pschmitt/9ddf8d1e1b2646c78739c47b91dd6f3e
The other would certainly require more drastical changes, especially the ubuntu based images.

**Comment by dotneft** [comment]
It looks like raspberrypi3-alpine is not official Alpine release, so we can not provide it as official solution. Sorry.

**Comment by pschmitt** [comment]
@dotneft okay. What about using [arm32v6/alpine](https://hub.docker.com/r/arm32v6/alpine/) or [arm32v7/ubuntu](https://hub.docker.com/r/arm32v7/ubuntu/) as base images?

arm32v7 images at least are officially supported as per https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by dotneft** [comment]
Possible, I will try check it

**Comment by pschmitt** [comment]
For what is worth, I created [a script](https://github.com/pschmitt/zabbix-docker-armhf) that patches this here repository and builds armhf images using Travis CI.

It is using `resin/raspberry-pi-alpine:3.4` as a base image since there is alpine 3.4 image available for arm32v6 (and the resin images allow for easy cross-arch building).
The resulting images are available on Docker Hub and work fine on my Raspberry Pi 3.

- https://hub.docker.com/r/pschmitt/zabbix-agent-alpine-armhf/
- https://hub.docker.com/r/pschmitt/zabbix-proxy-mysql-alpine-armhf/
- https://hub.docker.com/r/pschmitt/zabbix-proxy-sqlite3-alpine-armhf/
- https://hub.docker.com/r/pschmitt/zabbix-web-apache-mysql-alpine-armhf/
- https://hub.docker.com/r/pschmitt/zabbix-web-apache-pgsql-alpine-armhf/
- https://hub.docker.com/r/pschmitt/zabbix-web-nginx-mysql-alpine-armhf/
- https://hub.docker.com/r/pschmitt/zabbix-web-nginx-pgsql-alpine-armhf/
- https://hub.docker.com/r/pschmitt/zabbix-server-mysql-alpine-armhf/
- https://hub.docker.com/r/pschmitt/zabbix-server-pgsql-alpine-armhf/

**Comment by dotneft** [comment]
Thank you! It is good idea, but still not sure about alpine. Is resin official repository?

**Comment by xenek** [comment]
Hi pschmitt, 

I'd also like an official Arm build that allows use of eg. Docker via Portainer on Rasberry Pi to be monitored via Zabbix Agent.

So, just trying this now, on my Odroid XU4 (also armhf or arm32v7) much like a Raspberry Pi,
Base OS is Ubuntu Mate 16.04.04 LTS  I think.

I see https://hub.docker.com/r/pschmitt/zabbix-agent-alpine-armhf/ is pretty empty, is there a plan for instructions? I'm using Portainer on Arm, not the terminal ;-)

Also see you have some stuff here.
https://github.com/pschmitt?utf8=%E2%9C%93&tab=repositories&q=zabbix&type=&language=

Here are my portainer Docker Gui setup 'notes'

Zabbix Agent (Arm HF / arm32v7 support!)
https://hub.docker.com/r/pschmitt/zabbix-agent-alpine-armhf/
Image Name pschmitt/zabbix-agent-alpine-armhf
Container name armzabbixagent
Always pull image
Don't publish exposed ports
No port mapping
Turn off access control
Set console to interactive & TTY
Set network to host, hostname to zabbixagent
Set restart policy
Set Runtime & Resources to Privileged 
Set both volumes with bind  /:/rootfs and /var/run:/var/run
(note host is the / and container is the /rootfs)
Set environment variables
 ZA_Server=yourprivatezabbixserver
 ZA_ServerActive=yourprivatezabbixserver



I tried this https://hub.docker.com/r/monitoringartist/dockbix-agent-xxl-limited/
but it responds with 
_init_linux.go:178: exec user process caused "exec format error"
Which is to be expected.


Yours looks much more promising, if I get all variables etc. right

(I've used monitoring artist's excellent instructions as a guide). The below is what I have so far. Any tips you can add those instructions would be great.




29T00:46:55.536110143Z ** Deploying Zabbix agent
,
29T00:46:55.536572057Z ** Preparing the system
,
29T00:46:55.537152178Z ** Preparing Zabbix agent
,
29T00:46:55.537508926Z ** Preparing Zabbix agent configuration file
,
29T00:46:55.543015935Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "PidFile": ''... removed
,
29T00:46:55.557517056Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogType": 'console'... added
,
29T00:46:55.561972488Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogFile": ''... removed
,
29T00:46:55.566427295Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogFileSize": ''... removed
,
29T00:46:55.570894060Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "DebugLevel": ''... removed
,
29T00:46:55.575279408Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "SourceIP": ''... removed
,
29T00:46:55.579933297Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "EnableRemoteCommands": ''... removed
,
29T00:46:55.585233891Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogRemoteCommands": ''... removed
,
29T00:46:55.585302390Z ** Using 'zabbix-server' servers for passive checks
,
29T00:46:55.597300568Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Server": 'zabbix-server'... updated
,
29T00:46:55.601806042Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenPort": ''... removed
,
29T00:46:55.606305806Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenIP": ''... removed
,
29T00:46:55.610789988Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "StartAgents": ''... removed
,
29T00:46:55.610830363Z ** Using 'zabbix-server:10051' servers for active checks
,
29T00:46:55.622131628Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ServerActive": 'zabbix-server:10051'... updated
,
29T00:46:55.626609518Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Hostname": ''... removed
,
29T00:46:55.631073575Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostnameItem": ''... removed
,
29T00:46:55.635488757Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostMetadata": ''... removed
,
29T00:46:55.639991105Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostMetadataItem": ''... removed
,
29T00:46:55.644545703Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "RefreshActiveChecks": ''... removed
,
29T00:46:55.649175217Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "BufferSend": ''... removed
,
29T00:46:55.653712731Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "BufferSize": ''... removed
,
29T00:46:55.658213246Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "MaxLinesPerSecond": ''... removed
,
29T00:46:55.662462804Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Timeout": ''... removed
,
29T00:46:55.676772218Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Include": '/etc/zabbix/zabbix_agentd.d/'... added first occurrence
,
29T00:46:55.681593189Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "UnsafeUserParameters": ''... removed
,
29T00:46:55.695808896Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LoadModulePath": '/var/lib/zabbix/modules/'... added
,
29T00:46:55.700934199Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSConnect": ''... removed
,
29T00:46:55.705428172Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSAccept": ''... removed
,
29T00:46:55.709815562Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCAFile": ''... removed
,
29T00:46:55.714396743Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCRLFile": ''... removed
,
29T00:46:55.719034549Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSServerCertIssuer": ''... removed
,
29T00:46:55.723578522Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSServerCertSubject": ''... removed
,
29T00:46:55.728109703Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCertFile": ''... removed
,
29T00:46:55.732898299Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSKeyFile": ''... removed
,
29T00:46:55.737389939Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSPSKIdentity": ''... removed
,
29T00:46:55.741815996Z ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSPSKFile": ''... removed
,
29T00:46:55.742375326Z ** Cleaning the system
,
29T00:46:55.742403118Z ########################################################
,
29T00:46:55.742988031Z ** Starting Zabbix agent
,
29T00:46:55.752599640Z Starting Zabbix Agent [zabbixagent]. Zabbix 3.4.8 (revision 79252).
,
29T00:46:55.752721806Z Press Ctrl+C to exit.
,
29T00:46:55.752762514Z 
,
29T00:46:55.752796889Z      1:20180429:004655.752 Starting Zabbix Agent [zabbixagent]. Zabbix 3.4.8 (revision 79252).
,
29T00:46:55.752832138Z      1:20180429:004655.752 **** Enabled features ****
,
29T00:46:55.752866347Z      1:20180429:004655.752 IPv6 support:          YES
,
29T00:46:55.752917971Z      1:20180429:004655.752 TLS support:           YES
,
29T00:46:55.752953554Z      1:20180429:004655.752 **************************
,
29T00:46:55.752987763Z      1:20180429:004655.752 using configuration file: /etc/zabbix/zabbix_agentd.conf
,
29T00:46:55.753027137Z      1:20180429:004655.752 agent #0 started [main process]
,
29T00:46:55.754053048Z     55:20180429:004655.753 agent #1 started [collector]
,
29T00:46:55.759108268Z     56:20180429:004655.754 agent #2 started [listener #1]
,
29T00:46:55.759176184Z     57:20180429:004655.754 agent #3 started [listener #2]
,
29T00:46:55.759235517Z     58:20180429:004655.755 agent #4 started [listener #3]
,
29T00:46:55.759260558Z     59:20180429:004655.755 agent #5 started [active checks #1]
,
29T00:46:55.768560711Z     59:20180429:004655.768 active check configuration update from [zabbix-server:10051] started to fail (cannot resolve [zabbix-server])
,

**Comment by yarons** [comment]
When I come to think about it I think it would be easier to keep all the parameters and use a simple `apk add zabbix-agent` on a clean Alpine 3.9 (With the "edge" repository enabled), this way it would be possible to avoid the compilation and still use the latest version.

This is the list of available packages (for all platforms):
https://pkgs.alpinelinux.org/packages?name=zabbix-agent&branch=edge

The only thing that needs porting are all the parameters.

**Comment by rockaut** [comment]
well but now as the arm32v6 and v7 packages are official it would fit pretty good to also support this architectures.
