### ISSUE TITLE
Error Decoding env_file in Docker Compose Configuration for Zabbix

### ISSUE THREAD

**Issue by vrain1025** [zabbix/zabbix-docker#1454]
Hello,

I'm encountering an issue when trying to set up Zabbix using Docker Compose. The command I'm running is:
docker compose -f ./docker-compose_v3_alpine_mysql_latest.yaml up -d
1 error(s) decoding:

* 'env_file[1]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[path:./env_vars/.env_java_override required:false]'

Docker version 26.1.3, build b72abbb
Docker Compose version v2.6.0

Any help or guidance on how to resolve this issue would be greatly appreciated. Thank you!

**Comment by dotneft** [comment]
Please upgrade docker compose to the latest stable version.

**Comment by vrain1025** [comment]
> 请将 docker compose 升级到最新的稳定版本。

Thank you, upgrading Docker Compose indeed solved the problem.
