### ISSUE TITLE
Invalid nginx config after restart container

### ISSUE THREAD

**Issue by adrianlzt** [zabbix/zabbix-docker#1458]
##### SUMMARY
Using the image `zabbix/zabbix-web-nginx-pgsql:6.0.31-ubuntu`, after restarting the container, the entrypoint command adds a new `user www-data;` line at the beggining of the `/etc/nginx/nginx.conf` file.
A duplicated line is invalid nginx config so the container does not work after a reboot.

The error was introduced in the commit https://github.com/zabbix/zabbix-docker/commit/e018c3030378f1e83eed923f135ce1cbd4f9c564

Probably a simple change like:
```
sed -i -e "/^[#;] user/s/.*/&\nuser ${DAEMON_USER};/" "$NGINX_CONF_FILE"
```
->
```
sed -i -e "/^[#;] user/s/.*/user ${DAEMON_USER};/" "$NGINX_CONF_FILE"
```
Should be enough to fix it.

**Comment by dotneft** [comment]
Thank you! Will check the issue.

**Comment by dotneft** [comment]
Fixed!
