### ISSUE TITLE
Zabbix Proxy Shutdowns Following Child Process Termination

### ISSUE THREAD

**Issue by RagnesrocK** [zabbix/zabbix-docker#1459]
SUMMARY
The Zabbix Proxy process intermittently shuts down immediately after a child process (PID:334) terminates. This issue appears to be triggered by a missing dependency (curl) within Docker containers running Alpine Linux 3.20, impacting the stability of Zabbix monitoring operations.

I am replicating the behavior of docker on a lab server, but it behaves the same on my 2 productive proxy servers.
The proxy server only has the curl script test monitor.

OS / ENVIRONMENT / Used docker-compose files
Docker version: Docker version 24.0.7, build afdd53b
Container OS: Alpine Linux 3.20
Docker-compose configuration:  (docker compose was cut to be used as a proxy)

[root@lab zabbix-docker]# cat docker-compose_v3_alpine_pgsql_latest_proxy.yaml
services:
  zabbix-proxy-sqlite3:
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.0-latest
    container_name: zbx-proxy-sqlite3
    profiles:
      - all
    ports:
      - "10061:10051"
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - /etc/timezone:/etc/timezone:rw
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:rw
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:rw
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:rw
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:rw
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '1'
          memory: 1G
    env_file:
      - ./env_vars/.env_prx
      - ./env_vars/.env_prx_sqlite3
    depends_on:
      - zabbix-java-gateway
      - zabbix-snmptraps
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-proxy-sqlite3
          - zabbix-proxy-alpine-sqlite3
          - zabbix-proxy-sqlite3-alpine
      zbx_net_frontend:
    stop_grace_period: 30s
    labels:
      com.zabbix.description: "Zabbix proxy with SQLite3 database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-proxy"
      com.zabbix.dbtype: "sqlite3"
      com.zabbix.os: "alpine"

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    container_name: zbx-agent2
    profiles:
      - full
      - all
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 64M
      mode: global
    env_file:
      - ./env_vars/.env_agent
    privileged: true
    pid: "host"
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-agent
          - zabbix-agent-passive
          - zabbix-agent-alpine
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "alpine"

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-7.0-latest
    container_name: zbx-java-gateway
    profiles:
      - full
      - all
    ports:
      - "10052:10052"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    env_file:
      - ./env_vars/.env_java
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-java-gateway
          - zabbix-java-gateway-alpine
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix Java Gateway"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "java-gateway"
      com.zabbix.os: "alpine"

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:alpine-7.0-latest
    container_name: zbx-proxy-snmp
    profiles:
      - full
      - all
    ports:
      - "162:1162/udp"
    volumes:
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      zbx_net_frontend:
        aliases:
          - zabbix-snmptraps
      zbx_net_backend:
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix snmptraps"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "snmptraps"
      com.zabbix.os: "alpine"

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24

volumes:
  snmptraps:

CONFIGURATION
No specific configurations were altered beyond standard Zabbix Docker image deployments. The issue persists across multiple Zabbix Proxy instances within our Dockerized environment.

STEPS TO REPRODUCE
Start a Docker container with Zabbix Proxy using Alpine Linux 3.20.
Execute a script within the Zabbix external scripts directory that attempts to execute a curl command.
Observe the Zabbix Proxy process termination following the script's execution.

Debug script

/usr/lib/zabbix/externalscripts # ls
check_url.sh
/usr/lib/zabbix/externalscripts #
/usr/lib/zabbix/externalscripts #
/usr/lib/zabbix/externalscripts # bash -x check_url.sh www.google.com
+ '[' 1 -lt 1 ']'
+ WEB_SITE_URL=www.google.com
+ '[' 1 -gt 1 ']'
+ TEXT_TO_SEARCH=
++ timeout 28 curl --connect-timeout 28 -X GET --insecure -s --output /dev/null -w '%{http_code} %{time_total}' www.google.com
timeout: can't execute 'curl': No such file or directory
+ curl_output=
++ echo ''
++ awk '{print $1}'
+ HTTP_CODE=
++ echo ''
++ awk '{print $2}'
+ TIME_TOTAL=
+ '[' -z '' ']'
+ HTTP_CODE=000
+ TIME_TOTAL=28
+ '[' '!' -z '' ']'
+ TEXT_FOUND=0
+ JSON_OUTPUT='{"http_code": "000", "time_total": "28", "text_found": "0"}'
+ echo '{"http_code": "000", "time_total": "28", "text_found": "0"}'
{"http_code": "000", "time_total": "28", "text_found": "0"}
/usr/lib/zabbix/externalscripts #

here the docker crashes and returns me to the prompt at the operating system level
/usr/lib/zabbix/externalscripts # [root@lab zabbix-docker]#
[root@lab zabbix-docker]#

EXPECTED RESULTS
The Zabbix Proxy should continue to operate normally, handling script executions gracefully even when external dependencies such as curl are not present.

ACTUAL RESULTS
Following the script's attempt to execute curl without the dependency installed, the Zabbix Proxy abruptly terminates. Logs indicate a sudden halt of the Proxy process without error messages or warnings.

paste
Copy code
1:20240717:093028.215 End of zbx_ipc_service_recv():2
1:20240717:093028.215 One child process died (PID:334,exitcode/signal:0). Exiting ...
1:20240717:093028.215 zbx_on_exit() called with ret:-1
1:20240717:093028.222 In zbx_db_connect() flag:1
1:20240717:093028.223 query without transaction detected
1:20240717:093028.223 query [txnlev:0] [pragma synchronous=0]
1:20240717:093028.232 query without transaction detected
1:20240717:093028.232 query [txnlev:0] [pragma foreign_keys=on]
1:20240717:093028.232 query without transaction detected
1:20240717:093028.232 query [txnlev:0] [pragma temp_store=2]
1:20240717:093028.232 query without transaction detected
1:20240717:093028.232 query [txnlev:0] [pragma temp_store_directory='/var/lib/zabbix/db_data/']
1:20240717:093028.232 End of zbx_db_connect():0
1:20240717:093028.232 In zbx_free_database_cache()
1:20240717:093028.232 In DCsync_all()
1:20240717:093028.232 In sync_history_cache_full() history_num:0
1:20240717:093028.232 End of sync_history_cache_full()
1:20240717:093028.232 End of DCsync_all()
1:20240717:093028.232 End of zbx_free_database_cache()
1:20240717:093028.232 In zbx_free_configuration_cache()
1:20240717:093028.232 End of zbx_free_configuration_cache()
1:20240717:093028.233 In zbx_deinit_remote_commands_cache()
1:20240717:093028.233 End of zbx_deinit_remote_commands_cache()
1:20240717:093028.233 In zbx_vmware_destroy()
1:20240717:093028.233 End of zbx_vmware_destroy()
1:20240717:093028.233 In zbx_free_selfmon_collector() collector.monitor:0x7f935e4fa170
1:20240717:093028.233 End of zbx_free_selfmon_collector()
1:20240717:093028.233 In zbx_unload_modules()
1:20240717:093028.233 End of zbx_unload_modules()
1:20240717:093028.233 Zabbix Proxy stopped. Zabbix 7.0.0 (revision 49955f1).
1:20240717:093028.233 In zbx_ipc_service_close() path:rtc
1:20240717:093028.233 In zbx_ipc_socket_close()
1:20240717:093028.234 End of zbx_ipc_socket_close()
1:20240717:093028.234 In zbx_ipc_socket_close()
1:20240717:093028.234 End of zbx_ipc_socket_close()
1:20240717:093028.234 In zbx_ipc_socket_close()

**Comment by RagnesrocK** [comment]
Attached complete log file
[error_1.zip](https://github.com/user-attachments/files/16272294/error_1.zip)

Regards

**Comment by dotneft** [comment]
Did you try to use "init" option?

**Comment by RagnesrocK** [comment]
Thats works fine, i'll use in all my zabbix instances.

regards
