### ISSUE TITLE
zabbix-proxy-pgsql image

### ISSUE THREAD

**Issue by LeHigh75** [zabbix/zabbix-docker#1464]
##### SUMMARY

Hello, in my company we use PostgreSQL as our database system for almost everything, we are actually building a new dockerized zabbix platform, include proxies.

The problem is i can t find a zabbix-proxy-pgsql image anywhere, that s a nonsense that you provide resources to use postgresql except for the proxy, is there any particular reason ? 

greetings

**Comment by dotneft** [comment]
Please check #913
