### ISSUE TITLE
Manually updating auditlog to hypertable after Zabbix 7.0 upgrade with timescaledb

### ISSUE THREAD

**Issue by kallama** [zabbix/zabbix-docker#1471]
##### SUMMARY

For those of us running the timescaledb container for our database,  [https://www.zabbix.com/documentation/current/en/manual/appendix/install/timescaledb#configuration](https://www.zabbix.com/documentation/current/en/manual/appendix/install/timescaledb#configuration) mentions having to manually run /usr/share/zabbix-sql-scripts/postgresql/timescaledb/schema.sql against the zabbix database after upgrading to 7.0. I don't see see this file anywhere to manually run it myself against my timescaledb container.

> For existing installations, when upgrading to Zabbix 7.0.0 or 7.0.2 from previous versions (for example, 6.0 to 7.0.0 or 6.4 to 7.0.2, or 7.0.0 to 7.0.2):
> 
> Start Zabbix server; this will upgrade the existing database.
> Check the server log file that the database upgrade has been successful; if so, stop Zabbix server and proceed to the next step.
> Run the postgresql/timescaledb/schema.sql script (since Zabbix 7.0.0, the script's location and name has been changed from postgresql/timescaledb.sql to postgresql/timescaledb/schema.sql). Note that Zabbix server will log a warning if started without running this script.

In my Zabbix log file I see the following:

```
266:20240726:164211.918 [Z3005] query failed: [0] PGRES_FATAL_ERROR:ERROR:  "auditlog" is not a hypertable or a continuous aggregate
 [select add_compression_policy('auditlog', compress_created_before => interval '612000')]
   266:20240726:164211.918 failed to add compression policy to table 'auditlog'
```

Can this file be provided somewhere so it can be manually applied like the instructions state?

**Comment by kallama** [comment]
In addition to 7.0 converting the auditlog table to hypertable, 7.0.2 converts the history_bin table, which also requires running schema.sql. [https://www.zabbix.com/documentation/7.0/en/manual/introduction/whatsnew702#binary-data-history-converted-to-hypertable-on-timescaledb](https://www.zabbix.com/documentation/7.0/en/manual/introduction/whatsnew702#binary-data-history-converted-to-hypertable-on-timescaledb)

**Comment by kallama** [comment]
Probably not the most efficient way, but I spun up a Debian VM and followed instructions on [https://www.zabbix.com/download](https://www.zabbix.com/download) to `apt install zabbix-sql-scripts` and grabbed the 7.0.2 version of schema.sql. I then brought my container stack down, pulled the 7.0.2 images, brought the stack up, brought the stack down, brought up only the timescaledb container, and ran `cat zabbix_schema_7.0.2.sql | docker exec -i zabbix-docker-postgres-server-1 psql -U zabbix zabbix`. I then brought the rest of the stack up and all seems well so far.

Gist of schema.sql for 7.0.2 is here [https://gist.github.com/kallama/041255c1db5b455b1569e3539ce43375](https://gist.github.com/kallama/041255c1db5b455b1569e3539ce43375)

**Comment by dotneft** [comment]
Hello! Please check /usr/share/doc/zabbix-server-postgresql/timescaledb.sql file. It is /timescaledb/schema.sql.

**Comment by kallama** [comment]
> Hello! Please check /usr/share/doc/zabbix-server-postgresql/timescaledb.sql file. It is /timescaledb/schema.sql.

I just checked on zabbix/zabbix-server-pgsql:alpine-7.0.2 and you are correct, `/usr/share/doc/zabbix-server-postgresql/timescaledb.sql` is the same file as baremetals `/usr/share/zabbix-sql-scripts/postgresql/timescaledb/schema.sql`.

**Comment by dotneft** [comment]
Is it helpful? :-)
