### ISSUE TITLE
Some updates were forgotten when releasing new releases

### ISSUE THREAD

**Issue by neids0n** [zabbix/zabbix-docker#1476]
##### SUMMARY

In .env the zabbix image tags remains -7.0 instead of -7.0.2, for example.

The images on docker hub are no longer finalized with -latest. I had to comment out the line ZABBIX_IMAGE_TAG_POSTFIX=-latest in the .env file and remove ${ZABBIX_IMAGE_TAG_POSTFIX} in the docker-compose file

**Comment by dotneft** [comment]
Sorry, but still the same logic: https://hub.docker.com/layers/zabbix/zabbix-server-mysql/alpine-7.0-latest/images/sha256-1d87e558fbb4384d1ef7be6e235bb0eb3ffd4df9efa15e00ddb7a04cf4a02404?context=explore. Please elaborate the problem.

**Comment by neids0n** [comment]
I said regarding versions 7.0.1: 
https://hub.docker.com/layers/zabbix/zabbix-server-mysql/alpine-7.0.1/images/sha256-6a0d0a1468f6b0809272b138d53e4281568e365d8af3f9dd4383b99b76088fd3?context=explore 
and 7.0.2:
https://hub.docker.com/layers/zabbix/zabbix-server-mysql/alpine-7.0.2/images/sha256-96cb44e49f2a40f372529dadb07275109420bfae7c78e39b34cd482fc7720912?context=explore

These versions no longer end with -latest.

**Comment by dotneft** [comment]
Latest tag applied only to major versions. If you check my previous comment URl, there is alpine-7.0-latest. What "latest" tag you are talking?

**Comment by neids0n** [comment]
Sorry, I downloaded version 7.0.2 and when I updated my zabbix it reverted back to version 7.0.
I tried to reproduce it now with a fresh install and version 7.0.2 worked fine.
I will revew my original installation. Thanks!!

**Comment by neids0n** [comment]
By the way, do you know how I keep the zabbix server agent IP when I recreate the containers?

**Comment by dotneft** [comment]
It depends on your infrastructure and what network driver you use, please, check docker official documentation: https://docs.docker.com/reference/cli/docker/network/create/. Anyway, it is better to use DNS instead of IP.
