### ISSUE TITLE
Hope get  more simple  docker compose configuration.

### ISSUE THREAD

**Issue by chlinwei** [zabbix/zabbix-docker#1481]
##### SUMMARY

I have much experience in zabbix and know docker, docker compose .
But this zabbix-docker repo is too complicated for me . I think many people have same thoughts with me .
I hope the offical  can give us some simple configuration . So that we can copy it and modify it by ourselves.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
Sorry, what kind of examples do you want?

**Comment by chlinwei** [comment]
Thank you for your prompt rely.
I use zabbix-server-mysql,zabbix-web-nginx-mysql,zabbix-agent2.  
This probably is the smallest composation.
I hope to get this type of examples. 
Thank you.

**Comment by dotneft** [comment]
still not clear what you want. If you just execute docker compose up -d, you already will have everything except zabbix-agent2.

**Comment by kernbug** [comment]
You have minimal examples how to start containers here: https://www.zabbix.com/documentation/7.0/en/manual/installation/containers

Also you can start as already mentioned like this:
` docker compose -f docker-compose_v3_alpine_pgsql_latest.yaml up -d `

And it will give minimal amount of containers: 3 - Frontend, Server, Database. 

Compose files are given as-is as an example, full featured example of latest compose options and Zabbix related things, if you don't like this example -  feel free to modify it as needed in your environment, provided examples are not suited for every environment and should be adopted anyway (Kubernetes, Podman, Docker, Docker SWARM). 

Using container technologies assumes some knowledge to be learned before, like any other technology.

**Comment by luweijun1992** [comment]
Yes, the docker compose file in Zabbix 7 is too complicated, and it associates several files.
It was good before, with just one file

**Comment by dotneft** [comment]
it was separated into a few files by meaning to simplify understanding :-D

**Comment by luweijun1992** [comment]
> it was separated into a few files by meaning to simplify understanding :-D



> it was separated into a few files by meaning to simplify understanding :-D

Separation becomes complicated
Originally one file could be used to view all the contents, but now 2-3 files need to be combined to view

**Comment by dotneft** [comment]
You can view all content right now, just use config parameter for compose.

**Comment by luweijun1992** [comment]
> You can view all content right now, just use config parameter for compose.

So the compose file of version 7 has become more complicated, with several files strung together. It is better to get used to the one file of version 6.

**Comment by dotneft** [comment]
options and features can be different, so it is not a good idea. Also 6 version have the same structure :-)
