### ISSUE TITLE
zabbix-agent: Support for https in wget and/or curl in the alpine image

### ISSUE THREAD

**Issue by riav** [zabbix/zabbix-docker#149]
Support for https in wget and / or curl in the alpine image, in order to create custom scripts in agentd.d

**Comment by riav** [comment]
zabbix/zabbix-agent:alpine-3.4-latest

bash-4.3# curl
bash: curl: command not found
bash-4.3# wget https://www.google.com
Connecting to www.google.com (172.217.29.164:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer

**Comment by ronnicek** [comment]
I am running custom script called "afterstart.sh" where I run this to install my dependencies which I need :)
```docker exec zabbix_zabbix-server_1 bash -c "apt update && apt install -y openssl bc python-requests"```

**Comment by dotneft** [comment]
Actually I'm not sure that is required in vanilla images. They should be provided ONLY with Zabbix components.
