### ISSUE TITLE
Current docker is broken - ssl errors

### ISSUE THREAD

**Issue by bbrendon** [zabbix/zabbix-docker#1490]
using 6.4-latest...

From inside the container...

```
7a598cc9cbb9:/tmp# apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
288BAE2DFC7E0000:error:0A000410:SSL routines:ssl3_read_bytes:ssl/tls alert handshake failure:ssl/record/rec_layer_s3.c:907:SSL alert number 40
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.20/main: Permission denied
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
288BAE2DFC7E0000:error:0A000410:SSL routines:ssl3_read_bytes:ssl/tls alert handshake failure:ssl/record/rec_layer_s3.c:907:SSL alert number 40
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.20/community: Permission denied
4 unavailable, 0 stale; 71 distinct packages available
```

**Comment by dotneft** [comment]
Execute the command under root.

**Comment by bbrendon** [comment]
# dc exec -u root zabbix-server bash
7a598cc9cbb9:/var/lib/zabbix# apk update
fetch
https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
289B2DAFD47F0000:error:0A000410:SSL routines:ssl3_read_bytes:ssl/tls alert
handshake failure:ssl/record/rec_layer_s3.c:907:SSL alert number 40
WARNING: updating and opening
https://dl-cdn.alpinelinux.org/alpine/v3.20/main: Permission denied
fetch
https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
289B2DAFD47F0000:error:0A000410:SSL routines:ssl3_read_bytes:ssl/tls alert
handshake failure:ssl/record/rec_layer_s3.c:907:SSL alert number 40
WARNING: updating and opening
https://dl-cdn.alpinelinux.org/alpine/v3.20/community: Permission denied
4 unavailable, 0 stale; 71 distinct packages available
7a598cc9cbb9:/var/lib/zabbix#

**Comment by bbrendon** [comment]
I figured this out.
Cloudflare was denying access because it didn't like how I had my DNS configured. No idea why they care, but ...
