### ISSUE TITLE
zabbix-docker return error run docker compose for the first time

### ISSUE THREAD

**Issue by dpsw1203** [zabbix/zabbix-docker#1494]
hello everyone, i got some problem first time installation running docker compose for zabbix-docker
i just run it without edit anything but returned with error below.

> docker compose -f docker-compose_v3_alpine_pgsql_latest.yaml up -d
1 error(s) decoding:
>
>'* 'env_file[1]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[path:./env_vars/.env_snmptraps_override required:false]'

Please help, thanks

**Comment by dotneft** [comment]
Hello! What docker compose version do you use?

**Comment by dpsw1203** [comment]
I'm running Docker Compose version v2.21.0

**Comment by dotneft** [comment]
Update it, please.

**Comment by dpsw1203** [comment]
Oh yes after upgraded it to Docker Compose version v2.29.1 no error appear, thank you very much.
