### ISSUE TITLE
Allow configuring proxy PSK from environment

### ISSUE THREAD

**Issue by Ricaz** [zabbix/zabbix-docker#1495]
We can already set database passwords through environment.
Please allow us to set PSK as well.

**Comment by dotneft** [comment]
please provide more details about what you would like to configure

**Comment by Ricaz** [comment]
> please provide more details about what you would like to configure

You can set environment variables in the image, like `MYSQL_PASSWORD`, but for the PSK (used for encryption between server and proxy), you can only specify a file to load it from.

I would like to be able to configure the PSK directly as an environment variable.

**Comment by dotneft** [comment]
Yes, because it is TLSPSKFile. What is the problem to specify file?

**Comment by Ricaz** [comment]
The other environment variables have options to set values directly _and_ a `_FILE` option, so why not keep it consistent and have one for PSK as well? It's just a string.

Better to avoid having to mount files into the container when possible. It saves the trouble of managing permissions outside the container, especially when the services inside run as a special `zabbix` user.

Docker doesn't allow mounting secrets as specific users or different access modes, outside of Swarm. That means you have to create another user on the host system with the same UID as inside the container, or make it readable by all users.

**Comment by dotneft** [comment]
Added new options. Please check them! :-)
