### ISSUE TITLE
ERROR: Error: cannot set cURL option CURLOPT_INTERFACE: A libcurl function was given a bad argument.

### ISSUE THREAD

**Issue by dpsw1203** [zabbix/zabbix-docker#1497]
Hello, i recently upgrade my zabbix-docker from 6.4 to 7.0 and i encounter this error 

> ERROR: Error: cannot set cURL option CURLOPT_INTERFACE: A libcurl function was given a bad argument. 

and my zabbix-docker-zabbix-web-nginx-pgsql container status is unhealthy this error shows when i'm using Discord Media, Proxmox HTTP and Fortigate HTTP.
Please help, thank you

**Comment by dotneft** [comment]
Unfortunately it is known issue, related to curl 8.9.0: https://support.zabbix.com/browse/ZBX-24926. Currently you can try to  use different image for Zabbix server (Ubuntu for example or Alpine but 7.0.1). Closing, as it is not related directly to Docker images.

**Comment by dpsw1203** [comment]
if i do docker compose down and running with the ubuntu, all data remain?

**Comment by dotneft** [comment]
yes. DB is different image.

**Comment by dpsw1203** [comment]
oke but i'm still using postgres 15 because if use 16 the db can't start

**Comment by dotneft** [comment]
what is the problem? Just replace server image to ubuntu one in your compose file

**Comment by dpsw1203** [comment]
i think switching from alpine to ubuntu is fine but it's taking longer
![image](https://github.com/user-attachments/assets/18b66bd2-d74c-4362-bdfe-77150c124b35)
is it because im still using postgres 15?

**Comment by dotneft** [comment]
What longer?
