### ISSUE TITLE
Frontend startup gets error: sed: bad option in substitution expression

### ISSUE THREAD

**Issue by zheng-liang** [zabbix/zabbix-docker#150]
When start the frontend container(alpine images), logs contain sed exceptions:

zbx-web   | ** Updating '/etc/php5/conf.d/99-zabbix.ini' parameter "post_max_size": '16M'... updated
zbx-web   | ** Updating '/etc/php5/conf.d/99-zabbix.ini' parameter "upload_max_filesize": '2M'... updated
zbx-web   | ** Updating '/etc/php5/conf.d/99-zabbix.ini' parameter "max_input_time": '300'... updated
zbx-web   | ** Updating '/etc/php5/conf.d/99-zabbix.ini' parameter "date.timezone": '"America/Toronto"'... added
zbx-web   | sed: bad option in substitution expression
zbx-web   | ** Cleaning the system
zbx-web   | ########################################################
zbx-web   | ** Executing supervisord
zbx-web   | 2017-10-13 23:29:41,414 CRIT Set uid to user 0
zbx-web   | 2017-10-13 23:29:41,414 CRIT Set uid to user 0

Try access the frontend pages, gets a red box: "Database error --- Error connecting to database: "

In the container, /etc/zabbix/web/zabbix.conf.php:

<?php
// Zabbix GUI configuration file.
global $DB;

$DB['TYPE']     = 'MYSQL';
$DB['SERVER']   = '{DB_SERVER_HOST}';
$DB['PORT']     = '{DB_SERVER_PORT}';
$DB['DATABASE'] = '{DB_SERVER_DBNAME}';
$DB['USER']     = '{DB_SERVER_USER}';
$DB['PASSWORD'] = '{DB_SERVER_PASS}';

// Schema name. Used for IBM DB2 and PostgreSQL.
$DB['SCHEMA'] = '';

$ZBX_SERVER      = '{ZBX_SERVER_HOST}';
$ZBX_SERVER_PORT = '{ZBX_SERVER_PORT}';
$ZBX_SERVER_NAME = '{ZBX_SERVER_NAME}';

$IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
?>

**Comment by zheng-liang** [comment]
I tried on both Apache and Nginx image, and got the same results

**Comment by dotneft** [comment]
Please post full command to create container.

**Comment by dotneft** [comment]
no response

**Comment by mbrrg** [comment]
Just ran into the same problem. I believe it is related to `sed`on Alpine not supporting everything that works on Ubuntu for example.

```
 # Escaping "/" character in parameter value
    server_name=${ZBX_SERVER_NAME//\//\\/}

   sed -i \
        -e "s/{DB_SERVER_HOST}/${DB_SERVER_HOST}/g" \
        -e "s/{DB_SERVER_PORT}/${DB_SERVER_PORT}/g" \
        -e "s/{DB_SERVER_DBNAME}/${DB_SERVER_DBNAME}/g" \
        -e "s/{DB_SERVER_USER}/${DB_SERVER_ZBX_USER}/g" \
        -e "s/{DB_SERVER_PASS}/${DB_SERVER_ZBX_PASS}/g" \
        -e "s/{ZBX_SERVER_HOST}/${ZBX_SERVER_HOST}/g" \
        -e "s/{ZBX_SERVER_PORT}/${ZBX_SERVER_PORT}/g" \
        -e "s/{ZBX_SERVER_NAME}/$server_name/g" \
"$ZBX_WEB_CONFIG"
```
I think it's the "/" replacements in the server_name assignment that makes it break. Worth noting is that this error completely breaks the Alpine Mysql image as it can't connect to the database whatever the environment variables are set to.

**Comment by Titinux** [comment]
Same problem here with the zabbix-web-nginx-pgsql docker image. Container is not working at all.

**Comment by mbrrg** [comment]
I couldn't get the Ubuntu image working either. Gave up and installed on a VM instead. :-(

**Comment by dotneft** [comment]
Please show logs.

**Comment by Titinux** [comment]
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Preparing the system
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Preparing Zabbix web-interface
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ********************
zabbix-web.1.sim5stkgxm0m@groseillier-001    | * DB_SERVER_HOST: postgres
zabbix-web.1.sim5stkgxm0m@groseillier-001    | * DB_SERVER_PORT: 5432
zabbix-web.1.sim5stkgxm0m@groseillier-001    | * DB_SERVER_DBNAME: zabbix
zabbix-web.1.sim5stkgxm0m@groseillier-001    | * DB_SERVER_ZBX_USER: zabbix
zabbix-web.1.sim5stkgxm0m@groseillier-001    | sed: bad option in substitution expression
zabbix-web.1.sim5stkgxm0m@groseillier-001    | * DB_SERVER_ZBX_PASS: password
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ********************
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Disable default vhosts
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Adding Zabbix virtual host (HTTP)
zabbix-web.1.sim5stkgxm0m@groseillier-001    | **** Impossible to enable SSL support for Nginx. Certificates are missed.
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Preparing Zabbix frontend configuration file
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Updating '/etc/php5/conf.d/99-zabbix.ini' parameter "max_execution_time": '600'... updated
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Updating '/etc/php5/conf.d/99-zabbix.ini' parameter "memory_limit": '128M'... updated
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Updating '/etc/php5/conf.d/99-zabbix.ini' parameter "post_max_size": '16M'... updated
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Updating '/etc/php5/conf.d/99-zabbix.ini' parameter "upload_max_filesize": '2M'... updated
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Updating '/etc/php5/conf.d/99-zabbix.ini' parameter "max_input_time": '300'... updated
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Updating '/etc/php5/conf.d/99-zabbix.ini' parameter "date.timezone": 'Europe/Paris'... added
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Cleaning the system
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ########################################################
zabbix-web.1.sim5stkgxm0m@groseillier-001    | ** Executing supervisord
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:04,854 CRIT Set uid to user 0
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:04,854 CRIT Set uid to user 0
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:04,854 WARN Included extra file "/etc/supervisor/conf.d/supervisord_zabbix.conf" during parsing
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:04,854 WARN Included extra file "/etc/supervisor/conf.d/supervisord_zabbix.conf" during parsing
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:04,879 INFO RPC interface 'supervisor' initialized
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:04,879 INFO RPC interface 'supervisor' initialized
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:04,880 INFO supervisord started with pid 1
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:04,880 INFO supervisord started with pid 1
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:05,883 INFO spawned: 'nginx' with pid 31
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:05,883 INFO spawned: 'nginx' with pid 31
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:05,886 INFO spawned: 'php-fpm' with pid 32
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:05,886 INFO spawned: 'php-fpm' with pid 32
zabbix-web.1.sim5stkgxm0m@groseillier-001    | [23-Feb-2018 15:17:05] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:07,977 INFO success: nginx entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:07,977 INFO success: nginx entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:07,977 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web.1.sim5stkgxm0m@groseillier-001    | 2018-02-23 15:17:07,977 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)

**Comment by dotneft** [comment]
Hm... the script does not have sed between:
zabbix-web.1.sim5stkgxm0m@groseillier-001 | * DB_SERVER_ZBX_USER: zabbix
zabbix-web.1.sim5stkgxm0m@groseillier-001 | sed: bad option in substitution expression
zabbix-web.1.sim5stkgxm0m@groseillier-001 | * DB_SERVER_ZBX_PASS: password

Please check /etc/zabbix/web/config.inc.php. What is difference between passed args and the config?

**Comment by Titinux** [comment]
:confused: /etc/zabbix/web/config.inc.php doesn't exist but I have /etc/zabbix/web/zabbix.conf.php

**Comment by dotneft** [comment]
Ok. What is difference between passed args and the config?

**Comment by dotneft** [comment]
Ok. What exactly you passed to the image and what inside zabbix.conf.php? Which image did you use?

**Comment by Titinux** [comment]
I'm using the alpine nginx pgsql flavor of zabbix 3.4-latest version

docker service create --replicas 1 --name zabbix-web \
  --network postgres --network progralab \
  --env DB_SERVER_HOST=postgres \
  --env DB_SERVER_PORT=5432 \
  --env POSTGRES_DB=zabbix \
  --env POSTGRES_USER=zabbix \
  --env POSTGRES_PASSWORD="password" \
  --env PHP_TZ="Europe/Paris" \
  --env ZBX_SERVER_NAME=Progralab \
  --detach=false \
  zabbix/zabbix-web-nginx-pgsql:alpine-3.4-latest

**Comment by dotneft** [comment]
I can not reproduce the issue with provided options. Do you use some special chars in "password"?

**Comment by Titinux** [comment]
Yes, special chars are ?@|/# and .

but the exact same password works great with zabbix-server-pgsql:alpine-3.4-latest image.

Info : I've updated the /etc/zabbix/web/zabbix.conf.php file with real informations and the frontend is working fine.

**Comment by dotneft** [comment]
Confirmed. Input is
* DB_SERVER_ZBX_PASS: "zabbix?@|/# and ."
final result is
$DB['PASSWORD'] = '"zabbix?@|';

**Comment by dotneft** [comment]
I hope I solved the issue :-) Currently docker hub is rebuilding images, please, try again to use alpine-latest tomorrow.

**Comment by Titinux** [comment]
Sorry for the huge delay. With the fix it works great. Thanks a lot for your quick work.

**Comment by dotneft** [comment]
You are welcome :-)
