### ISSUE TITLE
ERROR [internal] load metadata for docker.io/library/zabbix-build-mysql:alpine-7.0.3

### ISSUE THREAD

**Issue by lauboudou** [zabbix/zabbix-docker#1507]
Hi,

Firstly, I deployed zabbix on a Debian 12 VM using the docker-compose version of alpine 'docker-compose_v3_alpine_mysql_latest.yaml'. 

To complete this installation, I deployed the zabbix-agent from zabbix-docker/Dockerfiles/agent2/alpine. I encountered the following error when starting build.sh

![image](https://github.com/user-attachments/assets/f173dd1c-1c3f-4839-bfd2-6ea55d6ba01d)

For the correct recovery of the image zabbix-build-mysql:alpine-7.0.3 on the hub.docker.com you must prefix the name of the image in the zabbix-docker/Dockerfiles/agent2/alpine/Dockerfile with zabbix/ as in this line:

![image](https://github.com/user-attachments/assets/d33b51a0-78a0-4384-9f48-8a986fbe99de)

The build.sh will work and zabbix-agent will be created

**Comment by dotneft** [comment]
```
docker compose -f docker-compose_v3_alpine_mysql_local.yaml build  zabbix-build-base zabbix-build-mysql zabbix-agent
```
is enough to build Zabbix agent. The script you are trying to use for debug reasons, do not need to use it.
