### ISSUE TITLE
Failed to retrive api_jsonrpc.php from dockerized zabbix

### ISSUE THREAD

**Issue by amikha33** [zabbix/zabbix-docker#1509]
Hello would you please clarify nginx configuration inside dockerized frontend here based on zabbix-web-nginx-pgsql:ubuntu-7.0-latest  image ? as i need to configuere localhost to expose http://localhost-frontend:8080/api_jsonrpc.php

docker compose file by refrence https://github.com/akmalovaa/zabbix-docker/blob/main/docker-compose.yml

<img width="565" alt="image" src="https://github.com/user-attachments/assets/470aca92-33eb-4bfa-b8e9-e57287103c14">

**Comment by dotneft** [comment]
Sorry, what clarify? Nginx as web-server is listening 8080/TCP port. What port you would like to use outside of container it is up to you, it just must be linked to 8080/TCP in the container.

**Comment by amikha33** [comment]
yes nginx port already defined in port exposing, but i need clarification of the built-in nginx hence i need to enable api_jsonrpc.php fron nginx configuerations but using volumes hence containers are ephemeral  if it's doable
<img width="461" alt="image" src="https://github.com/user-attachments/assets/67d5bcbb-0bac-425b-a3bd-d7f3483c8452">
this api will be used inside grafana data source


![image](https://github.com/user-attachments/assets/543413bd-d106-4d60-aa3d-14d2afe9a0b7)

**Comment by dotneft** [comment]
API is part of Web-interface, if regular web-interface is available, in this case API also must be available. In your case error clearly shows the reason, nothing listening 8080/TCP on 127.0.0.1.

**Comment by amikha33** [comment]
the Frontend is accessible and reachable normaly but the mentioned issue here is the API is not accessible
 
![image](https://github.com/user-attachments/assets/5d59703f-4ccf-4cb9-874e-c4c7d8ee4355)

**Comment by dotneft** [comment]
Why is not accessible? Looks like it is available:
```
http://127.0.0.1/api_jsonrpc.php
```
Just try to retrieve some data using API.

**Comment by amikha33** [comment]
> Why is not accessible? Looks like it is available:
> ```
> http://127.0.0.1/api_jsonrpc.php
> ```
> Just try to retrieve some data using API.

I can't retrieve any data from the API url as it's documented in Zabbix API library documentation as it's used for automation purposes

**Comment by dotneft** [comment]
what error message do you see?
