### ISSUE TITLE
About Zabbix Agent

### ISSUE THREAD

**Issue by zhaojing1987** [zabbix/zabbix-docker#1510]
After installing Zabix with Docker compose, I encountered an error on the web interface. Do I need to manually modify the IP or DNS?

![image](https://github.com/user-attachments/assets/daf01554-dcfe-478f-b34e-8d29ef5020ec)

1. Will a new host (Zabbix server) be automatically added after installation?
2. Will configuring the agent not automatically connect to the server and create a usable host?

**Comment by dotneft** [comment]
You need start agent and specify proper IP or DNS.
