### ISSUE TITLE
High CPU usage zabbix_server since 7.0.3

### ISSUE THREAD

**Issue by dsdsdk** [zabbix/zabbix-docker#1514]
##### SUMMARY
![image](https://github.com/user-attachments/assets/4d165815-8ecf-4e80-812e-c75a12d3a7a3)
![image](https://github.com/user-attachments/assets/7ede5678-d1e7-41b8-a2d5-44a496dd5b21)

After start of the container CPU Usage is normal however after short while top shows zabbix_server going to 90% cpu.
HTTP agent poller sat at ~0% on 7.0.1, but since 7.0.3 the behavior changed. 

Zabbix says it's a upstream issue with CURL/libcurl 8.9.0: https://support.zabbix.com/browse/ZBX-25054
Curl fix commit: https://github.com/curl/curl/commit/17e6f06ea37136c36d2712b3433ef0d3b118ec0d

##### OS / ENVIRONMENT / Used docker-compose files
zabbix-server-pgsql:alpine-7.0.3

##### CONFIGURATION
zabbix-server:
        image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
        container_name: zabbix-server
        restart: always
        depends_on:
            - zabbix-postgres
        environment:
            DB_SERVER_HOST: xx
            POSTGRES_USER: xx
            POSTGRES_PASSWORD: xx
            ZBX_STARTVMWARECOLLECTORS: 3
            ZBX_VMWARECACHESIZE: 128M
            ZBX_STARTPREPROCESSORS: 5
            ZBX_STARTPINGERS: 10
            ZBX_STARTPOLLERS: 30
            ZBX_STARTHTTPPOLLERS: 5
            ZBX_STARTHTTPAGENTPOLLERS: 5
            ZBX_STARTPOLLERSUNREACHABLE: 25
            ZBX_STARTBROWSERPOLLERS: 2
            ZBX_WEBDRIVERURL: http://172.18.0.6:4444
            ZBX_CACHESIZE: 448M
            ZBX_TRENDCACHESIZE: 24M
            ZBX_VALUECACHESIZE: 64M
            ZBX_TIMEOUT: 5
            MIBDIRS: 
        volumes:
                networks:
            - zabbix-net

##### STEPS TO REPRODUCE
Start Zabbix 7.0.3 server container

##### EXPECTED RESULTS
to not consistently use 100% CPU

##### ACTUAL RESULTS
consistently use 100% CPU

**Comment by dotneft** [comment]
Please check #1505

**Comment by dsdsdk** [comment]
Thank you. I saw it. But I think curl is in the container?

_It could be because of known issue with libcurl 8.9.0: https://support.zabbix.com/browse/ZBX-25054 and https://github.com/curl/curl/issues/14280. Please try to use different variant of OS._

Here's my OS curl:
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18
Release-Date: 2022-01-05

**Comment by dotneft** [comment]
if you use container, your host curl is not used.

**Comment by dsdsdk** [comment]
So this should be fixed in the container image? I'm trying to understand why https://github.com/zabbix/zabbix-docker/issues/1505 was Closed without fix.

**Comment by kernbug** [comment]
> So this should be fixed in the container image? I'm trying to understand why #1505 was Closed without fix.

Because Zabbix is not responsible for the CURL and Alpine development process or their products.
Images will be using fixed CURL since upstream (Alpine project) will update them. 

You can use another image like Oracle based with curl libs not affected by the upstream bug.
