### ISSUE TITLE
Typo in compose_zabbix_components.yaml, line 22

### ISSUE THREAD

**Issue by sjackson0109** [zabbix/zabbix-docker#1520]
Line 22 reads:
 `  - snmptraps:/var/lib/zabbix/snmptraps:roz`

should read:
 `  - snmptraps:/var/lib/zabbix/snmptraps:ro`

**Comment by dotneft** [comment]
No, it should be "roz": https://docs.docker.com/engine/storage/bind-mounts/#configure-the-selinux-label
