### ISSUE TITLE
In the zabbix-agent2-docker, can the 'Templates: Docker by Zabbix agent 2' be used to monitor items that are also Docker containers?

### ISSUE THREAD

**Issue by joetww** [zabbix/zabbix-docker#1530]
can the 'Templates: Docker by Zabbix agent 2' be used to monitor items that are also Docker containers?

**Comment by dotneft** [comment]
Sorry? Please elaborate. Do you mean is it possible to monitor Docker environment from Zabbix agent 2 container? Yes, it is possible.

**Comment by joetww** [comment]
Should i use "-v /var/run/docker.sock:/var/run/docker.sock" for 'Templates: Docker by Zabbix agent 2'?
