### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16718272 bytes) in /usr/share/zabbix/include/classes/html/CObject.php on line 34

### ISSUE THREAD

**Issue by ITMPGIT** [zabbix/zabbix-docker#1534]
##### SUMMARY
I'm facing an issue related to PHP memory limit on Zabbix Docker images. I receive a fatal error indicating that the allowed memory size has been exhausted.

##### OS / ENVIRONMENT / Used docker-compose files
- Docker version: 27.3.1
- Docker Compose version: 2.29.7
- Sistema operacional: rockylinux

##### CONFIGURATION
my config `docker-compose.yml`:

```yaml
version: '3'
services:
  zabbix:
    image: zabbix/zabbix-web-nginx-mysql
    environment:
      - PHP_MEMORY_LIMIT=256M
    ...
Is there any environment variable to adjust the php memory or do I have to build it?

**Comment by dotneft** [comment]
https://github.com/zabbix/zabbix-docker/tree/7.0/Dockerfiles/web-nginx-mysql#zbx_memorylimit
