### ISSUE TITLE
about kubernetes.yaml

### ISSUE THREAD

**Issue by jorgevisentini** [zabbix/zabbix-docker#1541]
Hi all.

I'm trying to deploy using kubernetes.yaml, but the deployment returns the following error:

**error: resource mapping not found for name: "zabbix-web" namespace: "zabbix" from "zabbix.yml": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"**

I tried to find a solution, but I couldn't.

One more thing, **on line 1122**, they could remove the **beta.**
beta.kubernetes.io/os: linux
**kubernetes.io/os: linux**

Thanks!

**Comment by scottyah** [comment]
You just need to change a couple things in the HorizontalPodAutoscaler, see https://github.com/zabbix/zabbix-docker/pull/1580

**Comment by dotneft** [comment]
Fixed!
