### ISSUE TITLE
Make busybox image configurable

### ISSUE THREAD

**Issue by ponchofiesta** [zabbix/zabbix-docker#1542]
##### SUMMARY

Actually major docker images are configurable via .env file. But the busybox image is hard coded into compose file. When using private docker registries it is necessary to change all image names to a local registry.

##### OS / ENVIRONMENT / Used docker-compose files

- docker-compose_v3_alpine_mysql_latest.yaml
- compose_databases.yaml
  ```yaml
  db-data-mysql:
    image: busybox
  ```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
Done! Thank you!

**Comment by ponchofiesta** [comment]
@dotneft Thank you. But I think there was a mistake: https://github.com/zabbix/zabbix-docker/commit/f16ba34a342a01154e58c6f15208cc05d1012f8d#r148349111

**Comment by dotneft** [comment]
Yes, sorry, fixed!
