### ISSUE TITLE
ZBX_SERVER_HOST in frontend config only works with brackets

### ISSUE THREAD

**Issue by fansari** [zabbix/zabbix-docker#1550]
##### SUMMARY

On all other places where I have put IPv6 address in Zabbix configs (DB_SERVER_HOST, or ZBX_SERVER_HOST in proxies) the IPv6 address can be written without brackets.

Only in the frontend this does not work (and even there DB_SERVER_HOST works without brackets which is confusing).

##### OS / ENVIRONMENT / Used docker-compose files

OS: CentOS Stream release 9
Docker image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0.5

##### STEPS TO REPRODUCE

This does not work:

```
 --env DB_SERVER_HOST=2xxx:xxxx:xxxx::2
 --env ZBX_SERVER_HOST=2xxx:xxxx:xxxx::3
```

This does not work:

```
 --env DB_SERVER_HOST=[2xxx:xxxx:xxxx::2]
 --env ZBX_SERVER_HOST=[2xxx:xxxx:xxxx::3]
```

Using brackets with DB_SERVER_HOST gives this error:

```
**** PostgreSQL server is not available. Waiting 5 seconds...
```

This works:

```
 --env DB_SERVER_HOST=2xxx:xxxx:xxxx::2
 --env ZBX_SERVER_HOST=[2xxx:xxxx:xxxx::3]
```

##### EXPECTED RESULTS

I would expect the writing style of IPv6 addresses to be cosistent. Or is there is a reason why only in this place brackets are mandatory?

##### ACTUAL RESULTS

When ZBX_SERVER_HOST is configured with IPv6 without brackets and you reload the Zabbix GUI there is no attempt to reach the Zabbix server. I checked this with tcpdump.

```paste below

```

**Comment by dotneft** [comment]
Sorry, you said it works when DB_SERVER_HOST specified without brackets, but then said the problem with ZBX_SERVER_HOST. What is correct?

**Comment by fansari** [comment]
After I noticed that I have to use the brackets for ZBX_SERVER_HOST I tested what happens when I also write the address for DB_SERVER_HOST in brackets. But this does not work. You can see above three combinations I have tested.

You have to use ZBX_SERVER_HOST with brackets but DB_SERVER_HOST without brackets. I find this not very intuitive.

**Comment by dotneft** [comment]
Because different destinations and applications.
