### ISSUE TITLE
Cant disable HA Mode

### ISSUE THREAD

**Issue by unixcosu** [zabbix/zabbix-docker#1563]
##### SUMMARY
Running zabbix-server 6.0.29 with zabbix-server-pgsql:ubuntu-6.0.29 image.
We begun to run zabbix-server on HA mode and worked ok.
Now we wanna go to swarm so we need to disable HA mode so swarm manage the service.
We cant disable HA mode.

##### OS / ENVIRONMENT / Used docker-compose files
Debian 12
# docker --version
Docker version 26.1.3, build b72abbb
Env in docker-compose file:
environment:
      POSTGRES_USER: XXXXXXXXX
      POSTGRES_PASSWORD: XXXXXXXX
      POSTGRES_DB: XXXXXXX
      DB_SERVER_HOST: XXXXXXXXXXXX
      DB_SERVER_PORT: XXXXXXXXXXX
      DB_SERVER_DBNAME: XXXXXXXXXXX
      ZBX_HISTORYSTORAGETYPES: log,text # Zabbix configuration variables
      ZBX_DEBUGLEVEL: 3
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 7500
#      ZBX_HOSTNAME: zabbix-server
#      ZBX_AUTONODEADDRESS: fqdn
#      ZBX_AUTOHANODEADDRESS: fqdn
#      ZBX_HANODENAME: 
#      ZBX_HANODENAME: pre-server01
#      ZBX_NODEADDRESS: 
#      ZBX_NODEADDRESS: 10.233.62.4
      ZBX_JAVAGATEWAY_ENABLE: "false"
      ZBX_STARTJAVAPOLLERS: 0
      ZBX_ENABLE_SNMP_TRAPS: "false"
      ZBX_STARTPROXYPOLLERS: 5
      ZBX_PROXYCONFIGFREQUENCY: 3600
      ZBX_CACHESIZE: 2G
      ZBX_TRENDCACHESIZE: 1G
      ZBX_STARTTRAPPERS: 160
      ZBX_STARTHTTPPOLLERS: 15
      ZBX_VALUECACHESIZE: 2G
      ZBX_STARTPREPROCESSORS: 90
      ZBX_STARTDISCOVERERS: 10
      ZBX_LOGSLOWQUERIES: 120000
      ZBX_TRAPPERTIMEOUT: 300
      ZBX_HISTORYINDEXCACHESIZE: 512M
      ZBX_UNREACHABLEPERIOD: 360
      ZBX_UNAVAILABLEDELAY: 360
      ZBX_UNREACHABLEDELAY: 30
      ZBX_PROXYDATAFREQUENCY: 30

##### CONFIGURATION
Just those options

##### STEPS TO REPRODUCE
The server always comes up with HA mode enabled.

##### EXPECTED RESULTS
The expected result is running the server just with these options about its network config:
ZBX_HOSTNAME: zabbix-server
ZBX_AUTONODEADDRESS: fqdn

Because then it will run inside swarm we will not know about the address nor the name...it doesnt mind...

##### ACTUAL RESULTS
We can see always in logs that nodename and nodeipaddress is set:

** Updating '/etc/zabbix/zabbix_server.conf' parameter "HANodeName": 'node01'...updated
** Updating '/etc/zabbix/zabbix_server.conf' parameter "NodeAddress": '10.233.62.4'...updated

Why are these variables updated? From where???

BR,
Mariano.

```

**Comment by dotneft** [comment]
So, do not specify ZBX_AUTOHANODENAME and ZBX_HANODENAME.

**Comment by unixcosu** [comment]
Sorry, I did not copy&paste env variables correctly: (the '#' made bold letters)

These are the only variables I set:
      POSTGRES_USER: xxxxx
      POSTGRES_PASSWORD: xxxx
      POSTGRES_DB: xxxxx
      DB_SERVER_HOST: xxxxxxx
      DB_SERVER_PORT: 5432
      ZBX_HISTORYSTORAGETYPES: log,text # Zabbix configuration variables
      ZBX_DEBUGLEVEL: 3
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 7500
      ZBX_JAVAGATEWAY_ENABLE: "false"
      ZBX_STARTJAVAPOLLERS: 0
      ZBX_ENABLE_SNMP_TRAPS: "false"
      ZBX_STARTPROXYPOLLERS: 5
      ZBX_PROXYCONFIGFREQUENCY: 3600
      ZBX_CACHESIZE: 2G
      ZBX_TRENDCACHESIZE: 1G
      ZBX_STARTTRAPPERS: 160
      ZBX_STARTHTTPPOLLERS: 15
      ZBX_VALUECACHESIZE: 2G
      ZBX_STARTPREPROCESSORS: 90
      ZBX_STARTDISCOVERERS: 10
      ZBX_LOGSLOWQUERIES: 120000
      ZBX_TRAPPERTIMEOUT: 300
      ZBX_HISTORYINDEXCACHESIZE: 512M
      ZBX_UNREACHABLEPERIOD: 360
      ZBX_UNAVAILABLEDELAY: 360
      ZBX_UNREACHABLEDELAY: 30
      ZBX_PROXYDATAFREQUENCY: 30

**Comment by xtonousou** [comment]
I can confirm the same behavior with a fresh deployment on Docker Swarm, using Zabbix `alpine-7.0-latest` and Postgres `16-alpine`.

```bash
a2842c31584e:/var/lib/zabbix$ env | grep -i hanodename
a2842c31584e:/var/lib/zabbix$
```

Although, after restarting the whole stack, zabbix is working perfectly.

`¯\_(ツ)_/¯`

**Comment by dotneft** [comment]
what about ZBX_AUTOHANODENAME? You checked only one.

**Comment by unixcosu** [comment]
> I can confirm the same behavior with a fresh deployment on Docker Swarm, using Zabbix `alpine-7.0-latest` and Postgres `16-alpine`.
> 
> ```shell
> a2842c31584e:/var/lib/zabbix$ env | grep -i hanodename
> a2842c31584e:/var/lib/zabbix$
> ```
> 
> Although, after restarting the whole stack, zabbix is working perfectly.
> 
> `¯\_(ツ)_/¯`

I've got another installation which was working in standalone mode, then I switched to swarm and is still working perfectly, I mean, no HA config is seen.
The issue seems to go with standalone config from a HA config...

**Comment by unixcosu** [comment]
> what about ZBX_AUTOHANODENAME? You checked only one.

What do you mean?

**Comment by dotneft** [comment]
both variables must be not defined.

**Comment by unixcosu** [comment]
> both variables must be not defined.

Sure, they are not defined:

POSTGRES_USER: xxxxx
POSTGRES_PASSWORD: xxxx
POSTGRES_DB: xxxxx
DB_SERVER_HOST: xxxxxxx
DB_SERVER_PORT: 5432
ZBX_HISTORYSTORAGETYPES: log,text # Zabbix configuration variables
ZBX_DEBUGLEVEL: 3
ZBX_HOUSEKEEPINGFREQUENCY: 1
ZBX_MAXHOUSEKEEPERDELETE: 7500
ZBX_JAVAGATEWAY_ENABLE: "false"
ZBX_STARTJAVAPOLLERS: 0
ZBX_ENABLE_SNMP_TRAPS: "false"
ZBX_STARTPROXYPOLLERS: 5
ZBX_PROXYCONFIGFREQUENCY: 3600
ZBX_CACHESIZE: 2G
ZBX_TRENDCACHESIZE: 1G
ZBX_STARTTRAPPERS: 160
ZBX_STARTHTTPPOLLERS: 15
ZBX_VALUECACHESIZE: 2G
ZBX_STARTPREPROCESSORS: 90
ZBX_STARTDISCOVERERS: 10
ZBX_LOGSLOWQUERIES: 120000
ZBX_TRAPPERTIMEOUT: 300
ZBX_HISTORYINDEXCACHESIZE: 512M
ZBX_UNREACHABLEPERIOD: 360
ZBX_UNAVAILABLEDELAY: 360
ZBX_UNREACHABLEDELAY: 30
ZBX_PROXYDATAFREQUENCY: 30

**Comment by dotneft** [comment]
check inside container what related to HANODENAME defined.

**Comment by unixcosu** [comment]
> check inside container what related to HANODENAME defined.

This is not defined but inside container, on zabbix_server.conf, is defined. WHy? I dont know.

**Comment by unixcosu** [comment]
Maybe somewhere in DB is stored the HA info?? A part of ha_node table??

**Comment by dotneft** [comment]
show me "env | grep -i node"
