### ISSUE TITLE
CentOS stream docker image not maintained any more?

### ISSUE THREAD

**Issue by tbblake** [zabbix/zabbix-docker#1569]
##### SUMMARY
The centos-6.0-latest docker image is only at version 6.0.30 while all the others are at 6.0.36

##### OS / ENVIRONMENT / Used docker-compose files
Docker version 27.3.1

##### STEPS TO REPRODUCE
Docker pull the images and use docker inspect to check versions

```
$ docker image inspect zabbix/zabbix-server-mysql:alpine-6.0-latest| jq | grep ZBX_VERSION
        "ZBX_VERSION=6.0.36",
$ docker image inspect zabbix/zabbix-server-mysql:ubuntu-6.0-latest| jq | grep ZBX_VERSION
        "ZBX_VERSION=6.0.36",
$ docker image inspect zabbix/zabbix-server-mysql:ol-6.0-latest| jq | grep ZBX_VERSION
        "ZBX_VERSION=6.0.36",
$ docker image inspect zabbix/zabbix-server-mysql:centos-6.0-latest| jq | grep ZBX_VERSION
        "ZBX_VERSION=6.0.30",
```

##### EXPECTED RESULTS
centos-6.0-latest would be at 6.0.36

##### ACTUAL RESULTS
centos-6.0-latest is at 6.0.30

**Comment by tbblake** [comment]
Worth mentioning the page on dockerhub (https://hub.docker.com/r/zabbix/zabbix-server-mysql) states "These are the only official Zabbix server Docker images. They are based on Alpine Linux v3.20, Ubuntu 24.04 (noble), CentOS Stream 9 and Oracle Linux 9 images. The available versions of Zabbix server are" so I'd assume that either that needs updating or the images need updating.

**Comment by tbblake** [comment]
at a glance the latest centos 5.0 image is at 5.0.42 where the latest zabbix release is 5.0.45...

**Comment by tbblake** [comment]
5.0is also behind for centos

```
+ docker image inspect zabbix/zabbix-web-apache-mysql:alpine-5.0-latest
+ grep ZBX_VERSION
+ jq
        "ZBX_VERSION=5.0.45",
+ docker image inspect zabbix/zabbix-web-apache-mysql:ubuntu-5.0-latest
+ grep ZBX_VERSION
+ jq
        "ZBX_VERSION=5.0.45",
+ docker image inspect zabbix/zabbix-web-apache-mysql:ol-5.0-latest
+ grep ZBX_VERSION
+ jq
        "ZBX_VERSION=5.0.45",
+ docker image inspect zabbix/zabbix-web-apache-mysql:centos-5.0-latest
+ grep ZBX_VERSION
+ jq
        "ZBX_VERSION=5.0.42",

```

**Comment by tbblake** [comment]
Up to date images appear to be in the build process, but maybe not getting pushed to dockerhub?

https://github.com/zabbix/zabbix-docker/tree/6.0/Dockerfiles/server-mysql/centos is at 6.0.36

**Comment by tbblake** [comment]
FWIW, doesn't appear to be just isolated to the mysql versions:

```
$ docker image inspect zabbix/zabbix-server-pgsql:centos-6.0-latest | jq | grep ZBX_VERSION
        "ZBX_VERSION=6.0.30",

```

**Comment by dotneft** [comment]
Fixed https://support.zabbix.com/browse/ZBX-25652.

**Comment by tbblake** [comment]
5.0 appears to still be outdated:

```
$ docker image pull zabbix/zabbix-server-mysql:centos-5.0-latest
centos-5.0-latest: Pulling from zabbix/zabbix-server-mysql
Digest: sha256:67c27b8cf750b4962fc045f8c6d596f42fee92b3e001deca7977852e4fd9067e
Status: Image is up to date for zabbix/zabbix-server-mysql:centos-5.0-latest
docker.io/zabbix/zabbix-server-mysql:centos-5.0-latest
$ docker image inspect zabbix/zabbix-server-mysql:centos-5.0-latest| jq | grep ZBX_VERSION
        "ZBX_VERSION=5.0.42",
$

```
