### ISSUE TITLE
No error log in check_db_connect_postgresql

### ISSUE THREAD

**Issue by TriDvaRas** [zabbix/zabbix-docker#1573]
Hi,
So I've been stuck on zabbix server container not being able to connect to db. 
I've found the solution in the end. Had the same error as in https://github.com/zabbix/zabbix-docker/issues/1572

But it got me wondering, why is stderr being /dev/null'ed? It would have been quite nice seeing the error message in the log without running the command myself
Are there concerns in having the error message exposed in log? 

https://github.com/zabbix/zabbix-docker/blob/be328b97241041ab0596dd350b7b2d81115a189b/Dockerfiles/server-pgsql/alpine/docker-entrypoint.sh#L207-L214
(and the same in other os files)

**Comment by dotneft** [comment]
The error message can expose some sensitive information. As it is not Zabbix tool, we can not promise what actually output it can display.
