### ISSUE TITLE
Trigger action intended for one Media Type is also being assigned to All Media Types in Zabbix

### ISSUE THREAD

**Issue by alemsas** [zabbix/zabbix-docker#1578]
Hello,

I'm experiencing an issue with Zabbix where a trigger action configured to use only the Telegram(for example) media type is also being assigned to Squadcast(for example), even though I did not configure it that way.

Environment:

    Zabbix Version: 7.0.5
    Database Type: MySQL

Problem Details:

    I have created a trigger action that should send notifications exclusively via the Telegram media type.
    Despite this configuration, the action is also being assigned to the Squadcast media type, resulting in notifications being sent through both channels.
    I suspect that this issue might be related to the database, possibly due to inconsistencies or corruption.

Questions:

    Could there be a database issue causing this action to be assigned to the wrong media type?
    Are there any known issues or bugs in Zabbix that might cause this behavior?
    What database queries or checks can I perform to identify and resolve this issue?
    Is there a way to reset or repair the database entries related to actions and media types without affecting the rest of the system?

Request:

I would appreciate any guidance on how to troubleshoot and resolve this issue.

![image](https://github.com/user-attachments/assets/c0b85c87-40da-402b-bc66-b7355323ea9c)

**Comment by dotneft** [comment]
I would like to draw your attention to the fact that this issue tracker is for Zabbix docker images defects only.

Please use https://www.zabbix.com/community for community support, https://support.zabbix.com/servicedesk for commercial support or contact our Sales team for commercial support options.
