### ISSUE TITLE
Not start zabbix-server-psql-7.0.7

### ISSUE THREAD

**Issue by Tonwins** [zabbix/zabbix-docker#1592]
##### SUMMARY
/usr/sbin/zabbix_server: error while loading shared libraries: libevent_extra-2.1.so.7: cannot open shared object file: No such file or directory
After updating from 7.0.6 to 7.0.7, the production server does not start. 
No library installed

##### OS / ENVIRONMENT / Used docker-compose files
Used docker-compose files

##### STEPS TO REPRODUCE
docker-compose up

need libevent-extra-2.1-7
https://github.com/zabbix/zabbix-docker/blob/9ec904f806b34df556f15ce9380cf84bb3a66849/Dockerfiles/server-pgsql/ubuntu/Dockerfile#L48

**Comment by dotneft** [comment]
What image do you use?

**Comment by Tonwins** [comment]
zabbix/zabbix-server-pgsql:ubuntu-7.0.7

**Comment by Tonwins** [comment]
сейчас откатился на zabbix/zabbix-server-pgsql:ubuntu-7.0.6 
На нем всё работает. 
если доустанавливаю пакет ibevent-extra-2.1-7 в zabbix/zabbix-server-pgsql:ubuntu-7.0.7  
то сервер начинает работать и падает каждые 5 минут при старте lld воркеров

**Comment by dotneft** [comment]
Fixed, please, wait next "latest" release.
