### ISSUE TITLE
Support for database connection url

### ISSUE THREAD

**Issue by sumitgoelpw** [zabbix/zabbix-docker#163]
The docker images work great with database host, user, password credentials but it would be beneficial also to support the ability to pass the database connection URL.

**Comment by dotneft** [comment]
What do you mean? Please elaborate the request.

**Comment by sumitgoelpw** [comment]
[Section 33.1.1.2](https://www.postgresql.org/docs/current/static/libpq-connect.html) PostgreSQL connection URI can be created in following form,

`postgresql://[user[:password]@][netloc][:port][,...][/dbname][?param1=value1&...]`

I want to be able to pass an environment variable let's say DATABASE_URI in the above format instead of passing DB_SERVER_HOST, DB_SERVER_PORT, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB separately.

**Comment by dotneft** [comment]
Actually Zabbix does not work with such connection URI. I'm not sure that is a good idea to parse it then.
