### ISSUE TITLE
Parameter ZBX_SOURCEIP not working

### ISSUE THREAD

**Issue by proffust** [zabbix/zabbix-docker#164]
Hello.
I start proxy with this parameters
docker run --name zabbix-proxy -e ZBX_HOSTNAME=SANDBOX -e ZBX_SERVER_HOST=10.242.0.81 -e ZBX_PROXYMODE=0 -e ZBX_SOURCEIP=10.242.24.130 --net=host  -d zabbix/zabbix-proxy-sqlite3:alpine-3.0-latest

but in docker logs I see 
Preparing Zabbix proxy
** Preparing Zabbix proxy configuration file
** Updating '/etc/zabbix/zabbix_proxy.conf' parameter "ProxyMode": '0'... added
** Updating '/etc/zabbix/zabbix_proxy.conf' parameter "Server": '10.242.0.81'... updated
** Updating '/etc/zabbix/zabbix_proxy.conf' parameter "ServerPort": '10051'... added
** Updating '/etc/zabbix/zabbix_proxy.conf' parameter "Hostname": 'SANDBOX'... updated
** Updating '/etc/zabbix/zabbix_proxy.conf' parameter "HostnameItem": ''... removed
** Updating '/etc/zabbix/zabbix_proxy.conf' parameter "ListenPort": ''... removed
**** Updating '/etc/zabbix/zabbix_proxy.conf' parameter "SourceIP": ''... removed**

**Comment by dotneft** [comment]
It looks like it is hub.docker.com issue. Please try to specify alpine-3.0.12

**Comment by dotneft** [comment]
Fixed!
