### ISSUE TITLE
[question] Why use supervisord instead of starting zabbix agent directly

### ISSUE THREAD

**Issue by kouinkouin** [zabbix/zabbix-docker#169]
Hi,

I just use your container (thanks for it ! :-) ), and because I set a bad environment variable, the zabbix service failed, but I expected that the container stopped. It didn't.

So, as you have only 1 process (with children), why use supervisord?

Maybe to avoid the service fails without restarting, but the user can simply set `autorestart=always` when he launch its container, no?

It's just a question, not a request to change it (yet, depending the response :-p ).

Thanks for your work!

**Comment by dotneft** [comment]
Just to make unify all builds :-) + Autorestart in case of memory issues and some other issues. Currently supervisord configured to restart just 3 ones...
