### ISSUE TITLE
zabbix-server-pgsql 3.2 -> 3.4 database upgrade failed

### ISSUE THREAD

**Issue by BoOgatti** [zabbix/zabbix-docker#170]
Hi, i'am trying to upgrade my latest 3.2 to 3.4. What i have:

- OS: Ubuntu 16.04.3 LTS
- docker: 17.09.0-ce, build afdb6d4
- zabbix-server-pgsql image: ubuntu-3.2-latest (3.2.10)
- postgres image: 9.6.6

> 20.11.2017 11:26:32   146:20171120:112632.121 Starting Zabbix Server. Zabbix 3.4.4 (revision 74338).
20.11.2017 11:26:32   146:20171120:112632.122 ****** Enabled features ******
20.11.2017 11:26:32   146:20171120:112632.123 SNMP monitoring:           YES
20.11.2017 11:26:32   146:20171120:112632.123 IPMI monitoring:           YES
20.11.2017 11:26:32   146:20171120:112632.124 Web monitoring:            YES
20.11.2017 11:26:32   146:20171120:112632.124 VMware monitoring:         YES
20.11.2017 11:26:32   146:20171120:112632.125 SMTP authentication:       YES
20.11.2017 11:26:32   146:20171120:112632.125 Jabber notifications:      YES
20.11.2017 11:26:32   146:20171120:112632.126 Ez Texting notifications:  YES
20.11.2017 11:26:32   146:20171120:112632.126 ODBC:                      YES
20.11.2017 11:26:32   146:20171120:112632.126 SSH2 support:              YES
20.11.2017 11:26:32   146:20171120:112632.127 IPv6 support:              YES
20.11.2017 11:26:32   146:20171120:112632.127 TLS support:               YES
20.11.2017 11:26:32   146:20171120:112632.128 ******************************
20.11.2017 11:26:32   146:20171120:112632.128 using configuration file: /etc/zabbix/zabbix_server.conf
20.11.2017 11:26:32   146:20171120:112632.149 current database version (mandatory/optional): 03030021/03030021
20.11.2017 11:26:32   146:20171120:112632.150 required mandatory version: 03040000
20.11.2017 11:26:32   146:20171120:112632.151 optional patches were found
20.11.2017 11:26:32   146:20171120:112632.151 starting automatic database upgrade
20.11.2017 11:26:32   146:20171120:112632.182 [Z3005] query failed: [0] PGRES_FATAL_ERROR:ERROR:  duplicate key value violates unique constraint "items_pkey"
20.11.2017 11:26:32DETAIL:  Key (itemid)=(25471) already exists.
20.11.2017 11:26:32 [update items set formula='' where flags<>1 or evaltype<>3]
20.11.2017 11:26:32   146:20171120:112632.183 database upgrade failed
20.11.2017 11:26:322017-11-20 11:26:32,186 INFO exited: zabbix-server (exit status 1; not expected)
20.11.2017 11:26:322017-11-20 11:26:32,186 INFO exited: zabbix-server (exit status 1; not expected)
20.11.2017 11:26:332017-11-20 11:26:33,189 INFO gave up: zabbix-server entered FATAL state, too many start retries too quickly
20.11.2017 11:26:332017-11-20 11:26:33,189 INFO gave up: zabbix-server entered FATAL state, too many start retries too quickly
20.11.2017 11:28:002017-11-20 11:28:00,929 WARN received SIGTERM indicating exit request
20.11.2017 11:28:002017-11-20 11:28:00,929 WARN received SIGTERM indicating exit request

I did not edit any tables in PG directly

**Comment by dotneft** [comment]
It looks like DB is corrupted. Did you solve the issue?

**Comment by BoOgatti** [comment]
Agree, db's storage was "unstable" in last times and i think zbx image not culprit. I'll plan to reinstall system. Thx
