### ISSUE TITLE
cannot send proxy data to server at "zabbix-server"

### ISSUE THREAD

**Issue by erickertz** [zabbix/zabbix-docker#171]
I just pulled and ran the latest for zabbix-mysql: 

`docker-compose -f docker-compose_v2_ubuntu_mysql_latest.yaml up 
`
And am seeing the following errors:

```
zabbix-proxy-mysql_1       |    135:20171122:180809.821 cannot send proxy data to server at "zabbix-server": proxy "zabbix-proxy-mysql" not found
zabbix-proxy-sqlite3_1     |    105:20171122:180809.991 cannot send proxy data to server at "zabbix-server": proxy "zabbix-proxy-sqlite3" not found
zabbix-server_1            |    167:20171122:180809.990 cannot parse proxy data from active proxy at "172.16.238.10": proxy "zabbix-proxy-sqlite3" not found
```

I'm completely new to Zabbix and am trying it out for the first time. Is there additional setup I need for these proxies to be found? Thanks.

**Comment by erickertz** [comment]
Nevermind! Getting further into the docs, I have a better understanding of what to do now. Thanks :)

**Comment by M1dor1ya** [comment]
@erickertz Hey bro,can you tell me how to solve this problem or Where is the document you mentioned？Thansk

**Comment by fleimgruber** [comment]
@erickertz @M1dor1ya any progress?

**Comment by wajika** [comment]
I don't understand. How did you solve it @erickertz

**Comment by erickertz** [comment]
I honestly don't remember the details I did to solve this. I do remember
creating my own repo though https://github.com/erickertz/zabbix-docker
