### ISSUE TITLE
Docker compose issue on MacBook

### ISSUE THREAD

**Issue by steineracedo** [zabbix/zabbix-docker#180]
Hello, I'm having this issue on my MacBook when try to run the composer file for alpine/mysql lates images:

Starting 212f91ac251a_zabbixdocker_zabbix-server_1 ... error

ERROR: for 212f91ac251a_zabbixdocker_zabbix-server_1  Cannot start service zabbix-server: Mounts denied: EOF

ERROR: for zabbix-server  Cannot start service zabbix-server: Mounts denied: EOF
ERROR: Encountered errors while bringing up the project.

First I had an issue regarding /etc path and I changed that path for /private/etc but now I'm having the issue above and not sure what's happening. I've just changed the mentioned path, the rest is all the original .yaml file

**Comment by dotneft** [comment]
try to remove unnecessary mounts. Most of them work on Linux ONLY.
