### ISSUE TITLE
Cannot run a container

### ISSUE THREAD

**Issue by Yelfive** [zabbix/zabbix-docker#183]
When it tried to run a container with image ``, it exited immediately. Then i tried

```bash
> docker start -i zabbix_server_1
```
Impossible to use MySQL server because 'root' password is not defined and not empty

**Comment by dotneft** [comment]
Please check documentation https://www.zabbix.com/documentation/3.0/manual/installation/containers

**Comment by Yelfive** [comment]
So I guess, there is no default value of mysql user and password stuff as described in the documentation
![image](https://user-images.githubusercontent.com/7898026/34602676-a30b87e4-f23b-11e7-8b7b-a6268328ccd2.png)

For which, I intendedly set my mariadb's user zabbix and password as well 😂

**Comment by dotneft** [comment]
Please, show us container logs.

**Comment by Yelfive** [comment]
I mean, I have double checked the documentation you posted, and solved my issue, yes, it failed because I did not set the environments about mysql user and password for my `zabbix-server-mysql` (which I had thought the default ones works for me). 

I'm just saying, the documentation says there's a default value, and yet, there's actually none. And as a matter of fact, user should set their own `MYSQL_USER` and `MYSQL_PASSWORD`, which is a required step not optional.

**Comment by nyukers** [comment]
Hi, I have same problem.
Tell me, what's the "environments about mysql user and password for my zabbix-server-mysql"?

**Comment by dotneft** [comment]
Please check the documentation link above:
# docker run --name zabbix-server-mysql -t \
      -e DB_SERVER_HOST="mysql-server" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="zabbix_pwd" \
      -e MYSQL_ROOT_PASSWORD="root_pwd" \
      -e ZBX_JAVAGATEWAY="zabbix-java-gateway" \
      --link mysql-server:mysql \
      --link zabbix-java-gateway:zabbix-java-gateway \
      -p 10051:10051 \
      -d zabbix/zabbix-server-mysql:latest

**Comment by jcoutch** [comment]
In my case, I'm trying to run `zabbix-web-nginx-mysql`, and ran into the exact error message above.

If Zabbix is publishing a container that has mysql (or any other 3rd party component) installed inside of it, one would expect the container to work out of the box with the default values listed on the documentation link above.  As a consumer of your container, I have no knowledge of how mysql was installed, nor should I if it's only being used internal to the container.

The only time I should need to add/change environment variables is if I'm straying from the default configuration, and in those cases, I'd just use the `zabbix` container and set the environment variables myself.

**Comment by dotneft** [comment]
In this case please read the documentation, but if you want all-in-one use zabbix-appliance image

**Comment by mobious999** [comment]
I've got the same issues a described from above. By reading the documentation I expect that all of the defaults will use zabbix for the database connection etc. All that needs to be done is add some comments to the docker entrypoint "these are mandatory parameters".

**Comment by dotneft** [comment]
Hello! I recommend you use compose file, it has all preconfigured options, then you can just optimize Zabbix installation for your environment. Sometimes to run "raw" docker images from scratch is a bit difficult procedure :-(

**Comment by mobious999** [comment]
Hi Alexey,
As it turns out it looks like it's firewalld.
I'm reformatting and using ubuntu lts starting monday.

    On Friday, April 24, 2020, 11:04:41 AM EDT, Alexey Pustovalov <notifications@github.com> wrote:  
 
 


Hello! I recommend you use compose file, it has all preconfigured options, then you can just optimize Zabbix installation for your environment. Sometimes to run "raw" docker images from scratch is a bit difficult procedure :-(
