### ISSUE TITLE
No symlink for ssl config in zabbix-web-nginx-mysql?

### ISSUE THREAD

**Issue by christiaan-janssen** [zabbix/zabbix-docker#184]
I'm running zabbix/zabbix-web-nginx-mysql:alpine-3.4-latest and if I look in the Dockerfile I can see that port 443 is exposed and a ssl config file is added to the container:

```
EXPOSE 80/TCP 443/TCP
...
ADD conf/etc/zabbix/nginx.conf /etc/zabbix/
ADD conf/etc/zabbix/nginx_ssl.conf /etc/zabbix/
```

The files are also present in the container:

```
bash-4.3# cd /etc/zabbix/
bash-4.3# ls
nginx.conf      nginx_ssl.conf  web
```

but the config is not symlinked to nginx config dir:
```
bash-4.3# cd /etc/nginx/conf.d/
bash-4.3# ls -la
total 8
drwxr-xr-x    1 root     root          4096 Dec 22 13:32 .
drwxr-xr-x    1 root     root          4096 Dec 22 13:10 ..
lrwxrwxrwx    1 root     root            22 Dec 22 13:32 nginx.conf -> /etc/zabbix/nginx.conf
```

**Comment by dotneft** [comment]
Because you do not have certs. Provide certs and restart image.

**Comment by christiaan-janssen** [comment]
I have a volume mounted in `/etc/ssl/nginx`:

```
bash-4.3# mount | grep ssl
tmpfs on /etc/ssl/nginx type tmpfs (ro,relatime)

bash-4.3# cd /etc/ssl/nginx/
bash-4.3# ls
ssl.crt  ssl.key
```

I restarted the container, but still no symlink.

**Comment by dotneft** [comment]
It requires:
1. ssl.crt
2. ssl.key
3. dhparam.pem
in /etc/ssl/nginx directory

**Comment by christiaan-janssen** [comment]
Yes that was the solution, I was missing the dhparam.pem file
