### ISSUE TITLE
zabbix in  kubernetes: failed to accept an incoming connection: connection from "10.233.66.53" rejected, allowed hosts: "zabbix-server,172.168.60.10,172.168.60.11,172.168.60.12

### ISSUE THREAD

**Issue by szediktam** [zabbix/zabbix-docker#186]
I install zabbix in a multimode kubernetes cluester.
zabbix-server and zabbix-web ars deployment with a single pod in openstack-controller,  and zabbix-agent is daemonset in openstack-compute.

Server in agentd.conf is: Server = zabbix-server,172.168.60.10,172.168.60.11,172.168.60.12, the zabbix-server service domain and the controller ip. And the ServerActive is same to Server.
But the zabbix-agentd.conf ocured a error:
failed to accept an incoming connection: connection from "10.233.66.53" rejected, allowed hosts: "zabbix-server,172.168.60.10,172.168.60.11,172.168.60.12"

10.233.66.53 is the ip of zabbix-servrt pod.

How to set Server/ServerActive in agentd.conf or else to solve the problem.

**Comment by dotneft** [comment]
Try to use DNS instead of IP.

**Comment by szediktam** [comment]
Server = zabbix-server,172.168.60.10,172.168.60.11,172.168.60.12
zabbix-server is DNS of zabbix-server service.
if I only write zabbix-server in Server. agent log shows:
failed to accept an incoming connection: connection from "172.50.10.4" rejected, allowed hosts: "zabbix-server"
so I add controller ip in Server.
Then, only the agent located in same node with zabbix-server pod, show errors：
failed to accept an incoming connection: connection from "10.233.66.53" rejected, allowed hosts: "zabbix-server,172.168.60.10,172.168.60.11,172.168.60.12"

**Comment by jangaraj** [comment]
If it's your private cluster, then why you don't allow all IPs `Server=0.0.0.0/0`?

We don't know anything about your networking but in theory, some you zabbix agents can see zabbix-server pod IP as zabbix-server IP and some can see host IP, where zabbix-server pod is running as a zabbix-server IP. Be aware of that.
Also using zabbix-server pod IP in the agent config is not a good idea, because if new zabbix-server pod will have a different pod IP - it will require redeploying all your agents in this case. You should use DNS in your cluster to avoid that.

**Comment by szediktam** [comment]
If I set Server=0.0.0.0/0, it occured the error message:
failed to accept an incoming connection: connection from "10.233.66.53" rejected, allowed hosts: "0.0.0.0/0"
im my cluster, the zabbix-agent  see host IP of openstack-controller. And the zabbix-agent located in same host with zabbix-server pod, see the zabbix-server pod IP.  

What does the DNS mean? The zabbix-server Server name like zabbix-server.openstack.svc.cluster.local?

**Comment by dotneft** [comment]
what version do you use?

**Comment by miaofenk** [comment]
I met exactly the same issue as szediktam. 
Could you tell me how this issue is resolved?

Thanks a lot!

**Comment by szediktam** [comment]
Set a lable in one host, and set zabbix-server as a daemonset in this host?
Then a zabbix-server with a daemonset type in only a host, will have a fixed ip.
I dont test it.

**Comment by miaofenk** [comment]
Thanks for your reply! @szediktam
