### ISSUE TITLE
zabbix user to dialout group

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#195]
If you want to use a gsm modem for sms notification you mostly will use --device which maps the specified device in the container. In Ubuntu it is needed that the user is in the dialout group which isn't the case and so you will get a permission denied error.

Adding the zabbix user to the group will solve that problem. I think it would be best if this is handled in the run_zabbix_component.sh scripts.

**Comment by dotneft** [comment]
done

**Comment by rockaut** [comment]
Hey @dotneft ... Done means you accepted the commit? Well then it seems it didn't make it to the latest changes where you renamed the run_components.sh file.

**Comment by dotneft** [comment]
I added it to dockerfile.

**Comment by rockaut** [comment]
Oh sorry. I haven't realized that. Thanks for that.
I initially also wanted to to it in dockerfile but thought it would fit better in startup script as it is only needed on server role.
