### ISSUE TITLE
Unclear issue with disk space usage graph

### ISSUE THREAD

**Issue by mdihtyar** [zabbix/zabbix-docker#241]
After pulling new zabbix docker images, faced with such interesting issue, my disk space usage ( Mounted filesystem discovery: Disk space usage) graph became like below on picture.

![image](https://user-images.githubusercontent.com/20419696/36586104-15f3abc4-1889-11e8-81e1-87f513333056.png)

If I create graph manually, everything looks like work. I am not sure is this issue related to docker env.
![image](https://user-images.githubusercontent.com/20419696/36586219-a1e98748-1889-11e8-8de8-e268b83149a7.png)

**Comment by richlv** [comment]
known issue - https://support.zabbix.com/browse/ZBX-13340

**Comment by dotneft** [comment]
Thank you Richlv! It is known Zabbix issue and not related to images.

**Comment by mdihtyar** [comment]
thanks
