### ISSUE TITLE
ZBX_TYPE invalid values on comments

### ISSUE THREAD

**Issue by migueleliasweb** [zabbix/zabbix-docker#243]
Hey guys !

Apparently this line is pointing invalid values to the ZBX_TYPE variable. You can see that the values in the comments are quite different compared to the ones in the end of the entrypoint. I was trying to use the value "web" but the real value is "frontend". =/

[Values from the comment](https://github.com/zabbix/zabbix-docker/blob/9f7a808a9209b01c3e10f9a2c918f126705436f6/web-apache-mysql/alpine/docker-entrypoint.sh#L13
) / [Exepcted values](https://github.com/zabbix/zabbix-docker/blob/9f7a808a9209b01c3e10f9a2c918f126705436f6/web-apache-mysql/alpine/docker-entrypoint.sh#L941L953)

**Comment by dotneft** [comment]
Agree, currently i'm doing script refactoring, hope I will solve all such cases :-)

**Comment by migueleliasweb** [comment]
Perfect ! :+1:

**Comment by dotneft** [comment]
fixed. Thank you!
