### ISSUE TITLE
proxy-sqlite3 Env issues

### ISSUE THREAD

**Issue by milefork** [zabbix/zabbix-docker#245]
Hi,

I've a problem:

When I try to run the zabbix-proxy-sqlite3 Docker image and define the ENV:

`ZBX_HOSTNAMEITEM = system.hostname`

I expect that the Hostname will be taken from the hostnameitem. But that doesnt work and when I check the logs I see the problem:

`zabbix_proxy [1]: Warning: both Hostname and HostnameItem defined, using [zabbix-proxy-sqlite3]`

So is it possible to adapt the startup script to take the hostnameitem when the env is set?

Greetings

**Comment by dotneft** [comment]
Have you tried specify ZBX_HOSTNAME="" (empty) as well?

**Comment by dotneft** [comment]
checked the issue, agree. Currently it is impossible to specify and use ZBX_HOSTNAMEITEM

**Comment by dotneft** [comment]
Fixed. Thank you!
