### ISSUE TITLE
Add Env to use existing config

### ISSUE THREAD

**Issue by milefork** [zabbix/zabbix-docker#248]
Hi,

I stumbled upon another issue/problem. If I mount the /etc/zabbix dir from the host to the container, my existing config gets overwritten (testet in proxy).
It would be nice to have a flag or smth. to stop this.

**Comment by dotneft** [comment]
why do you want to mount the directory?

**Comment by milefork** [comment]
Because I've the proxy running via Rancher and want to use my handwritten configuration file, where I can set the hostname per host statically for example or tune other options host specific.

**Comment by dotneft** [comment]
you can use environment variables to tune the config. I specially removed access to /etc/zabbix, because it has some preconfigured params for docker.

**Comment by milefork** [comment]
okay
