### ISSUE TITLE
How can we use zabbix-agent monitor the host

### ISSUE THREAD

**Issue by xiaoweihong** [zabbix/zabbix-docker#251]
Your projet is very useful to me.But I met some problem.
I want to know ,how can we use zabbix-agent image to monitor the host .The md file not describe.

**Comment by dotneft** [comment]
Just run and monitor :-) What is the issue?

**Comment by nyukers** [comment]
I think you have to change "localhost" to IP adr of host.

**Comment by nyukers** [comment]
Or don't use image and install zabbix-agent directly to host.

**Comment by xiaoweihong** [comment]
thank you for replay.
if i use the zabbix-agent directly,how the zabbix-server receive the agent data from another host?

--------------原始邮件--------------
发件人："Nyukers "<notifications@github.com>;
发送时间：2018年3月19日(星期一) 晚上7:22
收件人："zabbix/zabbix-docker" <zabbix-docker@noreply.github.com>;
抄送："洪晓威@视频结构化 "<xiaoweihong@deepglint.com>;"Author "<author@noreply.github.com>;
主题：Re: [zabbix/zabbix-docker] How can we use zabbix-agent monitor thehost (#251)
-----------------------------------

Or don't use image and install zabbix-agent directly to host.

**Comment by nyukers** [comment]
zabbix-server: configuration/hosts/agent interfaces/ip adr

**Comment by mohitrajvardhan17** [comment]
Few Clarification required here:
  - You are using dockerized zabbix-server container on host A.
  - You have the zabbix agent installed on the host A.
  - You need to created a connection between the dockerized zabbix-server container and  standalone zabbix agent on the host A.

**Comment by xiaoweihong** [comment]
@mohitrajvardhan17 ok,i'll try it,thank you.
