### ISSUE TITLE
CRIT reaped unknown pid <PID>

### ISSUE THREAD

**Issue by dj-wasabi** [zabbix/zabbix-docker#252]
Hi,

I'm using the proxy mysql ubuntu (3.4.5) container in my environment. I have a single python script configured as "External Check" which runs fine, but this script also sends some data with `zabbix_sender`. But every time this happens, we see the following message appear in the logfile: 

```
2018-02-23 21:30:09,893 CRIT reaped unknown pid 8985)
2018-02-23 21:30:33,144 CRIT reaped unknown pid 9025)
2018-02-23 21:30:37,487 CRIT reaped unknown pid 9043)
```

And the `zabbix_trapper` checks don't receive their values. When I run the script manually in the container itself, script works and sends the data.

I found somewhere a "solution" (Not zabbix related, but supervisor) to change the shell of the user from `false` to `/bin/bash`, but that didn't worked either in my case.

Any suggestions/ideas?

**Comment by dotneft** [comment]
Please try 3.4.7

**Comment by dotneft** [comment]
I suppose in the script you need define environment.
