### ISSUE TITLE
MySQL server is not available. Waiting 5 sec

### ISSUE THREAD

**Issue by nyukers** [zabbix/zabbix-docker#253]
docker run --name some-mysql -t -p 3306:3306 \
-e MYSQL_DATABASE="zabbix" -e MYSQL_ROOT_PASSWORD="root" -e MYSQL_USER="zabbix" -e MYSQL_PASSWORD="zabbix" \
-d mysql/mysql-server:latest

docker run --name zabbix-server -t -p 80:80 -p 10051:10051 \
-e DB_SERVER_HOST="172.17.0.2" -e MYSQL_DATABASE="zabbix" -e MYSQL_USER="zabbix" -e MYSQL_PASSWORD="zabbix" \
-e MYSQL_ROOT_PASSWORD="root" \
-e ZBX_JAVAGATEWAY="zabbix-java-gateway" \
--link some-mysql:mysql --link zabbix-java-gateway:zabbix-java-gateway \
-d zabbix/zabbix-server-mysql:latest

Why do I get such message? Help me.

**Comment by dotneft** [comment]
are you able to connect to MySQL container from Zabbix container?

**Comment by nyukers** [comment]
How can I test it?

**Comment by nyukers** [comment]
Does Zabbix-server-mysql container include Zabbix-server and MySql as 2 in 1 ?

**Comment by dotneft** [comment]
zabbix-server-mysql contains ONLY zabbix_server. But you can try to use mysql cli utility from the container and try to connect to MySQL container.

**Comment by nyukers** [comment]
mysql -u zabbix -p zabbix -h 172.17.0.2
Yes, I able to connect to MySQL container from Zabbix container.

**Comment by dotneft** [comment]
under root?

**Comment by nyukers** [comment]
yes

**Comment by nyukers** [comment]
Ok. I need Zabbix frontend. After start Zabbix-web-apache-mysql container should I to execute "Linking the container to Zabbix server" ?

**Comment by nyukers** [comment]
-d mysql/mysql-server:latest 
changed to
 -d mysql/5.7

**Comment by overheavenlyshadows** [comment]
same problem, cant find how to fix.
I have 2 containers: with mariadb and zabbix server. They are useing networking, not link.
I can ping, connect by root, connect by zabbix usernames, but i always have error MySQL is not available.

**Comment by pvdh** [comment]
The message might be misleading.

It sounds like zabbix fails to connect to the mysql-server, but when I had this issue, the mysql-logs reported a failure to authenticate. So there was no network/firewall/etc. issue but simply a typo in the password.

**Comment by AlanAraujo72** [comment]
It must be the ASCII, UNICODE e UTF-8  PASSWORD.... have you install mariaDb to supporte those formats ?

**Comment by overheavenlyshadows** [comment]
I dont remember how i did fix that problem but check privileges for users in DB. You need give privileges for users for specified network.

**Comment by bjmi** [comment]
The default password authentication plugin changed with MySQL 8.0.4.
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin

Adding this to mysql service section in docker-compose.yml let the zabbix server connect to mysql 8 database again.
`command: --default_authentication_plugin=mysql_native_password`

**Comment by LaurianoElmiroDuarte** [comment]
@jlegido the code in the step [3] no run, error "docker: Error response from daemon: could not get container for zabbix-server: No such container: zabbix-server."

**Comment by dotneft** [comment]
Please check status of Zabbix server container.

**Comment by LaurianoElmiroDuarte** [comment]
up

**Comment by iticworld** [comment]
__Remove double quotation in docker's environments.__

```
echo $(mysqladmin ping -h ${DB_SERVER_HOST} -P ${DB_SERVER_PORT} -u ${DB_SERVER_ROOT_USER} --password="${DB_SERVER_ROOT_PASS}" --connect_timeout=10 $ssl_opts)
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at '"172.16.0.1"' failed
error: 'Unknown MySQL server host '"172.16.0.1"' (0)'
Check that mysqld is running on "172.16.0.1" and that the port is 3306.
You can check this by doing 'telnet "172.16.0.1" 3306'
```

https://github.com/zabbix/zabbix-docker/blob/7550a12631c6e7199717038535ec458050c02468/server-mysql/ubuntu/docker-entrypoint.sh#L196

**Comment by aleks-spv** [comment]
Hello! i am using version zabbix-server-mysql: ubuntu-5.0-latest
Environment variables are not passed to zabbix_server.conf
Building zabbix-server-mysql
Step 1/10 : ARG ZABBIX_VERSION
Step 2/10 : FROM zabbix/zabbix-server-mysql:${ZABBIX_VERSION}
 ---> aaf4bc5ae77d
Step 3/10 : ENV PHP_TZ=Asia/Bishkek
 ---> Using cache
 ---> a3bcfd1b5758
Step 4/10 : ENV DB_SERVER_HOST=db-mysql
 ---> Running in 872573844da5
Removing intermediate container 872573844da5
 ---> 312c30454536
Step 5/10 : ENV DB_SERVER_PORT=3306
 ---> Running in e9d1add469a5
Removing intermediate container e9d1add469a5
 ---> 40b7314e5a8b
Step 6/10 : ENV MYSQL_DATABASE=zabbix
 ---> Running in ceb83a8ff8ae
Removing intermediate container ceb83a8ff8ae
 ---> dd50b694b995
Step 7/10 : ENV MYSQL_USER=zabbix
 ---> Running in 4a1c430616ad
Removing intermediate container 4a1c430616ad
 ---> fdd9b7ae289c
Step 8/10 : ENV MYSQL_PASSWORD=zabbix_password
 ---> Running in 57af191f3f4b
Removing intermediate container 57af191f3f4b
 ---> d1dfbb9417c9
Step 9/10 : ENV MYSQL_ROOT_PASSWORD=zabbix-root-password
 ---> Running in 54811b580dca
Removing intermediate container 54811b580dca
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
docker logs zabbix-server
** Preparing Zabbix server
** Using MYSQL_USER variable from ENV
** Using MYSQL_PASSWORD variable from ENV
** Using MYSQL_ROOT_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: db-mysql
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
**** MySQL server is not available. Waiting 5 seconds...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
docker exec -ti 8b64f69a7e34 bash
zabbix@8b64f69a7e34:/var/lib/zabbix$ cat /etc/zabbix/zabbix_server.conf | grep DBHost
### Option: DBHost
# DBHost=localhost
DBHost=localhost
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
by the way, the logs zabbix-web-nginx-mysql: ubuntu-5.0-latest are the same
**** MySQL server is not available. Waiting 5 seconds...

Pls help

**Comment by jlegido** [comment]
@aleks-spv could you please paste the output of below command?

```
docker inspect zabbix-server
```

**Comment by aleks-spv** [comment]
> @aleks-spv could you please paste the output of below command?
> 
> ```
> docker inspect zabbix-server
> ```

[inspect.txt](https://github.com/zabbix/zabbix-docker/files/5100382/inspect.txt)

**Comment by aleks-spv** [comment]
I don’t know why it happened, but I transferred all the ENV parameters from the dockerfile to the docker-compose.yml, then I deleted all images and containers to clear the cache, the problem was solved!

**Comment by bbrendon** [comment]
Took me awhile to figure this one out...
But the lines below are missing from this file:  https://github.com/zabbix/zabbix-docker/blob/6.4/env_vars/.env_db_mysql

```
# MYSQL_ROOT_USER=root
MYSQL_ROOT_USER_FILE=/run/secrets/MYSQL_ROOT_USER
```
