### ISSUE TITLE
I can't find the file zabbix_server.log anywhere.

### ISSUE THREAD

**Issue by nyukers** [zabbix/zabbix-docker#254]
I set for Zabbix server LogFile=/var/log/zabbix/zabbix_server.log in zabbix_server.conf,
LogType=file and restart container.

Hmm, I can't find the file zabbix_server.log anywhere.

**Comment by dotneft** [comment]
Zabbix docker images are designed to use console log output.

**Comment by majidhashemi70** [comment]
Hello

How to check logs in console?

**Comment by rockaut** [comment]
There is no such server log in containers. Here you must use container logs.

docker logs containername

https://docs.docker.com/engine/reference/commandline/logs/

majidhashemi70 <notifications@github.com> schrieb am So., 13. Okt. 2019,
07:01:
