### ISSUE TITLE
Zabbix in Kubernetes: failed to accept an incoming connection: connection from "192.168.1.123" rejected, allowed hosts: "zabbix-server,10.76.66.182,10.76.66.185"

### ISSUE THREAD

**Issue by miaofenk** [zabbix/zabbix-docker#256]
Hi,

I met the same issue with https://github.com/zabbix/zabbix-docker/issues/186 . The pods and daemonset I deployed is also the same with the previous issue except for the IPs used.

I would like to get an appropriate solution about the issue.

Thanks a lot!

**Comment by dotneft** [comment]
Try to understand why Zabbix server has 192.168.1.123 and what you have IP address for "zabbix-server" DNS.

**Comment by miaofenk** [comment]
I'm sorry that I didn't get your meaning. 192.168.1.123 is the internal IP address of zabbix-server pod. Only the agent on the same worker node with server receives the message from internal IP. 
I know that "zabbix-server" may not work. But if I configured the actual internal IP of zabbix-server, it will be changed when the pod is crashed and recreated.

**Comment by dotneft** [comment]
You can use subnet for Server parameter in Zabbix agent pod. It is allowed since 3.4 version.
