### ISSUE TITLE
 PostgreSQL server is not available. Waiting 5 seconds

### ISSUE THREAD

**Issue by petereyn** [zabbix/zabbix-docker#261]
have a problem creating a zabbix/zabbix-web-nginxpgsql:latest container says that the PostgreSQL server is not available. Waiting 5 seconds

`docker run -e DB_SERVER_ROOT_USER="zabbix" zabbix/zabbix-web-nginx-pgsql:latest
** Deploying Zabbix frontend (nginx) with postgresql database
** Preparing the system
** Preparing Zabbix web-interface
********************
* DB_SERVER_HOST: postgres-server
* DB_SERVER_PORT: 5432
* DB_SERVER_DBNAME: zabbix
* DB_SERVER_ZBX_USER: zabbix
* DB_SERVER_ZBX_PASS: zabbix
********************
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...`

**Comment by dotneft** [comment]
do you have psql in the image?

**Comment by petereyn** [comment]
Yes, i have PostgreSQL 9.2.23

**Comment by dotneft** [comment]
Is it available if you trying connect from the image using credentials above?

**Comment by dotneft** [comment]
No response

**Comment by eldhov** [comment]
Please try to run the zabbix with --network=host. it solved my issue.

https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach/52858101#52858101

**Comment by matrix273** [comment]
echo 'DB_SERVER_ROOT_USER=zabbix' >> env_vars/.env_db_pgsql
