### ISSUE TITLE
HISTORYSTORAGEURL, HISTORYSTORAGETYPE env missing for web images

### ISSUE THREAD

**Issue by neothematrix** [zabbix/zabbix-docker#276]
Hi!
thanks for the great job with these images!

I know ElasticSearch support is still relatively new and experimental, but I noticed that the Zabbix Server images support the ENV variable allowing to configure historystorageurl and historystoragetype, but the same variable cannot be used on the web images.
I know it's still possible to mount the zabbix.conf.php and change it there, but it would be nice to be able to define it as variable like in the server images.

thanks!

**Comment by dotneft** [comment]
Web does not have these env variables yet. Please wait :-)

**Comment by dotneft** [comment]
Added :-)
