### ISSUE TITLE
system.run not support in zabbix agent image since 3.4.8

### ISSUE THREAD

**Issue by hotsnow** [zabbix/zabbix-docker#277]
Zabbix agentd start failed if we set HostnameItem to be "system.run[hostname -f]", looks like not support system.run in HostnameItem setting. 
It happens since alpine-3.4.8. alpine-3.4.7 works well

error message:
---
zabbix_agentd [12]: Warning: failed to get system hostname from [system.run\]hostname -f]])                             
zabbix_agentd [12]: ERROR: "Hostname" configuration parameter is not defined

**Comment by hotsnow** [comment]
@richlv It's correct in my deployment file (zabbix agent running in kubernetes). I'm sure is not my configuration problem because it was working. It works if I change to old image version.

**Comment by dotneft** [comment]
Please show us zabbix agent configuration file

**Comment by hotsnow** [comment]
@dotneft 
Sorry I can't show you de configuration file because container can't be started with this error. I can show you the deployment describe and container start log.

deployment describe:
------
Name:           zabbix-agent-test-666d65d785-lh6q4      
Namespace:      core-zabbix         
Node:           k8s-node-12898100-5/10.1.128.13
Start Time:     Fri, 13 Apr 2018 13:54:46 +0200
Labels:         app=zabbix
                name=zabbix-agent-test                          
                pod-template-hash=2228218341                      
Annotations:    kubernetes.io/psp=fleetboard-default
Status:         Running                                                                 
IP:             172.23.16.68                                                            
Controlled By:  ReplicaSet/zabbix-agent-test-666d65d785                                                                                                      Containers:
  zabbix-agent:                                                                                                                              
    Container ID:   docker://93406f8885f7023fb36276490173420e00bc1015b23f6d13f400a4d0d8a3267e                                                     
    Image:          zabbix/zabbix-agent:alpine-3.4-latest                                         
    Image ID:       docker-pullable://zabbix/zabbix-agent@sha256:6c620326b5dcfc8348a19504e70cfe484708bb00c1838bbc385237612fdf0153
    Port:           10050/TCP                                                                                        
    Host Port:      0/TCP                                                                                                             
    State:          Waiting                    
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 13 Apr 2018 13:56:24 +0200
      Finished:     Fri, 13 Apr 2018 13:56:24 +0200
    Ready:          False
    Restart Count:  4
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:     50m
      memory:  16Mi
    Environment:
      ZBX_SERVER_HOST:    10.0.0.0/8
      ZBX_ACTIVESERVERS:  zabbix-proxy
      ZBX_HOSTNAMEITEM:   system.run["hostname"]
      ZBX_METADATAITEM:   system.run["uname -a;hostname -f"]
      ZBX_DEBUGLEVEL:     3
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8dnhr (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  default-token-8dnhr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8dnhr
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age              From                          Message
  ----     ------                 ----             ----                          -------
  Normal   Scheduled              2m               default-scheduler             Successfully assigned zabbix-agent-test-666d65d785-lh6q4 to k8s-node-1289810
0-5
  Normal   SuccessfulMountVolume  2m               kubelet, k8s-node-12898100-5  MountVolume.SetUp succeeded for volume "default-token-8dnhr"
  Normal   Pulled                 1m (x4 over 2m)  kubelet, k8s-node-12898100-5  Successfully pulled image "zabbix/zabbix-agent:alpine-3.4-latest"
  Normal   Created                1m (x4 over 2m)  kubelet, k8s-node-12898100-5  Created container
  Normal   Started                1m (x4 over 2m)  kubelet, k8s-node-12898100-5  Started container
  Warning  BackOff                1m (x7 over 2m)  kubelet, k8s-node-12898100-5  Back-off restarting failed container
  Normal   Pulling                1m (x5 over 2m)  kubelet, k8s-node-12898100-5  pulling image "zabbix/zabbix-agent:alpine-3.4-latest"
  Warning  BackOff                32s (x24 over 5m)  kubelet, k8s-node-12898100-5  Back-off restarting failed container

container start log:
----------
** Deploying Zabbix agent
** Preparing the system
** Preparing Zabbix agent
** Preparing Zabbix agent configuration file
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "PidFile": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogType": 'console'... added
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogFile": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogFileSize": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "DebugLevel": '3'... added
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "SourceIP": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "EnableRemoteCommands": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogRemoteCommands": ''... removed
** Using '10.0.0.0/8' servers for passive checks
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Server": '10.0.0.0/8'... updated
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenPort": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenIP": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "StartAgents": ''... removed
** Using '10.0.0.0/8:10051,zabbix-proxy' servers for active checks
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ServerActive": '10.0.0.0/8:10051,zabbix-proxy'... updated
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Hostname": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostnameItem": 'system.run["hostname"]'... added
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostMetadata": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostMetadataItem": 'system.run["uname -a;hostname -f"]'... added
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "RefreshActiveChecks": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "BufferSend": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "BufferSize": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "MaxLinesPerSecond": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Timeout": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Include": '/etc/zabbix/zabbix_agentd.d/'... added first occurrence
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "UnsafeUserParameters": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LoadModulePath": '/var/lib/zabbix/modules/'... added
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSConnect": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSAccept": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCAFile": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCRLFile": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSServerCertIssuer": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSServerCertSubject": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCertFile": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSKeyFile": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSPSKIdentity": ''... removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSPSKFile": ''... removed
** Cleaning the system
########################################################
** Starting Zabbix agent
zabbix_agentd [1]: Warning: failed to get system hostname from [system.run\]"hostname"]])
zabbix_agentd [1]: ERROR: "Hostname" configuration parameter is not defined

**Comment by hotsnow** [comment]
Any update on this bug?

**Comment by dick-twocows** [comment]
I've encountered a similar issue with system.run[uuidgen] throwing;

zabbix_agentd [65]: Warning: failed to get system hostname from...

**Comment by dotneft** [comment]
Fixed. Thank you! Very stupid mistake in the script :-(
