### ISSUE TITLE
php7.2+zabbix3.4.8

### ISSUE THREAD

**Issue by ivixq** [zabbix/zabbix-docker#279]
count(): Parameter must be an array or an object that implements Countable [ in latest.php:104]

**Comment by dotneft** [comment]
Which image did you use?

**Comment by mlouala** [comment]
Hi there,
Same issue 

> count(): Parameter must be an array or an object that implements Countable [ in latest.php:104]

With php-7.2.5  and  zabbix-3.4.9 running on arch linux. Downloaded last package from Arch Repository

**Comment by DaviSojogos** [comment]
same ..

![screenshot_2](https://user-images.githubusercontent.com/3921535/40252807-e16a2d16-5ab3-11e8-90f9-798a83cda09d.png)


centos-release-7-5.1804.el7.centos.2.x86_64
PHP 7.2.5 (cli) (built: Apr 28 2018 07:30:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
https://www.zabbix.com/download
http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm

**Comment by fillorkill** [comment]
same here

**Comment by dotneft** [comment]
The problem is not related to images. It is Zabbix issue: https://support.zabbix.com/browse/ZBX-14414
