### ISSUE TITLE
How do you upgrade the database using docker

### ISSUE THREAD

**Issue by ppabc** [zabbix/zabbix-docker#280]
How do you upgrade the database using docker?
My version is Zabbix 3.2.11, and I want to upgrade to Zabbix 3.4.8.
I manually enter docker, perform zabbix_server upgrade, and then start docker again.

**Comment by neogan74** [comment]
If zabbix-server binary upgraded, then when it starts it upgrade automatically the DB if it older than required. Which you can see in the logs.
Do you use separate DB container I suppose?

**Comment by dotneft** [comment]
Everything is correct, thank you Neogan.
