### ISSUE TITLE
Zabbix web time zone not correct

### ISSUE THREAD

**Issue by hotsnow** [zabbix/zabbix-docker#281]
Zabbix frontend page show wrong time because it doesn't change timezone as you defined in docker environment "TZ=Etc/UTC" in file /etc/php5/conf.d/99-zabbix.ini.

image: zabbix/zabbix-web-nginx-mysql:alpine-3.4-latest
sha256:298275c2bb7f8d1fdf742821efad6f9ca1d27cc10f2bbae41ef6b32c90c52b2f

**Comment by dotneft** [comment]
Have you tried PHP_TZ instead of TZ?
