### ISSUE TITLE
ZBX_VALUECACHESIZE custom setting failed

### ISSUE THREAD

**Issue by coder4web** [zabbix/zabbix-docker#283]
Hello!

I have .env file for docker-compose with some settings:
```
ZBX_ENABLE_SNMP_TRAPS=true
...
ZBX_VALUECACHESIZE=128M
```
It has appeared that ValueCacheSize not changed in the zabbix_server.conf file during docker-entrypoint.sh processing (https://github.com/zabbix/zabbix-docker/blob/3.4/server-pgsql/alpine/docker-entrypoint.sh).
Original ValueCacheSize settings in the zabbix_server.conf:
```
### Option: ValueCacheSize
...
# Default:
# ValueCacheSize=8M

```
and it has disappeared after processing instead of new value (128M from ZBX_VALUECACHESIZE):
```
### Option: ValueCacheSize
...
# Default:
EMPTY LINE HERE
```
All other settings from my .env  had changed properly.
But can't be sure about all other Zabbix settings.

ValueCacheSize is important setting for high-load Zabbix configuration, so I think this is high priority issue.

**Comment by dotneft** [comment]
Fixed. Please try the latest images.
