### ISSUE TITLE
Zabbix Agent 3.4.8 errors

### ISSUE THREAD

**Issue by yaron-tracxpoint** [zabbix/zabbix-docker#284]
I've tried deploying 3.4.8 (as alpine-latest) and I got all sorts of weird errors, first: there's no `who` command which is essential for counting the active users in the system, since this is a default check I can't change it.

Furthermore, python is not installed, most of my checks are somehow based on python, it doesn't make any sense to remove it.

I've looked at the latest changes in git and I really like the fact that you removed supervisor but removing python as well may lead to many errors on the users side.

This is the error message about `who`:

    61:20180508:163621.738 Remote command [who | wc -l] result is not unsigned integer
    61:20180508:163621.738 active check "system.users.num" is not supported: Invalid result. Unsigned integer is expected.

**Comment by dotneft** [comment]
Does the image has who command? Actually I do not remember :-)

**Comment by yaron-tracxpoint** [comment]
LOL Well it did, now it doesn't and the base image is the same (`FROM alpine/alpine-3.4`) so I can't really tell what could be wrong, it only means that the script that allegedly installed `who` on top of this images was altered in some way.

BTW, the latest alpine is 3.7 nowadays, not that I see any reason to upgrade but maybe it could solve the problem.

**Comment by dotneft** [comment]
Unfortunately Zabbix does not support Alpine 3.7. It is my dream to upgrade images to 3.7, but... problems with compilation.

**Comment by yaron-tracxpoint** [comment]
Is there any repository for this effort? Maybe I can give it a hand.

Anyways, any way of fixing the bug in 3.4.8?

**Comment by dotneft** [comment]
Sorry, what kind of bug? Alpine 3.7 or "who" command? :-)

**Comment by yaron-tracxpoint** [comment]
Hmm my original issue is that there's no `python` nor `who` command in 3.4.8 agent docker.

Lack of `who` produces an internal error as I printed, this is a default check for counting the current users (not a custom one), so even if I don't need this check I can't disable it (technically I can from the Zabbix Server but it's part of the Linux OS Template so I'd rather keep it that way).

About `python`: this is not a default check, this is a custom check I wrote but it's not working with 3.4.8.

I can only guess that installing some base packages on Alpine would solve that but I can't see any significant change besides the fact that now `supervisor` is no longer used (I can't see why it affected `who` but I can totally understand why it affected `python`).

Regarding migration to Alpine 3.7 I guess we can mark that as "nice to have" :smile: 

I'll try to help with the compilation for Alpine 3.7 and see if I have some insights, any where I can see the progress?

**Comment by dotneft** [comment]
You can see the progress here: https://support.zabbix.com/browse/ZBXNEXT-3653.

I will check who command, but if you need python, please use zabbix-agent as base image for your own image.

**Comment by yaron-tracxpoint** [comment]
Well the fix is only a week old so we can't really have any progress without a fix:
https://github.com/alpinelinux/aports/pull/4178

Anyways, now these 2 will be connected to one another and once the PR will be merged this one can be fixed as well.

Now we can focus on the 3.4.8 bug with `who` and `python` :smile: 
Any clues yet?

**Comment by dotneft** [comment]
Fixed. thank you!
