### ISSUE TITLE
Unable to import templates from zabbix/zabbix-web-nginx-mysql:alpine-latest 

### ISSUE THREAD

**Issue by calebkhor** [zabbix/zabbix-docker#308]
This is in reference to the following commit 3e4cf5c:

I found a bug is that it is not possible to import any xml templates using the image zabbix/zabbix-web-nginx-mysql:**alpine-latest**. The error I got was this:

`Fatal error: Uncaught Error: Call to undefined function simplexml_load_string() in /usr/share/zabbix/include/classes/import/readers/CXmlImportReader.php:40 Stack trace: #0 /usr/share/zabbix/include/classes/api/services/CConfiguration.php(139): CXmlImportReader->read('<?xml version="...') #1 /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php(123): CConfiguration->import(Array) #2 /usr/share/zabbix/include/classes/api/wrappers/CFrontendApiWrapper.php(97): CLocalApiClient->callMethod('configuration', 'import', Array, 'f1eeb9ed3a1c19c...') #3 /usr/share/zabbix/include/classes/api/wrappers/CApiWrapper.php(94): CFrontendApiWrapper->callClientMethod('import', Array) #4 /usr/share/zabbix/include/classes/api/wrappers/CFrontendApiWrapper.php(63): CApiWrapper->callMethod('import', Array) #5 /usr/share/zabbix/include/classes/api/wrappers/CApiWrapper.php(82): CFrontendApiWrapper->callMethod('import', Array) #6 /usr/share/zabbix/conf.import.php(166): CApiWrapper->__call('import', Array) #7 {main} thrown in /usr/share/zabbix/include/classes/import/readers/CXmlImportReader.php on line 40
`
This was, however possible with **ubuntu-latest**

Perhaps the php xmlrpc library has to be installed for alpine-latest for this to work?

**Comment by mtruiz81** [comment]
Hi 
I got same problem when using zabbix/zabbix-web-nginx-mysql:alpine-trunk

`Fatal error: Uncaught Error: Call to undefined function simplexml_load_string() in /usr/share/zabbix/include/classes/import/readers/CXmlImportReader.php:40 Stack trace: #0 /usr/share/zabbix/include/classes/api/services/CConfiguration.php(139): CXmlImportReader->read('<?xml version="...') #1 /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php(123): CConfiguration->import(Array) #2 /usr/share/zabbix/include/classes/api/wrappers/CFrontendApiWrapper.php(97): CLocalApiClient->callMethod('configuration', 'import', Array, 'e4f9c376ae13949...') #3 /usr/share/zabbix/include/classes/api/wrappers/CApiWrapper.php(94): CFrontendApiWrapper->callClientMethod('import', Array) #4 /usr/share/zabbix/include/classes/api/wrappers/CFrontendApiWrapper.php(63): CApiWrapper->callMethod('import', Array) #5 /usr/share/zabbix/include/classes/api/wrappers/CApiWrapper.php(82): CFrontendApiWrapper->callMethod('import', Array) #6 /usr/share/zabbix/conf.import.php(166): CApiWrapper->__call('import', Array) #7 {main} thrown in /usr/share/zabbix/include/classes/import/readers/CXmlImportReader.php on line 40`

how we can fix it ?

Thanks

**Comment by dotneft** [comment]
Fixed. Thank you!

**Comment by ar01xph** [comment]
Worked great. Thank you!
