### ISSUE TITLE
Missing database creation flow

### ISSUE THREAD

**Issue by kfir-drivenets** [zabbix/zabbix-docker#315]
I tried to use the docker image `zabbix/zabbix-web-nginx-mysql:ubuntu-3.0.17` to deploy a local zabbix installation.
It took me a long time to figure out that I need to manually initialize my mysql database with the initial tables. Most containers should be just 'plug&play'. I think that the container should install an empty schema if it is missing from the provided database.
If you still decide to avoid from doing that for some reason you should at the very least add an explanation to the README in docker hub on how to initialize the database..

I just found https://www.zabbix.com/documentation/3.0/manual/installation/containers
I think this link should appear on the docker hub README...

**Comment by dotneft** [comment]
Everything is documented, please read it carefully :-) You need zabbix-server image to create database.

**Comment by yasinlachiny** [comment]
no 
the document is awful
