### ISSUE TITLE
changes are getting lost in zabbix_server.conf

### ISSUE THREAD

**Issue by sauraahu** [zabbix/zabbix-docker#318]
We had issue with Default CacheSize as it was going out of memory. We attached volume to /etc/zabbix from docker to local path and placed zabbix_server.conf with changes, but as soon as container starts, it overwrites the zabbix_server.cong with new parameter we gave, how do we make sure changes are not lost when container is tarting to zabbix_server.conf?

**Comment by dotneft** [comment]
You need to use environment variables, it is not allowed to attach /etc/zabbix.

**Comment by sauraahu** [comment]
i gave env variable in zabbix docker as --env ZS_CacheSize="2G" --env ZS_HistoryIndexCacheSize="512M" --env ZS_ValueCacheSize="1G" and still i see same issue. Also tried with --env CacheSize="2G" --env HistoryIndexCacheSize="512M" --env ValueCacheSize="1G", this also didnt worked . Same error-

1:20180608:050225.242 [file:strpool.c,line:51] zbx_mem_malloc(): out of memory (requested 160 bytes)
     1:20180608:050225.242 [file:strpool.c,line:51] zbx_mem_malloc(): please increase CacheSize configuration parameter

Do you have some document to follow to set environment variable in dockerised form?

**Comment by dotneft** [comment]
Why do you use ZS_CacheSize? Please read documentation carefully! https://www.zabbix.com/documentation/3.4/manual/installation/containers#usage

**Comment by jangaraj** [comment]
ZS_* syntax for env variables is used by https://github.com/monitoringartist/dockbix-xxl. Be sure about used Docker image.

**Comment by JhonnyBeGood** [comment]
please tell me how to write the environment variable for the parameter "increase CacheSize configuration parameter"
I use Docker container to start Zabbix Server
