### ISSUE TITLE
Legend is't displayed on the graphs.

### ISSUE THREAD

**Issue by stallion2303** [zabbix/zabbix-docker#321]
I use image zabbix/zabbix-web-nginx-pgsql:centos-3.4-latest
But legend is't displayed on the graphs.
Reason is that invalid symbolic link /usr/share/zabbix/fonts/graphfont.ttf -> /usr/share/fonts/ttf-dejavu/DejaVuSans.ttf
but must be -> /usr/share/fonts/dejavu/DejaVuSans.ttf

**Comment by dotneft** [comment]
Fixed! Thank you!
