### ISSUE TITLE
Interrupted system call - zabbix agent on Kubernetes

### ISSUE THREAD

**Issue by danielmrosa** [zabbix/zabbix-docker#323]
Hi,
I´m using zabbix/zabbix-agent image inside Kubernetes cluster to monitor some microservices though http checks. When the pod does not exists ( replica 0 for example), rather Zabbix return down, on the Zabbix latest data screen I see the service "shaded". The zabbix agent container log says:

 59:20180621:203609.146 active check "web.page.get[router-app.qa.svc.cluster.local,router/manage/health,8080]" is not supported: HTTP get error: cannot connect to [[router-app.qa.svc.cluster.local]:8080]: [4] Interrupted system call

I have this same agent on another docker swarm cluster using http check and it works.

Does someone can help?

**Comment by dotneft** [comment]
The error means that agent can not open http://router-app.qa.svc.cluster.local:8080/router/manage/health URL. Looks like some network issue.

**Comment by danielmrosa** [comment]
Hi @dotneft 
No, it´s not a network issue. When pod is down, zabbix should return health check down, but it returns cannot connect to the related pod.

**Comment by dotneft** [comment]
Are you able to get the data from Zabbix server pod:
curl -vvv http://router-app.qa.svc.cluster.local:8080/router/manage/health  ?

**Comment by dotneft** [comment]
no response
