### ISSUE TITLE
The status is alawys 'unhealthy'

### ISSUE THREAD

**Issue by Anorpi** [zabbix/zabbix-docker#329]
```
healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost"]
```
The status is alawys show 'unhealthy',because no 'curl' COMMAND in the image.It's ok,when in run `apk add --no-cache curl` in the container.

**Comment by dotneft** [comment]
Hello! What image name are you talking?

**Comment by Anorpi** [comment]
`docker-compose -f ./docker-compose_v3_alpine_mysql_latest.yaml up -d`
I use this yaml file,run the zabbix server.The use `docker ps` command.
IMAGE : `zabbix/zabbix-web-apache-mysql:alpine-3.4-latest`   STATUS  show 'unhealthy'
IMAGE : `zabbix/zabbix-web-nginx-mysql:alpine-3.4-latest`   STATUS  show 'unhealthy'

**Comment by dotneft** [comment]
Ok. Thank you! I will check it.

**Comment by dotneft** [comment]
Fixed. Thank you!
