### ISSUE TITLE
Add curl in zabbix image

### ISSUE THREAD

**Issue by edouardkleinhans** [zabbix/zabbix-docker#334]
Is it possible to add curl in zabbix docker image ?

**Comment by dotneft** [comment]
Which one? :-)

**Comment by dotneft** [comment]
no responce

**Comment by edouardkleinhans** [comment]
Sorry, was on leave. 

I'm using zabbix/zabbix-server-mysql:alpine-3.4-latest, but it must usefull for any zabbix server image. 
Trying to integrate zabbix with slack.

**Comment by dotneft** [comment]
It is useful for you, not sure about most of users :-) If you need it I recommend you create your own image with base image zabbix/zabbix-server-mysql:alpine-3.4-latest.

**Comment by edouardkleinhans** [comment]
Sure, that's what I do.
