### ISSUE TITLE
Add jq to 

### ISSUE THREAD

**Issue by Dolbodrynya** [zabbix/zabbix-docker#335]
Hi!
Есть хороший скрипт для проверки  "просрачивания"

 сертификата, так вот там используется парсилка JSON. Не хватает очень. 

?Is it possible to add jq in 

>  zabbix/zabbix-server-mysql alpine

I will be very grateful

**Comment by dotneft** [comment]
Не самая лучшая идея добавлять подобное. It is not so good idea to add jq. Please make your own images based on required image and add everything you want.
