### ISSUE TITLE
Add Timezone support to server alpine image

### ISSUE THREAD

**Issue by muutech** [zabbix/zabbix-docker#336]
Hi,

How can I set the timezone in the zabbix server image, so it can be the same as the web image, so email notifications show the correct time?

Thanks! 

Keep it up the good work!

**Comment by dotneft** [comment]
Zabbix server/proxy do not depend on locatime. It uses unixtime only. So you do not need it, just make sure that date is correct :-)

**Comment by muutech** [comment]
It is correct, but for example in mail notifications I receive the central time as "event time", no the local time and is confusing. 

Thanks for the quick reply :)

**Comment by dotneft** [comment]
I see, in this case you need to mount /etc/localtime, /etc/timezone for example :-) Actually it depends on OS you use for host.

**Comment by muutech** [comment]
Thanks! It worked perfectly! :)

**Comment by dotneft** [comment]
You are welcome :-)
