### ISSUE TITLE
missing font file

### ISSUE THREAD

**Issue by ixjx** [zabbix/zabbix-docker#338]
There is no font file in the `zabbix-appliance:latest` image ?

Because I started a new container and  found graphs like this:
![](http://shurriklab.qiniudn.com/18-7-19/85511292.jpg)

So I get into the container and found `/usr/share/zabbix/fonts` is empty .
 
Is there should be a font named `graphfont.ttf` ?

**Comment by dotneft** [comment]
I supposed it was fixed. Thank you! I will check. What version of Zabbix do you see in the frontend?

**Comment by ixjx** [comment]
Zabbix 3.4.11

**Comment by dotneft** [comment]
Fixed! Thank you!
