### ISSUE TITLE
Errors with zabbix-web-nginx-pgsql:ubuntu-latest 

### ISSUE THREAD

**Issue by niorg** [zabbix/zabbix-docker#343]
The currently latest version of this image seems to have been rebased to Ubuntu 18.04 in the past days. Anyone else seeing these errors?

Fatal error: Uncaught Exception: Cannot start session. in /usr/share/zabbix/include/classes/core/CSession.php:50 Stack trace: #0 /usr/share/zabbix/include/page_header.php(22): CSession::start() #1 /usr/share/zabbix/include/views/general.login.php(29): require_once('/usr/share/zabb...') #2 /usr/share/zabbix/include/classes/mvc/CView.php(139): include('/usr/share/zabb...') #3 /usr/share/zabbix/index.php(128): CView->render() #4 {main} thrown in /usr/share/zabbix/include/classes/core/CSession.php on line 50

**Comment by dotneft** [comment]
Which image did you use?

**Comment by niorg** [comment]
ubuntu-latest sha256:f5cc693ea909a5cddf135fffd6658f378b1b3e4b060896e0bafa699195eb3c56

**Comment by dotneft** [comment]
I confirm, sorry for that ( Will solve it as soon as possible.

**Comment by dotneft** [comment]
Fixed!
