### ISSUE TITLE
MySQL is not available. Waiting for 5 sec.

### ISSUE THREAD

**Issue by overheavenlyshadows** [zabbix/zabbix-docker#350]
I am using docker-compose. There is yml:
version: '3.6'
services:
  db:
     image: mariadb
     environment:
        MYSQL_ROOT_PASSWORD: 123
     volumes:
       - /docker/maria_db:/var/lib/mysql
     ports:
       - "3306:3306"
     networks:
       - default

  zabbix:
     image: zabbix/zabbix-server-mysql:centos-3.4-latest
     depends_on:
       - db
     environment:
       DB_SERVER_HOST: "DB"
       MYSQL_ROOT_PASSWORD: "123"
       MYSQL_PASSWORD: "123"
       MYSQL_DATABASE: "zabbix_db"
       PHP_TZ: 'Europe/Moscow'
     ports:
       - "10051:10051"
       - "10050:10050"
     networks:
       - default

networks:
   default:
      driver: bridge

I made zabbix user in mariadb and grant privileges (zabbix@%) and created DB
I can ping from zabbix to db. I can use users "root" and "zabbix" for connecting to db. And when i use user "zabbix" i can see zabbix_db.

MariaDB shows this:
Db_1      | 2018-08-02 22:57:21 0 [Note] mysqld (mysqld 10.3.8-MariaDB-1:10.3.8+maria-bionic) starting as process 1 ...
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Using Linux native AIO
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Uses event mutexes
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Number of pools: 1
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Using SSE2 crc32 instructions
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Completed initialization of buffer pool
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=1630887
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Waiting for purge to start
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: 10.3.8 started; log sequence number 1630896; transaction id 21
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1      | 2018-08-02 22:57:21 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1      | 2018-08-02 22:57:21 0 [Note] Recovering after a crash using tc.log
db_1      | 2018-08-02 22:57:21 0 [Note] Starting crash recovery...
db_1      | 2018-08-02 22:57:21 0 [Note] Crash recovery finished.
db_1      | 2018-08-02 22:57:21 0 [Note] Server socket created on IP: '::'.
db_1      | 2018-08-02 22:57:21 0 [Warning] 'proxies_priv' entry '@% root@99c13a6c1891' ignored in --skip-name-resolve mode.
db_1      | 2018-08-02 22:57:21 0 [Note] InnoDB: Buffer pool(s) load completed at 180802 22:57:21
db_1      | 2018-08-02 22:57:21 0 [Note] Reading of all Master_info entries succeded
db_1      | 2018-08-02 22:57:21 0 [Note] Added new Master_info '' to hash table
db_1      | 2018-08-02 22:57:21 0 [Note] mysqld: ready for connections.
db_1      | Version: '10.3.8-MariaDB-1:10.3.8+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

**Comment by dotneft** [comment]
Please show log from zabbix-server-mysql container.

**Comment by overheavenlyshadows** [comment]
I found only below

/var/log/mysql is not exist, can you tell where i can find it?

**Comment by overheavenlyshadows** [comment]
I found my mistake. Problem was occured by capital letters in DB_HOST. But my service called 'db'. There is a mistake.
