### ISSUE TITLE
LoadModule Error

### ISSUE THREAD

**Issue by chace20** [zabbix/zabbix-docker#351]
Hi, there are something wrong when I use LoadModule.

```
     1:20180806:084352.442 In zbx_load_modules()
     1:20180806:084352.442 loading module "/var/lib/zabbix/modules//zabbix_module_docker.so"
     1:20180806:084352.442 cannot load module "zabbix_module_docker.so": Error loading shared library /var/lib/zabbix/modules//zabbix_module_docker.so: No such file or directory
     1:20180806:084352.442 End of zbx_load_modules():FAIL
     1:20180806:084352.442 loading modules failed, exiting...
```
I think that could be the path ```/var/lib/zabbix/modules//zabbix_module_docker.so``` is wrong, there are '//'. I can't fix it.

My startup command is below:
```
docker run \
        -t -i \
        -e ZBX_HOSTNAME="zabbix-agent-test" \
        -e ZBX_DEBUGLEVEL="4" \
        -e ZBX_SERVER_HOST="192.168.2.17" \
        -e ZBX_ACTIVESERVERS="192.168.2.17:10050" \
        -e ZBX_LOADMODULE="zabbix_module_docker.so" \
        zabbix/zabbix-agent:latest
```

**Comment by dotneft** [comment]
I do not see that you mount /var/lib/zabbix/modules/ directory.

**Comment by chace20** [comment]
Yeah, I modify my command as follow. But it still with same error.

```
docker run \
        -e ZBX_HOSTNAME="zabbix-agent-test" \
        -e ZBX_DEBUGLEVEL="4" \
        -e ZBX_SERVER_HOST="192.168.2.17" \
        -e ZBX_ACTIVESERVERS="192.168.2.17:10050" \
        -e ZBX_LOADMODULE="zabbix_module_docker.so" \
        -v /var/lib/zabbix/modules:/home/zabbix/modules \
        zabbix/zabbix-agent:latest
```

**Comment by dotneft** [comment]
Do you have the module in /home/zabbix/modules ?

**Comment by chace20** [comment]
Yeah.
![image](https://user-images.githubusercontent.com/7760149/43708223-91581860-999c-11e8-98d9-f2f51d490cb8.png)

**Comment by chace20** [comment]
Not work.

I don't know why there are '//' in ```/var/lib/zabbix/modules//zabbix_module_docker.so```.

**Comment by chace20** [comment]
My bad. 

My ```.so``` file is build for ubuntu, but the zabbix docker latest tag is alpine.

So the docker can't load the module. I think it's the cause.
