### ISSUE TITLE
zabbix-proxy-mysql exits with error 1 when a check timeouts

### ISSUE THREAD

**Issue by mnowiasz** [zabbix/zabbix-docker#352]
I've got a container running zabbix-proxy-mysql with active checks (some shell scripts). When one of the cheks runs into a timeout, the whole zabbix process exits with error code 1, resulting in a restarting container.

I think the reason for this is the way zabbix-proxy is started:

exec su zabbix -s "/bin/bash" -c "/usr/sbin/zabbix_proxy --foreground -c /etc/zab
bix/zabbix_proxy.conf"

When I remove the exec (su zabbix -s "/bin/bash" -c "/usr/sbin/zabbix_proxy --foreground -c /etc/zab
bix/zabbix_proxy.conf") the proxy runs fine and indicates the offending check (Timeout..). When the exec is present, the whole zabbix_proxy process is terminated with exit 1 when a timeout is reached.

**Comment by mnowiasz** [comment]
Oh, I forgot - I'm using zabbix-proxy-mysql:ubuntu-3.4-latest

**Comment by dotneft** [comment]
Please attach debug log tot the issue.

**Comment by mnowiasz** [comment]
Fair enough. You'll notice that the container id changes from u6y49vmxbwzn to k8z12bhapgk1 - after that it runs smoothly, because in the first case (u6...) is has been started with exec, in the second case the proxy has been started without exec. But the debug log won't help you very much - this is why it took me quite some time to find thnis bug, no errors, just  some logs in docker that the container exited with error 1.

Anyway, this should be piece of cake to verify: Just add a shell skript to /usr/lib/zabbix/externalscripts containing something like sleep 20 and let the proxy execute it using the default timeout.

[debug.log](https://github.com/zabbix/zabbix-docker/files/2269763/debug.log)

**Comment by dotneft** [comment]
It is Zabbix bug if it stops with 1 signal in case of some metric timeouts :-)

**Comment by dotneft** [comment]
But I will check it, thank you! ;-)

**Comment by dotneft** [comment]
Correct! It is not a good idea to remove it at least at current time.
