### ISSUE TITLE
Wrong fping and fping6 path in alpine-images

### ISSUE THREAD

**Issue by skorobkov** [zabbix/zabbix-docker#36]
Fping's in alpine images located at `/usr/sbin/` but in `run_zabbix_component.sh`used `/usr/bin/`

>     update_config_var $ZBX_CONFIG "FpingLocation" "/usr/bin/fping"
    update_config_var $ZBX_CONFIG "Fping6Location" "/usr/bin/fping6"

should be

>     update_config_var $ZBX_CONFIG "FpingLocation" "/usr/sbin/fping"
    update_config_var $ZBX_CONFIG "Fping6Location" "/usr/sbin/fping6"

**Comment by dotneft** [comment]
Hello!

Which image did you try? Actually that problem was fixed some time ago.

**Comment by skorobkov** [comment]
Look into 
https://github.com/zabbix/zabbix-docker/blob/3.2/server-mysql/alpine/run_zabbix_component.sh#L612

and thats what i got in docker:
> ~# docker pull zabbix/zabbix-server-mysql:alpine-3.2-latest
alpine-3.2-latest: Pulling from zabbix/zabbix-server-mysql
Digest: sha256:56aa773c1ee5915b3ee61f45689d9e1ef19d9f7ba0094f0659f9ae887dd9f224
Status: Image is up to date for zabbix/zabbix-server-mysql:alpine-3.2-latest
~# docker run -ti --rm --entrypoint="/bin/sh" zabbix/zabbix-server-mysql:alpine-3.2-latest -c "grep fping /run_zabbix_component.sh"
    update_config_var $ZBX_CONFIG "FpingLocation" "/usr/bin/fping"
    update_config_var $ZBX_CONFIG "Fping6Location" "/usr/bin/fping6"
~# docker run -ti --rm --entrypoint="/bin/sh" zabbix/zabbix-server-mysql:alpine-3.2-latest -c "which fping"
/usr/sbin/fping
~#

**Comment by skorobkov** [comment]
You talk about this fix https://github.com/zabbix/zabbix-docker/commit/5898c48cadf44b7815ea26029b44898b29da73b0 ?
Yes, you fixt `/etc/zabbix/zabbix_proxy.conf` on build, but on container start `/run_zabbix_component.sh` edit it again...

**Comment by dotneft** [comment]
yeah :) just figured out that is rewritten then. Thinking how to solve :(

**Comment by dotneft** [comment]
fixed
