### ISSUE TITLE
Table 'users' already exists; table 'users' empty?

### ISSUE THREAD

**Issue by MaxDiOrio** [zabbix/zabbix-docker#360]
Ok - Trying out the docker container version of Zabbix for the first time and using this as the reference:  https://www.zabbix.com/documentation/4.0/manual/installation/containers

I brought up a mysql container using mysql:5.7.  

I then deployed a zabbix-server-mysql:alpine-latest and pointed it to the mysql instance.  

I got a log stating:

** Creating 'zabbix' user in MySQL database
8/20/2018 11:55:45 AM ** Database 'zabbix' already exists. Please be careful with database COLLATE!
8/20/2018 11:55:45 AM ** Creating 'zabbix' schema in MySQL
8/20/2018 11:55:45 AM ERROR 1050 (42S01) at line 1: Table 'users' already exists

I guess the DB would exist since the mysql container instructions had you create a DB named zabbix.  What I don't expect is that the table 'users' already to exist.

A little further down in the logs, I get:

cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)

It seems like the initial mysql container deployment either shouldn't specify a zabbix database, since the zabbix-server-mysql instance tries to create it, or the zabbix-server-mysql instance needs to work some magic if the table already exists.

**Comment by dotneft** [comment]
Please provide full commands to deploy MySQL and Zabbix server to reproduce the issue. Maybe you specified the same DB name for proxy and server.

**Comment by MaxDiOrio** [comment]
Essentially the following, but I'm using Rancher and Kubernetes.  I don't have a proxy, and it was a clean instance of mysql brought up using the command:

docker run --name mysql-server -t \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="zabbix_pwd" \
      -e MYSQL_ROOT_PASSWORD="root_pwd" \
      -d mysql:5.7

docker run --name zabbix-server-mysql -t \
      -e DB_SERVER_HOST="mysql-server" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="zabbix_pwd" \
      -e MYSQL_ROOT_PASSWORD="root_pwd" \
      --link mysql-server:mysql \
      -p 10051:10051 \
      -d zabbix/zabbix-server-mysql:alpine-latest

**Comment by dotneft** [comment]
Maybe Kubernetes started multiple Zabbix server instances? Please try remove them and try again, and attach instance log files to the issue if the problem occurs again.

**Comment by MaxDiOrio** [comment]
Figured it out.  I had a health check on there to test tcp/10051, but it was set too aggressively.  Since the mysql schema deploy took just over a minute, it automatically put the container in a failed state and restarted it.

Might want to add a quick blurb about container monitors and appropriate values for time out/retries.

Thanks for the help.

**Comment by gelsoncjunior** [comment]
@MaxDiOrio how did you solve it?

**Comment by B3DTech** [comment]
@gelsoncjunior - I pretty much stated what I needed to do. Increase the time of the health check, at least on initial deployment, so that it didn’t time out and recycle the pod.

**Comment by dotneft** [comment]
Yes, initial deployment and upgrade process requires longer time to start services. Deployment - new DB schema is created, Upgrade - DB is upgrading.

But anyway, you need to drop database or tables if you faced such error.
