### ISSUE TITLE
Impossible to use MySQL server because 'root' password is not defined and it is not empty

### ISSUE THREAD

**Issue by bugbugson** [zabbix/zabbix-docker#361]
Hi.
I've read other issues regarding this outcome that were solved by defining db user and pass, but after defining the following environmental variables:

   - "MYSQL_USER"
   - "MYSQL_PASSWORD:"
   - "MYSQL_DATABASE"
   - "DB_SERVER_PORT"
   - "DB_SERVER_HOST"

I'm still getting that output line: Impossible to use MySQL server because 'root' password is not defined and it is not empty.

I've also tried defining a MYSQL_ROOT_PASSWORD manually but it makes no difference.
Is this related to how is my MySQL server configured or am I missing anything when adding variables to run the docker?

NOTE: In DB_SERVER_HOST I'm pointing to an external DB server, but I'm sure it's reachable, since i'm not getting a "MySQL is not available" line

**Comment by bugbugson** [comment]
Closing this: resulted on a syntax error when defining environmental variables. Switching to version 3 expected environmental variables to come as an array
- key1="value1"
And I had it as
"key1:value1"
So it acted like I didn't define anything. Thanks. Hope this helps others with this issue.

**Comment by reckless-huang** [comment]
hello, i just have this problem too ,but i don't know how to solve it
