### ISSUE TITLE
[request]loosing files when using containers as base

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#363]
I have some proxy containers with special software dependencies and so i am using your containers as my base while i'm adding some scripts and software in an own Dockerfile/Build.

Problem is that files which are located in an previously exported volume path like /var/lib/zabbix/modules gets "deleted". Well they aren't deleted the volume just get's mounted and so the files are obstructed. ( https://forums.docker.com/t/files-created-during-docker-build-not-present-in-container-created-from-image/8949/2 )

I'm currently working around this by building my files to another directory first. Then copying the docker-entrypoint.sh and modifing it to copy the files from the build path to the module path.

Would it be acceptable to implement such an behaviour directly into the base docker-entrypoint.sh? I would contribute the code but i firstly wanted to ask if it's accepted or if anyone has a better idea.

Thought about just something like this:
`cp -r /usr/src/zabbix/modules /var/lib/zabbix/`

I see the problem that there might be files overwritten but in the src folders would only be files if it's intended. It also may be firstly enabled with an ENV "switch" which has to be set in the own Dockerfile first.

**Comment by rockaut** [comment]
Another long thread on this (https://github.com/moby/moby/issues/3639).

The other even cleaner workaround would be to remove the Volume directives at all from the bases.

**Comment by dotneft** [comment]
Currently no solution, waiting for multiple modules directory for Zabbix :-(
