### ISSUE TITLE
zabbix-server-mysql:ubuntu-trunk: Support for HTTPS check was not compiled in.

### ISSUE THREAD

**Issue by martin-hu** [zabbix/zabbix-docker#364]
net.tcp.service[https,<ip>,<port>] is unsupported for last week ubuntu trunk (4.0 beta1) image. 
The error message is "Support for HTTPS check was not compiled in."

**Comment by dotneft** [comment]
It is strange. Because it was compiled with libcurl support.

**Comment by dotneft** [comment]
It works fine. Maybe it was beta1 issue :-)
