### ISSUE TITLE
HTTP 403 error often occurs.

### ISSUE THREAD

**Issue by lxepoo** [zabbix/zabbix-docker#366]
I use **ZABBIX alpine-3.4.13**, and now I often make 403 errors when using the web. My server is located in Asia, and the prompt is:

> 403 ERROR
> The request could not be satisfied.
> Bad request.
> 
> Generated by cloudfront (CloudFront)
> Request ID: WBh2zWt8_JHCDZLbslbwDEXe-vF2lwRp2cL8B-2HV-07zJGUXyB0-g==

How do I solve this problem?

**Comment by dotneft** [comment]
What is your request?

**Comment by lxepoo** [comment]
Sorry, it's my fault.
