### ISSUE TITLE
Env for Webinterface language

### ISSUE THREAD

**Issue by milefork** [zabbix/zabbix-docker#367]
Hi,

is it possible to add an Env to set the webinterface lang?

Like this here: https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/39267-german-language-missing-in-2-4-1

So that it is possible to set the Env to for example German and the Cointainer set it while starting in /usr/share/zabbix/include/locales.inc.php

?

**Comment by dotneft** [comment]
Images are provided with enabled languages in Zabbix. Is German enabled in the version you are trying to use?
