### ISSUE TITLE
Providing an ssl.key and ssl.crt file causes the Web-Apache-MySQL container not to start

### ISSUE THREAD

**Issue by jmwebslave** [zabbix/zabbix-docker#368]
<pre>** Deploying Zabbix frontend (apache) with mysql database
** Preparing the system
** Preparing Zabbix web-interface
********************
* DB_SERVER_HOST: mysql-server
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
* DB_SERVER_ROOT_USER: root
* DB_SERVER_ROOT_PASS: [redacted]
* DB_SERVER_ZBX_USER: zabbix
* DB_SERVER_ZBX_PASS: [redacted]
********************
** Adding Zabbix virtual host (HTTP)
** Enable SSL support for Apache2
** Adding Zabbix virtual host (HTTPS)
** Preparing Zabbix frontend configuration file
** Updating '/etc/php.d/99-zabbix.ini' parameter "max_execution_time": '600'... updated
** Updating '/etc/php.d/99-zabbix.ini' parameter "memory_limit": '248M'... updated
** Updating '/etc/php.d/99-zabbix.ini' parameter "post_max_size": '200M'... updated
** Updating '/etc/php.d/99-zabbix.ini' parameter "upload_max_filesize": '200M'... updated
** Updating '/etc/php.d/99-zabbix.ini' parameter "max_input_time": '300'... updated
** Updating '/etc/php.d/99-zabbix.ini' parameter "date.timezone": 'Europe/Riga'... added
** Cleaning the system
########################################################
** Starting Zabbix frontend
[Thu Sep 13 06:42:06.740578 2018] [so:warn] [pid 1] AH01574: module ssl_module is already loaded, skipping
[Thu Sep 13 06:42:06.740708 2018] [so:warn] [pid 1] AH01574: module socache_shmcb_module is already loaded, skipping
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.16.239.5. Set the 'ServerName' directive globally to suppress this message
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:443
no listening sockets available, shutting down
AH00015: Unable to open logs</pre>

**Comment by dotneft** [comment]
Hello! It is known issue and will be fixed in next release. Currently I can recommend you use different OS. I suppose you used CentOS, right?

**Comment by jmwebslave** [comment]
Yes, that's right.  Sorry, I should have specified.  Okay, that's cool - I can make that work.

**Comment by dotneft** [comment]
Fixed. Thank you!
