### ISSUE TITLE
snmp MIBS incorrect ?

### ISSUE THREAD

**Issue by dsteinkopf** [zabbix/zabbix-docker#369]
I am using `zabbix/zabbix-server-mysql`.
And (at least) since the image was upgraded to ubuntu 18.04 I (again) have problems with my snmp checks.
Currently one easy solution is to set in my derived Dockerfile (or set the env somewhere else - e.g. in docker-compose file):
```
ENV MIBDIRS=/var/lib/snmp/mibs/ietf:/var/lib/snmp/mibs/iana:/usr/share/snmp/mibs:/var/lib/zabbix/mibs
```
(It seems the mibs` paths have changed in ubuntu 18.04)

Shouldn't this be set in the Dockerfile for everyone`s convenience? (`https://github.com/zabbix/zabbix-docker/blob/3.4/server-mysql/ubuntu/Dockerfile`)

**Comment by dotneft** [comment]
Thank you! Fixed!
