### ISSUE TITLE
disk space usage statistics on host

### ISSUE THREAD

**Issue by brainsam** [zabbix/zabbix-docker#37]
Hi all! I'm trying to use zabbix-agent on CoreOS and see mostly statistics inside docker container. What I need to mount into zabbix-agent to see volume stats of the host?

**Comment by dotneft** [comment]
Zabbix uses statvfs and statfs kernel functions to get volume stats. I hope it uses /proc/mounts and /proc/diskstats.

PS: Please use Zabbix forum for such questions.
