### ISSUE TITLE
ping not working?

### ISSUE THREAD

**Issue by maximkrusina** [zabbix/zabbix-docker#370]
Hi,

Using completely Dockerized Zabbix infrastructure.

On items: "Template Module ICMP Ping: ICMP ping"
monitored by Zabbix proxy, I'm getting status "Not supported" with info:
fping failed: (null): can't create socket (must run as root?) : Permission denied

Docker image used:
zabbix/zabbix-proxy-sqlite3:ubuntu-latest

Any clue?
Thanx!

**Comment by dotneft** [comment]
I can not confirm the problem. it works fine.
