### ISSUE TITLE
Missing nmap package

### ISSUE THREAD

**Issue by rafacouto** [zabbix/zabbix-docker#371]
_Zabbix server_ comes with a script to detect the OS with _nmap_. 

![Zabbix scripts](https://i.imgur.com/VmP3ZUn.png)

However, _zabbix-docker_ images are missing the nmap utility (**_nmap_ package**) in the _Dockerfile_ installation.

**Comment by dotneft** [comment]
It is just an example. It is not mandatory thing. I'm not sure that it good idea to add it.

**Comment by rafacouto** [comment]
[Debian package](https://packages.debian.org/stretch/zabbix-server-pgsql) recommends nmap and traceroute with zabbix-server-* packages. 

 I'd vote for including it, but it is opinable ;)

**Comment by juanluisbaptiste** [comment]
> It is just an example. It is not mandatory thing. I'm not sure that it good idea to add it.

Why do you think is not a good idea ?

**Comment by fpaternot** [comment]
If it's not necessary for image to run, then i'd say its not required. Simply because docker images are supposed to be lean and clean. Some images even don't have bash or sh. You should be able to run on your docker host as well. Or pack it in in your custom image.

**Comment by juanluisbaptiste** [comment]
Understood :thumbsup:
