### ISSUE TITLE
curl command missing

### ISSUE THREAD

**Issue by marcolino7** [zabbix/zabbix-docker#391]
Hi,
I have a lot of items using curl to perform check.
Since some day I got this error on all of this items:

`"Value "/usr/lib/zabbix/externalscripts/ohab_check.sh: line 10: /usr/bin/curl: not found" of type "string" is not suitable for value type "Numeric (unsigned)."`

It seems curl command is not available. I logged into console with:
`docker exec -it zabbix-server-mysql /bin/bash`
but curl is not present.
Here more detail on version:
![image](https://user-images.githubusercontent.com/11460036/46533109-b8c5df00-c8a3-11e8-9955-3c557ea824f0.png)

**Comment by dotneft** [comment]
You can build your own image based on official ones.

**Comment by marcolino7** [comment]
Hi,
I added curl with this command:

`apk update`
`apk add curl

(1/1) Installing curl (7.60.0-r1)
Executing busybox-1.24.2-r14.trigger
OK: 106 MiB in 47 packages
`

now curl is installed but it do not return me back any value. If I execute same command on the host, i get a results

1) How can I include CURL into container without loose at any reboot?
2) Why result is not returnet?

Thanks

**Comment by dotneft** [comment]
You need to make your own image based on official.

**Comment by maximkrusina** [comment]
Hi @marcolino7 

I had the same issue (with Zabbix server zabbix/zabbix-server-mysql:ubuntu-3.4-latest)

so this is part of my docker-compose:

```
  zabbix-server:
    build:
      context: ./dockerfiles/zabbix-server
    container_name: zabbix-server
```

and this if my Dockerfile, very easy:

```
FROM zabbix/zabbix-server-mysql:ubuntu-3.4-latest

# Install remaining stuff
RUN apt-get update && apt-get install -y \
        curl \
        openssl \
        ca-certificates
```

Didn't tested with 4.0 yet.
