### ISSUE TITLE
Ping works on Zabbix server, not on Zabbix proxy?

### ISSUE THREAD

**Issue by maximkrusina** [zabbix/zabbix-docker#392]
Hi there, just migrated to 4.0 using those Docker images:

server: 
- zabbix/zabbix-server-mysql:ubuntu-4.0-latest
- zabbix/zabbix-web-nginx-mysql:ubuntu-4.0-latest

proxy:
- zabbix/zabbix-proxy-sqlite3:ubuntu-latest

From the main dashboard, I'm trying to ping some hosts.
When the host is monitored by Zabbix Server, the ping works just well.
But there is something with on on Zabbix proxy, affecting both UI Ping from menu and the monitoring. When I invoke Ping from menu, I see this:

Ping
- sh: 1: /bin/ping: not found
- Cannot execute script

In the log of Zabbix Proxy container, I see lot of those items:

`171:20181007:160045.595 fping failed: (null): can't create socket (must run as root?) : Permission denied`

When I SSH into Zabbix Proxy docker image, I can run fping.

Any clue? Thanx!!!

**Comment by dotneft** [comment]
I do not see any issues with fping on proxy. Could you tell us the issue still actual? and if yes, please, tell us exact versions of the images you use.

**Comment by maximkrusina** [comment]
Hi, just found the soluiton:
https://www.zc0317.com/post/view?id=109

So to make it work:
```
docker exec -it zabbix-proxy /bin/bash
chown root:root /usr/bin/fping
chmod u+s /usr/bin/fping
```

PS: looks like fping can be on two different locations: https://github.com/zabbix/zabbix-docker/blob/4.0/proxy-sqlite3/ubuntu/docker-entrypoint.sh si it will good idea to implement this.

Tested on latest: zabbix/zabbix-proxy-sqlite3:ubuntu-latest

Please, can be this added to entrypoint file?
https://github.com/zabbix/zabbix-docker/blob/4.0/proxy-sqlite3/ubuntu/docker-entrypoint.sh

**Comment by Ricaz** [comment]
I'm having the same issue with the `6.2-latest` images.

It's not viable to have to manually `+s` the executable.

**Comment by NetHorror** [comment]
For me, rebooting the proxy after adding new hosts helped
