### ISSUE TITLE
Zabbix-server 4 not a valid Windows path

### ISSUE THREAD

**Issue by vlada-jerkovic** [zabbix/zabbix-docker#393]
I'm trying to start Zabbix on Windows 10 Pro Docker Version 18.06.1-ce-win73 (19507) which is switched to run Linux containers. 
**Error: Cannot create container for service zabbix-server: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path'**

Is it possible to solve this issue for windows environment? It works on Centos 7 virtual machine, but I want to use on docker for Windows. 
- mysql error was solved by sharing the drive.

Commands I used:
git clone https://github.com/zabbix/zabbix-docker
git checkout trunk 
docker-compose -f .\docker-compose_v3_alpine_mysql_latest.yaml pull
docker-compose -f .\docker-compose_v3_alpine_mysql_latest.yaml up -d

PS D:\docker\zabbix-docker> docker-compose -f .\docker-compose_v3_alpine_mysql_latest.yaml up -d
Creating network "zabbix-docker_zbx_net_backend" with driver "bridge"
Creating network "zabbix-docker_zbx_net_frontend" with driver "bridge"
Creating network "zabbix-docker_default" with the default driver
Creating zabbix-docker_zabbix-snmptraps_1    ... done
Creating zabbix-docker_zabbix-java-gateway_1 ... done
Creating zabbix-docker_db_data_mysql_1       ...
Creating zabbix-docker_mysql-server_1        ... error
Creating zabbix-docker_db_data_mysql_1       ... done
ERROR: for zabbix-docker_mysql-server_1  Cannot create container for service mysql-server: b'Drive has not been shared'

ERROR: for mysql-server  Cannot create container for service mysql-server: b'Drive has not been shared'
ERROR: Encountered errors while bringing up the project.

PS D:\docker\zabbix-docker> docker-compose -f .\docker-compose_v3_alpine_mysql_latest.yaml up -d
Starting zabbix-docker_db_data_mysql_1 ...
zabbix-docker_zabbix-java-gateway_1 is up-to-date
Starting zabbix-docker_db_data_mysql_1 ... done
Creating zabbix-docker_mysql-server_1  ... done
Creating zabbix-docker_zabbix-server_1 ... error

** ERROR: for zabbix-docker_zabbix-server_1  Cannot create container for service zabbix-server: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path'

ERROR: for zabbix-server  Cannot create container for service zabbix-server: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path' **
ERROR: Encountered errors while bringing up the project.

**Comment by dotneft** [comment]
Please remove these lines from compose file and try again.

**Comment by vlada-jerkovic** [comment]
I removed  from compose file but it still shows the same error.  
- /etc/localtime:/etc/localtime:ro
- /etc/timezone:/etc/timezone:ro

PS D:\docker\zabbix-docker> docker-compose -f .\docker-compose_v3_alpine_mysql_latest.yaml up -d
WARNING: Some services (zabbix-agent, zabbix-java-gateway, zabbix-proxy-mysql, zabbix-proxy-sqlite3, zabbix-server, zabbix-snmptraps, zabbix-web-apache-mysql, zabbix-web-nginx-mysql) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Starting zabbix-docker_db_data_mysql_1 ...
zabbix-docker_zabbix-java-gateway_1 is up-to-date
zabbix-docker_zabbix-snmptraps_1 is up-to-date
zabbix-docker_mysql-server_1 is up-to-date
Creating zabbix-docker_zabbix-server_1 ... error
Starting zabbix-docker_db_data_mysql_1 ... done
ERROR: for zabbix-docker_zabbix-server_1  Cannot create container for service zabbix-server: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path'

ERROR: for zabbix-server  Cannot create container for service zabbix-server: b'Mount denied:\nThe source path "\\\\etc\\\\localtime:/etc/localtime"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
PS D:\docker\zabbix-docker>

**Comment by dotneft** [comment]
remove all lines with these volumes :-)

**Comment by vlada-jerkovic** [comment]
:-) I did that, but unfortunately it didn't help. Do you have any other idea?

**Comment by dotneft** [comment]
it is impossible, because only yaml file has such mount volume information.

**Comment by vlada-jerkovic** [comment]
Please check this yaml file? Maybe I'm missing something. 
1  removed all  
/etc/localtime:/etc/localtime:ro
/etc/timezone:/etc/timezone:ro
2 Restared docker on my computer.
3 Executed commands:
docker-compose -f .\docker-compose_v3_alpine_mysql_latest.yaml down
docker-compose -f .\docker-compose_v3_alpine_mysql_latest.yaml up -d


[docker-compose_v3_centos_mysql_latest .yaml.txt](https://github.com/zabbix/zabbix-docker/files/2488814/docker-compose_v3_centos_mysql_latest.yaml.txt)

**Comment by dotneft** [comment]
Looks good! Are you able to run "docker run -it --rm centos bash"?

**Comment by vlada-jerkovic** [comment]
yes, it works.

**Comment by dotneft** [comment]
Hmmm .... you attached docker-compose_v3_centos_mysql_latest .yaml, but trying to run alpine version.

**Comment by vlada-jerkovic** [comment]
Thanks. Attached modified compose file which is working on Windows 10 Pro. (rename file removing .txt extension)

Modified:
 zabbix-web-apache-mysql:
  image: zabbix/zabbix-web-apache-mysql:alpine-trunk
  ports:
   **- "80"
   - "443"**

[docker-compose_v3_alpine_mysql_latest.yaml.txt](https://github.com/zabbix/zabbix-docker/files/2489464/docker-compose_v3_alpine_mysql_latest.yaml.txt)

**Comment by VectorBCO** [comment]
this problem was not solved in a code
new members (as me) still facing with the same problem on at least centos_pgsql configuration

**Comment by dotneft** [comment]
these files are for example, just remove these "Linux-style" lines

**Comment by VectorBCO** [comment]
> these files are for example, just remove these "Linux-style" lines
yes, I know but my expectation (and I believe not only my) that if someone will open official documentation https://www.zabbix.com/documentation/4.4/manual/installation/containers?s[]=docker
and execute Example1 or Example2 will get a result (nor a strange error)

at the same time there more than 1 problems with those examples: postgress sql container cannot get access to the folder 
![image](https://user-images.githubusercontent.com/13451494/71517681-80972b80-28af-11ea-8884-f7d4d34236ae.png)

**Comment by dotneft** [comment]
where from the output? What is that?

**Comment by VectorBCO** [comment]
Reproduction: 
1 Install docker on windows (windows 10 pro 1903)
2 cd d:\projects # any location on a PC
3  git clone https://github.com/zabbix/zabbix-docker.git
4 open Yaml file and commmenting out all /etc/time config lines
5 execute command from example 1 or 2 : docker-compose -f .\docker-compose_v3_centos_pgsql_latest.yaml up -d
6 docker ps -a
![image](https://user-images.githubusercontent.com/13451494/71520162-fa80e200-28ba-11ea-961a-09e74a2290eb.png)
7 docker logs <appache id>
![image](https://user-images.githubusercontent.com/13451494/71520231-403daa80-28bb-11ea-8aa6-362c049203ac.png)
8 docker logs <postgres-sql id>
![image](https://user-images.githubusercontent.com/13451494/71520290-8c88ea80-28bb-11ea-9246-5cf9c690da70.png)

**Comment by dotneft** [comment]
So, it is related to PostgreSQL. It is known PostgreSQL issue: https://github.com/docker-library/postgres/issues/435

**Comment by VectorBCO** [comment]
Alexey, thanks for links 
this comment solve my problem 
https://github.com/docker/for-win/issues/445#issuecomment-550054803

Issue was in yaml file stored on zabbix repo (at least solution was in modification zabbix sample)
![image](https://user-images.githubusercontent.com/13451494/71521294-61ed6080-28c0-11ea-8b67-4c8365078332.png)
