### ISSUE TITLE
duplicate output in snmptraps.log output

### ISSUE THREAD

**Issue by ryn9** [zabbix/zabbix-docker#396]
Using the lastest zabbix/zabbix-snmptraps docker build...

I believe I am missing something simple - but I cannot stop getting duplicate output in snmptraps.log output.

I have tried a handful of different images, tried playing with docker network settings, explored the settings for snmptrapd and snmptrapfmt, all to no avail.

Following docker logs for the images, appears to show only one-to-one messages as compared to whats coming in off the network.... but still there appears to be 2 log lines in snmptraps.log.

**Comment by ryn9** [comment]
anyone got ideas?
would like to get this sorted out :/

**Comment by dotneft** [comment]
I suppose it is a problem with image, sometime ago I figured out the same behavior. Please try different OS image for snmptraps. Originally it is Ubuntu.

**Comment by ryn9** [comment]
I tried different images with the same issue

**Comment by nagalakshmikurnella** [comment]
I am also seeing the same problem with zabbix-snmptraps:alpine-3.4.x and the latest. Can someone please give us the verison that doesn't have this problem.

**Comment by petersonbasso** [comment]
I'm also having this problem, any solution?

**Comment by dotneft** [comment]
Thank you! Fixed!

**Comment by ryn9** [comment]
I think you got it in the latest release :)
