### ISSUE TITLE
zabbix-server images: wrong volume path /usr/lib/zabbix/alertscripts, /usr/lib/zabbix/externalscripts

### ISSUE THREAD

**Issue by Shawyeok** [zabbix/zabbix-docker#40]
The default values of `AlertScriptsPath` and `ExternalScripts` are `/usr/share/zabbix/alertscripts` and `/usr/share/zabbix/externalscripts`, but we specify two volumes which path start with `/usr/lib/zabbix`, it was a mistake.

I thought there are two ways able to fix it:

1. add option `--datadir=/usr/lib` to configure.
2. change volume path to `/usr/share/zabbix/alertscripts` and `/usr/share/zabbix/externalscripts` directly.

Any ideas? :-)

**Comment by dotneft** [comment]
fixed
