### ISSUE TITLE
service.zabbix-proxy-sqlite3.ulimits.mem_limit to appropriate type: "512m" is not a valid integer

### ISSUE THREAD

**Issue by taobaohi** [zabbix/zabbix-docker#401]
docker-compose -f ./docker-compose_v2_alpine_mysql_latest.yaml up -d
ERROR: Error while attempting to convert service.zabbix-proxy-sqlite3.ulimits.mem_limit to appropriate type: "512m" is not a valid integer

**Comment by jasgeo75** [comment]
Have you cloned the full directory?  Do you have all of the necessary .env files?

**Comment by oldskool73** [comment]
Not OP, but I got the same error, looks like you have an old bug come back https://github.com/zabbix/zabbix-docker/pull/188

Several of your `mem_limit` blocks are incorrectly indented, the have an extra prefix space character, thus putting them under the `ulimits` block which is wrong.

**Comment by dotneft** [comment]
What version of compose do you use?
