### ISSUE TITLE
cannot connect to mariadb

### ISSUE THREAD

**Issue by Randix6644** [zabbix/zabbix-docker#403]
I've deployed the Zabbix server (ubuntu-trunk)  and Mariadb(10.4.0) with docker on two different machines. I can connect to the database on the zabbix server machine, so it's not a firewall issue. When I check the log of Zabbix server it keeps saying:
`**** MySQL server is not available. Waiting 5 seconds...`

`mysqladmin: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`

And I checked the Mariadb log,  I found out  there was no request coming from zabbix server.
And I'm sure the password and db name are all correct.

I deployed the Zabbix server through Ansible, the enviroment variables I provide are as following:
` 
   env:
      DB_SERVER_HOST: "{{ zabbix['DB_SERVER_HOST']}}"
      MYSQL_USER: "{{ zabbix['MYSQL_USER'] }}"
      MYSQL_PASSWORD: "{{ zabbix['MYSQL_PASSWORD']}}"
      ZBX_JAVAGATEWAY_ENABLE: true
`

**Comment by Randix6644** [comment]
it seems like a mount point issue. 
`
 /docker/zabbix/var/lib:/var/lib
`

`
/docker/zabbix/usr/lib:/usr/lib
`
if i mount like this , the problem will occur.

**Comment by dotneft** [comment]
It is not a good idea to mount /usr/lib
