### ISSUE TITLE
mysql aborted connection

### ISSUE THREAD

**Issue by fajanssen** [zabbix/zabbix-docker#404]
Hey there,

We are recently getting many erros in MySQL DB logs and also the zabbix-server-mysql-ubuntu container is dying every 10mins. The checks are still running, because we defined to always restart the container and the web-container is not affected, but its pretty annoying.

We get the following in the MySQL db logs:

[Note] Aborted connection 36 to db: 'zabbix' user: 'zabbix' host: '<container-ip>' (Got an error reading communication packets)

container is latest version + we installed OpenSSL for external script

MySQL  Ver 14.14 Distrib 5.7.24

Greetings Fabian

**Comment by dotneft** [comment]
Do you still have such issue?

**Comment by dotneft** [comment]
Please reopen if you have such issue!

**Comment by fajanssen** [comment]
Hey there,

Yes the issue still exists. There is also sometimes a "Bad Handshake" in the MySQL error-log

**Comment by dotneft** [comment]
Please show us Zabbix server log with such errors.

**Comment by fajanssen** [comment]
These are the last lines from the log right before the container stops:

`   165:20190116:135334.275 In zbx_process_triggers() values_num:9
   165:20190116:135334.275 In zbx_process_trigger() triggerid:15403 value:0(0) new_value:3
   165:20190116:135334.275 End of zbx_process_trigger():FAIL flags:0
   165:20190116:135334.275 In zbx_process_trigger() triggerid:15471 value:0(0) new_value:3
   165:20190116:135334.275 End of zbx_process_trigger():FAIL flags:0
   165:20190116:135334.275 In zbx_process_trigger() triggerid:15529 value:0(0) new_value:3
   165:20190116:135334.275 End of zbx_process_trigger():FAIL flags:0
   165:20190116:135334.275 In zbx_process_trigger() triggerid:15585 value:0(0) new_value:3
   165:20190116:135334.275 End of zbx_process_trigger():FAIL flags:0
   165:20190116:135334.275 In zbx_process_trigger() triggerid:15650 value:0(0) new_value:3
   165:20190116:135334.275 End of zbx_process_trigger():FAIL flags:0
   165:20190116:135334.275 In zbx_process_trigger() triggerid:15874 value:0(0) new_value:3
   165:20190116:135334.275 End of zbx_process_trigger():FAIL flags:0
   165:20190116:135334.275 In zbx_process_trigger() triggerid:15953 value:0(0) new_value:3
   165:20190116:135334.275 End of zbx_process_trigger():FAIL flags:0
   165:20190116:135334.275 In zbx_process_trigger() triggerid:16083 value:0(0) new_value:3
   165:20190116:135334.275 End of zbx_process_trigger():FAIL flags:0
   165:20190116:135334.275 In zbx_process_trigger() triggerid:16129 value:0(0) new_value:3
   165:20190116:135334.275 End of zbx_process_trigger():FAIL flags:0
   165:20190116:135334.275 End of zbx_process_triggers()
   165:20190116:135334.275 End of DCmass_update_triggers()
   165:20190116:135334.275 In DCmass_update_trends()
   165:20190116:135334.275 End of DCmass_update_trends()
   165:20190116:135334.275 In process_events() events_num:0
   165:20190116:135334.275 End of process_events() processed:0
   165:20190116:135334.275 query [txnlev:1] [commit;]
   165:20190116:135334.275 In DBupdate_itservices()
   165:20190116:135334.275 End of DBupdate_itservices():SUCCEED
   165:20190116:135334.275 __zbx_zbx_setproctitle() title:'history syncer #1 [synced 12 items in 0.044821 sec, idle 1 sec]'`

**Comment by dotneft** [comment]
Sorry, why we are talking about container stop, I supposed you have problem with MySQL aborted connections?

**Comment by fajanssen** [comment]
No its about the container stopping after about 6mins. And then i get the MySQL erros as the container died :(

**Comment by dotneft** [comment]
please show last 20-100 lines without debug enabled.

**Comment by fajanssen** [comment]
Since yesterday the Problem is gone. We had some issues with an external script that apperently caused the zabbix container to crash. 

The external script is used to count the number of files in an sftp-server directory, but it started to fail because of configuration changes to the security settings of the sftp-server.
