### ISSUE TITLE
Wrong include directive in php-fpm.conf on alpine

### ISSUE THREAD

**Issue by devopssmart** [zabbix/zabbix-docker#405]
In [php-fpm.conf](https://github.com/zabbix/zabbix-docker/blob/4.0/web-nginx-pgsql/alpine/conf/etc/php7/php-fpm.conf) on alpine images you have the following line 
`
include = /etc/php5/fpm.d/*.conf
`

But the image use php7-fpm and in the Docker file we copy zabbix php config into php7-fpm' config folder
`
COPY ["conf/etc/php7/conf.d/99-zabbix.ini", "/etc/php7/conf.d/"]
`

Similar issue with path to php-fpm socket(it doesn't break anything but can confuse)
`
listen = /var/run/php5-fpm.sock
`

**Comment by dotneft** [comment]
Fixed
