### ISSUE TITLE
Getting Zabbix agent on Zabbix server is unreachable for 5 minutes error

### ISSUE THREAD

**Issue by psv-001** [zabbix/zabbix-docker#409]
Hi,

I am new to Zabbix tool, I wanted to monitor some of the docker containers that I am running in my local vagrant setup.

I am trying to integrate zabbix-server with postgresql, zabbix-agent and zabbix-web-nginx.

I have ran following run commands -

1. zabbix-server:
docker run --name zabbix-server -t \
      --net plat_setup_default \
      -e DB_SERVER_HOST="192.xxx.xxx.x" \
      -e POSTGRES_USER="postgres" \
      --link postgres:postgres \
      --link zabbix-agent:zabbix-agent \
      -p 10051:10051 \
      -d zabbix/zabbix-server-pgsql:latest

2. web-nginx:
docker run --net plat_setup_default --name zabbix-web-nginx-pgsql -e DB_SERVER_HOST="192.xxx.xxx.x" --link postgres:postgres \
--link zabbix-server:zabbix-server -e POSTGRES_USER="postgres" -e ZBX_SERVER_HOST="172.18.0.1" -p 18195:18195 -d zabbix/zabbix-web-nginx-pgsql:latest

3. Zabbix-agent:
docker run --net plat_setup_default --name zabbix-agent --link zabbix-server:zabbix-server -e ZBX_HOSTNAME="zabbix-server" -e ZBX_SERVER_HOST="172.18.0.18" --privileged -d zabbix/zabbix-agent:latest

Please note that, I am not sure about the ZBX_SERVER_HOST variable here, I have done docker inspect of server and added the IP in agents run command.

I am getting following issues while deploying and running the Zabbix server, agent.

zabix-agent logs:
   59:20181205:133513.767 no active checks on server [172.18.0.18:10051]: host [zabbix-server] not found

zabbix-server logs:
155:20181205:133513.767 cannot send list of active checks to "172.18.0.20": host [zabbix-server] not found

![hosts](https://user-images.githubusercontent.com/30928840/49517192-9101f000-f8c1-11e8-9d00-92da98ec8663.JPG)
![monitoring](https://user-images.githubusercontent.com/30928840/49517193-9101f000-f8c1-11e8-88a0-e4561ef59f11.JPG)

Attached are screen shots of the zabbex web.

Quick help will be really appreciated.

**Comment by dotneft** [comment]
Please configure DNS.

**Comment by bozerkins** [comment]
I am having the same problem with zabbix-appliance docker image for ubuntu 3.2 build. @dotneft , could you at least provide a link to the docs to resolve this issue?

**Comment by kakakikikeke** [comment]
I solved it. Please try below configuration. 

* Host name･･･zabbix-agent
* Agent interfaces -> DNS name -> zabbix-agent
* Agent interfaces -> Connect to -> DNS

![zabbix_with_docker2](https://user-images.githubusercontent.com/1751050/59748614-710ea880-92b6-11e9-8d55-dda911e74bd7.png)

I think you can tentatively make the status green in this way.

**Comment by kushlychok** [comment]
Let me ask, did you configure file .env_zabbix and modify next line? ZBX_SERVER_HOST=zabbix-agent
