### ISSUE TITLE
SNMP  not working？

### ISSUE THREAD

**Issue by windsdeng** [zabbix/zabbix-docker#41]
zabbix-server-mysql ：  SNMP  not working？

**Comment by lord2y** [comment]
have you connected volume for MIBs files?

**Comment by dotneft** [comment]
please elaborate the question.

**Comment by lord2y** [comment]
@dotneft I meant `docker run [...] -v /usr/share/snmp/mibs:/var/lib/zabbix/mibs [...] -d zabbix/zabbix-server-mysql`

**Comment by dotneft** [comment]
solved
