### ISSUE TITLE
zabbix-server-pgsql with custom schema raises errors after restart 

### ISSUE THREAD

**Issue by Tsimon-Dorakh** [zabbix/zabbix-docker#411]
Having DB_SERVER_SCHEMA set docker-entrypoint.sh doesn't recognize that DB has been already initialized and tries to do it again. Therefore a bunch of errors are happened:
```
** Deploying Zabbix server with postgresql database
** Preparing the system
** Preparing Zabbix server
********************
* DB_SERVER_HOST: postgres
* DB_SERVER_PORT: 5432
* DB_SERVER_DBNAME: db
* DB_SERVER_SCHEMA: zabbix
* DB_SERVER_ZBX_USER: zabbix
* DB_SERVER_ZBX_PASS: zabbix
********************
** Database 'test_postgres_db' already exists. Please be careful with database owner!
** Creating 'test_postgres_db' schema in PostgreSQL
ERROR:  relation "users" already exists
ERROR:  relation "users_1" already exists
....
```
The root cause migth be because _public_ namespace is used during the DB check (https://github.com/zabbix/zabbix-docker/blob/4.0/server-pgsql/alpine/docker-entrypoint.sh#L438 https://github.com/zabbix/zabbix-docker/blob/4.0/server-pgsql/alpine/docker-entrypoint.sh#L442)

**Comment by dotneft** [comment]
Fixed. Thank you!
