### ISSUE TITLE
Why so many volumes?

### ISSUE THREAD

**Issue by fabiang** [zabbix/zabbix-docker#412]
Hello,

what is the reason why the images have so many default volumes? Docker creates an volume for each of those and the contents of a volume are hard to update, once the image is updated.

Currently I've trouble installing my "externalscripts" to `/usr/lib/zabbix/externalscripts/` in my own image, since I've to find and the correct volume each time I update the contents of "externalscripts".

IMHO there should be not be any default volumes in any of the images. If I want any of the folder to be an volume I can to it later by config with the flags `-v`, `--mount` or by `docker-compose.yml`

**Comment by dotneft** [comment]
It is known issue. Please wait while Zabbix will support multiple externalscripts volumes.
