### ISSUE TITLE
Implement ZBX_SESSION_NAME for zabbix-web

### ISSUE THREAD

**Issue by santyzu13** [zabbix/zabbix-docker#416]
Trying to access two Zabbix frontend installations on the same host, on different ports, simultaneously will fail. Logging into the second one will terminate the session on the first one - unless the default frontend session name is adjusted for the second frontend in frontend [definitions](https://www.zabbix.com/documentation/4.0/manual/web_interface/definitions) (see ZBX_SESSION_NAME).

**Comment by dotneft** [comment]
Added. Thank you!
