### ISSUE TITLE
nginx proxy zabbix-web-nginx-mysql

### ISSUE THREAD

**Issue by xinxiamu** [zabbix/zabbix-docker#417]
1. install zabbix-web-nginx-mysql:

docker run --name zabbix-web-nginx-mysql --hostname zabbix-web-nginx-mysql \
--link zabbix-mysql-server:mysql \
--link zabbix-server-mysql:zabbix-server \
-e DB_SERVER_HOST="mysql" \
-e MYSQL_ROOT_PASSWORD="xcsqjr.123456" \
-e MYSQL_USER="zabbix" \
-e MYSQL_PASSWORD="xcsqjr.123456" \
-e MYSQL_DATABASE="zabbix" \
-e ZBX_SERVER_HOST="zabbix-server" \
-e PHP_TZ="Asia/Shanghai" \
-p 8083:80 \
-d zabbix/zabbix-web-nginx-mysql:centos-4.0.2

2.proxy it use my nginx

upstream zabbix {
    server localhost:8083;
    #server localhost:8081;
}
server {
    listen       80;                                                         
    server_name  zabbix.xxx.com;                                               
    client_max_body_size 1024M;

    location / {
        proxy_pass http://zabbix;
        proxy_set_header Host $host:$server_port;
    }
}

brows : http://zabbix.xxx.com; it cat not load some resource ,and it is very slowly.please help!

**Comment by dotneft** [comment]
does it work fine without proxy?

**Comment by dotneft** [comment]
Please reopen if you have such issue!
