### ISSUE TITLE
Server cant see agents

### ISSUE THREAD

**Issue by frenzymind** [zabbix/zabbix-docker#418]
Hello!
My compose part with zabbix:

>   zabbix:
    privileged: true
    image: zabbix/zabbix-agent:alpine-latest
    ports:
      - '10050:10050/tcp'
    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - ZBX_HOSTNAME=${ZBX_HOSTNAME}
      - ZBX_DEBUGLEVEL=3
    volumes:
      - /:/rootfs
      - /var/run:/var/run

when I start I see:

> ** Starting Zabbix agent
zabbix_1_149bcd499014 | Starting Zabbix Agent [HOST_IP]. Zabbix 4.0.2 (revision 87228).
zabbix_1_149bcd499014 | Press Ctrl+C to exit.
zabbix_1_149bcd499014 | 
zabbix_1_149bcd499014 |      1:20181220:095621.790 Starting Zabbix Agent [HOST_IP]. Zabbix 4.0.2 (revision 87228).
zabbix_1_149bcd499014 |      1:20181220:095621.790 **** Enabled features ****
zabbix_1_149bcd499014 |      1:20181220:095621.790 IPv6 support:          YES
zabbix_1_149bcd499014 |      1:20181220:095621.790 TLS support:           YES
zabbix_1_149bcd499014 |      1:20181220:095621.790 **************************
zabbix_1_149bcd499014 |      1:20181220:095621.790 using configuration file: /etc/zabbix/zabbix_agentd.conf
zabbix_1_149bcd499014 |      1:20181220:095621.791 agent #0 started [main process]
zabbix_1_149bcd499014 |     62:20181220:095621.791 agent #1 started [collector]
zabbix_1_149bcd499014 |     63:20181220:095621.791 agent #2 started [listener #1]
zabbix_1_149bcd499014 |     64:20181220:095621.792 agent #3 started [listener #2]
zabbix_1_149bcd499014 |     65:20181220:095621.800 agent #4 started [listener #3]
zabbix_1_149bcd499014 |     66:20181220:095621.800 agent #5 started [active checks #1]
zabbix_1_149bcd499014 |     63:20181220:095644.919 Message from 192.168.128.6 is missing header. Message ignored.
zabbix_1_149bcd499014 |     64:20181220:095744.953 Message from 192.168.128.6 is missing header. Message ignored.
zabbix_1_149bcd499014 |     63:20181220:095844.048 Message from 192.168.128.6 is missing header. Message ignored.
zabbix_1_149bcd499014 |     64:20181220:095944.001 Message from 192.168.128.6 is missing header. Message ignored.

zabbix server cant see client. What do I do worng ? Any working guide ?

**Comment by dotneft** [comment]
What is 192.168.128.6? Is it old Zabbix server/proxy?

**Comment by frenzymind** [comment]
192.168.128.6 is current zabbix server, but installed without docker.

**Comment by frenzymind** [comment]
> root@zabbix-server:~# zabbix_server --version
Zabbix server v2.4.8 (revision 59539) (20 April 2016)
Compilation time: May  4 2016 06:15:03

**Comment by neogan74** [comment]
Zabbix 4.0.X agent is not properly working with oldest Zabbix server version, because there was changed the protocol.  So forward agent compatibility never was an option for agent.
