### ISSUE TITLE
Updating Zabbix from 3.4.9 to 4.0.x frontend DB version mismatch

### ISSUE THREAD

**Issue by PeterBizQIT** [zabbix/zabbix-docker#419]
Currently I am trying to upgrade our Zabbix server from version 3.4.9 to 4.0.2. I am using the following images:

zabbix-server-mysql:ubuntu-4.0.2
zabbix-web-apache-mysql:ubuntu-4.0.2

At the Zabbix server container logs I can confirm that the DB gets updated. However, when I try to open the webinterface I receive the following error:

`Database error

    The frontend does not match Zabbix database. Current database version (mandatory/optional): 4000000/4000003. Required mandatory version: 3040000. Contact your system administrator.
`

When entering the web frontend container and changing the following variables to 4.0.2 in defines.inc.php I am able to login but many SQL errors appear all over the web interface:

`
define('ZABBIX_VERSION',                '3.4.9');
define('ZABBIX_API_VERSION',    '3.4.9');
define('ZABBIX_EXPORT_VERSION', '3.4');
define('ZABBIX_DB_VERSION',             3040000);
`

I tried the above both with version ubuntu-4.0.2 and ubuntu-4.0.3. However, none of these images work for me.

Am I missing something in the upgrade process?

**Comment by dotneft** [comment]
You have old web or Zabbix server, while your database is 4.0.

**Comment by PeterBizQIT** [comment]
You're right! I forgot to edit the Dockerfile for the web frontend.

I successfully updated our Zabbix server to 4.0.2 now.
