### ISSUE TITLE
Install Chinese language pack, but there is no locale

### ISSUE THREAD

**Issue by lvtu0316** [zabbix/zabbix-docker#420]
I execute the following command
```
yum install kde-l10n-Chinese
yum reinstall glibc-common
```
But 
`locale -a `
thereis no zh_cn anyway !
please help!
thinks!

**Comment by dotneft** [comment]
Why do you need Chinese lang pack? For Zabbix web-interface?

**Comment by lvtu0316** [comment]
I need to display Chinese on the frontend.

**Comment by lvtu0316** [comment]
> Why do you need Chinese lang pack? For Zabbix web-interface?

I need to display Chinese on the front end.

**Comment by dotneft** [comment]
Actually it must be enabled for 4.0 by default. Do you use Ubuntu image?

**Comment by lvtu0316** [comment]
I used zabbix/zabbix-web-nginx-mysql:centos-trunk

**Comment by lvtu0316** [comment]
this is in centos image:(and i yum install kde-l10n-Chinese )
![image](https://user-images.githubusercontent.com/29847918/50443418-56c6c400-093e-11e9-9327-a31321bd539f.png)

this is in ubuntu image:
![image](https://user-images.githubusercontent.com/29847918/50443380-22530800-093e-11e9-8426-b671bd67acf7.png)

**Comment by dotneft** [comment]
Zabbix frontend language does not depend on system locales. You just need to choose Chinese language in the frontend. you do not need to change anything in the image.

**Comment by lvtu0316** [comment]
You are not able to choose some of the languages, because locales for them are not installed on the web server.
![image](https://user-images.githubusercontent.com/29847918/50461258-2b80bb00-09b8-11e9-950a-ebef6c790a50.png)

**Comment by dotneft** [comment]
It is true only for Ubuntu version. Please show env output from the docket container you use.

**Comment by lvtu0316** [comment]
> It is true only for Ubuntu version. Please show env output from the docket container you use.

docker run --name php-nginx --link zabbix-server:zabbix-server -p 80:80 -e DB_SERVER_HOST="192.168.66.20" -e MYSQL_USER="root" -e MYSQL_PASSWORD="root" -e ZBX_SERVER_HOST="zabbix-server" -e PHP_TZ="Asia/Shanghai" -d zabbix/zabbix-web-nginx-mysql:ubuntu-trunk

**Comment by dotneft** [comment]
I mean env command output from the container. And actually why you use trunk?

**Comment by dotneft** [comment]
Which languages do you see in the list?

**Comment by lvtu0316** [comment]
Chinese（zh_cn）

I changed ubuntu image ,this is in ubuntu-4.0-latest tag.But not in centos image。
![image](https://user-images.githubusercontent.com/29847918/50475204-cef4be80-09fe-11e9-9236-0e1b0d592ded.png)

**Comment by dotneft** [comment]
It is strange a bit. I will check why CentOS does not have translations.

**Comment by lvtu0316** [comment]
OK, very thanks!

**Comment by dotneft** [comment]
CentOS images are fixed now!
