### ISSUE TITLE
Can not create host using (zabbix/zabbix-server-mysql:centos-4.0-latest)(zabbix-web-nginx-mysql:ubuntu-trunk)

### ISSUE THREAD

**Issue by lvtu0316** [zabbix/zabbix-docker#421]
![image](https://user-images.githubusercontent.com/29847918/50461382-09d40380-09b9-11e9-8165-2da499b5dad3.png)

**Comment by dotneft** [comment]
Why do you use trunk for web and 4.0 for server?

**Comment by lvtu0316** [comment]
I think there is only trunk for 4.0, yes?
![image](https://user-images.githubusercontent.com/29847918/50463077-4a854a00-09c4-11e9-8559-59eb0caead22.png)

**Comment by dotneft** [comment]
No. 4.0 is not trunk! It is release since a few months ago. Trunk and 4.0 are not compatible

**Comment by dotneft** [comment]
Sorry, it is mistake )

**Comment by lvtu0316** [comment]
so which tag should i use?

**Comment by dotneft** [comment]
Use the same tag like you have for server image

**Comment by lvtu0316** [comment]
Thanks! The problem is solved,
