### ISSUE TITLE
default username and password for zabbix-appliance

### ISSUE THREAD

**Issue by MeenachiSundaram** [zabbix/zabbix-docker#422]
I got the following docker run command here - `https://www.zabbix.com/documentation/3.4/manual/installation/containers`

```
# docker run --name zabbix-appliance -t \
      -p 10051:10051 \
      -p 80:80 \
      -d zabbix/zabbix-appliance:latest
```

Zabbix web interface is working fine, but what is the default username and password

because in docker log i can see the following but it's not working !!

```
********************
* DB_SERVER_HOST: localhost
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
* DB_SERVER_ROOT_USER: root
* DB_SERVER_ROOT_PASS:
* DB_SERVER_ZBX_USER: zabbix
* DB_SERVER_ZBX_PASS: zabbix
********************
```

**Comment by dotneft** [comment]
According Zabbix documentation: Admin/zabbix :-)

**Comment by MeenachiSundaram** [comment]
> According Zabbix documentation: Admin/zabbix :-)

May i know the documentation link where it specifies this username/password, and yep it works !!

**Comment by dotneft** [comment]
Here it is https://www.zabbix.com/documentation/4.0/manual/quickstart/login
