### ISSUE TITLE
[DNS] implement nscd to prevent dns flooding and increase dns resolution reliability

### ISSUE THREAD

**Issue by fpaternot** [zabbix/zabbix-docker#425]
I'm talking about ubuntu image, but this could apply to alpine and centos as well, i didn't check.

During tests migrating to docker we noticed a lot of DNS request errors originating from proxies. 

Further investigation led us to solve it by simply installing `nscd` to our image based on zabbix-proxy-sqlite3:ubuntu-${VERSION} image.

We are also considered adding the following to /etc/resolv.conf, to increase dns resolution reliabilty.

```
options		attempts:2
options		timeout:1
```

Note: our test included a couple proxies and ~1knvps, so the load was relevant but not that big.

**Comment by dotneft** [comment]
Feel free to use our images as base images for your required purposes. We deliver our images as is, so nothing added from our side (clean images).

**Comment by fpaternot** [comment]
Perhaps it could be documented somewhere, then.

Without it, if the only dns query fails, we have a dns resolution failure and the item fails, possibily triggering a false-positive on zabbix.

Docker nativaly creates a dns server on 127.0.0.11 that resolves the services locally, but has no retry/timeout. It's up to the image to solve those issues.

Also, `nscd` is only a few kb in centos and ubuntu:

```
Dependencies Resolved

==========================================================================
 Package                                                Arch                                                     Version                                                         Repository                                              Size
==========================================================================Installing:
 nscd                                                   x86_64                                                   2.17-260.el7                                                    base                                                   281 k

Transaction Summary
==========================================================================Install  1 Package

Total download size: 281 k
Installed size: 183 k
```

ubuntu
```
root@5e2a65281d7d:/var/lib/zabbix# apt-cache show nscd | grep Size:
Installed-Size: 440
Size: 78096
root@5e2a65281d7d:/var/lib/zabbix# 
```

I'm fine solving this on my end, but others might encounter this problem as well. With that said and as Zabbix is supposed to be stable and reliable, i think is expected to minimize dns issues as basic and cheap to solve as 200k. The point of this ticket is to avoid others from falling into the same issue.

**Comment by dotneft** [comment]
It is quite common task and does not related to Docker at all. Zabbix uses DNS requests if you monitor devices using domain names. So in this case independent of docker or vm or hardware server it is better to have DNS caching mechanism :-)

**Comment by fpaternot** [comment]
Let me circle back to this issue to suggest an improvement.

As you put it, it sounds its no business of zabbix images to manage it in any way. However, for domain queries to perform reasonably well (you know, it's udp) it's recommended to use some DNS caching as you've put yourself. And Zabbix support's both IP and DNS interfaces. So, it does seems like it's related to docker 

The images however do not document it in any way. So, some suggestions:

- Use nscd locally in all images. This way the `container is independent` from anything else (and that's kind of the point of using containers)
- Use nscd from docker-host (`volume /var/run/nscd/socket`)[1]
- Last but not least, if none of the above, we should document some sort of **`BIG WARNING`** letting people know that DNS queries do not use any caching and should be either avoided or solved by those interested in using DNS.

[1]Source: https://github.com/moby/moby/issues/33298
