### ISSUE TITLE
ZBX_SESSION_NAME for zabbix-web is NOT WORKING

### ISSUE THREAD

**Issue by santyzu13** [zabbix/zabbix-docker#426]
I'm trying to use ZBX_SESSION_NAME on zabbix/zabbix-web-nginx-mysql:alpine-4.0.3, but it's not working.

**Comment by dotneft** [comment]
Try to use latest instead of already released version.

**Comment by santyzu13** [comment]
Thanks for your reply. I tried again with zabbix/zabbix-web-nginx-mysql:alpine-latest, zabbix/zabbix-web-nginx-mysql:latest, zabbix/zabbix-web-apache-mysql:ubuntu-latest, but when I check the file /usr/share/zabbix/include/defines.inc.php, the "ZBX_SESSION_NAME" var never changes.

This is my command:

docker run --name some-zabbix-web-nginx-mysql -e DB_SERVER_HOST="10.0.0.5" -e MYSQL_DATABASE="zabbixser" -e MYSQL_USER="zabserver" -e MYSQL_PASSWORD="XXXXXXXX" -e ZBX_SERVER_HOST="10.0.0.2" -e PHP_TZ="America/Bogota" -e ZBX_SESSION_NAME="prueba123" -d zabbix/zabbix-web-apache-mysql:ubuntu-latest


Thanks

**Comment by santyzu13** [comment]
I was looking on the changes applied on the last commit, and I think the problem could be in this line:

sed "/ZBX_SESSION_NAME/s/'[^']*'/'${ZBX_SESSION_NAME}'/2" "$ZBX_WWW_ROOT/include/defines.inc.php"

I think your are missing "-i" option in the sed command.

Thanks.

**Comment by dotneft** [comment]
PS: Agree with "-i" argument. Sorry for that. I updated GIT. Please wait some time.

**Comment by santyzu13** [comment]
Thanks for your help. Everything is fine now.
