### ISSUE TITLE
System error occurred. Please contact Zabbix administrator.

### ISSUE THREAD

**Issue by downright77086** [zabbix/zabbix-docker#427]
I'm currently try to test Zabbix and keep getting this message in the browser once I login. 
"System error occurred. Please contact Zabbix administrator." 
Here is my docker-compose file. In front of this i have NGINX doing certs.
__________________
version: '3.1'
services:
  postgres-server:    # The Postgres Database Service
    image: postgres:latest
    restart: always
    environment:   # Username, password and database name variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata #data storage

  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:centos-latest
    restart: always
    environment:   # The Postgres database value variable
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      DB_SERVER_HOST: postgres-server
      DB_SERVER_PORT: 5432
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    volumes:  # Volumes for scripts and related files you can add
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts

  zabbix-web:    # The main Zabbix web UI or interface
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:  # Postgre database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      DB_SERVER_HOST: postgres-server
      DB_SERVER_PORT: 5432
      ZBX_SERVER_HOST: zabbix-server  # Zabbix related and Php variables
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "America/Vancouver"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 8090:80

  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent:latest
    privileged: true   #access mode for allowing resource access
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST= #the IP/Dns of Zabbix server
___________________________
The only issues I see from the docker logs is in zabbix-server container.
 "173:20190121:203717.664 server #29 started [alert manager #1]"

**Comment by dotneft** [comment]
Please change include/defines.inc.php variable ZBX_SHOW_TECHNICAL_ERRORS to true and check ones again.

**Comment by downright77086** [comment]
@dotneft would that go under the Server or web interface contianer

**Comment by dotneft** [comment]
under web interface container, please.

**Comment by downright77086** [comment]
Not showing any errors 
in the containers and the website showing still the same

**Comment by dotneft** [comment]
It is impossible :-)

function filter_messages(array $messages = []) {
        if (!ZBX_SHOW_TECHNICAL_ERRORS && CWebUser::getType() != USER_TYPE_SUPER_ADMIN && !CWebUser::getDebugMode()) {
                $filtered_messages = [];
                $generic_exists = false;

                foreach ($messages as $message) {
                        if (array_key_exists('src', $message) && ($message['src'] === 'sql' || $message['src'] === 'php')) {
                                if (!$generic_exists) {
                                        $message['message'] = _('System error occurred. Please contact Zabbix administrator.');
                                        $filtered_messages[] = $message;
                                        $generic_exists = true;
                                }
                        }
                        else {
                                $filtered_messages[] = $message;
                        }
                }
                $messages = $filtered_messages;
        }

        return $messages;

**Comment by downright77086** [comment]
Where should i be finding the debug error output

**Comment by dotneft** [comment]
Nope, you need to connect to the container, find include/defines.inc.php file and change mentioned definition to true. Then just try again, you do not need to restart container.

**Comment by downright77086** [comment]
Okay 
____
Cookie names must not be empty [zabbix.php:21 → require_once() → ZBase->run() → ZBase->authenticateUser() → CWebUser::checkAuthentication() → CWebUser::setSessionCookie() → zbx_setcookie() → setcookie() in include/func.inc.php:104]
_____

**Comment by dotneft** [comment]
Ops... what is ZBX_SESSION_NAME value in include/defines.inc.php?

**Comment by downright77086** [comment]
define('ZBX_SESSION_NAME', ''); // Session cookie name for Zabbix front-end.

**Comment by dotneft** [comment]
please pass ZBX_SESSION_NAME variable with zbx_sessionid value as env variable and restart container

**Comment by downright77086** [comment]
Does it matter what the ZBX_SESSION_NAME is for the docker-compose.yml file

**Comment by dotneft** [comment]
does not matter where....

**Comment by downright77086** [comment]
okay msg is now gone @dotneft thank you for your help.
I think i need to create a ticket for the users selection and create as this does not show up in browser as documented on the official guide.

**Comment by dotneft** [comment]
It is bug, I fixed it right now. So after a few days you can remove it :-)
