### ISSUE TITLE
Add ZBX_LISTENPORT to Proxy and Server

### ISSUE THREAD

**Issue by fpaternot** [zabbix/zabbix-docker#428]
Much like the https://github.com/zabbix/zabbix-docker/issues/402, it would be great to add ZBX_LISTENPORT to both `Server` and `Proxy` so we can run multiple containers inside the same docker host using `network_mode = host` in compose or `--ip` in `docker run`.

**Comment by dotneft** [comment]
I do not understand usecase of such installation :-) Could you explain me that?

**Comment by fpaternot** [comment]
Default briged docker networks use [`masquerade`](https://docs.docker.com/v17.09/engine/userguide/networking/#docker-and-iptables), in other words: NAT.

It just came to our attention a problem when monitoring our `netapp` storage cluster that has multiple ips. In some situations we make a snmp request trough one ip and it comes back using another. That happens because of multiple "heads/controllers". Note that this scenario is true for other cases as well, where devices have multiple ips (think a web server with multiple ips, for instance).

Let me show the `netapp` case on tcpdump:

```
18:40:49.539959 IP (tos 0x0, ttl 63, id 43942, offset 0, flags [DF], proto UDP (17), length 75) 10.10.0.136.43155 > 10.10.66.5.161: [bad udp cksum 0x57d5 -> 0x7c4c!]  { SNMPv2c C="public" { GetRequest(28) R=1495520451  .1.3.6.1.2.1.1.5.0 } } 
18:40:49.542464 IP (tos 0x0, ttl 61, id 2604, offset 0, flags [none], proto UDP (17), length 103) 10.10.65.5.161 > 10.10.0.136.43155: [udp sum ok]  { SNMPv2c C="public" { GetResponse(52) R=1495520451  .1.3.6.1.2.1.1.5.0="filer.domain" } } 
18:40:54.105422 IP (tos 0x0, ttl 63, id 37663, offset 0, flags [DF], proto UDP (17), length 75) 10.10.0.136.59424 > 10.10.65.5.161: [bad udp cksum 0x56d5 -> 0x24ec!]  { SNMPv2c C="public" { GetRequest(28) R=1596170716  .1.3.6.1.2.1.1.5.0 } } 
18:40:54.105914 IP (tos 0x0, ttl 61, id 2860, offset 0, flags [none], proto UDP (17), length 103) 10.10.65.5.161 > 10.10.0.136.59424: [udp sum ok]  { SNMPv2c C="public" { GetResponse(52) R=1596170716  .1.3.6.1.2.1.1.5.0="filer.domain" } }
```

Note that the request `1495520451` asks for sysName.0 on 10.10.**66**.5 but gets it's reply from 10.10.**65**.5. That difference makes `iptables` disregard that package so our container never gets that reply giving a timeout error.

This is what the container sees in it veth:
```
18:40:49.539912 IP (tos 0x0, ttl 64, id 43942, offset 0, flags [DF], proto UDP (17), length 75) 172.18.0.3.43155 > 10.10.66.5.161: [bad udp cksum 0xf8e2 -> 0xdb3e!]  { SNMPv2c C="public" { GetRequest(28) R=1495520451  .1.3.6.1.2.1.1.5.0 } } 
```

The package get's out but no package returns because it's not forwarded back to container from docker host.

So, in networks where we have this kind of situation, it seems better to not use NAT and go straight to `network_mode = host`. But if we do that we need to set different ports to Proxy/Server otherwise they would conflict and not start due to 'cannot bind/assign port'.

**Comment by dotneft** [comment]
Understood. I will add it soon :-)

**Comment by dotneft** [comment]
Fixed! Thank you
