### ISSUE TITLE
[Request] TimescaleDB support in 4.2

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#429]
I know it's a little early but as with yesterday official support for TimescaleDB is stated for 4.2 can we prepare the containers accordingly.

- Will the default PGSQL container just be switched to the TimescaleDB container or more sane and prefered will there be an third container (mysql,pgsql, tsdb)?
- Also can then please be the migration script included in this container? So we can just spin up the stack with tsdb instead of pgsql as standalone and execute the migration script directly in the container. Afterwards just booting up the whole stack again be happy :D

**Comment by dotneft** [comment]
Added! Thank you!
