### ISSUE TITLE
[Request] Healthcheck scripts

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#430]
Would be cool if the containers could implement own healthcheck scripts for native docker health checks where applicable.

**Comment by fpaternot** [comment]
I agree but recommend some discretion here.

Remember we have several conditions that might deceive a simple healthcheck. Think of a simple healthcheck as a check if a listening port is there, it there is a process poller running and so on.

I can think of at least this non-trivial conditions:

* zabbix server is performing a db upgrade routine typically between major versions
* zabbix server database is too big, so it takes a while to start up (some of mine takes up 120sec)
* zabbix database is external and down so the service won't start (not a container issue, no point in restarting/recreating it). We might wanna know that through health monitor though. Interesting point for discussion.

This thread is promising, we can come up with some good documentation on it. :)

**Comment by dotneft** [comment]
Docker compose files already have such kind of examples how to check health.

**Comment by fpaternot** [comment]
I see healthcheck only for nginx and apache. Did I miss something? We were hopping for some server/proxy/agent healthchecks.

**Comment by giggio** [comment]
> I see healthcheck only for nginx and apache. Did I miss something? We were hopping for some server/proxy/agent healthchecks.

Yes, it seems we are missing healthchecks for those ones.

**Comment by pantovad** [comment]
+1 for this one - Zabbix beeing a monitoring software lacking a health check endpoint of its core server process does not sound right.

**Comment by dotneft** [comment]
depends on https://support.zabbix.com/browse/ZBXNEXT-7658.
