### ISSUE TITLE
x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by jdkcn** [zabbix/zabbix-docker#431]
ubuntu version zabbix-server can't request https urls.

should install `ca-certificates` package.

**Comment by dotneft** [comment]
Do you mean web-scenarios?

**Comment by dotneft** [comment]
I just checked web-scenarios with HTTPS on zabbix-server-mysql:ubuntu-4.0.6. No problems. Could you identify example of the issue?

**Comment by jdkcn** [comment]
@dotneft  Use wget show this error

root@8370fdf46abb:/var/lib/zabbix# wget https://github.com
--2019-04-11 23:39:10--  https://github.com/
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
ERROR: cannot verify github.com's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.

I'll send another error from a go script to call https rest service error later.

**Comment by jdkcn** [comment]
I use a go program to send the notification message to a Dingtalk's api not working.


<img width="776" alt="Screen Shot 2019-04-12 at 7 56 48 AM" src="https://user-images.githubusercontent.com/3855/56003319-ae741a00-5cf8-11e9-87d8-f69de98ac3fd.png">

<img width="763" alt="Screen Shot 2019-04-12 at 7 57 31 AM" src="https://user-images.githubusercontent.com/3855/56003317-ae741a00-5cf8-11e9-845b-f54832344a59.png">

After install `ca-certificates` the problem solved.

**Comment by dotneft** [comment]
fixed. Thank you!
