### ISSUE TITLE
zabbix-web API api_jsonrpc.php missing

### ISSUE THREAD

**Issue by mauro-vaccari** [zabbix/zabbix-docker#433]
I try with both zabbix-web-nginx and zabbix-web-apache but when I try to access to api:

http://servername/zabbix/api_jsonrpc.php I receive this error:

The requested URL /zabbix/api_jsonrpc.php was not found on this server.

So trying to add it to graphana for example don't work

**Comment by dotneft** [comment]
You do need to use subdirectory /zabbix/. Try just: http://servername/api_jsonrpc.php

**Comment by mauro-vaccari** [comment]
Thank you for the quick reply,

That's fine.

Work correctly.

Thanks
>>> Alexey Pustovalov <notifications@github.com> 19/02/2019 16.43 >>>
You do need to use subdirectory /zabbix/. Try just:
http://servername/api_jsonrpc.php
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(
https://github.com/zabbix/zabbix-docker/issues/433#issuecomment-465184080)
, or mute the thread
(
