### ISSUE TITLE
Timezone enviroment variable

### ISSUE THREAD

**Issue by netarea** [zabbix/zabbix-docker#436]
https://github.com/zabbix/zabbix-docker/blob/37a938db81fa61924a288911d7a7b333ae813dfc/web-apache-pgsql/alpine/docker-entrypoint.sh#L31

There is $TZ variable in documentation page.
https://www.zabbix.com/documentation/4.0/manual/installation/containers#usage

**Comment by dotneft** [comment]
Fixed. Thank you!
