### ISSUE TITLE
zabbix-appliance missing ping

### ISSUE THREAD

**Issue by rsynnest** [zabbix/zabbix-docker#437]
I think the zabbix-appliance Docker image needs iputils and traceroute installed similar to zabbix-server as discussed in  #114 and fixed in commit 8a4defcf67c7f76e

**Comment by dotneft** [comment]
Which OS image do you mean? Alpine based already have iputils.

**Comment by rsynnest** [comment]
Sorry, this was for zabbix/zabbix-appliance:ubuntu-latest
