### ISSUE TITLE
Zabbix agent on Zabbix server is unreachable

### ISSUE THREAD

**Issue by lord2y** [zabbix/zabbix-docker#44]
It looks like zabbix-server-mysql does not have support for agent. 
When I enabled monitoring for zabbix-server itself zabbix triggers an alert and I'm not able to get metrics from it

**Comment by dotneft** [comment]
Each Zabbix component has dedicated image. Zabbix server does not include Zabbix agent. So you need to run Zabbix agent image and configure it in the web-interface.

**Comment by aliusmiles** [comment]
Is there a more detailed instructions on how to use zabbix-agent container for monitoring zabbix-server container? When running docker-compose with default variables, I got the following in logs:
```
zabbix-server_1           |    121:20161031:134119.483 cannot send list of active checks to "172.16.238.5": host [ef63588b4ee1] not found
zabbix-agent_1            |   7928:20161031:134119.483 no active checks on server [zabbix-server:10051]: host [ef63588b4ee1] not found
```
Or the only way to monitor zabbix-server container is to link it just to "Template App Zabbix server", as described in https://github.com/zabbix/zabbix-docker/issues/65?

**Comment by dotneft** [comment]
what do you want to monitor there? if internal health just use "Template App Zabbix server"

**Comment by aliusmiles** [comment]
Would be useful to monitor CPU, memory, etc. From https://github.com/zabbix/zabbix-docker/blob/3.2/agent/alpine/README.md I've got an impression that linking `zabbix-agent` to `zabbix-server` would allow monitoring of `zabbix-server` container and usage of "OS Linux" template. Guess I was wrong, but how exactly zabbix-agent container could be used then?

P.S. System stats monitoring should be achievable by simply installing zabbix-agent on docker host itself, right?

**Comment by dotneft** [comment]
feel free to install agent on host system or enable privileged permissions to zabbix agent container

**Comment by aliusmiles** [comment]
Thanks!
