### ISSUE TITLE
Default Zabbix Templates on Build?

### ISSUE THREAD

**Issue by donnyv12** [zabbix/zabbix-docker#442]
Hi all, 

Instead of using the UI or API to import templates, I would like to include them as part of the zabbix-server docker build. I have noticed that when I start a zabbix-server docker image with a clean Mysql db, there are templates that exist with triggers by default. I've looked through the code for the build and can't find these "default" templates. Are they included with the install of zabbix? Any way to import templates into the build (and remove the default templates?). 

Thanks and sorry if this is a dumb question.

**Comment by dotneft** [comment]
It is prepared SQL inserts :-) But you can extend Zabbix server/frontend images and add additional templates as you want.

**Comment by donnyv12** [comment]
Could you point me to the line in the entrypoint.sh where that is? I would like to try and extend the image. Thank you for answering my question :)

**Comment by dotneft** [comment]
It is not trivial task. You must change Dockerfile and place in entrypoint which responsible to schema data import.

**Comment by donnyv12** [comment]
I see, so I can't just comment a line out to get rid of the default templates, or replace with a different source for custom template import?

**Comment by dotneft** [comment]
Unfortunately not. File data.sql contains all initial data (users, groups and etc), so you can not just ignore the file. You need to replace it with your own.
