### ISSUE TITLE
Unsupported item key

### ISSUE THREAD

**Issue by for-mat** [zabbix/zabbix-docker#443]
我安装的zabbix-server和zabbix-agent版本都是alpine-4.0.5。在添加监控模板后，mysql的监控项都无法使用，显示错误为  Unsupported item key ,更换其他版本后都无效，在使用rpm版的zabbix-agent时，会解决这个问题，但是又会导致自动发现会报错。妈个鸡，该怎么整
The zabbix-server and zabbix-agent versions I installed are alpine-4.0.5.After adding the monitoring template, the monitoring items of mysql could not be used, and the error was displayed as Unsupported item key, which was invalid after changing other versions. When using zabbix-agent of RPM version, this problem would be solved, but it would lead to automatic finding and error reporting.Fuck！How should the whole
![image](https://user-images.githubusercontent.com/43637488/54744865-09878500-4c03-11e9-8edf-758e85328f40.png)

**Comment by dotneft** [comment]
Please use volumes to add Included userparameters.
