### ISSUE TITLE
setuid missing from fping in  zabbix-server-mysql:ubuntu-latest

### ISSUE THREAD

**Issue by nafur** [zabbix/zabbix-docker#444]
There seems to be a solid history of problems with fping. I just hit this problem with the zabbix-server-mysql:ubuntu-latest docker image, leading to the `no output` error. Indeed both fping and fping6 lacked the setuid flag, though the config (zabbix_server.conf) stated they should have it. I fixed it locally with
>  docker exec zabbix-server chmod u+s /usr/bin/fping
>  docker exec zabbix-server chmod u+s /usr/bin/fping6

**Comment by nafur** [comment]
I just could observe this behaviour a few times and I suspect the following happens: during discovery zabbix also pings ips that are not reachable. The first line of the fping output is empty in this case and [this check](https://github.com/zabbix/zabbix/blob/1511a91b8684fc87c52f5cf4df86a0b9cc4a62cf/src/libs/zbxicmpping/icmpping.c#L256) then triggers the `fping failed: no output` message.

While I acknowledge that fping in some sense indeed fails, this message is pretty confusing to see in the log output in default configuration. Maybe change it to something like `host unreachable`, don't show it on log level 3 or change the logic to distinguish between "fping failed" and "host could not be reached"?

**Comment by dotneft** [comment]
Which image do you use?

**Comment by dotneft** [comment]
I can not confirm the issue:
` 187:20190411:185013.685 /tmp/zabbix_server_187.pinger
   187:20190411:185013.685     127.0.0.1
   187:20190411:185013.685     google.com
   187:20190411:185013.685 /usr/bin/fping -C3 2>&1 </tmp/zabbix_server_187.pinger;/usr/bin/fping6 -C3 2>&1 </tmp/zabbix_server_187.pinger;
   187:20190411:185013.692 read line [127.0.0.1  : [0], 84 bytes, 0.02 ms (0.02 avg, 0% loss)]
   187:20190411:185013.713 read line [google.com : [0], 84 bytes, 10.6 ms (10.6 avg, 0% loss)]
   187:20190411:185014.694 read line [127.0.0.1  : [1], 84 bytes, 0.07 ms (0.04 avg, 0% loss)]
   187:20190411:185014.716 read line [google.com : [1], 84 bytes, 10.6 ms (10.6 avg, 0% loss)]
   187:20190411:185015.695 read line [127.0.0.1  : [2], 84 bytes, 0.06 ms (0.05 avg, 0% loss)]
   187:20190411:185015.717 read line [google.com : [2], 84 bytes, 10.9 ms (10.7 avg, 0% loss)]
   187:20190411:185015.717 read line []
   187:20190411:185015.717 read line [127.0.0.1  : 0.02 0.07 0.06]
   187:20190411:185015.717 read line [google.com : 10.61 10.69 10.92]
   187:20190411:185015.723 read line [127.0.0.1  : [0], 84 bytes, 0.02 ms (0.02 avg, 0% loss)]
   187:20190411:185015.744 read line [google.com : [0], 84 bytes, 10.7 ms (10.7 avg, 0% loss)]
   187:20190411:185016.725 read line [127.0.0.1  : [1], 84 bytes, 0.19 ms (0.10 avg, 0% loss)]
   187:20190411:185016.746 read line [google.com : [1], 84 bytes, 10.9 ms (10.8 avg, 0% loss)]
   187:20190411:185017.726 read line [127.0.0.1  : [2], 84 bytes, 0.06 ms (0.09 avg, 0% loss)]
   187:20190411:185017.747 read line [google.com : [2], 84 bytes, 10.6 ms (10.7 avg, 0% loss)]
   187:20190411:185017.747 read line []
   187:20190411:185017.747 read line [127.0.0.1  : 0.02 0.19 0.06]
   187:20190411:185017.747 read line [google.com : 10.76 10.94 10.67]
   187:20190411:185017.748 End of process_ping()
`

Please reopen the issue with debug information
