### ISSUE TITLE
Database error Unable to select configuration.

### ISSUE THREAD

**Issue by OSXGroupFL** [zabbix/zabbix-docker#447]
<img width="645" alt="Screen Shot 2019-04-03 at 2 23 33 PM" src="https://user-images.githubusercontent.com/44268753/55503159-22893080-561c-11e9-86e7-5a39101b793a.png">
Installed the latest ubuntu-mysql 4.2 docker. I am able to connect to the msqldb using the default credentials and see all the tables from terminal but loading the page yields the error message in the title.

`root@bbdf8351f3d6:/var/log/mysql# mysql -h localhost -u zabbix -p -P 3306 -s <<< 'show grants;'
Enter password:
GRANT USAGE ON *.* TO 'zabbix'@'%'
GRANT ALL PRIVILEGES ON `zabbix`.* TO 'zabbix'@'%'`

Also there is no text editor installed in the image in case files need to be edited. (Vi would be nice)

**Comment by dotneft** [comment]
Which image did you use? MySQL on localhost is available only in appliance images.
