### ISSUE TITLE
zabbix-server-pgsql has not agent installed

### ISSUE THREAD

**Issue by heruan** [zabbix/zabbix-docker#448]
The `zabbix-server-pgsql` image has no agent installed on it, preventing the instance to monitor itself.

**Comment by heruan** [comment]
Note: I'm using the `ubuntu-4.2.0` tag.

**Comment by fpaternot** [comment]
I belive this might help: https://github.com/zabbix/zabbix-docker/issues/251

**Comment by heruan** [comment]
Not sure it helps, I'd like to monitor the Zabbix server instance itself and for that I guess it needs to have the agent available on the same image.

**Comment by fpaternot** [comment]
Not really. Zabbix server and proxy have internal items that don't need the agent.

I guess you are referring to monitor the server that the container of server is hosted in. In that case, you can have it installed on the server itself (package, sources..) or on a separate container that will expose port 10050.

**Comment by heruan** [comment]
I mean using e.g. the "OS Linux" template to monitor the Zabbix instance: it needs a Zabbix Agent installed on the same instance to monitor the instance itself (not the host).

**Comment by fpaternot** [comment]
You should not link that host to your server container, but link it to the server it's in.
