### ISSUE TITLE
Issues with pm.max_children

### ISSUE THREAD

**Issue by asdrub** [zabbix/zabbix-docker#451]
In my installation, frontend continuously crashes after this message: 
`[12-Apr-2019 18:55:47] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it`
[...]
`2019/04/12 19:01:27 [error] 45#45: *387 connect() to unix:/var/run/php/php7.2-fpm.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 10.0.5.6, server: zabbix, request: \"POST /zabbix.php?sid=4a27f77d919f00cf\u0026action=widget.problems.view HTTP/1.0\", upstream: \"fastcgi://unix:/var/run/php/php7.2-fpm.sock:\", host: \"openmonit.techmaster.com.br\", referrer: \"http://openmonit.techmaster.com.br/zabbix.php?action=dashboard.view\"`

Searching for solution I found: https://community.webcore.cloud/tutorials/how_to_solve_php_fpm_server_reached_max_children/

So at Zabbix nginix mysql frontend image:

```
# grep -nr "^pm" /etc/php/7.2/fpm/pool.d/www.conf
102:pm = dynamic
113:pm.max_children = 5
118:pm.start_servers = 2
123:pm.min_spare_servers = 1
128:pm.max_spare_servers = 3
```

A solution proposition could be a more powered config in this parameters, ou some docker environment variables to set this parameters at container startup time.

Thanks in advance.

**Comment by fpaternot** [comment]
Hello, wouldn't it be better if you scaled up your container?

Imagine how wild configuration would have to be to run in every deployment in the world.

I would advocate for it to be better documented for suggesting such cases and also for 'pm = static'. Containers are supposed to scale up and down easily, this is part of the point of using it in the first place.

**Comment by dotneft** [comment]
Exactly! You need to replicate containers instead of creating "monster" instances :-)
