### ISSUE TITLE
check_db_connect_mysql with external database

### ISSUE THREAD

**Issue by lionelpaquet** [zabbix/zabbix-docker#457]
Hi,

i'm trying to use docker image zabbix-appliance with an external database.

I'm using the following variables:
-e ZBX_SERVERNAME=ZabbixLPA -e DB_SERVER_HOST=192.168.200.10 -e MYSQL_USER=zabbix -e MYSQL_PASSWORD=zabbixpassword -e MYSQL_DATABASE=zabbix

Logs are:
** Deploying Zabbix appliance (nginx) with mysql database
** Preparing the system
** Preparing Zabbix server
********************
* DB_SERVER_HOST: 192.168.200.10
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
* DB_SERVER_ROOT_USER: root
* DB_SERVER_ROOT_PASS:
* DB_SERVER_ZBX_USER: zabbix
* DB_SERVER_ZBX_PASS: zabbixpassword
********************
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...

It seems that some code is missing in the check_db_connect_mysql function like:
 if [ "${USE_DB_ROOT_USER}" == "true" ]; then
        echo "* DB_SERVER_ROOT_USER: ${DB_SERVER_ROOT_USER}"
        echo "* DB_SERVER_ROOT_PASS: ${DB_SERVER_ROOT_PASS}"
    **else
        DB_SERVER_ROOT_USER=${DB_SERVER_ZBX_USER}
        DB_SERVER_ROOT_PASS=${DB_SERVER_ZBX_PASS}**
    fi

**Comment by TUISTERa** [comment]
Please update zabbix appliance to work with external database, or external dbdata volume. We can not update it now, because of integrated db

**Comment by dotneft** [comment]
Zabbix Appliance does not suggest to use external DB. Please use dedicated containers for such purpose.

**Comment by dotneft** [comment]
I agree that it should support db data volume. Will be added soon. Thank you!

**Comment by NFDWADM** [comment]
Are there any news? Or can we maybe build this ourselves?

**Comment by dotneft** [comment]
You can use volume /var/lib/mysql. It is already added, when we release new Zabbix versions, tags will be updated as well according latest changes.
