### ISSUE TITLE
Support container secrets

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#458]
It would be great if Zabbix could also support using container secrets. Currently the common implementation is to look at _FILE environment variables and if there are some use that provided file for reading the environment variable.

For example with POSTGRES_PASSWORD:
If the env variable POSTGRES_PASSWORD_FILE is set read the contents of the POSTGRES_PASSWORD_FILE into POSTGRES_PASSWORD environment variable (even overwriting already set POSTGRES_PASSWORD).

Also look at implementation in grafana for example: https://grafana.com/docs/installation/docker/#reading-secrets-from-files-support-for-docker-secrets and https://github.com/grafana/grafana-docker/pull/166
By the way - Postgres is already supporting this in their containers!

**Comment by rockaut** [comment]
Heja @dotneft I would like to add that over the weekend with PR. What would be better fitting in you opinion:
- implementing _FILE on just the handfull of variables ( like POSTGRES_PASSWORD )
- ... or checking all env variables for _FILE ( like grafana and all other projects does ) and excluding the handfull which already have the _FILE ending currently ( like ZBX_TLSKEY_FILE ) ?

**Comment by rockaut** [comment]
Side comment - grafana is doing it a little bit weird as they are using __FILE (double underscore FILE) so postgres is a better example: https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh

**Comment by dotneft** [comment]
Added
