### ISSUE TITLE
Unnecessary insistence on knowledge of database root password

### ISSUE THREAD

**Issue by ianmacs** [zabbix/zabbix-docker#461]
Dockerized zabbix components insist on knowing the mysql root password, otherwise they will not start. Tested images:

- zabbix/zabbix-web-nginx-mysql:latest
- zabbix/zabbix-server-mysql:latest

Even when the database is initialized so that the zabbix database and user are created, and the zabbix components are configured with the MYSQL_PASSWORD, still the logs of the server and frontend components contain
`*** Impossible to use MySQL server because 'root' password is not defined and it is not empty`

Even if the server should have need of the root password e.g. to alter permissions of the zabbix user, the web frontend surely has no such need.

**Comment by dotneft** [comment]
Did you specify MYSQL_USER? The error is is not present if MYSQL_USER is defined.

**Comment by dotneft** [comment]
With the following params web container works fine:
```
# env | grep ZBX
ZBX_SOURCES=https://git.zabbix.com/scm/zbx/zabbix.git
ZBX_VERSION=4.4
ZBX_DB_TYPE=mysql
ZBX_OPT_TYPE=apache
ZBX_SERVER_NAME=Composed installation
ZBX_TYPE=frontend
root@7cf4e5d6aa5a:/usr/share/zabbix# env | grep MYSQL
MYSQL_PASSWORD=zabbix
MYSQL_DATABASE=zabbix
MYSQL_USER=zabbix
```
