### ISSUE TITLE
Connection refused with vanilla zabbix-appliance image

### ISSUE THREAD

**Issue by kornerc** [zabbix/zabbix-docker#464]
I wanted to try out the zabbix-appliance as described in the [docs](https://www.zabbix.com/documentation/4.2/manual/installation/containers) by running this code:
```bash
$ docker run --name zabbix-appliance -t \
    -p 10051:10051 \
    -p 80:80 \
    -d zabbix/zabbix-appliance:latest
```
When I login, the ZBX icon under `Availability` in the menu `Configuration/Hosts` of the Zabbix server is red.
It displays the error `Get value from agent failed: cannot connect to to [[127.0.0.1]:10050]: [111] Connection refused`.
The same happens when I add a [new host](https://www.zabbix.com/documentation/4.2/manual/quickstart/host).

I tried this on an Ubuntu 18.04 VM and a regular Ubuntu 18.04 installation
```bash
$ uname -a
Linux clemens-VirtualBox 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

$ docker images
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
...
zabbix/zabbix-appliance         latest              4fe642587c18        4 weeks ago         459MB
...
```

**Comment by dotneft** [comment]
It is normal. The appliance does no have Zabbix agent onboard :-)

**Comment by kornerc** [comment]
Thank you for the clarification, I thought the agent is shipped with the appliance.

Maybe it would help Zabbix beginners (like me) to link to this [video](https://youtu.be/ScKlF0ICVYA) in the docs. At least it helped me a lot :-)
