### ISSUE TITLE
i cant access zabbix api

### ISSUE THREAD

**Issue by tuyula** [zabbix/zabbix-docker#466]
When i test api: it return:
       he requested URL /zabbix/api_jsonrpc.php was not found on this server.

**Comment by tuyula** [comment]
zabbix/zabbix-web-apache-mysql:latest
zabbix/zabbix-server-mysql:latest

**Comment by dotneft** [comment]
Please try without /zabbix/ subfolder.

**Comment by tuyula** [comment]
could you update it in zabbix web document

**Comment by dotneft** [comment]
Which one? This one: https://www.zabbix.com/documentation/4.0/manual/installation/containers must be updated, but maybe you are talking about some different place.

**Comment by tuyula** [comment]
Nop, 
![image](https://user-images.githubusercontent.com/32473341/58315272-d43a2600-7e43-11e9-8394-f6bc936a802b.png)

**Comment by tuyula** [comment]
![image](https://user-images.githubusercontent.com/32473341/58315366-05b2f180-7e44-11e9-8196-4d5677b4f9fd.png)

**Comment by dotneft** [comment]
It is just an example. It is not from real life.

**Comment by dotneft** [comment]
Users can use any domain name, any subdirectory :-) You are not limited to /zabbix/

**Comment by tuyula** [comment]
soga, thank u
