### ISSUE TITLE
Unable to manually build Zabbix Docker image (Ubuntu)

### ISSUE THREAD

**Issue by viewmithun** [zabbix/zabbix-docker#470]
Hi Team,

I am trying to build and run Zabbix Docker container manually. Below are the steps I am trying, 
* using git clone, I cloned the Zabbix-Docker 
* Then, changed my working directory to "**zabbix-docker/zabbix-appliance/ubuntu/**"
* Now, manually building the Zabbix Docker image by running "build.sh" script
**./build.sh**

Build script was unsuccessful with the below error message, 

+ make -j2 -s
Making all in src
Making all in zabbix_java
**java.io.FileNotFoundException: bin/zabbix-java-gateway-4.2.1.jar (No such file or directory)**
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at sun.tools.jar.Main.run(Main.java:195)
        at sun.tools.jar.Main.main(Main.java:1288)
**Makefile:531: recipe for target 'bin/zabbix-java-gateway-4.2.1.jar' failed**
make[2]: *** [bin/zabbix-java-gateway-4.2.1.jar] Error 1
make[1]: *** [all-recursive] Error 1
Makefile:488: recipe for target 'all-recursive' failed
Makefile:530: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
The command '/bin/sh -c set -eux &&     apt-get ${APT_FLAGS_COMMON} update &&     DEBIAN_FRONTEND=noninteractive apt-get ${APT_FLAGS_DEV} install             autoconf             automake             libc6-dev             make             openjdk-8-jdk             pkg-config             git             gcc &&     cd /tmp/ &&     git clone ${ZBX_SOURCES} --branch ${ZBX_VERSION} --depth 1 --single-branch zabbix-${ZBX_VERSION} &&     cd /tmp/zabbix-${ZBX_VERSION} &&     zabbix_revision=`git rev-parse --short HEAD` &&     sed -i "s/{ZABBIX_REVISION}/$zabbix_revision/g" include/version.h &&     sed -i "s/{ZABBIX_REVISION}/$zabbix_revision/g" src/zabbix_java/src/com/zabbix/gateway/GeneralInformation.java &&     ./bootstrap.sh &&     ./configure             --datadir=/usr/lib             --libdir=/usr/lib/zabbix             --sysconfdir=/etc/zabbix             --prefix=/usr             --enable-java             --silent &&     make -j"$(nproc)" -s &&     mkdir -p /usr/sbin/zabbix_java/ &&     cp -r src/zabbix_java/bin /usr/sbin/zabbix_java/ &&     cp -r src/zabbix_java/lib /usr/sbin/zabbix_java/ &&     rm -rf /usr/sbin/zabbix_java/lib/*.xml &&     cd /tmp/ &&     rm -rf /tmp/zabbix-${ZBX_VERSION}/ &&     DEBIAN_FRONTEND=noninteractive apt-get ${APT_FLAGS_COMMON} purge             autoconf             automake             libc6-dev             make             openjdk-8-jdk             pkg-config             git             gcc &&     apt-get ${APT_FLAGS_COMMON} autoremove &&     apt-get ${APT_FLAGS_COMMON} clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2

I also tried the below command, but I get the above error message
#docker build -t zabbix-docker:ubuntu-latest --build-arg VCS_REF=4.0.1 --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -f Dockerfile .

Request you guys to resolve this asap for me. Appreciate it. 

Thanks, 
Mithun

**Comment by dotneft** [comment]
It is known issue with old releases. Please change release version to 4.2.2 and try again :-)

**Comment by viewmithun** [comment]
Thanks a lot for your prompt response Alexey. 
In the Zabbix docker GitHub link (https://github.com/zabbix/zabbix-docker/commits/4.2), I can see till 4.2.1 Tag

Where can I get the 4.2.2 release version. Please help me with the link. 

Thanks again!

~Mithun
