### ISSUE TITLE
Missing docker images for Zabbix 4.2.2

### ISSUE THREAD

**Issue by ndusart** [zabbix/zabbix-docker#471]
Zabbix 4.2.2 has been released a few days ago and there is no docker images for this version yet.

**Comment by rockaut** [comment]
Sure they are ;-)
https://github.com/zabbix/zabbix-docker/releases/tag/4.2.2

**Comment by ndusart** [comment]
Well, looks at the times, it was not the case ;)

Well, do not know if it's a human reaction to this issue or a very spread cronjob detecting Zabbix releases but thanks wh(o|at)ever is behind this.

**Comment by ndusart** [comment]
Actually the docker image for `zabbix-appliance` failed when based on alpine.

**Comment by dotneft** [comment]
Fixed! Will be published soon

**Comment by ndusart** [comment]
Thanks :+1:
