### ISSUE TITLE
ldaps requires ca-certificates for ubuntu-4.0-latest

### ISSUE THREAD

**Issue by bjmi** [zabbix/zabbix-docker#472]
I recently switched from zabbix/zabbix-web-apache-mysql:alpine-4.0-latest to zabbix/zabbix-web-apache-mysql:ubuntu-4.0-latest cause https://hub.docker.com/r/zabbix/zabbix-web-apache-mysql#the-image-variants states that zabbix-web-apache-mysql:ubuntu-&lt;version&gt;

> This is the defacto image. [...]

Thanks to docker after switching to ubuntu base image I can't login anymore using ldap credentials.
Administration -> Authentication -> LDAP Settings -> Test shows
> Cannot bind to LDAP server.

After installing _ca-certificates_ package within container executing _Test_ button shows
> LDAP login successful

again.

**Comment by dotneft** [comment]
Thank you! Will be fixed soon!

**Comment by dotneft** [comment]
Fixed!
