### ISSUE TITLE
zabbix_get value different from zabbix server

### ISSUE THREAD

**Issue by tuyula** [zabbix/zabbix-docker#473]
i have item net.tcp.service[tcp,,6379]

when i user zabbix_get: it return 1
![image](https://user-images.githubusercontent.com/32473341/59756343-1b3cff00-92bc-11e9-8c75-628e5cf1cdb0.png)

But when i see zabbix-web: it return 0
![image](https://user-images.githubusercontent.com/32473341/59756410-3dcf1800-92bc-11e9-84c1-7eba97472197.png)

Zabbix Server Version: 
![image](https://user-images.githubusercontent.com/32473341/59756466-57705f80-92bc-11e9-8725-208f0214bbe1.png)

Zabbix Agent Version:
![image](https://user-images.githubusercontent.com/32473341/59756488-65be7b80-92bc-11e9-94ad-902afc22fe75.png)

**Comment by dotneft** [comment]
Not the issue with docker. Sorry!
