### ISSUE TITLE
XMPP (Jabber) notifications aren't sent

### ISSUE THREAD

**Issue by x-jokay** [zabbix/zabbix-docker#479]
When using `centos-4.0-latest` the XMPP notifications aren't sent.

Was working before on a dedicated server for `zabbix 3.0 LTS` using the same (our own) XMPP server ([prosody 0.11.2](https://prosody.im/)).

In the zabbix web UI it states:

```sh
received error [7]: [0] Success
```

Could be related to [ZBX-6220](https://support.zabbix.com/browse/ZBX-6220) and/or [ZBX-10002](https://support.zabbix.com/browse/ZBX-10002).

**Comment by x-jokay** [comment]
And is it possible the used lib for XMPP does support at max `TLSv1 with DES-CBC3-SHA`?

**Comment by x-jokay** [comment]
And may be related to this https://github.com/meduketto/iksemel/issues/48.

Did you ever consider to change the XMPP lib in the last almost 4 years? :wink:

**Comment by dotneft** [comment]
Actually iksemel is deprecated on many operating systems. So yes, we are thinking! Actually the issue is not related to docker images. What do you think?

**Comment by x-jokay** [comment]
Yes I think you should really think about changing the XMPP lib and push this request where necessary.

**Comment by dotneft** [comment]
Official bug tracker is the best place for that: https://support.zabbix.com ;-) You can vote!

**Comment by x-jokay** [comment]
What about including `sendxmpp` in the Docker image as suggested [here](https://support.zabbix.com/browse/ZBX-16132?focusedCommentId=342376&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-342376).
