### ISSUE TITLE
Include sendxmpp in Docker image

### ISSUE THREAD

**Issue by x-jokay** [zabbix/zabbix-docker#480]
As follow-up to https://github.com/zabbix/zabbix-docker/issues/479 I suggest to include `sendxmpp` in the Docker image as workaround as described [here](https://support.zabbix.com/browse/ZBX-16132?focusedCommentId=342376&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-342376).

**Comment by dotneft** [comment]
As it is command line utility, please, use Alert as script.
