### ISSUE TITLE
UserParameter.conf kubernetes

### ISSUE THREAD

**Issue by rmsmgaspar** [zabbix/zabbix-docker#481]
Hi,
I'm deploying zabbix in kubernetes and we have defined a UserParameter.conf, is there any way to pass it through the deployment, like a environment variable or something like that?
Thanks.

**Comment by fpaternot** [comment]
Yes, you can create a volume.

https://hub.docker.com/r/zabbix/zabbix-agent

```
Allowed volumes for the Zabbix agent container
/etc/zabbix/zabbix_agentd.d
The volume allows include *.conf files and extend Zabbix agent using UserParameter feature.
```

**Comment by rmsmgaspar** [comment]
thanks, it works.
