### ISSUE TITLE
Unable to get https url using "web.page.get"

### ISSUE THREAD

**Issue by imaoxian** [zabbix/zabbix-docker#483]
Unable to get https url using "web.page.get".
```
/var/lib/zabbix # zabbix_get -s agent -p 10050 -k "web.page.get[https://www.google.com]"
ZBX_NOTSUPPORTED: Unsupported scheme: https.
/var/lib/zabbix # zabbix_get -V
zabbix_get (Zabbix) 4.0.10
Revision cc25224 26 June 2019, compilation time: Jul 13 2019 06:27:38

Copyright (C) 2019 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 1.1.1b  26 Feb 2019
Running with OpenSSL 1.1.1b  26 Feb 2019
```
I use these docker images:
zabbix/zabbix-web-apache-mysql:alpine-4.0.10
zabbix/zabbix-server-mysql:alpine-4.0.10
zabbix/zabbix-agent:alpine-4.0.10

**Comment by oleksandrmeleshchuk-epm** [comment]
Can you please clarify how exactly it was fixed, I'm having same issue with the zabbix-agent.
```
C:\Program Files\Zabbix Agent>zabbix_get -V
zabbix_get (Zabbix) 4.4.5
Revision b93f5c4fc0 28 January 2020, compilation time: Jan 28 2020 15:33:42

Copyright (C) 2020 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 1.1.1  11 Sep 2018
Running with OpenSSL 1.1.1  11 Sep 2018
```
```
C:\Program Files\Zabbix Agent>zabbix_get -s localhost -k web.page.get[https://www.zabbix.com]
ZBX_NOTSUPPORTED: Unsupported scheme: https.
```

**Comment by dotneft** [comment]
how is your issue related to Docker? It looks like you have Windows without Docker instance.

**Comment by oleksandrmeleshchuk-epm** [comment]
it's not related with the Zabbix-docker, it's related with the zabbix-agent, but as soon as there is seprate brunch for the zabbix-agent - the only place which I've found with the same issue is this page, that is why I've posted my message here.

If there is any other URL where I can fin help it would be great if you can share it with me.

**Comment by dotneft** [comment]
Probably this one is the issue:
> SSL (HTTPS) is supported only if agent is compiled with cURL support. Otherwise the item will turn unsupported.
From: https://www.zabbix.com/documentation/current/manual/config/items/itemtypes/zabbix_agent

**Comment by oleksandrmeleshchuk-epm** [comment]
thx for the info, but as you can see from the zabbix_get -V output it's:
```
Compiled with OpenSSL 1.1.1  11 Sep 2018
Running with OpenSSL 1.1.1  11 Sep 2018
```

I'm right now checking rest of the zabbix-agent versions which are available for download from the:
https://www.zabbix.com/download_agents webpage and for now none of them is working, so I'm thinking that there might be additional packages missing in the OS....
Also I've just checked same web.page.get from the Linux based OS and it's working fine

**Comment by oleksandrmeleshchuk-epm** [comment]
also [here](https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/382403-web-page-regexp-on-windows-2012-r2-unsupported-scheme-https?view=thread) is thread on the forum related to this issue
