### ISSUE TITLE
zabbix-docker running on swarm mode.

### ISSUE THREAD

**Issue by flaporta** [zabbix/zabbix-docker#485]
When running zabbix-docker in swarm mode. Everything is working but I can't figure out how to get Zabbix-agent to work with Zabbix server. Zabbix agent works fine with other servers. I tried using using VIP from docker service inspect on zabbix-agent. Please provide some guidance.

Thank you.

**Comment by rockaut** [comment]
Which agent you mean. The one also deployed with the configuration files? Which config you're using?
