### ISSUE TITLE
PVC acting strange

### ISSUE THREAD

**Issue by MaxDiOrio** [zabbix/zabbix-docker#486]
I have no idea what's going on here, but this is the first time I've had this issue running a container.  Running in Rancher/K8S with NFS PVCs.

I created two PVC's and two mount points so I can persist data in these directories.
/usr/lib/zabbix
/var/lib/zabbix

As I've done tons of times in the past, I mount the NFS volume that's the source of the PVC's on my Mac, copy file into the PVC and like magic - they are in the container.  Except not this time.

I can create files in the root of the mount, /var/lib/zabbix, and they appear as it should in the container and in my nfs mount.

However if I do anything with a subdirectory, like /var/lib/zabbix/mibs, it never shows up on the other end.

I can delete the /var/lib/zabbix/mibs folder in the NFS mount, create a new one in /var/lib/zabbix and have it show up in the container.  I can drop the MIBs in this new folder and have it show up in the container.  But when the container restarts, the MIBs are gone within the container but still exist on the NFS mount.

Something strange is happening to subfolders, but I can't quite figure out what it is.  Any thoughts?

**Comment by dotneft** [comment]
/var/lib/zabbix/ is not in allowed list of volumes. Please carefully check documentation!

**Comment by MaxDiOrio** [comment]
So you have to create a mount point for each one of those directories independently?  That seems like an awful waste when you can simply mount the root.

**Comment by dotneft** [comment]
Yes, but it is security reasons, /var/lib/zabbix/ is home directory for zabbix user. So it is not a good idea to allow modify such "root" directory.
