### ISSUE TITLE
Add curl

### ISSUE THREAD

**Issue by MaxDiOrio** [zabbix/zabbix-docker#487]
Please add curl to the zabbix server images based on Alpine.

**Comment by dotneft** [comment]
why?

**Comment by MaxDiOrio** [comment]
In my case, Our MS Teams alert script uses curl to post data to the web hook.

**Comment by dotneft** [comment]
So probably it is better to make your own image based on official one?

**Comment by MaxDiOrio** [comment]
And then I every time you update the image, I have to rebuild it as well?  It was added to the ubuntu image, why not the Alpine image?

**Comment by dotneft** [comment]
`        iputils-ping \
            traceroute \
            fping \
            libcurl4 \
            libevent-2.1 \
            libiksemel3 \
            libmysqlclient20 \
            libopenipmi0 \
            libpcre3 \
            libsnmp30 \
            libssh2-1 \
            libssl1.1 \
            libxml2 \
            mysql-client \
            snmp-mibs-downloader \
            ca-certificates \
            unixodbc && \`
Nope!
`# docker exec -ti zabbix-docker_zabbix-server_1  /bin/bash
root@00788972f63a:/var/lib/zabbix# curl
bash: curl: command not found
`

**Comment by dotneft** [comment]
That is exactly the idea of base images. We provide image with small size without any additional features outside of Zabbix features, then (if you need) add anything you would like to have in images using our base images :-)

**Comment by MaxDiOrio** [comment]
OK - it was added to the appliance.  https://github.com/zabbix/zabbix-docker/pull/414/commits/efc6b94a09bd01e53dd242b81c5208449ad0309d

And you've already had several requests for curl to be built into the image.  Maybe you should document just how bare the image is, and provide people information on building their own from your base.

**Comment by dotneft** [comment]
Yes, appliances provide an example, like all in one. In this case it is reasonable to have such command.

Probably we need to document, but the idea of Docker base images is quite clear I think :-) 

But curl was added to all Web-based images just because of #329

**Comment by rockaut** [comment]
You don't have to build it if you let's say use docker hub and trigger
rebuild on new base image.

Alexey Pustovalov <notifications@github.com> schrieb am Fr., 19. Juli 2019,
18:05:

**Comment by dotneft** [comment]
Yes, another good way :-) Local repository or Docker Hub!

**Comment by tedkuban** [comment]
Hello! I need curl in ubuntu image for work of my alertscripts so I vote for inclusion of curl in all images ;-)

**Comment by SystemZ** [comment]
I've had similar problem while using alpine image.  
I ended up just using wget instead.

For example if you used something like this:
```bash
curl -d '{"content":"'"$MSG"'"}' -H 'Content-Type: application/json' $URL
```

You can use this instead:
```bash
wget -q --post-data '{"content":"'"$MSG"'"}' --header 'Content-Type: application/json' $URL
```
