### ISSUE TITLE
Parse error when activate ZBX_HISTORYSTORAGETYPE

### ISSUE THREAD

**Issue by melozo** [zabbix/zabbix-docker#489]
When we activate this option [1] shows an error[2], is a problem in the rendering, the ";" is added after the comment "#", so it is ignored.

I have tested it with the latest versions of zabbix-appliance (zabbix-appliance:ubuntu-4.2-latest and zabbix-appliance:alpine-4.2-latest).

[1]: ZBX_HISTORYSTORAGETYPES=uint,dbl,str,log,text # Available since 3.4.5
[2] Parse error: syntax error, unexpected ',' in /etc/zabbix/web/zabbix.conf.php on line 24

```sh
// Value types stored in Elasticsearch.
$HISTORY['types'] = uint,dbl,str,log,text # Available since 3.4.5;
```

Thanks for the great job!

**Comment by dotneft** [comment]
You need to provide different format as it shown in examples:
`ZBX_HISTORYSTORAGETYPES=['uint', 'dbl', 'str', 'text', 'log'] # Available since 3.4.5`
