### ISSUE TITLE
Database error: The frontend does not match Zabbix database.

### ISSUE THREAD

**Issue by chengkinhung** [zabbix/zabbix-docker#490]
Database error: The frontend does not match Zabbix database.

**Comment by chengkinhung** [comment]
Just follow the document: https://www.zabbix.com/documentation/4.0/zh/manual/installation/containers and try to install zabbix/zabbix-appliance:latest, the installation succeed, but web page encounter error: 
Database error: 
The frontend does not match Zabbix database.

**Comment by dotneft** [comment]
Hello! Which command did you use? Please show us logs

**Comment by chengkinhung** [comment]
Hi, this command: 
docker run --name zabbix-appliance -t \
      -p 10051:10051 \
      -p 80:80 \
      -d zabbix/zabbix-appliance:latest

Thanks.

**Comment by chengkinhung** [comment]
I can exec into docker container: docker exec -ti zabbix-appliance /bin/bash , and check mysql/nginx all running, database and tables exist ...

**Comment by dotneft** [comment]
show me please log information from container.

**Comment by chengkinhung** [comment]
hi, i am not sure which log you want ? could you please tell us the path of log ? Thanks.

**Comment by dotneft** [comment]
"docker logs" from container

**Comment by dotneft** [comment]
I found the problem with the latest image. It is described in https://support.zabbix.com/browse/ZBX-16465. Please try to use any image before 31 July 2019.

**Comment by chengkinhung** [comment]
Thanks.

**Comment by chengkinhung** [comment]
I finally see the zabbix web login page after following steps:
# docker exec -ti zabbix-appliance /bin/bash
# mysql
MariaDB [(none)]> SET GLOBAL innodb_strict_mode=OFF;
MariaDB [(none)]> SET SESSION innodb_strict_mode=OFF;
# cd /usr/share/doc/zabbix-server-mysql/
# mysqldump --quick --hex-blob --no-data zabbix > zabbix.sql
# cat zabbix.sql |grep DROP > zabbix.sql.droptb
#  mysql zabbix < zabbix.sql.droptb
# zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz > create.sql
# mysql zabbix < create.sql

However the login failed, i try the username: admin and password: zabbix

**Comment by chengkinhung** [comment]
The login succeed with username: Admin now:
 Username: Admin
 Password: zabbix
Thanks.

**Comment by MoxxNull** [comment]
Same problem with me.. @chengkinhung 's solution worked. Thanks

**Comment by antigenius0910** [comment]
somehow this solution will cause "Zabbix Server is not running". I followed @dotneft's suggestion and roll it back to ubuntu 4.2.1

**Comment by dotneft** [comment]
Is not Zabbix docker issue, it is Zabbix issue + appliances will be deprecated soon!
