### ISSUE TITLE
Timezone in container

### ISSUE THREAD

**Issue by s-weise** [zabbix/zabbix-docker#495]
When I deploy the container and use `PHP_TZ=Europe/Berlin` the timezone on the webfrontend is right. But when Zabbix send a message with `{EVENT.TIME}` the time seems to be UTC. I use the alpine zabbix container.

**Comment by dotneft** [comment]
It is known issue, Zabbix server sends all alerts and it does not use web-interface's timezone. You need to provide correct timezone to Zabbix server container.

**Comment by s-weise** [comment]
I installed tzdata and command date gives the right time in the cotainer.
