### ISSUE TITLE
Externalscripts need python - how to add this?

### ISSUE THREAD

**Issue by derwin12** [zabbix/zabbix-docker#497]
I am using a docker-compose file along with the image. Is the only option to go back to a Dockerfile and rebuild the image with python installed?

**Comment by dotneft** [comment]
Yes, please, build your own image based on our.

**Comment by rockaut** [comment]
As a tipp - if you have newer docker running try to use multi-image build! With that you can use from: zabbix/... and a second from: with official python images.

https://docs.docker.com/develop/develop-images/multistage-build/
