### ISSUE TITLE
How do I set static IP

### ISSUE THREAD

**Issue by nappy-d** [zabbix/zabbix-docker#499]
New to docker so please bear with me :)

I have installed the zabbix docker app on my Qnap and got it started.

How do I manually set the static IP?

I cannot find /etc/network/ interfaces file

I have tried using ifconfig

Any help would be appreciated :) 

![Screenshot_6](https://user-images.githubusercontent.com/47362805/66133094-1af31600-e5c4-11e9-8e8d-7f91dbfc33b7.png)

**Comment by rockaut** [comment]
Ok first I don't know how it run on Qnap at all.

How you started your containers? Which config did you use? Which Image.

You can't just start a container like an VM and then fiddle around in the running pod/container. Containers/Pods are immutable. If you stop it it will loose all your changes. You have to start a container with the according settings.

Try to go on YouTube and watch the Video on Zabbix with Containers on Zabbix own channel. And go through the official docs.

Also if you're just starting with docker as such I would go to katacoda.com. Great for trying out lot's of container magic without any invest. ( You can even start up a Zabbix Container Infra there with, for example the Ubuntu Playground). But I wouldn't use and abstracted implementation for learning basic docker and trying out new things.

**Comment by rockaut** [comment]
Also there are good starting points for docker newbies. Easy to find - google "easy docker" for example.

**Comment by rockaut** [comment]
But to just answer your question: you cant change the ip of the container that easy. But you even dont have to. The IP of the container is an internal ip "running" on the qnap box itself. You can access the running containers over the convigured ports with the ip of your qnap.

So lets say you start a webserver image which is configured to give you http on port 8080 and your qnap has an ip of 10.0.0.1 - just access over http://10.0.0.1:8080/

**Comment by rockaut** [comment]
https://www.zabbix.com/documentation/4.4/manual/installation/containers
