### ISSUE TITLE
a way to make zabbix-appliance (mysql) persistent?

### ISSUE THREAD

**Issue by thetuxinator** [zabbix/zabbix-docker#501]
Hi,

As i want some small monitoring server, to be used for some of my private machines (so i don't care about production ready and could be a good tester) i tried to make zabbix-appliance persistent using a volume for /var/lib/mysql , which did not work.

I just found this issue regarding mysql persistence, is this related? Has that change to be merged to zabbix-appliance? see https://github.com/zabbix/zabbix-docker/pull/500

Kind regards

Mike/tuxinator

**Comment by rockaut** [comment]
Just my opinion but I absolutely think the appliance should just disappear! Just use docker-compose which spins up all needed containers at once also on a single machine. Or even better spin up a single docker swarm node and use it there.

Ad your question - can you give use your command which you use to start the appliance?

**Comment by rockaut** [comment]
You're right but in case off the Zabbix appliance (there once we're a VM,
don't know if it still is) there was always the warning that it's just
meant for testing out Zabbix and never for production use. And now in the
age of containers an "appliance" is even more just for testing as it speaks
against all practice in containerization.

thetuxinator <notifications@github.com> schrieb am Fr., 11. Okt. 2019,
13:18:

**Comment by thetuxinator** [comment]
"And now in the age of containers an "appliance" is even more just for testing as it speaks
against all practice in containerization."
Sorry but, you are wrong here, or are all your containers only meant to be for testing?

There are 2 ways of using docker, first and most used and known is the usage by developers for their own testing and development. The second is to use it for production, to minimize amount of repeatable steps which you can automate. There is no real reason to use docker images only for testing, containerization is however often misunderstood and most people only use it for their own playground.

My goal was to get Zabbix up and running with minimal effort, so my plan was like one would do with either Docker or an appliance:

For Docker:
Method a)
1. search the right docker images for it
2. set the right variables and RTFM
3. mount the right paths to make it stateful
4. start it
5. test and configure it with the interface and let's go

Method b)
1. search the right docker images for it
2. set the right variables and RTFM
3. set mariadb/mysql server to another host or container
4. start it
5. test and configure it with the interface and let's go

in both scenarios one would have a stateful solution.

**Comment by rockaut** [comment]
Docker is of course not only for testing. The Zabbix appliances always
were. I meant appliances are not the logic of containers. Each service,
each purpose should be a container.

And what would be easier than docker-compose which handles all your config
with simple commands? Have a look at the templates. Choose the one you like
(psql, mysql) edit the file and docker-compose up -d ... or docker-compose
down.

Next step then would be a swarm cluster or if you go further use k8s/k3s.

I guarantee you, you will have more headache with the appliance image.
Especially if you want to segment it afterwards or even want to use it in
production.

That said. If you're willing to give more details on how you started the
appliance (read the commands) and the configuration used we might help
there too.


thetuxinator <notifications@github.com> schrieb am Fr., 11. Okt. 2019,
14:01:

**Comment by thetuxinator** [comment]
Found and using another solution, so closing this

**Comment by lfriends** [comment]
to those morons taking about the meanig on life on zabbix-applicance ... the question posed was about volumes for sql
