### ISSUE TITLE
Password visible in plain text at the start of container

### ISSUE THREAD

**Issue by SystemZ** [zabbix/zabbix-docker#504]
Currently there is some debug function at start of the zabbix server container that helps with troubleshooting but it doesn't censor password field.  
It could end up in logs if someone uses cluster-wide container logging.

Example:

```
** Deploying Zabbix server with mysql database
** Preparing the system
** Preparing Zabbix server
** Using MYSQL_USER variable from ENV
** Using MYSQL_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: mysql-server
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
* DB_SERVER_ZBX_USER: zabbix
* DB_SERVER_ZBX_PASS: SOMESECRETPASSWORD
********************
** Creating 'zabbix' user in MySQL database
...
...
...
```

**Comment by rockaut** [comment]
You may use the _file variables

Michał Frąckiewicz <notifications@github.com> schrieb am Do., 10. Okt.
2019, 12:55:

**Comment by SystemZ** [comment]
If I'm missing something then I think it would be wise to document it in each README related to docker image

**Comment by rockaut** [comment]
Sorry I'm currently only on mobile so just short answers. Also I don't know
why the documentation isn't there anymore. Will check that tomorrow.

I contributed that a while ago. Basically you can add _FILE to the DB
variables ( like MYSQL_PASSWORD_FILE ) write the user and password in file
and setting the path to the files for those variables - like -e
MYSQL_PASSWORD_FILE=./.dbpass

This also works with lube and swarm secrets where you use the secrets name
instead the path.

You can have a look at the docker-entrypoint.sh scripts in the containers.

Michał Frąckiewicz <notifications@github.com> schrieb am Do., 10. Okt.
2019, 20:52:

**Comment by rockaut** [comment]
Hmm... I was on vacation the so I might have just not updated the docs.
Sorry, will do over the weekend.

Michał Frąckiewicz <notifications@github.com> schrieb am Do., 10. Okt.
2019, 20:52:

**Comment by rockaut** [comment]
Also I checked back in the scripts and even with the file the passwords are
printed I think. Also find that not ideal. Will do that too over the
weekend.

Michał Frąckiewicz <notifications@github.com> schrieb am Do., 10. Okt.
2019, 20:52:

**Comment by dotneft** [comment]
Removed by default. Thank you!
