### ISSUE TITLE
Question on contributing

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#505]
Where should contribution be based on? Master branch i think would be the best. This should be mentioned in the "Contribution" sections of the readme's.

Also: how should we contribute code for the other branches? It's pretty repetitive to contribute to all docker-entrypoint.sh scripts in all distros in all branches. A way could be to favour only the latest and greatest and the LTS one's

**Comment by SanderSander** [comment]
I'm also wondering this, I created a PR for a small issue and it's was merged in the 3.0 branch. 
https://github.com/zabbix/zabbix-docker/commit/5e9a36326716f3f16ee25a47f3b057e2f0622dbd

I based my PR on 4.2 branch, but the changed were applied on the master branch. And it's a bit unclear when fixes get merged to the newer releases.

**Comment by dotneft** [comment]
It will be fixed as soon as possible! Currently 4.0, 4.2 and 4.4 are frozen for any changes!
