### ISSUE TITLE
Discontinue zabbix-appliance image(s) / containers

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#506]
and instead convince people to go with single node swarm oder k3s for example or just document docker-compose more detailed.

**Comment by rockaut** [comment]
Just have a look in some of the issues ( like #501 ). Most users stumbling upon Zabbix will tend to try the containers as it is easy to test new software. Then they see there's even an "appliance" image and will chose this one to go along with. But then they get stuck and will drop off completely or - maybe even worse - will go along with the single image and never doing it correct.

The appliance should have never been introduced to this repo. Harsh I know but it is just against all good practice of containerization. And in the end it causes more headache than goods. Just improve the Dokumentation on how to use docker-compose, swarm oder k3s with the templates and drop the appliance.

**Comment by dotneft** [comment]
I agree with u, appliance images must be considered as deprecated. I will investigate, how it is better to do :-)

**Comment by Chrislevi** [comment]
Any news about this? I've tried to convert the repo compose examples to support Swarm, found some deadlocks clearly was time consuming with not much success, decided to try out the appliance just to expedite the deployment in order to test out zabbix.

**Comment by dentonmwood** [comment]
Would also love to hear if this is going forward. I spent a few weeks figuring out the compose setup before switching to appliance, and I need to know if I need to switch back to persist our setup.

**Comment by rockaut** [comment]
IMO I wouldn't use the appliance any longer. If you absolutely need an appliance I would more go with the VM Appliance (https://www.zabbix.com/download_appliance).

@Chrislevi what do you mean with deadlocks? Also wouldn't go with Swarm as it seams to be more or less dead. Give k3s a try.

That all said I also think there should be a better way off quickly deploying the different variants to Kubernetes. Now as helm 3 doesn't require tiller anymore, maybe we could get an official helm chart? I think most people are confused by the amount of docker_compose* files and that they still need to customize these. So maybe also a reorg for those might help.

**Comment by cccdemon** [comment]
such a bad idea. The appliance is good for testing and setting up an monitoring as fast as possible, without having an k8 environment up and running. 

Please continue and provide an k8-helm chart too.

**Comment by rockaut** [comment]
Why is it a bad idea? It causes lots of troubles for folks which aren't
that used to containers. You can have a complete Zabbix environment on one
box with one docker-compose without any k8s.

Torsten Ennenbach <notifications@github.com> schrieb am Fr., 10. Jan. 2020,
10:51:

**Comment by ndusart** [comment]
How do you consider people that rely on your appliance image ?

I mean, there is no communication whatsoever about that. This image is already behind latest stable version. I don't see how this could be stated as "deprecated" either. You just dropped that.
The issue is not even closed and yet, the appliance image is not built anymore...

I'm not arguing about the good reasons you want to drop that image. I am a bit concerned about the fact that you can drop support for something so fast. I don't see any reason why docker compose would not be dropped as well in any future where other configuration methods will appear and fit you more...

**Comment by dotneft** [comment]
You can easily migrate to standard docker images. We made appliance image for testing purposes, but some people started to use it for production environments. It is one of the most important reason, why it is not supported anymore. Regarding compose files, we will support most of features for Docker images according best practises from Docker and 3rd party tools.

Appliance is very difficult to manage, you can not predict / check if something inside will be crashed or corrupted, in this case container will be stable, running.

**Comment by mbirth** [comment]
So is it not supported any more or will there be an update to 5.x some day? If it's not supported, a big warning on the Docker Hub page would be nice.

**Comment by dotneft** [comment]
We do not have any plans for appliance. Warning will be published soon.

**Comment by dotneft** [comment]
Finally removed! https://support.zabbix.com/browse/ZBX-18062
