### ISSUE TITLE
Missing ZBX_STARTLLDPROCESSORS

### ISSUE THREAD

**Issue by CuBiC3D** [zabbix/zabbix-docker#507]
Currently there is no way to set the StartLLDProcessors server option from 4.2 on docker env.

Would require additional config entry in `docker-entrypoint.sh`:
```
update_config_var $ZBX_CONFIG "StartLLDProcessors" "${ZBX_STARTLLDPROCESSORS}"
```

**Comment by dotneft** [comment]
Added! Thank you!
