### ISSUE TITLE
Allow to add custom nginx configurations

### ISSUE THREAD

**Issue by hatifnatt** [zabbix/zabbix-docker#511]
Issue
-------
Currently files matching mask `/etc/nginx/conf.d/*.conf` are removed in `docker-entrypoint.sh`
https://github.com/zabbix/zabbix-docker/blob/f96e167a80d39ae460192d8846f891df6017871c/web-nginx-pgsql/ubuntu/docker-entrypoint.sh#L634

This prevent adding drop-in configs to nginx. I.e. my `zabbix-web-nginx-pgsql` container is running behind reverse proxy and I want to enable `realip` with something like

Dockerfile
```
FROM zabbix/zabbix-web-nginx-pgsql:ubuntu-4.4-latest
COPY realip.conf /etc/nginx/conf.d/
```

realip.conf
```
set_real_ip_from 127.0.0.0/8;
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 192.168.0.0/16;
set_real_ip_from 172.16.0.0/12;
```
But my config is removed during container startup.

Can you consider replacing 
```
rm -f $NGINX_CONFD_DIR/*.conf 
```
for example with
```
rm -f $NGINX_CONFD_DIR/default.conf 
```

Another approach - add at the bottom of current `nginx.conf` something like 
```
    include /etc/nginx/custom.d/*.conf;
```
That will allow to add a volume with custom `nginx` configuration if required.

Current dirty solution
--------------------------
```
COPY realip.conf /etc/nginx/
RUN sed -i'' -e '/include \/etc\/nginx\/conf.d\/\*.conf;/a\    include /etc/nginx/realip.conf;' /etc/nginx/nginx.conf
```
I will be glad to hear if there is already another solution that I missed.

**Comment by dotneft** [comment]
Fixed! Thank you! 

Now default configuration are removed on image building stage.
