### ISSUE TITLE
Cannot build specific version; build always produces 4.4

### ISSUE THREAD

**Issue by cdhowie** [zabbix/zabbix-docker#513]
I am trying to build the agent, version 4.0.13.  While the `build.sh` script accepts this version number, 4.4.0 gets built instead:

```
$ sudo ./build.sh 4.0.13
[build output]
Successfully built bd1b63298f42
Successfully tagged zabbix-agent:alpine-4.0.13
$ sudo docker run --rm --entrypoint zabbix_agentd zabbix-agent:alpine-4.0.13 --version
zabbix_agentd (daemon) (Zabbix) 4.4.0
Revision cfac660 7 October 2019, compilation time: Oct 27 2019 23:57:50

Copyright (C) 2019 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit (http://www.openssl.org/).

Compiled with OpenSSL 1.1.1d  10 Sep 2019
Running with OpenSSL 1.1.1d  10 Sep 2019
```

It's not clear if this is expected, or if there is some other way to build alternate versions.

**Comment by dotneft** [comment]
The script does not work like that. Please check it

**Comment by cdhowie** [comment]
Yes, I have opened it and it's not clear _at all_ how to build older versions. Presumably this is possible, as the images on Docker Hub are getting updated.

Is there any documentation on how to build prior versions? I have not been able to find any, and the script accepting a version argument _without it actually doing what would be obvious_ is confusing and misleading.

`build.sh` does set `VCS_REF` but the Dockerfile seems to completely ignore this environment variable, so I'm not sure what the point of passing `build.sh` a version other than `latest` even is.

**Comment by dotneft** [comment]
Exactly. You need to checkout the correct branch, then manually change information about version in Dockerfile or use update_ver.sh update for all images.

**Comment by cdhowie** [comment]
Ah, thanks. Is `update_ver.sh` not in all branches?

```
$ git describe --all
tags/4.0.13
$ find -name update_ver.sh
$
```

**Comment by dotneft** [comment]
Ahh... sorry ( It is not yet available. Please do it manually. Sorry! (

**Comment by dotneft** [comment]
why do you need to rebuild 4.0.13? )

**Comment by cdhowie** [comment]
I am building for armhf: https://hub.docker.com/r/cdhowie/zabbix-agent-alpine-4.0.13-armhf

**Comment by cdhowie** [comment]
It wound up not working out, though... even with `--privileged`, there's lots of information that isn't available when running inside of a container, such as system-wide process count and network interface transfer rates.
