### ISSUE TITLE
Languages missing on frontend image zabbix-web-nginx-mysql:centos-3.4.12

### ISSUE THREAD

**Issue by joseeduardoperes** [zabbix/zabbix-docker#520]
The languages are missing on the frontend of docker image: zabbix-web-nginx-mysql:centos-3.4.12
Is there a fix for this?
![Screen Shot 2019-11-20 at 20 52 22](https://user-images.githubusercontent.com/22481852/69288580-ce49b580-0bd8-11ea-8a99-42a6250831e2.png)

**Comment by dotneft** [comment]
Hello! 3.4 version is not supported anymore. Do you face the same issue in 4.0?
