### ISSUE TITLE
zabbix-docker on Swarm

### ISSUE THREAD

**Issue by Chrislevi** [zabbix/zabbix-docker#521]
Is there any reliable configuration base that I can count on to be able to fully deploy the stack in Docker Swarm?

**Comment by rockaut** [comment]
Well... Basically you can take any docker-compose config with slight
changes.

But I wouldn't use swarm too extensive and not in production anymore. For
testing you might be safe but won't find a lot of help on the webs. I
advise to use k3s (it's a small kubernetes).

Chris Levi <notifications@github.com> schrieb am Do., 21. Nov. 2019, 12:33:

**Comment by Chrislevi** [comment]
We're planning on moving to k8s, but for now out production runs on Swarm

**Comment by joosequezada** [comment]
Currently, I'm working in a presentation based on Zabbix on Swarm. @Chrislevi you can you to my repo and see it (https://github.com/joosequezada/Zabbix-Docker-Swarm). You can use it as reference. After my speech at OpenSaturday Conf I'll post my presentation. However, I share @rockaut suggestion.
