### ISSUE TITLE
missing nmap

### ISSUE THREAD

**Issue by mmaridev** [zabbix/zabbix-docker#522]
In zabbix-server-psql , the "nmap" command is missing and it can't be installed via apk add since zabbix user is not root

**Comment by ronnicek** [comment]
You need to create your own image which will have nmap included :)

Example Dockerfile:
```
FROM zabbix/zabbix-server-pgsql:ubuntu-4.0-latest

RUN apt update && apt install -y curl ca-certificates openssl bc python-requests && rm -rf /var/lib/apt/lists/*
```

**Comment by rockaut** [comment]
My advise would always be to let the server be mostly standard and just
modify a proxy image. Even if you're just in a small configuration. It's
easier to spread out later and somewhat more compliant to standards.

Jindřiška <notifications@github.com> schrieb am Fr., 22. Nov. 2019, 13:12:

**Comment by ronnicek** [comment]
It was example how I have the server image extended, I am not saying he should do it in server :)

**Comment by rockaut** [comment]
No offense! It was a good example.

Jindřiška <notifications@github.com> schrieb am Fr., 22. Nov. 2019, 14:54:

**Comment by ronnicek** [comment]
No problem, I didnt took that :) Anyway.. I think these questions are here quite often.. @dotneft could you update README with that somehow maybe? :)

**Comment by mmaridev** [comment]
Compiling an image makes sense to me (and I already did it) but since nmap
is used by zabbix to detect OSs wouldn't be great having it compiled in the
standard image? Otherwise you'll always get an error when trying to detect
the OS.

Il Ven 22 Nov 2019, 14:58 Jindřiška <notifications@github.com> ha scritto:

**Comment by D3vl0per** [comment]
> In zabbix-server-psql , the "nmap" command is missing and it can't be installed via apk add since zabbix user is not root

Try to use older images(for example 4.4.0), because the newest image include zabbix user.
Or add USER root before apk install and after set USER zabbix back.
I know, the second method isn't pretty.

[Zabbix user added commit](https://github.com/zabbix/zabbix-docker/blob/4.4.1/server-pgsql/alpine/Dockerfile)

**Comment by mmaridev** [comment]
Using 4.0 is fine but to me would be great to have nmap and sudo packed by default... are 4398K at the end of the day...

**Comment by dotneft** [comment]
Please create your own image based on official images and include everything what you want to see inside containers :-)
