### ISSUE TITLE
zabbix error

### ISSUE THREAD

**Issue by xulinbao** [zabbix/zabbix-docker#524]
`[root@s133953 yum.repos.d]# uname -a
Linux s133953.wholesaleinternet.net 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@s133953 yum.repos.d]# cat /etc/redhat-release
CentOS Linux release 8.0.1905 (Core)`

`[root@s133953 yum.repos.d]# php -v
PHP 7.4.0 (cli) (built: Nov 26 2019 20:13:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0, Copyright (c), by Zend Technologies`

`[root@s133953 yum.repos.d]# mysql -V
mysql  Ver 15.1 Distrib 10.3.11-MariaDB, for Linux (x86_64) using readline 5.1`

`[root@s133953 yum.repos.d]# httpd -v
Server version: Apache/2.4.37 (centos)
Server built:   Oct  7 2019 21:42:02`

[/zabbix/zabbix.php?action=userprofile.edit](url)

You are not able to choose some of the languages, because locales for them are not installed on the web server.

`Trying to access array offset on value of type null [zabbix.php:21 → require_once() → ZBase->run() → ZBase->processRequest() → CView->getOutput() → include() → local_generateHeader() → zbx_construct_menu() in include/menu.inc.php:420]`
`Trying to access array offset on value of type null [zabbix.php:21 → require_once() → ZBase->run() → ZBase->processRequest() → CView->getOutput() → include() → local_generateHeader() in app/views/layout.htmlpage.php:86]`

[/zabbix/zabbix.php?action=web.view&ddreset=1](url)

`Trying to access array offset on value of type null [zabbix.php:21 → require_once() → ZBase->run() → ZBase->processRequest() → CController->run() → CControllerWebView->doAction() → CPageFilter->__construct() → CPageFilter->_getProfiles() in include/classes/pagefilter/CPageFilter.php:279]`

[/zabbix/charts.php?ddreset=1](url)
`Trying to access array offset on value of type bool [charts.php:80 → CPageFilter->__construct() → CPageFilter->_initGraphs() → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CGraph->get() → CMacrosResolverHelper::resolveGraphNameByIds() in include/classes/macros/CMacrosResolverHelper.php:453]`

**Comment by dotneft** [comment]
what image do you use?
