### ISSUE TITLE
Zabbix agent error

### ISSUE THREAD

**Issue by manne45** [zabbix/zabbix-docker#525]
I just did a git pull of entire repo and use docker-compose to set up the docker-compose_v3_ubuntu_mysql_latest.yaml  file , the server looks fine, but the agent is not working, here the logs for the container:
########################################################
** Starting Zabbix agent
Starting Zabbix Agent [17c72357d5f8]. Zabbix 4.4.3 (revision 6cad6f8).
Press Ctrl+C to exit.

  5121:20191201:220123.076 Starting Zabbix Agent [17c72357d5f8]. Zabbix 4.4.3 (revision 6cad6f8).
  5121:20191201:220123.076 **** Enabled features ****
  5121:20191201:220123.076 IPv6 support:          YES
  5121:20191201:220123.076 TLS support:           YES
  5121:20191201:220123.076 **************************
  5121:20191201:220123.076 using configuration file: /etc/zabbix/zabbix_agentd.conf
  5121:20191201:220123.097 agent #0 started [main process]
  5144:20191201:220123.098 agent #2 started [listener #1]
  5143:20191201:220123.098 agent #1 started [collector]
  5145:20191201:220123.100 agent #3 started [listener #2]
  5146:20191201:220123.109 agent #4 started [listener #3]
  5147:20191201:220123.110 agent #5 started [active checks #1]
  5147:20191201:220123.120 active check configuration update from [zabbix-server:10051] started to fail (cannot connect to [[zabbix-server]:10051]: [111] Connection refused)

**Comment by sazad44** [comment]
is there any guidance on setting up non-containerized agents with a containerized application? I can't get success or errors to show on confgured hosts in my Zabbix configuration.

**Comment by rockaut** [comment]
There isn't anything special really. If you don't get access on active
agents it's most likely because your server isn't available from outside.
Do you use the correct IP/hostname? Is the server container on a network
which is available to non-container resources?

Samie Azad <notifications@github.com> schrieb am Fr., 10. Jan. 2020, 20:58:

**Comment by sazad44** [comment]
I've tested connection between the servers
I've made sure I'm forwarding my ports correctly
there doesn't seem to be any reason why they can't communicate
and it's odd I don't get any errors either
