### ISSUE TITLE
Docker image zabbix / zabbix-appliance modify /etc/zabbix/zabbix_server.conf configuration will be overwritten

### ISSUE THREAD

**Issue by k649781645** [zabbix/zabbix-docker#527]
Use the mirror docker pull zabbix / zabbix-appliance running container on the Dcoker hub, enter the container and modify /etc/zabbix/zabbix_server.conf to add VMWare monitoring related parameters. Why does the parameter modification not take effect here? It will be reset to the default configuration, making it impossible to enable VMWare related monitoring.

**Comment by dotneft** [comment]
Please use environment variables instead of manual change.
