### ISSUE TITLE
Raw data collection only every 30 min?

### ISSUE THREAD

**Issue by drexlma** [zabbix/zabbix-docker#528]
I installed the standard Docker container. Mysql and Nginx template activated. It only gets the RAW information every 30 minutes.

Zabbix-Server: 8 Core, Debian 10
Hosts: 2 (Zabbix + 1 Server)
![chart_mysql](https://user-images.githubusercontent.com/7121202/70860481-8c373980-1f22-11ea-8179-c7f285164684.jpg)

**Comment by rockaut** [comment]
Is it active or passive agent?
Are there any errors in the logs?

Daniel Drexlmaier <notifications@github.com> schrieb am So., 15. Dez. 2019,
10:07:

**Comment by drexlma** [comment]
no logs in server error log

it's passive

**Comment by rockaut** [comment]
Client logs are also "empty"?

With passive agents you may always use the check now function with the
items to check if there are troubles.

It may also be that the simply are too far away that they connect in the
graph. I don't know the exact "distance". maybe you can lower the intervals
for testing?

Daniel Drexlmaier <notifications@github.com> schrieb am So., 15. Dez. 2019,
10:33:

**Comment by drexlma** [comment]
**Ok I have to test the next week extensively.** I restart the Zabbix server and the whole thing works for exactly one hour. That he checks every minute. After this hour ... he does the check every 30 - 40 minutes.

**Comment by rockaut** [comment]
Maybe you should elevate the logs and look at the debug messages. Also have
a look at the queues.

Daniel Drexlmaier <notifications@github.com> schrieb am So., 15. Dez. 2019,
14:36:
