### ISSUE TITLE
ZBX_STATSALLOWEDIP variable not included in alpine's entrypoint

### ISSUE THREAD

**Issue by aruizpardo** [zabbix/zabbix-docker#529]
In the mysql-server dockers of alpine, the file "docker-entrypoint.sh" does not include the environment variable "ZBX_STATSALLOWEDIP", so it does not put it in the configuration file and does not allow monitoring the server externally.

In the mysql-server dockers of centos is [here](https://github.com/zabbix/zabbix-docker/blob/4.4/server-mysql/centos/docker-entrypoint.sh#L772)

**Comment by dotneft** [comment]
Fixed. Thank you!
