### ISSUE TITLE
Error while trying to restore db from old backup!

### ISSUE THREAD

**Issue by anandzy** [zabbix/zabbix-docker#530]
root@box:~/zabbix-docker# docker exec -i zabbix-docker_mysql-server_1 sh -c 'bunzip2 -dc /backups/zabbix_db_dump_2019-12-18-14.35.16.sql.bz2 | mysql -uroot -p --password=root_pwd zabbix'
sh: 1: bunzip2: not found
mysql: [Warning] Using a password on the command line interface can be insecure.

**Comment by dotneft** [comment]
It is not related to Zabbix at all. Your MySQL container does not have bunzip2.
