### ISSUE TITLE
zabbix agent error

### ISSUE THREAD

**Issue by happinesslijian** [zabbix/zabbix-docker#533]
I also encountered a similar problem. I run zabbix and agent in kubernetes. Their status is running. When I check the agent pod log, `20191227: 085743.351 no active checks on server [zabbixserver: 10051]: host [zabbixagent -jxr84] not found` 
![微信截图_20191227175158.png](https://i.loli.net/2019/12/27/bgtXYENWUIfQ14w.png)
ends up causing Zabbix not to run properly
![微信截图_20191227175313.png](https://i.loli.net/2019/12/27/4Jkd8zQPXSrFZeK.png)
Here is my configuration file, you can download or clone it for verification
`https://github.com/happinesslijian/k8s-application/blob/master/zabbix.tar.gz`
I need help thanks

**Comment by dotneft** [comment]
it is related to Zabbix configuration, not Kubernetes, not Docker. You need to create "zabbixagent-jxr84" host or specify correct DNS (probably "zabbix-agent") for existing one host.
