### ISSUE TITLE
How can I map a mysql database storage volume for docker-appliance?

### ISSUE THREAD

**Issue by sshxmz** [zabbix/zabbix-docker#535]
According to the document, it seems there is no volume entry for mysql database.?https://hub.docker.com/r/zabbix/zabbix-appliance/

**Comment by kkrkarthik** [comment]
@sshxmz you can mount the volume to the docker container or map the folder mount to container 

Here is one example from compose file:
    volumes:
       - mysql_data:/var/lib/mysql:rw
or
use -v flag in docker run to mount the volume 

-mysql_data is the docker volume 
-/var/lib/mysql is the container location
