### ISSUE TITLE
Zabbix API 

### ISSUE THREAD

**Issue by anandzy** [zabbix/zabbix-docker#537]
I'm using the Zabbix-docker  &  docker-compose_v3_ubuntu_mysql_latest.yaml file to provision the whole stack and then the grafana6.0 using grafana_on_docker with grafana6+ version. I'm trying to integrate using alexanderzobnin-zabbix-app the issue comes even I follow the official documentation of Zabbix.

`adtoox@zabbix4_on_docker-compose:~$ curl -i -X POST -H 'Content-Type: application/json-rpc' -d '{"params": {"password": "zabbix", "user": "Admin"}, "jsonrpc": "2.0", "method": "user.authenticate","auth": "", "id": 0}' http://localhost/zabbix/api_jsonrpc.php
HTTP/1.1 404 Not Found
Date: Tue, 07 Jan 2020 15:52:02 GMT
Server: Apache/2.4.29 (Ubuntu)
Content-Length: 271
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at localhost Port 80</address>
</body></html>`
![_thumb_94886](https://user-images.githubusercontent.com/26261048/71909568-98ed2d00-3170-11ea-8b5a-422a0094e96b.png)
![_thumb_94886](https://user-images.githubusercontent.com/26261048/71909606-a99da300-3170-11ea-840a-4d7e380b73be.png)

**Comment by rockaut** [comment]
Have you added the network to the grafana service?

Live long and prosper 🖖

Markus

**Comment by Superjajaman75** [comment]
Hey,
I have just integrated Zabbix into Grafana, and you should not use the API key, but just enter your identifiers in login/password field for first configuration (i.e. Admin/zabbix).

Otherwise for your answer you must not put /zabbix in the url ==> http://localhost/api_jsonrpc.php

Hope this help

Ben

**Comment by rockaut** [comment]
Good point @Superjajaman75 I've overlooked that. I the docker-compose files the url is without /zabbix/ ... unless you modified that.
