### ISSUE TITLE
Change database password

### ISSUE THREAD

**Issue by lukas-pl** [zabbix/zabbix-docker#542]
Hi, How do I change database password? I'm using docker-compose. Can I change the .env file or .MYSQL_ROOT_PASSWORD file?

**Comment by kkrkarthik** [comment]
Consider two scenarios:

- 1. New zabbix Docker Install, change the password in both files
          .MYSQL_PASSWORD (Contains zabbix DB password)
          .MYSQL_ROOT_PASSWORD (Contains root DB password) 
- 2. Existing DB Password change, login to mysql as root and change password for root/zabbix with ALTER USER command. Once its done you can follow the Step:1
