### ISSUE TITLE
Docker-compose files for PostgreSQL also start unrelated services

### ISSUE THREAD

**Issue by maxhq** [zabbix/zabbix-docker#544]
All `docker-compose_v3_*_pgsql_*.yaml` files also contain the MySQL and SQLite related services
- *zabbix-proxy-mysql*
- *zabbix-proxy-sqlite3*
- *mysql-server*
- *db_data_mysql*

**Comment by kkrkarthik** [comment]
Agree, zabbix-proxy-sqlite3 is understandable because its self contained, doesn't require mysql

**Comment by dotneft** [comment]
Compose files require manual changes. They provide redundant services to show possible ways. If you do not need them, just remove redundant services.
