### ISSUE TITLE
Zabbix v4.4.5 release

### ISSUE THREAD

**Issue by edouardkleinhans** [zabbix/zabbix-docker#550]
Build failed for this image. 

Can you fix this ?

**Comment by dotneft** [comment]
What exactly failed? Which image, which OS?

**Comment by edouardkleinhans** [comment]
sorry, i forgot to mention, docker alpine image for agent2

ci/dockercloud (/agent2/alpine)

**Comment by dotneft** [comment]
Fixed! Thank you!
