### ISSUE TITLE
Hello, please ask a question about the version upgrade

### ISSUE THREAD

**Issue by cdy668** [zabbix/zabbix-docker#552]
zabbix/zabbix-server-mysql:4.2.5 upgrade zabbix/zabbix-server-mysql:4.4.5
zabbix/zabbix-web-nginx-mysql:4.2.5 upgradezabbix/zabbix-web-nginx-mysql:4.4.5

I use docker composer to replace the old version of images with the latest version，What should I do to keep the old data and have the latest features。
Can I use the latest container image to build ZABBIX server and point MySQL data volume to the original directory?
For example：
version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:centos-latest
  .....................
 mysql-server:
  image: mysql5.7:latest
  restart: always
  command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
  volumes:
   - ./data/zabbix/mysql:/var/lib/mysql:rw
  ....................

When I backed up the historical data, I did the following
docker-compose -f docker-compose.yaml stop
docker-compose -f docker-compose.yaml up -d --build

But in this way, although my historical data can be preserved in the ZABBIX web interface, and the version numbers of the query ZABBIX server and ZABBIX web have been upgraded to the latest version, I have lost some data only available in 4.4.5, such as template data

Can you direct me, thank you

**Comment by dotneft** [comment]
No problem, you can use new images. Just point them to the old DB. Zabbix server will automatically upgrade DB to latest version.
