### ISSUE TITLE
Update docker hub

### ISSUE THREAD

**Issue by joaostorrer** [zabbix/zabbix-docker#554]
When I pull zabbix images from docker hub the container shows the error 'standard_init_linux.go:211: exec user process caused "exec format error"', but when I build from github source it works without errors.
I've tried all the different images (alpine, ubuntu and centos).

I'm using Raspbian Buster (armv71 architeture).

**Comment by jangaraj** [comment]
Zabbix images support only `linux/amd64` architecture. You really can't run `amd64` binary on `arm71` machine.
![image](https://user-images.githubusercontent.com/1182932/74722002-7f8fd400-5238-11ea-8aa1-d4824b681dc0.png)

**Comment by joaostorrer** [comment]
Shouldn't the image on the docker hub be the same as the built from github source ?
Because when i build from Dockerfile available here in github it doesn't give me any error.

**Comment by dotneft** [comment]
it depends on system arch you built the image.
