### ISSUE TITLE
wrong value for ZBX_EXPORTFILESIZE 

### ISSUE THREAD

**Issue by loopping** [zabbix/zabbix-docker#555]
I'm running latest alpine version.
I would like to use "real time export" and as I have read here:
https://github.com/zabbix/zabbix-docker/blob/90d8c209fc5f40f8d23d8447325d4c5787acbed9/server-pgsql/alpine/docker-entrypoint.sh#L386
I have added this at the end of file .env_srv:
`ZBX_EXPORTFILESIZE=1M`

But I have this error in zabbix server logs:
`zabbix_server [6]: wrong value of "ExportFileSize" in config file "/etc/zabbix/zabbix_server.conf", line 179`

**Comment by dotneft** [comment]
Thank you very much! The issue is fixed. Please wait when images will be rebuilt!
