### ISSUE TITLE
How to use python script  in  alertscripts

### ISSUE THREAD

**Issue by Duzcinfo** [zabbix/zabbix-docker#557]
if I want to used dingdingtalk alter,but it depends on python.but I don't want to built image,Is there any other solution？

**Comment by fangtianhj** [comment]
U can use shell script with dingtalk

**Comment by Duzcinfo** [comment]
I just put on dir "/usr/lib/zabbix/alertscripts" in zabbix-serever-mysql container.
Execution this python script，but it's wrong .
-----------detail------
/usr/lib/zabbix/alertscripts/dingding-alter.py: line 6:
@Author : duzc
@File: dingding-alter.py
@Time: 2020/3/5 15:03
: not found
/usr/lib/zabbix/alertscripts/dingding-alter.py: line 7: : not found
/usr/lib/zabbix/alertscripts/dingding-alter.py: line 8: import: not found
/usr/lib/zabbix/alertscripts/dingding-alter.py: line 9: import: not found
/usr/lib/zabbix/alertscripts/dingding-alter.py: line 10: import: not found
/usr/lib/zabbix/alertscripts/dingding-alter.py: line 11: import: not found
/usr/lib/zabbix/alertscripts/dingding-alter.py: line 12: : not found
/usr/lib/zabbix/alertscripts/dingding-alter.py: line 13: headers: not found
/usr/lib/zabbix/alertscripts/dingding-alter.py: line 14: api_url: not found
/usr/lib/zabbix/alertscripts/dingding-alter.py: line 15: : not found
/usr

**Comment by dotneft** [comment]
Our images are trying to be minimal. So they do not have Ruby, Java, Python, Perl. if you would like to use some programming languages, please, build your own images based on our
