### ISSUE TITLE
Multiarch support

### ISSUE THREAD

**Issue by pschmitt** [zabbix/zabbix-docker#558]
Hi,

Over the past few days I've been updating my multiarch enabled images (see #145) of the various zabbix projects.
This time around I used the upstream ARM images and build them via [docker buildx](https://docs.docker.com/buildx/working-with-buildx/). The result is true multiarch capables images, I've setup [my build script](https://github.com/pschmitt/zabbix-docker-armhf) to build for every architecture that the upstream image support.
You can find the images [here](https://hub.docker.com/u/zabbixmultiarch).

Would you consider publishing official ARM builds now that there is no need to base off of unofficial images?

**Comment by rockaut** [comment]
Oh yes please that would be awesome!

**Comment by dotneft** [comment]
:-) Yep, especially when AWS introduced ARM powered services. I hope will do it as soon as possible. Currently checking Github Actions.

**Comment by dotneft** [comment]
Done!

**Comment by pschmitt** [comment]
Noice! Thanks.

**Comment by mintyray** [comment]
Hi,

testing the armv7 arch - zabbixmultiarch/zabbix-server-mysql:ubuntu-4.4.8,
 there is an issue with /sbin/tini file, which is compiled for x86 platform

./overlay2/7f0be3c7378031e4d077d3770fda0a3b6676f7b67b9d92f2e50e9bb2bec558a5/diff/sbin/tini: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=38c262787814dc459678c8f24710bbde944b7e56, stripped

while the docker image is platform linux/arm/v7

root@odroid:/var/lib/docker# docker image inspect zabbixmultiarch/zabbix-server-mysql:ubuntu-4.4.8 |grep -E "Architecture|Variant"
        "Architecture": "arm",
        "Variant": "v7",

and container will not start,
standard_init_linux.go:228: "exec user process caused: exec format error"

**Comment by dotneft** [comment]
zabbixmultiarch repository is not related to official Zabbix repository. Unfortunately we can not help with the issue with 3rd party repositories.
