### ISSUE TITLE
Issue with changing timezone from UTC to America/Denver

### ISSUE THREAD

**Issue by preston3271** [zabbix/zabbix-docker#560]
Hello, 

I have deployed the Zabbix Appliance successfully.  However, when configuration the web monitoring, I see that the graphs is displaying in UTC, so I searched the documentation to see that the change must be set within the php.ini file.  Determining that the image is Alpine, I find the file at /etc/php7/php.ini.  Moreover, I note the the web engine is Nginx.  Making the change within the file to the following:

[Date]                                                
; Defines the default timezone used by the date functions             
; http://php.net/date.timezone             
date.timezone = America/Denver     

Afterwhich, the timezone did not change.  I have went through a number of posted solutions but not have prevailed.  Please advise.

**Comment by reckless-huang** [comment]
i have also found this problem ,but i haven't found a way to solve it ,can i get help here

**Comment by dotneft** [comment]
Please do not use Zabbix Appliance, use dedicated images per each component!

**Comment by reckless-huang** [comment]
thanks for your reply , but why not recommend zabbix-appiance ,is looks esasy any cool

**Comment by dotneft** [comment]
it is an example of Zabbix installation, not ready for production and will be decommissioned soon ) + it is not true Docker way :-)

**Comment by reckless-huang** [comment]
ok, thansk ,and i will try  dedicated images .this is my first issue ,full  exciting
