### ISSUE TITLE
file system read only zabbix server 

### ISSUE THREAD

**Issue by waterlili** [zabbix/zabbix-docker#563]
when I want to create externalscript there is permission problem- read only file system. How can I solve it?

**Comment by dotneft** [comment]
Did you try to mount externalscript path?

**Comment by waterlili** [comment]
Hey @dotneft 
I want to use umount command, but it said that doesn't exist. I even tried to change default location of external script, but It doesn't work. This is on CentOs. I want to change permission of directory, however, It sounds well permitted, but again It was impossible.

**Comment by waterlili** [comment]
I found the answer. In yaml file of each operating system for each volume wrote ro which means read-only. The worst section was that we couldn't act as a root in filesystem.
