### ISSUE TITLE
Incorrect default charset for Zabbix database: "utf8mb4" instead "UTF8".

### ISSUE THREAD

**Issue by reckless-huang** [zabbix/zabbix-docker#564]
hello, i get a problem with zabbix dashboard notification : Incorrect default charset for Zabbix database: "utf8mb4" instead "UTF8". And i try change mysql character to utf8 ,it's work 
mysql> show variables like 'char%';
+--------------------------+--------------------------------+
| Variable_name            | Value                          |
+--------------------------+--------------------------------+
| character_set_client     | utf8                           |
| character_set_connection | utf8                           |
| character_set_database   | utf8mb4                        |
| character_set_filesystem | binary                         |
| character_set_results    | utf8                           |
| character_set_server     | utf8mb4                        |
| character_set_system     | utf8                           |
| character_sets_dir       | /usr/share/mysql-8.0/charsets/ |
+--------------------------+--------------------------------+
8 rows in set (0.00 sec)
but the notification is still in . 
Hope to get your help , Thanks

**Comment by maxxer** [comment]
For anyone running into this issue, here's how to repair your DB:

https://www.zabbix.com/documentation/current/en/manual/appendix/install/db_charset_coll
