### ISSUE TITLE
Using postgresql socket host instead of tcp host errors

### ISSUE THREAD

**Issue by sergei-maertens** [zabbix/zabbix-docker#566]
I'm running the nginx web frontend with PGSQL (4.4.7)

- PostgreSQL is running on the host machine
- `/var/run/postgreql` is mounted in the web container
- password does not contain special characters

**Web error in the browser:**

```
Parse error: syntax error, unexpected '{' in /etc/zabbix/web/zabbix.conf.php on line 24
```

Checking that file in the container shows that the sed replacements didn't happen.

**Container logs:**

```
** Deploying Zabbix frontend (nginx) with postgresql database
** Preparing the system
** Preparing Zabbix web-interface
** Using POSTGRES_USER variable from ENV
** Using POSTGRES_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: /var/run/postgresql
* DB_SERVER_PORT: 5432
* DB_SERVER_DBNAME: zabbix
* DB_SERVER_SCHEMA: public
* DB_SERVER_ZBX_USER: -redacted-
* DB_SERVER_ZBX_PASS: -redacted-
********************
** Adding Zabbix virtual host (HTTP)
**** Impossible to enable SSL support for Nginx. Certificates are missed.
** Preparing Zabbix frontend configuration file
** Updating '/etc/php/7.2/fpm/conf.d/99-zabbix.ini' parameter "max_execution_time": '600'... updated
** Updating '/etc/php/7.2/fpm/conf.d/99-zabbix.ini' parameter "memory_limit": '128M'... updated
** Updating '/etc/php/7.2/fpm/conf.d/99-zabbix.ini' parameter "post_max_size": '16M'... updated
** Updating '/etc/php/7.2/fpm/conf.d/99-zabbix.ini' parameter "upload_max_filesize": '2M'... updated
** Updating '/etc/php/7.2/fpm/conf.d/99-zabbix.ini' parameter "max_input_time": '300'... updated
** Updating '/etc/php/7.2/fpm/conf.d/99-zabbix.ini' parameter "date.timezone": 'Europe/Amsterdam'... added
sed: -e expression #1, char 21: unknown option to `s'

...
```

I suspect the issue is because of escaping in https://github.com/zabbix/zabbix-docker/blob/f43791e2800e51ba0b7beb5534eccedfc354dd19/web-nginx-pgsql/ubuntu/docker-entrypoint.sh#L178

I can probably work around it by letting Postgres listen on other interfaces, but I prefer to have it listen on localhost only (and not containerize my DB server).

**Comment by dotneft** [comment]
I completely do not have any idea why you want to use socket? Docker idea has important thing... all your containers could be on different machines. so in this case socket file does not have any sense. If you run containers on one machine, I think the installation is not big, so feel free to use TCP.

**Comment by sergei-maertens** [comment]
> I completely do not have any idea why you want to use socket?

Because I do not want to run my database in a container, and I do not want to let my database listen on any other interface than the loopback interface for security reasons (if it's not open to the net, it can't be accessed through the net).

> Docker idea has important thing... all your containers could be on different machines.

That's a very bold statement. If all containers should be on different machines, then why does Docker support bridge networking on the same host machine?

I'm looking at Zabbix as a free, open-source solution because I don't want to throw money at too many servers. If I have that spare budget, I'll look at a paid managed service instead of Zabbix. I want to use Docker so I am OS-independent in my config and do not have to rely on any other packages polluting my host system.

Either way if this is a wontfix, a note in the documentation that this isn't supported would've been helpful and can be helpful to future other people running into this.

**Comment by dotneft** [comment]
It is already [documented](https://github.com/zabbix/zabbix-docker/tree/4.4/server-mysql/alpine#db_server_host). You can specify IP or DNS.

Also if you would like to use socket instead of IP/DNS, you can change the image and build your own based on our images.
