### ISSUE TITLE
Obsolete VOLUME statements in Dockerfile prohibit custom images

### ISSUE THREAD

**Issue by CuBiC3D** [zabbix/zabbix-docker#568]
The Dockerfiles contain multiple `VOLUME` declarations especially for external scripts and altert scripts. `VOLUME` creates an anonymous volume that persists default container recreation by docker compose, which makes custom images containing those scripts in the locations impossible.

Anonymous volumes are considered legacy and were intended to be used where a container need to persist a state. Scripts are not a state(they are immutable) and are not produced by the application running inside the container. If a user wants to provide scripts by volume, the user would need to mount a named volume or bind mount a directory.

So my suggestion would be to remove unnecessary paths from the `VOLUME` directives or at least to allow setting those paths via environment variables outside of those volumes (not possible at the moment: `update_config_var $ZBX_CONFIG "ExternalScripts" "/usr/lib/zabbix/externalscripts"`)

Related to #412 (long ago closed with no resolution)

**Comment by dotneft** [comment]
I agree with you. We must support multiple directories for customize base image and use as volume. Unfortunately currently no solution(

**Comment by dotneft** [comment]
We will provide support for multiple Alert script and External script paths only for Docker images. Is it acceptable way?

**Comment by CuBiC3D** [comment]
@dotneft The issue exists for all the directories using `VOLUME`, so modules and everything else would not be possible to be contained in a custom image.

**Comment by dotneft** [comment]
So your idea is completely remove VOLUMEs from Dockerfile definition? But in this case the problem will be still there. You can not make custom image and mount volume at the same time. Right?

**Comment by CuBiC3D** [comment]
@dotneft Yes the idea is to remove `VOLUME` declarations, since there is no state. If you need a volume in one of those directories you can always mount one using `-v` docker-compose, kubernetes or whatever required. The directories just need to be documented in the README - but if one wants to integrate files/scripts/modules in one of those directories into an derived image (with `FROM ` directive) and not mount volumes, this is not possible with `VOLUME` declarations, since those explicitly advise Docker to create anonymous volumes - even no volumes have been provided by the command line or any other manager.

I'm not sure if there's a wrong assumption about the `VOLUME` directive. Setting directories as `VOLUME` does not declare those to be available for a mount, but it creates an anonymous volume for them to hold the contents on the host without any further specification. So your only choice is to accept this oder override it with an named volume or mount path. But not to avoid it, since it's built into the Dockerfile. Usually the user wants to choose what should be a volume and not having a lot of anonymously be created.

**Comment by dotneft** [comment]
Removed :-) Will be updated soon!

**Comment by CuBiC3D** [comment]
@dotneft thanks :wink:
