### ISSUE TITLE
Error loading modules.

### ISSUE THREAD

**Issue by agjdesenvolvimentobr** [zabbix/zabbix-docker#569]
When I use the variable **ZBX_LOADMODULE**, give an error, it passes the wrong parameters into zabbix_agentd.conf.

Command:
```
sudo docker run /
--name zabbix-agent --privileged /
-v /etc/zabbix/zabbix_agentd.d/modules:/var/lib/zabbix/modules /
-v /var/run:/var/run /
--restart unless-stopped /
-e ZBX_LOADMODULE="zabbix_module_docker.so" 
-d zabbix/zabbix-agent:latest
```

Error:
```
using configuration file: /etc/zabbix/zabbix_agentd.conf
cannot load module "zabbix_module_docker.so": Error relocating /var/lib/zabbix/modules//zabbix_module_docker.so: string_replace: symbol not found
loading modules failed, exiting...
Zabbix Agent stopped. Zabbix 4.4.7 (revision 77fb8c7
```

**Comment by jangaraj** [comment]
You need to have module compiled against used agent version https://github.com/monitoringartist/zabbix-docker-monitoring#compilation (4.4.7 in your case). Otherwise module binary may not be loaded by agent as you see in this case.

**Comment by agjdesenvolvimentobr** [comment]
that was exactly the problem, thank you very much.
