### ISSUE TITLE
zabbix4.4 ，How to modify the monitoring threshold

### ISSUE THREAD

**Issue by symenghuan** [zabbix/zabbix-docker#572]
zabbix version： 4.4
How to modify the monitoring threshold
for example：
the monitoring threshold is {$VFS.FS.PUSED.MAX.CRIT:"/"}%)，I want to change it
![image](https://user-images.githubusercontent.com/44770931/78760695-1f095180-79b4-11ea-9f31-34a0b23b917d.png)

**Comment by kernbug** [comment]
Hello macros are support on the Global, Template and Host level, see official article about using Macro: https://www.zabbix.com/documentation/current/manual/config/macros/usermacros. Closing, not related to the docker images.
