### ISSUE TITLE
dockerfile fail on Raspberry Pi 4

### ISSUE THREAD

**Issue by Kawabountou** [zabbix/zabbix-docker#573]
Hi and thank's for your job
I come to you because  i can't build the dockerfile with my 
Raspberry Pi 4. 
I use alpine Dockerfile and i have a return non zero code.
When i use Ubuntu Dockerfile, i have a bad exec.

Thank you in advance.

**Comment by dotneft** [comment]
Our docker images are not ready for ARM. You need to manually modify base images and probably STEPs as well.
