### ISSUE TITLE
IFALIAS/INTERFACES not Update 

### ISSUE THREAD

**Issue by benhamoua** [zabbix/zabbix-docker#574]
Running Zabbix 4.4.7 on CentOS. (docker):

We have an Juniper router, and we recently changed the ifalias name of a few interfaces. However, they are not showing the new name in Zabbix. We get the old name. We discovered the router before changing the interface names, the same issue when we add new interface, it's seems the template discovery is not running, i have triyed to unlink the template and link it again at this time the new Interfaces are added & IFALIAS are updated (but i guease this not the best way)

there i no issue when Running Zabbix 4.4.7 on Ubuntu.

**Comment by kernbug** [comment]
Hello. Please check LLD rule state on the host level (no errors should be for the rule used) and also update interval for the discovery rule. Issue is not related to the docker Zabbix images, closing.
