### ISSUE TITLE
Mapping port for mysql

### ISSUE THREAD

**Issue by waterlili** [zabbix/zabbix-docker#575]
@dotneft 
I want to open 3306 for docker container, so I did this commanline 

docker run -td -p 0.0.0.0:3306:3306 --name=zabbix-docker1_mysql-server_1 -e MYSQL_ROOT_PASSWORD='zabbix'  -e DB_SERVER_HOST="mysql"  mysql:8.0
Although it sounds everything is working in docker ps, when I open zabbix web page encounter with this error 
Error connecting to database: Unknown MySQL server host 'mysql' (2)

Would you please help me ?

**Comment by kernbug** [comment]
Hello. Incorrect usage of the docker options (https://docs.docker.com) and strange configuration. Please follow official Zabbix guide: https://www.zabbix.com/documentation/current/manual/installation/containers
