### ISSUE TITLE
Docker - MySQL Frontend - DB Error - the server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by uktricky** [zabbix/zabbix-docker#577]
Installed latest versions of:
mysql
zabbix/zabbix-server-mysql:latest
zabbix/zabbix-web-apache-mysql:latest

When attempting to connect client/frontend I get:
Database error
Error connecting to database: The server requested authentication method unknown to the client

**Comment by kernbug** [comment]
Could you specify MySQL version, database user setup method and show current settings for the database user from mysq.user table?

**Comment by uktricky** [comment]
MySQL version: Server version: 8.0.19 MySQL Community Server - GPL 

Created with:
docker run -d \
--net RT-Network \
--ip 192.168.144.36 \
--name=zab-mysql \
--restart unless-stopped \
-p 3306:3306 \
-e MYSQL_ROOT_PASSWORD=xxxxx \
-e MYSQL_DATABASE=zabbix \
-e MYSQL_USER=zabbix \
-e MYSQL_PASSWORD=xxxxx \
-v /volume1/docker/mysql:/var/lib/mysql \
mysql:latest

| localhost | zabbix | N           | N           | N           | N           | N           | N         | N           | N             | N            | N         | N          | N               | N          | N          | N            | N          | N                     | N                | N            | N               | N                | N                | N              | N                   | N                  | N                | N          | N            | N                      |          | 0x                     | 0x                       | 0x                         |             0 |           0 |               0 |                    0 | mysql_native_password | *CF8C0etc | N                | 2020-04-25 09:33:23   |              NULL | N              | N                | N              |                   NULL |                NULL | NULL                     | NULL            |

**Comment by dotneft** [comment]
You need to pass
```
--default-authentication-plugin=mysql_native_password
```
argument to MySQL. Zabbix does not support SHA256 auth!
