### ISSUE TITLE
Zabbix server, Docker

### ISSUE THREAD

**Issue by JhonnyBeGood** [zabbix/zabbix-docker#578]
please tell me how to write the environment variable for the parameter "increase CacheSize configuration parameter"
I use Docker container to start Zabbix Server

my error: please increase CacheSize configuration parameter
__zbx_mem_realloc(): please increase CacheSize configuration

**Comment by JhonnyBeGood** [comment]
Here is my script starting the server:

#!/bin/bash
echo
echo "Now we create Zabbix Server"
echo
docker run -it -d --name zbx-server --network zbx-network 
-p 10051:10051 
-e DB_SERVER_HOST=zbx-pgsql 
-e POSTGRES_PASSWORD=zabbix 
-e POSTGRES_USER=zabbix 
-e ZBX_ENABLE_SNMP_TRAPS=TRUE 
-v /etc/localtime:/etc/localtime:ro 
-v /etc/timezone:/etc/timezone:ro 
-v zbx-usr_alertscripts:/usr/lib/zabbix/alertscripts:ro 
-v zbx-usr-extern-scripts:/usr/lib/zabbix/externalscripts:ro 
-v zbx-export:/var/lib/zabbix/export:rw 
-v zbx-modules:/var/lib/zabbix/modules:ro 
-v zbx-enc:/var/lib/zabbix/enc:ro 
-v zbx-ssh-keys:/var/lib/zabbix/ssh_keys:ro 
-v zbx-mibs:/vat/lib/zabbix/mibs:ro 
-v zbx-snmptraps:/var/lib/zabbix/snmptraps:ro 
-v zbx-ssl_certs:/var/lib/zabbix/ssl/certs:ro 
-v zbx-ssl-ssl_ca:/var/lib/zabbix/ssl/ssl_ca:ro 
-v zbx-ssl-keys:/var/lib/zabbix/ssl/keys:ro 
--restart unless-stopped 
--volumes-from zbx-snmptraps 
--link zbx-pgsql:zbx-pgsql 
zabbix/zabbix-server-pgsql
echo
echo "Zabbix Server is running"

**Comment by dotneft** [comment]
You need to increase ZBX_CACHESIZE.

**Comment by JhonnyBeGood** [comment]
I will need to add a line in let's say some place in my code
line of this type:

e DB_SERVER_HOST=zbx-pgsql
-e POSTGRES_PASSWORD=zabbix
-e POSTGRES_USER=zabbix
=========================
-e ZBX_CACHESIZE=25M
=========================
-e ZBX_ENABLE_SNMP_TRAPS=TRUE


is that what i need to do?

Thanks!

**Comment by dotneft** [comment]
exactly!

**Comment by JhonnyBeGood** [comment]
But can you say how to correctly calculate the size of the cache in order to correctly indicate it in the settings?

**Comment by JhonnyBeGood** [comment]
unfortunately the server did not work
