### ISSUE TITLE
__zbx_mem_realloc(): out of memory (requested 32056 bytes)

### ISSUE THREAD

**Issue by JhonnyBeGood** [zabbix/zabbix-docker#580]
Hello!!!

I am using Docker system for Zabbix
I have more than 260 hosts that I must control
I start Zabbix Server as follows:

```
> #!/bin/bash
> echo
> echo "Now we create Zabbix Server"
> echo
> docker run -it -d --name zbx-server --network zbx-network \
> -p 10051:10051 \
> -e DB_SERVER_HOST=zbx-pgsql \
> -e POSTGRES_PASSWORD=zabbix \
> -e POSTGRES_USER=zabbix \
> -e ZBX_ENABLE_SNMP_TRAPS=TRUE \
> -e ZBX_CASHESIZE=1024M \
> -e ZBX_HISTORYCASHSIZE=512M \
> -e ZBX_TRENDCACHESIZE=128M \
> -e ZBX_HISTORYTEXTCASHSIZE=512M \
> -e ZBX_VALUECACHESIZE=256M \
> -v /etc/localtime:/etc/localtime:ro \
> -v /etc/timezone:/etc/timezone:ro \
> -v zbx-usr_alertscripts:/usr/lib/zabbix/alertscripts:ro \
> -v zbx-usr-extern-scripts:/usr/lib/zabbix/externalscripts:ro \
> -v zbx-export:/var/lib/zabbix/export:rw \
> -v zbx-modules:/var/lib/zabbix/modules:ro \
> -v zbx-enc:/var/lib/zabbix/enc:ro \
> -v zbx-ssh-keys:/var/lib/zabbix/ssh_keys:ro \
> -v zbx-mibs:/vat/lib/zabbix/mibs:ro \
> -v zbx-snmptraps:/var/lib/zabbix/snmptraps:ro \
> -v zbx-ssl_certs:/var/lib/zabbix/ssl/certs:ro \
> -v zbx-ssl-ssl_ca:/var/lib/zabbix/ssl/ssl_ca:ro \
> -v zbx-ssl-keys:/var/lib/zabbix/ssl/keys:ro \
> --volumes-from zbx-snmptraps \
> zabbix/zabbix-server-pgsql
> echo
> echo "Zabbix Server is running"
```

immediately after starting, the container stops working
here is his log:

> {"log":"** Preparing Zabbix server\r\n","stream":"stdout","time":"2020-04-27T10:16:51.413618065Z"}
> {"log":"** Using POSTGRES_USER variable from ENV\r\n","stream":"stdout","time":"2020-04-27T10:16:51.413965756Z"}
> {"log":"** Using POSTGRES_PASSWORD variable from ENV\r\n","stream":"stdout","time":"2020-04-27T10:16:51.414465877Z"}
> {"log":"********************\r\n","stream":"stdout","time":"2020-04-27T10:16:51.414840066Z"}
> {"log":"* DB_SERVER_HOST: zbx-pgsql\r\n","stream":"stdout","time":"2020-04-27T10:16:51.414855804Z"}
> {"log":"* DB_SERVER_PORT: 5432\r\n","stream":"stdout","time":"2020-04-27T10:16:51.414864987Z"}
> {"log":"* DB_SERVER_DBNAME: zabbix\r\n","stream":"stdout","time":"2020-04-27T10:16:51.414945798Z"}
> {"log":"* DB_SERVER_SCHEMA: public\r\n","stream":"stdout","time":"2020-04-27T10:16:51.414961169Z"}
> {"log":"********************\r\n","stream":"stdout","time":"2020-04-27T10:16:51.415487301Z"}
> {"log":"** Database 'zabbix' already exists. Please be careful with database owner!\r\n","stream":"stdout","time":"2020-04-27T10:16:51.437128103Z"}
> {"log":"\r\n","stream":"stdout","time":"2020-04-27T10:16:51.445412104Z"}
> {"log":"** Table 'zabbix.dbversion' already exists.\r\n","stream":"stdout","time":"2020-04-27T10:16:51.4557869Z"}
> {"log":"** Preparing Zabbix server configuration file\r\n","stream":"stdout","time":"2020-04-27T10:16:51.465510132Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"ListenPort\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.46826446Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"SourceIP\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.470675044Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"LogType\": 'console'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.478098285Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"LogFile\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.480582752Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"LogFileSize\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.482922137Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"PidFile\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.485168137Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"DebugLevel\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.487417808Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"DBHost\": 'zbx-pgsql'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.494207612Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"DBName\": 'zabbix'... updated\r\n","stream":"stdout","time":"2020-04-27T10:16:51.49917185Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"DBSchema\": 'public'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.506017454Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"DBUser\": 'zabbix'... updated\r\n","stream":"stdout","time":"2020-04-27T10:16:51.511278288Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"DBPort\": '5432'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.518204695Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"DBPassword\": 'zabbix'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.525326093Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"HistoryStorageURL\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.527647017Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"HistoryStorageTypes\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.529911098Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"HistoryStorageDateIndex\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.532246383Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"DBSocket\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.534459965Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StatsAllowedIP\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.536689224Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartPollers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.539078619Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartIPMIPollers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.541506882Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartPollersUnreachable\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.543919536Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartTrappers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.546375391Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartPingers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.548625749Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartDiscoverers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.550839722Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartHTTPPollers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.553036062Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartPreprocessors\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.555249707Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartTimers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.557425256Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartEscalators\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.559617047Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartAlerters\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.561764021Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartTimers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.563925735Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartEscalators\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.566139088Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartLLDProcessors\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.568359126Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"JavaGateway\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.570553315Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"JavaGatewayPort\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.572782047Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartJavaPollers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.574997054Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartVMwareCollectors\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.577266606Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"VMwareFrequency\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.579478084Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"VMwarePerfFrequency\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.581790775Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"VMwareCacheSize\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.584076796Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"VMwareTimeout\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.58629725Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"SNMPTrapperFile\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.588540942Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartSNMPTrapper\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.590799515Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"HousekeepingFrequency\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.59314695Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"MaxHousekeeperDelete\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.595389433Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"SenderFrequency\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.597590194Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"CacheSize\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.599735229Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"CacheUpdateFrequency\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.602046757Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartDBSyncers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.604262017Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"HistoryCacheSize\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.606477486Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"HistoryIndexCacheSize\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.608755454Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"TrendCacheSize\": '128M'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.615672081Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"ValueCacheSize\": '256M'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.622457531Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"Timeout\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.624607255Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"TrapperTimeout\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.627101851Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"UnreachablePeriod\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.629335013Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"UnavailableDelay\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.63158713Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"UnreachableDelay\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.633743114Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"AlertScriptsPath\": '/usr/lib/zabbix/alertscripts'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.640562624Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"ExternalScripts\": '/usr/lib/zabbix/externalscripts'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.647714978Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"FpingLocation\": '/usr/sbin/fping'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.65453746Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"Fping6Location\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.656669475Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"SSHKeyLocation\": '/var/lib/zabbix/ssh_keys'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.663685149Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"LogSlowQueries\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.665874239Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"StartProxyPollers\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.66811421Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"ProxyConfigFrequency\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.670291441Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"ProxyDataFrequency\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.672572214Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"SSLCertLocation\": '/var/lib/zabbix/ssl/certs/'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.679561613Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"SSLKeyLocation\": '/var/lib/zabbix/ssl/keys/'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.686555663Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"SSLCALocation\": '/var/lib/zabbix/ssl/ssl_ca/'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.693392641Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"LoadModulePath\": '/var/lib/zabbix/modules/'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.700221524Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"TLSCAFile\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.702490989Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"TLSCRLFile\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.704672755Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"TLSCertFile\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.706866417Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"TLSKeyFile\": ''... removed\r\n","stream":"stdout","time":"2020-04-27T10:16:51.709048089Z"}
> {"log":"** Updating '/etc/zabbix/zabbix_server.conf' parameter \"User\": 'zabbix'... added\r\n","stream":"stdout","time":"2020-04-27T10:16:51.717819016Z"}
> {"log":"Starting Zabbix Server. Zabbix 4.4.7 (revision 77fb8c7).\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724769164Z"}
> {"log":"Press Ctrl+C to exit.\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724786875Z"}
> {"log":"\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724795953Z"}
> {"log":"     6:20200427:101651.724 Starting Zabbix Server. Zabbix 4.4.7 (revision 77fb8c7).\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724854979Z"}
> {"log":"     6:20200427:101651.724 ****** Enabled features ******\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724873488Z"}
> {"log":"     6:20200427:101651.724 SNMP monitoring:           YES\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724888476Z"}
> {"log":"     6:20200427:101651.724 IPMI monitoring:           YES\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724897557Z"}
> {"log":"     6:20200427:101651.724 Web monitoring:            YES\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724905814Z"}
> {"log":"     6:20200427:101651.724 VMware monitoring:         YES\r\n","stream":"stdout","time":"2020-04-27T10:16:51.72491414Z"}
> {"log":"     6:20200427:101651.724 SMTP authentication:       YES\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724922163Z"}
> {"log":"     6:20200427:101651.724 ODBC:                      YES\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724979811Z"}
> {"log":"     6:20200427:101651.724 SSH support:               YES\r\n","stream":"stdout","time":"2020-04-27T10:16:51.724997987Z"}
> {"log":"     6:20200427:101651.724 IPv6 support:              YES\r\n","stream":"stdout","time":"2020-04-27T10:16:51.725007548Z"}
> {"log":"     6:20200427:101651.724 TLS support:               YES\r\n","stream":"stdout","time":"2020-04-27T10:16:51.725015698Z"}
> {"log":"     6:20200427:101651.724 ******************************\r\n","stream":"stdout","time":"2020-04-27T10:16:51.725023954Z"}
> {"log":"     6:20200427:101651.724 using configuration file: /etc/zabbix/zabbix_server.conf\r\n","stream":"stdout","time":"2020-04-27T10:16:51.725032074Z"}
> {"log":"     6:20200427:101651.740 current database version (mandatory/optional): 04040000/04040002\r\n","stream":"stdout","time":"2020-04-27T10:16:51.741166825Z"}
> {"log":"     6:20200427:101651.740 required mandatory version: 04040000\r\n","stream":"stdout","time":"2020-04-27T10:16:51.741193004Z"}
> {"log":"     6:20200427:101651.751 server #0 started [main process]\r\n","stream":"stdout","time":"2020-04-27T10:16:51.752149496Z"}
> {"log":"   149:20200427:101651.752 server #1 started [configuration syncer #1]\r\n","stream":"stdout","time":"2020-04-27T10:16:51.752424215Z"}
> {"log":"   149:20200427:101652.067 __mem_malloc: skipped 58 asked 32056 skip_min 328 skip_max 20144\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067436357Z"}
> {"log":"   149:20200427:101652.067 [file:dbconfig.c,line:94] __zbx_mem_realloc(): out of memory (requested 32056 bytes)\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067489642Z"}
> {"log":"   149:20200427:101652.067 [file:dbconfig.c,line:94] __zbx_mem_realloc(): please increase CacheSize configuration parameter\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067500145Z"}
> {"log":"   149:20200427:101652.067 === memory statistics for configuration cache ===\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067508948Z"}
> {"log":"   149:20200427:101652.067 free chunks of size     24 bytes:       13\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067517447Z"}
> {"log":"   149:20200427:101652.067 free chunks of size    112 bytes:        1\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067525629Z"}
> {"log":"   149:20200427:101652.067 free chunks of size \u003e= 256 bytes:       58\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067533907Z"}
> {"log":"   149:20200427:101652.067 min chunk size:         24 bytes\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067542497Z"}
> {"log":"   149:20200427:101652.067 max chunk size:      20144 bytes\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067550791Z"}
> {"log":"   149:20200427:101652.067 memory of total size 8388232 bytes fragmented into 67526 chunks\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067558934Z"}
> {"log":"   149:20200427:101652.067 of those,      49592 bytes are in       72 free chunks\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067567277Z"}
> {"log":"   149:20200427:101652.067 of those,    7258240 bytes are in    67454 used chunks\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067575494Z"}
> {"log":"   149:20200427:101652.067 ================================\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067583828Z"}
> {"log":"   149:20200427:101652.067 backtrace is not available for this platform\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067591868Z"}
> {"log":"     6:20200427:101652.069 One child process died (PID:149,exitcode/signal:1). Exiting ...\r\n","stream":"stdout","time":"2020-04-27T10:16:52.069412365Z"}
> {"log":"     6:20200427:101652.075 syncing trend data...\r\n","stream":"stdout","time":"2020-04-27T10:16:52.07546147Z"}
> {"log":"     6:20200427:101652.075 syncing trend data done\r\n","stream":"stdout","time":"2020-04-27T10:16:52.075784751Z"}
> {"log":"     6:20200427:101652.075 Zabbix Server stopped. Zabbix 4.4.7 (revision 77fb8c7).\r\n","stream":"stdout","time":"2020-04-27T10:16:52.075863496Z"}
> 

what could be my mistake, what am I doing wrong?

and another question: how could I put a damn on the **usr/local/etc/zabbix_server.conf** file
inside the container
I go into the container
docker exec -it zbx-server sh
but I am limited inside the container, I cannot access zabbix_server.conf

[b3a0032e07cf6cc53b30a741846e9daeb1b7a2358f4da312c21dc675b0143c13-json.log](https://github.com/zabbix/zabbix-docker/files/4538202/b3a0032e07cf6cc53b30a741846e9daeb1b7a2358f4da312c21dc675b0143c13-json.log)

Thanks!!!!

**Comment by kernbug** [comment]
Hello Jhonny,

> {"log":" 149:20200427:101652.067 [file:dbconfig.c,line:94] __zbx_mem_realloc(): please increase CacheSize configuration parameter\r\n","stream":"stdout","time":"2020-04-27T10:16:52.067500145Z"}

You need to increase Configuration Cache size, for docker use Docker variable ZBX_CACHESIZE=, currently from the output you have only 1024M and it's not enough. 

Also this options could be reduced to:
> -e ZBX_HISTORYCASHSIZE=64M \
> -e ZBX_TRENDCACHESIZE=64M \
> -e ZBX_HISTORYTEXTCASHSIZE=64M \

> and another question: how could I put a damn on the usr/local/etc/zabbix_server.conf file
inside the container

Path to the configuration file inside docker container is /etc/zabbix/zabbix_server.conf. Use docker variables instead of manual editing of the configuration file. 

Regards,
Edgar
