### ISSUE TITLE
Images broken and latest not up-to-date

### ISSUE THREAD

**Issue by fabiang** [zabbix/zabbix-docker#584]
Hello,

I recently pulled the image `zabbix/zabbix-web-nginx-mysql:alpine-4.0-latest` and

1. but the most recent version 4.0.20 has a different checksum as latest. Guess someone needs to update the latest tag.
2. I've noticed that supvervisord now runs as user zabbix (uid 1997, b2daaa6fe6da8f322d5d31aaa6e3334a266867fe) which then executes Nginx and PHP, but this failes with the error

   `2020/04/28 18:00:02 [emerg] 43#43: bind() to 0.0.0.0:443 failed (13: Permission denied)`

   Of cause the user `zabbix` can't bound to port 443, only root can. When I extend the Dockerfile and let it run everything under root Nginx will work, but the config of php-fpm requires a user and group to be defined.

The images are completely broken by the time of this writing and I guess it's not only the 4.0-latest image.

**Comment by dotneft** [comment]
Terrible sorry! Thank you for the informaiton! It will be solved soon!

**Comment by dotneft** [comment]
Fixed!

**Comment by fabiang** [comment]
Thanks! Gonna check it tomorrow.
