### ISSUE TITLE
zabbix-web-apache-mysql: Ports changed from 80/443 to 8080/8443

### ISSUE THREAD

**Issue by dsteinkopf** [zabbix/zabbix-docker#585]
see f2644247bd2e162a8b4c4c9f54636a5c0ade9c3a

Does this have any particular reason? It's no problem for me (just asking - I only had to change my docker-compose file), but maybe it's a problem for others!?

**Comment by dotneft** [comment]
The main idea, avoid to use 'root' user, because for example openshift does not allow to use root by default.

**Comment by niek1992** [comment]
If you try to run the default `docker-compose` image for (in my case) `zabbix/zabbix-server-mysql:ubuntu-4.4-latest` it brings all containers up nicely, but you can't connect to it. Found out that `zabbix-web-apache-mysql` is linked to `zabbix-server` on `80:80` whilst the port that gets exposed to the host is `8080`. Had to change this in the `docker-compose`.

**Comment by dotneft** [comment]
sorry, but what you changed exactly?

**Comment by niek1992** [comment]
`zabbix-web-apache-mysql` has it's ports exposed as:
``` 
ports:
   - "80:8080"
   - "443:8443"
```
But i had to change this to `8080:80` to get the webserver to talk to the zabbix-server. Maybe this is only applicable to me because i already have utilized `80` and `443` for my reverse-proxy.

I found out i needed to change the portmapping (HOST:CONTAINER) via a label on the webserver:
`docker run --name zabbix-web-apache-mysql --link mysql-server:mysql --link zabbix-server:zabbix-server -p 80:80 -d zabbix-web-apache-mysql:ubuntu-4.4.8`

Am i wrong to assume that this links both containers on port 80?

**Comment by dotneft** [comment]
Docker hub has very big queue for new images at this moment. Please wait...

**Comment by dotneft** [comment]
the image must be based on CentOS 8, but currently 4.4.8 is available only for CentOS 7.

**Comment by dsteinkopf** [comment]
In my docker-compose.yml I changed the ports-line from
```
    ports:
      - ${BIND_IP}:8083:80
```
to
```
    ports:
      - ${BIND_IP}:8083:8080
```
8083 in my case is connected to by a reverse proxy in front of zabbix.

**Comment by thejordanclark** [comment]
Maybe I missed the documentation but this needs to be documented clearly in the README.md file for the docker images.  After upgrading it took a while for me to realize that the port changed after version 4.4.7 from port 80 to port 8080.

**Comment by dotneft** [comment]
Yes, it is documented: https://www.zabbix.com/documentation/4.4/manual/installation/upgrade_notes_449

**Comment by thejordanclark** [comment]
Thanks, I see it there now.  I did not think to look in the Zabbix manual as my issue was a docker specific deployment issue.  I was thinking more from the prospective of new installs that would expect to see that type of info represented in the README.md file for the image.

i.e. https://github.com/zabbix/zabbix-docker/blob/4.4/web-nginx-pgsql/ubuntu/README.md for nginx-pgsql image.

When I get a chance I can create a pull request.

**Comment by nmoreaud** [comment]
Wow, it breaks my nuts to see this kind of changes made in a sub-minor version.
There is less than 2 years between the releases of version 4 and 5, but you had to make a breaking change in between !

**Comment by dotneft** [comment]
Yep, it is major condition to support Openshift /Kubernetes. Do not forget about notice on main repository page:
Official Zabbix Dockerfiles (**under development, not ready for production**)

PS: At this moment 3.0, 4.0, 5.0+ are more less stable and will be not significantly changed.

**Comment by nmoreaud** [comment]
You are right, there is a notice about production usage on the zabbix-docker github page. I didn't see it and it is rather discreet.
However, there is no warning on all the other pages : 

- https://www.zabbix.com/container_images
- https://www.zabbix.com/documentation/current/manual/installation/containers
- https://hub.docker.com/u/zabbix

If it is really not ready, you should add a big read warning on all these pages.

>  Zabbix provides Docker images for each Zabbix component as portable and self-sufficient containers **to speed up deployment and update procedure**.  :heart:

**Comment by mariomurrent-softwaresolutions** [comment]
How can I change the ports in V 7.4? havent found a solution yet :(
