### ISSUE TITLE
zabbix/zabbix-agent:alpine-latest

### ISSUE THREAD

**Issue by gudge25** [zabbix/zabbix-docker#590]
hi  there
docker Zabbix agent in  Privileged  mode  is  not  showing  network  and disks
],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
           "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
![image](https://user-images.githubusercontent.com/2346208/81057214-a921d880-8ed4-11ea-9f81-47e48e989e9a.png)

anything  we can do  with  this

**Comment by dotneft** [comment]
Please connect to the container and check, does it see host resources. For example, ps aux, df -h and etc...

**Comment by gudge25** [comment]
thanks for  a  quick reply
there seems  to be a problen with OS
doesnt matter  which  container in --privileged  mode i use 
there is still no  access  ho  host resourses
