### ISSUE TITLE
Enable support to tzdata trought environment

### ISSUE THREAD

**Issue by GoDllkE** [zabbix/zabbix-docker#593]
We got the problem with the timezone where there's no way to configure when installing through docker environment, making the database entries with wrong datetime from where we live. 

Would be nice to put a option of the desired tzdata as an environment option instead of forcing the UTC0.

**Comment by dotneft** [comment]
What timezone do you have in and outside? Actually you can mount /etc/timezone.

**Comment by GoDllkE** [comment]
In, it's America/Sao_Paulo and out, it showed to be "UTC0".
Got to workaround by setting up the tzdata package and creating the symbolic link. But would be nicer to be able to configure trough environment ad others docker images do.

**Comment by dotneft** [comment]
Zabbix server, proxy do not use timezone at all. They operate with unixtime stamps only. So do you have problem in your web-interface?

**Comment by GoDllkE** [comment]
No issues with web-interface

**Comment by dotneft** [comment]
do you have similar output on host server and in container:
`date +%s`

**Comment by GoDllkE** [comment]
Output is: 1588801639

Got notice that all graphs are on another localtime while the container OS is in GTM+3

**Comment by dotneft** [comment]
In this case you just need to change timezone for web container :-) PHP_TZ env variable.

**Comment by GoDllkE** [comment]
Nice! Settings this env "PHP_TZ" worked for me. Thanks!
