### ISSUE TITLE
Startup error in new versions (5.0) of proxy-sqlite3

### ISSUE THREAD

**Issue by PatrickstarWritesCode** [zabbix/zabbix-docker#594]
proxy-sqlite3 container wont start because of _zabbix_proxy [6]: ERROR: parameter "TLSConnect" value requires "TLSPSKFile", but it is not defined_ error, However I am able to run the proxy with the same environment variables on version 4.4 and successfully connect the active proxy to the server using TLSPSK method.

**Comment by dotneft** [comment]
what value do you have in TLSConnect?

**Comment by PatrickstarWritesCode** [comment]
docker run --name zabbix-proxy-sqlite3 \
	  -v /etc/zabbix:/var/lib/zabbix/enc:ro \
           *** some other PARAMS ***
	  -e ZBX_TLSPSKIDENTITY=<identity here> \
	  -e ZBX_TLSCONNECT=psk \
	  -e ZBX_TLSPSKFILE=zabbix_proxy.psk \

**Comment by PatrickstarWritesCode** [comment]
> 
> 
> what value do you have in TLSConnect?

```
docker run --name zabbix-proxy-sqlite3 \
	  -v /etc/zabbix:/var/lib/zabbix/enc:ro \
           *** some other PARAMS ***
	  -e ZBX_TLSPSKIDENTITY=<identity here> \
	  -e ZBX_TLSCONNECT=psk \
	  -e ZBX_TLSPSKFILE=zabbix_proxy.psk \
```

**Comment by dotneft** [comment]
Fixed! Thank you for finding!
