### ISSUE TITLE
Wrong PATH for fping on zabbix/zabbix-server-mysql:ubuntu-5.0-latest

### ISSUE THREAD

**Issue by fauust** [zabbix/zabbix-docker#595]
Hi!
The `fping` path is incorrect in `zabbix/zabbix-server-mysql:ubuntu-5.0-latest`.

```console
❯ docker run -it --rm zabbix/zabbix-server-mysql:ubuntu-5.0-latest bash -c "command -V fping"
fping is /usr/bin/fping
```
See https://github.com/zabbix/zabbix-docker/blob/5.0/server-mysql/ubuntu/docker-entrypoint.sh#L373

Please either update the path to `/usr/bin/fping` or add an env variable so we can specify the correct PATH.

Workarounds:
- use alpine image;
- modify and mount zabbix_server.conf into container;
- create a symlink (see bellow).

```console
❯ docker-compose exec -u root zabbix-server bash
root@afe68061f155:/var/lib/zabbix# ln -s /usr/bin/fping /usr/sbin/fping
```

**Comment by dotneft** [comment]
Fixed! Please wait when images will be updated. Thank you!

**Comment by fauust** [comment]
wow that was fast! Thank you.

**Comment by fauust** [comment]
And I see that you added `fping6`, I was wondering why it was absent, excellent!
