### ISSUE TITLE
Zabbix 5 incorrect timezone

### ISSUE THREAD

**Issue by kostopravby** [zabbix/zabbix-docker#599]
Just updated zabbix deployment in k8s from 4.4.8 to 5.0. Alerts has incorrect timezone. In env for zabbix-web-pgsql I set PHP_TZ = Europe/Madrid but now email alerts shows with UTC+0 ({EVENT.TIME}). In WebUI timezone is correct. All works fine in 4.4.8.

**Comment by john-arvid** [comment]
Probably same problem here. /etc/localtime and /etc/timezone is correct for my location(UTC+2). Also the clock in frontend shows correct time, but the alerts and check time is in my case UTC+3.

**Comment by dotneft** [comment]
WebUI does not affect to notifications, because notifications are sent by Zabbix server. So you need to specify correct timezone for Zabbix server container.

**Comment by kostopravby** [comment]
according to https://hub.docker.com/r/zabbix/zabbix-server-pgsql container
doesn't have variable with timezone

**Comment by dotneft** [comment]
Yes, mount /etc/localtime and /etc/timezone.

**Comment by kostopravby** [comment]
you need to update your documentation because for version 4.8 this setting
is not required.

**Comment by john-arvid** [comment]
In my case I'm using the [docker-compose_v3_alpine_mysql_latest.yaml](https://github.com/zabbix/zabbix-docker/blob/5.0/docker-compose_v3_alpine_mysql_latest.yaml) and there is the /etc/localtime and /etc/timezone mounted. But the problem is still there.

**Comment by dotneft** [comment]
it is required for all versions of Zabbix and required only if you have different timezone.

**Comment by kostopravby** [comment]
it's not true. I use zabbix in K8s with your yaml file from repository.
version 4.4.8 - all was correct. timezone settings was set up to webui
replication controller. when I change container image versions to 5.0.0 I
have got problems with timezone in notifications. I can't back to 4.4.8
version because do not have dev environment and don't want to restore
database backup.

**Comment by dotneft** [comment]
Webui's timezone is not related to Zabbix server container at all! Zabbix operates with unixtime everywhere. And if Zabbix server (does not matter 4.4 or 5.0 version) has different timezone than your web-interface, all date and time information in Zabbix server will be processed by different timezone.

**Comment by kostopravby** [comment]
I will check this tomorrow and let you know

**Comment by dotneft** [comment]
Sure! Thank you!

**Comment by john-arvid** [comment]
I get a bit unsure if I am understanding what @dotneft is saying.
But in the yaml file: [docker-compose_v3_alpine_mysql_latest.yaml](https://github.com/zabbix/zabbix-docker/blob/5.0/docker-compose_v3_alpine_mysql_latest.yaml)
All the containers have the /etc/localtime and /etc/timezone mounted (except the java, mysql and snmptraps).
So is this not enough to have a correct timezone in the webui for both the frontend and the alerts?
What is missing to have the correct timezone on all "servers"?

**Comment by dotneft** [comment]
webui does not use system timezone. you need to pass PHP_TZ env variable, all others use system timezone.

Just forget about web-ui timezone and correct time in notifications! It is not related at all! All notifications are sent by Zabbix server.

**Comment by john-arvid** [comment]
Thank you for your reply.
I think I have to rephrase cause I'm not sure if I understand and make myself understood.
I also add some pictures to show.
Clock in localtime (correct)
[https://imgur.com/a/w9phNMk](https://imgur.com/a/w9phNMk)
Clock in servertime (incorrect)
[https://imgur.com/a/e4LTzHW](https://imgur.com/a/e4LTzHW)
Time on Last check (incorrect)
[https://imgur.com/a/Q6xhGq0](https://imgur.com/a/Q6xhGq0)

Is this caused by the PHP_TZ env variable?

**Comment by kostopravby** [comment]
mounting timezone solved problem in k8s. please update your documentation about timezones.
