### ISSUE TITLE
Zabbix Alpine PGSQL - Fails to start

### ISSUE THREAD

**Issue by MattCrumPCN** [zabbix/zabbix-docker#601]
I've run the following command to download and run the latest Alpine/PGSQL image on Centos7 without any additional configuration:

`docker-compose -f docker-compose_v3_alpine_pgsql_latest.yaml up -d`

Both the NGINX and Apache containers are running, but have errors and are showing "unhealthy" according to docker ps:

NGINX
```
[13-May-2020 15:47:50] ALERT: [pool www] user has not been defined
[13-May-2020 15:47:50] ALERT: [pool www] user has not been defined
[13-May-2020 15:47:50] ERROR: failed to post process the configuration
[13-May-2020 15:47:50] ERROR: failed to post process the configuration
[13-May-2020 15:47:50] ERROR: FPM initialization failed
[13-May-2020 15:47:50] ERROR: FPM initialization failed
2020-05-13 15:47:50,364 INFO exited: php-fpm7 (exit status 78; not expected)
2020-05-13 15:47:50,364 INFO exited: php-fpm7 (exit status 78; not expected)
2020-05-13 15:47:53,371 INFO spawned: 'php-fpm7' with pid 49
2020-05-13 15:47:53,371 INFO spawned: 'php-fpm7' with pid 49
[13-May-2020 15:47:53] ALERT: [pool www] user has not been defined
[13-May-2020 15:47:53] ALERT: [pool www] user has not been defined
[13-May-2020 15:47:53] ERROR: failed to post process the configuration
[13-May-2020 15:47:53] ERROR: failed to post process the configuration
[13-May-2020 15:47:53] ERROR: FPM initialization failed
[13-May-2020 15:47:53] ERROR: FPM initialization failed
2020-05-13 15:47:53,432 INFO exited: php-fpm7 (exit status 78; not expected)
2020-05-13 15:47:53,432 INFO exited: php-fpm7 (exit status 78; not expected)
2020-05-13 15:47:54,434 INFO gave up: php-fpm7 entered FATAL state, too many start retries too quickly
2020-05-13 15:47:54,434 INFO gave up: php-fpm7 entered FATAL state, too many start retries too quickly

```

Apache:

```
********************
** Adding Zabbix virtual host (HTTP)
**** Impossible to enable SSL support for Apache2. Certificates are missed.
** Preparing Zabbix frontend configuration file
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "max_execution_time": '600'... updated
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "memory_limit": '128M'... updated
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "post_max_size": '16M'... updated
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "upload_max_filesize": '2M'... updated
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "max_input_time": '300'... updated
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "date.timezone": 'Europe/Riga'... added
/usr/bin/docker-entrypoint.sh: line 268: clear_deploy: command not found
########################################################
```

Any ideas what I am doing wrong / where to look next?

**Comment by dotneft** [comment]
What branch do you use? I can not reproduce the problem. Do you have specified root user in compose file?

**Comment by MattCrumPCN** [comment]
Hi @dotneft - I have not touched anything in the compose file or specified a branch (I'm using "latest" per the docker-compose command below):

`docker-compose -f docker-compose_v3_alpine_pgsql_latest.yaml up -d`

Do I need to specify a user in the compose file? If so, please let me know where that is mentioned in the Usage instructions (I followed the instructions here: https://www.zabbix.com/documentation/current/manual/installation/containers#docker_compose).

**Comment by dotneft** [comment]
```cat docker-compose_v3_alpine_pgsql_latest.yaml | grep user``` do you see something?

**Comment by djbobyd** [comment]
i have the same problem after upgrading to 5.0 . I have the user: root specified in the docker file.

**Comment by dotneft** [comment]
remove it :-)

**Comment by djbobyd** [comment]
This helped. thanks :)

**Comment by MattCrumPCN** [comment]
Hi - I removed every instance of user: root from the docker-compose file (there were 10 instances - is that what I should have done?) and the errors above have disappeared, but I'm still unable to connect - docker-compose logs shows the following:

```
zabbix-server_1            |    167:20200514:130114.303 cannot parse proxy configuration data request from active proxy at "172.16.238.5": proxy "zabbix-proxy-sqlite3" not found
zabbix-server_1            |    167:20200514:130114.311 cannot parse heartbeat from active proxy at "172.16.238.5": proxy "zabbix-proxy-sqlite3" not found
zabbix-server_1            |    164:20200514:130114.509 cannot parse proxy data from active proxy at "172.16.238.5": proxy "zabbix-proxy-sqlite3" not found

```

The zabbix-proxy-sqlite3 container has this error in it:

```
zabbix-proxy-sqlite3_1     |    111:20200514:130114.309 cannot obtain configuration data from server at "zabbix-server": empty string received
zabbix-proxy-sqlite3_1     |    117:20200514:130114.313 cannot send heartbeat message to server at "zabbix-server": proxy "zabbix-proxy-sqlite3" not found

```

The NGINX & Apache containers both show unhealthy according to docker ps:
```

977879c18469        zabbix/zabbix-web-nginx-pgsql:alpine-4.0-latest    "docker-entrypoint.sh"   5 minutes ago       Up About a minute (unhealthy)   8080/tcp, 8443/tcp, 0.0.0.0:8081->80/tcp, 0.0.0.0:8443->443/tcp   zabbix-docker_zabbix-web-nginx-pgsql_1
126be092cf65        zabbix/zabbix-web-apache-pgsql:alpine-4.0-latest   "docker-entrypoint.s…"   5 minutes ago       Up About a minute (unhealthy)   0.0.0.0:80->80/tcp, 8080/tcp, 0.0.0.0:443->443/tcp, 8443/tcp      zabbix-docker_zabbix-web-apache-pgsql_1
```

Please let me know what to try next :)

**Comment by djbobyd** [comment]
I am not sure what is your situation but I will share how it worked with me. I removed the user: root only from the frontend containers. Additionally those containers used to have a healthcheck based on curl, which seems is not available in the new versions. I removed the healthcheck from my docker-compose file as well. Another difference was that now nginx (that's what I am using) is not listening to port 80 inside the container but port 8080 instead. Thus I also changed this in the docker-compose and everything started working again and now I have a working 5.0 Zabbix server. The only thing left for me is to figure out how to upgrade the pgsql without loosing my data.
I hope this information will help you!

**Comment by dotneft** [comment]
MattCrumPCN, just use updated compose, please :-)

djbobyd, it works, healthcheck must be done on 8080 port.

**Comment by MattCrumPCN** [comment]
Hi - 

Thanks - I've recloned the repo and tried again and this now gets further, the GUI loads up and I can navigate around fine.

However, I've tried running a discovery on our local network and it hasn't worked - this is in the logs and there's a screenshot of the Zabbix host below:

```
zabbix-server_1            |    208:20200515:091047.813 cannot parse proxy data from active proxy at "172.16.238.7": proxy "zabbix-proxy-mysql" not found
zabbix-server_1            |    207:20200515:091048.312 cannot parse proxy data from active proxy at "172.16.238.4": proxy "zabbix-proxy-sqlite3" not found
zabbix-server_1            |    209:20200515:091048.817 cannot parse proxy data from active proxy at "172.16.238.7": proxy "zabbix-proxy-mysql" not found
zabbix-server_1            |    207:20200515:091049.314 cannot parse proxy data from active proxy at "172.16.238.4": proxy "zabbix-proxy-sqlite3" not found
```

![image](https://user-images.githubusercontent.com/64490589/82054055-41c70e00-96b6-11ea-83a0-e0c7ad29967d.png)

Any ideas what might be going wrong?

Thanks

**Comment by dotneft** [comment]
Hi MattCrumPCN!

Please use the issues tracker for issues related to Docker images only. I recommend you consult on our forum regarding network discovery: https://www.zabbix.com/forum/. Also I hope our manual can help you with the task: https://www.zabbix.com/documentation/current/manual/discovery/network_discovery
