### ISSUE TITLE
Port changes not documented in upgrade notes (and docs still seem to reference wrong ports) w/ 5.0

### ISSUE THREAD

**Issue by nneul** [zabbix/zabbix-docker#602]
Just updated to 5.0 containers, and found that I had to update my launch scripts (not using compose) to reflect that the in-container ports for at least docker-web-nginx-mysql changed from 80/443 to 8080/8443. 

It might be worth having that as an explicit note in the upgrade documentation and fixing the port references in the 'install from containers' section of the docs.

**Comment by holantomas** [comment]
@nneul thanks, I cannot get that work and didn't found this information. Documentation should say that.

**Comment by pedropilla** [comment]
definitely should have a big mention on that

**Comment by dotneft** [comment]
Will be fixed in https://support.zabbix.com/browse/ZBX-18007.
