### ISSUE TITLE
Zabbix should not be setting 'includeSubDomains' on it's HSTS response

### ISSUE THREAD

**Issue by nneul** [zabbix/zabbix-docker#603]
Unless zabbix is specifically managing *._zabbixfqdn_ - it should not be speaking for the HSTS status of those subdomains. 

```
nneul@skyhawk:/local/zabbix/zabbix-docker (5.0)$ grep -r -i includeSub
zabbix-appliance/rhel/conf/etc/zabbix/nginx_ssl.conf:    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
web-nginx-pgsql/alpine/conf/etc/zabbix/nginx_ssl.conf:    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
web-nginx-pgsql/centos/conf/etc/zabbix/nginx_ssl.conf:    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
web-nginx-pgsql/ubuntu/conf/etc/zabbix/nginx_ssl.conf:    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
web-nginx-mysql/alpine/conf/etc/zabbix/nginx_ssl.conf:    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
web-nginx-mysql/centos/conf/etc/zabbix/nginx_ssl.conf:    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
web-nginx-mysql/ubuntu/conf/etc/zabbix/nginx_ssl.conf:    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
```

**Comment by nneul** [comment]
Independently I think you shouldn't have that turned on by default unless someone requests it - since the average person who doesn't set up a proper cert will wind up locking themselves out of the UI.

**Comment by dotneft** [comment]
so you suggest to change HSTS to:
`add_header Strict-Transport-Security "max-age=31536000; preload";`

**Comment by nneul** [comment]
Yes, but I'm also not 100% certain on including the preload. That may have it's own set of requirements. Biggest concern I have is that careless application of HSTS can lock admins out of their services very easily, so you especially don't want to imply it for subdomains that are not directly under control of the service.

Example, it's really easy for an admin to do something like putting that HSTS record on their base website for their domain, thinking it's no big deal. Once that admin has hit that website, they are unable to access ANY of their internal services, admin web pages, legacy/insecure urls on their internal web servers, etc. from that browser since the root web page published a "subdomains" hsts rule. (That's not issue here, but related for explanation.)

Overall - my preference would be to not hard set it, but make HSTS configuratio a flag that the admin can enable  when they know it's safe to do so, including TTL and scope. That however is much more involved of a change.

**Comment by dotneft** [comment]
Removed "includeSubDomains" option according: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
