### ISSUE TITLE
Are you planing on releasing a proper Helm chart for Zabbix 5 LTS this time?

### ISSUE THREAD

**Issue by laghao** [zabbix/zabbix-docker#608]
Some backgroud to this question is to be able to deploy Zabbix 5 LTS to more container platforms therefore the question is to have an official **Helm Chart** for Zabbix, which can address some problems like ingress controllers, resources integration, secret management..

Helm helps you manage Kubernetes applications — Helm Charts help you define, install, and upgrade even the most complex Kubernetes application.

**Comment by dotneft** [comment]
Currently not, sorry (
