### ISSUE TITLE
Zabbix Agent 2: encryption support was not compiled in

### ISSUE THREAD

**Issue by o51n** [zabbix/zabbix-docker#610]
I am trying to deploy Agent 2 in a container based on the zabbix/zabbix-agent2:latest image with TLS encryption as follows:

`"docker run --name zabbix-testagent2 -e ZBX_HOSTNAME="proxyname" -e ZBX_SERVER_HOST="zabbix_ip" -e ZBX_TLSACCEPT="psk" -e ZBX_TLSCONNECT="psk" -e ZBX_TLSPSKFILE="zabbix_agent.psk" -e ZBX_TLSPSKIDENTITY="identity" -d zabbix/zabbix-agent2:alpine-latest "`

After the deployment, an error in the logs: 

`"zabbix_agent2 [3817]: ERROR: cannot use encryption configuration: encryption support was not compiled in".`

When using docker-compose with same environment variables get the same error.

What could be the reason?

**Comment by dotneft** [comment]
Fixed! Thank you!
