### ISSUE TITLE
Zabbix Agent 2: variable ZBX_ENABLEREMOTECOMMANDS not working

### ISSUE THREAD

**Issue by stallion2303** [zabbix/zabbix-docker#611]
I have ZBX_ENABLEREMOTECOMMANDS=1 in docker-compose.yml but does nothing.

Perhaps because:

> Note that this parameter has been replaced by the Plugins.SystemRun.EnableRemoteCommands parameter in 4.4.2.

**Comment by dotneft** [comment]
Actually the solution is more complex that in 4.4.2: https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/src/go/conf/zabbix_agent2.conf?at=refs%2Fheads%2Frelease%2F5.0#418

So the problem will be solved in #662.
