### ISSUE TITLE
proxy "zabbix-proxy-sqlite3" not found

### ISSUE THREAD

**Issue by baramann72** [zabbix/zabbix-docker#613]
hi@all,

ist try to run die latest ./docker-compose_v3_alpine_mysql_latest but when I start it, I got always these errors:
zabbix-server_1            |    199:20200521:205522.518 cannot parse heartbeat from active proxy at "172.16.238.7": proxy "zabbix-proxy-sqlite3" not found
zabbix-proxy-sqlite3_1     |    153:20200521:205522.518 proxy #18 started [poller #1]
zabbix-proxy-sqlite3_1     |    142:20200521:205522.519 cannot send heartbeat message to server at "zabbix-server": proxy "zabbix-proxy-sqlite3" not found
zabbix-proxy-sqlite3_1     |    154:20200521:205522.531 proxy #19 started [poller #2]
zabbix-proxy-sqlite3_1     |    161:20200521:205522.604 proxy #26 started [preprocessing worker #1]
zabbix-proxy-sqlite3_1     |    162:20200521:205522.604 proxy #27 started [preprocessing worker #2]
zabbix-proxy-sqlite3_1     |    163:20200521:205522.604 proxy #28 started [preprocessing worker #3]
zabbix-server_1            |    200:20200521:205522.629 cannot parse proxy data from active proxy at "172.16.238.7": proxy "zabbix-proxy-sqlite3" not found
zabbix-proxy-sqlite3_1     |    143:20200521:205522.630 cannot send proxy data to server at "zabbix-server": proxy "zabbix-proxy-sqlite3" not found
zabbix-server_1            |    203:20200521:205523.634 cannot parse proxy data from active proxy at "172.16.238.7": proxy "zabbix-proxy-sqlite3" not found

Docker version 19.03.9, build 9d988398e7
docker-compose version 1.25.5, build 8a1c60f6

Thanks for help :-)
Bjoern

**Comment by dotneft** [comment]
Add these proxies in Zabbix web interface Administration->Proxies.

**Comment by baramann72** [comment]
ok thanks for your hint. 

I looked into you yaml file and found this double entries for web and proxy:

zabbix-web-apache-mysql:
zabbix-web-nginx-mysql:
zabbix-proxy-sqlite3:
zabbix-proxy-mysql:

so, after delete the sections "zabbix-web-apache-mysql" and "zabbix-proxy-sqlite3" I got no more errror.

thanks

**Comment by wajika** [comment]
> Add these proxies in Zabbix web interface Administration->Proxies.

I use kubernetes.yaml  have the same issue.

zabbix svc info
![image](https://user-images.githubusercontent.com/17058349/92700769-cafb0280-f381-11ea-8579-cb4baa2afcad.png)
![image](https://user-images.githubusercontent.com/17058349/92700846-e36b1d00-f381-11ea-97c2-0536683a2896.png)

After I added the proxy address, the error prompt changed, but it still can't work.
![image](https://user-images.githubusercontent.com/17058349/92700926-f978dd80-f381-11ea-873e-0f1fd6c29d05.png)
