### ISSUE TITLE
Set BaseURL for SAML authentication when behind a reverse-proxy

### ISSUE THREAD

**Issue by msnelling** [zabbix/zabbix-docker#614]
Hi,
I'm running our Zabbix 5.0 server/web/mysql as Docker containers with Traefik v2.2 as a reverse proxy in front of them handling TLS termination with LetsEncrypt certificates. 

When attempting to get SAML authentication working with Azure AD I'm running into an issue where the SAML request generated by Zabbix contains an internal callback URL e.g `http://zabbix.example.org:8080/index_sso.php` but Azure AD is expecting to see `https://zabbix.example.org/index_sso.php?acs`. 

We need the ability to set the base URL for the SAML request when running behind a reverse-proxy.

**Comment by dotneft** [comment]
Could you try manually specify $SSO['SETTINGS']['baseurl'] in /etc/zabbix/web/zabbix.inc.php. Does it work?

**Comment by blightbow** [comment]
I'm having a similar issue where the docker container is sending the following URL:

`AssertionConsumerServiceURL="http://192.168.2.3:8080/index_sso.php?acs"`

Settings $SSO['SETTINGS']['baseurl'] in /etc/zabbix/web/zabbix.inc.php (does not exist and must be created) or /etc/zabbix/web/zabbix.conf.php does not appear to change the behavior. The container was restarted after all changes, and I know it was picking up the change to zabbix.conf.php because I forgot a semicolon. :)

Looking at [the Zabbix documentation](https://www.zabbix.com/documentation/current/manual/web_interface/frontend_sections/administration/authentication#saml_authentication), the statement `Only the following options can be set as part of $SSO['SETTINGS']:` appears and baseurl does not appear to be in that list. Is this hardcoded?

**Comment by o51n** [comment]
I have a similar problem too. The SAML request contains 'http://zabbix.url/index_sso.php?acs'.

Also tried with 'baseurl' setting in $SSO['SETTINGS'] but it makes no difference to request.

**Comment by zeduperes** [comment]
I have the same issue, trying to use SAML behind Traefik (reverse-proxy).

**Comment by zeduperes** [comment]
@dotneft did you mean zabbix.conf.php instead of zabbix.inc.php ?

**Comment by zeduperes** [comment]
Guys, I found a workaround ! 
just edit the file /usr/share/zabbix/vendor/php-saml/src/Saml2/Utils.php in the frontend container. (make sure to point this file to persist on docker volume)
edit the line
`private static $_proxyVars = false; `
to 
`private static $_proxyVars = true; `

Now is working fine with Traefik 2.2.1 + Zabbix 5.0.1

**Comment by o51n** [comment]
> Guys, I found a workaround !
> just edit the file /usr/share/zabbix/vendor/php-saml/src/Saml2/Utils.php in the frontend container. (make sure to point this file to persist on docker volume)
> edit the line
> `private static $_proxyVars = false; `
> to
> `private static $_proxyVars = true; `
> 
> Now is working fine with Traefik 2.2.1 + Zabbix 5.0.1

Thank you! Its seems to work now.

**Comment by msnelling** [comment]
> Guys, I found a workaround !
> just edit the file /usr/share/zabbix/vendor/php-saml/src/Saml2/Utils.php in the frontend container. (make sure to point this file to persist on docker volume)
> edit the line
> `private static $_proxyVars = false; `
> to
> `private static $_proxyVars = true; `
> 
> Now is working fine with Traefik 2.2.1 + Zabbix 5.0.1

Thanks, is this the full solution or do we need to do something else too?

**Comment by dotneft** [comment]
Looks like Zabbix must allow to use setProxyVars:
{quote}
When the PHP application is behind a proxy or a load balancer we can execute `setProxyVars(true)` and `setSelfPort` and `isHTTPS` will take care of the `$_SERVER["HTTP_X_FORWARDED_PORT"]` and `$_SERVER['HTTP_X_FORWARDED_PROTO']` vars (otherwise they are ignored).
{quote}

**Comment by zeduperes** [comment]
> > Guys, I found a workaround !
> > just edit the file /usr/share/zabbix/vendor/php-saml/src/Saml2/Utils.php in the frontend container. (make sure to point this file to persist on docker volume)
> > edit the line
> > `private static $_proxyVars = false; `
> > to
> > `private static $_proxyVars = true; `
> > Now is working fine with Traefik 2.2.1 + Zabbix 5.0.1
> 
> Thanks, is this the full solution or do we need to do something else too?

This is the solution for now... hopefully someone find another way, like adding SAML parameters to zabbix.conf.php.

**Comment by o51n** [comment]
> > > Guys, I found a workaround !
> > > just edit the file /usr/share/zabbix/vendor/php-saml/src/Saml2/Utils.php in the frontend container. (make sure to point this file to persist on docker volume)
> > > edit the line
> > > `private static $_proxyVars = false; `
> > > to
> > > `private static $_proxyVars = true; `
> > > Now is working fine with Traefik 2.2.1 + Zabbix 5.0.1
> > 
> > 
> > Thanks, is this the full solution or do we need to do something else too?
> 
> This is the solution for now... hopefully someone find another way, like adding SAML parameters to zabbix.conf.php.

I think the best way is adding ability to management SAML (SSO) parameters to .env_web.

**Comment by dotneft** [comment]
I agree, but there are too much params and it is not quite clear which ones are useful to change (

**Comment by dotneft** [comment]
So now instead of 'http://zabbix.url:8080/index_sso.php?acs', which URL do you have? Did you change only _proxyVars ?

**Comment by o51n** [comment]
> So now instead of 'http://zabbix.url:8080/index_sso.php?acs', which URL do you have? Did you change only _proxyVars ?

After change only _proxyVars variable to true at /zabbix/vendor/php-saml/src/Saml2/Utils.php I have the correct url "https://zabbix.url/index_sso.php?acs". No more changes. 

With Traefik 2.2.0 + Keycloak 10.0.0 + Zabbix 5.0.1 working fine now.

**Comment by pfeiffee** [comment]
Changing the $_proxyVars thing didn't work for me in zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest

However - we can be bold and just force it.
Here are some copy and pastes for folks still waiting for the fix:


FROM zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest

USER root
RUN sed -i 's/private static $_proxyVars = false;/private static $_proxyVars = true;/g' /usr/share/zabbix/vendor/php-saml/src/Saml2/Utils.php
RUN sed -i 's/private static $_protocol;/private static $_protocol = "https";/g' /usr/share/zabbix/vendor/php-saml/src/Saml2/Utils.php
RUN sed -i 's/private static $_port;/private static $_port = 443;/g' /usr/share/zabbix/vendor/php-saml/src/Saml2/Utils.php

**Comment by ajaxous** [comment]
Another option to try to set the value of ProxyVars can be found at [ZBXNEXT-5948](https://support.zabbix.com/browse/ZBXNEXT-5948?focusedCommentId=447948&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-447948)

**Comment by absmith82** [comment]
turns out if you set SSO['SETTINGS'] = ['strict' => false]; in /etc/zabbix/web/zabbix.conf.php it also fixes the problem and is then at least something that works within the [ Zabbix Documentation](https://www.zabbix.com/documentation/current/manual/web_interface/frontend_sections/administration/authentication#saml_authentication) instead of custom rewriting source code.

**Comment by dotneft** [comment]
We added SSO_SETTINGS for all web images. I hope it may help in this situation.

**Comment by dotneft** [comment]
So now you can specify the following env variable:
```
ZBX_SSO_SETTINGS=['strict' : 0]
```

Not sure that "false" will be correctly recognised (

**Comment by mart123p** [comment]
> So now you can specify the following env variable:
> 
> ```
> ZBX_SSO_SETTINGS=['strict' : 0]
> ```
> 
> Not sure that "false" will be correctly recognised (

For anyone stumbling on this issue the suggested fix in the environment variable should be
`ZBX_SSO_SETTINGS={'strict':false}`

**Comment by absmith82** [comment]
seems like this fixed the issue with some providers but does not fix the issue with all providers.

Azure AD still rejects some of the settings and Zabbix doesn't like the way Azure AD tries to directly sign in on this,  
Looks like we will need Zabbix to allow us to use setProxyVars if we want this to work properly without users needing to rebuild the containers.

**Comment by modaresimr** [comment]
It is not still working 

> > So now you can specify the following env variable:
> > ```
> > ZBX_SSO_SETTINGS=['strict' : 0]
> > ```
> > 
> > 
> > Not sure that "false" will be correctly recognised (
> 
> For anyone stumbling on this issue the suggested fix in the environment variable should be
> `ZBX_SSO_SETTINGS={'strict':false}`
> Otherwise the json_decode method will not properly decode the JSON and will return false.

**Comment by BadAtIrcBots** [comment]
For the sake of anyone Googling this, the issue was properly fixed in https://support.zabbix.com/browse/ZBX-19320

The fix for that introduced a new variable "use_proxy_headers", set it in zabbix.conf.php like so
`$SSO['SETTINGS'] = [
        'use_proxy_headers' => true
];`

**Comment by bgilly1** [comment]
On version 5.4 docker containers using nginx/mysql this worked for me with no other changes:

`ZBX_SSO_SETTINGS={"strict":false, "baseURL":"https://<fqdn>/", "use_proxy_headers":true}`

**Comment by szuro** [comment]
> 
> 
> On version 5.4 docker containers using nginx/mysql this worked for me with no other changes in .env_web :
> 
> `ZBX_SSO_SETTINGS={"strict":false, "baseURL":"https://<fqdn>/", "use_proxy_headers":true}`

To anyone trying to use this and failing: it's `baseurl` not `baseURL`

**Comment by crlshn** [comment]
Hi, I am writing in 2022, this may be already closed and I may be failing to read/understand the documentation (spanish-user),
after clone zabbix-docker git repository, current tag: **ubuntu-6.0-latest**, after add at the end of the file env_vars/.env_web 
```
ZBX_SSO_SP_KEY=/usr/share/zabbix/conf/certs/sp.key  
ZBX_SSO_SP_CERT=/usr/share/zabbix/conf/certs/sp.crt
ZBX_SSO_IDP_CERT=/usr/share/zabbix/conf/certs/idp.crt

ZBX_SSO_SETTINGS={
    "strict" : false, 
    "baseurl" : "https://zabbix.xxxxxx.tk/",
    "use_proxy_headers" : true
    } # Available since 5.0.0
```
created the key/crt and copy/paste the idp.crt.... I am still having the RelayState pointing to "http" // <fqdn> "8080"
![image](https://user-images.githubusercontent.com/2448271/171759617-37927e6d-00c7-4648-bda6-f03e272e6855.png)

which of course give me the 
![image](https://user-images.githubusercontent.com/2448271/171759684-12816df3-8630-40b6-85d8-d66a1294399f.png)

I did add nginx proxy headers in the synology reverse proxy settings:
![image](https://user-images.githubusercontent.com/2448271/171759857-ca0e3092-4cd8-48a9-86d8-be8b1b39e8c6.png)

I don't have https Certs inside the zabbix-docker 
![image](https://user-images.githubusercontent.com/2448271/171760008-89421508-6803-4953-893a-9e9902c38ea8.png)

any help or documentation will be appreciated

**Comment by dsexton1055** [comment]
Google searches tend to lead here.
Docker Compose BaseURL is configured in .env_web
ZBX_SSO_SETTINGS={"strict":false, "baseurl":"https://FQDN/", "use_proxy_headers":true}
baseurl is, naturally, case sensitive. Many git comments have it shown as baseURL. Might have been modified at some point over the years.

**Comment by cheggerdev** [comment]
In docker-compose this setting

```
            - ZBX_SSO_SETTINGS="{\"strict\":true, \"baseurl\":\"https://xxxxxxx/\", \"use_proxy_headers\":true}"
```

results in

```
zabbix-web-1  | [26-Jan-2025 21:35:31] WARNING: [pool zabbix] child 34 said into stderr: "[26-Jan-2025 21:35:31 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, string given in /usr/share/zabbix/index_sso.php:73"
```

In docker-compose this setting

```
            - >-
                ZBX_SSO_SETTINGS={"strict": false, "baseurl": "https://xxxxx/", "use_proxy_headers": true, "security": {"requestedAuthnContext": false}}
```

works for me. This is on Zabbix 7.2.2.

**Comment by HimbeersaftLP** [comment]
baseurl and use_proxy_headers should be enough, and it works like that for me.
strict shouldn't be set to false in production: https://github.com/SAML-Toolkits/php-saml/?tab=readme-ov-file#security-warning
`ZBX_SSO_SETTINGS={"baseurl": "https://zabbix.example.com/zabbix/", "use_proxy_headers": true}`
