### ISSUE TITLE
Upgrade from 4.4 to 5.0 issue

### ISSUE THREAD

**Issue by starlessboi** [zabbix/zabbix-docker#615]
Hi guys, thanks for your great job
I use zabbix docker-compose, based on Ubuntu, nginx and postgres. (https://github.com/zabbix/zabbix-docker/blob/4.4/docker-compose_v3_ubuntu_pgsql_latest.yaml)
after version 5.0 released, decided to upgrade my running zabbix 4.4.8 version to latest version.
for this I changed all ubuntu-4.4-latest to ubuntu-5.0-latest tag in my compose file, then pulled images, and upgraded it. I also applied this to my docker compose file: https://github.com/zabbix/zabbix-docker/issues/602
but my zabbix is not running any more, it gives error 502 bad gateway.
did I missed some thing?
after more investigation, I saw docker zabbix-web-nginx-pgsql is unhealthy, then I checked logs and saw this:
 connect() to unix:/tmp/php-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 10.1.10.9, server: zabbix, request: "POST /zabbix.php?sid=ce6f8cfef19b6fc1&action=widget.favmaps.view HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "10.1.10.230:8081", referrer: "http://10.1.10.230:8081/zabbix.php?action=dashboard.view&ddreset=1"

What is wrong with my steps?

**Comment by dotneft** [comment]
You are welcome! Do you have user variable in compose file? If yes, remove it for zabbix-web-nginx-pgsql

**Comment by starlessboi** [comment]
that was the trick.
thanks, saved me a day
