### ISSUE TITLE
**** MySQL server is not available. Waiting 5 seconds...

### ISSUE THREAD

**Issue by lemon360cn** [zabbix/zabbix-docker#616]
the problem is CentOS 8.1, it works well on CentOS 7.

docker logs -f zabbix-server-mysql 
** Preparing Zabbix server
** Using MYSQL_USER variable from ENV
** Using MYSQL_PASSWORD variable from ENV
** Using MYSQL_ROOT_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: mysql-server
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...

**Comment by lemon360cn** [comment]
#--1.Start empty MySQL server instance
shell> docker run --name mysql-server -t \
-e MYSQL_DATABASE="zabbix" \
-e MYSQL_USER="zabbix" \
-e MYSQL_PASSWORD="zabbix_pwd" \
-e MYSQL_ROOT_PASSWORD="root_pwd" \
-v /etc/localtime:/etc/localtime \
--restart unless-stopped \
-p 3306:3306 \
-d mysql:8.0 \
--character-set-server=utf8 --collation-server=utf8_bin \
--default-authentication-plugin=mysql_native_password

#--2.Start Zabbix Java gateway instance
shell> docker run --name zabbix-java-gateway -t \
-v /etc/localtime:/etc/localtime \
--restart unless-stopped \
-d zabbix/zabbix-java-gateway:latest

#--3.Start Zabbix server instance and link the instance with created MySQL server instance
shell> docker run --name zabbix-server-mysql -t \
--link mysql-server:mysql \
--link zabbix-java-gateway:zabbix-java-gateway \
-e DB_SERVER_HOST="mysql-server" \
-e MYSQL_DATABASE="zabbix" \
-e MYSQL_USER="zabbix" \
-e MYSQL_PASSWORD="zabbix_pwd" \
-e MYSQL_ROOT_PASSWORD="root_pwd" \
-e ZBX_JAVAGATEWAY="zabbix-java-gateway" \
-v /etc/localtime:/etc/localtime \
--restart unless-stopped \
-p 10051:10051 \
-d zabbix/zabbix-server-mysql:latest

#--4.Start Zabbix web interface and link the instance with created MySQL server and Zabbix server instances
shell> docker run --name zabbix-web-nginx-mysql -t \
--link mysql-server:mysql \
--link zabbix-server-mysql:zabbix-server \
-e DB_SERVER_HOST="mysql-server" \
-e MYSQL_DATABASE="zabbix" \
-e MYSQL_USER="zabbix" \
-e MYSQL_PASSWORD="zabbix_pwd" \
-e MYSQL_ROOT_PASSWORD="root_pwd" \
-e PHP_TZ="Asia/Shanghai" \
-v /etc/localtime:/etc/localtime \
--restart unless-stopped \
-p 80:8080 \
-d zabbix/zabbix-web-nginx-mysql:latest

**Comment by dotneft** [comment]
Please try to use network instead of link.

**Comment by lemon360cn** [comment]
The problem remains

**Comment by dotneft** [comment]
what about MySQL availability in Zabbix server container?

**Comment by sandy5737** [comment]
i met too
and  i checked the nohup.out
200529 12:13:56 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
200529 12:13:56 [Note] Server socket created on IP: '0.0.0.0'.
200529 12:13:56 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.host' doesn't exist
[

**Comment by dotneft** [comment]
so it looks like you have issue with MySQL container. Looks like MySQL does not have permissions to write DB data files. Please check this moment.

**Comment by garymol** [comment]
I'm having the same issue with zabbix/zabbix-server-mysql:centos-4.4-latest images, but the database is up and all of the connection details are correct.
When the zabbix server starts I see the above error, and the database is showing:
   "database_1      | 2020-05-29 17:52:50 117 [Warning] Access denied for user '"zabbix"'@'10.100.98.3' (using password: YES)"

However, I can connect successfuly to the database container from the zabbix container using the same credentials:

docker exec -ti zabbix_zabbixserver_1 mysql -h database -u zabbix -p zabbix
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A
Welcome to the MariaDB monitor.  Commands end with ; or \g.
...

Is the password perhaps not being issued properly?

**Comment by dotneft** [comment]
why you have double quotes in user name?
`"zabbix"`
maybe this one is mistake?

**Comment by sandy5737** [comment]
no ， all file is mysql:mysql like 
rw-rw----. 1 mysql mysql     8192 May 29 17:55 aria_log.00000001
-rw-rw----. 1 mysql mysql       52 May 29 17:55 aria_log_control
-rw-rw----. 1 mysql mysql  5242880 May 29 17:55 ib_logfile0
-rw-rw----. 1 mysql mysql  5242880 May 29 17:42 ib_logfile1
-rw-rw----. 1 mysql mysql 18874368 May 29 17:55 ibdata1

**Comment by garymol** [comment]
I removed all quoting on the ENV variables.  That fixed it.  Thanks.
