### ISSUE TITLE
Java gateway don't work

### ISSUE THREAD

**Issue by rogeriomachado666** [zabbix/zabbix-docker#617]
Java gateway don't work on commit 055cf57d9084c482accb4f8aaeb65a69de02f964 , no TCP port on  https://github.com/zabbix/zabbix-docker/blob/5.0/docker-compose_v3_ubuntu_pgsql_latest.yaml#L332

**$ cat /etc/debian_version**
buster/sid

**$ netstat -an | grep 10052**
/empty/

**$ docker-compose up -d**

**$ docker-compose version**
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**$ docker logs 69**
** Preparing Zabbix Java Gateway
** Preparing Zabbix Java Gateway log configuration file
2020-05-25 19:16:21.228 [main] INFO  com.zabbix.gateway.JavaGateway - Zabbix Java Gateway 5.0.0 (revision 9665d62) has started
2020-05-25 19:16:21.245 [main] INFO  com.zabbix.gateway.JavaGateway - listening on 0.0.0.0/0.0.0.0:10052

**$ docker ps**
...
699f36f42754        zabbix/zabbix-java-gateway:alpine-5.0.0            "docker-entrypoint.s…"   49 seconds ago      Up 41 seconds                                                                       zabbix-docker_zabbix-java-gateway_1
...

**$ sudo netstat -nltp | grep 10052** 
/empty/

**$ netstat -an | grep 10052**
udp     6912      0 0.0.0.0:10052 

**$ docker exec --user root -it 69 /bin/bash**

bash-5.0# netstat -an | grep 10052
tcp        0      0 0.0.0.0:10052           0.0.0.0:*               LISTEN

bash-5.0# ps -ef | grep java
    1 zabbix    0:03 /usr/bin/java -server -Dlogback.configurationFile=/etc/zabbix/zabbix_java_gateway_logback.xml -classpath /usr/sbin/zabbix_java/lib:/usr/sbin/zabbix_java/lib/slf4j-api-1.6.1.jar:/usr/sbin/zabbix_java/lib/logback-core-0.9.27.jar:/usr/sbin/zabbix_java/lib/logback-classic-0.9.27.jar:/usr/sbin/zabbix_java/lib/android-json-4.3_r3.1.jar:/usr/sbin/zabbix_java/bin/zabbix-java-gateway-5.0.0.jar com.zabbix.gateway.JavaGateway
   52 root      0:00 grep java
bash-5.0#

**Comment by dotneft** [comment]
Hello! Did you found some issue in sources or on your side?
