### ISSUE TITLE
how to use zabbix-snmptraps images

### ISSUE THREAD

**Issue by sandy5737** [zabbix/zabbix-docker#621]
hi , i have try to follow the step to build the container with zabbix-snmptraps and zabbix-appliance,but they can not receive the trap message . 
actually , the container zabbix-snmptraps havd never create the snmptrap.log file , but i can use the docker logs to check the caontainer already received the trap message.

**Comment by dotneft** [comment]
Please do not use appliance, use dedicated images for each component! To understand how to use it you can check compose files.

**Comment by sandy5737** [comment]
> Please do not use appliance, use dedicated images for each component! To understand how to use it you can check compose files.

oh yes  thanks for help, actually , if i  just only use this images , when it received traps , it will write in to the snmptraps.log rihgt ? but it has not .

**Comment by dotneft** [comment]
Exactly! It is fully correct. The file is shared between server and snmptraps containers.
