### ISSUE TITLE
Bad replacement when passing the parameter ZBX_SERVER_HOST=“1.2.3.4”

### ISSUE THREAD

**Issue by ntbrito** [zabbix/zabbix-docker#622]
Hi,
When passing the ZBX_SERVER_HOST parameter to the image zabbix-web-apache-mysql it get badly replaced on the file /etc/zabbix/web/zabbix.conf.php with 3 extra dots on each side of the value, like:
$ZBX_SERVER      = '...1.2.3.4...';
instead
$ZBX_SERVER      = '1.2.3.4';
Which causes the frontend to be unable to connect to the zabbix server.
Removing the dots and restarting the container makes it work and I stop seeing error message saying that the zabbix server is not running and the data may be outdated.
Thanks.

**Comment by dotneft** [comment]
Hello please show us container log file.

**Comment by ntbrito** [comment]
This is all there is during the container startup:

** Deploying Zabbix web-interface (Apache) with MySQL database
** Using MYSQL_USER variable from ENV
** Using MYSQL_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: name-was-deleted.rds.amazonaws.com
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
** Adding Zabbix virtual host (HTTP)
**** Impossible to enable SSL support for Apache2. Certificates are missed.
** Preparing Zabbix frontend configuration file
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "max_execution_time": '600'... updated
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "memory_limit": '128M'... updated
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "post_max_size": '16M'... updated
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "upload_max_filesize": '2M'... updated
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "max_input_time": '300'... updated
** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "date.timezone": 'Europe/London'... added
########################################################
** Executing '/usr/sbin/httpd -D FOREGROUND'
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message


From here it's just regular http related stuff:

[Fri May 29 12:34:20.412570 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.43 (Unix) PHP/7.3.17 configured -- resuming normal operations
[Fri May 29 12:34:20.412609 2020] [core:notice] [pid 1] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
10.100.1.174 - - [29/May/2020:12:34:42 +0000] "GET / HTTP/1.1" 200 3556 "-" "ELB-HealthChecker/2.0"
10.100.1.156 - - [29/May/2020:12:34:43 +0000] "GET / HTTP/1.1" 200 3556 "-" "ELB-HealthChecker/2.0"
10.100.1.120 - - [29/May/2020:12:34:43 +0000] "GET / HTTP/1.1" 200 3556 "-" "ELB-HealthChecker/2.0"

**Comment by ntbrito** [comment]
And this is how I start both containers, the server and the web frontend:

docker run --name zabbix-server -p 10051:10051 -v /efsvolume/zabbix/externalscripts:/usr/lib/zabbix/externalscripts -e DB_SERVER_HOST=“databaseservername.rds.amazonaws.com" -e MYSQL_USER="zabbix" -e MYSQL_PASSWORD=“PASSWORD” -d zabbix/zabbix-server-mysql:latest

docker run --name zabbix-web --link zabbix-server:zabbix-server -p 8040:8080 -e DB_SERVER_HOST="databaseservername.rds.amazonaws.com" -e MYSQL_USER="zabbix" -e MYSQL_PASSWORD="PASSWORD" -e ZBX_SERVER_HOST=“10.100.1.48” -e ZBX_SERVER_NAME="Silicon Markets" -e PHP_TZ="Europe/London" -d zabbix/zabbix-web-apache-mysql:latest

Thanks.

**Comment by ntbrito** [comment]
Hi Alexey, I think you are right I might have used the wrong quotes. I deployed the container and this time everything looks good on the file /etc/zabbix/web/zabbix.conf.php and the ZBX_SERVER variable shows the correct value like it should be without the extra dots.
I am sorry i wasted your time.
I believe we can close this.
