### ISSUE TITLE
SNMP Mib error when proxy starts

### ISSUE THREAD

**Issue by thebeerman** [zabbix/zabbix-docker#623]
I'm using the 5.0.0 and 5.0.1 ubuntu proxy images and see the same SNMP error when starting the container in the zabbix_proxy.log

Bad operator (INTEGER): At line 73 in /var/lib/snmp/mibs/ietf/SNMPv2-PDU

This is due to an outdated SNMPv2-PDU mib file provided in the image.  Can this be updated to the patched version?
Issue is documented here:
https://serverfault.com/questions/936119/snmp-mibs-on-ubuntu-error-in-mibs

**Comment by dotneft** [comment]
Actually during each image build process we use the latest available snmp-mibs-downloader. So probably the issue still exists in Ubuntu distribution.

**Comment by PadaKwaak** [comment]
I have switched to the CentOS variant, since I'm experiencing this kind of issue on both the Ubuntu & Alpine images - even with 5.0.2.

**Comment by dotneft** [comment]
What issue do you have with Alpine?

**Comment by PadaKwaak** [comment]
@dotneft , sorry, so it looks like alpine-5.0.2 is working even though it logs a bunch of MIB related issues on startup: 
[zabbix-server-mysql_alpine-5.0.2.log](https://github.com/zabbix/zabbix-docker/files/5028368/zabbix-server-mysql_alpine-5.0.2.log)

with alpine-4.4.8 I had SNMP issues and then I went to ubuntu-4.4.8.

**Comment by PadaKwaak** [comment]
@dotneft , I have now upgraded to alpine-5.0.3 and had the same kind of issues with SNMP again:
```
Cannot find module (HOST-RESOURCES-MIB): At line 0 in (none)
   195:20200825:082010.269 item "host1.example.com:snmp.system.hrSWRunPerfCPUSuperDoctor" became not supported: snmp_parse_oid(): cannot parse OID "HOST-RESOURCES-MIB::hrSWRunPath".
```

When I stopped the container, removed it and started it again the issue went away with the zabbix/zabbix-server-mysql:alpine-5.0.3 image.
The logs did not contain any MIB issues either on the second start of the docker container.

The one difference that I have also noticed on the first start of the docker container was this:
```
     6:20200825:081854.674 optional patches were found
     6:20200825:081854.674 starting automatic database upgrade
     6:20200825:081854.677 completed 100% of database upgrade
     6:20200825:081854.677 database upgrade fully completed
```

My full alpine-5.0.3 logs of the first startup can be found here:
[zabbix-server-mysql_alpine-5.0.3.log](https://github.com/zabbix/zabbix-docker/files/5122830/zabbix-server-mysql_alpine-5.0.3.log)
And the logs of the second startup:
[zabbix-server-mysql_alpine-5.0.3-2nd-start.log](https://github.com/zabbix/zabbix-docker/files/5122898/zabbix-server-mysql_alpine-5.0.3-2nd-start.log)

**Comment by dotneft** [comment]
probably it needs to create some caches... did you recreate the container from scratch or just restarted? Do you have mounted MIB volume?

**Comment by PadaKwaak** [comment]
I am really not sure what kind of caching it is.

I can reproduce it by doing:
```docker-compose down && docker system prune -f && docker-compose up -d```

The only thing that seemed to solve it is by using a named volume in docker-compose, eg:
```zbx-usr-share-snmp-mibs:/usr/share/snmp/mibs:rw```

If I don't invoke the prune command, then it works (after 2nd startup) without having to mount a volume.
