### ISSUE TITLE
 zabbix is ​​not grouping items by application

### ISSUE THREAD

**Issue by renancamargo** [zabbix/zabbix-docker#624]
In the most recent data Zabbix 5.0 is ​​not grouping items by application.

Zabbix 5.0 only groups items together when searching by application.

In the previous version of zabbix 5.0 items appeared grouped.

![1](https://user-images.githubusercontent.com/16986760/83530933-c55c6980-a4c2-11ea-98b3-bde13976ce4c.png)
`

`
![2](https://user-images.githubusercontent.com/16986760/83530949-ca211d80-a4c2-11ea-8d24-50285edd8c12.png)

**Comment by dotneft** [comment]
Sorry, the issue is not related to images. Please use our BUG tracker: https://support.zabbix.com/projects/ZBX/
