### ISSUE TITLE
Docker-Compose - Alpine/MySQL - Agent/Server issues

### ISSUE THREAD

**Issue by MattCrum1** [zabbix/zabbix-docker#625]
Hi - I'm having issues getting the Server/local Agent to talk to each other (I think) - within the Zabbix GUI, I'm seeing this message against the host "ZBX" connection:

`Get value from agent failed: cannot connect to [[127.0.0.1]:10050]: [111] Connection refused`

To get this stood up, I have git-cloned the most recent version of the repo from here into /opt/zabbix-docker on my server and attempted to start it using the docker-compose_v3_alpine_mysql_latest.yaml file.

It complained about not being able to access proxies, so I removed the zabbix-proxy-sqlite3 section from the docker-compose file because we're not using sqlite here (might be worth removing that on your side?) and added zabbix-proxy-mysql as a proxy within the GUI which appeared to work.

However, I'm now seeing an issue with the Agent - its port mapping is set up properly, but it is failing to start with these messages:

```
 24095:20200602:162247.171 active check configuration update from [zabbix-server:10051] started to fail (ZBX_TCP_READ() timed out)
 24095:20200602:162347.200 active check configuration update from [zabbix-server:10051] is working again
 24095:20200602:162347.200 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:162547.243 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:162747.265 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:162947.303 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:163147.330 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:163347.353 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:163547.373 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:163747.402 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:163947.430 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:164147.451 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:164347.476 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:164547.511 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:164747.538 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24095:20200602:164947.556 no active checks on server [zabbix-server:10051]: host [34555d3097ea] not found
 24009:20200602:165136.940 Got signal [signal:15(SIGTERM),sender_pid:23567,sender_uid:1997,reason:0]. Exiting ...
 24009:20200602:165136.941 Zabbix Agent stopped. Zabbix 5.0.1 (revision c2a0b03).
```

Zabbix server is running and listening on TCP 10051 - so I'm not sure why the agent is not able to connect to it.

`9b8127edc671        zabbix/zabbix-server-mysql:alpine-5.0-latest       "/sbin/tini -- /usr/…"   2 hours ago         Up 54 minutes             0.0.0.0:10051->10051/tcp                         zabbix-docker_zabbix-server_1`

Any ideas what is going on here / why the server isn't able to talk to the agent?

**Comment by dotneft** [comment]
Zabbix server communicates with agent on 10050／TCP port. Also I recommend you use DNS name, if you use our compose file, just change "127.0.0.1" to "zabbix-agent" in DNS field and switch connection to DNS. 

Errors you have specified are related to active checks only.
