### ISSUE TITLE
Upgrade psql from 4.4 to 5.0 failed - index "items_1" does not exist

### ISSUE THREAD

**Issue by maarsaks** [zabbix/zabbix-docker#627]
Steps to reproduce:
```
docker stop [all containers]

docker pull [all images to latest - postgres, zabbix-nginx, zabbix-server]

docker container prune

docker run -d \
   --name zabbix_pgsql \
   --network zabbix_netw \
   -p 5432:5432 \
   -e POSTGRES_DB="zabbixdb" \
   -e POSTGRES_USER="zabbixuser" \
   -e POSTGRES_PASSWORD="zabbixpswd" \
   -e PGDATA=/var/lib/postgresql/data/pgdata \
   -v /volumes/postgresql:/var/lib/postgresql/data \
   postgres:latest

docker run -d \
    --name zabbix_server \
    --network zabbix_netw \
    -e DB_SERVER_HOST="zabbix_pgsql" \
    -e POSTGRES_DB="zabbixdb" \
    -e POSTGRES_USER="zabbixuser" \
    -e POSTGRES_PASSWORD="zabbixpswd" \
    -p 10051:10051 \
    zabbix/zabbix-server-pgsql:latest

docker run -d \
    -p 8080:80 \
    --name zabbix_frontend \
    --network zabbix_netw \
    -e DB_SERVER_HOST="zabbix_pgsql" \
    -e POSTGRES_DB="zabbixdb" \
    -e POSTGRES_USER="zabbixuser" \
    -e POSTGRES_PASSWORD="zabbixpswd" \
    -e ZBX_SERVER_HOST="zabbix_server" \
    zabbix/zabbix-web-nginx-pgsql:latest
```

Error when try to start the "zabbix_server" container:

> Starting Zabbix Server. Zabbix 5.0.1 (revision c2a0b03).
> Press Ctrl+C to exit.
> 
>      6:20200603:085738.227 Starting Zabbix Server. Zabbix 5.0.1 (revision c2a0b03).
>      6:20200603:085738.227 ****** Enabled features ******
>      6:20200603:085738.227 SNMP monitoring:           YES
>      6:20200603:085738.227 IPMI monitoring:           YES
>      6:20200603:085738.227 Web monitoring:            YES
>      6:20200603:085738.227 VMware monitoring:         YES
>      6:20200603:085738.227 SMTP authentication:       YES
>      6:20200603:085738.227 ODBC:                      YES
>      6:20200603:085738.227 SSH support:               YES
>      6:20200603:085738.227 IPv6 support:              YES
>      6:20200603:085738.227 TLS support:               YES
>      6:20200603:085738.227 ******************************
>      6:20200603:085738.227 using configuration file: /etc/zabbix/zabbix_server.conf
>      6:20200603:085738.251 current database version (mandatory/optional): 04050001/04050001
>      6:20200603:085738.251 required mandatory version: 05000000
>      6:20200603:085738.251 starting automatic database upgrade
>      6:20200603:085738.252 [Z3005] query failed: [0] PGRES_FATAL_ERROR:ERROR:  index "items_1" does not exist
>  [drop index items_1]
>      6:20200603:085738.252 database upgrade failed

**Comment by Toumash** [comment]
Did you try to add the index?

Are you sure you didn't delete it on some migration?

**Comment by dotneft** [comment]
Looks like your db is not consistent. Please check 4.4 vanilla db schema and recover indexes. Then try again to upgrade

**Comment by maarsaks** [comment]
Okay, you're right. I don't why, but the database wasn't consistent. I created the index with:
`CREATE INDEX items_1 on items (type);`
And then the zabbix_server successfully dropped it.

I'm curious - it shouldn't be ignored if there's nothing to drop?

**Comment by dotneft** [comment]
Great!

Why we can ignore error? Maybe DB is corrupted?
