### ISSUE TITLE
It comes with an error ''./docker-compose_v3_alpine_mysql_latest.yaml' is invalid' when start running a docker container using docker-compose up -d command

### ISSUE THREAD

**Issue by JxClur** [zabbix/zabbix-docker#635]
Operation system: Ubuntu 18.04.4 LTS
Docker Version: Docker version 19.03.8, build afacb8b7f0
Zabbix-docker version: Zabbix v5.0.1 release

When I start running zabbix docker container using 'docker-compose up -d' command, it comes with the following error messege:
**ERROR messege:**
ERROR: The Compose file './docker-compose_v3_ubuntu_mysql_latest.yaml' is invalid because:
services.zabbix-web-apache-mysql.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.zabbix-web-nginx-mysql.healthcheck value Additional properties are not allowed ('start_period' was unexpected)

**Comment by rainisto** [comment]
I have the same issue on latest Ubuntu 18.04.4 LTS on all compose files with start_period property.

**Comment by loethen** [comment]
I think you can change version to "3.4", because 3.5 not working

**Comment by dotneft** [comment]
What docker-compose version do you have?

**Comment by dotneft** [comment]
Actually it is supported since 3.4 version, while compose files are prepared with 3.5 version support: https://docs.docker.com/compose/compose-file/#healthcheck
