### ISSUE TITLE
Make it possible to disable nginx access_log

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#640]
Currently nginx "spams" the container log with access_log and there's no way to shut it off.
So maybe a new env variable woud be great.

```
    access_log /dev/fd/1 main;
    error_log /dev/fd/2 error;
```

**Comment by rockaut** [comment]
Sorry for PR spamming. Had errors on git-pushes.
Currently 3 open PR fixes this issue with adding an new environment variable NGINX_ACCESS_LOG.
It defaults to `/dev/fd/1 main` and replaces it in the `/etc/zabbix/nginx.conf and /etc/zabbix/nginx_ssl.conf` with sed - like the other conf files do.

**Comment by rockaut** [comment]
Added proper description in readmes and example in `.env_web`.

This should also "open"/show the example how to further modify nginx configs.

**Comment by dotneft** [comment]
I would like to avoid possible issues with writing logs inside container. Why you can not limit container log data: https://docs.docker.com/config/containers/logging/configure/ ?

**Comment by dotneft** [comment]
For example, official docker image for Nginx: https://github.com/nginxinc/docker-nginx/blob/2ef3fa66f2a434cd5e44e35a02f4ac502cf50808/mainline/buster/Dockerfile

**Comment by rockaut** [comment]
I understand. What about this: if I change the variable to be an on/off switch instead a free-form string it would be way more restricting and headroom for errors is basically gone. I should have done this in the first place as you're absolutely right that my current implementation is too troublesome.

Also sorry for not providing background: Problem is we just don't use Docker at all so no log config here. But even if we might handle the log-size it still would be majority senseless access_log (for us) and even harder to find errors in the log at all.

**Comment by rockaut** [comment]
Changed

**Comment by dotneft** [comment]
Added!
