### ISSUE TITLE
Zabbix Web time is not displayed correctly

### ISSUE THREAD

**Issue by WinJayX** [zabbix/zabbix-docker#641]
Hello, the time displayed by my ZabbixWeb is inconsistent with my current time. I use the time zone of East Eight District and the time zone of Asia/Shanghai.
My Zabbix runs in Docker-compose mode. The "docker-compose_v3_centos_mysql_latest.yaml" file is used, and there are operations for mounting the time zone and time in this file.

but there is no this file in my centos7 system.

I want to ask, is the time displayed by my WebServer abnormal due to this file?
![1](https://user-images.githubusercontent.com/9602672/84216120-1d1a5680-aafb-11ea-8f78-4942395a0527.png)
![2](https://user-images.githubusercontent.com/9602672/84216126-21467400-aafb-11ea-84c7-5b7afad78b0b.png)

**Comment by dotneft** [comment]
do not attach it in this case :-) What is the problem?

**Comment by dotneft** [comment]
I think you need just specify correct PHP_TZ for web-interface container.
