### ISSUE TITLE
Error when using path in DB_SERVER_HOST (web)

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#647]
Seams like the entrypoint script doesn't escape sed expression.

```
sed: -e expression #1, char 21: unknown option to `s'
```

```
** Preparing Zabbix frontend configuration file
** Updating '/etc/php.d/99-zabbix.ini' parameter "max_execution_time": '600'...
** Updating '/etc/php.d/99-zabbix.ini' parameter "memory_limit": '128M'... updated
** Updating '/etc/php.d/99-zabbix.ini' parameter "post_max_size": '16M'...
** Updating '/etc/php.d/99-zabbix.ini' parameter "upload_max_filesize": '2M'... updated
** Updating '/etc/php.d/99-zabbix.ini' parameter "max_input_time": '300'...
** Updating '/etc/php.d/99-zabbix.ini' parameter "date.timezone": '"Europe/Vienna"'...
sed: -e expression #1, char 21: unknown option to `s'
** Cleaning the system
########################################################
```

**Comment by rockaut** [comment]
Is there a reason the pipe declaration isn't used for sed? Like: `-e "s|{DB_SERVER_HOST}|${DB_SERVER_HOST}|g" \` which seams to be the preferred way today?

If not I would provide an PR with it changed to this.

Background: I would like to use an volume/path for DB_SERVER_HOST connection to unix port for performance reasons.

**Comment by rockaut** [comment]
Or the more simpler way, would it be enough to escape_spec_char DB_SERVER_HOST in prepare_zbx_web_config too?

**Comment by dotneft** [comment]
What path do you use?

**Comment by rockaut** [comment]
`/tmp` as there the unix socket resides.

**Comment by dotneft** [comment]
Containers do not support path as socket, please, do not use it! Use network connection only.
