### ISSUE TITLE
zabbix/zabbix-web-apache-pgsql try to load MySQL

### ISSUE THREAD

**Issue by joshartman** [zabbix/zabbix-docker#648]
I have been using ver 4.0.18 of the above mentioned package and worked perfectly. When I upgraded to 4.0.21 it does not work at all anymore and the logfile shows it is compiled for MySQL. Is this correct ?

Looks like the MySQL version is packaged as the pgsql image.

------
```

zabbix-server-web_1  | ** Deploying Zabbix web-interface (Apache) with MySQL database
zabbix-server-web_1  | ********************
zabbix-server-web_1  | * DB_SERVER_HOST: postgres-server
zabbix-server-web_1  | * DB_SERVER_PORT: 5432
zabbix-server-web_1  | * DB_SERVER_DBNAME: zabbix
zabbix-server-web_1  | * DB_SERVER_SCHEMA: public
zabbix-server-web_1  | ********************
zabbix-server-web_1  | ** Adding Zabbix virtual host (HTTP)
zabbix-server-web_1  | **** Impossible to enable SSL support for Apache2. Certificates are missed.
zabbix-server-web_1  | ** Preparing Zabbix frontend configuration file
zabbix-server-web_1  | ** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "max_execution_time": '600'... updated
zabbix-server-web_1  | ** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "memory_limit": '128M'... updated
zabbix-server-web_1  | ** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "post_max_size": '16M'... updated
zabbix-server-web_1  | ** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "upload_max_filesize": '2M'... updated
zabbix-server-web_1  | ** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "max_input_time": '300'... updated
zabbix-server-web_1  | ** Updating '/etc/php7/conf.d/99-zabbix.ini' parameter "date.timezone": 'Etc/UTC'... added
zabbix-server-web_1  | ########################################################
zabbix-server-web_1  | ** Executing '/usr/sbin/httpd -D FOREGROUND'
zabbix-server-web_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
zabbix-server-web_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
zabbix-server-web_1  | [Wed Jun 10 16:13:51.676768 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.43 (Unix) PHP/7.3.17 configured -- resuming normal operations
zabbix-server-web_1  | [Wed Jun 10 16:13:51.676807 2020] [core:notice] [pid 1] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

```

**Comment by dotneft** [comment]
Is the problem still actual?

**Comment by joshartman** [comment]
Last time I tried to make it work it failed. I went back to 4.0.18 which is working 100%. I will try again when the release number is > 4.0.21.

**Comment by dotneft** [comment]
already released ) Please try!

**Comment by joshartman** [comment]
I am still having issues. When I use the 4.0.18 series I can login via the web and use Zabbix normal. When I use exactly the same running postgres and I change the version in the compose file from .18 to .22 and re-run it I cannot login via port 80 at all. I did the following:

1) Stop and down the .18 version
2) Did a prune of system, network and volume to clean out all older information
3) Change the version in the compose file for the image version to .22
4) Run the same compose up command as for .18

No error and I cannot login via the web page. When I try to telnet to the port 80 I get connection refused. If you want my compose files etc, let me know and I will somehow get it to you.

**Comment by dotneft** [comment]
Probably I know the reason, please, expose 8080 port instead of 80. Currently all images use non-privileged port numbers.

**Comment by joshartman** [comment]
Looks like when I expose my outside port to the inside 8080 it works. This makes me think that between .18 —> .22 it was moved from port 80 to 8080.

I would consider it in this case closed as it works when I expose the 8080.

Thank for your help in getting this to work.

**Comment by dotneft** [comment]
Thank you! I'm sorry that we did not document such significant change yet :-(
