### ISSUE TITLE
Zabbix server with agent - is it possible?

### ISSUE THREAD

**Issue by kbjm99u2** [zabbix/zabbix-docker#65]
Hello there,

I would like to monitor my zabbix server, but I can't do this, because the agent is missing from there. Is there any solution to patch it?

Thank you

**Comment by dotneft** [comment]
Hello!

What do you want to monitor in Zabbix server? 

Alexey.

**Comment by kbjm99u2** [comment]
Hi Alexey,

Himself as a Zabbix server service….
I can’t us zabbix server tempate…


Tamas Barina

**Comment by dotneft** [comment]
Template App Zabbix Server does not require agent. It uses only internal item type.

**Comment by kbjm99u2** [comment]
Hmmmm
It’s new info, let me check.

1.       I create a host

2.       And what’s the interface for the host, because I would like to link the template.
Or am I wrong?

Tamas Barina

**Comment by dotneft** [comment]
internal checks do not require interface. Feel free to add 127.0.0.1 interface (because there is impossible to create a host without interface).

**Comment by kbjm99u2** [comment]
Thank you for the reply, let me check….
But, if the agent is unreachable, then the zabbix server will disable this?

“Zabbix agent on Zabbix server is unreachable for 5 minutes”

Tamas Barina

**Comment by dotneft** [comment]
do not link other templates, only "Template App Zabbix server"

**Comment by kbjm99u2** [comment]
Yep I did this…Now I re-created and waiting for the data…


Tamas Barina

**Comment by kbjm99u2** [comment]
Yep,

Working… ☺
OMG I spent two days with this…. Build own docker image where the agent is inside…


Thanks for help….

Tamas Barina
