### ISSUE TITLE
zabbix/zabbix-proxy-sqlite3:alpine-latest invalid table name "interface_snmp"

### ISSUE THREAD

**Issue by fauust** [zabbix/zabbix-docker#650]
Hi!
Is it possible that the `zabbix/zabbix-proxy-sqlite3:alpine-latest` image is impacted by:
https://support.zabbix.com/browse/ZBX-17534
https://support.zabbix.com/browse/ZBX-17475

Using `zabbix/zabbix-proxy-sqlite3:ubuntu-latest` resolves the problem.
I have no time to investigate further but I may have more time in the next days to look into it.

```console
$ docker images | grep zabbix-proxy
zabbix/zabbix-proxy-sqlite3  ubuntu-latest  3bfc22feff2d  2 weeks ago  188MB
zabbix/zabbix-proxy-sqlite3  alpine-latest  be3a0c137e71  5 weeks ago  29.4MB
```

**Comment by fauust** [comment]
BTW, looking at a diff between `ubuntu/Dockerfile` and `alpine/Dockerfile`, I see references to MySQL (should be SQLite3):
https://github.com/zabbix/zabbix-docker/blob/5.0/proxy-sqlite3/ubuntu/Dockerfile#L3
https://github.com/zabbix/zabbix-docker/blob/5.0/proxy-sqlite3/ubuntu/Dockerfile#L7
https://github.com/zabbix/zabbix-docker/blob/5.0/proxy-sqlite3/ubuntu/Dockerfile#L35

**Comment by dotneft** [comment]
I do not think it is a problem, but must be fixed anyway :-) Thank you!

What is the problem with alpine? Any logs?

**Comment by dotneft** [comment]
Zabbix proxy creates SQLite database without any external files, so these difference are not related to the issue.

**Comment by fauust** [comment]
> I do not think it is a problem, but must be fixed anyway :-) Thank you!
No absolutely not. But yes, it would be cleaner...

**Comment by fauust** [comment]
> What is the problem with alpine? Any logs?
```console
zabbix-proxy_1  |    150:20200612:131111.943 received configuration data from server at "zabbix-proxy", datalen 3039473
zabbix-proxy_1  |    150:20200612:131111.949 failed to update local proxy configuration copy: invalid table name "interface_snmp"
```

**Comment by fauust** [comment]
So, the problem is a bit tricky to catch because it will occur only if you add new hosts to be monitored to the proxy...

**Comment by fauust** [comment]
Ok so it seems that I was not using the latest image `3cf7d0fe530b` !
Sorry for that.
