### ISSUE TITLE
$DB['DOUBLE_IEEE754'] setting in web

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#653]
Currently the new setting for double precission db is set to static true in web-containers zabbix.conf.php

```php
$DB['DOUBLE_IEEE754']	= true;
```

Does that mean we are NOT able to use a web-container in combination with, let's say, <= Postgres 12  ? That would be bad. Why not making this editable as all other variables in this file?

I'm currently in the process to upgrade to v5.0.x comming from 4.4. Until now we had an package-installation of all components and the PG DB is a managed service so we don't have full controll there.
Now with 5 we want to go containers all-in but this would be a blocker as I see it currently? (Yeah I know we can build the container as we wish or sideload the file... but that's not the point)

**Comment by dotneft** [comment]
Fixed!
