### ISSUE TITLE
PostgreSQL  server is not available. Waiting 5 seconds...

### ISSUE THREAD

**Issue by gorsing** [zabbix/zabbix-docker#659]
**** PostgreSQL server is not available. Waiting 5 seconds...
Ploblems on CentOS 8.1 minimal in all docker-compose files:

docker-compose_v3_alpine_pgsql_latest.yaml
docker-compose_v3_centos_pgsql_latest.yaml
docker-compose_v3_ubuntu_pgsql_latest.yaml

**Comment by gorsing** [comment]
![Выделение_035](https://user-images.githubusercontent.com/3708084/84885442-b9b09b80-b09b-11ea-8894-1994032d1e2d.png)

**Comment by gorsing** [comment]
This is default start
selinux off
firewall off

**Comment by dotneft** [comment]
Is docker officially supported on CentOS 8?

**Comment by rockaut** [comment]
Well RedHat does it's best to do not so and as far as I understood it will not get support by docker also.

But we're running the containers in production with podman (as systemd service) without problems (well beside the PRs/and Issues I've thrown in). So if that is a possible way @gorsing try it.

**Comment by rockaut** [comment]
Actually @gorsing ... have you tried to remove podman and all dependencies? I can't find it currently but I think I came across some issues if those are installed beside docker.

**Comment by dotneft** [comment]
Anyway, compose is not fully supported on CentOS 8. But it is possible to use images with podman without any issues.

**Comment by sethsimmons** [comment]
For future visitors, you can fix this issue in CentOS 8 via:

`firewall-cmd --zone=public --add-masquerade --permanent`

Source: https://serverfault.com/questions/987686/no-network-connectivity-to-from-docker-ce-container-on-centos-8
