### ISSUE TITLE
How can I continue to using zabbix images

### ISSUE THREAD

**Issue by erikbotta** [zabbix/zabbix-docker#66]
Hello. I was using zabbix in my docker image this way:

**FROM zabbix/zabbix-3.0:latest**

But after 2 months I need to rebuild it and getting:

**Build failed: Error: image zabbix/zabbix-3.0:latest not found**

Is there any howto for migrating to new docker images from old ones?

**Comment by jangaraj** [comment]
That your old one, community one is still live - it has been moved to https://github.com/monitoringartist/zabbix-xxl
