### ISSUE TITLE
agent docker-entrypoint.sh doesn't handle DenyKey & AllowKey

### ISSUE THREAD

**Issue by fmax** [zabbix/zabbix-docker#662]
`docker-entrypoint.sh` do not handle `DenyKey` & `AllowKey`
so if you use ENV variables to configure those options:
```
ZBX_DENYKEY=system.run[*]
ZBX_ALLOWKEY=system.run[/usr/local/share/zabbix/externalscripts/*]
```
they won't take effect and as per default config `DenyKey=system.run[*]` is set, you will fail to get any 
`system.run` executed.

**Comment by dotneft** [comment]
Hmm... sounds reasonable, the problem related to too complicated syntax. We have env variables you can specify multiple DenyKey and AllowKey entries. So how does handle such situation. I'm thinking to remove default DenyKey=system.run[*].

**Comment by dotneft** [comment]
Added. Thank you!
