### ISSUE TITLE
Docker image zabbix-appliance:centos-4.0-latest not working

### ISSUE THREAD

**Issue by zeduperes** [zabbix/zabbix-docker#663]
The "docker image zabbix/zabbix-appliance:centos-4.0-latest" is not working...

I used the command:
```
docker run --name zabbix-appliance -p 80:80 -p 10051:10051 -d zabbix/zabbix-appliance:centos-4.0-latest
```

I'm getting the errors:
200625  5:53:54 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
200625  5:53:54 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.host' doesn't exist
**** MySQL server is not available. Waiting 5 seconds...

*I use the docker zabbix-appliance images for testing purposes...

**Comment by dotneft** [comment]
Please use regular docker images, do not use appliance!

**Comment by zeduperes** [comment]
> Please use regular docker images, do not use appliance!

Sure!, I’m always using regular docker images, I use appliance for testing purposes as it’s supposed for.
