### ISSUE TITLE
database is not a Zabbix database

### ISSUE THREAD

**Issue by wilianuhlmann** [zabbix/zabbix-docker#664]
I have a error in create zabbix-server-pgsql:
6:20200629:020757.415 using configuration file: /etc/zabbix/zabbix_server.conf
     6:20200629:020757.419 [Z3005] query failed: [0] PGRES_FATAL_ERROR:ERROR:  relation "users" does not exist
LINE 1: select userid from users limit 1
                           ^
 [select userid from users limit 1]
     6:20200629:020757.420 cannot use database "zabbix_pwd2": database is not a Zabbix database

**Comment by DawidStankiewicz** [comment]
I had similar issue on docker image zabbix-proxy-sqlite3:ubuntu when I tried too fast restart container after docker run. I guess that in my case DB initiation was interrupted and that caused errors.

**Comment by dotneft** [comment]
Yes, probably DB schema is not fully filled (
