### ISSUE TITLE
Is zabbix-appliance discontinued

### ISSUE THREAD

**Issue by BGmot** [zabbix/zabbix-docker#666]
The latest image at registry.connect.redhat.com is 4.4.8.
Documentation here https://github.com/zabbix/zabbix-docker/tree/5.0/zabbix-appliance/rhel is misleading, mentions Ubuntu and Alpine images that don't even exist in 5.0 branch.
Failed to build using this Docker file too https://github.com/zabbix/zabbix-docker/blob/5.0.1/zabbix-appliance/rhel/Dockerfile

**Comment by dotneft** [comment]
Completely! But RedHat version is not discontinued. It will be updated very very soon :-)
