### ISSUE TITLE
Update image tags on docker hub

### ISSUE THREAD

**Issue by andrazjelenc** [zabbix/zabbix-docker#667]
Hello.

On [https://hub.docker.com/r/zabbix/zabbix-server-pgsql](https://hub.docker.com/r/zabbix/zabbix-server-pgsql) the tag **alpine-5.0-latest** still points to some old image although the tag **latest** is updated.

Shouldn't these tags be synchronised?

Thanks!

**Comment by dotneft** [comment]
Looks like you are correct, but others are correct. I suppose some issue with auto-build. I disabled caching, lets check :-)

**Comment by dotneft** [comment]
Fixed!
