### ISSUE TITLE
zabbix-proxy-sqlite3 oom

### ISSUE THREAD

**Issue by yadangsmith** [zabbix/zabbix-docker#669]
zabbix proxy often is killed by k8s for oom when sync configure data from server .
zabbix-proxy resource limit 4G,2cpu in k8s , and zabbix server only 3000 host，and 600 itmes per host, is the sqlite3 cant't suport so many hosts and items or proxy configure problem ( the parameter CacheSize is 1024mb)  ?

**Comment by dotneft** [comment]
Hello! I'm sorry but it is more configuration question about Zabbix, it is not related to Zabbix images. I recommend you check our forum https://www.zabbix.com/forum/.

But generally, yes, SQLite3 is designed for 1000-1400 NVPS max.
