### ISSUE TITLE
zabbix-server: bug on postgresql server availibility test since 4.0.22

### ISSUE THREAD

**Issue by simplerezo** [zabbix/zabbix-docker#672]
Since commit https://github.com/zabbix/zabbix-docker/commit/e1abf0b3071c13ecb2661c98d186966d6c3abeb3, we cannot use zabbix-server dockerfile, because of this update:
```
-     while [ ! "$(psql -h ${DB_SERVER_HOST} -p ${DB_SERVER_PORT} -U ${DB_SERVER_ROOT_USER} -d ${DB_SERVER_DBNAME} -l -q 2>/dev/null)" ]; do
+     while [ ! "$(psql --host ${DB_SERVER_HOST} --port ${DB_SERVER_PORT} --username ${DB_SERVER_ROOT_USER} --list --quiet 2>/dev/null)" ]; do
```

I don't know if it's intentional or not but on on the new line the database is not specified anymore (missing "--dbname ${DB_SERVER_DBNAME}")... and because we are using a postgresql cloud service, connect to "postgresql" (default database) is not allowed, so the test fails despite postgresql is available...

**Comment by dotneft** [comment]
I see, the problem could be if db schema is not created yet. In this case ${DB_SERVER_DBNAME} can produce different error. What error do you have if use the current command?

**Comment by simplerezo** [comment]
No. DB schema is already created, since it was an error created on an update.
Without DB specified:
psql: FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.

And my user cannot have CONNECT privilege on postgres... but has full privileges on my ${DB_SERVER_DBNAME} ...

(for now i have reverted image to 4.0.21 with the same docker-compose.yml file and its working again)

**Comment by dotneft** [comment]
Ok. Thank you for the information! We will fix it soon!

**Comment by dotneft** [comment]
I hope I fixed that. Actually very strange behaviour of PostgreSQL, it does not allow to connect to DB without database name...

**Comment by dotneft** [comment]
Can anybody test tomorrow new images?

**Comment by simplerezo** [comment]
Sorry for the delay. Tested today, it works!
