### ISSUE TITLE
unable to set up docker monitoring using zabbix 5.0

### ISSUE THREAD

**Issue by lastwon1216** [zabbix/zabbix-docker#675]
I have recently upgraded to Zabbix 5.0.1 to monitor docker and installed zabbix-agent on a docker server. However, I am into a bit of an issue with errors as following:

Zabbix Version: 5.0.1
Zabbix server IP: 10.200.140.70
Docker server IP: 10.200.140.65

/etc/zabbix/zabbix_agentd.conf:

```
Server=10.200.140.70
ServerActive=10.200.140.70
Hostname=docker
```

```
[root@docker:/root]# zabbix_get -s 127.0.0.1 -k docker.info
zabbix_get [904]: Check access restrictions in Zabbix agent configuration
```
```
[root@zabbix:/root]# zabbix_get -s 10.200.140.65 -k docker.info
ZBX_NOTSUPPORTED: Cannot fetch data.
```
Please let me know if any additional information is required.

**Comment by dotneft** [comment]
Your issue is not related to images. It is configuration issue. You request item key from localhost, while you have allowed 10.200.140.70 host only.

**Comment by lastwon1216** [comment]
@dotneft I am sorry about the confusion, the /etc/zabbix/zabbix_agentd.conf is actually from the docker server.

**Comment by dotneft** [comment]
Are you able to fetch information from Zabbix server using the following command:
```
zabbix_get -s 10.200.140.65 -k agent.version
```

**Comment by lastwon1216** [comment]
Yes, I am able to fetch information as following:

```
[root@zabbix:/root]# zabbix_get -s 10.200.140.65 -k agent.version
5.0.2
```

**Comment by dotneft** [comment]
In this case I think the issue is related to Docker monitoring, not docker images issue. I recommend you check the following report: https://support.zabbix.com/browse/ZBX-17632

**Comment by lastwon1216** [comment]
@dotneft I really did a lot of research before creating a ticket here and tried your suggestion before, but had no luck..
As I mentioned before docker and zabbix are on different servers, do I have to additionally install zabbix tools other than zabbix-agent2 on docker server?

 ```
[root@docker:/root]# rpm -qa | grep zabbix
zabbix-agent2-5.0.2-1.el7.x86_64
zabbix-release-5.0-1.el7.noarch
zabbix40-4.0.17-1.el7.x86_64
```

**Comment by lastwon1216** [comment]
zabbix tools on zabbix server
```
[root@zabbix:/root]# rpm -qa | grep zabbix
zabbix-get-5.0.1-1.el7.x86_64
zabbix-web-5.0.1-1.el7.noarch
zabbix-web-deps-scl-5.0.1-1.el7.noarch
zabbix-release-5.0-1.el7.noarch
zabbix-web-mysql-scl-5.0.1-1.el7.noarch
zabbix-agent2-5.0.1-1.el7.x86_64
zabbix-agent-5.0.1-1.el7.x86_64
zabbix-apache-conf-scl-5.0.1-1.el7.noarch
zabbix-server-mysql-5.0.1-1.el7.x86_64
zabbix-java-gateway-5.0.1-1.el7.x86_64
```

**Comment by dotneft** [comment]
Sorry, the repository you are writing is related to Zabbix docker images, not Docker **monitoring**. Please check https://zabbix.com/forum/
