### ISSUE TITLE
Change timeout on a running zabbix server container

### ISSUE THREAD

**Issue by jividijuvent** [zabbix/zabbix-docker#678]
Hi, I have a Zabbix 5 monitoring on 3 separate containers for DB and web and server. I didn't mention the "ZBX_TIMEOUT" env on docker-compose but now I need to change it and I prefer not to recreate the containers, is there any way to change it that? I have lots of hosts and configurations.

**Comment by dotneft** [comment]
Just change and restart container with new env variables. You do not need to recreate them.

**Comment by jividijuvent** [comment]
> Just change and restart container with new env variables. You do not need to recreate them.
change what and where? add env in the docker-compose file and docker-compose restart?

**Comment by dotneft** [comment]
Add env in the docker-compose file and docker-compose restart :-)

**Comment by jividijuvent** [comment]
Thanks, I'll close the issue and check it.
