### ISSUE TITLE
zabbix-web-nginx-mysql:5.0.2 session folder incorrect

### ISSUE THREAD

**Issue by jahrensnv** [zabbix/zabbix-docker#679]
The php session folder is created as `/var/lib/php/session` inside the container. PHP expects it to be `/var/lib/php/sessions` and returns the error `Cannot create session.` on the web-ui. 

Since the path is ephemeral, I had to work around it by creating a user with uid/gid = 1997/1995 on host and bind mounting a sessions folder `-v <host dir>/sessions:/var/lib/php/sessions`.

**Comment by dotneft** [comment]
Hello!

What image do you use? Please specify exact one.

**Comment by jahrensnv** [comment]
`zabbix/zabbix-web-nginx-mysql:centos-5.0.2`
`sha256:82750c997f468ede562100cbe74433732a5e149233f6c277391c267df34c79c6`

**Comment by dotneft** [comment]
Sorry, but I can not confirm the problem:
```
# docker inspect --format '{{.Config.Image}}' zabbix-docker_zabbix-web-nginx-mysql_1
zabbix/zabbix-web-nginx-mysql:centos-5.0.2
# docker exec -ti zabbix-docker_zabbix-web-nginx-mysql_1 cat /etc/php-fpm.d/zabbix.conf | grep session
php_value[session.save_handler] = files
php_value[session.save_path]    = /var/lib/php/session
# docker exec -ti zabbix-docker_zabbix-web-nginx-mysql_1 ls -lah /var/lib/php | grep session
drwxrwx---. 1 zabbix root   4.0K Jul 21 16:52 session
```
What is difference?

**Comment by jahrensnv** [comment]
Should be `sessions`, not `session`.

**Comment by dotneft** [comment]
why？

**Comment by jahrensnv** [comment]
![Screenshot from 2020-07-21 16-05-41](https://user-images.githubusercontent.com/34585340/88107244-61722b00-cb6c-11ea-96c8-4ccfc2c5db57.png)

I apologize `sessions` is a red-herring. Bind-mounting over `/var/lib/php/session` does it fix it though.

**Comment by dotneft** [comment]
Yes, in this case I agree with you :-) But I surprised that /var/lib/php/session does not fix the issue. I also surprised that you have such problem at all! Zabbix container does not use /var/lib/php/sessions ... What page did you try to open when you have such issue? What params did you use to run the container?

**Comment by jahrensnv** [comment]
Docker run command: 
```
docker run --rm \
--cpuset-cpus 1-15 \
--env-file /zabbix/server/zabbix_ui.env \
-v /var/log/zabbix:/var/log/zabbix \
-v /zabbix/ui/sessions:/var/lib/php/session \
-p 80:8080 \
-p 8080:8080 \
-p 443:8443 \
-p 8443:8443 \
--hostname zabbix-ui \
--name %n \
zabbix-web-nginx-mysql:5.0.2
```

env file:
```
ZBX_SERVER_HOST=zabbixsrv00
ZBX_SERVER_PORT=80
DB_SERVER_HOST=zabbixdb00
MYSQL_USER=******
MYSQL_PASSWORD=*******
PHP_TZ=UTC
ZBX_SERVER_NAME=zabbixsrv00
ZBX_MAXEXECUTIONTIME=300
ZBX_MEMORYLIMIT=512M
ZBX_POSTMAXSIZE=16M
ZBX_UPLOADMAXFILESIZE=2M
ZBX_MAXINPUTTIME=300
```

**Comment by dotneft** [comment]
Stop... you told about centos image, but zabbix-web-nginx-mysql:5.0.2 is not CentOS :-) We do not have zabbix-web-nginx-mysql:5.0.2 at all in hub.docker.com: https://hub.docker.com/repository/docker/zabbix/zabbix-web-nginx-mysql/tags?name=5.0.2&page=1

**Comment by jahrensnv** [comment]
I retagged it for our internal repo. Same SHA

**Comment by dotneft** [comment]
Got it! What page did you try to open when you have such issue?

**Comment by dotneft** [comment]
+ you specified:
```
-v /zabbix/ui/sessions:/var/lib/php/session \
```
what means that you mount /var/lib/php/session. But you told you tried that and it does not work, only /var/lib/php/sessions in the container help to avoid the error. Hm?

**Comment by jahrensnv** [comment]
Just going to the default page http://zabbixui00/. 

I apologize again for the mistake at the beginning. I had bind-mounted over both `/var/lib/php/session` and `/var/lib/php/sessions` initially. Only bind-mounting over `/var/lib/php/session` is necessary.

**Comment by dotneft** [comment]
No problem :-) Just an idea, recently we faced the same issue with one user. What OS do you use and what kernel do you use?

**Comment by jahrensnv** [comment]
```
Linux zabbixui00 4.4.216-1.el7.elrepo.x86_64 #1 SMP Wed Mar 11 09:13:43 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.8.2003 (Core)
```

**Comment by dotneft** [comment]
Yeah! Looks like the same issue like #670. Please check it!
