### ISSUE TITLE
FR: add curl & ca-certificates packages

### ISSUE THREAD

**Issue by Blasterdick** [zabbix/zabbix-docker#68]
To work with [slack](https://github.com/ericoc/zabbix-slack-alertscript) alert script it would be great to have those packages installed.

**Comment by dotneft** [comment]
I'm not sure that is a good idea. Images are provided clean, without any additional packages. Feel free to build your own images based on official images with any additional changes.

**Comment by KostyaEsmukov** [comment]
@dotneft , while I agree that adding extra packages would harm the cleanness of images, I want to note that some (maybe a lot?) of the people using Zabbix for alerts might need these 2 packages.

It's certainly possible for us, the users, to make and maintain our own images of zabbix, but that's a lot of hassle for just two small packages, which, being in the image, will not harm it in any way but a cleanness.
