### ISSUE TITLE
zabbix active proxy reload configuration cache runtime command via docker

### ISSUE THREAD

**Issue by RipperSK** [zabbix/zabbix-docker#681]
Is there a simple way to reload configuration cache when running zabbix proxy in docker container ?

**Comment by dotneft** [comment]
zabbix_server -R config_cache_reload is only one way.

**Comment by RipperSK** [comment]
ok I guess you can close the issue
will use `docker exec - it` for this purpose

**Comment by RipperSK** [comment]
fixed by workaround
