### ISSUE TITLE
How to migrate from zabbix 4.4.10 to zabbix 5.

### ISSUE THREAD

**Issue by gorsing** [zabbix/zabbix-docker#682]
How to migrate from zabbix 4.4.10 to zabbix 5, infrastructure deployed in docker. Is there a step-by-step instruction somewhere?

**Comment by dsteinkopf** [comment]
I my case I just pulled the new image versions and did `docker-compose up -d`.

**Comment by dotneft** [comment]
Absolutely correct!

docker-compose pull
docker-compose up -d

**Comment by gorsing** [comment]
thank
