### ISSUE TITLE
where can i get mysql-connector-odbc for alpine-latest image?

### ISSUE THREAD

**Issue by qwzhou89** [zabbix/zabbix-docker#685]
I am using ODBC monitoring  in zabbix ,but where can i get mysql-connector-odbc for zabbix/zabbix-server-mysql:alpine-latest image?
or i must use a non-alpine image?

**Comment by dotneft** [comment]
It looks like Alpine do not have MySQL odbc connector. I think you need to use different image.

**Comment by qwzhou89** [comment]
> It looks like Alpine do not have MySQL odbc connector. I think you need to use different image.

Thanks a lot.
I'm trying a lot of methods,such as bulid from mysql-connector-odbc src,install with command
"apk add mysql-connector-odbc --update-cache --repository http://dl-4.alpinelinux.org/alpine/edge/testing/ --allow-untrusted",they are all failed。
now i am using ubuntu-latest instead ，and it works well.

**Comment by luiszaelot** [comment]
RUN apk add mariadb-connector-odbc --update-cache --repository http://dl-4.alpinelinux.org/alpine/edge/testing/ --allow-untrusted

**Comment by LuchoLopez** [comment]
I had created my own image using docker file:

Dockerfile:
```
from zabbix/zabbix-server-mysql:alpine-latest
USER root
RUN apk update
RUN apk add gcc libc-dev g++ libffi-dev libxml2 unixodbc-dev mariadb-dev
RUN apk add mariadb-connector-odbc --update-cache --repository http://dl-4.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
RUN echo -e "[mysql]\nDescription = ODBC for MySQL\nDriver = /usr/lib/mariadb/libmaodbc.so" > /etc/odbcinst.ini
```
Notice that the driver is installed in `/usr/lib/mariadb/libmaodbc.so` by the `mariadb-connector-odbc` package

You should be able to use Database Monitor items setting the Driver=/usr/lib/mariadb/libmaodbc.so parameter.

That worked for me :smile: 

Cheers from Uruguay! :uruguay:
