### ISSUE TITLE
Add custom packages with apt ?

### ISSUE THREAD

**Issue by zab35** [zabbix/zabbix-docker#689]
Hello,

Is-it possible to add an environnement var for install package with apt ?
My custom script use unavailable command in ubuntu template.

For the zabbix-proxy

Thanks

**Comment by rockaut** [comment]
I wouldn't advise to do such a thing. This might get you in more troubles than you think.
What if one of the additional apts incorporates libs or whatever which breaks the default functionality?

The better way to do this is with your own image! Like so (not working

```yaml
FROM zabbix/zabbix-proxy-sqlite3:latest

RUN apk add --clean-protected --no-cache \
    whateveryouneed \
    rm -rf /var/cache/apk/*
```

Put it in your own github repo, login to hub.docker.com and set up an automated build. Then just pull your own images.
This way you could even automate updates as if zabbix-proxy get's a new build your image can also be automaticalle be build base on this new image.

**Comment by rockaut** [comment]
The other way would be to just clone the specific Docker files and modify them to your wishes. Thought you might loose track to on newer versions over time (like I did for my repo I linked above. It was only for patching some bugs back then for a small amount of time).

**Comment by zab35** [comment]
Thank you for your feedback.
I have already tested that with ubuntu version.
There is a permission problem because the zabbix user is limited

I have the same problem with alpine:

```
admincloud@Ubuntu:~/zabbix-proxy-sqlite3$ sudo docker-compose up --build -d
Building zabbix-proxy-sqlite3
Step 1/2 : FROM zabbix/zabbix-proxy-sqlite3:latest
 ---> a2a230c291d1
Step 2/2 : RUN apk add --clean-protected --no-cache     python-novaclient     rm -rf /var/cache/apk/*
 ---> Running in ca06d504d5b5
apk: unrecognized option: r
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
ERROR: Service 'zabbix-proxy-sqlite3' failed to build: The command '/bin/sh -c apk add --clean-protected --no-cache     python-novaclient     rm -rf /var/cache/apk/*' returned a non-zero code: 99
```

**Comment by rockaut** [comment]
That is because of rootless containers - which is needed nowadays for secure kubernetes!
You need to switch to user root and don't forget to switch back in the end. Look at the base Dockerfiles!

```docker
FROM zabbix/zabbix-proxy-sqlite3:latest
USER root
RUN apk add --clean-protected --no-cache python-novaclient && \
        rm -rf /var/cache/apk/*
USER 1997
```

**Comment by rockaut** [comment]
If you are done with this and it's working for you, do @dotneft a favour and close this issue yourself ;-)

**Comment by zab35** [comment]
It works, thank you :)
