### ISSUE TITLE
How memory increases - Error status code 500

### ISSUE THREAD

**Issue by wilianuhlmann** [zabbix/zabbix-docker#690]
Hi,
I'm trying to increase the memory in web-nginx-pgsql (/etc/php/7.2/fpm/pool.d/zabbix.conf)
php_value[max_execution_time]=900
php_value[memory_limit]=128M
php_value[post_max_size]=16M
php_value[upload_max_filesize]=2M
php_value[max_input_time]=300 
But when I change and restart the container it returns to the default value.
I'm trying to do this because in zabbix when trying to import a large number of hosts the browser returns me error 500.
Few host successfully imports
POST 
scheme| http
host | 192.168.1.185:8081
filename | /conf.import.php
 Address | 192.168.1.185:8081
Status| 500 Internal Server Error

**Comment by fpaternot** [comment]
Use enviroment variables to customize it.

They are documented at https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql (or pgsql)
