### ISSUE TITLE
Install Traditional Chinese language pack, but no locale

### ISSUE THREAD

**Issue by turtlechang** [zabbix/zabbix-docker#693]
use docker image:  zabbix/zabbix-web-apache-mysql:centos-5.0.0

I execute the following command
```no-highlight
yum install kde-l10n-Chinese
yum reinstall glibc-common
```
But
```no-highlight
locale -a
```
there is no zh_TW anyway !
please help!
thinks!

**Comment by turtlechang** [comment]
You are not able to choose some of the languages, because locales for them are not installed on the web server.
![image](https://user-images.githubusercontent.com/51768222/89988182-b871a880-dcb1-11ea-869b-d962ba6caee9.png)

**Comment by turtlechang** [comment]
I successfully solved!!

Step 1:
Install the glibc-common.x86_64 package.
```
yum install -y glibc-common.x86_64
```

Step 2:
Install langpacks-zh_TW.noarch Traditional Chinese language pack.
```
yum install -y langpacks-zh_TW.noarch
```

Step 3:
Check if there are zh_TW, zh_TW.euctw, zh_TW.utf8 languages, etc.
```
locale -a | grep zh_TW

zh_TW
zh_TW.euctw
zh_TW.utf8
```

Step 4:
Restart the Apache web server to make the changes to Traditional Chinese take effect
```
apachectl -k restart
```

**Comment by turtlechang** [comment]
~bug

**Comment by turtlechang** [comment]
![image](https://user-images.githubusercontent.com/51768222/90750764-d9687800-e307-11ea-8d73-ecb0f9eaa4aa.png)

**Comment by dotneft** [comment]
I just checked 5.0.3 and Chinese is available without any additional modifications. Could you check that?

**Comment by turtlechang** [comment]
Ok, let me try and thank you for your reply.

**Comment by turtlechang** [comment]
I changed the image version to "zabbix/zabbix-web-apache-mysql:centos-5.0.3" and an error message still appears.
![註解 2020-08-27 094628](https://user-images.githubusercontent.com/51768222/91374240-5c2e8d00-e84a-11ea-9966-193b43967169.png)

**Comment by dotneft** [comment]
I can not reproduce that. What host OS do you use?
<img width="560" alt="Screenshot 2020-08-27 at 10 38 33" src="https://user-images.githubusercontent.com/10911965/91411761-7881f800-e851-11ea-82a5-d29bcb58ce0b.png">

**Comment by turtlechang** [comment]
Thanks for your reply,

My VMware is using  **CentOS 7.8**  system.

Because there is no Chinese (zh_TW) option after zabbix web is installed by default.

So I modified it in the  **locales.inc.php**  file.
```
/usr/share/zabbix/include/locales.inc.php
```

I turn on the **Traditional Chinese** option.
```
'zh_TW' => ['name' => _('Chinese (zh_TW)'),	'display' => true]
```
After that, the **Chinese(zh_TW)** option appears and cannot be selected.😂

**Comment by dotneft** [comment]
Ahh... we are talking about zh_TW and zh_CN. Sorry. Actually if it is not enabled, it means it is not officially translated and probably contains incorrect/unverified/not full translation. Sorry, but it is not docker images issue, it is Zabbix frontend configuration. So according https://www.zabbix.org/pootle/zh_TW/Zabbix-5.0/ it is translated just for 50%. You can help to translate it to Taiwanese if you want :-)

**Comment by turtlechang** [comment]
I understand, thank you for your reply, I will try to translate it later.
If the traditional Chinese translation is completed, can you please open it?

**Comment by dotneft** [comment]
Yes, sure! You need to follow the procedure: https://www.zabbix.org/wiki/Translating_Zabbix
