### ISSUE TITLE
How to monitor host using zabbix agent container and add host to the zabbix portal ? 

### ISSUE THREAD

**Issue by Syed-Saifulla** [zabbix/zabbix-docker#695]
How do I add the Zabbix agent container which is running on the host to the Zabbix server running as service in a separate machine via the portal?
A- Zabbix server with os service
B- Zabbix agent running as a container on Host.
If adding is possible then how Zabbix server sends a list of items to the agent container?
Please let us know the procedure to do

**Comment by dotneft** [comment]
Thank you for your response!
