### ISSUE TITLE
Minor documentation update - zabbix/zabbix-web-nginx-pgsql

### ISSUE THREAD

**Issue by trahman-hm** [zabbix/zabbix-docker#699]
Hello,

In the section where the /etc/ssl/nginx configuraiton is listed, there is a statement:

"The volume must contains two files ssl.crt, ssl.key and dhparam.pem prepared for Nginx SSL connections."

Is this correct or should it state that "The volume must contain three files ssl.crt, ssl.key and dhparam.pem ..."

I tried to start the server with just ssl.crt and ssl.key placed into a mounted volume but the Zabbix SSL option did not work for me until I also generated and added the dhparam.pem file as well.

**Comment by dotneft** [comment]
Fixed! Thank you!
