### ISSUE TITLE
Does the zabbix-docker images work with docker engine swarm mode?(1.12+)

### ISSUE THREAD

**Issue by hamburml** [zabbix/zabbix-docker#70]
Hi!

We want to use docker's new engine swarm mode (1.12+) and the zabbix images. My docker swarm runs currently:

DockerName : DockerImage : DockerNetwork : publicports
zabbix-postgres : postgres:9.6.1-alpine : zabbix-network : none
zabbix-server : zabbix/zabbix-server-pgsql:alpine-3.2-latest : zabbix-network : none
zabbix-web : zabbix/zabbix-web-nginx-pgsql:alpine-3.2-latest : zabbix-network : 80:80
zabbix-agent : zabbix/zabbix-agent:alpine-3.2-latest : zabbix-network : none

The zabbix-agent has a constraint so that it always run on a special node (the docker swarm manager).

Zabbix-server starts, creates db schema, I can login and add hosts. The fact that the running docker images are all inside the same docker networks also means that they can reach each other via DockerName.

Now I try to add the running **zabbix-agent** as a host to the **zabbix-server** (which is the same physical machine btw). Therefore I changed the Agent interface from ip address to dns name zabbix-agent, switched to dns and updated the zabbix-agent host. After enabling the host I get the following error in the web interface.

_Received empty response from Zabbix Agent at [zabbix-agent]. Assuming that agent dropped connection because of access permissions._

When printing the zabbix-agent logs I see the following errors:

    57:20161128:105614.513 no active checks on server [zabbix-server:10051]: host [5cafc50bc2b6] not found
    55:20161128:105652.359 failed to accept an incoming connection: connection from "10.0.0.6" rejected, allowed hosts: "zabbix-server"
    54:20161128:105752.426 failed to accept an incoming connection: connection from "10.0.0.6" rejected, allowed hosts: "zabbix-server"
    57:20161128:105814.586 no active checks on server [zabbix-server:10051]: host [5cafc50bc2b6] not found
    54:20161128:105852.491 failed to accept an incoming connection: connection from "10.0.0.6" rejected, allowed hosts: "zabbix-server"
    56:20161128:105952.561 failed to accept an incoming connection: connection from "10.0.0.6" rejected, allowed hosts: "zabbix-server"
    57:20161128:110014.660 no active checks on server [zabbix-server:10051]: host [5cafc50bc2b6] not found
    55:20161128:110052.632 failed to accept an incoming connection: connection from "10.0.0.6" rejected, allowed hosts: "zabbix-server"
    54:20161128:110152.701 failed to accept an incoming connection: connection from "10.0.0.6" rejected, allowed hosts: "zabbix-server"
    57:20161128:110214.730 no active checks on server [zabbix-server:10051]: host [5cafc50bc2b6] not found

But here you can see that the host with the container id 5cafc50bc2b6 is running.

![image](https://cloud.githubusercontent.com/assets/7239350/20666108/e6b81172-b562-11e6-8547-b52944799221.png)

What am I doing wrong? Any help? Thanks!

**Comment by Michael-Hamburger** [comment]
**Update**

Looks like this has something to do with the virtual ip which is used when using docker engine in swarm mode. The docker service inspect <containerName> command displays the virtual-ip which is used for load balancing. The virtual-ip distributes the incoming requests to the running containers of that service.

**Comment by dotneft** [comment]
ok :)
