### ISSUE TITLE
zabbix-agent2 version 5.0.3 won't start

### ISSUE THREAD

**Issue by x-jokay** [zabbix/zabbix-docker#700]
Hello

When trying to start the [zabbix/zabbix-agent2:alpine-5.0.3](https://hub.docker.com/layers/zabbix/zabbix-agent2/alpine-5.0.3/images/sha256-54bb647402b23d4d3a492fde41832b29ec53f643bc9ef1bb7d9212bfbc39c77b?context=explore) the following error occurs:

```sh
zabbix_agent2 [6]: ERROR: Cannot assign configuration: invalid parameter LoadModulePath at line 587: unknown parameter
```

This are the environment params which are set:

```yml
environment:
  - TZ=Europe/Zurich
  - ZBX_HOSTNAME=sample_host
  - ZBX_SERVER_HOST=192.168.1.123
  - ZBX_TLSCONNECT=psk
  - ZBX_TLSACCEPT=psk
  - ZBX_TLSPSKIDENTITY=sample_identity
  - ZBX_TLSPSKFILE=sample_psk
```

`zabbix/zabbix-agent2:alpine-5.0.2` works.

**Comment by dotneft** [comment]
Fixed! Thank you!
