### ISSUE TITLE
Volume layers on 4.0 images

### ISSUE THREAD

**Issue by zopar** [zabbix/zabbix-docker#701]
Hi
In 4.0 dockerfile does not contains volumes /usr/lib/zabbix/alertscripts but the image still continue to contains the volumes
This create problem like this issue  #568

docker history zabbix/zabbix-server-mysql:alpine-4.0.22 |grep VOL
<missing>           8 weeks ago         /bin/sh -c #(nop)  VOLUME [/var/lib/zabbix/e…   0B
<missing>           8 weeks ago         /bin/sh -c #(nop)  VOLUME [/var/lib/zabbix/s…   0B
<missing>           8 weeks ago         /bin/sh -c #(nop)  VOLUME [/usr/lib/zabbix/a…   0B

In the latest image we have only this
docker history zabbix/zabbix-server-mysql:latest |grep VOL
<missing>           28 hours ago        /bin/sh -c #(nop)  VOLUME [/var/lib/zabbix/s…   0B

**Comment by dotneft** [comment]
Because 4.0.22 is quite old. Please check 4.0.24.

**Comment by zopar** [comment]
Hi
I confirm that 4.0.24 is ok

Regards
Armando
