### ISSUE TITLE
Problem with zabbix-agent and docker deploiement

### ISSUE THREAD

**Issue by STYNET** [zabbix/zabbix-docker#703]
Hello,

I am testing Zabbix 5.0 via the Docker deployment

Here is the command I use:

`docker-compose -f ./docker-compose_v3_alpine_mysql_latest.yaml up -d`

Everything works fine, except for Zabbix-agent

On the "Dashbord", the error messages are:
**Zabbix agent is not available (for 3m)
For passive only agents, host availability is used with 3m as time threshold.**

I consult the logs of zabbix-agent:
`docker logs -f zabbix-docker_zabbix-agent_1`

Here is a part of these logs:
```
  1743: 20200827: 083605.003 active check configuration update from [zabbix-server: 10051] started to fail (cannot connect to [[zabbix-server]: 10051]: [111] Connection refused)
  1743: 20200827: 083705.032 active check configuration update from [zabbix-server: 10051] is working again
  1743: 20200827: 083705.032 no active checks on server [zabbix-server: 10051]: host [a7e230a74777] not found
```

In the zabbix-agent container:
`docker exec -ti zabbix-docker_zabbix-agent_1 / bin / bash`

- I have checked that the zabbix-server is accessible from zabbix agent:
```
bash-5.0 $ ping zabbix-server #PING OK
bash-5.0 $ ping a7e230a74777 #PING OK

```
- I also checked the configuration of the agent which seems correct to me:
`egrep -v "^ # | ^ $" /etc/zabbix/zabbix_agentd.conf`

```
LogType = console
Server = zabbix-server
ServerActive = zabbix-server: 10051
User = zabbix
Include = / etc / zabbix / zabbix_agentd.d /
LoadModulePath = / var / lib / zabbix / modules /
```

Do you have an idea ?

Thanks for your help.

**Comment by dotneft** [comment]
Try to use Zabbix agent IP address or DNS name in Zabbix web-interface.

**Comment by STYNET** [comment]
> Try to use Zabbix agent IP address or DNS name in Zabbix web-interface.

Thank you for your reply
I have tried, but it cannot work.

Port 10050 on the host is not reachable:
`netstat -plantu | grep 10050 #No result`

Logical because the port is not exposed on by the container:
`docker container port zabbix-docker_zabbix-agent_1 #No result`

However, from the container, the process is well exposed (internally)
`docker exec -ti zabbix-docker_zabbix-agent_1 / bin / bash`

```
bash-5.0 $ netstat -plantu | grep 10050
netstat: showing only processes with your user ID
tcp 0 0 0.0.0.0:10050 0.0.0.0:* LISTEN 1653 / zabbix_agentd
tcp 0 0 ::: 10050
```

**Comment by STYNET** [comment]
I also checked in the docker-compose.yml file
the port exposure on the host is well declared:
```
...
  zabbix-agent:
   image: zabbix / zabbix-agent: alpine-5.0-latest
   ports:
    - "10050: 10050"
...
```

**Comment by dotneft** [comment]
how you configured the host in zabbix web?

**Comment by STYNET** [comment]
Sorry, i don't understand.
What web configuration ?
On host, i installed the docker engine and deployed Zabbix with docker-compose (based on "alpine mysql latest").

**Comment by STYNET** [comment]
I don't change the default configuration.

My configuration on **.env_web** file
```
# ZBX_SERVER_HOST=zabbix-server
# ZBX_SERVER_PORT=10051
ZBX_SERVER_NAME=Composed installation
# ZBX_DB_ENCRYPTION=true # Available since 5.0.0
# ZBX_DB_KEY_FILE=/run/secrets/client-key.pem # Available since 5.0.0
# ZBX_DB_CERT_FILE=/run/secrets/client-cert.pem # Available since 5.0.0
# ZBX_DB_CA_FILE=/run/secrets/pgsql-ca.pem # Available since 5.0.0
# ZBX_DB_VERIFY_HOST=false # Available since 5.0.0
# ZBX_DB_CIPHER_LIST= # Available since 5.0.0
# ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200/ # Available since 3.4.5
# ZBX_HISTORYSTORAGETYPES=['uint', 'dbl', 'str', 'text', 'log'] # Available since 3.4.5
# ENABLE_WEB_ACCESS_LOG=true
# ZBX_MAXEXECUTIONTIME=600
# ZBX_MEMORYLIMIT=128M
# ZBX_POSTMAXSIZE=16M
# ZBX_UPLOADMAXFILESIZE=2M
# ZBX_MAXINPUTTIME=300
# ZBX_SESSION_NAME=zbx_sessionid
# Timezone one of: http://php.net/manual/en/timezones.php
# PHP_TZ=Europe/Riga

```

And my configuration on **.env_agent** file, i only uncomment ZBX_SERVER_HOST
```
# ZBX_SOURCEIP=
# ZBX_DEBUGLEVEL=3
# ZBX_ENABLEREMOTECOMMANDS=0 # Deprecated since 5.0.0
# ZBX_LOGREMOTECOMMANDS=0
# ZBX_HOSTINTERFACE= # Available since 4.4.0
# ZBX_HOSTINTERFACEITEM= # Available since 4.4.0
ZBX_SERVER_HOST=zabbix-server
# ZBX_PASSIVE_ALLOW=true
# ZBX_PASSIVESERVERS=
# ZBX_ACTIVE_ALLOW=true
# ZBX_ACTIVESERVERS=
# ZBX_LISTENIP=
# ZBX_STARTAGENTS=3
# ZBX_HOSTNAME=
# ZBX_HOSTNAMEITEM=system.hostname
# ZBX_METADATA=
# ZBX_METADATAITEM=
# ZBX_REFRESHACTIVECHECKS=120
# ZBX_BUFFERSEND=5
# ZBX_BUFFERSIZE=100
# ZBX_MAXLINESPERSECOND=20
# ZBX_ALIAS=""
# ZBX_TIMEOUT=3
# ZBX_UNSAFEUSERPARAMETERS=0
# ZBX_LOADMODULE="dummy1.so,dummy2.so,dummy10.so"
# ZBX_TLSCONNECT=unencrypted
# ZBX_TLSACCEPT=unencrypted
# ZBX_TLSCAFILE=
# ZBX_TLSCRLFILE=
# ZBX_TLSSERVERCERTISSUER=
# ZBX_TLSSERVERCERTSUBJECT=
# ZBX_TLSCERTFILE=
# ZBX_TLSKEYFILE=
# ZBX_TLSPSKIDENTITY=
# ZBX_TLSPSKFILE=
# ZBX_DENYKEY=system.run[*]
# ZBX_ALLOWKEY=

```

**Comment by dotneft** [comment]
How did you added/configured host in zabbix web-interface (where you see problems with zabbix agent availability)

**Comment by STYNET** [comment]
In web interface, the host is configured with public IP and 10050 port.

**Comment by STYNET** [comment]
I solved my problem ! :)

The zabbix Server must be call with docker container name (and not public DNS or IP).

The configuration in web-interface is :

- Agent interfaces -> DNS name : **zabbix-agent**
- Agent interfaces -> Connect to : selected **DNS**

Thank (spocibo) dotneft for your help :+1:

**Comment by dotneft** [comment]
You are welcome :-)
