### ISSUE TITLE
Add curl to zabbix-agent

### ISSUE THREAD

**Issue by x-jokay** [zabbix/zabbix-docker#706]
Would it be possible to add `curl` to the `zabbix-agent` so we can mount `/var/run/docker.sock` and monitor a host?

More information [here](https://github.com/vivanov-dp/zabbix-docker-template/issues/2) :wink:

**Comment by x-jokay** [comment]
According to https://github.com/zabbix/zabbix-docker/issues/487#issuecomment-513278704 was it added to the `ubuntu` images but no the `alpine` images :confused:

**Comment by rockaut** [comment]
It's easy to derive the image for your own. For example:

```
FROM zabbix/zabbix-agent

RUN apt install curl
```

Also have you tried agent2 with the docker plugin? https://www.zabbix.com/integrations/docker

**Comment by x-jokay** [comment]
> Also have you tried agent2 with the docker plugin? https://www.zabbix.com/integrations/docker

Not yet, thank you, will try this 👍🏼
