### ISSUE TITLE
Enable the GitHub wiki to add some help pages here

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#709]
Would it be possible to enable the wiki sections here at GitHub? I would find it helpful for some newcomers to get quicker help. There are so many repeating issue-patterns which MAY get helped/sorted out before opening an issue.

I understand if you guys would like it more if users get over to zabbix.com docs but that may be accomplished through also through the wiki if here are just the quick helps /FAQs and then linking to the official docs.

That said I feel like the official docs are lacking many details on the dockerized versions and so it might even fit to send the official one over to here then?

**Comment by dotneft** [comment]
Enabled :-) Anything else? Permissions?

**Comment by rockaut** [comment]
Thank you @dotneft ... I'm currently in a vacation for the next two weeks but I will check back later.
I think there are some permissions needed yes : https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by dotneft** [comment]
don!
