### ISSUE TITLE
docker.containers.discovery[false] & docker.images.discovery are populated as  Unsupported item key

### ISSUE THREAD

**Issue by sysadmin-james** [zabbix/zabbix-docker#710]
hey there,
i have followed this https://blog.zabbix.com/zabbix-docker-containers/7150/ link to setup zabbix as Server-AgentClient model using docker containers.

zabbix server is showing  Unsupported item key for docker.containers.discovery[false] & docker.images.discovery of "Template App docker" template for a server running docker containers and zabbix server and agent are also running as docker containers.

please tell us how to resolve this issue.

**Comment by x-jokay** [comment]
Your used `docker-compose.yml` may be useful to analyze the problem?

It sounds similar to https://github.com/zabbix/zabbix-docker/issues/695#issuecomment-678610056 or https://github.com/zabbix/zabbix-docker/issues/707#issuecomment-684511596 but without any further information it's hard to tell.

**Comment by sysadmin-james** [comment]
hey there, i have used this https://github.com/zabbix/zabbix-docker/blob/5.0/docker-compose_v3_ubuntu_mysql_latest.yaml docker-compose file for deployment.

**Comment by x-jokay** [comment]
Ok, in this [configuration](https://github.com/zabbix/zabbix-docker/blob/5.0/docker-compose_v3_ubuntu_mysql_latest.yaml#L293), the `agent` can't connect to `/var/run/docker.sock` which is needed for `Template App Docker`.

Therefore you need to update the agent accordingly to [this](https://github.com/zabbix/zabbix-docker/issues/707#issuecomment-684511596), especially add

```yml
...
volumes:
  - /var/run/docker.sock:/var/run/docker.sock
...
user: 0:0
...
```

**Comment by x-jokay** [comment]
And don't forget the use `agent2` as `agent` won't support it.

```yml
image: zabbix/zabbix-agent2:ubuntu-5.0-latest
```

**Comment by sysadmin-james** [comment]
thanks 
below setting done trick for me

volumes:
  - /var/run/docker.sock:/var/run/docker.sock
...
user: 0:0

**Comment by sysadmin-james** [comment]
just one more thing can  we make this repo's "zabbix-docker_zabbix-agent"  collects data using this link  "https://github.com/monitoringartist/zabbix-docker-monitoring/blob/master/template/Zabbix-Template-App-Docker.xml" template.

I have added that template but does not seems to collect data using it.
it gives this error 

"Unknown metric docker.discovery"

**Comment by x-jokay** [comment]
I'm not sure if this will work with the template you mentionned but I suggest you to use the official [Template App Docker](https://www.zabbix.com/integrations/docker), this won't need any further changes.

**Comment by sysadmin-james** [comment]
ok thanks @x-jokay, you are right, Zabbix Official docker template has almost everything we can expect from Open source monitoring tool.

using Official Zabbix Template App Docker, cpu utilization of individual containers are coming as milliseconds, can we make it to come say in cpu percentages.(see below image for reference)


![image](https://user-images.githubusercontent.com/53431292/92075696-a8dc1000-edd6-11ea-91e5-bb73f025dfad.png)

**Comment by x-jokay** [comment]
Great it works 👍🏼 

Currently this template doesn't provide this type of information but it may be added one day.

This was asked in the [Zabbix Forums](https://www.zabbix.com/forum/zabbix-help/405437-zabbix-default-docker-template#post405437) as well.

**Comment by dotneft** [comment]
Also if you would like to see something new in templates or Zabbix, feel free, to open ZBXNEXT in our issue tracker: https://support.zabbix.com/
