### ISSUE TITLE
Message from 192.168.200.10 is missing header. Message ignored

### ISSUE THREAD

**Issue by bd1567** [zabbix/zabbix-docker#711]
zabbix_server_host is 192.168.200.11 installed by docker ;zabbix_agent_Host is 192.168.200.10 installed by not docker ,the error happen at zabbix_server_host.
maybe is bug. the version of server and agent  is all newest 5.0.3.
This problem is fatal. When the agent is running on 192.168.200.11, it is OK, but when it is running on another independent vm 192.168.200.10, it prompts this error.

source:docker pull zabbix/zabbix-server-mysql:latest
server start cmd:
docker run --name zabbix-server-mysql -t \
      -e DB_SERVER_HOST="mysql-server" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="iflytek" \
      -e MYSQL_ROOT_PASSWORD="iflytek" \
      -e ZBX_JAVAGATEWAY="zabbix-java-gateway" \
      --network=zabbix-net \
      --ip 172.20.240.3 \
      -v  zabbix_server:/etc \
      -p 10051:10051 \
      -d zabbix/zabbix-server-mysql 
      #-d zabbix-server-mysql:centos-latest

source:https://www.zabbix.com/downloads/5.0.3/zabbix_agent-5.0.3-linux-3.0-amd64-static.tar.gz
agent key config:
Server=192.168.200.11
ServerActive=192.168.200.11
Hostname=syq10

**Comment by bd1567** [comment]
![image](https://user-images.githubusercontent.com/45749008/91913101-62f44e80-ece7-11ea-961a-4b6a83be04c3.png)

**Comment by bd1567** [comment]
Later, I changed the container used by Zabbix_server. Docker pull zabbix/ Zabbix-server-mysql: cenos-5.0-latest, but the results were consistent

**Comment by x-jokay** [comment]
Hello

On your printscreen, the hostname is `syq10` but you used `Hostname=syq_10` for the agent.

Set the same `hostname` for both and check if this will resolve your problem.

**Comment by bd1567** [comment]
thanks for you reply ，My original configuration was syq10, but I made a mistake in pasting. If I made a mistake here, zabbix_server would prompt syq_11 not Found

**Comment by bd1567** [comment]
> Hello
> 
> On your printscreen, the hostname is `syq10` but you used `Hostname=syq_10` for the agent.
> 
> Set the same `hostname` for both and check if this will resolve your problem.

thanks for your reply ，My original configuration was syq10, but I made a mistake in pasting. If I made a mistake here, zabbix_server would prompt syq_11 not Found.now,I have changed the config of agent from 'Hostname=syq_10'  to 'Hostname=syq10'
