### ISSUE TITLE
version: centos-5.3, not found python

### ISSUE THREAD

**Issue by OPSTime** [zabbix/zabbix-docker#713]
**Upgrade to version: centos-5.3**

**Action log error:**
`sh: /usr/lib/zabbix/alertscripts/sendmail.py: /usr/bin/python2: bad interpreter: No such file or directory`

**docker exec -it \`docker ps|grep zabbix-server-mysql|awk '{print $1}' \`  bash**
```
bash-4.4$ find / -name 'python*'
/usr/lib/rpm/python-macro-helper
/usr/lib/python3.6
/usr/lib64/python3.6
/usr/share/gcc-8/python
/usr/share/crypto-policies/python
/usr/share/licenses/python3-setuptools-wheel
/usr/share/licenses/python3-pip-wheel
/usr/share/licenses/python3-libs
/usr/share/man/man1/python.1.gz
/usr/share/python3-wheels
/usr/include/python3.6m
/var/lib/alternatives/python
find: '/var/lib/portables': Permission denied
find: '/var/lib/private': Permission denied
find: '/var/cache/private': Permission denied
find: '/var/cache/ldconfig': Permission denied
find: '/var/log/private': Permission denied
/etc/alternatives/python
find: '/run/cryptsetup': Permission denied
find: '/proc/tty/driver': Permission denied
find: '/lost+found': Permission denied
```

**version: centos-5.2**
**docker exec -it \`docker ps|grep zabbix-server-mysql|awk '{print $1}'\` bash** 
```
bash-4.2$ find / -name 'python*'
/usr/lib/python2.7
/usr/lib/tmpfiles.d/python.conf
/usr/lib64/python2.7
/usr/lib64/python2.7/idlelib/Icons/python.gif
/usr/share/gcc-4.8.2/python
/usr/share/doc/python-kitchen-1.1.1
/usr/share/doc/python-pycurl-7.19.0
/usr/share/licenses/python-gobject-base-3.22.0
/usr/bin/python2.7
/usr/bin/python
/usr/bin/python2
/usr/include/python2.7
find: '/var/lib/yum/history/2020-05-04/1': Permission denied
find: '/var/lib/yum/history/2020-05-04/2': Permission denied
find: '/var/lib/yum/history/2020-05-04/5': Permission denied
find: '/var/lib/yum/history/2020-05-04/6': Permission denied
find: '/var/lib/yum/history/2020-05-04/4': Permission denied
find: '/var/lib/yum/history/2020-05-04/3': Permission denied
find: '/var/lib/machines': Permission denied
find: '/var/cache/ldconfig': Permission denied
find: '/var/tmp/yum-root-6Il4sc': Permission denied
/etc/python
find: '/run/cryptsetup': Permission denied
find: '/proc/tty/driver': Permission denied
```

**Comment by fpaternot** [comment]
Well, python2 is deprecated and out of support, so i assume it is natural to remove python2 and start replacing it with python3.

Also, looking at their [Dockerfile](https://github.com/zabbix/zabbix-docker/blob/master/server-mysql/centos/Dockerfile), python is not mentioned so, this has to do with base OS.

If you really really need it, build your image based on zabbix to include python.

**Comment by OPSTime** [comment]
> Well, python2 is deprecated and out of support, so i assume it is natural to remove python2 and start replacing it with python3.
> 
> Also, looking at their [Dockerfile](https://github.com/zabbix/zabbix-docker/blob/master/server-mysql/centos/Dockerfile), python is not mentioned so, this has to do with base OS.
> 
> If you really really need it, build your image based on zabbix to include python.

not found python(python、python2、python3)

**Comment by x-jokay** [comment]
Out of curiosity, what can your `/usr/lib/zabbix/alertscripts/sendmail.py` do, which can't be done by the native Zabbix email notification?
