### ISSUE TITLE
Frontend container for PSQL shows Mysql in logs

### ISSUE THREAD

**Issue by thebeerman** [zabbix/zabbix-docker#714]
Minor...but noticed in zabbix/zabbix-web-apache-pgsql:ubuntu-5.0.1 and looking at the logs as container starts, it states MySQL

a26036961a9c752c6184a1b940471072794ab1bb11cdbd2e99a89e8cc9a322c2
** Deploying Zabbix web-interface (Apache) with MySQL database
** Using POSTGRES_USER variable from ENV
** Using POSTGRES_PASSWORD variable from ENV
********************

**Comment by x-jokay** [comment]
This has already been fixed on newer versions, see [here](https://github.com/zabbix/zabbix-docker/commit/00b193ea1ee367fbcba79a5b6e09609a91bd6b7e#diff-25a93d21ddc25270efaaf56263a3afe1).
