### ISSUE TITLE
SourceIP on server and web

### ISSUE THREAD

**Issue by pedropilla** [zabbix/zabbix-docker#72]
Please, provide this option to those who wants use host's network stack.

**Comment by dotneft** [comment]
Do you need ListenIP and SourceIP or only SourceIP?

I'm not sure about web images. I think it is not required there at all.

**Comment by pedropilla** [comment]
Both, we have multiple instances running on the same machine so this parameters are necessary to segregate them. I was doing this changes through Dockerfile, not so pretty but fully functional.

**Comment by dotneft** [comment]
Added.
