### ISSUE TITLE
ZBX_DB_* variable change in web-nginx-mysql/ubuntu/docker-entrypoint.sh has some duplicated code

### ISSUE THREAD

**Issue by ajaxous** [zabbix/zabbix-docker#721]
This is a new change for 5.0.3 and just in the web-nginx-mysql/ubuntu/docker-entrypoint.sh file (the other root distributions don't have the duplication).

The following section:

280    ZBX_DB_KEY_FILE=$(escape_spec_char "${ZBX_DB_KEY_FILE}")
281    ZBX_DB_CERT_FILE=$(escape_spec_char "${ZBX_DB_CERT_FILE}")
282    ZBX_DB_CA_FILE=$(escape_spec_char "${ZBX_DB_CA_FILE}")
283
284    ZBX_DB_KEY_FILE=$(escape_spec_char "${ZBX_DB_KEY_FILE}")
285    ZBX_DB_CERT_FILE=$(escape_spec_char "${ZBX_DB_CERT_FILE}")
286    ZBX_DB_CA_FILE=$(escape_spec_char "${ZBX_DB_CA_FILE}")

Results in the "\" escape character being added twice, essentially escaping itself so the final definition of the certificate paths in the /etc/zabbix/web/zabbix.conf.php file has the "\" character and the certificate files can't be located.

5.0.2 didn't have the above lines at all and I had the "\" escape characters in my docker-compose yaml file and things worked okay.  With 5.0.3 the zabbix-web container (I'm using the default, ubuntu, version) wasn't able to talk to the DB.  I believe the problem is due to the above duplicated lines.  As noted, the duplication just seems to be present in the ubuntu version.

**Comment by dotneft** [comment]
Thank you! Will be fixed in a few minutes 👍

**Comment by dotneft** [comment]
Fixed
