### ISSUE TITLE
zabbix_agent2 permission denied on /var/run/docker.sock

### ISSUE THREAD

**Issue by FudiHub** [zabbix/zabbix-docker#722]
Hi

I deployed zabbix/zabbix_agent2. The container creates a user 1997 and runs as this. This user is not allowed to access docker.sock. (I added a volume /var/run/docker.sock:/var/run/docker.sock to have docker.sock available in the container)
Please add variables for UID and GID to let us configure the user running the container. This would allow us to run the agent container as root and give access to docker.sock.

Otherwise running the container as predefined user 1997 gives the error message:
`2020/09/09 08:36:05.093801 [Docker] cannot fetch data: Get http://1.28/containers/json?all=true: dial unix /var/run/docker.sock: connect: permission denied`

**Comment by x-jokay** [comment]
You can even [search](https://github.com/zabbix/zabbix-docker/issues?q=is%3Aissue+zabbix-agent2+docker+is%3Aclosed) issues on GitHub.

**Comment by FudiHub** [comment]
thanks, did it with --user=0:0
