### ISSUE TITLE
broken zabbix-web container after 8f3092b commit

### ISSUE THREAD

**Issue by neothematrix** [zabbix/zabbix-docker#724]
just reporting it here too, as mentioned on [my comment](https://github.com/zabbix/zabbix-docker/commit/8f3092b49364755056fbff96adaf92b4ecbad7b3#commitcomment-42249113), the last commit implementing maintenance support for docker zabbix-web container could potentially break existing installation if using an external conf volume where maintenance.inc.php was not previously present (it wasn't required before).
Unfortunately, it's not immediately easy to understand the issue either, zabbix frontend will just be blank and php display_errors needs to be turned on to see the real issue (can't open maintenance.php.inc file).
Not sure if it's something that can/should be fixed, but perhaps a check of the existence of the file could be done and if it doesn't exist, a default maintenance file could be created? In my case, I just created the file by copying the content of the new file from this repo.
thanks!

**Comment by dotneft** [comment]
Hello! Yes, it is possible, but why do you use external volume instead of ENV variables? Currently I see only one idea how to partly solve the issue - docker_entrypoint.sh can create the file if it is missing, but if you use external volume, I'm not sure it helps or not (you may use read only access).

**Comment by dotneft** [comment]
Also there is additional volume for SAML certs in /etc/zabbix/web/certs/. I think attached volume also breaks such directory.

**Comment by neothematrix** [comment]
Yeah, you're right, I didn't think about this, my volume is also readonly, so creating the file wouldn't work anyways. I was using the external volume to define some variables that were unsupported some time ago, but now I don't see any reason to be honest, except for faster debug and tests, I guess we can close this. Maybe a check if the required files exist and terminate the container if they don't with a proper message could be helpful to debug future issues? Like what happens if you don't have certificates for ssl and nginx can't start https. 
Thanks!

**Comment by dotneft** [comment]
Could you tell me what do you mean "faster debug and tests"? Maybe we need to introduce some additional features.

Hm... yes, probably it is a good idea to check required files according really required files and passed env variables. Ok. I will think about!

**Comment by neothematrix** [comment]
it was just a way for me to quickly changing the parameters when I was experimenting with elasticsearch storage, it was faster to change the historystorageurls/type directly in the conf without having to destroy and re-create the container, nothing really important.
