### ISSUE TITLE
docker-compose 1.27.1  unsupported

### ISSUE THREAD

**Issue by gorsing** [zabbix/zabbix-docker#725]
And when I tried to run on docker-compose version 1.26.2 everything works well

My OS : CentOS 7.8

**Comment by x-jokay** [comment]
Did you already try using docker-compose [1.27.2](https://github.com/docker/compose/releases/tag/1.27.2)?

**Comment by x-jokay** [comment]
Or now with [1.27.3](https://github.com/docker/compose/releases/tag/1.27.3)?

**Comment by dotneft** [comment]
1.27.3 is working fine!
