### ISSUE TITLE
how to monitor the zabbix-server-mysql container itself?

### ISSUE THREAD

**Issue by myzhuh** [zabbix/zabbix-docker#726]
hi.. i use this command to create a container:
docker run --hostname zabbix-server-mysql --name zabbix-server-mysql --restart=always -t -e DB_SERVER_HOST="mysql-server" -e MYSQL_DATABASE="zabbix" -e MYSQL_USER="zabbix" -e MYSQL_PASSWORD="12345" -e MYSQL_ROOT_PASSWORD="67890" -e MYSQL_PORT="3306" --link mysql-server:mysql -p 10051:10051 -d zabbix/zabbix-server-mysql:centos-latest

and after that, i can use the zabbix monitor other devices, but how to monitor the container itself?

please see the red zabbix icon as follow:
![image](https://user-images.githubusercontent.com/71317399/93188030-12fb9a00-f773-11ea-86dd-5657926281e7.png)

i can't use command 'dnf install -y zabbix-agent'，it shows 'Error: Unable to find a match: zabbix-agent'
ths..

**Comment by x-jokay** [comment]
You can monitor it using `zabbix-agent2` like explained [here](https://github.com/zabbix/zabbix-docker/issues/695#issuecomment-678610056).
