### ISSUE TITLE
no active checks on server [zabbix-server:10051]: host [zabbix-agent-69bsg] not found 

### ISSUE THREAD

**Issue by wajika** [zabbix/zabbix-docker#727]
https://github.com/zabbix/zabbix-docker/issues/613
I use kubernetes.yaml have the same issue.

I don't understand why there is a link problem between zabbix-server and zabbix-agent (zabbix-xxx service and endpoint are running)

**Comment by dariodsa** [comment]
Hostname of your container is ``zabbix-agent-69bsg`` so you should add host with that name on your zabbix server and set it that is monitored by the proxy. But be aware that when container is restarted, it's hostname and ip address will be different so you need to take care of it.

**Comment by wajika** [comment]
@dariodsa Thank you for your answer, but I have an idea. Why can't we automatically discover ZABBIX agent?
