### ISSUE TITLE
Option for enabling proxy variables in SAML library missing

### ISSUE THREAD

**Issue by hcsaustrup** [zabbix/zabbix-docker#728]
When running the frontend in a container, the SAML library will send an invalid redirect URL to the SAML identity provider. The reason is a missing call to Utils::setProxyVars(true) before getting the $baseurl in index_sso.php. Without this option, the HTTP_X_FORWARDED* variables in $_SERVER[] will be ignored and the scheme will fall back to "http" and the port to "8080".

Please provide a ZBX_* environment variable for enabling this if not by default.

Thanks.

**Comment by dotneft** [comment]
If you do not use container and use proxy on custom port. Do you need to modify ZABBIX web sources to change the parameter?

**Comment by dotneft** [comment]
Known issue and must be resolved on Zabbix web-interface source level: https://support.zabbix.com/browse/ZBXNEXT-5948
