### ISSUE TITLE
Migrate from MariaDB to Oracle MySQL library

### ISSUE THREAD

**Issue by x-jokay** [zabbix/zabbix-docker#729]
Why did you [migrate from MariaDB to Oracle MySQL library](https://github.com/zabbix/zabbix-docker/commit/e211ab5cf4e74de4f8d7e310e416fcd3f190a982)? 🧐

**Comment by dotneft** [comment]
It id difficult to say, many incompatibles in MariaDB and unexpected evolution future. They completely do not have database compatibility since 10.3 version + MariaDB connector does not have verify_ca option, while MySQL 8.0 has such option. But I'm opened for any suggestions and objections.

**Comment by x-jokay** [comment]
Thx for the response, was just curious about it :wink:

**Comment by dotneft** [comment]
Also probably future clients will support X protocol: https://dev.mysql.com/doc/dev/mysql-server/latest/mysqlx_protocol.html
