### ISSUE TITLE
import template got 500 error

### ISSUE THREAD

**Issue by okletswin** [zabbix/zabbix-docker#73]
Hi, while import an template xml file (48KB) use web-ui, nginx returned 500 error
nginx error log:
open() "/var/cache/nginx/client_temp/0000000001" failed (13: Permission denied)

Then I add "client_body_buffer_size 256k;" into nginx.conf, import successful.

Can We set an suitable value for this parameter as default ?

**Comment by dotneft** [comment]
which image do you use?

**Comment by toto976** [comment]
zabbix-web-nginx-pgsql:ubuntu-latest

**Comment by dotneft** [comment]
fixed.
