### ISSUE TITLE
zabbix-appliance not up to date

### ISSUE THREAD

**Issue by dekiesel** [zabbix/zabbix-docker#730]
Hi,

zabbix-appliance hasn't been updated for some months now.

What is the recommended way of migrating from 4.x to 5 if you have used zabbix-appliance before?

Thanks.

**Comment by dotneft** [comment]
we do not support appliances anymore. The migration procedure is quite simple. You just need use dedicated containers per each component. You need to take the same version of MariaDB container and attach volume from appliance instance.
