### ISSUE TITLE
zabbix-web-nginx-pgsql: http/500 errors are not properly logged

### ISSUE THREAD

**Issue by neothematrix** [zabbix/zabbix-docker#731]
Hi!
I noticed that zabbix-web-nginx-pgsql docker image is not properly logging http/500 error details to stdout (or anywhere in general), the only error is in the access log that shows the return code was 500 but with no error message, making it very hard to debug issues.
It seems the issue is solved by commenting out this line:

php_admin_value[error_log] = /dev/fd/2

from the /etc/php7/php-fpm.d/zabbix.conf, error details are then properly logged to stderr and visible via "docker logs".

**Comment by dotneft** [comment]
Could you show an example of the error you received?

**Comment by neothematrix** [comment]
ciao @dotneft ,
sure, for example errors related to memory_limit exceeded, you can easily test by set ZBX_MEMORY_LIMIT to a very low value, for example "1" and monitor the zabbix-web container log (docker logs -f <container-name>) while trying to open the dashboard, that should fail with just a white page, nothing is shown in the logs, just the access attempts returning HTTP/500 with no details:

`x.x.x.x - - [09/Oct/2020:11:58:00 +0000] "GET /zabbix.php?action=dashboard.view HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0" "-"`

but if you remove the php_admin_value[error_log] parameter, restart the container and try opening the dashboard again, it will of course still fail with a blank page, but you'll see the actual error in the container logs:

`2020/10/09 11:59:00 [error] 17#17: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 163840 bytes) in /usr/share/zabbix/include/defines.inc.php on line 1536" while reading response header from upstream, client: x.x.x.x, server: zabbix, request: "GET /zabbix.php?action=dashboard.view HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "x.x.x.x:8081"`

`x.x.x.x- - [09/Oct/2020:11:59:00 +0000] "GET /zabbix.php?action=dashboard.view HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0" "-"`

I hope this helps!

thanks

**Comment by dotneft** [comment]
Thank you! The issue is fixed!
