### ISSUE TITLE
nginx "fastcgi_send_timeout" and "fastcgi_read_timeout" should match (or exceed) php "max_execution_time"

### ISSUE THREAD

**Issue by neothematrix** [zabbix/zabbix-docker#732]
ciao,
while trying to debug a "timeout" issue of an heavy zabbix api call, for reference, this is the error visible in nginx logs (after fixing the issue mentioned on #730 ):

`2020/09/21 10:12:37 [error] 46#46: *9368 upstream timed out (110: Operation timed out) while reading response header from upstream, client: x.x.x.x, server: zabbix, request: "POST /zabbix/api_jsonrpc.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock", host: "xxx.net"`

I noticed that, despite the php "max_execution_time" set as 600 seconds, the fast-cgi send/read timeout is set to 180 seconds, so our api call was timed out by fast-cgi after 3 min, before the php allotted time of 10m.

Syncing the fastcgi send/read timeout to the php max_execution_time parameter seems like [a good idea](https://notes.luxian.ro/node/7)

**Comment by dotneft** [comment]
I'm not sure but it looks like fastcgi_send_timeout is not the solution in this case. From documentation:
`Sets a timeout for transmitting a request to the FastCGI server. The timeout is set only between two successive write operations, not for the transmission of the whole request. If the FastCGI server does not receive anything within this time, the connection is closed.`
while fastcgi_read_timeout:
`Defines a timeout for reading a response from the FastCGI server. The timeout is set only between two successive read operations, not for the transmission of the whole response. If the FastCGI server does not transmit anything within this time, the connection is closed.`

So probably fastcgi_read_timeout is enough?

**Comment by neothematrix** [comment]
ciao @dotneft ,
yes you're right, I supposed one of the two could've been enough, but to quickly solve it, I've just increased both.
fastcgi_read_timeout seems the way to go.
thanks!

**Comment by dotneft** [comment]
Fixed!
