### ISSUE TITLE
zabbix/zabbix-server-pgsql:centos-4.4-latest stuck in PostgreSQL wait loop

### ISSUE THREAD

**Issue by immanuelfodor** [zabbix/zabbix-docker#733]
Hi Everyone, 

I tried running `zabbix/zabbix-server-pgsql:centos-4.4-latest` but the container is stuck in a wait loop for PG. After some debugging, it seems that the `docker-entrypoint.sh` file is different in the image than it is published here on Github, and uses a different method of checking for the DB which fails over and over.

I'd expect these lines: https://github.com/zabbix/zabbix-docker/blob/4.4/server-pgsql/centos/docker-entrypoint.sh#L182

```bash
    while true :
    do
        psql --host ${DB_SERVER_HOST} --port ${DB_SERVER_PORT} --username ${DB_SERVER_ROOT_USER} --list --quiet 1>/dev/null 2>&1 && break
        psql --host ${DB_SERVER_HOST} --port ${DB_SERVER_PORT} --username ${DB_SERVER_ROOT_USER} --list --dbname ${DB_SERVER_DBNAME} --quiet 1>/dev/null 2>&1 && break

        echo "**** PostgreSQL server is not available. Waiting $WAIT_TIMEOUT seconds..."
        sleep $WAIT_TIMEOUT
    done
```

Hovewer, the container's entrypoint has these lines:

```bash
    while [ ! "$(pg_isready --host ${DB_SERVER_HOST} --port ${DB_SERVER_PORT} --username ${DB_SERVER_ROOT_USER} --dbname ${DB_SERVER_DBNAME} --quiet 2>/dev/null && echo $?)" ]; do
        echo "**** PostgreSQL server is not available. Waiting $WAIT_TIMEOUT seconds..."
        sleep $WAIT_TIMEOUT
    done
```

After grepping and finding through the filesystem, it seems that the `pg_isready` command doesn't exist, and only this file contains it on this line. 

I managed to solve the wait loop issue by using `centos-4.4.10` instead which uses `psql` to check the connection:

```bash
    while [ ! "$(psql --host ${DB_SERVER_HOST} --port ${DB_SERVER_PORT} --username ${DB_SERVER_ROOT_USER} --dbname ${DB_SERVER_DBNAME} --list --quiet 2>/dev/null)" ]; do
        echo "**** PostgreSQL server is not available. Waiting $WAIT_TIMEOUT seconds..."
        sleep $WAIT_TIMEOUT
    done
```

Although it starts up fine now, it's a bit disturbing that all these files differ from the ones published in the repo.

**Comment by dotneft** [comment]
I suppose 4.4.10 image has a bug with some local/remote PostgreSQL detection. I recommend you upgrade the instance to 5.0 version.
