### ISSUE TITLE
Docker-compose failed with invalid number

### ISSUE THREAD

**Issue by AndyS04909** [zabbix/zabbix-docker#734]
This may be past issue ever happen but can anyone help that which part I need to change for clear this issue 
The Compose file '.\./docker-compose_v3_ubuntu_mysql_local.yaml' is invalid because:
services.zabbix-agent.deploy.resources.reservations.cpus contains an invalid type, it should be a number
services.zabbix-java-gateway.deploy.resources.reservations.cpus contains an invalid type, it should be a number
services.zabbix-snmptraps.deploy.resources.reservations.cpus contains an invalid type, it should be a number
services.zabbix-proxy-mysql.deploy.resources.reservations.cpus contains an invalid type, it should be a number
services.zabbix-proxy-sqlite3.deploy.resources.reservations.cpus contains an invalid type, it should be a number
services.zabbix-server.deploy.resources.reservations.cpus contains an invalid type, it should be a number
services.zabbix-web-apache-mysql.deploy.resources.reservations.cpus contains an invalid type, it should be a number
services.zabbix-web-nginx-mysql.deploy.resources.reservations.cpus contains an invalid type, it should be a number

Thank you

**Comment by dotneft** [comment]
Update docker-compose binary to the latest version. Similar issue #725

**Comment by AndyS04909** [comment]
Thank you, it worked
