### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/dev/stdout'

### ISSUE THREAD

**Issue by TheToto318** [zabbix/zabbix-docker#735]
Hey,
Trying to use the zabbix-web-apache-mysql image on my docker environnement (Synology DSM 5).

docker run --name zabbix-web-apache-mysql\
      -e ZBX_SERVER_HOST="zabbix-server-mysql" \
      -e DB_SERVER_HOST="mysql-server" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="zabbix_pwd2" \
      -e MYSQL_ROOT_PASSWORD="root_pwd2" \
      -p 8085:8080 \
	  --link zabbix-server-mysql:zabbix-server-mysql \
	  --link mysql-server:mysql-server \
      -d zabbix/zabbix-web-apache-mysql:centos-latest

Get this error `PermissionError: [Errno 13] Permission denied: '/dev/stdout'`

Full log : 
** Deploying Zabbix web-interface (Apache) with MySQL database
** Using MYSQL_USER variable from ENV
** Using MYSQL_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: mysql-server
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
** Adding Zabbix virtual host (HTTP)
**** Impossible to enable SSL support for Apache2. Certificates are missed.
** Preparing Zabbix frontend configuration file
########################################################
** Executing supervisord
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 11, in <module>
    load_entry_point('supervisor==4.2.0', 'console_scripts', 'supervisord')()
  File "/usr/lib/python3.6/site-packages/supervisor/supervisord.py", line 361, in main
    go(options)
  File "/usr/lib/python3.6/site-packages/supervisor/supervisord.py", line 371, in go
    d.main()
  File "/usr/lib/python3.6/site-packages/supervisor/supervisord.py", line 72, in main
    self.options.make_logger()
  File "/usr/lib/python3.6/site-packages/supervisor/options.py", line 1476, in make_logger
    backups=self.logfile_backups,
  File "/usr/lib/python3.6/site-packages/supervisor/loggers.py", line 415, in handle_file
    handler = FileHandler(filename)
  File "/usr/lib/python3.6/site-packages/supervisor/loggers.py", line 160, in __init__
    self.stream = open(filename, mode)
PermissionError: [Errno 13] Permission denied: '/dev/stdout'

Docker version : 1.6.2

**Comment by dotneft** [comment]
Probably Synology has some custom permissions on /dev/stdout and /dev/stderr. Do you have a chance to check it?

**Comment by TheToto318** [comment]
Fixed the problem by rebuilding completly the zabbix image and changing the user to "root" in the dockerfile.

**Comment by dotneft** [comment]
Hmm... you do not need to rebuild the image, just run under root it. Can you try to run vanilla image under root?
