### ISSUE TITLE
Error on pulling image from dockerhub for zabbix/zabbix-agent:ubuntu-latest

### ISSUE THREAD

**Issue by Danny-SCNX** [zabbix/zabbix-docker#737]
I was running this from Ubuntu 18.04 and hit unknown blob error. I suppose something went wrong when the image was pushed few day ago.

docker pull zabbix/zabbix-agent:ubuntu-latest

ubuntu-latest: Pulling from zabbix/zabbix-agent
e6ca3592b144: Already exists 
534a5505201d: Already exists 
990916bd23bb: Already exists 
ba0391246a50: Pulling fs layer 
74cab0736adf: Pulling fs layer 
8ac144b1ab3f: Pulling fs layer 
66d113235979: Waiting 
error pulling image configuration: unknown blob

**Comment by dotneft** [comment]
Please try again!

**Comment by Danny-SCNX** [comment]
Perfecto! Works now.

Thank you!
