### ISSUE TITLE
NightlyBuild of centos 5.0.4 images in error

### ISSUE THREAD

**Issue by grunlab** [zabbix/zabbix-docker#738]
Just in case you did not notice this issue yet : NightlyBuild of centos 5.0.4 images are in error since zabbix version 5.0.4 has been release.

**Comment by dotneft** [comment]
I know. There is a problem in base image in CentOS :-)

**Comment by grunlab** [comment]
This is very strange ... versions 5.0.3 and 5.0.4 have exactly the same dockerfiles (except the minor version value) and are both based on same base image centos:centos8 ... I don't really understand why builds are OK for 5.0.3 and not for 5.0.4 !?
Do you have the same issue with RHEL images based on UBI8?

**Comment by dotneft** [comment]
CentOS repo does not provide zlib version which is installed in base image, zlib is updated during binaries building, but then I use transaction rollback, buuut zlib version previously installed is missing in repo :-)

**Comment by dotneft** [comment]
So waiting for CentOS image update or include zlib to update list before installing dev packages)

**Comment by grunlab** [comment]
Ok, understood. Thank you for the explanation.

**Comment by dotneft** [comment]
Fixed!

**Comment by grunlab** [comment]
Great ! but the images are not available in docker hub :-( ... do you know why ?

**Comment by dotneft** [comment]
because 5.0.4 release contains the issue. Please try to use centos-latest or wait 5.0.5

**Comment by grunlab** [comment]
Hi Alexey, I'm not sure to understand your last comment.
The 5.0.4 build is now fixed so the image can now be pushed to dockerhub ... no?
So what do you mean by "5.0.4 release contains the issue" ? ... there is no more issue !

**Comment by grunlab** [comment]
Or maybe you mean that even if the build is now fixed, the version 5.0.4 itself is containing an issue that you volontary do not want to push to dockerhub? So 5.0.4 image will never be available in dockerhub and we need to wait 5.0.5 ?

**Comment by dotneft** [comment]
5.0.4 is already released and available as release tag. Yes, 5.0.4 centos will never be available (

**Comment by grunlab** [comment]
Ok, i will wait for 5.0.5, no problem for that. Thank you.
