### ISSUE TITLE
Populating ZBX_TLSPSKFILE from ENV variable

### ISSUE THREAD

**Issue by johndalexander** [zabbix/zabbix-docker#739]
HI Team,
What are the thoughts for populating ```ZBX_TLSPSKFILE``` with the appropriate pre-shared-key passed in as an ENV variable for ```zabbix-proxy```?
Potentially call said variable ```ZBX_TLSPSKVALUE```.  Use the entrypoint to create the file and populate it with ```ZBX_TLSPSKVALUE``` (if set).
This would certainly streamline automation.

I'm wondering if this idea has been broached.

Thanks

John

**Comment by dotneft** [comment]
Because ENV variable data can be compromised.
