### ISSUE TITLE
How do I change the time zone in zabbix-web-apache-pgsgl?

### ISSUE THREAD

**Issue by AtomStark** [zabbix/zabbix-docker#74]
Using the change does not work.

**Comment by dotneft** [comment]
Use official documentation https://www.zabbix.com/documentation/3.2/playground/playground/server_installation_with_postgres?s[]=timezone#php_configuration_for_zabbix_frontend

**Comment by AtomStark** [comment]
A link that you provide does not work

**Comment by dotneft** [comment]
Apache configuration file for Zabbix frontend is located in /etc/httpd/conf.d/zabbix.conf. Some PHP settings are already configured. But it's necessary to uncomment the "date.timezone" setting and http://php.net/manual/en/timezones.php|set the right timezone for you.

  php_value max_execution_time 300
  php_value memory_limit 128M
  php_value post_max_size 16M
  php_value upload_max_filesize 2M
  php_value max_input_time 300
  php_value always_populate_raw_post_data -1
  # php_value date.timezone Europe/Riga
