### ISSUE TITLE
Enable some SSO Certificate paths to be configured from the yaml file used with docker-compose

### ISSUE THREAD

**Issue by ajaxous** [zabbix/zabbix-docker#740]
There are several SSO related certificates, described here https://www.zabbix.com/documentation/current/manual/web_interface/frontend_sections/administration/authentication under ADVANCED SETTINGS:

```
$SSO['SP_KEY'] = '<path to the SP private key file>';
$SSO['SP_CERT'] = '<path to the SP cert file>';
$SSO['IDP_CERT'] = '<path to the IDP cert file>';
$SSO['SETTINGS']
```

Only the SETTINGS variable seems to be created by the docker-entrypoint.sh script.

It would be nice if it was possible to specify the other three certificate paths (SP_KEY, SP_CERT and IDP_CERT) too.

Currently I have my certificates in the default locations and didn't need to change these variables, but after updating to 5.0.4, SSO stopped working and users were presented with a message "invalid array settings: idp_cert_or_fingerprint_not_found_and_required".  I had to revert to 5.0.3 to enable people to use Zabbix, so haven't been able to debug this more, but if some default paths changed, then being able to specify them in my yaml file used by docker-compose might help create a stable configuration.

Thanks for giving this some consideration.

**Comment by ajaxous** [comment]
It looks like the feature I was asking for was actually just added for 5.0.4 and that changed the default paths for the files.

from /etc/zabbix/web/zabbix.conf.php inside the docker container:

`// Used for SAML authentication.
// Uncomment to override the default paths to SP private key, SP and IdP X.509 certificates, and to set extra settings.
$SSO['SP_KEY']                  = file_exists('/etc/zabbix/web/certs/sp.key') ? '/etc/zabbix/web/certs/sp.key' : (file_exists(getenv('ZBX_SSO_SP_CERT')) ? getenv('ZBX_SSO_SP_CERT') : '');
$SSO['SP_CERT']                 = file_exists('/etc/zabbix/web/certs/sp.crt') ? '/etc/zabbix/web/certs/sp.crt' : (file_exists(getenv('ZBX_SSO_SP_KEY')) ? getenv('ZBX_SSO_SP_KEY') : '');
$SSO['IDP_CERT']                = file_exists('/etc/zabbix/web/certs/idp.crt') ? '/etc/zabbix/web/certs/idp.crt' : (file_exists(getenv('ZBX_SSO_IDP_CERT')) ? getenv('ZBX_SSO_IDP_CERT') : '');
`

So I can use ZBX_SSO_SP_CERT, ZBX_SSO_SP_KEY and ZBX_SSO_IDP_CERT in my docker_compose yaml file and be good to go.  The previous default location for the certificate files is different from 5.0.3 and that's why things broke for me.

However, there's still a bug in 2 of the above lines:

- SP_CERT is getting it's value from ZBX_SSO_SP_KEY
- SP_KEY is getting it's value from ZBX_SSO_SP_CERT

I think that's swapped?

So I assigned ZBX_SSO_SP_CERT the private key and ZBX_SSO_SP_KEY the public certificate.  I have SSO working by doing that with the additional assignment of ZBX_SSO_IDP_CERT.

**Comment by dotneft** [comment]
Fixed! Thank you!
