### ISSUE TITLE
connection to pgsql

### ISSUE THREAD

**Issue by Kawabountou** [zabbix/zabbix-docker#741]
Hi to the team,

I did some research but i don't find the solution.

I  use the command ( docker-compose -f docker-compose_v3_alpine_pgsql_latest.yaml up -d ) for starting the zabbix containers.

But, with a software, i would like to connect to the pgsql server.
I try to add this in the postgres-server  section
ports:
  - "5432:5432"

but nothing happen when i try to connect me.

Moreover, the port is not display in the portainer dashboard.

Thanks to the team :)

**Comment by dotneft** [comment]
Sorry, what do you want to achieve when expose the port?

**Comment by Kawabountou** [comment]
i would like to connect me to the database

**Comment by dotneft** [comment]
from where? Using psql command?

**Comment by Kawabountou** [comment]
like a software for analyse the database

**Comment by dotneft** [comment]
locally from host? or remotely? Locally it should be able to connect, if you exposed the port. Try to use telnet to check port availability.

**Comment by Kawabountou** [comment]
yes, from locally. i try telnet, but he said that something is wrong

**Comment by dotneft** [comment]
Is it exact error message? Show us the exact information you see when execute telnet

**Comment by Kawabountou** [comment]
telnet 192.168.1.20 5432
Connexion à 192.168.1.20...Impossible d’ouvrir une connexion à l’hôte, sur le port 5432: Échec lors de la connexion (in french)
Connection to 192.168.1.20 ... Unable to open a connection to the host, on port 5432: Failed to connect

for information, my postgres-server section : 

 postgres-server:
  image: postgres:latest
#  command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
  volumes:
   - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
   - ./.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
   - ./.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
   - ./.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
  ports:
    - "5432:5432/tcp"
  restart: unless-stopped
  env_file:
   - .env_db_pgsql
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - postgres-server
     - pgsql-server
     - pgsql-database

**Comment by dotneft** [comment]
What is 192.168.1.20?
Please check:
netstat -tulpan | grep 5432

**Comment by Kawabountou** [comment]
the zabbix server has the 192.168.1.20 ip address

when i do the command "netstat -tulpan | grep 5432" on the zabbix-server, the result is empty

**Comment by dotneft** [comment]
Is 192.168.1.20 IP of host server for  PostgreSQL container?

**Comment by Kawabountou** [comment]
yes

**Comment by dotneft** [comment]
Please show the output of:
```
docker inspect <name of postgresql container>
```

**Comment by Kawabountou** [comment]
[
    {
        "Id": "4354beafa501f02e6edae4d837dbc809bc097c272a40a96b08bfee381e962662",
        "Created": "2020-10-06T12:31:40.250259066Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "postgres"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 317075,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-10-06T12:31:42.306524143Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:66e8b65fac314a41858880804b375cd87c63b61fa9c1fe1e91ac70fb473c1b60",
        "ResolvConfPath": "/var/lib/docker/containers/4354beafa501f02e6edae4d837dbc809bc097c272a40a96b08bfee381e962662/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/4354beafa501f02e6edae4d837dbc809bc097c272a40a96b08bfee381e962662/hostname",
        "HostsPath": "/var/lib/docker/containers/4354beafa501f02e6edae4d837dbc809bc097c272a40a96b08bfee381e962662/hosts",
        "LogPath": "/var/lib/docker/containers/4354beafa501f02e6edae4d837dbc809bc097c272a40a96b08bfee381e962662/4354beafa501f02e6edae4d837dbc809bc097c272a40a96b08bfee381e962662-json.log",
        "Name": "/zabbix-docker_postgres-server_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/ubuntu/zabbix-docker/zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw",
                "/home/ubuntu/zabbix-docker/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro",
                "/home/ubuntu/zabbix-docker/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro",
                "/home/ubuntu/zabbix-docker/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "zabbix-docker_zbx_net_backend",
            "PortBindings": {
                "5432/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5432"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "bind",
                    "Source": "/home/ubuntu/zabbix-docker/.POSTGRES_USER",
                    "Target": "/run/secrets/POSTGRES_USER",
                    "ReadOnly": true
                },
                {
                    "Type": "bind",
                    "Source": "/home/ubuntu/zabbix-docker/.POSTGRES_PASSWORD",
                    "Target": "/run/secrets/POSTGRES_PASSWORD",
                    "ReadOnly": true
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/95241c8c6d7540ede8c3ac1f9bfc1490db51e2e1a5826f44830b245f5cfdcbf2-init/diff:/var/lib/docker/overlay2/f16cd7004c69ac9eb9ebf6d8eaa96dd83ba41255fae69b18ffa322cf9e41032a/diff:/var/lib/docker/overlay2/4ada0f4283a76bcec6cefe5ff2b69ff00bc65f106e741718acf2f17cb91c2fb5/diff:/var/lib/docker/overlay2/d0b62a53a3c1d0da551b28664d825e005a8a0c282081cbfdd6ab77f9134ba35e/diff:/var/lib/docker/overlay2/e5fd34028f0e73ad63fb4df118d0ca879197d78f19a9b140f08228edeea7f439/diff:/var/lib/docker/overlay2/a6c9b851c2d0514e062284a411551282f83b53b844d3207bd8f7ef452a856aee/diff:/var/lib/docker/overlay2/5feaffa8b6548c2ebee82fe6ca71b3ce3ce2fca7edd85383bc192bd3b234da3e/diff:/var/lib/docker/overlay2/16953129cad2c42f6920d2b47536200ad364ab06d92018272e2c96e139c5f898/diff:/var/lib/docker/overlay2/ad17f76c7f692387c3bb5b35bda89eff39d73c999ac97c2cff2cea997d03299a/diff:/var/lib/docker/overlay2/0007e1952daf78584ea05c6aee4b2257122ccccfeb03d312edb51bb7ff144faa/diff:/var/lib/docker/overlay2/9934e04095e80e912403a9d96c15aeeabe0de4f434c2760d019b96093f7c5412/diff:/var/lib/docker/overlay2/10ecf3ec44088eebcdfd9bc88e92a7a124e0c3f1fccf9c2c7390f811a43a8bf9/diff:/var/lib/docker/overlay2/6366e46813c021a2182251a85ceff32b99dfccad3f691ff569b27a40fabcb42c/diff:/var/lib/docker/overlay2/43494817eef3a4b5ecd58922e9ab2139d68fa8d64dbe60d8e1d068b4e12344e0/diff:/var/lib/docker/overlay2/63737c69c23e37d7d7b87b5a72a0cede6d15f9a98d42215b4149b5e9db9ea6cf/diff",
                "MergedDir": "/var/lib/docker/overlay2/95241c8c6d7540ede8c3ac1f9bfc1490db51e2e1a5826f44830b245f5cfdcbf2/merged",
                "UpperDir": "/var/lib/docker/overlay2/95241c8c6d7540ede8c3ac1f9bfc1490db51e2e1a5826f44830b245f5cfdcbf2/diff",
                "WorkDir": "/var/lib/docker/overlay2/95241c8c6d7540ede8c3ac1f9bfc1490db51e2e1a5826f44830b245f5cfdcbf2/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/ubuntu/zabbix-docker/zbx_env/var/lib/postgresql/data",
                "Destination": "/var/lib/postgresql/data",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ubuntu/zabbix-docker/.ZBX_DB_CERT_FILE",
                "Destination": "/run/secrets/server-cert.pem",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ubuntu/zabbix-docker/.ZBX_DB_CA_FILE",
                "Destination": "/run/secrets/root-ca.pem",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ubuntu/zabbix-docker/.ZBX_DB_KEY_FILE",
                "Destination": "/run/secrets/server-key.pem",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ubuntu/zabbix-docker/.POSTGRES_USER",
                "Destination": "/run/secrets/POSTGRES_USER",
                "Mode": "",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ubuntu/zabbix-docker/.POSTGRES_PASSWORD",
                "Destination": "/run/secrets/POSTGRES_PASSWORD",
                "Mode": "",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "4354beafa501",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5432/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DB_SERVER_PORT=5432",
                "POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER",
                "POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD",
                "POSTGRES_DB=zabbix",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/13/bin",
                "GOSU_VERSION=1.12",
                "LANG=en_US.utf8",
                "PG_MAJOR=13",
                "PG_VERSION=13.0-1.pgdg100+1",
                "PGDATA=/var/lib/postgresql/data"
            ],
            "Cmd": [
                "postgres"
            ],
            "Image": "postgres:latest",
            "Volumes": {
                "/run/secrets/root-ca.pem": {},
                "/run/secrets/server-cert.pem": {},
                "/run/secrets/server-key.pem": {},
                "/var/lib/postgresql/data": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "e7385c5ade9e96763dab7e681ad02c6bd19f74db0388629ab1b4fb325b7f54ff",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "zabbix-docker",
                "com.docker.compose.project.config_files": "docker-compose_v3_alpine_pgsql_latest.yaml",
                "com.docker.compose.project.working_dir": "/home/ubuntu/zabbix-docker",
                "com.docker.compose.service": "postgres-server",
                "com.docker.compose.version": "1.25.0"
            },
            "StopSignal": "SIGINT",
            "StopTimeout": 60
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9d80b6ef156b1907aadef5d480f29663d94970073aeec77d359eb916810d2367",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/9d80b6ef156b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "zabbix-docker_zbx_net_backend": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "4354beafa501",
                        "postgres-server",
                        "pgsql-database",
                        "pgsql-server"
                    ],
                    "NetworkID": "b3c57828156e0d755f0f89f36dba8f85d01a05e89e06c42978fa753fb2bd0b18",
                    "EndpointID": "2b9c1b1c03304d54b07834f7e1d2df95eac7a9c832ecd753fc37dff0861578c4",
                    "Gateway": "172.16.239.1",
                    "IPAddress": "172.16.239.5",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:10:ef:05",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by dotneft** [comment]
It uses "NetworkMode": "zabbix-docker_zbx_net_backend" network, which does not have "public" access. Instead of "zbx_net_backend" use "zbx_net_frontend". Or just add "zbx_net_frontend" as additional network for PostgreSQL.

**Comment by Kawabountou** [comment]
thank you so much !!
It's exactly what you said :)

I close the issue
