### ISSUE TITLE
zabbix / zabbix-docker / web-apache-mysql:ubuntu - secure connection with elasticsearch 7.9

### ISSUE THREAD

**Issue by ozmoze** [zabbix/zabbix-docker#742]
Hello,

We are trying to setup a secure connection between zabbix 5.0 web to a a v7.9 elasticsearch. 
For this puropose, we are passing env variables : 
```
 - ZBX_HISTORYSTORAGEURL = https://elk:9200
 - ZBX_HISTORYSTORAGETYPES = ['uint','dbl','str','log','text']
```
Unfortunately connection fails because php doe not seem to use system CA.

To make it work, we had to manually edit /usr/share/zabbix/include/classes/helpers/CElasticsearchHelper.php and explicitly add ssl options in request function
```
'ssl' => [
 'cafile' => "path to elasticsearch CA",
 'verify_peer'=> true,
 'verify_peer_name'=> true
 ]
```
Is there a way to achieve this without editing elastic helper config?

Regards

**Comment by dotneft** [comment]
if you use non-container Zabbix web-interface do you still need to change the file? Did you try Alpine/CentOS versions?

**Comment by dotneft** [comment]
Thank you! I just thinking we need change something in the image. But ca-certificates already in the image.

**Comment by ozmoze** [comment]
Hi,

We have just tried with zabbix/zabbix-web-apache-mysql:centos-5.0-latest and it is working fine after running "update-ca-trust extract".


With ubuntu image a basic test with curl is OK, meaning that CA are correctly picked from system: 

zabbix@zabbix-web-b9fd68c69-4g6ln:/usr/share/zabbix$ curl -vvv https://x;x;x;x:9200

* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs

> GET / HTTP/1.1
< HTTP/1.1 200 OK

{
  "name" : "zabbix-elk-es-node-2",
  "cluster_name" : "zabbix-elk",
  "cluster_uuid" : "sJGR5L0QS9uR8Bh3OvQV5Q",
  "version" : {
    "number" : "7.9.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "d34da0ea4a966c4e49417f2da2f244e3e97b4e6e",
    "build_date" : "2020-09-23T00:45:33.626720Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

Still on GUI, we have the error:

file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed [zabbix.php:21 → require_once() → ZBase->run() → ZBase->processRequest() → CController->run() → CControllerWidgetSvgGraphView->doAction() → CSvgGraphHelper::get() → CSvgGraphHelper::getMetricsData() → CHistoryManager->getGraphAggregationByWidth() → CHistoryManager->getGraphAggregationByWidthFromElasticsearch() → CElasticsearchHelper::query() → CElasticsearchHelper::request() → file_get_contents() in include/classes/helpers/CElasticsearchHelper.php:58]
file_get_contents(): Failed to enable crypto [zabbix.php:21 → require_once() → ZBase->run() → ZBase->processRequest() → CController->run() → CControllerWidgetSvgGraphView->doAction() → CSvgGraphHelper::get() → CSvgGraphHelper::getMetricsData() → CHistoryManager->getGraphAggregationByWidth() → CHistoryManager->getGraphAggregationByWidthFromElasticsearch() → CElasticsearchHelper::query() → CElasticsearchHelper::request() → file_get_contents() in include/classes/helpers/CElasticsearchHelper.php:58]


Regards

**Comment by dotneft** [comment]
What about Alpine image?

**Comment by dotneft** [comment]
is the cert self-signed? Do you mount manually /etc/ssl/certs?

**Comment by ozmoze** [comment]
Hi,

Not yet tried with Alpine image.

Cert is self signed by elastic eck operator and indeed we manually mount it in our kubernetes deployment as it is not possible to run "update-ca-certificates" in the container anymore, as 5.0 image is using zabbix user for security reasons.

Here is a snapshot of kube deployment:

spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      volumes:
        - name: elastic-tls-certificate
          secret:
            secretName: zabbix-elk-es-http-certs-public 
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0-latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: elastic-tls-certificate
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: "tls.crt"
              readOnly: true
            - name: elastic-helper
              mountPath: /usr/share/zabbix/include/classes/helpers/CElasticsearchHelper.php
              subPath: "CElasticsearchHelper.php"
              readOnly: true

Anyway, as you can see, we have used a configMap with a custom CElasticsearchHelper.php where CA certificate path is added.

Thanks for you time.

Regards

**Comment by dotneft** [comment]
Could you show me what custom CElasticsearchHelper.php you have? Maybe we can introduce such change from a box.

**Comment by ozmoze** [comment]
Hi,

We have added the "ssl" part in request options of CElasticsearchHelper.php config file.
Here is a snippet of the code:

private static function request($method, $endpoint, $request = null) {
    		$time_start = microtime(true);
    		$options = [
    			'http' => [
    				'header'  => "Content-Type: application/json; charset=UTF-8",
    				'method'  => $method,
    				'ignore_errors' => true, // To get error messages from Elasticsearch.
    			],
    			'ssl' => [
                                    'cafile' => "/etc/ssl/certs/ca-certificates.crt",
                                    'verify_peer'=> true,
                                    'verify_peer_name'=> true
    			]
    		];

Regards

**Comment by dotneft** [comment]
Thank you! I very confused that you told Zabbix frontend is working with SSL if it is not inside of container. I'm thinking if CA certs are self-signed - it should not work! Or you mean that you still need put these ca-certificates.crt to /etc/ssl/certs/ independent of installation type?

**Comment by ozmoze** [comment]
Hi,

CA certs are self-signed by elasticsearch.
 
On both installation types, certificates were added to /etc/ssl/certs/

Regards

**Comment by dotneft** [comment]
Do you execute any additional commands if Zabbix web is running outside of container?

**Comment by ozmoze** [comment]
Hello,

When running outside of container, as the linux distribution was an ubuntu one, we had to run "update-ca-certificates" command.

Regards

**Comment by dotneft** [comment]
I have registered issue to solve the problem in Zabbix: https://support.zabbix.com/browse/ZBXNEXT-6277. It must be solved in Zabbix sources I think.
