### ISSUE TITLE
zabbix/zabbix-server-mysql:centos-5.0.4 ist missing on docker hub

### ISSUE THREAD

**Issue by alexei-matveev** [zabbix/zabbix-docker#743]
Ubuntu & Alpine-based images v5.0.4 are there ...

  $ docker pull zabbix/zabbix-server-mysql:centos-5.0.4
  Trying to pull repository docker.io/zabbix/zabbix-server-mysql ...
  manifest for docker.io/zabbix/zabbix-server-mysql:centos-5.0.4 not found

Maybe a failed build somewhere?

**Comment by alexei-matveev** [comment]
Ah, and zabbix-agent:centos-5.0.4 is missing too ..

**Comment by alexei-matveev** [comment]
https://github.com/alexei-matveev/hello-zabbix/commit/83a2a3906ad36d5fa892addab1257775b867da1e

**Comment by dotneft** [comment]
Correct! It happened because of #738.
