### ISSUE TITLE
Cache configuration Zabbix Server

### ISSUE THREAD

**Issue by adhityaranggap** [zabbix/zabbix-docker#744]
Hi, 

I try to install zabbix-docker with this command 
`docker-compose -f docker-compose_v3_centos_pgsql_latest.yaml up -d`

But seems I got configuration cache is low

Alert: More than 75% used in the configuration cache

Description : Consider increasing CacheSize in the zabbix_server.conf configuration file

I try to configure `/etc/zabbix/zabbix_server.conf` but seems the issue not yet resolved

Could you please share how to fix this case?

Regards.

**Comment by dotneft** [comment]
Please use env variables to increase configuration cache.

**Comment by adhityaranggap** [comment]
Hi,

Thank you! 
I tried to edit .env by this command `vi ~/zabbix-docker/.env_srv`

Regards,
