### ISSUE TITLE
$DB['TYPE'] unset in web-nginx-mysql (zabbix.conf.php) since 5.0.4

### ISSUE THREAD

**Issue by msccodestuff** [zabbix/zabbix-docker#745]
Until 5.0.3 the $DB['TYPE']  is correctly set to MYSQL in web-nginx-mysql.
Since 5.0.4 there is 
$DB['TYPE']     = getenv('DB_SERVER_TYPE');
But for the image web-nginx-mysql, $DB['TYPE'] should be set fix to MSQL, not?

**Comment by dotneft** [comment]
Thank you! Which image you found the issue?

**Comment by dotneft** [comment]
Previously $DB['TYPE']     = 'MYSQL'; had static value. I can not find where is a mistake.

**Comment by dotneft** [comment]
MYSQL or POSTGRESQL. I made the change just to have the same config files for PgSQL and MySQL :-) DB_SERVER_TYPE is specified directly in docker entrypoint script.

**Comment by fpaternot** [comment]
Makes total sense to me. More we can customize parameters via environment variables, more control we have to customize it along the way in production. I even feel we need more variables to play around :)

**Comment by msccodestuff** [comment]
Yes, agreed, make sense to allow customization via variables and entry-point script. But in case of the container/image web-nginx-mysql, the variable DB_SERVER_TYPE (https://github.com/zabbix/zabbix-docker/blob/5.0/web-nginx-mysql/rhel/conf/etc/zabbix/web/zabbix.conf.php#L5) is not processed by the entry-point script (https://github.com/zabbix/zabbix-docker/blob/5.0/web-nginx-mysql/rhel/docker-entrypoint.sh) and thus left unset. 
This has changed between versions 5.0.4 and 5.0.3.

**Comment by dotneft** [comment]
The variable is set in docker-entrypoint.sh: https://github.com/zabbix/zabbix-docker/blob/5.0/web-nginx-mysql/rhel/docker-entrypoint.sh#L274

In Zabbix 5.0.3 $DB['TYPE'] was static: https://github.com/zabbix/zabbix-docker/blob/5.0.3/web-nginx-mysql/rhel/conf/etc/zabbix/web/zabbix.conf.php
