### ISSUE TITLE
PHP_TZ doesn't have an effect on web interface

### ISSUE THREAD

**Issue by KrisTheGreat** [zabbix/zabbix-docker#746]
Hi,
I'm using zabbix 5.0.3. Run with docker-compose: docker-compose_v3_alpine_mysql_latest.yaml. The problem is timezone in Zabbix web interface is wrong; all events, graphs are GMT +3 and should be GMT+2 according my PHP_TZ settings in .env_web file. Surprisingly the clock witget shows correct time. Please help me.

PHP_TZ="Europe/Warsaw"

**Comment by dotneft** [comment]
What do you have in /etc/php7/php-fpm.d/zabbix.conf ?

**Comment by KrisTheGreat** [comment]
web-nginx-mysql/alpine/conf/etc/php7/php-fpm.d/zabbix.conf :

php_value[date.timezone]= Europe/Warsaw

**Comment by dotneft** [comment]
could you try to use [phpinfo](https://www.php.net/manual/en/function.phpinfo.php) and verify that timezone is Europe/Warsaw?

**Comment by KrisTheGreat** [comment]
@dotneft How can I check that? I need to touch php file with phpinfo command somewhere?

**Comment by dotneft** [comment]
just create php file with phpinfo function and try to open in web.

**Comment by dotneft** [comment]
Any news?
