### ISSUE TITLE
Docker: Cannot send proxy data to server at x.x.x.x: connection of type "unencrypted" is not allowed for proxy x

### ISSUE THREAD

**Issue by lorenzzz987** [zabbix/zabbix-docker#747]
After configuring a Zabbix server on CentOS (native), I configured a CentOS-mariadb container with a zabbix-proxy database and granted privileges. Thereafter I ran a zabbix-proxy-mysql container, generated a psk with the appropriate rights and checked the zabbix_proxy_mysql.config to make sure the correct parameters are used (Server, ServerPort, Hostname, DBName, DBUser, TLSConnect, TLSAccept, TLSPSKFile and TLSPSKIdentity). I made sure that the server frontend has the correct hostname, pskidentity and psk. After this I rebooted the container, but the container showed the following  error message: "cannot send proxy data to server at "x.x.x.x": connection of type "unencrypted" is not allowed for proxy "xxx"". When I switched the encryption to unencrypted at the server frontend, the proxy interacts with the server. However encryption using psk doesn't seem to work. It appears that the TLS part of the config is wiped during the reboot of the container. My only solution might be to run the proxy service in a generic CentOS/system.d container which I'm trying right now.

**Comment by dotneft** [comment]
What exact env vars do you pass to Zabbix proxy?

**Comment by dotneft** [comment]
It is not path:
`/var/lib/zabbix/enc

The volume is used to store TLS related files. These file names are specified using ZBX_TLSCAFILE, ZBX_TLSCRLFILE, ZBX_TLSKEY_FILE and ZBX_TLSPSKFILE variables.`
You just specify file name and attach volume /var/lib/zabbix/enc with the PSK file.

**Comment by lorenzzz987** [comment]
Working with attached volumes is new to me, I will try this but it might take a bit longer. If I understand correctly, the psk-key needs to be put in the newly created volume and that volume has to be mounted to the zabbix_proxy_mysql container? I don't quite understand if it's a newly created volume or the volume /var/lib/zabbix/enc has to be attached to the container, could you specify this?

**Comment by dotneft** [comment]
Please check official Docker documentation: https://docs.docker.com/storage/volumes/

**Comment by lorenzzz987** [comment]
It works using the following command:
docker run --name e-zabbix-proxy-mysql -v /home/shared:/var/lib/zabbix/enc -e DB_SERVER_HOST=x.x.x.x -e MYSQL_USER="db_user" -e MYSQL_PASSWORD="db_pwd" -e ZBX_HOSTNAME=proxy_name -e ZBX_SERVER_HOST=x.x.x.x -e ZBX_TLSCONNECT=psk -e ZBX_TLSACCEPT=psk -e ZBX_TLSPSKIDENTITY=psk_id -e ZBX_TLSPSKFILE=zabbix_proxy.psk

I've tested it both on a Windows & CentOS host, thanks alot for the suppport!
