### ISSUE TITLE
Dashboard page problems

### ISSUE THREAD

**Issue by agvaliente** [zabbix/zabbix-docker#748]
Hello

I have implemented Zabbix in kubernetes on-premise. The installation was successfully. When I connect yo my zabbix web, http://myserver/zabbix/ the login and dashboard page is not loaded correctly.

I have attached the image with my page loaded.

![22-10-2020 21-46-15](https://user-images.githubusercontent.com/68594748/96922465-2c011480-14b0-11eb-9dea-33696674a413.png)

**Comment by dotneft** [comment]
Could you try to reset cache? Or use private browsing mode?

**Comment by agvaliente** [comment]
Hello

The problem is the same reseting cache and using private browsing mode.

Best regards.

**Comment by dotneft** [comment]
Please check network in browser. Any errors to load CSS, content, Java?

**Comment by agvaliente** [comment]
Hello

with F12 report this messages:

![image](https://user-images.githubusercontent.com/68594748/96927848-f2340c00-14b7-11eb-9a3c-df038c8579a2.png)

**Comment by agvaliente** [comment]
The problem was in the ingress, the correct path is /

![image](https://user-images.githubusercontent.com/68594748/97086720-5de7b780-1625-11eb-968d-289641d31d7f.png)
