### ISSUE TITLE
returned a non-zero code: 1

### ISSUE THREAD

**Issue by suanmb** [zabbix/zabbix-docker#75]
root@baoxx-VirtualBox:/home/baoxx/mygit/zabbix-docker/server-mysql/ubuntu# ./build.sh
Sending build context to Docker daemon 60.93 kB
Step 1 : FROM ubuntu:trusty
 ---> 3f755ca42730
Step 2 : MAINTAINER Alexey Pustovalov <alexey.pustovalov@zabbix.com>
 ---> Using cache
 ---> e793dd4c6133
Step 3 : ARG APT_FLAGS_COMMON="-qq -y"
 ---> Using cache
 ---> 45423a4b85ac
Step 4 : ARG APT_FLAGS_PERSISTANT="${APT_FLAGS_COMMON} --no-install-recommends"
 ---> Using cache
 ---> a3a189e48aeb
Step 5 : ARG APT_FLAGS_DEV="${APT_FLAGS_COMMON} --no-install-recommends"
 ---> Using cache
 ---> b0658dac8e77
Step 6 : ARG DB_TYPE=mysql
 ---> Using cache
 ---> 750765548222
Step 7 : ENV MIBDIRS /usr/share/snmp/mibs:/var/lib/zabbix/mibs MIBS +ALL
 ---> Using cache
 ---> 30e447bed5e1
Step 8 : RUN echo -e '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d
 ---> Running in 119bd75ff72d
write pipe: bad file descriptor
The command '/bin/sh -c echo -e '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d' returned a non-zero code: 1

and Dockerfile~~~~~~~~~~~~~~~~~
root@baoxx-VirtualBox:/home/baoxx/mygit/zabbix-docker/server-mysql/ubuntu# cat Dockerfile
FROM ubuntu:trusty
MAINTAINER Alexey Pustovalov <alexey.pustovalov@zabbix.com>

ARG APT_FLAGS_COMMON="-qq -y"
ARG APT_FLAGS_PERSISTANT="${APT_FLAGS_COMMON} --no-install-recommends"
ARG APT_FLAGS_DEV="${APT_FLAGS_COMMON} --no-install-recommends"
ARG DB_TYPE=mysql
#ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 DEBIAN_FRONTEND=noninteractive TERM=xterm
ENV MIBDIRS=/usr/share/snmp/mibs:/var/lib/zabbix/mibs MIBS=+ALL

#RUN locale-gen $LC_ALL 
RUN    echo -e '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d 
RUN addgroup --system --quiet zabbix && \

**Comment by dotneft** [comment]
I suppose the issue on your side. Try to use latest docker.
