### ISSUE TITLE
"SQL statement execution has failed" at login screen.

### ISSUE THREAD

**Issue by leandromribeiro** [zabbix/zabbix-docker#750]
When i try login in zabbix, i receive the error:

SQL statement execution has failed "INSERT INTO sessions (sessionid,userid,lastaccess,status) VALUES ('b26e0dc6e80a192bc43814b39906e5f2','3','1603540119','0')".

![image](https://user-images.githubusercontent.com/48056098/97081008-edfe1080-15d5-11eb-8f95-349616125678.png)

I running zabbix front with kubernetes, using the image zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest. 
It was working until 2 days ago in version 4.4.10, don't find any error in logs and DB. 

I decided to upgrade to version 5.0.4, believing the problem was the version, but the problem persist. 

Any ideas?

**Comment by dotneft** [comment]
If you execute the query manually, what is the error?
