### ISSUE TITLE
zabbix/zabbix-appliance:ubuntu-trunk doesn't have SAML option

### ISSUE THREAD

**Issue by antigenius0910** [zabbix/zabbix-docker#753]
![Screen Shot 2020-10-27 at 11 36 47 AM](https://user-images.githubusercontent.com/5915590/97332663-b4810b80-1848-11eb-917c-136e35d9edaa.png)

according to official release note 5.0 should have SAML option.
https://blog.zabbix.com/zabbix-5-0-released/10567/

Will 5.2 release have SAML option? or what should I do to make this option enable?

Thank you so much for your help!!

**Comment by dotneft** [comment]
SAML options are available as env variables. Please check docs: https://github.com/zabbix/zabbix-docker/tree/5.2/web-nginx-mysql/alpine#environment-variables

**Comment by antigenius0910** [comment]
Thanks, just trying to get a clear view on this, are we saying once if I config my key and crt in /etc/zabbix/web/certs as env variable. the following SAML GUI option will pop out? 

/etc/zabbix/web/certs
The volume allows to use custom certificates for SAML authentification. The volume must contains three files sp.key, sp.crt and idp.crt. Available since 5.0.0.

![Screen Shot 2020-10-28 at 1 57 03 AM](https://user-images.githubusercontent.com/5915590/97402967-88ee3780-18c1-11eb-8b53-6fda10d691dd.png)

**Comment by dotneft** [comment]
Yes, you need put these certs :-)

**Comment by antigenius0910** [comment]
ok so this build has the SAML option. registry.connect.redhat.com/zabbix/zabbix-appliance-50:5.0.4
No need to troubleshoot on 5.0.0beta1 problem. closing this ticket now. thanks
