### ISSUE TITLE
Please bump zabbix-agent v2 to 5.2.0

### ISSUE THREAD

**Issue by paskal** [zabbix/zabbix-docker#758]
Hi there, thanks for your amazing work! It's truly a pleasure to work with Zabbix in docker.

However, because of [the bug](https://support.zabbix.com/browse/ZBX-18591) agent image under tag `5` should be updated to 5.2, as the server image is upgraded already and at the time of writing client v5.0 is not working with server v5.2.

**Comment by dotneft** [comment]
I see, Zabbix agent 2 will be available soon, it has building issue on ARM v7 platform.

**Comment by dotneft** [comment]
I'm talking about https://support.zabbix.com/browse/ZBX-18505 issue. I started to build trunk Agent 2 image, so it must be available soon.

**Comment by dotneft** [comment]
So, trunk image is done. Feel free to use it till 5.0.6 release will be available.

**Comment by paskal** [comment]
Would you be so kind as to bump latest and alpine-5.0-latest and other tags as well? And also, I am not sure 5.0.6 will fix a problem for me, I was expecting 5.2 release. I am assuming that the problem I linked in the original message is not yet fixed in 5.0.6.

**Comment by dotneft** [comment]
You need to wait 5.2.1 version in this case.

**Comment by paskal** [comment]
Okay, thank you!

**Comment by chrisleekr** [comment]
@dotneft I know you are working on it. Any idea when will release zabbix-agent2:alpine-5.2.0?

**Comment by dotneft** [comment]
This week. I hope :-)

**Comment by dotneft** [comment]
We released Zabbix 5.2.1, updated image will be available in a few hours.

**Comment by paskal** [comment]
Works like a charm, thank you!
