### ISSUE TITLE
Question: Zabbix docker in production 

### ISSUE THREAD

**Issue by eran101** [zabbix/zabbix-docker#759]
Is it recommended to use Zabbix docker images in production?
For example, the VM appliance is not for production use according to the documenation.

**Comment by dotneft** [comment]
Feel free to use VM appliance and Docker images for production. VM appliance does not have any limitations at all.

**Comment by eran101** [comment]
> Feel free to use VM appliance and Docker images for production. VM appliance does not have any limitations at all.

Here is what the documentation says:
"The Appliance is not intended for serious production use."
https://www.zabbix.com/download_appliance
