### ISSUE TITLE
Cannot start service zabbix-server: invalid header field value "oci runtime error: container_linux.go:247

### ISSUE THREAD

**Issue by patsevanton** [zabbix/zabbix-docker#76]
cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

docker info
Containers: 11
 Running: 4
 Paused: 0
 Stopped: 7
Images: 16
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-8:2-538046865-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.379 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105 GB
 Metadata Space Used: 6.087 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 15.02 GiB
Name: zabbix.local
ID: 3YMA:L65F:P7N3:WLOE:CZUW:JFLW:KKPT:AQ72:M3QW:BT7C:DKCB:XGQR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

cd zabbix-docker
docker-compose -f ./docker-compose_v2_ubuntu_pgsql_latest.yaml up -d

ERROR: for zabbix-server  Cannot start service zabbix-server: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/etc/timezone\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/devicemapper/mnt/6ef9fd12f3485ea8ecdebbca6e8e025afb7ca418035ff02b0362b8294888ae26/rootfs\\\\\\\" at \\\\\\\"/var/lib/docker/devicemapper/mnt/6ef9fd12f3485ea8ecdebbca6e8e025afb7ca418035ff02b0362b8294888ae26/rootfs/etc/timezone\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
ERROR: Encountered errors while bringing up the project.

**Comment by dotneft** [comment]
do you have /etc/localtime on host machine?

**Comment by skloeckner** [comment]
I just ran into this issue on my Arch machine. It may have something to do with systemd.

Read here for more info:

https://github.com/moby/moby/issues/28109

**Comment by patsevanton** [comment]
I think because centos 7.
I am sorry. I cannot check now.

**Comment by dotneft** [comment]
Ok. I will check it :)

**Comment by dotneft** [comment]
It is known issue with docker. Please try to update the kernel to at least 3.18: https://github.com/moby/moby/issues/10294 and https://github.com/moby/moby/issues/12488

**Comment by kylixs** [comment]
cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

Just comment every  '/etc/timezone' mapping in docker-compose_v2_ubuntu_mysql_latest.yaml, and it works fine, zabbix web monitor http response time is ok now.

  volumes:
   - /etc/localtime:/etc/localtime:ro
#   - /etc/timezone:/etc/timezone:ro
