### ISSUE TITLE
zabbix-appliance docker image not updated to latest version

### ISSUE THREAD

**Issue by mapsrof** [zabbix/zabbix-docker#760]
Seems like the appliance doesn't update since the last one was 8 months ago and is still version 4.4 or 5.0.

https://hub.docker.com/r/zabbix/zabbix-appliance/builds

**Comment by dotneft** [comment]
It is deprecated: https://github.com/zabbix/zabbix-docker/blob/4.0/zabbix-appliance/alpine/README.md. I updated information in Docker Hub. Thank you!
