### ISSUE TITLE
zabbix appliance CentOS latest does not work

### ISSUE THREAD

**Issue by Hiroki114** [zabbix/zabbix-docker#762]
hi, I try to use centos-latest on CentOS 8.1 Docker.
docker run command is "docker run -p 80:80 -p 10051:10051 -e PHP_TZ=Asia/Tokyo -d     zabbix/zabbix-appliance:centos-latest" .
is this image is can use?

**Comment by dotneft** [comment]
Please be careful! Zabbix appliance is deprecated, please, use images per each component:

> Important information:_ Zabbix Docker Appliance image has been decommissioned and will not be available for 3.0.31, 4.0.19, 4.4.7, 5.0.0 and newer releases. Please use a separate Docker image for each component instead of the all-in-one solution.

**Comment by Hiroki114** [comment]
thanks for reply .
why appliance is ? and other images(ex, alpine) is same ?

**Comment by dotneft** [comment]
All Zabbix appliance images, except RHEL based one. Because it is not true Docker way.
