### ISSUE TITLE
The configuration of /etc/zabbix/zabbix_server.conf becomes invalid after restart

### ISSUE THREAD

**Issue by myzhuh** [zabbix/zabbix-docker#763]
I deployed zabbix using docker. The version is 5.2.1. After the deployment was completed, an error of Zabbix icmp pinger processes more than 75% busy occurred. Therefore, I tried to change the StartPingers in the /etc/zabbix/zabbix_server.conf file. It was set to 5. After the setting was completed, I restarted the container to make the configuration take effect, but after the restart, I found that the new configuration I added was gone.
![image](https://user-images.githubusercontent.com/71317399/99649448-2e469680-2a8f-11eb-920d-0978fee75131.png)

**Comment by dotneft** [comment]
Of course, it is docker image :-) Please use env variables according documentation to manage configuration params.

**Comment by myzhuh** [comment]
> Of course, it is docker image :-) Please use env variables according documentation to manage configuration params.

thank you , it works
But here is something abnormal
![image](https://user-images.githubusercontent.com/71317399/99672068-dd926600-2aad-11eb-93fe-6291a37e339a.png)

**Comment by dotneft** [comment]
Do not have and idea, probably some issue with Zabbix web. Did you try to use private mode browsing? Just to exclude browser cache.

**Comment by myzhuh** [comment]
> Do not have and idea, probably some issue with Zabbix web. Did you try to use private mode browsing? Just to exclude browser cache.

I use chrome 86 and MS edge both have this problem. I still have this problem after clearing the cache.

**Comment by dotneft** [comment]
Is it still actual? I think it is better to check Zabbix forum and bug issue tracker to check the issue, as it is not related to images, I'm closing the issue.
