### ISSUE TITLE
how to monitor host processes with zabbix 3.4.12 in docker

### ISSUE THREAD

**Issue by matian2014** [zabbix/zabbix-docker#764]
Hello, I start zabbix/zabbix-agent:ubuntu-3.4.12 in docker on my ubuntu host, and the cmd is:

`
docker run \
        --privileged \
        --net=host \
        -v /proc:/host/proc:ro \
        -v /sys:/host/sys:ro \
        -v /dev:/host/dev:ro \
        -v /etc:/host/etc:ro \
        -e ZBX_HOSTNAME=$HOSTNAME \
        -e ZBX_SERVER_HOST="xxxxxxx" \
        -e ZBX_SERVER_PORT="xxxx" \
        -e ZBX_PASSIVE_ALLOW="false" \
        -e ZBX_STARTAGENTS="0" \
        -e ZBX_DEBUGLEVEL="5" \
        -d \
         zabbix/zabbix-agent:ubuntu-3.4.12
`

and in this way the agent get the processes items in template Template OS Linux Active, such as proc.num, but these are processes in zabbix agent's container.
Can I get the host's processes info?
Thank you

**Comment by dotneft** [comment]
Why you link dev and other things to /host/ directory? Actually --privileged must be enough to "see" host processes.

**Comment by matian2014** [comment]
I remove links, the metrics, such as cpu and memory, works well.
But “Number of processes” and "Number of running processes", which use keys "proc.num[]" and "proc.num[,,run]", get result for docker container. The Number of processes in host is more than 10000, but the agent return 4(the num in its container).
How can I make it return the result from my host?

**Comment by dotneft** [comment]
Try to start the container under root user.

**Comment by matian2014** [comment]
Ok, I use your command, "--pid host" works well!
Thanks~~
