### ISSUE TITLE
There is not zabbix appliance tag or iso 

### ISSUE THREAD

**Issue by aghayari** [zabbix/zabbix-docker#766]
hi dears,

There is no zabbix appliance version 5.0 or 5.2 tag ( in [address](https://access.redhat.com/containers/?tab=tags&platform=docker#/registry.connect.redhat.com/zabbix/zabbix-appliance)) and iso in [ftp](http://ftp.redhat.com/pub/redhat/containers/) , so please check and help me.

**Comment by dotneft** [comment]
Zabbix Appliance is available on official RedHat marketplace: https://catalog.redhat.com/software/containers/zabbix/zabbix-appliance-50/5f0dcf09ecb5245089451299

Zabbix 5.2 is not available on RedHat at this moment.
