### ISSUE TITLE
docker-compose includes everything

### ISSUE THREAD

**Issue by thematrixdev** [zabbix/zabbix-docker#767]
Hello there,

I have found docker-compose_v3_alpine_mysql_latest.yaml includes apache besides nginx. I think the apache one is not needed, right?

**Comment by aminvakil** [comment]
As https://www.zabbix.com/documentation/current/manual/installation/containers#docker_compose has stated:

> Zabbix provides compose files also for defining and running multi-container Zabbix components in Docker. These compose files are available in Zabbix docker official repository on github.com: https://github.com/zabbix/zabbix-docker. These compose files are added as examples, **they are overloaded**. For example, they contain proxies with MySQL and SQLite3 support.

So I think you should pick the services you want in docker compose and remove the other stuff.
