### ISSUE TITLE
 Docker Compose which also works in the portainer web editor

### ISSUE THREAD

**Issue by fagnerpatricio** [zabbix/zabbix-docker#768]
Hi!
Would it be possible to make a version of the composer that works in the portainer's web editor?

Some used options that work in Docker-Compose are not accepted by the portainer web editor, and I would like to launch the stack over there

Thank You

**Comment by dotneft** [comment]
What is difference?

**Comment by JHBoricua** [comment]
That's a Portainer issue, IMHO. They still don't support anything higher than docker compose version 2 in their web frontend. Supposedly they announced that they'll add support for version 3 in Portainer 2.0, but I haven't seen it working yet.

You could always just use docker-compose directly and not rely on Portainer. I know, not as pretty as a web based GUI, but still fully functional.
