### ISSUE TITLE
proxy "zabbix-proxy-sqlite3" not found

### ISSUE THREAD

**Issue by nnsimha** [zabbix/zabbix-docker#769]
am trying to do docker-compose up of https://raw.githubusercontent.com/zabbix/zabbix-docker/5.2/docker-compose_v3_ubuntu_pgsql_latest.yaml..i remvoed MYSQL stuff and added only postgress/zabbix/and other required ones

 i see bunch of errors on zabbix-proxy-sqlite3 and on zabbix-server containers like this

252:20201210:054738.185 cannot parse proxy data from active proxy at "172.16.238.5": proxy "zabbix-proxy-sqlite3" not found
   252:20201210:054739.281 cannot parse proxy data from active proxy at "172.16.238.5": proxy "zabbix-proxy-sqlite3" not found
   252:20201210:054740.313 cannot parse proxy data from active proxy at "172.16.238.5": proxy "zabbix-proxy-sqlite3" not found
   251:20201210:054741.318 cannot parse proxy data from active proxy at "172.16.238.5": proxy "zabbix-proxy-sqlite3" not found

unable to identiy where the issue is
please help

**Comment by dotneft** [comment]
You need add proxy with zabbix-proxy-sqlite3 name in web-interface.

**Comment by nnsimha** [comment]
is it not possible with adding in docker files,,
am running docker-compose ,but this is straightway giving error

**Comment by dotneft** [comment]
It does not make sense to add such configuration to dockerfiles, because name can be different.
