### ISSUE TITLE
Switch tagging from "type-x.y.z" to "x.y.z-type"

### ISSUE THREAD

**Issue by syphernl** [zabbix/zabbix-docker#774]
Would it be possible to swap the tagging of the containers from `type-x.y.z` to `x.y.z-type`? 
For instance: `zabbix/zabbix-server-pgsql:alpine-5.2.2` would become `zabbix/zabbix-server-pgsql:5.2.2-alpine`. 

This makes it possible for apps like [Renovate](https://docs.renovatebot.com/docker/#version-compatibility) to automatically update Dockerfiles in local repositories.

**Comment by fpaternot** [comment]
Did you try Renovate regex syntax for versioning with current model?

https://docs.renovatebot.com/modules/versioning/#regular-expression-versioning

The example code seems right on with what we already have:

```
"versioning": "regex:^(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))?(-(?<compatibility>.*))?$"
```

**Comment by syphernl** [comment]
@fpaternot That particular versioning rule is _exactly_ how I would hope to see the tags for the Zabbix containers 😉

The current situation of tags is probably more like this instead: 
```
"versioning": "regex:^((?<compatibility>.*)-)(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)(?<prerelease>[^.-]+)?$"
```

I am currently testing out this regex to see if it works for now. 
However, I still think it would still be a better move to swap around these tagging since it feels more clean. 
Other projects (e.g. Wordpress, MariaDB, Traefik, etc etc) are also doing it that way (`x.y.z-type`).

**Comment by dotneft** [comment]
It is a bit difficult to change tags right now. Many people use already existing tag naming. Do you think all other projects use suggested by you style?

**Comment by fpaternot** [comment]
I'd like to suggest that big changes like this one should only take effect between major versions and be documented in release notes (https://www.zabbix.com/rn/rn5.0.0rc1).

Reccently we had a major OS upgrade between minor versions (5.02 -> 5.0.3) and that breaks other people who build on top of this images.

So, if approved, for images in 5.4+ we would change the image tagging schema but not for older images.
