### ISSUE TITLE
Image zabbix-server-pgsql:alpine-5.2.3 is missing

### ISSUE THREAD

**Issue by kashikoy** [zabbix/zabbix-docker#775]
Hello,

I am looking for zabbix-server-pgsql:alpine-5.2.3 on docker hub, ubuntu and centos have been published but not alpine.
Maybe it's too soon.

Thank you.

**Comment by dotneft** [comment]
I'm looking too :-) Looks like GitHub has some performance issues and can not perform actions.

**Comment by dotneft** [comment]
I'm pretty sure it is some building machine issue: https://github.com/zabbix/zabbix-docker/runs/1596701044?check_suite_focus=true#step:8:1118

**Comment by kashikoy** [comment]
You're right,  https://github.com/zabbix/zabbix-docker/runs/1596648197?check_suite_focus=true (tag 5.2.3) failed.
But the new building has succeeded : https://github.com/zabbix/zabbix-docker/runs/1596700790?check_suite_focus=true (tag alpine-latest).

So, I can use this image ! Thank you.

**Comment by dotneft** [comment]
Fixed!
