### ISSUE TITLE
Swarm Incompatibility

### ISSUE THREAD

**Issue by jonatanmenghetti** [zabbix/zabbix-docker#776]
When running docker in swarm mode, cannot set hostname for container and not possible running agents or proxy in active mode.

**Comment by dotneft** [comment]
Oook. What do you suggest? :-)

**Comment by fpaternot** [comment]
What do you mean by `not possible running proxy in active mode`? I run proxy active and i use swarm (but i addmit i don't use supplyed yaml files).

For proxy, one just need to know the service name and set the env ZBX_SERVER_HOST accordingly.

From what i remmember, its pretty much the same for zabbix_agent, except that you cannot set the hostname. So just set it as network_mode == host to get the same hostname as docker host (see https://docs.docker.com/compose/compose-file/compose-file-v3/#network-configuration-reference).

Remmeber, as you are now defining the network from docker host, you must define ZBX_SERVER_HOST with an address exposed from swarm, you cannot define a network overlay in here.
