### ISSUE TITLE
ARM64 builds don't start on Apple Silicon Mac

### ISSUE THREAD

**Issue by fibbs** [zabbix/zabbix-docker#777]
Using Docker Desktop Preview from here: https://www.docker.com/blog/download-and-try-the-tech-preview-of-docker-desktop-for-m1/ on a brand new M1 Mac.

Checked out the platform linux/arm64 is supported by the images provided.

Tested `docker run -ti zabbix/zabbix-agent:centos-5.2-latest`

Got:
```
/lib64/ld-linux-x86-64.so.2: No such file or directory
```

I am not a multi-arch expert myself yet, but something is wrong here.... Apparently the x86_64 images are labelled as arm64?

**Comment by fibbs** [comment]
OK, this does not seem to be an issue with Zabbix-docker at all. The images provided run perfectly when using the ubuntu-* ones. Only the centos-* images fail this way, and they also do if building docker images yourselves. Didn't yet find out why....

**Comment by fibbs** [comment]
Found it. It's the tiny binary you download directly from github. This is the AMD64 binary, even if there are those for other architectures available. Unfortunately, I don't know enough to make a good pull request to fix this correctly.

**Comment by dotneft** [comment]
Which one?

**Comment by fibbs** [comment]
All the centos based images that contain the tini "init" utility don't start on non-AMD64 platforms.

**Comment by dotneft** [comment]
You are right! Will be fixed soon!

**Comment by dotneft** [comment]
Fixed! Please check it again.

**Comment by fibbs** [comment]
Works perfectly. Nicely solved.
