### ISSUE TITLE
Using postgres:alpine instead of debian based postgres:latest

### ISSUE THREAD

**Issue by sumitgoelpw** [zabbix/zabbix-docker#778]
The alpine docker-compose files use a non-alpine Postgres image. Is there any specific reason for not using `postgres:alpine`?

**Comment by dotneft** [comment]
what do you mean? Where is non-Postgres?

**Comment by sumitgoelpw** [comment]
These are a couple of Alpine based docker-compose files in the root of the 5.2 branch.

[docker-compose_v3_alpine_pgsql_latest.yaml](https://github.com/zabbix/zabbix-docker/blob/5.2/docker-compose_v3_alpine_pgsql_latest.yaml)
[docker-compose_v3_alpine_pgsql_local.yaml](https://github.com/zabbix/zabbix-docker/blob/5.2/docker-compose_v3_alpine_pgsql_local.yaml)

These are using `postgres:latest` image which is Debian based instead `postgres:alpine`.

**Comment by dotneft** [comment]
Alpine in the name is related to Zabbix images only. We do not care what OS base image is used in other images.

**Comment by sumitgoelpw** [comment]
I understand. Can I request to consider switching to `postgres:alpine` in the docker-compose files? It will reduce the disk space requirements and download time. It is primarily very helpful in the Github actions to spin up a Zabbix instance using these docker-compose files to run tests. I maintain the [zabbix-promise](https://github.com/sumitgoelpw/zabbix-promise) and [deno-zabbix](https://github.com/sumitgoelpw/deno-zabbix) libraries and would love to rely on the official docker-compose files.

**Comment by dotneft** [comment]
Updated! Thank you!
