### ISSUE TITLE
mysql image has no arm64/aarch64 candidate

### ISSUE THREAD

**Issue by fibbs** [zabbix/zabbix-docker#779]
The mysql server image used in the docker-compose files, `mysql:8.0` is only provided for amd64 platform, but not for arm64. Seems like there is another official mysql server image: https://hub.docker.com/r/mysql/mysql-server that is supported for both architectures. Maybe switching to use this instead would make also the mysql parts of the docker-compose files work on arm64 machines?

**Comment by dotneft** [comment]
Yes, but I'm not sure that both images are identical. At least in suggested image no MYSQL_PASSWORD as file implementation: https://github.com/mysql/mysql-docker/blob/mysql-server/8.0/docker-entrypoint.sh. I do not think it is a good idea to switch them in Compose examples.

**Comment by dotneft** [comment]
Congratulations! Now https://hub.docker.com/r/mysql/mysql-server/tags?page=1&ordering=last_updated has ARM64 tag as well :-)
