### ISSUE TITLE
log format broken in zabbix/zabbix-snmptraps:alpine-5.0.7

### ISSUE THREAD

**Issue by ryn9** [zabbix/zabbix-docker#783]
The snmp config changes fromzabbix/zabbix-snmptraps:alpine-5.0.6 to zabbix/zabbix-snmptraps:alpine-5.0.7 appears to have broken the output format. I would imagine the ubuntu and centos variants are impacted as well.

It appears the new formatting, defined in /etc/snmp/snmptrapd.conf, does not match the logformat which used to be defined in snmptrapfmt.conf

From the 5.0.6 snmptrapfmt.conf file:
```
# LOGFMT="format string for logfile entry"
#   specify the output of the logfile entry;
#   special char recognized:
#    \n  ... newline
#    \r  ... carriage return
#    \t  ... horizontal tab
#    \\  ... backslash
#    $#  ... number of variables in the trap
#    $*  ... print all variables of the trap as specified in VARFMT
#    $x  ... date the trap was received (YYYYMMDD.HHMMSS)
#    $r  ... the implied source of the trap (agent address) (see NODEFMT)
#    $R  ... the true source of the trap (via transport layer) (see NODEFMT)
#    $$  ... the character '$'
#    $e  ... the enterprise of the trap as specified in OIDFMT
#    $A  ... the trap agent address as specified in NODEFMT
#    $G  ... the trap generic number
#    $S  ... the trap specific number
#    $T  ... the trap's sysUpTime timestamp (in seconds)
#    ordinary characters represent themselfes
#   Default: "$x;$A;$e;$G;$S$*"
#LOGFMT="\n$$x=$x\n$$r=$r\n$$R=$R\n$$e=$e\n$$A=$A\n$$G=$G\n$$S=$S\n$$T=$T\n$$#=$#$*"
LOGFMT="$x ZBXTRAP $R $G $S $e $*"
```

From the 5.0.7 snmptrapd.conf file:
```
snmpTrapdAddr udp:0.0.0.0:1162

doNotFork yes
pidFile /tmp/snmptrapd.pid
doNotRetainNotificationLogs yes

authCommunity log,execute,net public
disableAuthorization yes

format1 %V\n%.4y%.2m%.2l.%.2h:%.2j:%.2k ZBXTRAP %A\n%b\n%v\n
format2 %V\n%.4y%.2m%.2l.%.2h:%.2j:%.2k ZBXTRAP %A\n%b\n%v\n

[snmp] logOption f /var/lib/zabbix/snmptraps/snmptraps.log
```

Examining the output showed a number of differences in the log output, which impacted readability from Zabbix
- Time format went from 20210106.215900 (example) to 20210106.22:00:00 (example).
- All entries showed being source from address 0.0.0.0 instead of the real address.
- The message after the source address had a number of differences and contains a number of new lines

Unfortunately - I cannot provide examples at this time.

Reverting to 5.0.6, with everything else being the same, fixes the issues I am seeing.

**Comment by dotneft** [comment]
I agree with you. The format is changed a bit, also no more additional handlers (no more snmptrapfmt). Do you think the format must be the same?

**Comment by ryn9** [comment]
As the zabbix server and/or zabbix proxy reads these logs in accordance to certain parsing rules - changing this format is quite impactful.

Changes to the date format - for example - would mean changing the date format defined for each 'snmp trap' item using the previous format.

Changes that introduce new lines will break the regexp engine - as it does not support Multi-line regexp (referenced here: https://www.zabbix.com/documentation/5.0/manual/config/items/itemtypes/snmptrap)

Changes to the message payload - in general - could break item's regexp definitions.

While format changes could be possible - it probably needs to be better thought out.

**Comment by dotneft** [comment]
Sorry, but I think you can use multiline regexp. Without any issues. For example:
```
((?m)test4.*)
```
and input:
```
test1
test2
test3
test4
test5
```

You can test on https://regex101.com. Also using preprocessing you can extract everything as you want :-)

**Comment by ryn9** [comment]
This says multi-line regexp not supported -> https://www.zabbix.com/documentation/5.0/manual/config/items/itemtypes/snmptrap)

Regardless - the changes to the format will break the previously configured timestamp parsing and likely break regexp parsers people have configured against the snmp log lines

**Comment by dotneft** [comment]
No problem with multiline. Try my regex :-)

Yes, I agree with you, the format will break currently configured items. You can update it using SQL:
```
update items logtimefmt = "<new format>" set where type = 17 and logtimefmt = "<old format>";
```

**Comment by ryn9** [comment]
That may be used to address changes in the format of the time string, it wouldn't address regexp expressions in the snmptrap keys (ie ... snmptrap[regexp]).

**Comment by dotneft** [comment]
regex can be used in snmptrap key without any issues:

<img width="1079" alt="Screenshot 2021-01-08 at 17 27 38" src="https://user-images.githubusercontent.com/10911965/104032565-00501980-51d7-11eb-9b9e-23719803d4a4.png">
<img width="824" alt="Screenshot 2021-01-08 at 17 27 43" src="https://user-images.githubusercontent.com/10911965/104032573-034b0a00-51d7-11eb-9bb6-b7f6206d0ed2.png">

**Comment by ryn9** [comment]
What I am saying is the log message payloads are changing.
As such - existing regexp expressions against the logs are at risk of breaking.

**Comment by KalenXI** [comment]
I'm running into problems with this as well. Specifically the "ZBXTRAP %A" is problematic.

According to the snmptrapd manual the %A format definition only works on SNMPv1 traps, using it in the SNMPv2 trap format results in it printing an IP of 0.0.0.0 for all v2c traps which breaks Zabbix's host matching.

The %b in the next line does print the correct IP address for v2c traps in the format of "UDP: [10.148.74.25]:59204->[172.17.0.11]:1162" but as far as I'm aware Zabbix does not parse this to determine the correct origin IP.

**Comment by dotneft** [comment]
Probably it is better to switch to "%B" ? What do you think?

**Comment by grcastleton** [comment]
> Probably it is better to switch to "%B" ? What do you think?

I just tried %B. Result is:

`20210126.20:34:32 ZBXTRAP UDP: [10.255.16.66]:162->[172.17.0.5]:1162`

Which is still not parsed by Zabbix.

**Comment by rvandomp** [comment]
I tried this using 5.2.3 image and can get V1 traps into zabbix OK but v2 traps have message in log file
unmatched trap received from "0.0.0.0": 20210126.15:18:09 UDP: [142.xxx.xxx.xxx]:58778->[142.xx.xx.xx.xx]:1162
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (3092027873) 357 days, 20:57:58.73
SNMPv2-MIB::snmpTrapOID.0 = OID: NET-SNMP-EXAMPLES-MIB::netSnmpExampleHeartbeatNotification
NET-SNMP-EXAMPLES-MIB::netSnmpExampleHeartbeatRate = INTEGER: 123456

I wonder if changing the the format2 entry will work
should the format2 entry be  %V\n%.4y%.2m%.2l.%.2h:%.2j:%.2k ZBXTRAP **%b**\n%b\n%v\n ? 

I am pretty new to K8s and docker so I am not sure on how to modify my image file to test this

**Comment by rvandomp** [comment]
I am not sure if it would just put the IP or would simply repeat the entire UDP: [10.255.16.66]:162->[172.17.0.5]:1162 entry. It looks like from above that it would.

**Comment by dotneft** [comment]
Yeah... it is bad, so it looks like I need to use SNMP-Perl handler with backward compatibility.  We used custom snmptrapfmt but no chance to compile it on modern systems.

**Comment by zephyia** [comment]
Any suggestions on what to do to get this working with SNMPv2 / v3 traps - it is def. broken - is there a suggested work around?

**Comment by ryn9** [comment]
@zephyia currently I am holding on to using zabbix/zabbix-snmptraps:alpine-5.0.6, where it is working as expected (in our setup at least)

**Comment by dotneft** [comment]
We have updated master with two possible options: one line and new line for each varbind. It will be available in other versions soon.

**Comment by zephyia** [comment]
Thanks, for now we have injected a modified zabbix-trap-receiver.pl script into the container and modified snmptrapd accordingly

**Comment by dotneft** [comment]
Fixed!
