### ISSUE TITLE
Zabbix Docker Proxy not sending SNMP traffic (to Zabbix Server)

### ISSUE THREAD

**Issue by lorenzzz987** [zabbix/zabbix-docker#784]
My Zabbix Docker Proxy (MySQL) is not sending SNMP traffic from WatchGuard M270 to the Zabbix Server (CentOS). Already tried ncat to check if traffic is allowed through firewall on port 161 UDP. Monitoring the proxy on the firewall and only 10051 tcp traffic showing up (from proxy to server), but no traffic on port 161 UDP. Also checked and confirmed MiB files having the WatchGuard Mibs. Docker logs from proxy don't show anything odd and proxies are showing up in Zabbix, but no SNMP Green tag (yes it's an active proxy) or data showing up. Any suggestions?

**Comment by dotneft** [comment]
Looks like proxy does not know about SNMP hosts. Please check proxy DB. Does it contain items and hosts?

**Comment by lorenzzz987** [comment]
When I triggered docker-compose down, the persistent DB volume caused the DB container to contain it's old configuration (not using docker volume but static route, bad practice. The backend Zabbix server was running version 5.0.x, the proxy had the latest flag causing it to use version 5.2.x. This caused a database error like " failed to update local proxy configuration copy: database error". Giving the zabbix proxy an explicit version and deleting the '/var/lib/mysql' volume to be rebuild resolved my issue. Thank you for pointing me in the Database direction!
