### ISSUE TITLE
Autoregistration registering with wrong IP Address

### ISSUE THREAD

**Issue by bth8939** [zabbix/zabbix-docker#785]
Hello,

I have an problem with the autoregistration. 

The agent is registering with a wrong IP address (IP loadbalancer). 

Zabbix server is in kubernetes infrastructure. 

Load Balancer( NLB)  => Zabbix server (POD) kubernetes  

Client: 

Ec2 instance (agent zabbix) => Load Balancer( NLB)  => Zabbix server (POD) kubernetes  

Can you help me please?

**Comment by dotneft** [comment]
You can use HostInterface (ZBX_HOSTINTERFACE) or HostInterfaceItem (ZBX_HOSTINTERFACEITEM) to specify correct IP or DNS.

**Comment by bth8939** [comment]
Hello,

Thanks you for your reply. 

I upgraded my agent and now i have access on parameter ZBX_HOSTINTERFACE. 

great
