### ISSUE TITLE
 cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)

### ISSUE THREAD

**Issue by liudianwei** [zabbix/zabbix-docker#786]
![image](https://user-images.githubusercontent.com/28178193/104711453-5b948580-575c-11eb-9529-09e0c54dfb9c.png)
 
it may can not read data from the exist db file, it should be like this
![image](https://user-images.githubusercontent.com/28178193/104711584-82eb5280-575c-11eb-986e-6e50b2ba3dde.png)

I don't konw why.... maybe this can help some people

**Comment by liudianwei** [comment]
it may cause like this:
![image](https://user-images.githubusercontent.com/28178193/104712349-67347c00-575d-11eb-849f-c05e71133eca.png)

**Comment by tekintian** [comment]
is your mysql version is mysql 8.0 ?

I have the same problem, because my mysql version is 5.7,   change the mysql version to 8.0 is OK!
