### ISSUE TITLE
SMTP issue 

### ISSUE THREAD

**Issue by mgori24** [zabbix/zabbix-docker#788]
Gents, 
I'm running Zabbix in a container. I'm using zabbix version 5. I have did the email configuration in order to send an email notification. I have the following error "An authentication function returned an error". I'm using starttls as connection security. Please any advise to fix this problem.

**Comment by dotneft** [comment]
Probably it is better to check https://www.zabbix.com/forum/. As it is not related directly to Docker images.

**Comment by mgori24** [comment]
> Probably it is better to check https://www.zabbix.com/forum/. As it is not related directly to Docker images.

Thanks
