### ISSUE TITLE
agent2 - environment variable to activate docker monitoring misssing

### ISSUE THREAD

**Issue by svenblum** [zabbix/zabbix-docker#790]
Hi,

I'd like to monitor docker containers with agent2. If I install it manually, uncommenting "Plugins.Docker.Endpoint=unix:///var/run/docker.sock" in /etc/zabbix/zabbix_agent2.conf works fine. If I install agent2 as a container with a YML I write the config with environment-variables. Unfortunately there is no variable "ZBX_Plugins.Docker.Endpoint" available to configure. 

If this isn't an issue - any help to configure this properly is very welcome.

thank you!!
Sven

https://hub.docker.com/r/zabbix/zabbix-agent2
https://www.zabbix.com/documentation/current/manual/appendix/config/zabbix_agent2

**Comment by dotneft** [comment]
Please use include files. It is very hard to prepare env variables for each param in Zabbix agent 2

**Comment by svenblum** [comment]
thank you! I tried to include a config - but it's not working as expected...
in my yml-file I added:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent-config/:/etc/zabbix/zabbix_agentd.d/

in /agent-config i have one file "allow_docker.conf" with one line: Plugins.Docker.Endpoint=unix:///var/run/docker.sock

Am I missing something?

**Comment by dotneft** [comment]
please check #710

**Comment by svenblum** [comment]
Alexey, 
thank you! Adding
  `user: 0:0`
to my yml did the trick.

on the other hand I still don't know what was wrong with the "include config"-way...
