### ISSUE TITLE
Agent2 Installation Problem & MQTT Support

### ISSUE THREAD

**Issue by takai-sama** [zabbix/zabbix-docker#792]
I have trouble installing agent2 on zabbix 5.2.3 (I am using Ubuntu 18)
https://hub.docker.com/r/zabbix/zabbix-agent2
1. I got an error when "Connects from Zabbix server or Zabbix proxy in other containers (Passive checks)" and "Connect to Zabbix server or Zabbix proxy containers (Active checks)" how to solve this? is this step mandatory? Is the tag available only alpine?
<img width="703" alt="1" src="https://user-images.githubusercontent.com/77669943/105155503-442f1100-5b3d-11eb-8833-5f856fd34828.PNG">

2. agent2 already supports mqtt, how do I use it? I want to monitor the tool by creating items with the key "mqtt.get" but the data does not appear in "latest data". I followed this tutorial https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/src/go/plugins/mqtt?at=refs%2Fheads%2Frelease%2F5.2
<img width="642" alt="item" src="https://user-images.githubusercontent.com/77669943/105155553-54df8700-5b3d-11eb-93e0-9c5b8651685a.PNG">
<img width="677" alt="host" src="https://user-images.githubusercontent.com/77669943/105155560-5610b400-5b3d-11eb-88e5-146f3a82b651.PNG">

**Comment by dotneft** [comment]
Did you resolve the issue? I tried MQTT monitoring through Docker and it works :-)
