### ISSUE TITLE
agent-addr field of the PDU always 0.0.0.0 After upgrade to 5.2

### ISSUE THREAD

**Issue by grcastleton** [zabbix/zabbix-docker#794]
Since upgrading both the server and snmptrapd containers to 5.2 we have been having a problem where received traps are not attached to hosts in Zabbix. This appears to be because the agent-addr field of the PDU always translates to 0.0.0.0. 

Here's our snmptrapd.conf file:
```
snmpTrapdAddr udp:0.0.0.0:1162

doNotFork yes
pidFile /tmp/snmptrapd.pid
doNotRetainNotificationLogs yes

authCommunity log,execute,net public
disableAuthorization yes

format1 %V\n%.4y%.2m%.2l.%.2h:%.2j:%.2k ZBXTRAP %A\n%b\n%v\n
format2 %V\n%.4y%.2m%.2l.%.2h:%.2j:%.2k ZBXTRAP %A\n%b\n%v\n

[snmp] logOption f /var/lib/zabbix/snmptraps/snmptraps.log
```

The `%A` in format1 / format2 always comes through in the log file as '0.0.0.0' for example:

```
20210126.19:36:50 ZBXTRAP 0.0.0.0
UDP: [10.255.17.98]:162->[172.17.0.5]:1162
```

We are using IPv4 everywhere. The IP address in the second line of the example above is correct, presumably if that IP address were in place of 0.0.0.0 the trap would be attached to the correct host in Zabbix. There does not appear to be a format option in snmptrapd.conf that places just the bare source IP address in the log, though. 

It looks like non-docker Zabbix deployments recommend using snmptt or a perl script in-between snmptrapd and Zabbix, but snmptt doesn't appear to be included in this docker image.

Appreciate anyone’s  suggestions if we're just doing something wrong here.

**Comment by dotneft** [comment]
Known issue #783. Could you try to use "format2 %V\n%.4y%.2m%.2l.%.2h:%.2j:%.2k ZBXTRAP %B\n%b\n%v\n
" ?

**Comment by grcastleton** [comment]
Thank you! Closing as a dup of #783
