### ISSUE TITLE
[zabbix-proxy-sqilte] ZBX_LISTENIP not working

### ISSUE THREAD

**Issue by olivierbouffet** [zabbix/zabbix-docker#795]
Hi,

The environment variable ZBX_LISTENIP is not working . 

It could be fixed like that : 

```
diff --git a/proxy-sqlite3/alpine/docker-entrypoint.sh b/proxy-sqlite3/alpine/docker-entrypoint.sh
index ef13eb4b..3f8c5ca5 100755
--- a/proxy-sqlite3/alpine/docker-entrypoint.sh
+++ b/proxy-sqlite3/alpine/docker-entrypoint.sh
@@ -125,6 +125,7 @@ update_zbx_config() {
     fi

     update_config_var $ZBX_CONFIG "ListenPort" "${ZBX_LISTENPORT}"
+    update_config_var $ZBX_CONFIG "ListenIP" "${ZBX_LISTENIP}"

     update_config_var $ZBX_CONFIG "SourceIP" "${ZBX_SOURCEIP}"
     update_config_var $ZBX_CONFIG "LogType" "console"
```

Thanks in advance

**Comment by dotneft** [comment]
Why do you need it?

**Comment by olivierbouffet** [comment]
Because I want to run multiple proxy container on host network with different IP on the same machine

**Comment by dotneft** [comment]
why you can not run proxy container on different IP without host network?

**Comment by olivierbouffet** [comment]
In fact the agent can send data to my proxy, they will be several per node , and I do not want to change the port when sending data to the proxy.

So I need my proxy to listen a specific IP, which will be a VIP .

**Comment by dotneft** [comment]
docker run -p IP:host_port:container_port ?

**Comment by olivierbouffet** [comment]
To reach the proxy that's fine , but then the proxy itself perform check with the ip of the node , not the VIP . I need to use the VIP, because the range is trusted , not the node ip . 

I tried to use -e ZBX_SOURCEIP=MYVIP 

but the proxy can not contact the server to retrieve its configuration.

 `  165:20210209:121028.914 Unable to connect to the server [test-zabbix-5.xxxx.xxx]:10051 [bind() failed: [99] Cannot assign requested address]. Will retry every 1 second(s)`


The only way I found to make my "maybe strange" setup working is to specify the LISTENIP and the SOURCEIP with the container on the host network

**Comment by dotneft** [comment]
Understood, did you try to use external configuration file with ListenIP directive?

**Comment by olivierbouffet** [comment]
Nope, I saw that it was easy to fix the docker-entrypoint.sh , so I tried the change and rebuild the proxy, and my container is working.

**Comment by dotneft** [comment]
The bug fix will be available a bit later. So currently you can use external config :-)

**Comment by olivierbouffet** [comment]
OK thanks for your work .

**Comment by dotneft** [comment]
Added! Thank you!
