### ISSUE TITLE
ERROR when setting ZBX_SESSION_NAME in version 5.2.1 for zabbix-web-apache-pgsql

### ISSUE THREAD

**Issue by thebeerman** [zabbix/zabbix-docker#798]
I see when docker-entrypoint.sh when trying to set the ZBX_SESSION_NAME, the script errors with
cp: cannot stat '/include/defines.inc.php': No such file or directory

I noticed $ZBX_FRONTEND_PATH is not set.  

ZABBIX_WWW_ROOT="/usr/share/zabbix" is set, and is what was used in previous versions

    if [ -n "${ZBX_SESSION_NAME}" ]; the
        cp "$ZBX_FRONTEND_PATH/include/defines.inc.php" "/tmp/defines.inc.php_tmp"
        sed "/ZBX_SESSION_NAME/s/'[^']*'/'${ZBX_SESSION_NAME}'/2" "/tmp/defines.inc.php_tmp" > "$ZBX_FRONTEND_PATH/include/defines.inc.php"
        rm -f "/tmp/defines.inc.php_tmp"
    fi

**Comment by dotneft** [comment]
Thank you! Will be fixed soon!

**Comment by dotneft** [comment]
Fixed!
