### ISSUE TITLE
Zabbix server-mysql-ubuntu - /usr/bin/fping: can't open network socket

### ISSUE THREAD

**Issue by pandel** [zabbix/zabbix-docker#799]
Hi!

I built the Zabbix server-mysql-ubuntu image via docker-compose myself under Debian 10 and had to modify the Dockerfile by adding

`setcap cap_net_raw+ep /usr/bin/fping`

below https://github.com/zabbix/zabbix-docker/blob/00f65af06bba28ad58df8d717ad3baf4a8981945/server-mysql/ubuntu/Dockerfile#L66 

to avoid the message

`/usr/bin/fping: can't open network socket`

which led to all ICMP* tasks being disabled before.

I tried to solve the error only by adding different capabilities (NET_RAW, NET_ADMIN, SYS_ADMIN, ...) to the `docker-compose.yml`, but that didn't work.

Regards,
Holger

**Comment by dotneft** [comment]
Hmmm... I can not reproduce the issue. It works normally:
<img width="900" alt="Screenshot 2021-02-09 at 03 25 56" src="https://user-images.githubusercontent.com/10911965/107302832-a9b05680-6a86-11eb-8eb6-040d737fc84c.png">

 How do you start the container?

**Comment by pandel** [comment]
I simply built and started via docker-compose. I tried starting as root and non-root, but that made no difference. Perhaps it is something special with my setup I guess. Nevertheless, I wanted to make sure that if someone else has this problem, too, he can find out about this via my report.

**Comment by dotneft** [comment]
Do you use some special environment settings?

**Comment by pandel** [comment]
Nothing that I am aware of. Do you have an example of an environment setting that may have an impact on this?

**Comment by dotneft** [comment]
I just tried to build Ubuntu images on Debian 10 and I do not see any issues. Inside Zabbix server container:
```
$ getcap /usr/bin/fping
/usr/bin/fping = cap_net_raw+ep
```

**Comment by pandel** [comment]
@dotneft I can't say why it is working for you but not for me. To not overstress the my issue, I simply close it now. Maybe I am the only one having this problem, but I have no clue how to investigate. So, many thanks for your time and patience. Stay save!
