### ISSUE TITLE
Add unixODBC drivers

### ISSUE THREAD

**Issue by endersonmaia** [zabbix/zabbix-docker#80]
I use Zabbix to monitor SQL Server via unixODBC, I have my own Dockerfile to add the FreeTDS unixODBC drivers, so I can connect to it.

- [ ] PostgreSQL ( [alpine](https://pkgs.alpinelinux.org/package/v3.5/main/x86/psqlodbc), [ubuntu](http://packages.ubuntu.com/xenial/odbc-postgresql) )
- [ ] MySQL ( https://dev.mysql.com/downloads/connector/odbc/ )
- [ ] SQL Server ( [alpine](https://pkgs.alpinelinux.org/package/v3.5/main/x86/freetds), [ubuntu](http://packages.ubuntu.com/xenial/tdsodbc) )
- [ ] Oracle ( http://www.oracle.com/technetwork/database/features/oci/odbc-ic-releasenotes-094306.html )
- [ ] Informix ( http://www.unixodbc.org/doc/informix.html )
- [ ] DB2 ( http://www.unixodbc.org/doc/db2.html )

I think this should be available in this official image, and the ODBC configuration could be injected via volumes (/etc/odbc.ini, /etc/odbcinst.ini).

If the maintainers are OK with this approach, I can work on a PR for this.

Feel free to suggest other approaches to this issue.

**Comment by windsdeng** [comment]
Dockerfile  ?

**Comment by dotneft** [comment]
Zabbix images are provided as clean images. Feel free to add these drivers to images based on vanilla Zabbix images.

**Comment by JasperE84** [comment]
So for all those struggling with this, I added MS SQL Server support to a Zabbix docker image, by taking the following steps.
(I'm running a named SQL server instance)

First stop and clear the docker containers:
```
$ docker-compose stop
$ docker-compose rm -f
```
In docker-compose change:
```
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-6.2-latest
[etc]
```

To:
```
services:
  zabbix-server:
    build:
      context: ./build
      dockerfile: Dockerfile
[etc]
```

This tells docker to rebuild the zabbix image from the local instruction file called "Dockerfile"

Then from the path where docker-compose.yml is do
```
$ mkdir build
$ vi build/Dockerfile
```

And set Dockerfile content to:
```
FROM zabbix/zabbix-server-mysql:ubuntu-6.2-latest
USER root
RUN apt-get -y update && apt-get -y --no-install-recommends install tdsodbc freetds-dev freetds-bin freetds-dev

```

Now rebuild the docker image:
`$ docker-compose up -d --build --remove-orphans`

Add these volumes and environment vars to docker-compose.yml zabbix-server service:
```
  volumes:
    - ./zbx_env/etc/odbc/odbc.ini:/etc/odbc.ini:ro
    - ./zbx_env/etc/odbc/odbcinst.ini:/etc/odbcinst.ini:ro
    - ./zbx_env/etc/odbc/freetds.conf:/etc/freetds/freetds.conf:ro
  environment:
    - ODBCSYSINI=/etc
    - ODBCINSTINI=odbcinst.ini
    - ODBCINI=/etc/odbc.ini
    - ODBCSEARCH=ODBC_SYSTEM_DSN

```

freetds.conf:
```
[global]
        tds version = auto

[YOURDSNNAME]
        host = <SQL SERVER IP>
        instance = <SQL SERVER INSTANCE NAME>
        tds version = 7.2

```

odbc.ini:
```
[YOURDSNNAME]
Description             = MSSQL Server
Driver                  = FreeTDS
Trace                   = No
ServerName              = YOURSQLINSTANCENAME
Database                = YOURSQLDBNAME
TDS_Version             = 8

```

odbcinst.ini:
```
[FreeTDS]
Driver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
Setup = /usr/lib/x86_64-linux-gnu/libodbc.so.2
```

I'm not sure if all settings are exactly required as posted here, but this worked for me after, I admit, some trial and error.
