### ISSUE TITLE
Busybox container exited after start

### ISSUE THREAD

**Issue by Vibri87** [zabbix/zabbix-docker#802]
Hi, I using buxybox as db_data_pgsq, everything working well, but one container exited after start. Can you help me ?

db_data_pgsql:
  image: busybox
  volumes:
   - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw

**Comment by dotneft** [comment]
it is normal behaviour.

**Comment by Vibri87** [comment]
Ok, thanks.
