### ISSUE TITLE
Zabbix loss existing hosts

### ISSUE THREAD

**Issue by o51n** [zabbix/zabbix-docker#804]
Hello!  

From time to time zabbix starts to lose hosts and consider that they do not exist but they are created and displayed in the web interface.

An example of a created host with an agent at web interface:

![image](https://user-images.githubusercontent.com/54809700/108353739-86f60e80-71f9-11eb-8038-cadfbbb45964.png)

Logs from agent on this host: 

```
2021/02/18 14:05:53.833961 [101] no active checks on server [ZABBIX_SERVER_IP:10051]: host [ACC-SBL-Agent] not found
```

At the same time logs on server:

```
213:20210218:140453.833 cannot send list of active checks to "HOST_IP": host [ACC-SBL-Agent] not found
210:20210218:140654.836 autoregistration from "HOST_IP" denied (host:"ACC-SBL-Agent" ip:"HOST_IP" port:10050): connection type "TLS with PSK" is not allowed for autoregistration
``` 

But when updating the hostname to wrong one in web interface and then back to correct one everything becomse normal. 

Also sometimes when I trying update the some host or template in web interface strange happens.

When trying to update some template:

```
Incorrect trigger expression. Host "Template [TEMPLATE_NAME] does not exist or you have no access to this host
``` 

Inability to update is also solving by changing the name of host/template and its becomes ok. 

What could be the reasons for what is happening and how can I fix it? 

Docker image: "zabbix-server-pgsql:centos-5.0-latest"
Zabbix version: 5.0.1

**Comment by dotneft** [comment]
I do not think it is related to Docker. Also you have quite old Zabbix version, please try to use the latest one.

**Comment by o51n** [comment]
I agree that maybe this problem is not docker-specific. I'll try to ask this question on the zabbix forum. Thanks for rapid response.
