### ISSUE TITLE
Unresolved merge committed in docker-entrypoint.sh (web-nginx-mysql/centos)

### ISSUE THREAD

**Issue by fspijkerman** [zabbix/zabbix-docker#805]
An unresolved merge has been committed; breaking https://github.com/zabbix/zabbix-docker/blob/5.2/web-nginx-mysql/centos/docker-entrypoint.sh

Caused by:
https://github.com/zabbix/zabbix-docker/commit/3d675302897480677679e4652dfbc8e3f3997cd8#diff-b6531d2e97528aec819eb01f4ce0b80914324cdf3bfe3aef7a7d57e1625e63fdR20-R25

**Comment by dotneft** [comment]
Thank you! Fixed!
