### ISSUE TITLE
Documentation for zabbix-snmptraps container does not mention UDP port 1162

### ISSUE THREAD

**Issue by mike-sol** [zabbix/zabbix-docker#806]
Hello, thank you for your excellent product! Just a small issue.

The zabbix-snmptraps container is listening for traps on UDP port 1162 by default, presumably because 162 is a privileged port. However, I did not realize this, and spent a long time trying to troubleshoot SNMP traps before seeing it.

The solution was of course to tell Docker to map 1162/udp to 162 outside the container, and then it started working right away. Could no longer run the container in host networking mode, but that doesn't pose a problem for me.

Could we get a small addition to the documentation covering this?

**Comment by dotneft** [comment]
Added + already documented in Zabbix official documentation.
