### ISSUE TITLE
 I need zabbix-agent2 docker ubuntu/debian

### ISSUE THREAD

**Issue by roysbike** [zabbix/zabbix-docker#807]
Hello! will docker be created zabbix-agent2 for debian/ubuntu ?

**Comment by dotneft** [comment]
Why do you need it? There is Alpine version.

**Comment by roysbike** [comment]
we use to monitor hardware raids such as lsi (megacli ) etc . The problem is to run the utility on alpine.

**Comment by dotneft** [comment]
What about CentOS? Do you prefer Ubuntu?

**Comment by roysbike** [comment]
> What about CentOS? Do you prefer Ubuntu?

Ubuntu/Debian

**Comment by dotneft** [comment]
Added! Thank you!
