### ISSUE TITLE
user parameter and service checks of the host docker by the zabbix-agent container

### ISSUE THREAD

**Issue by jaysonsantos18** [zabbix/zabbix-docker#808]
i need to execute remote commands on the host docker of my zabbix-agent2 container using user parameter and also check some services that are on the host docker. How to do this ?

**Comment by RedJohn14** [comment]
Good question I need this too, any ideas on this how to do this?

**Comment by dotneft** [comment]
Run container with privileged mode, otherwise the container is isolated.

**Comment by RedJohn14** [comment]
Yes I have my container in privileged mode in my LXC Container **BUT** zabbix container can **NOT** see processes on HOST or geht memory or CPU from HOST BUT WHY? How to fix?

**Comment by RedJohn14** [comment]
> Run container with privileged mode, otherwise the container is isolated.

Yes I have my container in privileged mode in my LXC Container BUT zabbix container can NOT see processes on HOST or geht memory or CPU from HOST BUT WHY? How to fix?

**Comment by dotneft** [comment]
did you try to use ``--ipc=host``?

**Comment by dotneft** [comment]
For example:
``
# docker run --privileged --ipc=host --pid=host --name some-agent -d zabbix/zabbix-agent2
# docker exec -ti some-agent zabbix_agent2 -t "proc.num[]"
proc.num[]                                    [s|172]
# docker exec -ti some-agent zabbix_agent2 -t proc.mem
proc.mem                                      [s|7487655936]
``

**Comment by RedJohn14** [comment]
> proc.mem

I have added `ipc: "host"` to my docker-compose.yml but proc.num und proc.mem are the same. Any idea why?

**Comment by RedJohn14** [comment]
> did you try to use `--ipc=host`?

I have added ipc: "host" to my docker-compose.yml but proc.num und proc.mem are the same. Any idea why?

**Comment by RedJohn14** [comment]
> For example:
> 
> ```
> # docker run --privileged --ipc=host --pid=host --name some-agent -d zabbix/zabbix-agent2
> # docker exec -ti some-agent zabbix_agent2 -t "proc.num[]"
> proc.num[]                                    [s|172]
> # docker exec -ti some-agent zabbix_agent2 -t proc.mem
> proc.mem                                      [s|7487655936]
> ```

Any idea? Thanks you very much for any help ;-)

**Comment by dotneft** [comment]
pid=host?

**Comment by RedJohn14** [comment]
> pid=host?

Thanks for fast reply.
This turns on sharing between container and the host operating system the PID address space, right?

I still need Container Privileged?

**Comment by dotneft** [comment]
You can check official docker documentation and decide you need the option or not: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities and https://www.docker.com/blog/docker-can-now-run-within-docker/

**Comment by RedJohn14** [comment]
> You can check official docker documentation and decide you need the option or not: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities and https://www.docker.com/blog/docker-can-now-run-within-docker/

Yes I have fixed my things, I have one last question. Any idea how I can get work RAM usage?

With `free -m` in zabbix-agent docker container I have only used RAM from docker container **not** from host. I have mounted **/usr/bin/free** into the docker container but problem is not fixed.

**Comment by dotneft** [comment]
Probably you need to check lxc.cgroup.memory.kmem.limit_in_bytes for the container.

**Comment by RedJohn14** [comment]
> Probably you need to check lxc.cgroup.memory.kmem.limit_in_bytes for the container.

You mean to use this on the lxc host not in the container with zabbix agent as docker container right? 

In the lxc container I can use free -m and get right values. Inside the zabbix agent docker container I used free -m and get only values from the docker container not from the "host" like the lxc container.

**Comment by dotneft** [comment]
Please check https://docs.docker.com/config/containers/resource_constraints/.
