### ISSUE TITLE
Failed to connect to zabbix-server?

### ISSUE THREAD

**Issue by zengxc-1996** [zabbix/zabbix-docker#809]
My system is AliyunCloud Centos 7.9
when I  execuate  
`docker-compose -f docker-compose_v3_centos_mysql_latest.yaml up -d ` 
```
zabbix-proxy-mysql_1       |    194:20210315:145723.890 Unable to connect to the server [zabbix-server]:10051 [cannot resolve [zabbix-server]]
zabbix-proxy-sqlite3_1     |    152:20210315:145754.560 Unable to connect to the server [zabbix-server]:10051 [cannot resolve [zabbix-server]]
```
docker logs zabbix-docker_zabbix-agent_1:
```
 15650:20210315:133943.239 Starting Zabbix Agent [Zabbix server]. Zabbix 5.2.5 (revision 1afd0de).
 15650:20210315:133943.239 **** Enabled features ****
 15650:20210315:133943.239 IPv6 support:          YES
 15650:20210315:133943.239 TLS support:           YES
 15650:20210315:133943.239 **************************
 15650:20210315:133943.239 using configuration file: /etc/zabbix/zabbix_agentd.conf
 15650:20210315:133943.239 agent #0 started [main process]
 15892:20210315:133943.240 agent #3 started [listener #2]
 15890:20210315:133943.241 agent #1 started [collector]
 15891:20210315:133943.242 agent #2 started [listener #1]
 15893:20210315:133943.250 agent #4 started [listener #3]
 15894:20210315:133943.254 agent #5 started [active checks #1]
 15894:20210315:133943.305 active check configuration update from [zabbix-server:10051] started to fail (cannot connect to [[zabbix-server]:10051]: [111] Connection refused)
 15894:20210315:134143.331 active check configuration update from [zabbix-server:10051] is working again
```
![image](https://user-images.githubusercontent.com/63622990/111112319-ee09a780-859a-11eb-9c0a-8db5f8d460a6.png)
Why can't I understand the local connection
I don't know what to do, I hope your help.

**Comment by rockaut** [comment]
The docker-compose starts an container for each service. So the server is one container and the agent is another.
Now the default Zabbix Server host already configured in Zabbix is trying to connect to 127.0.0.1 which is then the zabbix-server container. The easy solution is to replace the "127.0.0.1" with the zabbix-agent (or the container name you gave it) and switch to dns.

**Comment by rockaut** [comment]
In case of container deployment I would keep the "Zabbix server" as is with localhost and remove the "Linux by Zabbiy agent" template from it. And then creating a separate "zabbix-agent" host.

My tip: playing around with Zabbix in containers is great but you still should do your 101 of containers! If you skip that you will have a rough time with learning 2 new technologies :D

**Comment by zengxc-1996** [comment]
Thank you for your advice. It's very useful to me!

**Comment by zengxc-1996** [comment]
Do I have to start the containers one by one?How do I start all Zabbix containers with a template file?

**Comment by zengxc-1996** [comment]
Do I have to start the containers one by one?How do I start all Zabbix containers with a template file?

**Comment by zengxc-1996** [comment]
> In case of container deployment I would keep the "Zabbix server" as is with localhost and remove the "Linux by Zabbiy agent" template from it. And then creating a separate "zabbix-agent" host.
> 
> My tip: playing around with Zabbix in containers is great but you still should do your 101 of containers! If you skip that you will have a rough time with learning 2 new technologies :D
This method is feasible.

**Comment by rockaut** [comment]
> > In case of container deployment I would keep the "Zabbix server" as is with localhost and remove the "Linux by Zabbiy agent" template from it. And then creating a separate "zabbix-agent" host.
> > My tip: playing around with Zabbix in containers is great but you still should do your 101 of containers! If you skip that you will have a rough time with learning 2 new technologies :D
> 
> Do I have to start the containers one by one?How do I start all Zabbix containers with a template(docker-compose) file?

Thats what I meant with 101 of docker. Before hopping into learning Zabbix you should do a quick Docker 101 tutorial (will take you just an hour for the basics).

docker-compose up -d will start ALL services in the docker-compose file. BUT: you should choose the compose file you want (for example the docker-compose_v3_centos_mysql_latest.yaml), RENAME it to docker-compose.yml AND then edit it.
In Zabbix docker-compose file (which are more like templates!) there are some services you might not need! In the mysql for example also are the postgres containers.

**Comment by zengxc-1996** [comment]
Thank you. Thank you I think I already know what to do

**Comment by rockaut** [comment]
Great to hear. Don't shy to ask question if you're getting stuck again.

Maybe helpful for you too: https://github.com/zabbix/zabbix-docker/wiki/Docker-101---Before-starting-with-containerized-Zabbix

**Comment by zengxc-1996** [comment]
> The docker-compose starts an container for each service. So the server is one container and the agent is another.
> Now the default Zabbix Server host already configured in Zabbix is trying to connect to 127.0.0.1 which is then the zabbix-server container. The easy solution is to replace the "127.0.0.1" with the zabbix-agent (or the container name you gave it) and switch to dns.

![image](https://user-images.githubusercontent.com/63622990/111243166-8ce5e080-863b-11eb-9096-9aa15b839bca.png)
I tried to change '127.0.0.1' to the container's Intranet IP, but I didn't know how to configure it (for example, changing the way the environment variable is configured) so that Zabbix can connect to it initially, rather than having to manually configure it, that is, how to change the default '127.0.0.1' of the Zabbix-Server interface.

It doesn't matter if it can't be realized. It's not important to me. I still hope you can give me some advice.
Thank you again and look forward to your reply.

**Comment by zengxc-1996** [comment]
Following your suggestions, I rearranged the docker-compose file and reconfigured the network.It seems to work.
![image](https://user-images.githubusercontent.com/63622990/111243900-c9fea280-863c-11eb-9829-e8ca4ba96cef.png)

**Comment by rengaboy** [comment]
> Following your suggestions, I rearranged the docker-compose file and reconfigured the network.It seems to work. ![image](https://user-images.githubusercontent.com/63622990/111243900-c9fea280-863c-11eb-9829-e8ca4ba96cef.png) In addition, I'm going to configure NGINX forwarding so that I can configure HTTPS externally.

If you don't mind, could you share an example of docker-compose yaml and network.It?
