### ISSUE TITLE
Docker Help Wiki in readme.md

### ISSUE THREAD

**Issue by rockaut** [zabbix/zabbix-docker#810]
Heja @dotneft and others,

long time ago I said I would start with a quick wiki ... made it now :D (https://github.com/zabbix/zabbix-docker/wiki/Docker-101---Before-starting-with-containerized-Zabbix)
Maybe you want to link it somehow in Readme for better visibility?

**Comment by dotneft** [comment]
Hm... where do you think it must be? general README?

**Comment by rockaut** [comment]
I thought about README.md and mixing in into the ISSUES portion.
Done a quick PR.

**Comment by dotneft** [comment]
Done! Thank you!
