### ISSUE TITLE
s390x docker image

### ISSUE THREAD

**Issue by adpopescu** [zabbix/zabbix-docker#812]
Hello,

I noticed that s390x was removed from the list of images being created [here](https://github.com/zabbix/zabbix-docker/commit/33ed9a5d0e3f782401e4bfdeb876a3e9a1917854).
I was wondering if it could be added back in?
Was there an s390x specific issue that needs to be fixed first?

**Comment by dotneft** [comment]
Previously github actions did not build s390, i checked it right now... looks like the problem is disappeared. I will enable it for future releases.

**Comment by adpopescu** [comment]
Ah alright, thank you.
