### ISSUE TITLE
Redirect SSO URL

### ISSUE THREAD

**Issue by fabionaspolini** [zabbix/zabbix-docker#815]
I am executing Zabbix Web (PostgreSQL) at Kubernetes Pods and try to configure SSO SAML with the Keycloak server, but when click on the "Sign in with Single Sign-On" is generate "RelayState" argument invalid.

The correct path should use HTTPS, but is generated with HTTP and port 8080.

How I configure a correct redirect URI? (Or define a custom URI).

![image](https://user-images.githubusercontent.com/8163004/111892472-8f00c400-89da-11eb-9f72-0bc12b0e43bd.png)

**Comment by dotneft** [comment]
Did you try to use $SSO['SETTINGS']['baseurl'] ? According https://github.com/onelogin/php-saml/tree/3.4.1/#user-content-settings. Env variable is ZBX_SSO_SETTINGS.

**Comment by fabionaspolini** [comment]
Did not work.
When clicking on "Sign in with Single Sign-On (SAML)", the "RelayState" parameter is building with HTTP protocol and port 8080. Don't respecting my reverse proxy URL (http://zabbix.MYDOMAIN.com.br:8080/index_sso.php).

```
https://app.bbmlogistica.com.br/auth/realms/master/protocol/saml
?SAMLRequest=fVNNj9owFLzzK1DuxEmABSxIlUI%2FkChEkPbQy8pxHoul2E79nC7bX18ngS6ttvji6PnNeGb8Mkcmy4omtT2pPfyoAW2v79ZZlgppe7jwaqOoZiiQKiYBqeX0kHzZ0MgPaGW01VyX3j%2Bw%2ByiGCMYKrTrYerXwdtsPm92n9fYxH0XHaDwOJ1E%2BDEezMUSTCcxgOoVh8TB5YJH7CPmMd9BvYNDxLDxH6%2FU6NsQa1gotU9bVgygcBMNBNM6CEQ2mNJx976ArZ1YoZlv4ydoKKSGsqvw8l6V%2BEu6UM59r6eeGMJcQMcBKiUQytGDI1Tpp%2FHaU6aX0XqhCqKf7IeRdE9LPWZYO0t0h60iSazhLrbCWYA5gfgoOX%2FebTqeT%2BYvluTi%2FpZROg2lAHDWcHxG1X52qd4yjF7fc80YrbRMycUcyJ7e1166Kbp3k9SrVpeAvbb1ZH7WRzP7fWeiHbUUUg2PbSkEyUSZFYQDR%2B8OTlKV%2BXrpELSw8a2rw%2BuSv2y%2FjCEU7nC4LC2fbX2pZMSOweTM4M24vxl7N3bYvSzdpezjGd4eRU970uXLqtmdtiuYdgbu7M8MUVtrYS0pvkneqyR3Zce96fPunxb8B
&RelayState=http%3A%2F%2Fzabbix.MYDOMAIN.com.br%3A8080%2Findex_sso.php   <===== This is problem
```

But I need to put <https://zabbix.MYDOMAIN.com.br/index_sso.php> (Encoded https%3A%2F%2Fzabbix.MYDOMAIN.com.br%2Findex_sso.php) at the "RelayState" parameter.

I tried to configure ZBX_SSO_SETTINGS and change direct on zabbix.conf.php on docker container, but not work.

**Comment by dotneft** [comment]
Could you try:
```
ZBX_SSO_SETTINGS={'baseurlpath': 'https://zabbix.MYDOMAIN.com.br/', 'application' : {'baseURL' : 'https://zabbix.MYDOMAIN.com.br/'}}
```

I think you need to play with these params :-)

**Comment by fabionaspolini** [comment]
I was able to solve my problem by changing the file zabbix.conf.php

I create a custom `Dockerfile`

```Dockerfile
FROM zabbix/zabbix-web-nginx-pgsql:alpine-5.2.4
COPY zabbix.conf.php /etc/zabbix/web/
```

Edited [zabbix.conf.php](https://github.com/zabbix/zabbix-docker/blob/5.2/web-nginx-pgsql/alpine/conf/etc/zabbix/web/zabbix.conf.php) and put:

```php
<?php
include '/usr/share/zabbix/vendor/php-saml/src/Saml2/Utils.php';

// ... default file https://github.com/zabbix/zabbix-docker/blob/5.2/web-nginx-pgsql/alpine/conf/etc/zabbix/web/zabbix.conf.php

\OneLogin\Saml2\Utils::setSelfHost("zabbix.MYDOMAIN.com.br");
\OneLogin\Saml2\Utils::setSelfProtocol("https");
\OneLogin\Saml2\Utils::setSelfPort("443");
```

Thank you for help!

**Comment by dotneft** [comment]
According documentation it is not necessary to perform such changes:
`At the settings the developer will be able to set a `'baseurl'` parameter that automatically will use `setBaseURL` to set values for `setSelfProtocol`, `setSelfHost`, `setSelfPort` and `setBaseURLPath`.`

```baseurl``` in $SSO['SETTINGS'] is enough!

**Comment by fabionaspolini** [comment]
I try to configure $SSO['SETTINGS'] but not work's, my bug scenario is the docker container, running in Kubernetes behind Kong load balancer and LB doesn't preserve the original host.

I tried search in Zabbix source code, but don't locate when   $SSO['SETTINGS'] is used to execute `setBaseURL` method, in all cases the redirect URL use port 8080 at container, never identified with $SSO['SETTINGS'] baseUrl.

**Comment by dotneft** [comment]
$SSO['SETTINGS'] is used in index_sso.php to specify all possible configuration options. Hmmm... just checked again and it looks like we missed the parameter: https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/ui/index_sso.php#128. I have registered issue to allow the option: https://support.zabbix.com/browse/ZBX-19320

**Comment by szuro** [comment]
Just to chime in, I'm running Zabbix 5.4.4 and ZBX-19320 didn't resolve the issue.
The [trick](https://github.com/zabbix/zabbix-docker/issues/815#issuecomment-829749063) posted by @fabionaspolini, did.

**Comment by szuro** [comment]
OK, so of course i get the solution right after posting. To anyone interested.

I originally used `$SSO['SETTINGS']` posted in [this](https://github.com/zabbix/zabbix-docker/issues/614#issuecomment-912999345) comment and it didn't do the trick. Then i stumbled across this very issue and began investigating.

So it turns out that `baseurl` needs to be **lowercase**. Just doing that solved my problems.
And if anyone is wondering: I'm running Zabbix on Kubernetes with MetalLB.
