### ISSUE TITLE
Port issue on docker compose

### ISSUE THREAD

**Issue by jesselee04** [zabbix/zabbix-docker#817]
deployed the docker-compose_v3_ubuntu_mysql_latest and getting this error on the zabbix-docker_zabbix-web-apache-mysql container

Failure
driver failed programming external connectivity on endpoint zabbix-docker_zabbix-web-apache-mysql_1 (03643262b98e2371acda447be4b844dd9eb16d4067e85165c548555a4bbc70c3): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

**Comment by rockaut** [comment]
Have you any other container Or application running with active port 80? At least the error states that.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________
From: jesselee04 ***@***.***>
Sent: Tuesday, March 23, 2021 4:08:47 PM
To: zabbix/zabbix-docker ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zabbix/zabbix-docker] Port issue on docker compose (#817)


deployed the docker-compose_v3_ubuntu_mysql_latest and getting this error on the zabbix-docker_zabbix-web-apache-mysql container

Failure
driver failed programming external connectivity on endpoint zabbix-docker_zabbix-web-apache-mysql_1 (03643262b98e2371acda447be4b844dd9eb16d4067e85165c548555a4bbc70c3): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

**Comment by jesselee04** [comment]
I dont think so on this server

![image](https://user-images.githubusercontent.com/12163819/112170507-1a3bae80-8bc1-11eb-89c6-063ad2bd79db.png)

**Comment by jesselee04** [comment]
Where is port 80 being defined at? in the compose file i only see this for that container:

ports:
   - "10051:10051"
