### ISSUE TITLE
Unable to Log in to Zabbix

### ISSUE THREAD

**Issue by jesselee04** [zabbix/zabbix-docker#818]
I was able to get it installed and the ports changed so that i got a log in prompt. the zabbix/zabbix user doesnt seem to work. checked my containers and the busy box doesnt seem to want to start and not giving me any logs when i try to start it. 

 db_data_mysql:
  image: busybox
  volumes:
   - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
thank  you in advance.

**Comment by rockaut** [comment]
The busybox is mostly just for setup. So it will start and then ends itself. Infact you don't even need it anymore.
And the default User ist Admin/zabbix
