### ISSUE TITLE
true/True/TRUE -- it's a trap in entrypoint.sh 

### ISSUE THREAD

**Issue by mmarkgraf-tpgroup** [zabbix/zabbix-docker#819]
When we are testing == "true" , we are testing strings, not boolean values.
`true`, `True` and even `TRUE` should all be successful, so the variables being tested should be lowercased prior to testing.

Background:
when you are deploying your containers with ansible, and conditionally set true/false, it will give you 'True'/'False'.
You can of course use the '| lower' filter as a workaround, but it took me way to long to figure out my ansible-runs failed due to "this is a string comparison, not a boolean one in entrypoint.sh". People using other tools will probably run into the same issue and pull lots of hair ;-)

**Comment by rockaut** [comment]
That is a good point I also came across with ansible. But ... things like these happen often in Ansible and I didn't bother and we just use "| lower" in Ansible all the time - just have a look at the community.zabbix collection.

**Comment by mmarkgraf-tpgroup** [comment]
I'm currently using '| lower' myself with ansible,  
it's just that I'm thinking of all the people using Puppet, Salt, CFEngine, Chef and whatnot...

It's easily fixed with #814

**Comment by rockaut** [comment]
^^ ... I didn't know this trick tbh. Very nice.

**Comment by mmarkgraf-tpgroup** [comment]
^^ would be uppercasing the whole string :-)

**Comment by mmarkgraf-tpgroup** [comment]
#814  was merged :-)
