### ISSUE TITLE
How to change the default Admin password during deployment?

### ISSUE THREAD

**Issue by mmarkgraf-tpgroup** [zabbix/zabbix-docker#820]
Hi!

I was wondering: is it possible to change the initial default password for "Admin" to something other than "zabbix"?
By means of an ENV-var maybe, like for db-users and password?

If not, that would be a nice feature for the zabbix-server-mysql and zabbix-server-pqsql.

**Comment by rockaut** [comment]
Wait - do you mean the Zabbix Admin or the DB admin? You can change both!

If you just start your DB change all DB admin occurences (.*_PASSWORD files and look at .env_* files) and it will initialize with those.
If you already have a DB running stop all Zabbix containers, change the password in your DB according to the given DB documentation and then again change it in the docker files too.

If you're just going for the Zabbix UI Admin ... login and change it. No strings attached ;-)

**Comment by mmarkgraf-tpgroup** [comment]
I meant the default Zabbix super admin.

I'm aware that I can change the password after login, but I'd prefer to deploy the docker-container with the password of my choice already set.  Is that possible at all?

**Comment by rockaut** [comment]
Not out of the box nope! These special things are always picky to get right. Look at Grafana for example: you can set the Admin in the Docker files - but it's just for initializing the Admin. And people are always getting this wrong, wondering why the password isn't changing AFTER those initial creation.

Actually I never checked how it works with the DB containers ... need to try that.

I for myself have an simple additional container with some ansible (community.ansible) plays which is running alongside the other containers which runs on each startup and also teardown or timed with cron. This works exceptionally well - at least for me.

**Comment by mmarkgraf-tpgroup** [comment]
Okay, then I need to use ansible to change the password immediately after deployment.  
And hope there's no people with malicous intent in my network that wait for port 10051 to show up...

I had hoped for an undocumented env-variable somewhere :-)

**Comment by rockaut** [comment]
At least none I'm aware off... I looked into the official Zabbix Docs too as I actually find the idea good.
Hmm... I guess it can be possible with initial DB creation for example (so only one-time-setting) or trough a function each startup. I think the initialization would be a better solution (if good documented) than setting it each container start - could lead to potential problems to.

Why did you closed the issue. IMO this would translate to a good PR/contribution.

**Comment by mmarkgraf-tpgroup** [comment]
You're probably right :-)  Someone(tm) should implement this...

**Comment by dotneft** [comment]
Currently we do not have any plans to implement that. It is not good idea, because not so often new installation is deployed + you can use Zabbix API to change password from any automation tools.

**Comment by mmarkgraf-tpgroup** [comment]
I know I can work around this problem (and I do).

But docker-containers are supposed to be thrown away and respawned.
So really, I would like to do installations daily, if not more often, right from my ansible-CI/CD-Pipeline.

**Comment by dotneft** [comment]
Yes, you can recreate them every day :-) But DB is the same anyway, right?

**Comment by mmarkgraf-tpgroup** [comment]
In Production it will be.  But in all other stages it is a throw-away db in a docker-container.
