### ISSUE TITLE
Zabbix server is running: No

### ISSUE THREAD

**Issue by jesselee04** [zabbix/zabbix-docker#821]
New install, did some googling and found a couple typical things but new to zabbix and docker. 

i have increased the cache size in the .env_srv file, restarted, no difference.

i cant seem to find the log that would give me the exact error cause, so if i could be pointed to that and how to see it in a docker container thank you. 

I also say people said to run this, but i cant find where to run it at in the docker environment
grant all privileges on zabbix_db.* to zabbix@localhost identified by 'password';

i didnt see the 10050 and 10051 ports in the services file on the zabbix-server either, an article said they should be in there?

any help would be awesome, thank you in advance.

**Comment by rockaut** [comment]
first again: localhost in docker is always just this one container.
Second: personally I don't had to change anything in DB ever with containers (beside if its a bug).

If you're looking for deeper insights look for `# ZBX_DEBUGLEVEL=3` entries like in .env_srv and raise it. This will give you more detailed output.

The message of your issue let's me guess that the UI (so the web container) can't reach the zabbix-server? Can you give us details which services (MySQL or PG, nginx or Apache) you're running?

Also is it again the same host you're running on you had troubles in the last issue? Have you tried my debug steps from last time and `docker exec` into the containers and tried to just "ping" the other containers?

**Comment by rockaut** [comment]
Another good debug step, especially with docker-compose things is to start your services one by one. So don't just `docker-compose up -d` but do it manually one by one and each time have a look at their logs or dont start it in deamon (-d) but in attached mode (without -d but then you have to use another terminal/window).

1. docker-compose up postgres-server
2. docker-compose up zabbix-server

**Comment by rockaut** [comment]
Ah yes ... as stated here (by me (-; ) https://github.com/zabbix/zabbix-docker/wiki/FAQnP-...-Frequently-asked-questions-and-problems#why-are-there-so-many-containers-with-docker-compose ...

The different docker-compose files are just templates. Copy the one you like to go with (pgsql latest for example) into docker-compose.yml and then edit all mysql things out. Also remove the webserver you don't like (nginx or apache). The bare minimum are essential just DB, zabbix-server, zabbix-web.

**Comment by jesselee04** [comment]
i think im making some progress :D what is the zabbix-agent for? i have an alert its not available. i didnt build its container.

**Comment by dotneft** [comment]
Please check documentation: https://hub.docker.com/r/zabbix/zabbix-agent
