### ISSUE TITLE
Zabbix Server LogFile and LogType

### ISSUE THREAD

**Issue by sarhan1995** [zabbix/zabbix-docker#825]
Hi, 

is there a way to configure the LogFile and LogType as other environment variables.  I see those configuration params in the zabbix-server.conf but I can't find them in the environment variables list of this image. 

thanks for the help

**Comment by dotneft** [comment]
logs are managed by Docker. You need configure Docker to store logs where you would like. Images are configured to use stdout and stderr.

**Comment by sarhan1995** [comment]
can we configure the params in the zabbix-server.conf and map the volume outside the container?

**Comment by dotneft** [comment]
Nope, use local or syslog logging and then put to everywhere you would like :-)

**Comment by rockaut** [comment]
https://sematext.com/blog/docker-logs-location/

Why would you? Just have a look at `/var/lib/docker/containers/` and get them from there. If you dont like json you can change it to text or syslog too.

**Comment by sarhan1995** [comment]
Hi, 

thanks for the advice, 

we are interested in having a specific log file only for the Zabbix server logs (similar to what we had when we installed it as RPMs). 

I made some changes to the docker-entrypoint.sh, so that it will take the new Log File and LogType as an input. from a user's point of view, it will be easier for him to control the location of the Logs. 

the change : 
![Zabbix-entrypoint](https://user-images.githubusercontent.com/81613372/113103634-30242180-9208-11eb-8303-254fed9e41b6.PNG)

please check the change, i will create a PR if you are okay with it 

Regards,

**Comment by dotneft** [comment]
why do you need that? I do not have any ideas why container needs regular logging.

**Comment by sarhan1995** [comment]
we need the logs to be stored in a local file, that will exist in the same place always. we are not interested in sending the logs to Syslog server or having it in JSON. Also, we dont to lose the logs incase the docker is shutdown or lost for some reason

**Comment by dotneft** [comment]
I think you need to use Syslog in Docker with Zabbix server ID, then you will have correct log file as regular file.

**Comment by rockaut** [comment]
Sadly not: https://docs.docker.com/config/containers/logging/syslog/
With syslog drive you have to provide a syslog-address which can't be a file.

For a file it realy only is local or json (https://docs.docker.com/config/containers/logging/local/) or a workaround through something like fluentd with an file output.

I still think journald is supperior. Configure it to export all entries to log-files too and you got your solution with only trusted "on-board" tools without any hacks.

**Comment by sarhan1995** [comment]
due to the requirements, I will go with the local file change. 

if you think the change is not needed then I will close the ticket.
