### ISSUE TITLE
ListenIP is not set in the configuration file even if environment variable is set

### ISSUE THREAD

**Issue by sarhan1995** [zabbix/zabbix-docker#827]
Hi, 

I tried to make Zabbix-server docker listen on one IP only using this Configuration parameter ListenIP. it wasn't set in the Zabbix-server.conf although the environment variable is inside the docker. 

I went back to the code of the docker-entrypoint and i found the issue to be in the sed command used in this section: 
 
![image](https://user-images.githubusercontent.com/81613372/113689039-8c88b480-96d2-11eb-910f-9519bf87aa04.png)

this is the fix i tried and worked for me: 
![image](https://user-images.githubusercontent.com/81613372/113689168-b215be00-96d2-11eb-96d0-6afefb9958dd.png)

please check if this the right way to do it

**Comment by olivierbouffet** [comment]
on my side I just fix the config file :) 

I added the following line to the Dockerfile after the line 155, maybe the best way is to fix the zabbix_server.conf in the tar.gz

`sed -i -e "s/# ListenIP=127.0.0.1//" /etc/zabbix/zabbix_server.conf && \`

**Comment by dotneft** [comment]
Yep, this one works, but it is not a good idea to modify default values. In this case in is not clear which default values will be applied.

**Comment by olivierbouffet** [comment]
Thats not a default but a comment  , I think zabbix team should remove one of the both comment . That's misleading .

**Comment by dotneft** [comment]
Hmm... yeah! You are right, there is 0.0.0.0 already, so 127.0.0.1 is redundant!

**Comment by dotneft** [comment]
I have registered issue: https://support.zabbix.com/browse/ZBX-19334. Will be fixed soon!

**Comment by dotneft** [comment]
Reopened to verify after fix.

**Comment by dotneft** [comment]
I think it must be fixed already! Please verify.
