### ISSUE TITLE
"Remember me for 30 days"  not working in docker

### ISSUE THREAD

**Issue by scoopex** [zabbix/zabbix-docker#829]
I using "zabbix/zabbix-web-apache-pgsql:ubuntu-5.2.0" in docker on  kuberntes.

It seems that the "Remember me for 30 days" function on the login page does not work with docker.

According to my analysis apache does not deliver  the cookie flags for long remberance of the zbx-session cookie.

1. Checked where the zabbix-web pod is running
```
kubectl get pods -A -o wide|grep zabbix-web
```
2. Entered the kubernetes node which is running zabbix
2. Traced the connection
```
tcpdump -i any -s0 -w - host 10.244.2.10 > /tmp/trace
tcpflow -r /tmp/trace
rep -R "zbx_session" .|grep Set-Cookie
./010.244.002.010.08080-010.244.000.004.43810:Set-Cookie: zbx_session=REDACTED.....TIwZWQxY2I0M2M2MzlmOCIsInNpZ24iOiJSYjllbmhCOWF4a25EaEYxc1kxUkFyclozNnNtYUpkQ2NsYnk5SFQreXAwNFwvQ056WjdyWFpMM3pOelBCMk9ZOWpNcUhvUWMzeHFQN1hvaksrRWtxeGc9PSJ9; HttpOnly
...
```

Same request on a virtual machine looks like that:
```
Set-Cookie zbx_session=REDACTEDM5NGM5NCIsInNpZ24iOiJJVU05czB5d2I1SEtOSllaRXFmVldSZllxb1NYcEdsODBTNXRUWlRLcE9OREI2UGxBbWN1ekVMbXEzUVpPMWdFenN1aUxnQWtHMFdSTFdHc1dxcmh6UT09In0%3D; expires=Fri, 07-May-2021 18:18:31 GMT; Max-Age=2592000; path=/app/zabbix; secure; HttpOnly
```

**Comment by dotneft** [comment]
Did you try to use the same web-server configuration on VM?

**Comment by dotneft** [comment]
I did not try kubernetes, but simple docker-compose looks good. Remember for 30 days is working...

**Comment by scoopex** [comment]
I am sorry,  The problem was related to the zabbix release. My setup ran zabbix 5.2.0 - after upgrading to 5.2.6 the problem is solved.
