### ISSUE TITLE
Permissions '/var/cache/nginx/client_temp/'

### ISSUE THREAD

**Issue by toto976** [zabbix/zabbix-docker#83]
I can't import template.

After import xml-file I see '500 Internal Server Error':

```
docker logs zabbix-web
```

```
2017/02/14 11:49:51 [crit] 85#85: *68 open() "/var/cache/nginx/client_temp/0000000004" 
failed (13: Permission denied), client: 172.16.0.10, 
server: zabbix, request: "POST /conf.import.php HTTP/1.1", 
host: "mon.example.com", 
referrer: "http://mon.example.com/conf.import.php?rules_preset=template&sid=644907fc1537bb20"

```

**Comment by garci66** [comment]
was this solved somehow? how/why did you close it? I seem to be running into the same issue

**Comment by dotneft** [comment]
which image dod you use?

**Comment by toto976** [comment]
The problem is still not solved.
Details can be seen in the neighboring problem: https://github.com/zabbix/zabbix-docker/issues/73

**Comment by garci66** [comment]
I was using 3.2.5.. guess Ill have to wait for the next rebuild
