### ISSUE TITLE
SSL with Nginx Proxy

### ISSUE THREAD

**Issue by RafaelHGBotelho** [zabbix/zabbix-docker#831]
Hey guys.

Is there any way to implement SSL on the Zabbix front with Docker? I'm using nginx-proxy, and the front always gives error 502 Bad Gateway.

Example of what I use:
https://blog.ssdnodes.com/blog/host-multiple-ssl-websites-docker-nginx/

I tested this same project (Nginx-Proxy with SSL) with Grafana, WordPress, Nginx and it worked normally, but in Zabbix it doesn't work.

**Comment by dotneft** [comment]
Could you show Zabbix frontend container log?

**Comment by RafaelHGBotelho** [comment]
Hi @dotneft.

I saw that in the log there is this message (**** Impossible to enable SSL support for Apache2. Certificates are missed.), but I don't understand if it is because the volume needs to point the certificate files to Apache (even if I use Nginx-Proxy) or if it is another error.

`** Deploying Zabbix web-interface (Apache) with MySQL database
** Using MYSQL_USER variable from secret file
** Using MYSQL_PASSWORD variable from secret file
********************
* DB_SERVER_HOST: mysql-server
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
** Adding Zabbix virtual host (HTTP)
**** Impossible to enable SSL support for Apache2. Certificates are missed.
** Preparing Zabbix frontend configuration file
########################################################
** Executing '/usr/sbin/httpd -D FOREGROUND'
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.1.7. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.1.7. Set the 'ServerName' directive globally to suppress this message
[Tue Apr 13 23:35:18.837644 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.46 (Unix) PHP/7.3.27 configured -- resuming normal operations
[Tue Apr 13 23:35:18.837854 2021] [core:notice] [pid 1] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
127.0.0.1 - - [13/Apr/2021:23:35:28 +0000] "GET / HTTP/1.1" 200 3614 "-" "curl/7.69.1"
127.0.0.1 - - [13/Apr/2021:23:35:38 +0000] "GET / HTTP/1.1" 200 3614 "-" "curl/7.69.1"
127.0.0.1 - - [13/Apr/2021:23:35:48 +0000] "GET / HTTP/1.1" 200 3614 "-" "curl/7.69.1"
127.0.0.1 - - [13/Apr/2021:23:35:59 +0000] "GET / HTTP/1.1" 200 3614 "-" "curl/7.69.1"
127.0.0.1 - - [13/Apr/2021:23:36:09 +0000] "GET / HTTP/1.1" 200 3614 "-" "curl/7.69.1"
127.0.0.1 - - [13/Apr/2021:23:36:19 +0000] "GET / HTTP/1.1" 200 3614 "-" "curl/7.69.1"
127.0.0.1 - - [13/Apr/2021:23:36:29 +0000] "GET / HTTP/1.1" 200 3614 "-" "curl/7.69.1"`


My Compose:

`version: '3.5'
services:
 zabbix-server:
  container_name: zabbix-server
  image: zabbix/zabbix-server-mysql:alpine-5.2-latest
  restart: always
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - /opt/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - /opt/zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - /opt/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - /opt/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - /opt/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - /opt/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - /opt/zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  links:
   - mysql-server:mysql-server
  env_file:
   - .env_db_mysql
   - .env_srv
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  depends_on:
   - mysql-server
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-mysql
      - zabbix-server-alpine-mysql
      - zabbix-server-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-web-apache-mysql:
  container_name: zabbix-frontend
  image: zabbix/zabbix-web-apache-mysql:alpine-5.2-latest
  restart: always
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
   - /opt/zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
  env_file:
   - .env_db_mysql
   - .env_web
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
  depends_on:
   - mysql-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  environment:
   VIRTUAL_HOST: dominio.com
   LETSENCRYPT_HOST: dominio.com
   LETSENCRYPT_EMAIL: email@dominio.com
  expose:
   - 80
  networks:
   default:
   zbx_net_backend:
    aliases:
     - zabbix-web-apache-mysql
     - zabbix-web-apache-alpine-mysql
     - zabbix-web-apache-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Apache web-server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "apache2"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-agent:
  container_name: zabbix-agent2
  image: zabbix/zabbix-agent2:alpine-5.2-latest
  restart: always
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - /opt/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - /opt/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - /opt/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  links:
   - zabbix-server:zabbix-server
  env_file:
   - .env_agent
  privileged: true
  pid: "host"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-alpine
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "alpine"

 mysql-server:
  container_name: zabbix-mysql
  image: mysql:8.0
  restart: always
  command:
   - mysqld
   - --character-set-server=utf8
   - --collation-server=utf8_bin
   - --default-authentication-plugin=mysql_native_password
  volumes:
   - /opt/zbx_env/var/lib/mysql:/var/lib/mysql:rw
  env_file:
   - .env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - mysql-server
     - zabbix-database
     - mysql-database

 db_data_mysql:
  image: busybox
  volumes:
   - /opt/zbx_env/var/lib/mysql:/var/lib/mysql:rw

 zabbix-proxy-mysql-a:
  container_name: zabbix-proxya
  image: zabbix/zabbix-proxy-mysql:alpine-5.2-latest
  restart: always
  ports:
   - "10071:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/proxy/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  links:
   - zabbix-server:zabbix-server
  env_file:
   - .env_db_mysql_proxy
   - .env_prxa
   - .env_prx_mysql
  depends_on:
   - mysql-server
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-proxy-mysql
     - zabbix-proxy-alpine-mysql
     - zabbix-proxy-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix proxy with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-proxy"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-proxy-mysql-b:
  container_name: zabbix-proxyb
  image: zabbix/zabbix-proxy-mysql:alpine-5.2-latest
  restart: always
  ports:
   - "10072:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /opt/proxy/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - /opt/proxy/zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  links:
   - zabbix-server:zabbix-server
  env_file:
   - .env_db_mysql_proxy
   - .env_prxb
   - .env_prx_mysql
  depends_on:
   - mysql-server
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-proxy-mysql
     - zabbix-proxy-alpine-mysql
     - zabbix-proxy-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix proxy with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-proxy"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

networks:
  default:
    external:
      name: nginx-proxy
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.20.1.0/24

secrets:
  MYSQL_USER:
    file: ./.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./.MYSQL_ROOT_PASSWORD`

**Comment by RafaelHGBotelho** [comment]
I resolved by passing the `expose: 8080` and `VIRTUAL_port: 8080`

**Comment by dotneft** [comment]
Thank you for the information! It is really interesting use case. I suppose we need document that somewhere :-)

**Comment by RafaelHGBotelho** [comment]
@dotneft if you need, I can send you my compose Nginx-Proxy with Let's Encrypt and Docker Gen.

**Comment by dotneft** [comment]
If you can post it it would be great and save my time :-)

**Comment by RafaelHGBotelho** [comment]
Hi @dotneft, here are the compose to build the Zabbix environment with Front, Agent2, 2 Proxies, Server, MySQL 8.0, Nginx-Proxy, Docker Gen, Let's Encrypt and Grafana.

First create a network for the Nginx-Proxy to listen on ports 80 and 443:

`docker network create nginx-proxy`

Put this file at the root of your nginx-proxy directory:

`curl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl > nginx.tmpl`

Composes Nginx-Proxy, Grafana and Zabbix are attached.

PS: I created separate compose because I find it more organized.

[docker-compose.zip](https://github.com/zabbix/zabbix-docker/files/6320746/docker-compose.zip)

Sources:

https://blog.ssdnodes.com/blog/host-multiple-ssl-websites-docker-nginx
https://github.com/nginx-proxy/nginx-proxy
https://github.com/nginx-proxy/acme-companion

So you will have Zabbix and Grafana integrated and running with SSL and Proxy.

**Comment by dotneft** [comment]
Wow! Thank you so much! I will check it and I hope in final we will have good documentation :-) Thank you for the research
