### ISSUE TITLE
Unsupported config option 'profiles'

### ISSUE THREAD

**Issue by gabrielgiorisatto** [zabbix/zabbix-docker#833]
I'm trying to run `docker-compose -f "docker-compose_v3_ubuntu_mysql_latest.yaml" up -d --build`, but i'm getting the following error:

ERROR: The Compose file './docker-compose_v3_ubuntu_mysql_latest.yaml' is invalid because:
Unsupported config option for services.zabbix-agent: 'profiles'
Unsupported config option for services.zabbix-java-gateway: 'profiles'
Unsupported config option for services.zabbix-proxy-mysql: 'profiles'
Unsupported config option for services.zabbix-proxy-sqlite3: 'profiles'
Unsupported config option for services.zabbix-snmptraps: 'profiles'
Unsupported config option for services.zabbix-web-apache-mysql: 'profiles'
The terminal process "/bin/bash '-c', 'docker-compose -f "docker-compose_v3_ubuntu_mysql_latest.yaml" up -d --build'" terminated with exit code: 1.

**Comment by dotneft** [comment]
Please update docker-compose to the latest version.

**Comment by gabrielgiorisatto** [comment]
Thank you for the help, but after running the compose up, i tried to access localhost and got the error:

Database error
Unable to determine current Zabbix database version: the table "dbversion" was not found.

**Comment by dotneft** [comment]
I think you need verify that Zabbix server container created DB normally. Check container's logs...

**Comment by gabrielgiorisatto** [comment]
** Preparing Zabbix server
** Using MYSQL_USER variable from secret file
** Using MYSQL_PASSWORD variable from secret file
** Using MYSQL_ROOT_PASSWORD variable from secret file
********************
* DB_SERVER_HOST: mysql-server
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
** Creating 'zabbix' user in MySQL database
** Database 'zabbix' does not exist. Creating...
** Creating 'zabbix' schema in MySQL

It's been some minutes in this step

**Comment by dotneft** [comment]
So wait :-) Till finish...

**Comment by gabrielgiorisatto** [comment]
Thank you!!! It worked!
