### ISSUE TITLE
CentOS image for 5.0.11 not available on hub.docker.com

### ISSUE THREAD

**Issue by jokay** [zabbix/zabbix-docker#836]
The CentOS image for **5.0.11** is not available on [hub.docker.com](https://hub.docker.com/r/zabbix/zabbix-server-pgsql/tags?page=1&ordering=last_updated&name=5.0.11-).

**Comment by dotneft** [comment]
It is already released, so docker code is published. We can not change any code when a version released already. 5.0.12 will have correct Dockerfile.

**Comment by jokay** [comment]
This is sad :wink:
