### ISSUE TITLE
Set maximum DB version in Compose

### ISSUE THREAD

**Issue by Majr25** [zabbix/zabbix-docker#841]
Per https://www.zabbix.com/documentation/current/manual/installation/upgrade_notes_540

Zabbix now specifies an upper bound for tested DB versions. The compose files should specify the newest tested version to avoid pulling a potentially untested version.

E.g.: 
```diff
  postgres-server:
-  image: postgres:alpine
+  image: postgres:13-alpine
```

**Comment by dotneft** [comment]
Fixed! Thank you!
