### ISSUE TITLE
Zabbix agent not available on server at startup

### ISSUE THREAD

**Issue by pvalois** [zabbix/zabbix-docker#843]
##### SUMMARY

After installing Zabbix with docker-compose like this : 

the pull up, and starts goes smoothly, i can login all seems nice. 
but on the dashboard, there is a first alert saying that the "Zaggix agent is not available" for Zabbix-server

##### OS / ENVIRONMENT / Used docker-compose files

8Go Ram
Ubuntu 20.04
Linux krilin.maison 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Docker version 20.10.6, build 370c289
docker-compose version 1.29.2, build 5becea4c

file used : docker-compose_v3_ubuntu_pgsql_latest.yaml

##### CONFIGURATION

Nothing done personnaly.

##### STEPS TO REPRODUCE

git clone https://github.com/zabbix/zabbix-docker.git
ln -s docker-compose_v3_ubuntu_pgsql_latest.yaml docker-compose.yaml
docker-compose up -d 

##### EXPECTED RESULTS

i expected no error/warning on the dashboard at first start.

**Comment by dotneft** [comment]
Try to change Zabbix server DNS to zabbix-agent.
