### ISSUE TITLE
how use virtual path in zabbix front?

### ISSUE THREAD

**Issue by nAnderYang** [zabbix/zabbix-docker#844]
I use container images 5.4-alpine-latest. but i need frontend access url in virtual path /{set} not default path /
but i can't find set option or args.

Does the current container image have this function designed?

default:
http://ip addr:8080/
https://ip addr:8443/

custom set:
http://ip addr:8080/{virtual path}/
https://ip addr:8443/{vitual path}/

**Comment by dotneft** [comment]
How about some proxy behind Zabbix frontend?

**Comment by nAnderYang** [comment]
i use `docker-compose` proxy front container port.

the yaml file port set:
```
ports:
  - 80:8080
  - 443:8443
```

just only need the fronted web work on non-root path

**Comment by nAnderYang** [comment]
i check fronted container `zabbix/zabbix-web-nginx-mysql:alpine-5.4-latest` runtime nginx.conf .confirm this feature is not supported, I will modify the container image to support it in my operating environment.

**Comment by dotneft** [comment]
Probably it is better to use proxy behind Zabbix frontend :-)
