### ISSUE TITLE
Zabbix 5.2 and 5.4 not available on ubi8 (alternative to centos8)

### ISSUE THREAD

**Issue by grunlab** [zabbix/zabbix-docker#845]
I'm currently running zabbix 5.2.5 (in prod) and 5.4.0 (in val) based on centos8 images (with some few yum packages installed on top of the images for our customization)

I've just discovered that zabbix images based on centos8 are now discontinued (for example 5.4.1 not available anymore on centos8)

My plan is now to migrate from centos8 images to ubi8 images (no big change for our customization using yum packages)

Issue:
When connecting to redhat catalog (https://catalog.redhat.com/software/containers/search?q=zabbix&p=1), I see that only zabbix 5.0 images are available on ubi8 ... but not 5.2 and 5.4 :-(

Qestion:
When do you plan to publish zabbix 5.2 and 5.4 on ubi8 ?

**Comment by dotneft** [comment]
Feel free to use Oracle Linux 8 based images. RHEL 5.4 will be available soon!

**Comment by grunlab** [comment]
"RHEL 5.4 will be available soon" --> great :-)
Do you know approximately when ?

**Comment by dotneft** [comment]
Everything is ready, waiting approval from RHEL (

**Comment by grunlab** [comment]
OK, hope this approval process with RedHat is not too long ;-)
Zabbix ubi8 images cannot be pushed to docker.io and/or quay.io ?

**Comment by minsis** [comment]
@dotneft Does this mean y'all are not supporting any centos containers anymore? The last one built was 3 months ago for 5.4 and none of the minor releases since then.

**Comment by dotneft** [comment]
I would like to support them! But it is impossible, at lest at this time. Check tags: https://hub.docker.com/_/centos?tab=tags&page=1&ordering=last_updated. They updated 8 months ago! Any idea how to support this?

**Comment by minsis** [comment]
![image](https://user-images.githubusercontent.com/11248197/128744440-f98576bb-1010-4064-8cba-d0156f16c907.png)

Looks like they're expecting end users to maintain updating the containers internally.

Either way doesn't matter, I just wanted to validate with you so I can just switch to OL containers.

Thanks!

**Comment by dotneft** [comment]
If we will do that, image size can be very huge!

**Comment by minsis** [comment]
100% agree, I'm just pointing it out. Their issues board is littered with complaints about this; so maybe they'll change their stance.

**Comment by dotneft** [comment]
Done! Finally fixed :-)

**Comment by grunlab** [comment]
Great, effectively zabbix 5.4.3 images based on ubi are now available in redhat registry :-) Thank you !
Do you know if 5.2 will also be available ?

**Comment by dotneft** [comment]
Unfortunately 5.2 is deprecated already. So we do not plan to release these images.
