### ISSUE TITLE
missing export ZBX_SSO_SETTINGS in docker-entrypoint.sh for web-nginx-pgsql flavor

### ISSUE THREAD

**Issue by duviful** [zabbix/zabbix-docker#847]
##### SUMMARY

Hello, while trying to setup SSO with Azure AD, seems that the following line is missing from the file  zabbix-docker/web-nginx-pgsql/ubuntu/docker-entrypoint.sh 

```
export ZBX_SSO_SETTINGS=${ZBX_SSO_SETTINGS:-""}
```

thus, the custom settings are not received and enabled.

I looked around and seems that pretty much all other container flavors have that line.
Is missing by mistake or there are some incompatibility?

##### OS / ENVIRONMENT / Used docker-compose files

docker-compose stack on debian10 with the following:
zabbix/zabbix-web-nginx-pgsql:ubuntu-5.4-latest
zabbix/zabbix-server-pgsql:ubuntu-5.4-latest

pgsql is hosted on a different server

##### CONFIGURATION

relevant env:

ZBX_SSO_SETTINGS={"baseurl": "https://ch-net-staging-zabbix.xxx.xxx.com", "use_proxy_headers": true}

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

AssertionConsumerServiceURL="https://ch-net-staging-zabbix.xxx.xxx.com/index_sso.php?acs"

##### ACTUAL RESULTS

AssertionConsumerServiceURL="https://ch-net-staging-zabbix.xxx.xxx.com:8443/index_sso.php?acs"

```paste below

```

**Comment by dotneft** [comment]
Fixed! Thank you!
