### ISSUE TITLE
Docker build failing for server trunk

### ISSUE THREAD

**Issue by slabber** [zabbix/zabbix-docker#85]
The docker builds for trunk are failing in the server project.  But because the builds are successful for the web front-end we now face the issue that pulling trunk images for both web and server causes a mismatch in database schema version.

**Comment by jangaraj** [comment]
BTW: https://hub.docker.com/r/monitoringartist/zabbix-xxl/tags/ doesn't have this problem. Trunk version = `monitoringartist/zabbix-xxl:dev` docker image.

**Comment by slabber** [comment]
The Dockerfile needs libevent and libevent-dev adding.  In attach is a Dockerfile that works.
[Dockerfile.txt](https://github.com/zabbix/zabbix-docker/files/816670/Dockerfile.txt)

**Comment by dotneft** [comment]
solved
