### ISSUE TITLE
Container not started

### ISSUE THREAD

**Issue by luweijun1992** [zabbix/zabbix-docker#850]
Only ZABBIX server and ZABBIX web are started; The remaining containers are not started .
![image](https://user-images.githubusercontent.com/58923704/123064362-cb601800-d440-11eb-8cdd-7cb87cec58ac.png)
[docker-compose.txt](https://github.com/zabbix/zabbix-docker/files/6700288/docker-compose.txt)

**Comment by dotneft** [comment]
Please specify profile full or all for compose command.

**Comment by luweijun1992** [comment]
> Please specify profile full or all for compose command.

The docker-compose.txt provided in the attachment is my configuration file docker-compose.yml 
![image](https://user-images.githubusercontent.com/58923704/123185638-f726e080-d4c8-11eb-886b-c1ac19e4353d.png)

**Comment by dotneft** [comment]
Just different set of containers (minimal, usual and all) :-)
