### ISSUE TITLE
5.4.2-alpine tags not available for mysql variant on Docker hub

### ISSUE THREAD

**Issue by PadaKwaak** [zabbix/zabbix-docker#852]
##### SUMMARY
There are currently no "5.4.2-alpine" tags available for the Zabbix MySQL images (eg. zabbix/zabbix-server-mysql) to pull from Docker hub:
https://hub.docker.com/r/zabbix/zabbix-server-mysql/tags?page=1&ordering=last_updated&name=5.4.2

##### EXPECTED RESULTS
I was expecting a 5.4.2-alpine tag to be available, since there was one for the 5.4.1 version of Zabbix. 

There are still a 5.4.2-alpine tag available for PostgreSQL available ( https://hub.docker.com/r/zabbix/zabbix-server-pgsql/tags?page=1&ordering=last_updated&name=5.4.2 ) which makes me believe this was just an error somewhere...

**Comment by PadaKwaak** [comment]
I have now noticed that the zabbix/zabbix-server-mysql:alpine-5.4.3 image is available, however the zabbix/zabbix-web-nginx-mysql:alpine-5.4.3 is not.

For now I've switched to the zabbix/zabbix-web-nginx-mysql:ubuntu-5.4.3 image, but I can't do that with my zabbix-server-mysql image, since I am installing quite a number of additional packages and things such as SNMP mibs & mariadb-connector-odbc which would be too time consuming for me to currently rework for Ubuntu.

**Comment by dotneft** [comment]
Web image based on Alpine has broken PHP 7.4, so currently it is impossible to release 5.4.3 version. Feel free to use non-Alpine web and Alpine-based server :-)

**Comment by dotneft** [comment]
5.4.3 is available.

**Comment by syphernl** [comment]
@dotneft Since this issue was closed with "5.4.3 is available" I assumed this would mean that 5.4.3 would now be available on Alpine as well. 
But it seems that there are no `zabbix-web` package for neither the pgsql nor the mysql version?
