### ISSUE TITLE
Availability status is not shown

### ISSUE THREAD

**Issue by gabriel0029** [zabbix/zabbix-docker#856]
Hi, I have a problem and I can't find the solution. I'm new to the docker.
I set up a lab with zabbix + postgres + nginx which is working, my problem is that hosts registered with zabbix agent active templates are not shown as Available in status zabbix agent not active templates are ok. Has anyone experienced this problem?

I'm using the zabbix server 5.0.13 and the agent 5.0.0

![image](https://user-images.githubusercontent.com/87427032/126584506-94925a92-6e7f-4cc9-b0ba-fd32ef6be876.png)

The logs do not bring any errors:
![image](https://user-images.githubusercontent.com/87427032/126584644-000d20ec-ce9d-4970-b913-4bcdf223829e.png)

My agent configuration:

PidFile=/run/zabbix/zabbix_agentd.pid
LogFile=/var/log/zabbix/zabbix_agentd.log
LogFileSize=0
DenyKey=system.run[*]
Server=172.25.0.3
ServerActive=172.25.0.3
Hostname=Zabbix server
Include=/etc/zabbix/zabbix_agentd.d/*.conf

Do you have an idea ?
Thanks for your help.

**Comment by dotneft** [comment]
Zabbix agent active does not have such feature. Only passive items can affect to availability icons.
