### ISSUE TITLE
Dashboards are not working using Docker image

### ISSUE THREAD

**Issue by DonovanDiamond** [zabbix/zabbix-docker#857]
##### SUMMARY
The dashboards page is blank and does not allow you to edit any dashboard. However, all other functions of Zabbix are working normally including agents/hosts/graphs/triggers/etc.

Note that I have another Zabbix server running on a VM without docker and everything works fine.

##### OS / ENVIRONMENT / Used docker-compose files
**Host OS:** Ubuntu 20.04
**docker-compose** version 1.29.2, build 5becea4c
**Docker Engine** - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15

Tested with my own docker-compose file (under Configuration).
Also tested it with the compose file: `docker-compose_v3_ubuntu_pgsql_latest.yaml` on another machine with the exact same issue.

The browsers used to access the interface was Google Chrome, the new Microsoft Edge, Firefox.

##### CONFIGURATION
My `docker-compose.yml`: https://gist.github.com/DonovanDiamond/12d5e29b9bc07d4eb1d4573d1ccb0795

Also tested with the standard: `docker-compose_v3_ubuntu_pgsql_latest.yaml` (only modified information was the HTTP port which the web container uses, from port `80` to port `1080`).

##### STEPS TO REPRODUCE
```yaml
git clone https://github.com/zabbix/zabbix-docker.git
git checkout 5.4
mv docker-compose_v3_ubuntu_pgsql_latest.yaml docker-compose.yml
sudo docker-compose up
```

##### EXPECTED RESULTS
Dashboard page to be fully functional and you able to edit/create/view dashboards.

##### ACTUAL RESULTS
All dashboards are blank and you are unable to create or edit any dashboards:
![Screenshot from 2021-07-26 11-04-00](https://user-images.githubusercontent.com/56517875/126970187-99ef8b86-ac0b-4ceb-90c5-afb744889bb6.png)

Also an error occurs in the browser console:
```
Uncaught SyntaxError: Unexpected token '?'

jsLoader.php?lang=en_GB&ver=5.4.2&showGuiMessaging=1:3843 jQuery.Deferred exception: timeControl is not defined ReferenceError: timeControl is not defined
    at init (http://10.121.160.10:1080/zabbix.php?action=dashboard.view&dashboardid=57:42:4)
    at initializeView (http://10.121.160.10:1080/zabbix.php?action=dashboard.view&dashboardid=57:368:3)
    at HTMLDocument.<anonymous> (http://10.121.160.10:1080/zabbix.php?action=dashboard.view&dashboardid=57:510:2)
    at mightThrow (http://10.121.160.10:1080/jsLoader.php?lang=en_GB&ver=5.4.2&showGuiMessaging=1:3559:29)
    at process (http://10.121.160.10:1080/jsLoader.php?lang=en_GB&ver=5.4.2&showGuiMessaging=1:3627:12) undefined

jQuery.Deferred.exceptionHook @ jsLoader.php?lang=en_GB&ver=5.4.2&showGuiMessaging=1:3843
jsLoader.php?lang=en_GB&ver=5.4.2&showGuiMessaging=1:3852 Uncaught ReferenceError: timeControl is not defined
    at init (zabbix.php?action=dashboard.view&dashboardid=57:42)
    at initializeView (zabbix.php?action=dashboard.view&dashboardid=57:368)
    at HTMLDocument.<anonymous> (zabbix.php?action=dashboard.view&dashboardid=57:510)
    at mightThrow (jsLoader.php?lang=en_GB&ver=5.4.2&showGuiMessaging=1:3559)
    at process (jsLoader.php?lang=en_GB&ver=5.4.2&showGuiMessaging=1:3627)
```

Zabbix server logs: https://gist.github.com/DonovanDiamond/85b97e7b7a8da0d6384fdda987571fed
Zabbix web logs: https://gist.github.com/DonovanDiamond/35ad46527ce59bee0ca9c8cf8848d2d8

Let me know if there is any other logs/information you need. I did go through the Zabbix documentation and spent a few hours searching for/testing different solutions without any success.

**Comment by dotneft** [comment]
Could you try to use git pull before up? Actually if no downloaded images we have 5.4.3 already :-) I just tested the issue, and do not see any issues with Dashboard section.

**Comment by DonovanDiamond** [comment]
For some reason the dashboard only works from an Ubuntu desktop machine which has an active internet connection. Not sure exactly why it doesn't work on any of my windows machines on my local network. (They are using fully up to date browsers.)

I will close this for now but will comment if I find any useful information.
