### ISSUE TITLE
alpine-trunk zabbix web requires 5040000 DB_VERSION

### ISSUE THREAD

**Issue by tomaszsluszniak** [zabbix/zabbix-docker#858]
Hi,
I upgraded my `zabbix-server` container (`zabbix/zabbix-server-pgsql`) and `zabbix-web` (`zabbix/zabbix-web-nginx-pgsql`) to `alpine-trunk` and had an error on the web "The Zabbix database version does not match current requirements. Your database version: 5050031. Required version: 5040000. Please contact your system administrator.".

Database upgraded successfully to version `5050031` but `ZABBIX_DB_VERSION` in `zabbix/zabbix-web-nginx-pgsql` is `5040000`.

**Comment by dotneft** [comment]
Removed ppc64 from Alpine images. Please check it again.

**Comment by tomaszsluszniak** [comment]
Works like a charm, thanks :)
