### ISSUE TITLE
MYSQL_ROOT_PASSWORD_FILE not supported in zabbix-web-nginx-mysql image

### ISSUE THREAD

**Issue by m-tomczak** [zabbix/zabbix-docker#859]
`MYSQL_ROOT_PASSWORD_FILE` variable is ignored when passed to `docker run`.

I think it is not handled within `docker-entrypoint.sh` (`check_variables()`)

https://github.com/zabbix/zabbix-docker/blob/a823cbac9df4321b44fc7267b4d33452771c13af/web-nginx-mysql/alpine/docker-entrypoint.sh#L60-L94

**Comment by dotneft** [comment]
Yes, it is not handled. Usually Zabbix user is created by MySQL directly, so do not need to forward MySQL root password. Do you need that?

**Comment by m-tomczak** [comment]
When I don't pass `MYSQL_ROOT_PASSWORD` I'm getting this:

```
** Deploying Zabbix web-interface (Nginx) with MySQL database
** Using MYSQL_PASSWORD variable from secret file
*** Impossible to use MySQL server because 'root' password is not defined and it is not empty
```

**Comment by dotneft** [comment]
It is because you did not specify MYSQL_USER and MYSQL_PASSWORD variables. So Zabbix server does not know what to do :-)

**Comment by m-tomczak** [comment]
I did, I'm running it like this:

```
docker run --name zabbix-web \
    -e MYSQL_PASSWORD_FILE="/etc/mysql/mysql_pwd" \
    -v /opt/mysql/conf/mysql_pwd:/etc/mysql/mysql_pwd \
    --restart unless-stopped \
    --network zabbix-net \
    -p 80:8080 \
    -d zabbix/zabbix-web-nginx-mysql
```

I'm not specifying  `MYSQL_USER` because I’m using default username `zabbix` in MySQL. If I don't specify `MYSQL_ROOT_PASSWORD` it just won’t start and if I add:

```
    -e MYSQL_ROOT_PASSWORD_FILE="/etc/mysql/mysql_root_pwd" \
    -v /opt/mysql/conf/mysql_root_pwd:/etc/mysql/mysql_root_pwd \
```

`MYSQL_ROOT_PASSWORD_FILE` is ignored and the same error shows up:

`*** Impossible to use MySQL server because 'root' password is not defined and it is not empty`

Only if I add:

`    -e MYSQL_ROOT_PASSWORD="*****" \`

then Zabbix Web start properly.

**Comment by dotneft** [comment]
Please try to specify MYSQL_USER :-) For example specify default value.

**Comment by m-tomczak** [comment]
Ok, I get it now 😃 

Thanks for your help!
