### ISSUE TITLE
Are version specific containers not supported now?

### ISSUE THREAD

**Issue by minsis** [zabbix/zabbix-docker#861]
Are version specific containers not supported anymore?

I see that you're building 5.4-latest containers recently but 5.4.3 containers haven't been updated equally.

**Comment by dotneft** [comment]
Due issue with alpine ppc64 version, 5.4.3 is missing.

**Comment by minsis** [comment]
@dotneft But the other containers dont have version specifics either. Ubuntu, OL7, etc

**Comment by dotneft** [comment]
they update base image on regular basis.

**Comment by minsis** [comment]
Yes I, but I mean you are not updating version specific containers for 5.4. You've updated containers 4 days ago, but the version specific ones did not get updated.

![image](https://user-images.githubusercontent.com/11248197/128768996-7b761cdf-9df6-4a06-abed-d82537be103d.png)

![image](https://user-images.githubusercontent.com/11248197/128768958-a53ca7fc-85d6-428b-9f3c-aa100c0c4fee.png)

**Comment by dotneft** [comment]
version specific are like packages. They are not updated after release! Please wait next Zabbix release.
