### ISSUE TITLE
ubi8 images / redhat registry : delay to get new zabbix version

### ISSUE THREAD

**Issue by grunlab** [zabbix/zabbix-docker#864]
zabbix 5.4.4 has been released few days ago (August 30th)
Today, September 3rd, zabbix 5.4.4 on ubi8 images are still not yet available in Redhat registry --> https://catalog.redhat.com/software/containers/search?q=zabbix&p=1
The latest available version is currently 5.4.3.

Is this delay normal ?
How long does it take to get a new zabbix version pushed into Redhat registry ?

I've just started using Zabbix images based on ubi8 (this is linked to a company constraint) and those kind of delay is worring me a bit. If for example an emergency upgrade to 5.4.4 was needed, I would be currently blocked due to this !

**Comment by dotneft** [comment]
The issue is related to RedHat automation builds. They are fixing the issue... So currently we can update images only through manual push (

**Comment by dotneft** [comment]
Fixed!

**Comment by grunlab** [comment]
Finally, the 5.4.4 images were pushed manually or automatically ?

**Comment by dotneft** [comment]
manually
