### ISSUE TITLE
kubernetes.yaml doesn't work in minikube aka kubernetes

### ISSUE THREAD

**Issue by bigOconstant** [zabbix/zabbix-docker#865]
##### SUMMARY

trying to deploy the kubernetes file results in an error 

```
error: error validating "deployment.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

Because there is no selector defined.

**Comment by dotneft** [comment]
what is deployment? Selector is there: https://github.com/zabbix/zabbix-docker/blob/a6bc5ffa9d18cfc10ab61d0722f87d0fbac07b3e/kubernetes.yaml#L461

**Comment by bigOconstant** [comment]
> what is deployment? Selector is there:
> 
> https://github.com/zabbix/zabbix-docker/blob/a6bc5ffa9d18cfc10ab61d0722f87d0fbac07b3e/kubernetes.yaml#L461

Sorry kubernetes.yaml. That is a different branch than master branch. Master is broken

**Comment by dotneft** [comment]
Master is base, do not use it please. Use branch dedicated for a version you need.
