### ISSUE TITLE
Installed zabbix-docker. And I watch the error

### ISSUE THREAD

**Issue by sasha198407** [zabbix/zabbix-docker#868]
##### SUMMARY
Installed zabbix-docker. And I watch the error
zabbix-docker_db_data_pgsql_1            sh                               Exit 0

##### OS / ENVIRONMENT / Used docker-compose files
Ubuntu 20.04.3 LTS/docker-compose_v3_centos_pgsql_latest.yaml 

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
It is not error. It is normal for db_data.
