### ISSUE TITLE
Enable plugins via environment variable

### ISSUE THREAD

**Issue by jokay** [zabbix/zabbix-docker#869]
Is there a way to enable [plugin](https://zabbix.com/documentation/5.0/manual/config/items/plugins) **WebCertificate** via environment variable on **zabbix-agent2**?

**Comment by dotneft** [comment]
Too much env variables :-) So it is better to use Include files.

**Comment by jokay** [comment]
You mean mount `/etc/zabbix/zabbix_agent2.conf` to achieve this?

**Comment by dotneft** [comment]
This one: https://github.com/zabbix/zabbix-docker/tree/5.4/agent2/alpine#etczabbixzabbix_agentdd

**Comment by jokay** [comment]
thx, will have a look, issue closed.
