### ISSUE TITLE
no active checks on server [:10051]: connection of type "TLS with PSK" is not allowed for host "Zabbix server"

### ISSUE THREAD

**Issue by sasha198407** [zabbix/zabbix-docker#870]
Hello. I connected the agent to Zabbiks via PSK. The message in the logs is: "no active checks on server [ip-address:10051]: connection of type" TLS with PSK "is not allowed for host" Zabbix server " " It should be? I also want to configure access to the zabbix control panel through https, but I do not have enough rights inside the containers. What can be done in this situation?"

##### OS / ENVIRONMENT / Used docker-compose files
Ubuntu 20.04.3 LTS/docker-compose_v3_centos_pgsql_latest.yaml

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by kernbug** [comment]
Hello. You need to configure monitored host settings properly under the encryption tab:
https://www.zabbix.com/documentation/current/manual/config/hosts/host
https://www.zabbix.com/documentation/5.0/manual/encryption

Feel free to modify sources as required to add HTTPS support or use load balancer with HTTPS to enable encryption for the Web interface. 

This issue cannot be considered as a bug, closing.
