### ISSUE TITLE
Zabbix 5.4, the "discovery rules" does not work at "triggers" level 

### ISSUE THREAD

**Issue by alifro81** [zabbix/zabbix-docker#872]
Hi,
I have a problem with Zabbix 5.4, indeed since I was migrated to this version, I noticed that there is an error at the deployment level of "Template de vmware" because when I discover the hypervisor, Zabbix does not recover the items or halfway .... I made a test plan (redo 0 templates or a template already set for zabbix) .........
I do not know what to do, an adviser?
or if not, I am waiting for the new version 6 ???

Update: I tested with 6 (beta) and it's the same ......

Thank you
Kind regards

**Comment by dotneft** [comment]
Please check our https://www.zabbix.com/forum/ forum and https://support.zabbix.com/. The issue is not related to docker images.

**Comment by alifro81** [comment]
![zabbix1](https://user-images.githubusercontent.com/71875810/134913944-5bd2d24b-3a7d-423e-92d0-f5e0c28bad0b.JPG)
![zabbix2](https://user-images.githubusercontent.com/71875810/134913950-0e6b13df-ad74-4a5a-9498-3b0eb4d1bcdc.JPG)

**Comment by alifro81** [comment]
the problem comes with the containers, when I install version 5.2, everything works correctly but when I install 5.4 ou plus, it does not work.

everything is in docker :)
thanks for your help

**Comment by dotneft** [comment]
Docker images are not changed in comparison with 5.2, but Zabbix is changed :-) So the issue is related to Zabbix directly, not images issue.

**Comment by alifro81** [comment]
ah :0 ..........;; but every image calls zabbix non?
 because in 5.2 les declonchers works very well and from 5.4 non? is it a problem of zabbix?
because when I install zabbix 5.4 without conteneur it works fine :\

**Comment by dotneft** [comment]
So the issue, when you link VMware Hypervisor to some host, the host does not inherit all triggers from the template? Do you use vanilla template?

**Comment by alifro81** [comment]
yes,
I use the "vmware" template model, that is to say,
I create 1 host (vsphere) where with the decloncheur discovers the hyperviseur but does not recover the triggers, and if he recovers -> recovers in the middle :(

**Comment by alifro81** [comment]
i use the 3 containers (server,web and agent) with mysql
I have tested with 5.2 and it works
but I want to use version 5.4 because 5.2 is currently in production without docker

ahi something that I do wrong?

![zabbix3](https://user-images.githubusercontent.com/71875810/134927408-f0bd88cc-a875-4209-897a-1f6c8cbad9f4.JPG)
![zabbix4](https://user-images.githubusercontent.com/71875810/134928103-ecd0cd39-7e54-419d-9cec-b31ae0276299.JPG)

**Comment by dotneft** [comment]
What triggers do you have in the template and what you have on host level?

**Comment by alifro81** [comment]
In my vsphere host, I put the vmware template (zabbix template) and then it makes a discovery of all hypervisors (with the vanilla template). 
The problem is only in the triggers :(, everything else is ok ...
 On the other hand I tested when you activate and deactivate the triggers they appear but without their dependence 

Very strange -_- ...  It's the first time it happens to me... 
with version 5.2 I never had any problem :( ... 
Thanks for your help ^^

**Comment by alifro81** [comment]
I just did a test and I think the problem comes from my zabbix configuration (.env_srv), do you have a template that works correctly on the .env_srv?

**Comment by dotneft** [comment]
Probably DB charset is not correct. Also I recommend you check Zabbix server log for any SQL errors.

**Comment by alifro81** [comment]
I came from testing and nothing ..... the problem with the triggers continues ...
my .env_srv seems correct ??? 

![zabbix5](https://user-images.githubusercontent.com/71875810/135065342-e88ae25a-07c8-48fd-b9bd-39b520e25630.JPG)

**Comment by alifro81** [comment]
in the "logs" it only tells me, memory problem 

![image](https://user-images.githubusercontent.com/71875810/135065951-4b25c9fe-4608-4278-9f1e-ed261458e0d6.png)

**Comment by alifro81** [comment]
bon, 
I can not find a solution to my problem ...
if someone has had such a problem, please share

**Comment by dotneft** [comment]
I'm still waiting screenshots from your side. What triggers you have on template level and what triggers on host level with the template.

**Comment by alifro81** [comment]
oui, 
first I create the vsphere, with the vmware template ( from zabbix)
![zabbixce1](https://user-images.githubusercontent.com/71875810/135104636-e6c59e61-79b1-4f49-863d-6ce4b32851f6.JPG)
![zabbixce2](https://user-images.githubusercontent.com/71875810/135104645-8c69ebd4-404d-4822-b434-27fa91da72b1.JPG)
![zabbixce3](https://user-images.githubusercontent.com/71875810/135104660-4b91bd38-b25e-40cb-8ea4-25a417a73d97.JPG)

second, thanks to the "decouverte", the hyperviseurs appear (with the "vmware hypervisor" template).
the problem: the hyperviseurs don't have the template tiggers :(
![zabbixce4](https://user-images.githubusercontent.com/71875810/135105384-8097639c-6508-4307-a55c-75a0f4bf91d9.JPG)

I have tried for now almost everything ( macros, .env_srv configuration, mysql version)....
 and as I was saying, the problem happens to me starting from >5.4
if I change to version 5.2, everything works fine.

But if I install 5.4 without container(docker), it works correctly :(
Cdt

**Comment by alifro81** [comment]
the 6 triggers de template vmware hypervisor
![zabbixce5](https://user-images.githubusercontent.com/71875810/135108858-8a72b631-27c9-451c-a44a-fe6f1dffcab1.JPG)

 it triggers it to recover mon hypervisor 
![zabbixce6](https://user-images.githubusercontent.com/71875810/135109116-e5ec58c7-b023-45ff-85af-c0a8f2aae879.JPG)

**Comment by dotneft** [comment]
Do you have vmware.hv.sensor.health.state item on the discovered host level?

**Comment by alifro81** [comment]
Yes,
on the other hand it does not work because my vsphere does not have the sensor (it was always like that)
