### ISSUE TITLE
xframe option header parametr in zabbix

### ISSUE THREAD

**Issue by Vladozoff** [zabbix/zabbix-docker#874]
Good afternoon, how can I specify the xframe option header when launching a zabbix container using docker?

**Comment by dotneft** [comment]
do you mean some constant from defines.inc.php?

**Comment by Vladozoff** [comment]
I meant this option (the path to it via the web interface: Administration-> General-> Others-> X-frame-Options HTTP header). I can specify it in the web part, but I don't know how to specify it when starting the container.

**Comment by dotneft** [comment]
Please, specify in web part.
