### ISSUE TITLE
TimescaleDB is not enabled on already existing databases

### ISSUE THREAD

**Issue by xabinapal** [zabbix/zabbix-docker#877]
##### SUMMARY

When using the PostgreSQL version of Zabbix Server container image, if the `ENABLE_TIMESCALEDB` environment variable is set and a `zabbix` database already exists (but without TimescaleDB extension enabled), the extension is not enabled.

##### OS / ENVIRONMENT / Used docker-compose files

Container: `zabbix-server-pgsql`
Tag: `5.4.5-alpine`

##### CONFIGURATION

Not relevant.

##### STEPS TO REPRODUCE

```
$ docker run \
    --name timescaledb \
    --network zabbix \
    --remove \
    --detach \
    --env POSTGRES_PASSWORD=test \
    docker.io/timescale/timescaledb:2.4.2-pg13

$ docker exec timescaledb psql \
    --user postgres \
    --command "CREATE DATABASE zabbix TEMPLATE template0"
CREATE DATABASE

$ docker exec timescaledb psql \
    --user postgres \
    --db "zabbix" \
    --command "SELECT * FROM pg_extension WHERE extname = 'timescaledb'"
 oid | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
-----+---------+----------+--------------+----------------+------------+-----------+--------------
(0 rows)

$ docker run \
    --name zabbix \
    --network zabbix \
    --rm \
    --env DB_SERVER_HOST=timescaledb \
    --env POSTGRES_DB=zabbix \
    --env POSTGRES_USER=postgres \
    --env POSTGRES_PASSWORD=test \
    --env ENABLE_TIMESCALEDB=true \
    docker.io/zabbix/zabbix-server-pgsql:5.4.5-alpine
```

##### EXPECTED RESULTS

TimescaleDB should be enabled on the `zabbix` database by executing `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;` on the database and the `/usr/share/doc/zabbix-server-postgresql/timescaledb.sql` script should be executed next.

```
** Database 'zabbix' already exists. Please be careful with database owner!
** Creating 'zabbix' schema in PostgreSQL

NOTICE:  PostgreSQL version 13.4 is valid
NOTICE:  TimescaleDB extension is detected
NOTICE:  TimescaleDB version 2.4.2 is valid
NOTICE:  TimescaleDB is configured successfully
```

##### ACTUAL RESULTS

TimescaleDB extension is not enabled on the `zabbix` database and `/usr/share/doc/zabbix-server-postgresql/timescaledb.sql` script is not executed.

```
** Database 'zabbix' already exists. Please be careful with database owner!
** Creating 'zabbix' schema in PostgreSQL

NOTICE:  PostgreSQL version 13.4 is valid
ERROR:  TimescaleDB extension is not installed
```

**Comment by dotneft** [comment]
We can not enable any extensions from our side. We just use enabled features. So please enable feature on PostgreSQL side before.

**Comment by xabinapal** [comment]
@dotneft I'm not sure that is true, the entrypoint script is currently trying to enable the extension, but it's not selecting the Zabbix database so the command fails. Just submitted a PR right before I noticed your comment.

**Comment by dotneft** [comment]
Ok. I see your idea. Will be fixed soon :-) Thank you!

**Comment by dotneft** [comment]
Fixed!
