### ISSUE TITLE
zabbix-build-mysql:alpine-5.4.5 does not exist

### ISSUE THREAD

**Issue by slavoren** [zabbix/zabbix-docker#880]
##### SUMMARY

Docker file for alpine version 5.4 is building image from zabbix-build-mysql:alpine-5.4.5 But that image does not exist on dockerhub.

ARG MAJOR_VERSION=5.4
ARG ZBX_VERSION=${MAJOR_VERSION}.5
ARG BUILD_BASE_IMAGE=zabbix-build-mysql:alpine-${ZBX_VERSION}

##### OS / ENVIRONMENT / Used docker-compose files

zabbix-docker/Dockerfiles/server-mysql/alpine/Dockerfile

##### STEPS TO REPRODUCE

```yaml
docker build -t bug .
```

##### EXPECTED RESULTS

Container should be built

##### ACTUAL RESULTS

Container does not build, because image the docker relies on does not exists, or to be more accurate, the specified tag does not exist. The nearest match is tag 5.4-latest (which actually is 5.4.5). This seems to be working earlier (I think the tag 5.4.5 existed before)

```paste below
Error: build failed with (<Service: zabbix-server>, "pull access denied for zabbix-build-mysql, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

```

**Comment by dotneft** [comment]
The procedure is changed. Currently all final builds are based on build images. You can check github actions how is it building now.

**Comment by slavoren** [comment]
OK, but in docker hub, there is only tag "alpine-5.4-latest" and in dockerfile (zabbix-docker/Dockerfiles/server-mysql/alpine/Dockerfile) you are using non existing tag "alpine-5.4.5" So if you only want to use latest, that dockerfile needs to be fixed.

**Comment by dotneft** [comment]
Please specify BUILD_BASE_IMAGE as you want. Tag does not exist to avoid incorrect build. Currently binary file exported from base image. So you need specify proper BUILD_BASE_IMAGE tag.
