### ISSUE TITLE
How feasible is it to create a zabbix server docker container and integrate it with AWS RDS?

### ISSUE THREAD

**Issue by alvaronhs** [zabbix/zabbix-docker#882]
Hi, i would like to know if it's feasible to connect a zabbix server docker container with AWS RDS databases.

Does this idea make sense? I would like to hear feedback for this idea from more experienced developers.

The reason i'm asking this is because our tech lead had this idea to connect both services which eventually would lead to us using Aurora RDS with zabbix server docker container in ECS or Fargate.

**Comment by kernbug** [comment]
Hi,

You can use Aurora RDS, but please choose wisely storage type and perform sizing to fit IOPS requirements correctly, for example General SSD storage type will have 3 IO for 1GB of storage with some amount of burst IO. So even if you have DB size requirement < 100 GB but you need 3000 IO all the time, you need to buy 1TB of storage.  Or use Provisioned IOPS with another IO allocation policy.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#USER_PIOPS

Regards,
Edgar
