### ISSUE TITLE
Zabbix server not available

### ISSUE THREAD

**Issue by Danielsups** [zabbix/zabbix-docker#884]
##### SUMMARY

I wanted to start by saying that I'm just starting with docker and zabbix so i might be the problem, to summarize, when i try to docker-compose the image i want a few warnings pop up but I'm able to get through the process and access the zabbix web service, but i can't seem to find the zabbix-agent container so i can get the ip (just 3 of them pop up, i think it might have something to do with the warnings i get when trying to docker-compose), I'll link below the instructional video I'm using but it could just be a different method for my type of server, anyway, thanks in advance and I'm open to answer any questions that might lead to the solution

https://www.youtube.com/watch?v=ScKlF0ICVYA

##### OS / ENVIRONMENT / Used docker-compose files

OS: Ubuntu 20.04.3 LTS
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

##### CONFIGURATION

Using the original file from the repository

##### STEPS TO REPRODUCE

```yaml
sudo docker-compose -f docker-compose_v3_ubuntu_mysql_latest.yaml up -d
```

##### ACTUAL RESULTS

```paste below
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
Starting zabbix-docker_db_data_mysql_1 ... done
Creating zabbix-docker_mysql-server_1  ... done
Creating zabbix-docker_zabbix-server_1 ... done
Creating zabbix-docker_zabbix-web-nginx-mysql_1 ... done

```

**Comment by dotneft** [comment]
Please try to use --profile=all as docker-compose argument

**Comment by Danielsups** [comment]
Tried 

`sudo docker-compose -f docker-compose_v3_ubuntu_mysql_latest.yaml --profile=all up -d
`

And this is what i get 
```
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
Pulling zabbix-agent (zabbix/zabbix-agent:ubuntu-5.4-latest)...
ERROR: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution

```

**Comment by dotneft** [comment]
some issue with DNS on your side:
```
registry-1.docker.io: Temporary failure in name resolution
```

**Comment by Danielsups** [comment]
Do you think that's a problem with my docker configs or is it something about my internet provider? This might be why i cant access the Zabbix web page when I'm on my own network, it only works when I'm using the vpn from my workplace, which is where the server is located

**Comment by Danielsups** [comment]
Hey, just so i can close this. after some research i found out that the problem could be solved by restarting docker with,

`systemctl restart docker`

It worked for me, after doing it i could successfully docker-compose the file and now the server appear as available, thx again for the help.
