### ISSUE TITLE
zabbix-agent is not created by docker-compose

### ISSUE THREAD

**Issue by ranrubin** [zabbix/zabbix-docker#889]
##### SUMMARY

zabbix-agent is not created after  running `docker-compose -f docker-compose_v3_ubuntu_pgsql_latest.yaml up -d` 

I'm clearly missing something. Went over many tutorials and documentation resources, they all present that the agent container should be created by simply by running docker compose. Does not happen for me.

##### OS / ENVIRONMENT / Used docker-compose files

docker-compose template: `docker-compose_v3_ubuntu_pgsql_latest.yaml`  
uname -a :  `Linux myhost 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`  

docker version: `Docker version 20.10.9, build c2ea9bc`
docker-compose version: `docker-compose version 1.29.2, build 5becea4c`

zabbix-docker branch: 5.4

##### CONFIGURATION

Did not make any changes

##### STEPS TO REPRODUCE

Run 

```yaml
~/zabbix-docker$ docker-compose -f docker-compose_v3_ubuntu_pgsql_latest.yaml up -d 
```

##### EXPECTED RESULTS

Creation of all the components, including `zabbix-agent`

##### ACTUAL RESULTS

You can see that only 3 containers were created by the docker-compose command

```paste below
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
Creating network "zabbix-docker_zbx_net_backend" with driver "bridge"
Creating network "zabbix-docker_zbx_net_frontend" with driver "bridge"
Creating network "zabbix-docker_default" with the default driver
Creating zabbix-docker_postgres-server_1 ... done
Creating zabbix-docker_db_data_pgsql_1   ... done
Creating zabbix-docker_zabbix-server_1   ... done
Creating zabbix-docker_zabbix-web-nginx-pgsql_1 ... done
```

**Comment by dotneft** [comment]
execute docker-compose with --profile=full or --profile=all.

**Comment by ranrubin** [comment]
Thank you, that was super quick, I appreciate it! 
Would love to submit a pr with documentation if it is possible

**Comment by carlsue** [comment]
the same problem ，3q。
i delete profile。
