### ISSUE TITLE
Zabbix deploy in kubernetes

### ISSUE THREAD

**Issue by legolego621** [zabbix/zabbix-docker#894]
##### SUMMARY

Hey!
I am trying to deploy zabbix to kubernetes.
I have a problem that when a zabbix server is deployed for more than one replica, when the alert is triggered, the notification is duplicated.
Can you please tell me if the zabbix server image has support for more than one node during replication?

##### OS / ENVIRONMENT / Used docker-compose files

https://github.com/zabbix/zabbix-docker/blob/5.4/kubernetes.yaml

**Comment by dotneft** [comment]
it is not recommended to have multiple running Zabbix servers pointed to one DB! Such installation will be available only since 6.0.
