### ISSUE TITLE
Launch on Kubernetes fails

### ISSUE THREAD

**Issue by tulqin** [zabbix/zabbix-docker#895]
Starting Zabbix Proxy (active) [zabbix-proxy-mysql]. Zabbix 5.4.7 (revision 84dc2ec).
Press Ctrl+C to exit.

     7:20211108:153759.970 Starting Zabbix Proxy (active) [zabbix-proxy-mysql]. Zabbix 5.4.7 (revision 84dc2ec).
     7:20211108:153759.970 **** Enabled features ****
     7:20211108:153759.970 SNMP monitoring:       YES
     7:20211108:153759.970 IPMI monitoring:       YES
     7:20211108:153759.970 Web monitoring:        YES
     7:20211108:153759.970 VMware monitoring:     YES
     7:20211108:153759.970 ODBC:                  YES
     7:20211108:153759.970 SSH support:           YES
     7:20211108:153759.970 IPv6 support:          YES
     7:20211108:153759.970 TLS support:           YES
     7:20211108:153759.970 **************************
     7:20211108:153759.970 using configuration file: /etc/zabbix/zabbix_proxy.conf
     7:20211108:153800.001 current database version (mandatory/optional): 02010003/02010003
     7:20211108:153800.001 required mandatory version: 05040000
     7:20211108:153800.001 starting automatic database upgrade
     7:20211108:153800.002 [Z3005] query failed: [1146] Table 'zabbix_proxy.profiles' doesn't exist [update profiles set idx='web.screens.period' where idx='web.charts.period']
     7:20211108:153800.002 database upgrade failed

**Comment by dotneft** [comment]
I recommend you drop all tables on proxy DB and recreate schema manually.
