### ISSUE TITLE
Incorrect env checked

### ISSUE THREAD

**Issue by andrewtwemlow** [zabbix/zabbix-docker#897]
The passive allow env is checked instead of the active allow.
Therefor it is not possible to use the agent in active mode only.

https://github.com/zabbix/zabbix-docker/blob/711ec702577b5fba45f9c7b5681b02be36f1862d/Dockerfiles/agent/windows/docker-entrypoint.ps1#L161

**Comment by dotneft** [comment]
Fixed! Thank you!
