### ISSUE TITLE
Letsencrypt and certificates names.

### ISSUE THREAD

**Issue by duviful** [zabbix/zabbix-docker#898]
##### SUMMARY
Hello,
we are automating the renewal of certificates on the host (Debian) running our zabbix deployment in docker.
i found out that the certificates name are pretty much hardcoded in the `docker-entrypoint.sh` file.

i was wandering if somebody has come up with some clever trick to allow the usage of SSL certificates stored on the host ( `/etc/letsencrypt/live/` in my case). An additional problem apply to this specific case, letsencrypt folder use simlinks from the live folder to the archive folder, requiring to expost the entire `/etc/letsencrypt' to the container.

i am willing to contributed to the code with a PR in case this problem has never come up and could be of some interest.

##### OS / ENVIRONMENT / Used docker-compose files
zabbix-web-nginx-pgsql container hosted on a debian10 linux VM.

**Comment by dotneft** [comment]
You can use proxy with Letsencrypt behind Zabbix frontend. We do not want to have Letsencrypt in vanilla docker images.

**Comment by duviful** [comment]
Hello, no need to add letsencrypt in vanilla image. 
i was thinking more about making the certificates filename an environmental variable.

with `NGINX_SSL_CONFIG` i can customize the certificates directory, but the filename are hardcoded:

`NGINX_SSL_CONFIG="/etc/ssl/nginx"`

`if [ -f "$NGINX_SSL_CONFIG/ssl.crt" ] && [ -f "$NGINX_SSL_CONFIG/ssl.key" ] && [ -f "$NGINX_SSL_CONFIG/dhparam.pem" ]; then`

to something like

`NGINX_SSL_CONFIG="/etc/ssl/nginx"`
`NGINX_SSL_CER_NAME="cert.pem"`
`NGINX_SSL_KEY_NAME="privkey.pem"`

`if [ -f "$NGINX_SSL_CONFIG/$NGINX_SSL_CER_NAME" ] && [ -f "$NGINX_SSL_CONFIG/$NGINX_SSL_KEY_NAME" ] && [ -f "$NGINX_SSL_CONFIG/dhparam.pem" ]; then`

**Comment by dotneft** [comment]
what about symlinks?

**Comment by duviful** [comment]
Bind mounted symlinks are followed from within the container and destination needs to be accessible as well, but that’s a problem specific to the usage of cerbot for certificate renewal. I wrote about that to give you/the readers some context.

This discussion pretty much explains it better: 
https://stackoverflow.com/questions/47791396/letsencrypt-docker-the-best-way-to-handle-symlink

i think that having the certificate folder and the certificate name as variables are enough to allow the use of cerbot for certificate automation (external to the zabbix's images)

**Comment by dotneft** [comment]
Certificate names as variables is not enough to solve the problem, Nginx configuration also should have different path, certificate name. So i think it is better to use reverse proxy with letsencrypt.

**Comment by duviful** [comment]
Thanks for the Chat. 
I will follow your suggestion.
Best
