### ISSUE TITLE
Zabbix server thinks it's out of disk space

### ISSUE THREAD

**Issue by c0bra** [zabbix/zabbix-docker#90]
I'm not exactly sure where this problem lies. I was running this zabbix setup with docker-compose on an EC2 instance with 10GB of EBS storage. It was running a bit low (< 200MB) so I upped the size to 50GB.  `df` on the server shows that everything was extended properly, but the Zabbix server somehow thinks it's still out of disk space. I have a Zabbix Server dashboard on a Grafana instance on the "Free disk space on / (percentage)" had dropped to below 1%, and now says "N/A".

Unless I am misunderstanding, all the data should pretty much be in the database (postgres in my case), which is in a volume mounted to the host machine.

Nothing in `docker system df` seems to show any problems with the container size. It's less than 300MB.  I tried `exec`ing into the running container and checking via `df` there. It all appears to be fine.

This problem is compounded by the fact that when I start the Zabbix docker image, it starts completely pegging the CPU and making the machine unusable, which makes it hard to debug.

The git version I'm on is 1ced9ed6d92f from Dec 1.

**Comment by dotneft** [comment]
Actually Zabbix uses OS information. Please use support.zabbix.com for such issues.

**Comment by c0bra** [comment]
For anyone who runs into the same issue: it turns out there were a bunch (several hundred) items created by the postgresql plugin index discovery settings, which caused a general overload.

Not sure how exactly this affected apparent disk space but getting rid of all the postgresql index items brought Zabbix back to life.

**Comment by dotneft** [comment]
It is very strange... But thank you very much for the information! :-)
