### ISSUE TITLE
fping problem with zabbix-server with pgsql support on docker

### ISSUE THREAD

**Issue by replay111** [zabbix/zabbix-docker#900]
##### SUMMARY
Zabbix server on docker. version 5.4 based on oracle linux - problem with fping:

```
docker exec -i --user root 60f45d1b55a0 /bin/bash
fping 8.8.8.8
/bin/bash: line 1: /usr/sbin/fping: Operation not permitted
ls -la /usr/sbin/fping
-rwxr-xr-x 1 root root 53424 Nov  2  2019 /usr/sbin/fping
```
I found this when I was trying to create discovery rule based on ping for my subnet.

##### OS / ENVIRONMENT / Used docker-compose files
docker --version: Docker version 20.10.11, build dea9396
zabbix-server-pgsql: zabbix/zabbix-server-pgsql:ol-5.4-latest

##### CONFIGURATION
```
DB_SERVER_HOST="192.168.1.1"
DB_SERVER_PORT="5432"
POSTGRES_USER="zabbix"
POSTGRES_PASSWORD="zabbix"
POSTGRES_DB="zabbix"
DB_SERVER_SCHEMA="zabbix"
```

##### STEPS TO REPRODUCE
run docker image
logon to docker shell
try to ping i.e google IP (or even 127.0.0.1)

##### EXPECTED RESULTS
working fping? 

##### ACTUAL RESULTS
```
/bin/bash: line 1: /usr/sbin/fping: Operation not permitted
```

**Comment by replay111** [comment]
With image based on centos (still zabbix 5.4) - same issue :/

**Comment by dotneft** [comment]
works fine for me:
```
zabbix-docker % COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose_v3_ol_pgsql_latest.yaml up -d
% docker exec -ti zabbix-docker_zabbix-server_1 bash
bash-4.4$ fping 8.8.8.8
8.8.8.8 is alive
```
```
docker --version
Docker version 20.10.8, build 3967b7d
```

**Comment by dotneft** [comment]
What OS you have as host?

**Comment by replay111** [comment]
```
cat /etc/debian_version 
10.11
```

**Comment by replay111** [comment]
I am not building image - just using the one that is published on dockerhub:
```
 docker images | grep -i zabbix
zabbix/zabbix-web-nginx-pgsql            ol-5.4-latest       7970abcbd258   6 days ago      358MB
zabbix/zabbix-server-pgsql               ol-5.4-latest       6bd0702c9571   6 days ago      185MB
```

**Comment by dotneft** [comment]
me too. I posted commands which I used. Could you try the same way?

**Comment by replay111** [comment]
OK this way is working - also I removed all images and run it manually from console - just simple image - seems to be ok.

I had one instance in Nomad - maybe this is a problem... let me check this one :/

**Comment by replay111** [comment]
OK - only instance running through Nomad has a problem - I've also checked on my Mac (same way on deb server):

```
docker run -dt \
--name zabbix-server \
-e DB_SERVER_HOST="192.168.1.1" \
-e DB_SERVER_PORT="5432" \
-e POSTGRES_USER="zabbix" \
-e POSTGRES_PASSWORD="zabbix" \
-e POSTGRES_DB="zabbix" \
-e DB_SERVER_SCHEMA="zabbix" \
-e ZBX_SERVER_HOST="127.0.0.1" \
-p 10051:10051 \
zabbix/zabbix-server-pgsql:ol-5.4-latest 

```
works fine... sorry for troubles :/
