### ISSUE TITLE
Ability to define custom php-fpm pm.PARAM values in fpm config

### ISSUE THREAD

**Issue by fpaternot** [zabbix/zabbix-docker#904]
##### SUMMARY
Ability to tune php-fpm threads variables to prevent overload issues. Specially useful when using limit to cap its resources. This helps protect other services while helping autoscale.

Currently fpm threads are hard coded and not customizable, unlike other fpm variables and zabbix parameters. It would be nice to set them to different env values, maybe even keeping current values as default ones to prevent breaking instalations.

##### OS / ENVIRONMENT / Used docker-compose files
zabbix-web-nginx-mysql:ubuntu-5.0* or newer
VM with 24vCPU, inside baremetal with 56 CPU threads
Container with limited CPU usage to 16 threads

##### CONFIGURATION
/etc/php/7.4/fpm/pool.d/zabbix.conf
```
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
...
php_value[memory_limit] = ${ZBX_MEMORYLIMIT}
```

##### STEPS TO REPRODUCE
- deploy any frontend image with limited cpu resources (my test case is 8 vcpus inside a 24vcpu dedicated VM)
- send just one request for large result with no concurrent request (retrieve all current problems from a 600k triggers / 5k failed ones)
- note frontend page load times
- send 1x container vcpus requests for large results (retrieve all current problems from a 600k triggers / 5k failed ones)
- see php-fpm threads consuming ~100% cpu per thread ($ top), 100% container alocated cpu ($ docker stats)
- note frontend page load times
- send 2x container vcpus requests for large results (retrieve all current problems from a 600k triggers / 5k failed ones)
- see php-fpm threads consuming ~50% cpu per thread ($ top), 100% container alocated cpu ($ docker stats)
- see frontend page load times increasing exponentially

##### EXPECTED RESULTS
with custom variables tuned into it, we can limit the number of concurrent threads and give 100% cpu usage to 100% threads, preserving load times and scaling nice and steady horizontally.

##### ACTUAL RESULTS
page load times increase with overload in cpu requests beeing processed. they shouldn't be processed while there is no capacity in that container yet.

**Comment by dotneft** [comment]
why you can not run multiple frontend containers with LB?

**Comment by fpaternot** [comment]
Hello, sorry for taking so long. Hollidays are different time of the year :)

So yes, we use LB, and have about 16 containers. However, there are times that all alocated cpu is consumed, but fpm still accepts new threads. This leads to a new thread sharing cpu, reducing performance of already running threads, also to a bigger system load.

Just like StartPollers and other zabbix params, im suggesting that we make it a variable so it can be customized accordinly to the size and performance of the container we want, with no drawbacks.

Happy hollidays ;)

**Comment by dotneft** [comment]
what params do you like to tune in this case? All of them? Some other?

**Comment by fpaternot** [comment]
I believe all `pm*` parameters should be fine.

A suggestion would be to set it as follows:

```
pm = ${FPM_PM}
pm.max_children = ${FPM_PM_MAX_CHILDREN}
pm.start_servers = ${FPM_PM_START_SERVERS}
pm.min_spare_servers = ${FPM_PM_MIN_SPARE_SERVERS}
pm.max_spare_servers = ${FPM_PM_MAX_SPARE_SERVERS}
pm.max_requests = ${FPM_PM_MAX_REQUESTS}
```

https://www.php.net/manual/en/install.fpm.configuration.php

If any of those variables is empty/null, we shouldn't set the value at all. This is true when setting `$FPM_PM = static` and `$FPM_PM_MAX_CHILDREN = int`, other parameters are not needed.

**Comment by dotneft** [comment]
Done! Please verify :-)
