### ISSUE TITLE
[FRESH INSTALL] Unable to determine current Zabbix database version: the table "dbversion" was not found.

### ISSUE THREAD

**Issue by HorselessName** [zabbix/zabbix-docker#905]
##### SUMMARY

Hello there!
I am doing a fresh install of a Docker Enviroment for Zabbix.

I am using those images:

```
docker pull mysql:8
docker pull zabbix/zabbix-server-mysql:alpine-5.4-latest
docker pull zabbix/zabbix-web-nginx-mysql:alpine-5.4-latest

```

And then running the containers...

1. MySQL Database:

```
docker run -d --name mysql-zabbix \
 --restart always \
 -p 3306:3306 \
 -v /mnt/dados/mysql/zabbix/data:/var/lib/mysql \
--network=zabbix-net \
--env MYSQL_RANDOM_ROOT_PASSWORD=true \
 -e MYSQL_DATABASE=zabbix \
 -e MYSQL_USER=zabbix \
 -e MYSQL_PASSWORD=<my_password> \
 mysql:8 \
--default-authentication-plugin=mysql_native_password \
--character-set-server=utf8mb4 \
--collation-server=utf8mb4_bin
```

2. Zabbix Server:

```
docker run -d --name zabbix-server \
 --restart always \
 -p 10051:10051 \
 -e MYSQL_ROOT_PASSWORD="<my_generated_root_password>" \
 -e DB_SERVER_HOST="mysql-zabbix" \
 -e DB_SERVER_PORT="3306" \
 -e MYSQL_USER="zabbix" \
 -e MYSQL_PASSWORD="<mysql_pass>" \
 -e MYSQL_DATABASE="zabbix" \
--network=zabbix-net \
zabbix/zabbix-server-mysql:alpine-5.4-latest

```

3. Zabbix Web

```
docker run --name zabbix-web -t \
      -e ZBX_SERVER_HOST="zabbix-server" \
      -e DB_SERVER_HOST="mysql-zabbix" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="<mysql_pass>" \
      -e MYSQL_ROOT_PASSWORD="<mysql_root_pass>" \
      --network=zabbix-net \
      -p 80:8080 \
      --restart unless-stopped \
      -d zabbix/zabbix-web-nginx-mysql:alpine-5.4-latest

```

But the problem is on the web-server step when i run the container if i try to access the web panel it gives me the message below.

> Unable to determine current Zabbix database version: the table "dbversion" was not found.

Can someone help me?

**Comment by dotneft** [comment]
Please check Zabbix server log.

**Comment by gogich77** [comment]
The error means that the DB user can access the database server but cannot query the zabbix database.
I had the same error because my database schema for Postgres was wrong.

**Comment by HorselessName** [comment]
> Please check Zabbix server log.

Zabbix Server Log shows exactly what i said in my message!


> The error means that the DB user can access the database server but cannot query the zabbix database. I had the same error because my database schema for Postgres was wrong.

Oh, thanks. I made Zabbix Schema all over again, but this time before installing Zabbix Server and it worked...
It turns out it was indeed the Database Schema wrong causing the problem.

Thanks!

**Comment by Amonkey00** [comment]
I met the same issue.

 Turns out that All you need to do is DELETE the `-e MYSQL_DATABASE zabbix` when creating mysql-server. :(
