### ISSUE TITLE
zabbix-server-pgsql won't start without POSTGRES_USER set

### ISSUE THREAD

**Issue by dzhus** [zabbix/zabbix-docker#91]
If `POSTGRES_USER` is not set, `DB_SERVER_ROOT_USER` is initialized with `postgres` default which is not documented in the image description, therefore PG availability check keeps failing forever (see https://github.com/zabbix/zabbix-docker/blob/593ca5d524ca3b73efb29b3f7cd8bf60c7ead3c2/agent/alpine/run_zabbix_component.sh#L216 ):
```
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
```
The description of `POSTGRES_USER` is therefore misleading as it implies that there're defaults which the image can work with.

Setting `POSTGRES_USER` to `zabbix` explicitly fixes this.

**Comment by dotneft** [comment]
fixed default DB_SERVER_ROOT_USER to 'zabbix'
