### ISSUE TITLE
Confused on Agent Host

### ISSUE THREAD

**Issue by DustyArmstrong** [zabbix/zabbix-docker#911]
##### SUMMARY

I'm running into an issue with the agent on Docker. I have followed the steps as suggested in the FAQ and other posts on on this repo. 

```
52828:20220131:004148.077 no active checks on server [zabbix-server:10051]: host [zabbix-agent] not found
52828:20220131:004348.100 no active checks on server [zabbix-server:10051]: host [zabbix-agent] not found
```

I have added `hostname:` to my compose file. The compose file is a copy of the one on this repo. 

```
 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-5.4-latest
  hostname: zabbix-agent
  profiles:
```

The hostname is set correctly in the container: 

```
bash-5.1$ hostname
zabbix-agent
```

I have also added the environment to the `.env_agent` as described. 

```
# ZBX_STARTAGENTS=3
ZBX_HOSTNAME=zabbix-agent
# ZBX_HOSTNAMEITEM=system.hostname
# ZBX_METADATA=
```
I have added the DNS name `zabbix-agent` to the Configuration > Hosts page as I believe is correct. 

##### OS / ENVIRONMENT / Used docker-compose files

Using this docker file: https://raw.githubusercontent.com/zabbix/zabbix-docker/5.4/docker-compose_v3_alpine_mysql_latest.yaml

`Docker version 20.10.12, build e91ed57`
`docker-compose version 1.29.2, build 5becea4c`

##### STEPS TO REPRODUCE

I pulled the repository and ran `docker-compose --profile all up -d`. 

##### ADDITIONAL CONFIG

I also added to the compose file `hostname: zabbix-server` to the main server to see if that would work.

```
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:alpine-5.4-latest
  hostname: zabbix-server
```

##### EXPECTED RESULTS

The agent to be found.

##### ACTUAL RESULTS

```
52828:20220131:004048.061 active check configuration update from [zabbix-server:10051] started to fail (cannot connect to [[zabbix-server]:10051]: [111] Connection refused)
52828:20220131:004148.077 active check configuration update from [zabbix-server:10051] is working again
52828:20220131:004148.077 no active checks on server [zabbix-server:10051]: host [zabbix-agent] not found 52828:20220131:004348.100 no active checks on server [zabbix-server:10051]: host [zabbix-agent] not found
```

### EXTRA INFORMATION

I'm also seeing a lot of logs on the zabbix server container: 

```
237:20220131:004054.707 cannot parse proxy data from active proxy at "172.16.238.5": proxy "zabbix-proxy-sqlite3" not found
237:20220131:004055.709 cannot parse proxy data from active proxy at "172.16.238.5": proxy "zabbix-proxy-sqlite3" not found
```

My containers were automatically named as the below if it makes a difference:

```
zabbix-docker_zabbix-web-nginx-mysql_1
zabbix-docker_zabbix-proxy-mysql_1
```

**Comment by dotneft** [comment]
Just add zabbix-agent host in Zabbix web.

**Comment by DustyArmstrong** [comment]
> Just add zabbix-agent host in Zabbix web.

Would that be here?

![image](https://user-images.githubusercontent.com/13500305/151862650-104dd32b-c0d2-491d-bae9-4351c0c971f4.png)

**Comment by dotneft** [comment]
looks correct

**Comment by DustyArmstrong** [comment]
That's what I had before but I still get the same error: 

Agent container

```
371734:20220131:195652.275 active check configuration update from [zabbix-server:10051] started to fail (cannot connect to [[zabbix-server]:10051]: [111] Connection refused)
371734:20220131:195752.298 active check configuration update from [zabbix-server:10051] is working again
371734:20220131:195752.298 no active checks on server [zabbix-server:10051]: host [zabbix-agent] not found
```

Server container

```
240:20220131:195752.298 cannot send list of active checks to "172.16.239.3": host [zabbix-agent] not found
```

**Comment by dotneft** [comment]
Please check Zabbix documentation about how to configure active checks: https://www.zabbix.com/documentation/current/en/manual/appendix/items/activepassive

**Comment by DustyArmstrong** [comment]
> Please check Zabbix documentation about how to configure active checks: https://www.zabbix.com/documentation/current/en/manual/appendix/items/activepassive

Thanks. So I assume this is normal behavior and it's just for active checks?

**Comment by dotneft** [comment]
correct, you can undef active servers param.

**Comment by Jurrer** [comment]
The correct answer is not turning off active checks.
The variable `ZBX_HOSTNAME` on agent must match the `*Host name` value in the web host configuration.

The `homelab` value in the pic 
![image](https://github.com/zabbix/zabbix-docker/assets/72750942/865dfc42-9f55-44e4-b73c-e1f0b2dbff03)

**Comment by dotneft** [comment]
only in case of active check requirement.
