### ISSUE TITLE
5.4.10 images are not in the DockerHub

### ISSUE THREAD

**Issue by vicioussn** [zabbix/zabbix-docker#912]
Hello!

Sorry for possibly wrong place for asking the question, feel free to close this.

##### SUMMARY
5.4.10 images are not in the DockerHub.
What is the process of building for Zabbix? When can I expect them to be in the DockerHub?

Thanks!

**Comment by dotneft** [comment]
Published.

**Comment by vicioussn** [comment]
Thanks!
