### ISSUE TITLE
Add pgsql variant of zabbix-proxy

### ISSUE THREAD

**Issue by xabinapal** [zabbix/zabbix-docker#913]
##### SUMMARY

No `zabbix-proxy-pgsql` image is available, neither in this repository nor DockerHub. `server`and `web` components support both `mysql` and `pgsql` and a `build` image already exists for this database, so it should be technically possible to create this variant.

**Comment by dotneft** [comment]
currently we do not have any plans for PostgreSQL. You can use many sqlite3 containers :-)

**Comment by hzd2020** [comment]
zabbix-web      | 2022-05-20 11:04:29,145 INFO success: nginx entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web      | 2022-05-20 11:04:29,145 INFO success: nginx entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web      | 2022-05-20 11:04:29,145 INFO success: php-fpm8.1 entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web      | 2022-05-20 11:04:29,145 INFO success: php-fpm8.1 entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web      | 127.0.0.1 - - [20/May/2022:11:04:30 +0800] "GET / HTTP/1.1" 200 3942 "-" "curl/7.81.0" "-"
zabbix-web      | 2022/05/20 11:04:41 [error] 18#18: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "CMessageHelper" not found in /usr/share/zabbix/include/func.inc.php:2039
zabbix-web      | Stack trace:
zabbix-web      | #0 /usr/share/zabbix/include/func.inc.php(2298): error()
zabbix-web      | #1 /usr/share/zabbix/include/classes/core/CAutoloader.php(77): zbx_err_handler()
zabbix-web      | #2 /usr/share/zabbix/include/classes/core/CAutoloader.php(77): require('...')
zabbix-web      | #3 /usr/share/zabbix/include/func.inc.php(2039): CAutoloader->loadClass()
zabbix-web      | #4 /usr/share/zabbix/include/classes/api/wrappers/CFrontendApiWrapper.php(80): error()
zabbix-web      | #5 /usr/share/zabbix/include/classes/api/wrappers/CApiWrapper.php(82): CFrontendApiWrapper->callMethod()
zabbix-web      | #6 /usr/share/zabbix/include/classes/user/CWebUser.php(99): CApiWrapper->__call()
zabbix-web      | #7 /usr/share/zabbix/include/classes/core/ZBase.php(464): CWebUser::checkAuthentication()
zabbix-web      | #8 /usr/share/zabbix/include/classes/core/ZBase.php(187): ZBase->authenticateUser()
zabbix-web      | #9 /usr/share/zabbix/include/config.inc.php(25): ZBase->run()
zabbix-web      | #10 /usr/share/zabbix/index.php(24): require_once('...')
zabbix-web      | #11 {main}
zabbix-web      |   th" while reading response header from upstream, client: 127.0.0.1, server: zabbix, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "localhost:8080"
zabbix-web      | 127.0.0.1 - - [20/May/2022:11:04:41 +0800] "GET / HTTP/1.1" 500 5 "-" "curl/7.81.0" "-"
zabbix-web      | 2022/05/20 11:04:51 [error] 18#18: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "CMessageHelper" not found in /usr/share/zabbix/include/func.inc.php:2039



Zabbix version is: 6.0.4

**Comment by dotneft** [comment]
decided do not prepare postgresql images.

**Comment by szuro** [comment]
> decided do not prepare postgresql images.

Can we have some context as to why it'll not be supported?

**Comment by dotneft** [comment]
1. too much images to support
2. not really required. MySQL and SQLite3 in most cases enough.

**Comment by mmacedo-landers** [comment]
> 2. not really required. MySQL and SQLite3 in most cases enough.

and those cases that aren't enough?

Is it really hard for you guys to add the image to support postgres?

**Comment by dotneft** [comment]
what is your case?

**Comment by mmacedo-landers** [comment]
I have a fleet of  >1000 devices and the server database is hosted on stackgres.

I want to keep consistency and have the proxies using the same stackgres instance to reduce costs (implicitly meaning that the BD should be postgres). @dotneft

**Comment by dotneft** [comment]
How database engine on Zabbix server related to DB engine on proxy? You can choose any available.

**Comment by mmacedo-landers** [comment]
Yes, but as I told you I have a stackgres instance and I want the proxies to connect to it. 
but the DB engine for stackgres only supports postgresql.

**Comment by kernbug** [comment]
> Yes, but as I told you I have a stackgres instance and I want the proxies to connect to it. but the DB engine for stackgres only supports postgresql.

Hello. You can vote for this issue: https://support.zabbix.com/browse/ZBXNEXT-8931 and contact sales@zabbix.com to discuss sponsored development. Unfortunately we don't have unlimited human resources, but we can encourage the development of this image if you sponsor this feature request.

In addition, the current project is completely open source code including github actions customizations, you can create such a container, make a PR request, or share your work with the community using own repository.
