### ISSUE TITLE
Zabbix Agent2 image not exposing hostInterface env vars

### ISSUE THREAD

**Issue by dkpat12** [zabbix/zabbix-docker#916]
##### SUMMARY

Hi there, I have a need to modify the hostInterface values on the agent2 docker image, but the entrypoint script has those values commented out so that they don't get set in the configuration files. If I'm reading the documentation correctly, I need to modify that configuration to have the agent-server connections use DNS instead of IP addresses. Am I missing something about these?

##### OS / ENVIRONMENT / Used docker-compose files

https://github.com/zabbix/zabbix-docker/blob/5.4/Dockerfiles/agent2/ubuntu/docker-entrypoint.sh#L169-L170 

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
Actually Zabbix should try to resolve IP to DNS, do you have different IP / interface for outgoing connections from Zabbix agent side?

**Comment by dotneft** [comment]
Fixed! Thank you!

**Comment by dkpat12** [comment]
Thank you for fixing!

I believe I do have different interfaces. I'm setting zabbix up in kubernetes so the IP address that the agent pod uses could change and I need the server to prefer using the kubernetes service address to communicate with the agent.  Meanwhile outgoing communications from the agent would be from the agent's pod IP.

**Comment by dkpat12** [comment]
I just noticed this change didn't make it into the container images for the 6.0 cut. 

Do you know when this change might be released?

**Comment by dotneft** [comment]
Already.
