### ISSUE TITLE
How to install the ODBC driver of Oracle and MSSQL in the container?

### ISSUE THREAD

**Issue by chenyz1984** [zabbix/zabbix-docker#918]
In our environment, We want to monitor the Oracle and MSSQL though the ODBC connection.
So,how to install the odbc driver for Oracle and mssql in zabbix-server-pgsql image and the driver can not missing after the the docker restart? thank you very much!

**Comment by dotneft** [comment]
You need to extend our official image with ODBC drivers. Just use our images as base images.
