### ISSUE TITLE
error with zabbix-server-mysql:alpine-6.0-latest kubernetes

### ISSUE THREAD

**Issue by dionisus** [zabbix/zabbix-docker#919]
** Preparing Zabbix server
** Using MYSQL_USER variable from ENV
** Using MYSQL_PASSWORD variable from ENV
** Using MYSQL_ROOT_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: mysql-server
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
** Creating 'zabbix' user in MySQL database
** Database 'zabbix' already exists. Please be careful with database COLLATE!
** Table 'zabbix.dbversion' already exists.
** Preparing Zabbix server configuration file
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ListenIP": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ListenPort": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ListenBacklog": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SourceIP": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "LogType": 'console'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "LogFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "LogFileSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "PidFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DebugLevel": '3'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBTLSConnect": 'required'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBTLSCAFile": '/tmp/secrets/root-ca.pem'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBTLSCertFile": '/tmp/secrets/client-cert.pem'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBTLSKeyFile": '/tmp/secrets/client-key.pem'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBTLSCipher": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBTLSCipher13": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBHost": 'mysql-server'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBName": 'zabbix'...updated
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBSchema": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBPort": '3306'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VaultDBPath": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VaultURL": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBUser": 'zabbix'...updated
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBPassword": '****'. Enable DEBUG_MODE to view value ...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "AllowUnsupportedDBVersions": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartReportWriters": '3'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "WebServiceURL": 'http://zabbix-web-service:10053/report'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HistoryStorageURL": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HistoryStorageTypes": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HistoryStorageDateIndex": '1'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBSocket": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StatsAllowedIP": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartIPMIPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartPollersUnreachable": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartTrappers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartPingers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartDiscoverers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartHistoryPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartHTTPPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartPreprocessors": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartTimers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartEscalators": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartAlerters": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartTimers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartEscalators": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartLLDProcessors": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "JavaGateway": 'zabbix-java-gateway'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "JavaGatewayPort": '10052'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartJavaPollers": '5'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartVMwareCollectors": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VMwareFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VMwarePerfFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VMwareCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VMwareTimeout": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SNMPTrapperFile": '/var/lib/zabbix/snmptraps/snmptraps.log'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartSNMPTrapper": '1'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HousekeepingFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "MaxHousekeeperDelete": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ServiceManagerSyncFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SenderFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "CacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "CacheUpdateFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartDBSyncers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HistoryCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HistoryIndexCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TrendCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TrendFunctionCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ValueCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "Timeout": '4'...updated
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TrapperTimeout": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "UnreachablePeriod": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "UnavailableDelay": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "UnreachableDelay": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "AlertScriptsPath": '/usr/lib/zabbix/alertscripts'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ExternalScripts": '/usr/lib/zabbix/externalscripts'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "FpingLocation": '/usr/sbin/fping'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "Fping6Location": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SSHKeyLocation": '/var/lib/zabbix/ssh_keys'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "LogSlowQueries": '3000'...updated
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartProxyPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ProxyConfigFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ProxyDataFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SSLCertLocation": '/var/lib/zabbix/ssl/certs/'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SSLKeyLocation": '/var/lib/zabbix/ssl/keys/'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SSLCALocation": '/var/lib/zabbix/ssl/ssl_ca/'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "LoadModulePath": '/var/lib/zabbix/modules/'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCAFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCRLFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCertFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherAll": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherAll13": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherCert": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherCert13": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherPSK": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherPSK13": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSKeyFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSPSKIdentity": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSPSKFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ServiceManagerSyncFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HANodeName": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "NodeAddress": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "User": 'zabbix'...added
Starting Zabbix Server. Zabbix 6.0.0 (revision 5203d2e).
Press Ctrl+C to exit.

     7:20220217:190744.404 Starting Zabbix Server. Zabbix 6.0.0 (revision 5203d2e).
     7:20220217:190744.404 ****** Enabled features ******
     7:20220217:190744.404 SNMP monitoring:           YES
     7:20220217:190744.404 IPMI monitoring:           YES
     7:20220217:190744.404 Web monitoring:            YES
     7:20220217:190744.404 VMware monitoring:         YES
     7:20220217:190744.404 SMTP authentication:       YES
     7:20220217:190744.404 ODBC:                      YES
     7:20220217:190744.404 SSH support:               YES
     7:20220217:190744.404 IPv6 support:              YES
     7:20220217:190744.404 TLS support:               YES
     7:20220217:190744.404 ******************************
     7:20220217:190744.404 using configuration file: /etc/zabbix/zabbix_server.conf
     7:20220217:190744.412 cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)

**Comment by dotneft** [comment]
You have corrupted DB, probably need increase performance for DB or increase start up timeout for Zabbix server (at least for first start up).
