### ISSUE TITLE
Remove default User/password from kubernetes deployment

### ISSUE THREAD

**Issue by AndreHelwig** [zabbix/zabbix-docker#920]
https://github.com/zabbix/zabbix-docker/blob/bd65b3cf5091e83c428e8ab1deec046488b86087/kubernetes.yaml#L1316
https://github.com/zabbix/zabbix-docker/blob/bd65b3cf5091e83c428e8ab1deec046488b86087/kubernetes.yaml#L1317
https://github.com/zabbix/zabbix-docker/blob/bd65b3cf5091e83c428e8ab1deec046488b86087/kubernetes.yaml#L1318

Would be great to replace them with "variables" instead ow writing Passwords into kubernetes deployment.

Thanks a lot.

**Comment by dotneft** [comment]
What do you mean? Could you show us an example?

**Comment by AndreHelwig** [comment]
In that kubernetes.yml deployment file at 

https://github.com/zabbix/zabbix-docker/blob/bd65b3cf5091e83c428e8ab1deec046488b86087/kubernetes.yaml#L1316-1318

**Comment by dotneft** [comment]
Yes, I understood where, but what you suggest? Use environment variables or external secret file or...?

**Comment by AndreHelwig** [comment]
I would prefer environment variables.

**Comment by dotneft** [comment]
do you have an example? I can not find any best practices about env variables as secrets.

**Comment by dotneft** [comment]
decided to leave the example as is. Feel free to modify it as you want :-)
