### ISSUE TITLE
zabbix agent issue to start container with PASSIVESERVERS using CIDR and ZBX_ACTIVE_ALLOW: false

### ISSUE THREAD

**Issue by guilh22** [zabbix/zabbix-docker#921]
##### SUMMARY
It seems that zabbix agent use the same list as passiveserver for the activeservers even if specified otherwise. It is allowed to use CIDR in PASSIVESERVER (like 10.42.72.0/24) but not in activeserver. But since the list of activeserver seems to be always equals to passiveserver there is no way to make cidr work in passive field. I even tried to disable ACTIVE_ALLOW but even if active allow is set to false, it seems the active server are set identical to passive server in the config file preventing the container to boot

##### OS / ENVIRONMENT / Used docker-compose files
I used official image from this repo (zabbix-agent alpine-6.0-latest)

##### CONFIGURATION
Set ZBX_PASSIVESERVERS with a CIDR like 10.42.72.0/24 in the list of servers [ZBX_PASSIVESERVERS: 127.0.0.1,zabbix-server,10.42.72.0/24]
Set ZBX_ACTIVE_ALLOW to false [ZBX_ACTIVE_ALLOW: false]
Set ZBX_ACTIVESERVERS to what so ever (it is never used anyway...) [ZBX_ACTIVESERVERS: 127.0.0.1,zabbix-server]

##### STEPS TO REPRODUCE
set this configuration to zabbix agent docker image and try to boot it. The container will fail to boot with the logs saying that it is impossible to set ActiveServers with a CIDR (which isnt the case: Active is disabled, activeserver also have its own list of activeserver (which doesnt have CIDR inside).

##### EXPECTED RESULTS
Zabbix-agent should start without crashing. The active allow is disabled. If active allow would be enabled, it should then use the list 
127.0.0.1,zabbix-server instead of the value from ZBX_PASSIVESERVERS

##### ACTUAL RESULTS
...
Fri, Feb 18 2022 4:20:41 pm | ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherPSK13": ''...removed
Fri, Feb 18 2022 4:20:41 pm | ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSKeyFile": ''...removed
Fri, Feb 18 2022 4:20:41 pm | ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSPSKIdentity": ''...removed
Fri, Feb 18 2022 4:20:41 pm | ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSPSKFile": ''...removed
Fri, Feb 18 2022 4:20:42 pm | ** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "User": 'zabbix'...added
Fri, Feb 18 2022 4:20:42 pm | zabbix_agentd [8]: error parsing the "ServerActive" parameter: address "10.42.72.0/24:10051" is invalid

**Comment by dotneft** [comment]
ServerActive does not allow CIDR, you must specify exact IP / DNS for remote Zabbix servers / proxy.

**Comment by guilh22** [comment]
I know that read correctly please

**Comment by dotneft** [comment]
Ah... I see the problem, agree. Will be fixed soon! Thank you!

**Comment by guilh22** [comment]
thanks for reading and understanding the issue ;)

**Comment by guilh22** [comment]
Seems to be the case with 5.4 too

**Comment by guilh22** [comment]
Is there an ETA for this?

**Comment by dotneft** [comment]
Hmm... I can not reproduce the problem. So I specified:
```
ZBX_PASSIVESERVERS=127.0.0.1,zabbix-server,10.42.72.0/24
ZBX_ACTIVE_ALLOW=false
ZBX_ACTIVESERVERS=test
```
and logs from Zabbix agent:
```
** Preparing Zabbix agent
** Preparing Zabbix agent configuration file
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "PidFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogType": 'console'...added
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogFileSize": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "DebugLevel": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "SourceIP": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LogRemoteCommands": ''...removed
** Using 'zabbix-server,127.0.0.1,zabbix-server,10.42.72.0/24' servers for passive checks
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Server": 'zabbix-server,127.0.0.1,zabbix-server,10.42.72.0/24'...updated
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenPort": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenIP": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ListenBacklog": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "StartAgents": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "ServerActive": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostInterface": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostInterfaceItem": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Hostname": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostnameItem": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostMetadata": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "HostMetadataItem": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "RefreshActiveChecks": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "BufferSend": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "BufferSize": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "MaxLinesPerSecond": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Timeout": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "Include": '/etc/zabbix/zabbix_agentd.d/'...added first occurrence
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "UnsafeUserParameters": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "LoadModulePath": '/var/lib/zabbix/modules/'...added
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSConnect": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSAccept": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCAFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCRLFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSServerCertIssuer": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSServerCertSubject": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCertFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherAll": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherAll13": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherCert": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherCert13": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherPSK": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSCipherPSK13": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSKeyFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSPSKIdentity": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "TLSPSKFile": ''...removed
** Updating '/etc/zabbix/zabbix_agentd.conf' parameter "User": 'zabbix'...added
Starting Zabbix Agent [2728db8945b8]. Zabbix 6.2.0alpha1 (revision ee0c899).
Press Ctrl+C to exit.

 20554:20220226:214504.536 Starting Zabbix Agent [2728db8945b8]. Zabbix 6.2.0alpha1 (revision ee0c899).
 20554:20220226:214504.537 **** Enabled features ****
 20554:20220226:214504.537 IPv6 support:          YES
```

**Comment by guilh22** [comment]
Ok, so after more test, it seems it is because of this:

I also have ZBX_SERVER_HOST and ZBX_SERVER_PORT defined.

It seems those are automatically added at the start of the passive and active list.

It should be written in the image documentation if this is intended.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/3695456/157486727-141598e4-7d91-45a8-a7bd-5289a3f0f7bd.png">

**Comment by dotneft** [comment]
That could be, but if you specify ZBX_ACTIVE_ALLOW=false, ZBX_ACTIVESERVERS will be ignored completely!

**Comment by guilh22** [comment]
ok, so if I set the active allow to false it is still allow Active check but only for the main connection that is set using ZBX_SERVER_HOST?

**Comment by dotneft** [comment]
It does not allow active checks at all.

**Comment by guilh22** [comment]
Ok, so best way to have both set exactly like I want would be to not put the ZBX_SERVER_HOST and PORT and only set PASSIVESERVER and ACTIVESERVER?

**Comment by dotneft** [comment]
Hm... what do you want? Could you describe the task?

**Comment by guilh22** [comment]
I want to allow specific subnet for passivecheck and specific ip:port for the actives.

If I understood correctly, The ZBX_SERVER_HOST and PORT are kinda useless in my situation as they are use only if you have just one server and not when using multiple proxy/server. The goal is to have the same agent config for prod/staging/dev and eventually being able to monitor all agent from all environment. the ip range are for our CI/CD that can create a new environment on the go (k8s) for us to try on something without impacting our main dev/staging/prod build.

**Comment by dotneft** [comment]
do you want to have **ONLY** passive checks or active + passive with different set of servers / proxies?
