### ISSUE TITLE
Allow username other that "root" as MYSQL_ROOT_USER

### ISSUE THREAD

**Issue by bikeusaland** [zabbix/zabbix-docker#923]
##### SUMMARY

Allow other username other than "root" to be the primary database user

##### OS / ENVIRONMENT / Used docker-compose files

Dockerfiles -> aerver-mysql -> alpine -> docker-entrypoint.sh

##### STEPS TO REPRODUCE

1) Create RDS with username other than "root" and use the needed scripts to initialize
2) Try to connect using docker-compose -f docker-compose_v3_alpine_mysql_latest.yaml run zabbix-server up

**Comment by bikeusaland** [comment]
The following PR solves this issue and allows for the configuration to be more dynamic
https://github.com/zabbix/zabbix-docker/pull/922

**Comment by dotneft** [comment]
Done!
