### ISSUE TITLE
zabbix 6.0 images not available in RedHat registry

### ISSUE THREAD

**Issue by grunlab** [zabbix/zabbix-docker#925]
zabbix 6.0 has been released ~10 days ago.

zabbix 6.0 images are not yet available in RedHat registry --> https://catalog.redhat.com/software/containers/search?q=zabbix%206.0

Could you please make them available?
Thanks in advance

**Comment by dotneft** [comment]
We are waiting certification process. According RedHat Cert Team it could take about 2-3 weeks. All images are already prepared and uploaded.

**Comment by grunlab** [comment]
OK, thank you for the information.

**Comment by dotneft** [comment]
Published!

**Comment by grunlab** [comment]
Great. Thank you
