### ISSUE TITLE
Zabbix sever is unable to connect with Zabbix Agent on Port 10050

### ISSUE THREAD

**Issue by sundeeplella** [zabbix/zabbix-docker#929]
We have used docker container images to install the server and other components  along with agent. This is working when all the components are in the same VM(Zabbix server & Agent are on same VM). But when we install New Zabbix agent via docker container on a New VM (Ubuntu 20.04 & CentOs 8) it is not opening port 10050 and seeing the following error.

**Get value from agent failed: cannot connect to [[IP address]:10050]: [111] Connection refused**

##### SUMMARY
We disabled Firewall & SElinux and also tried different versions of docker container for Zabbix agent and still the port is not being exposed. 

Below are the OS Versions where Zabbix agent is installed Via Docker container
Ubuntu 18.04, 20.04
CentOs 8
Rhel 8

Docker images are downloaded from following location. 
https://hub.docker.com/r/zabbix/zabbix-agent
docker run --name  some-zabbix-agent -e ZBX_HOSTNAME="Some Host Name" -e ZBX_SERVER_HOST="IP of zabbix Server" -e ZBX_LISTENPORT=10050 --privileged -d zabbix/zabbix-agent:alpine-6.0-latest
docker run --name some-zabbix-agent -e ZBX_HOSTNAME="Some Host Name" -e ZBX_SERVER_HOST="IP of zabbix Server" -d zabbix/zabbix-agent2:alpine-6.0-latest

**Comment by dotneft** [comment]
If you would like to use passive checks you need expose 10050 port.

**Comment by sundeeplella** [comment]
I ran the below command for exposing the 10050 0n passive checks and still not working

docker run --name "IP-Address of Zabbix server"--link "zabbix-agent-name":zabbix-agent -d zabbix/zabbix-server:latest

**Comment by dotneft** [comment]
--link is not expose. Please check Docker documentation, you need to use -p option: https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose

**Comment by sundeeplella** [comment]
Thanks for the documentation. I have already tried that by exposing the port on the image and when the container is created it shows the port as 10050/tcp. But it is not not working and when I do netstat -tlpn the port is not showing as opened.

docker run -p 10050/tcp -d "image id"
docker run --expose 10050 ubuntu bash

![image](https://user-images.githubusercontent.com/46731093/156805031-404d18cf-b20c-4091-8f94-6313731380de.png)

![image](https://user-images.githubusercontent.com/46731093/156805368-be278cea-3d70-4c1e-b951-95eb813e0143.png)

**Comment by dotneft** [comment]
On screenshot I do not see that zabbix agent container has exposed port.

**Comment by sundeeplella** [comment]
Yeah that is what happening, even after running docker expose command for 10050 the port is not showing up.

![image](https://user-images.githubusercontent.com/46731093/156827426-cf8b4133-2b07-45a1-89fa-be076d42670f.png)

Firewall is inactive
![image](https://user-images.githubusercontent.com/46731093/156827614-7403820f-6bf6-47a9-8161-21e2a7762b9c.png)

SElinux is Disabled
![image](https://user-images.githubusercontent.com/46731093/156827854-f0091093-ae6f-4d90-8037-68b71c701101.png)

If I do a Zabbix Agent installation from the repo instead of using Docker image it is working.
![image](https://user-images.githubusercontent.com/46731093/156828331-2b6c3f29-c40f-4fe6-9e70-407029c716ba.png)
In my case when I am use the Docker Image for Zabbix Agent the port 10050/tcp is not working and if I use Repository (Package) for Zabbix agent the port 10050/tcp is working.

So I am wondering what is the issue that is causing the port 10050/tcp for not being exposed/opened when I use Docker image for Zabbix Agent.

**Comment by dotneft** [comment]
what command did you use to start zabbix agent in container with exposed port?

**Comment by sundeeplella** [comment]
Thank you for your recommendations.

I have fixed the issue by running the below command.
docker run -d -p 10050:10050 --name some-zabbix-agent -e ZBX_HOSTNAME="some-host-name" -e ZBX_SERVER_HOST="Zabbix server-IPaddress" zabbix/zabbix-agent:alpine-6.0-latest

Below command from official docker hub: https://hub.docker.com/r/zabbix/zabbix-agent
It didn't work for me.
docker run --name some-zabbix-agent -e ZBX_HOSTNAME="some-hostname" -e ZBX_SERVER_HOST="some-zabbix-server" -e ZBX_LISTENPORT=10050 -d zabbix/zabbix-agent:tag
