### ISSUE TITLE
Zabbix web service: Cannot fetch data: context canceled

### ISSUE THREAD

**Issue by mitko9922** [zabbix/zabbix-docker#930]
##### SUMMARY

After run and connect to zabbix web service container a get "Cannot fetch data: context canceled" when try to generate report from zabbix.

##### OS / ENVIRONMENT / Used docker-compose files
Docker version 20.10.7, build f0df350
OS: Raspdebian/Raspberry pi 4
tag: ubuntu-5.4-latest

##### STEPS TO REPRODUCE
docker run --name zabbix-web-service -e ZBX_ALLOWEDIP="172.20.240.3" --cap-add=SYS_ADMIN -d zabbix/zabbix-web-service:ubuntu-5.4-latest

##### EXPECTED RESULTS
Container was up, zabbix connect successfully, but when try to generate report from zabbix I get error: Cannot fetch data: context canceled
When try to run chromium from container I get: Unable to open X display

##### ACTUAL RESULTS
2022/03/06 17:03:35.660185 received report request from 172.20.240.3:50704
2022/03/06 17:03:35.660708 making chrome headless request with parameters url: http://172.20.240.1:8080/zabbix.php?action=dashboard.print&dashboardid=57&from=2022-03-05%2000%3A00%3A00&to=2022-03-06%2000%3A00%3A00, width: 1920, height: 292 for report request from 172.20.240.3:50704
2022/03/06 17:03:36.539350 Cannot fetch data: context canceled.

**Comment by dotneft** [comment]
Does 172.20.240.1 8080 available from the container?

**Comment by mitko9922** [comment]
Yes, itst available and try with curl 172.20.240.1:8080 frontend back successfully from web-service container.

**Comment by mitko9922** [comment]
I tested it on another environment, which is arm64 and it works without problems, on the environment with the problem the version is arm, is there any restriction for the arm architecture?

**Comment by dotneft** [comment]
currently no known issues.

**Comment by mitko9922** [comment]
Yes, and I wonder what the problem might be. The device with the problem is: Raspberry pi 4 with Linux image raspberrypi 5.10.17-v7l + armv7l GNU / Linux

**Comment by dotneft** [comment]
Yes, I just checked ARMv7, but the problem is slightly different. Did you try to start web-service container under "root"?

**Comment by mitko9922** [comment]
Thanks. I started the container as root and the report is already working! I wonder if there is a way without starting as root or I need to have another user. What's the problem :)

**Comment by dotneft** [comment]
I think you need to play with capabilities, looks like SYS_ADMIN is not enough in your case.

**Comment by dotneft** [comment]
I mean this one: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by mitko9922** [comment]
Thank you very much! I have one question, can I change the screen resolution for generated reports?

**Comment by dotneft** [comment]
I recommend you check official documentation and check our forum. The bug tracker here is dedicated for docker related issues.

But currently I do not think it is possible to change resolution. Probably you need to open feature request in https://support.zabbix.com/

**Comment by mitko9922** [comment]
OK, sorry, thank you again :)
