### ISSUE TITLE
Example of docker-compose configuration file

### ISSUE THREAD

**Issue by luweijun1992** [zabbix/zabbix-docker#932]
Can docker-compose provide a configuration file for zabbix-agent2.

In addition, can you provide the configuration file of docker-compose example for HA Mode.

**Comment by dotneft** [comment]
Just replace zabbix-agent with zabbix-agent2 in existing docker compose files. Regarding HA you can check https://github.com/zabbix/zabbix-docker/issues/931#issuecomment-1061548186 comment.

**Comment by luweijun1992** [comment]
> Just replace zabbix-agent with zabbix-agent2 in existing docker compose files. Regarding HA you can check [#931 (comment)](https://github.com/zabbix/zabbix-docker/issues/931#issuecomment-1061548186) comment.

Is the configuration file of agent and agent2 the same?

**Comment by dotneft** [comment]
mostly the same. Please check difference: https://www.zabbix.com/documentation/current/en/manual/appendix/agent_comparison

**Comment by luweijun1992** [comment]
> Just replace zabbix-agent with zabbix-agent2 in existing docker compose files. Regarding HA you can check [#931 (comment)](https://github.com/zabbix/zabbix-docker/issues/931#issuecomment-1061548186) comment.

I hope the official provides an HA-based docker-compose configuration file, thank you.

**Comment by dotneft** [comment]
Yes, documentation will be updated.

**Comment by luweijun1992** [comment]
> Yes, documentation will be updated.

When will it be provided, or provide it to me first, thank you.

**Comment by luweijun1992** [comment]
@dotneft 
What additional configuration is required to monitor docker?
![image](https://user-images.githubusercontent.com/58923704/157680549-a84fec8c-44f7-480a-be29-b81298aa792e.png)

**Comment by dotneft** [comment]
mount docker.sock from host machine.

**Comment by luweijun1992** [comment]
> mount docker.sock from host machine.

@dotneft 
Docker deploys zabbix, there are multiple images alpine\centos\ol\ubuntu, which one is the official recommendation, and which one will be used for a long time in the future.

**Comment by dotneft** [comment]
you can use everything you like except centos. I do not recommend use it. All others - if they will not change policy for distribution, they will be available.

**Comment by luweijun1992** [comment]
> you can use everything you like except centos. I do not recommend use it. All others - if they will not change policy for distribution, they will be available.

When I export a template from version 5.x and import it in 6.x, there will be the following prompt, two completely different template names, why are they merged?
![image](https://user-images.githubusercontent.com/58923704/158193225-58cea2d5-a454-427e-af87-8292408d3ae8.png)

**Comment by dotneft** [comment]
How is it related to docker images? I recommend you check Zabbix forum: https://www.zabbix.com/forum/
