### ISSUE TITLE
Discovery of File Systems with Agent running in a container

### ISSUE THREAD

**Issue by patricegautier** [zabbix/zabbix-docker#933]
##### SUMMARY

I recently noticed that the file systems automatically discovered on a server via vfs.fs.discovery I was monitoring made no sense and some looked like regular files..

After banging my head a bit, I realized it was because the Zabbix Agent on that server is run inside a container, and the file systems it is listing are the file systems that the container can see, including docker file mounts! This of course defeats the purpose of monitoring that server..

I think of a couple of options, neither satisfactory:

• I can explicitly mount some of the server file systems for the agent to discover and correctly monitor, but now I have to keep this up to date 
• I can run the agent directly on the server, but the container route seems better

The container is running in privileged mode so this should not be a permission issues

##### OS / ENVIRONMENT / Used docker-compose files

Zabbix Agent and Server 6.0.1

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

I think if the agent is running inside a container, then vfs.fs.discovery needs to take this into account, or possibly a new item needs to be introduced to look at the file system of the host server

**Comment by dotneft** [comment]
Zabbix agent discovers all mounted file systsems, you need to filter out what you do not need on host / template level.

**Comment by patricegautier** [comment]
That 'all file systems mounted to the container' right?  I really don't want to have to explicit maintain the mount of all the host's file systems to the container over time..

**Comment by dotneft** [comment]
No one wants to monitor everything. Use filter options on template / host level.

**Comment by patricegautier** [comment]
Understood about filtering what I don't want; the problem I'm trying to solve is that the file system of the host itself are not discovered by the agent when it's in a container..  I am trying to avoid (a lot of ) manual config on each host as well.

**Comment by dotneft** [comment]
It is described in https://support.zabbix.com/browse/ZBXNEXT-5329. Feel free to share your ideas and vote for feature request there.

**Comment by patricegautier** [comment]
Thanks for the pointer!
