### ISSUE TITLE
zabbix 5.4.11 images not available in RedHat registry --> URGENT

### ISSUE THREAD

**Issue by grunlab** [zabbix/zabbix-docker#935]
I'm currently running Zabbix 5.4.10 in Production and I'm impacted by this BUG --> https://support.zabbix.com/browse/ZBX-20649

The bug fix is available in 5.4.11 but this new version is not yet available in Redhat registry --> https://catalog.redhat.com/software/containers/zabbix/zabbix-server-mysql-54/61256016bd674341b5c5f472

Could you please make it available asap ?
Thanks in advance for your support.

**Comment by dotneft** [comment]
Published!

**Comment by grunlab** [comment]
Great, thank you
