### ISSUE TITLE
Zabbix 6.0 docker-compose version

### ISSUE THREAD

**Issue by kalyxnz** [zabbix/zabbix-docker#936]
##### SUMMARY
I have Zabbix up and running using the docker-compose files over HTTP, but I need to use SSL.
In order to secure the web front end with SSL I need more information, the docs don't appear to cover it.
1. What files and format types are required
2. Where should they be put in order for the container to ingest them
3. Are any changed required to the default .env files to enable SSL.

Also a guide to all the variables in the .env files would be amazing, e.g descriptions of what each variable does, and defaults etc.

##### OS / ENVIRONMENT / Used docker-compose files
docker-compose version with ngix and pgsql

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
Everything is documented. Also the documentation contains information about what exactly you need to mount to enable HTTPS: https://github.com/zabbix/zabbix-docker/tree/6.0/Dockerfiles/web-nginx-mysql/alpine
