### ISSUE TITLE
RHEL zabbix-server-mysql 6.0.2 : hostname command not found

### ISSUE THREAD

**Issue by grunlab** [zabbix/zabbix-docker#937]
The command hostname is missing in RHEL zabbix-server-mysql 6.0.2 image:

```
$ kubectl exec server-0 -ti -- ls -l /usr/bin/hostname
ls: cannot access '/usr/bin/hostname': No such file or directory
```

This command is needed/used into the docker-entrypoint.sh to setup HANodeName & NodeAddress:
https://github.com/zabbix/zabbix-docker/blob/6.0/Dockerfiles/server-mysql/rhel/docker-entrypoint.sh#L466

**Comment by dotneft** [comment]
Fixed in sources. Image is updated. Thank you!

**Comment by grunlab** [comment]
It looks the new image with the fix has not yet been pushed to RedHat registry --> last 6.0.2 tag was published the 14/03/2022

https://catalog.redhat.com/software/containers/zabbix/zabbix-server-mysql-60/622f43bb4a14c05796114d0e?tag=all

**Comment by dotneft** [comment]
Yeah, you are right. Published, but not published :-) Tried to publish again, looks like now it is ok.

**Comment by grunlab** [comment]
It is ok now :-)

```
$ kubectl exec -ti server-0 -- hostname
server-0
```

**Comment by dotneft** [comment]
Excellent! :-)
