### ISSUE TITLE
API URL doesn't work

### ISSUE THREAD

**Issue by boyadzhievb** [zabbix/zabbix-docker#938]
##### SUMMARY
Trying to open API URL:
 https://zabbix-server/zabbix/api_jsonrpc.php -H 'Content-Type: application/json-rpc'  -d '{'jsonrpc': '2.0', 'method': 'user.login', 'params': {'user': 'zabbix-agent', 'password': 'the_password123'}, 'id': '1'}'

returns error:
<title>404 Not Found</title>

##### OS / ENVIRONMENT / Used docker-compose files

Tried it with both nginx or apache images same result

##### CONFIGURATION

docker run --name zabbix-web-apache-mysql -t \
      -e ZBX_UPLOADMAXFILESIZE="8M" \
      -v /opt/zabbix-server/tls:/etc/ssl/apache2 \
      -e ZBX_SERVER_HOST="zabbix-server-mysql" \
      -e DB_SERVER_HOST="mysql-server" \
      -e MYSQL_DATABASE="zabbix" \
      -e MYSQL_USER="zabbix" \
      -e MYSQL_PASSWORD="zabbix_pwd" \
      -e MYSQL_ROOT_PASSWORD="root_pwd" \
      --network=zabbix-net \
      -p 80:8080 \
      -p 443:8443 \
      --restart unless-stopped \
      -d zabbix/zabbix-web-apache-mysql:ubuntu-latest

##### STEPS TO REPRODUCE
 https://zabbix-server/zabbix/api_jsonrpc.php -H 'Content-Type: application/json-rpc'  -d '{'jsonrpc': '2.0', 'method': 'user.login', 'params': {'user': 'zabbix-agent', 'password': 'the_password123'}, 'id': '1'}'

##### EXPECTED RESULTS

{"jsonrpc":"2.0","method":"apiinfo.version","id":1,"auth":null,"params":{}}
##### ACTUAL RESULTS
<title>404 Not Found</title>

**Comment by dotneft** [comment]
URL is not correct. Use this one https://zabbix-server/api_jsonrpc.php

**Comment by boyadzhievb** [comment]
blah, thanks, close it
