### ISSUE TITLE
zabbix-proxy-mysql:ol-5.4-latest GLIBC_2.29 not found 

### ISSUE THREAD

**Issue by stallion2303** [zabbix/zabbix-docker#940]
Run **microdnf install libnsl** or **microdnf update**

> Upgrading:
 glibc-2.28-164.0.5.el8_5.3.x86_64                                                                       ol8_baseos_latest                      3.8 MB
  replacing glibc-2.28-164.0.4.el8.x86_64
 glibc-common-2.28-164.0.5.el8_5.3.x86_64                                                                ol8_baseos_latest                      1.4 MB
  replacing glibc-common-2.28-164.0.4.el8.x86_64
 glibc-minimal-langpack-2.28-164.0.5.el8_5.3.x86_64                                                      ol8_baseos_latest                     61.2 kB
   replacing glibc-minimal-langpack-2.28-164.0.4.el8.x86_64

After zabbix crashes with an error
> /usr/sbin/zabbix_proxy: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /usr/sbin/zabbix_proxy)

**Comment by dotneft** [comment]
You need recompile Zabbix proxy if you would like to update packages in image.

**Comment by stallion2303** [comment]
The problem occurs even when installing a new package.
If you rebuild the image, the problem will not go away?

**Comment by dotneft** [comment]
rebuild image and recompile proxy

**Comment by bromine0x23** [comment]
`glibc-2.28-164.0.4.el8` seems to be a error release, and cannot be found in [Oracle Linux 8 BaseOS](https://yum.oracle.com/repo/OracleLinux/OL8/baseos/latest/x86_64/index.html) repo now without any description.
I think the images use this glibc release should be rebuild.

**Comment by bromine0x23** [comment]
I successfully upgrade glibc on `zabbix-server-pgsql:ol-5.4.10` (63ce71623fb4) from `glibc-2.28-164.0.2.el8.x86_64` to `glibc-2.28-164.0.5.el8_5.3.x86_64`.
But failed on `zabbix-server-pgsql:ol-5.4-latest`(5.4.11, 2dc4b369f3f7) from `glibc-2.28-164.0.4.el8.x86_64`.

It's obviously there are some fatal problems on `glibc-2.28-164.0.4.el8.x86_64`.

**Comment by dotneft** [comment]
Please check current images.

**Comment by stallion2303** [comment]
thanks the issue is gone
