### ISSUE TITLE
ldaps

### ISSUE THREAD

**Issue by zappbrannigan34** [zabbix/zabbix-docker#941]
Hello. My org used custom ca. I mount volume to server " - /etc/ssl/certs:/var/lib/zabbix/ssl/ssl_ca:ro". Custom certs installed on docker hosts and works well.
I try config ldap over web interface but got error "Cannot connect to LDAP server.". Try dns and ip   ldaps://10.64.64.3:636

How to show only ldap logs in docker logs?
How to set system ca certs or my cert chain?

Ubuntu docker-compose_v3_alpine_pgsql_latest.yaml

**Comment by dotneft** [comment]
is your cert self signed?

**Comment by zappbrannigan34** [comment]
My org have own cerificate authority

**Comment by dotneft** [comment]
then you need allow such CA for ldap. for example: https://www.ibm.com/support/pages/how-test-ca-certificate-and-ldap-connection-over-ssltls

**Comment by zappbrannigan34** [comment]
Its for host, not for container.

**Comment by dotneft** [comment]
I do not see difference

**Comment by zappbrannigan34** [comment]
connection to ldap made in containers, not in host.

**Comment by fpaternot** [comment]
I guess he is saying that the procedure is valid for both. Bare metal server, virtual server/VM, container.

**Comment by zappbrannigan34** [comment]
How? How this change apply inside container?

**Comment by zappbrannigan34** [comment]
> I do not see difference

difference that changes not affect container environment.

**Comment by kernbug** [comment]
1. Get certs and put them inside container
2. Adjust openldap configuration inside container

You can mount modified openldap by passing:  -v ${pwd}/ldap.conf:/etc/openldap/ldap.conf for example.

**Comment by zappbrannigan34** [comment]
> 1. Get certs and put them inside container
> 2. Adjust openldap configuration inside container
> 
> You can mount modified openldap by passing: -v ${pwd}/ldap.conf:/etc/openldap/ldap.conf for example.

Mount work. Need edit documentatin

**Comment by zappbrannigan34** [comment]
reopen

**Comment by fpaternot** [comment]
I believe you can accomplish this by:
 
- using mount solution
- configuring your container uppon start (custom entrypoint?)
- building your own image based on this one

However, this are the possible solutions to many of us, to many customizations needs we might have. I do agree that a section in manual should be considered to quick start people into customizing their images. Not just this case, but a more general one. There may be many who are skilled enough to build this by themselves, but many are not.

Should we open a new issue and perhaps send a PR?

**Comment by dotneft** [comment]
I do not think that we need document standard operations with images. How to customize images, how to build own images, how to mount anything is very clear described in official Docker documentation.

**Comment by fpaternot** [comment]
Fair enough. Maybe a link to that doc then? My point is to help newcomers to zabbix container world.
