### ISSUE TITLE
RHEL images contain security vulnerabilities

### ISSUE THREAD

**Issue by wbrown64** [zabbix/zabbix-docker#943]
##### SUMMARY

I am attempting to use RHEL based images of zabbix-proxy-sqlite3 and zabbix/zabbix-agent2 as part of a Kubernetes deployment of Zabbix, as is described here https://www.zabbix.com/integrations/kubernetes. I was able to pull the relevant images from here -> registry.connect.redhat.com/zabbix/zabbix-agent2-54:latest (and another for proxy), however when I preform ECR scans, I get 2 HIGH and 5 MED vulnerabilities.  I was wondering if these RHEL based images could be regenerated with these security issues addressed.  

NOTE:  I tried running docker build from this repo https://github.com/zabbix/zabbix-docker so I could add the yum update/upgrade myself, however it is trying to pull from docker registry on this imagedocker.io/library/zabbix-build-sqlite3:rhel-5.4.12 , which does not exist.  Which may be a separate bug in and of itself.  

##### OS / ENVIRONMENT / Used docker-compose files

Preferred Zabbix version 5.4 

##### STEPS TO REPRODUCE

Go to registry.connect.redhat.com/zabbix/zabbix-agent2-60:latest, and upload to a image scanning tool (Like AWS ECR) and note the vulns listed.  I can provide a sample if need be.  

```yaml

```

##### EXPECTED RESULTS

I would expect there to be no HIGH or MED vulnerabilities, or any at all. 

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
Please check now.

**Comment by wbrown64** [comment]
The 6.0 version for both products looks great!  I may have been confusing in my messaging, as I referenced 6.0 and 5.4.  Would it be possible to perform the same for the 5.4 version?  I see that it still hasn't been updated since I last pulled.  Thanks for the help on this!

**Comment by dotneft** [comment]
Version 5.4.12 will be available soon. Sorry, I though it was published already (

**Comment by dotneft** [comment]
Done!

**Comment by wbrown64** [comment]
Thank you!  Much appreciated
