### ISSUE TITLE
 Utilization of preprocessing manager processes over 75%

### ISSUE THREAD

**Issue by lawrence191** [zabbix/zabbix-docker#944]
##### SUMMARY

Zabbix currently monitors 500 servers, and I recently upgraded from 5.0.1 to version 6.0.3. I often need to restart the Zabbix Server process to resolve the "Preprocessing Manager Processes over 75%" problem. In version 5.0.1, the number of preprocessing worker processes was stable at 30. After upgrading to version 6.0.3, the number increased to 500, but still had the same problem.
![Snipaste_2022-04-10_20-56-30](https://user-images.githubusercontent.com/15275116/162619338-f6b5d916-f774-4a49-9212-da624d35a68d.jpg)

Every low point is after the restart.

How is it configured to get back to normal or is this a bug?

##### OS / ENVIRONMENT / Used docker-compose files

the docker-compose files：

version: "3"
services:
  zabbix-server:
    image：zabbix/zabbix-server-mysql:6.0.3-ubuntu
    container_name: zabbix-server
    ulimits:
       nproc: 65535
       nofile:
         soft: 65535
         hard: 65535
       memlock:
         soft: -1
         hard: -1
    privileged: true
    user: zabbix
    env_file:
      - /data/zabbix/zabbix_server.conf 
    cap_add: 
     - ALL
    restart: always
    network_mode: host

##### CONFIGURATION

ZBX_TIMEOUT=30
ZBX_LISTENPORT=10051
ZBX_STARTPOLLERS=95
ZBX_IPMIPOLLERS=10
ZBX_STARTPREPROCESSORS=500
ZBX_STARTPOLLERSUNREACHABLE=45
ZBX_STARTTRAPPERS=25
ZBX_STARTPINGERS=25
ZBX_STARTDISCOVERERS=35
ZBX_STARTHISTORYPOLLERS=130
ZBX_STARTHTTPPOLLERS=25
ZBX_STARTTIMERS=15
ZBX_STARTESCALATORS=95
ZBX_STARTALERTERS=35
ZBX_STARTLLDPROCESSORS=35
ZBX_HOUSEKEEPINGFREQUENCY=1
ZBX_MAXHOUSEKEEPERDELETE=10000
ZBX_PROBLEMHOUSEKEEPINGFREQUENCY=60
ZBX_CACHESIZE=1024M
ZBX_CACHEUPDATEFREQUENCY=10
ZBX_STARTDBSYNCERS=50
ZBX_HISTORYCACHESIZE=1024M
ZBX_HISTORYINDEXCACHESIZE=1024M
ZBX_HISTORYSTORAGEDATEINDEX=0
ZBX_TRENDCACHESIZE=512M
ZBX_TRENDFUNCTIONCACHESIZE=512M
ZBX_VALUECACHESIZE=1024M
ZBX_TRAPPERTIMEOUT=300
ZBX_UNREACHABLEPERIOD=45
ZBX_UNAVAILABLEDELAY=60
ZBX_UNREACHABLEDELAY=15
ZBX_LOGSLOWQUERIES=3000
ZBX_STARTPROXYPOLLERS=50
ZBX_PROXYCONFIGFREQUENCY=60
ZBX_PROXYDATAFREQUENCY=120
ZBX_STARTREPORTWRITERS=5

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
The issue is not related to docker images. It is related mostly to Zabbix product. Please use our forum https://www.zabbix.com/forum/ or / and https://support.zabbix.com/ if it is a bug in the product.
