### ISSUE TITLE
ZBX_SERVER_HOST default value is't zabbix-server

### ISSUE THREAD

**Issue by stallion2303** [zabbix/zabbix-docker#948]
Using image zabbix-web-nginx-pgsql:ol-6.0-latest
If I don't set the ZBX_SERVER_HOST environment variable, then an error occurs when execute the script:

```
Cannot execute script.
Connection to Zabbix server "localhost" failed. Possible reasons:
1. Incorrect server IP/DNS in the "zabbix.conf.php";
2. Incorrect DNS server configuration.
Cannot assign requested address
```

I didn't find the default setting [here](https://github.com/zabbix/zabbix-docker/blob/6.0/Dockerfiles/web-nginx-pgsql/ol/docker-entrypoint.sh)

**Comment by dotneft** [comment]
if it is not specified Zabbix 6.0 uses DB data to determine Zabbix server location.

**Comment by kkrkarthik** [comment]
Its available in .env_web file 
ZBX_SERVER_HOST=zabbix-server

**Comment by stallion2303** [comment]
> if it is not specified Zabbix 6.0 uses DB data to determine Zabbix server location.

where in the DB data to change localhost to zabbix-server?

**Comment by dotneft** [comment]
I'm sorry, if the installation is standalone, you need specify ZBX_SERVER_HOST for web container.
