### ISSUE TITLE
IgnoreURLCertErrors option not configurable via env variables for zabbix-web-service images

### ISSUE THREAD

**Issue by sa-ChristianAnton** [zabbix/zabbix-docker#949]
Please, add the option to supply a ZBX_IGNOREURLCERTERRORS env variable to the zabbix-web-service images to control the configuration file IgnoreURLCertErrors option.

**Comment by dotneft** [comment]
Thank you! Added!

**Comment by sa-ChristianAnton** [comment]
Quickest fix ever! Thanks.
