### ISSUE TITLE
Zabbix-Agent2 - Monitoring Docker

### ISSUE THREAD

**Issue by rafaelpmagalhaes** [zabbix/zabbix-docker#950]
##### SUMMARY
I can't monitor docker using Zabbix Agent2 in container, as I didn't find a way to grant permission to the Zabbix user from the container to the host's docker.sock even running the container in privileged mode.

##### OS / ENVIRONMENT / Used docker-compose files
docker run --name zabbix-agent2 --net=zabbix -p 10050:10050 -v /var/run:/var/run:rw -e ZBX_HOSTNAME=Monitoring -e ZBX_SERVER_HOST=zabbix-proxy-local -e ZBX_METADATA=Linux,Docker -e ZBX_HOSTNAMEITEM=system.hostname -e ZBX_TIMEOUT=30 -e ZBX_REFRESHACTIVECHECKS=60 --privileged -d registry.agilepromoter.com/involves-zabbix-agent2:6.0.3

##### STEPS TO REPRODUCE
I performed the following test:
I accessed the container: docker exec -ti zabbix-agent2 bash
I performed collection test: zabbix_agent2 -t docker.info
I got the following output: docker.info [m|ZBX_NOTSUPPORTED] [Cannot fetch data: Get "http://1.28/info": dial unix /var/run/docker.sock: connect: no such file or directory.]

**Comment by dotneft** [comment]
Please check #917
