### ISSUE TITLE
Change SNMP community dynamically in snmptraps image

### ISSUE THREAD

**Issue by fernandolcx** [zabbix/zabbix-docker#955]
Currently, the SNMP community in `snmptrapd.conf` is hardcoded to `public`:

https://github.com/zabbix/zabbix-docker/blob/428d423846a534b7f501d8cfdbfaecadb20a8eac/Dockerfiles/snmptraps/ubuntu/conf/etc/snmp/snmptrapd.conf#L12

There is any possibility to make this as a environment value, so we can dynamically change it?

**Comment by dotneft** [comment]
You can mount snmptrapd.conf and modify it as you want. It has a lot of options which is impossible to list as variables.
