### ISSUE TITLE
6.0-ubuntu-latest PHP 8.1 Dashboard Errors

### ISSUE THREAD

**Issue by pharbison** [zabbix/zabbix-docker#958]
##### SUMMARY
In the image zabbix/zabbix-web-nginx-mysql tagged with 6.0-ubuntu-latest the PHP version seems to have been updated to 8.1. This has caused the below error in logs and I just get a blank white page. 

```
2022/05/12 08:55:28 [error] 21#21: *19 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "CMessageHelper" not found in /usr/share/zabbix/include/func.inc.php:2039
Stack trace:
#0 /usr/share/zabbix/include/func.inc.php(2298): error()
#1 /usr/share/zabbix/include/classes/core/CAutoloader.php(77): zbx_err_handler()
#2 /usr/share/zabbix/include/classes/core/CAutoloader.php(77): require('...')
#3 /usr/share/zabbix/include/func.inc.php(1924): CAutoloader->loadClass()
#4 /usr/share/zabbix/include/classes/html/widget/CWidget.php(137): get_prepared_messages()
#5 /usr/share/zabbix/include/classes/html/widget/CWidget.php(113): CWidget->toString()
#6 /usr/share/zabbix/app/views/monitoring.dashboard.view.php(256): CWidget->show()
#7 /usr/share/zabbix/include/classes/mvc/CView.php(136): include('...')
#8 /usr/share/zabbix/include/classes/core/ZBase.php(603): CView->getOutput()
#9 /usr/share/zabbix/include/classes/core/ZBase.php(529): ZBase->processResponseFinal()
#10 /usr/share/zabbix/include/classes/core/ZBase.php(210): ZBase->processRequest()
#" while reading response header from upstream, client: 10.252.0.6, server: zabbix, request: "GET /zabbix.php?action=dashboard.view HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "***********"
```

For the time being I have rolled back to the previously working image that is running PHP 7.4. This installation is in production, so I'm limited on what I can do as far as troubleshooting the issue. I didn't see this issue reported anywhere and the image is only 19 hours old as I'm posting this, so I thought it best to open the case myself in case someone else runs into this issue. 

##### OS / ENVIRONMENT / Used docker-compose files
Host OS: Alpine Linux v3.15
Docker: 20.10.14
Container: zabbix/zabbix-web-nginx-mysql:6.0-ubuntu-latest
Compose Excerpt:
   zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:6.0-ubuntu-latest
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_USER=*******
      - MYSQL_PASSWORD=********
      - DB_SERVER_HOST=zabbix-db
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=America/Chicago
    restart: unless-stopped
    depends_on:
      - zabbix-server

Let me know if you need any further info. 

##### CONFIGURATION
No additional configuration changes have been made. 

##### STEPS TO REPRODUCE
Run the latest version of the above mentioned image with a working Zabbix Server and MySQL containers. 

##### EXPECTED RESULTS
Dashboard should display without issue. 

##### ACTUAL RESULTS
Getting blank white page.

**Comment by dotneft** [comment]
Will be fixed soon. Do not use latest, use 6.0.4 tag

**Comment by pharbison** [comment]
Also if it helps the broken image digest is b279c8f1ccae47aa2e2bfa10614bec04e91793dacca11f3c7c5a9968d6ad98c0 and the last working image digest I have is 30a2d9f7d2543b28916d7cf450eea798d55782dcdb558af8da2595c1e32e522d.

**Comment by pharbison** [comment]
Thanks for the update. I'll update my docker-compose file!

**Comment by rostislav-palivoda** [comment]
You can follow https://support.zabbix.com/browse/ZBXNEXT-7080
