### ISSUE TITLE
[FATAL tini (7)] exec /usr/bin/docker-entrypoint.sh failed: No such file or directory

### ISSUE THREAD

**Issue by tonyemiliano** [zabbix/zabbix-docker#960]
##### SUMMARY
I'm trying to build an image of the agent by adding the python3 installation inside the dockerfile. Apparently nothing that changes the structure of the dockerfile. However, when completing the image build and trying to run it, the following error is displayed:

> [FATAL tini (7)] exec /usr/bin/docker-entrypoint.sh failed: No such file or directory

##### OS / ENVIRONMENT / Used docker-compose files
I'm using windows to build the image. This one is building without any problems. It seems that the error happens when running. My idea is to create this image and add it to the same namespace as my current zabbix, to run python scripts and make API queries through python. So I came up with this idea of creating an image of the agent with python inside.

I'm using ubuntu and centos dockerfiles. Both are having the same problem. And when changing these files, I simply added the following:

Centos

```
RUN set -eux && \
    REPOLIST="baseos,appstream,epel" && \
    INSTALL_PKGS="bash \
            tini \
            tzdata \
            iputils \
            pcre2 \
            libcurl \
            openssl-libs \
            **python3** \
            zlib" && \
```

Ubuntu

```
RUN apt-get -y install software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get -y install python3.8

```

##### STEPS TO REPRODUCE
Command to build: `docker build -t zabbix-agent-python:centos-6.0.0 .` 
Build went through with no problems.

Commando to run and test the image:
`docker exec --name zabbix-python -it zabbix-agent-python:centos-6.0.0 bash` 
or 
`docker run --name some-zabbix-agent -it -e ZBX_HOSTNAME="some-hostname" -e ZBX_SERVER_HOST="some-zabbix-server" zabbix-agent-python:centos-6.0.0`

##### EXPECTED RESULTS
I just need an image of the agent running with python3 where I can map a "scripts" volume for example and run python scripts to the internet

##### ACTUAL RESULTS
Error
> [FATAL tini (7)] exec /usr/bin/docker-entrypoint.sh failed: No such file or directory
when trying to run the image after built.

**Comment by dotneft** [comment]
Try this one:
```
FROM zabbix/zabbix-agent:centos-6.0-latest

USER root

RUN set -eux && \
    REPOLIST="baseos,appstream,epel" && \
    INSTALL_PKGS="python3" && \
    dnf -y install \
            --disablerepo "*" \
            --enablerepo "${REPOLIST}" \
            --setopt=tsflags=nodocs \
            --setopt=install_weak_deps=False \
            --best \
        ${INSTALL_PKGS} && \
    dnf -y clean all && \
    rm -rf /var/cache/yum /var/lib/yum/yumdb/* /usr/lib/udev/hwdb.d/* && \
    rm -rf /var/cache/dnf /etc/udev/hwdb.bin /root/.pki

USER 1997
```

**Comment by tonyemiliano** [comment]
Thank you very much. I hadn't thought so. The image built correctly.
