### ISSUE TITLE
The access status code is 502.

### ISSUE THREAD

**Issue by jxsdegit** [zabbix/zabbix-docker#961]
hello ,I started ZABBIX，But the visit doesn't work
![image](https://user-images.githubusercontent.com/48508163/169778093-d6099960-4986-4923-98ff-914cd230991b.png)
The access status code is 502.

**Comment by dotneft** [comment]
I recommend you check Zabbix frontend container logs.

**Comment by jxsdegit** [comment]
![image](https://user-images.githubusercontent.com/48508163/169929456-89a6308c-d71a-43cd-969f-b09803788935.png)
hello，This log looks normal。

**Comment by jxsdegit** [comment]
ok,I found the problem
