### ISSUE TITLE
WSL2 + Windows + DockerDesktop generate a Right problems when mounting Mysql or PGSQL

### ISSUE THREAD

**Issue by rasata** [zabbix/zabbix-docker#963]
##### SUMMARY

When trying to launch one of the zabbix docker-compose file, 
It ends up with an error like this :
```
mysql-server_1             | mysqld: Cannot change permissions of the file 'private_key.pem' (OS errno 1 - Operation not permitted)
mysql-server_1             | 2022-05-23T21:07:05.644327Z 0 [ERROR] [MY-010295] [Server] Could not set file permission for private_key.pem
mysql-server_1             | 2022-05-23T21:07:05.644565Z 0 [ERROR] [MY-010119] [Server] Aborting
mysql-server_1             | 2022-05-23T21:07:07.142969Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.29)  MySQL Community Server - GPL.
```

##### OS / ENVIRONMENT / Used docker-compose files

- Windows 10 
- wsl2 
-- ubuntu 20.04
- Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
- docker-compose version 1.29.2, build 5becea4c
-- docker-py version: 5.0.0
-- CPython version: 3.7.10
-- OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

##### CONFIGURATION

no specific .env configuration 

##### STEPS TO REPRODUCE

launch 

```bash
 sudo docker-compose -f ./docker-compose_v3_ubuntu_mysql_local.yaml up
```

##### EXPECTED RESULTS

The complete zabbix should be running 

##### ACTUAL RESULTS

There is some rights issues on the volumes as Postgresql & Mysql have included a script that modify the volumes rights. 
To correct this, one should  prefix the volume name with ${PWD} but then it is not working on Linux host.

**Replace for instance** : 
   `./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro"`

**With**:
` "${PWD}/zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro"`

**Comment by dotneft** [comment]
If it does not work on Linux host then, in this case we have to provide all compose files for Windows and Linux. I suppose it is too much, we already have too much compose files (

**Comment by rasata** [comment]
Yes you are right there is many compose files, it seems to me that there is no easy way to solve it right now, maybe the easier way would be to mention some warning about the compatibility on wsl 2 + win10 + Docker Desktop for the docker-compose file.
So that this issue can be prioritize later on the road map, and then we may find a good solution
