### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by bartlebi** [zabbix/zabbix-docker#964]
##### SUMMARY

Cannot install zabbix on docker. 
Steps:
Installed mysql-server:5-7 (latest)
After installing created zabbix container, linked mysql. After running database was created but before runnig zabbix i see an error:

```
Unsupported DB! MySQL version is 50709 which is smaller than minimum of 50728
Error! Current MySQL database server version is too old (5.07.09)
Must be a least 5.07.28

```
But mysql -V returns: 
```
[root@mysql-server /]# mysql -V
mysql  Ver 14.14 Distrib 5.7.9, for Linux (x86_64) using  EditLine wrapper
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by bartlebi** [comment]
I think version 5.7.9 (90?) is grater than 5.7.28
Am i wrong?

**Comment by dotneft** [comment]
5.7.9 is not greater than 5.7.28.
