### ISSUE TITLE
fix docker-entrypoint.sh for use with postgresql 14

### ISSUE THREAD

**Issue by KowMangler** [zabbix/zabbix-docker#965]
##### SUMMARY

Postgresql Zabbix Server container cannot connect to SSL enabled postgres backend due to incorrect env var `PGSSLMODE=required`.

##### OS / ENVIRONMENT / Used docker-compose files

Deployed in Kubernetes but the problem is in the `docker-entrypoint.sh` script. 

##### STEPS TO REPRODUCE

Enable SSL only connect to pgsql (or via pgbouncer) without requiring cert verification.

```yaml

```

##### EXPECTED RESULTS

Expected zabbix-server to start

##### ACTUAL RESULTS

The entrypoint script stays in the loop forever:
```
    while true :
    do
        psql --host ${DB_SERVER_HOST} --port ${DB_SERVER_PORT} --username ${DB_SERVER_ROOT_USER} --list --quiet 1>/dev/null 2>&1 && break
        psql --host ${DB_SERVER_HOST} --port ${DB_SERVER_PORT} --username ${DB_SERVER_ROOT_USER} --list --dbname ${DB_SERVER_DBNAME} --quiet 1>/dev/null 2>&1 && break

        echo "**** PostgreSQL server is not available. Waiting $WAIT_TIMEOUT seconds..."
        sleep $WAIT_TIMEOUT
    done
```

```paste below
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
```

This is because all errors from usage of the `psql` client are black-holed. If we more appropriately bubble up underlying error messages you see the offending issue `psql: error: invalid sslmode value: "required"` . To verify this I changed the entrypoint script for every occurrence of the stanza:
```
    if [ -n "${ZBX_DBTLSCONNECT}" ]; then
        export PGSSLMODE=${ZBX_DBTLSCONNECT//_/-}
        export PGSSLROOTCERT=${ZBX_DBTLSCAFILE}
        export PGSSLCERT=${ZBX_DBTLSCERTFILE}
        export PGSSLKEY=${ZBX_DBTLSKEYFILE}
    fi
```

to the following:
```
    if [ -n "${ZBX_DBTLSCONNECT}" ]; then
        if [ "${ZBX_DBTLSCONNECT}" == "required" ]; then
            export PGSSLMODE="require"
        else
            export PGSSLMODE=${ZBX_DBTLSCONNECT//_/-}
        fi
        export PGSSLROOTCERT=${ZBX_DBTLSCAFILE}
        export PGSSLCERT=${ZBX_DBTLSCERTFILE}
        export PGSSLKEY=${ZBX_DBTLSKEYFILE}
    fi
```

This allowed the zabbix server to configure the database and startup as expected

**Comment by KowMangler** [comment]
I found the appropriate syntax for postgresql env var settings here:
https://www.postgresql.org/docs/14/libpq-connect.html#LIBPQ-CONNECT-SSLMODE

**Comment by dotneft** [comment]
Fixed! Thank you!
