### ISSUE TITLE
ZBX_SERVER_PORT env variable ignored on proxy images

### ISSUE THREAD

**Issue by jepke** [zabbix/zabbix-docker#966]
##### SUMMARY
zabbix/zabbix-proxy-sqlite3 ignores ZBX_SERVER_PORT variable possibly other images too

##### OS / ENVIRONMENT / Used docker-compose files
Currently testing on windows docker desktop.

##### CONFIGURATION
docker run --name TEST_ZABBIX_PROXY -e ZBX_SERVER_PORT=4433 -e ZBX_HOSTNAME=test_proxy -e ZBX_SERVER_HOST=proxy.zabbix.com.example -d zabbix/zabbix-proxy-sqlite3

##### STEPS TO REPRODUCE
See above docker run command.

During container startup this line states it should be added.
** Updating '/etc/zabbix/zabbix_proxy.conf' parameter "ServerPort": '4433'...added

##### EXPECTED RESULTS
Connecting on port 4433

##### ACTUAL RESULTS
Its using the default port and not my specified port from the env var.
   `150:20220526:235453.977 Unable to connect to [proxy.zabbix.com.example]:10051 [cannot resolve [proxy.zabbix.com.example]]`

**Comment by fpaternot** [comment]
Reproduced on linux too, with latest and ubuntu-6.0.[01234].

ubuntu-5.0.22, ubuntu-5.4.12 does work as expected.

Command i used to simplify my testing:

```sh
for VERSION in 5.0.22 5.4.12 6.0.0 6.0.1 6.0.2 6.0.3 6.0.4; do \
docker run -it --rm -e ZBX_SERVER_PORT=4433 -e ZBX_HOSTNAME=test_proxy \
-e ZBX_SERVER_HOST=proxy.zabbix.com.example zabbix/zabbix-proxy-sqlite3:ubuntu-${VERSION}
done
```

**Comment by dotneft** [comment]
ServerPort parameter is deprecated please specify port in ZBX_SERVER_HOST env separated by ':' instead.

**Comment by jepke** [comment]
Docs might need an update on that if its deprecated.

**Comment by dotneft** [comment]
thank yoU! Updated already )

**Comment by fpaternot** [comment]
Some mention on zabbix documentation as well:

https://www.zabbix.com/documentation/current/en/manual/installation/upgrade_notes_600
https://www.zabbix.com/rn/rn6.0.0

**Comment by dotneft** [comment]
will be done soon: https://support.zabbix.com/browse/ZBX-20989

**Comment by fpaternot** [comment]
Great! But breaking changes should consider it from the start. Consider adding this step before releasing images.
