### ISSUE TITLE
Use 'mysql:8.0-oracle' tag for docker-compose files

### ISSUE THREAD

**Issue by kernbug** [zabbix/zabbix-docker#968]
mysql:8.0-oracle tag provides both amd64 and arm64: https://hub.docker.com/_/mysql?tab=description.

Also used images are not from MySQL itself: https://hub.docker.com/r/mysql/mysql-server,
and provided as part of: https://docs.docker.com/docker-hub/official_images/.

Mysql compose files are not able to start on ARM64 like Graviton 2/3, Ampere Altra, Apple M1 until image changed to MariaDB or something like arm64v8 or mysql/mysql-server/mysql.

**Comment by dotneft** [comment]
fixed
