### ISSUE TITLE
Su root Password

### ISSUE THREAD

**Issue by lgonzale44** [zabbix/zabbix-docker#973]
done
 Done
 Done

##### SUMMARY
Unable to edit files inside docker. there is not Vi editor. is the a way to install Vi or Nano? for that i need root Password (su root before install)

```

**Comment by dotneft** [comment]
why do you need editing something inside container?

**Comment by lgonzale44** [comment]
yes. for example: I want to monitor esxi and need to make changes in a zabbix config file under de container.

**Comment by dotneft** [comment]
in this case you need to use env variables. never do not touch zabbix configuration file manually.

**Comment by lgonzale44** [comment]
its true...just want to know if exists another way. Thnks

**Comment by dotneft** [comment]
no way. if you recreate container, your changes will be lost.
