### ISSUE TITLE
Service -> Service menu Error.

### ISSUE THREAD

**Issue by 19940308cai** [zabbix/zabbix-docker#977]
hello , frend! 
After I try to add an IT service, the service page prompts 500 errors. The following is the error log and error page.

Error Detail:
![image](https://user-images.githubusercontent.com/20193598/175540316-0f736604-fc32-4aad-aef7-a7f9b1209ffb.png)
![image](https://user-images.githubusercontent.com/20193598/175540501-dcc044bf-24ca-40d4-9901-95624779a8b1.png)

**Comment by dotneft** [comment]
hello! what image do you use?
