### ISSUE TITLE
zabbix-web-nginx-pgsql:latest, zabbix-agent:latest ZBX host config issues

### ISSUE THREAD

**Issue by random-peon-00** [zabbix/zabbix-docker#978]
##### SUMMARY

1. default install of official Zabbix images implements a host for ZBX pointed to 127.0.0.1, needing to be updated to point zabbix-agent (minor)
2. zabbix-agent:latest must also be edited to allow the IP address of the server (ZBX_SERVER_HOST). However, it will not accept  wildcard syntax such as 172.0.0.0/8. This causes a Docker start failure. The inability to specify a fixed IP in the Docker container configuration necessitates a wildcard / network IP range to be configured (or another solution for zabbix-agent to recognize zabbix-server is that ip address... which is does not).

This thread has the most helpful information regarding the difficulty with linking the official zabbix-server and zabbix-agent communication. It happens on different base OS and has for years:

[Zabbix server shows as problem in dashboard](https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/366318-zabbix-servers-on-docker-keep-showing-in-problem-in-dashboard-is-it-normal)

##### OS / ENVIRONMENT / Used docker-compose files

Synology DSM: 7.1-42661 Update 1
Docker: 20.10.3-1306

Docker Registry:
zabbix/zabbix-agent:latest
zabbix/zabbix-server-pgsql:latest
zabbix/zabbix-web-nginx-pgsql:latest
postgres:latest

##### STEPS TO REPRODUCE

1. Bare install on a dedicated Docker Zabbix network, using defaults
2. Zabbix GUI, fix Host for default added Zabbix server to use DNS zabbix-agent instead of IP 127.0.0.1 (which only points to itself and does not contain a zabbix agent in the zabbix server docker) ![Zabbix server DNS](https://user-images.githubusercontent.com/70278581/175564760-6920c55e-8c97-4929-bd03-5aef4152297c.png)
3. Docker zabbix-agent add environment variable ZBX_SERVER_HOST to allow zabbix-server docker to communicate
3.1 Attempt to set ZBX_SERVER_HOST to: 172.0.0.0/8 results in failure to start container 
3.2 Only solution to work is a singular IP address, ex: "zabbix-server,172.19.0.3"
![Zabbix-agent-ZBX_SERVER_HOST_valid](https://user-images.githubusercontent.com/70278581/175565174-fde5ef15-ee67-494a-8076-7e145cb5e63f.png)

```yaml

```

##### EXPECTED RESULTS

The ability to either specify a wildcard network or a static IP for zabbix docker containers loaded from Docker registry.

##### ACTUAL RESULTS

Before addressing zabbix-agent and zabbix-server issue:
75:20220624:134457.122 failed to accept an incoming connection: connecting from "172.19.03" rejected, allowed hosts: "zabbix-server" appeared repeatedly in terminal.
![Zabbix-agent-zabbix-server](https://user-images.githubusercontent.com/70278581/175564848-052496ca-7fa9-4074-819b-f06ecf2f3216.png)

Attempting to use wildcard network, fails to start container.

```paste below

```

**Comment by dotneft** [comment]
You can specify ZBX_PASSIVESERVERS="172.0.0.0/8" and / or ZBX_ACTIVE_ALLOW="false".

**Comment by random-peon-00** [comment]
Specifying 172.0.0.0/8 results in the container failing to start.

**Comment by dotneft** [comment]
please show logs.

**Comment by random-peon-00** [comment]
Ah, a different environment variable (ZBX_PASSIVESERVERS). I do not recall
seeing that one listed on the page. I gave it a try and it seems to work
fine. I do wish we could specify static IPs (more secure, targeted
solution).

[image: image.png]

Thank you Alexey! I see years of posts about the default Zabbix server host
not working. Most threads seemed to have abandoned it. I am glad this is
working.

**Comment by dotneft** [comment]
Great that it helped you! But actually it is documented: https://github.com/zabbix/zabbix-docker/tree/6.0/Dockerfiles/agent/alpine#zbx_passiveservers
