### ISSUE TITLE
Docker zabbix/zabbix-server-pgsql and zabbix/zabbix-web-nginx-pgsql - Traceroute and Ping do not work

### ISSUE THREAD

**Issue by random-peon-00** [zabbix/zabbix-docker#979]
##### SUMMARY

Latest zabbix/zabbix-server-pgsql and zabbix/zabbix-web-nginx-pgsql giving errors when trying Traceroute on a host from the GUI. Also have ICMP errors for template items (Zabbix released template D-Link DES_DGS Switch SNMP).

##### OS / ENVIRONMENT / Used docker-compose files

Latest zabbix/zabbix-server-pgsql and zabbix/zabbix-web-nginx-pgsql Docker from repository

##### STEPS TO REPRODUCE

From WebGUI:
Click Host, select Traceroute
Get this message

![image](https://user-images.githubusercontent.com/70278581/176689928-f05ae057-886a-46da-9181-e7f0113086ec.png)

ICMP errors
Zabbix template D-Link DES_DGS Switch SNMP (no changes).
ICMP items fail because of permission

![image](https://user-images.githubusercontent.com/70278581/176690202-ec212f10-e53e-454c-9102-235c2d71691a.png)

```yaml

```

##### EXPECTED RESULTS

Tools will function

##### ACTUAL RESULTS

```paste below

### Traceroute
Traceroute
[Details ](javascript:void(0))Cannot execute script.
traceroute: socket(AF_INET,3,1): Operation not permitted

Ok

### Template Pings
/usr/sbin/fping: can't create socket (must run as root?)

```

**Comment by dotneft** [comment]
what image do you use? how do you start container?

**Comment by random-peon-00** [comment]
Hello,

These are the latest Zabbix docker official images from the registry using
the default configuration. Container is created with Docker and started.

https://registry.hub.docker.com/r/zabbix/zabbix-server-pgsql/

https://registry.hub.docker.com/r/zabbix/zabbix-web-nginx-pgsql/

https://registry.hub.docker.com/r/zabbix/zabbix-agent/

[image: image.png]

**Comment by dotneft** [comment]
I mean, what tag?

**Comment by random-peon-00** [comment]
-latest , per original report

**Comment by dotneft** [comment]
I can not reproduce the issue. What environment do you have? Any specific configuration options?

**Comment by random-peon-00** [comment]
All defaults. I am not sure why these errors are occurring. This docker on
Synology. Image is grabbed from the registry and started.


[image: image.png]

[image: image.png]

[image: image.png]

**Comment by dotneft** [comment]
I recommend you compare cgroups, selinux... and other methods on synology with working instance.

**Comment by random-peon-00** [comment]
What does that mean?

**Comment by dotneft** [comment]
I think your docker / podman / kubernetes / openshift has additional restrictions regarding sys capabilities, so that can affect to ping: https://docs.docker.com/engine/security/
