### ISSUE TITLE
zabbix-web-nginx-mysql requires IPv6 enabled?

### ISSUE THREAD

**Issue by Codelica** [zabbix/zabbix-docker#980]
##### SUMMARY

When bringing up a compose stack based on docker-compose_v3_ubuntu_mysql_latest.yaml using zabbix-web-nginx-mysql, results in the container failing with messages like:

```
2022-06-30 13:04:08,341 INFO spawned: 'nginx' with pid 32
2022-06-30 13:04:08,341 INFO spawned: 'nginx' with pid 32
2022/06/30 13:04:08 [emerg] 32#32: socket() [::]:8080 failed (97: Address family not supported by protocol)
2022/06/30 13:04:08 [emerg] 32#32: socket() [::]:8080 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:8080 failed (97: Address family not supported by protocol)
2022-06-30 13:04:09,354 INFO exited: nginx (exit status 1; not expected)
2022-06-30 13:04:09,354 INFO exited: nginx (exit status 1; not expected)
2022-06-30 13:04:12,359 INFO spawned: 'nginx' with pid 33
2022-06-30 13:04:12,359 INFO spawned: 'nginx' with pid 33
2022/06/30 13:04:12 [emerg] 33#33: socket() [::]:8080 failed (97: Address family not supported by protocol)
2022/06/30 13:04:12 [emerg] 33#33: socket() [::]:8080 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:8080 failed (97: Address family not supported by protocol)
2022-06-30 13:04:12,370 INFO exited: nginx (exit status 1; not expected)
2022-06-30 13:04:12,370 INFO exited: nginx (exit status 1; not expected)
2022-06-30 13:04:12,370 INFO gave up: nginx entered FATAL state, too many start retries too quickly
2022-06-30 13:04:12,370 INFO gave up: nginx entered FATAL state, too many start retries too quickly
```

Looking at the NGINX config I see it's trying to listen on IPv4 and iPv6:

/etc/zabbix/nginx.conf:
```
server {
    listen 8080;
    listen [::]:8080;
...
```

/etc/zabbix/nginx_ssl.conf:
```
server {
    listen 8443 ssl http2;
    listen [::]:8443 ssl http2;
...
```

Yet the network config in the compose file seems to disable IPv6:
```
networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
...
```

and my host machine definitely has it disabled.

Using the Apache container works fine, but I'd prefer to use NGINX.

##### OS / ENVIRONMENT / Used docker-compose files

Ubuntu 22
Docker version 20.10.17, build 100c701
IPv6 disabled

##### STEPS TO REPRODUCE

Not sure if it requires IPv6 disabled on the host or not, but I think running docker-compose_v3_ubuntu_mysql_latest.yaml using zabbix-web-nginx-mysql should expose this since it appears to have ipv6 on the networks disabled as well. 

```yaml

```

##### EXPECTED RESULTS

zabbix-web-nginx-mysql should run regardless of iPv6 being enabled

##### ACTUAL RESULTS

zabbix-web-nginx-mysql doesn't start properly without IPv6 enabled.

**Comment by ReaHe** [comment]
I had this problem as well, I had to copy the config files from the github and use volume mounts over the original configs. I would prefer a entrypoint ENV variable to turn it off/not include it in the config files when they're copied over to the nginx etc folder. Currently my ipv6 is disabled via Grub for awareness.

**Comment by Codelica** [comment]
Yep, I'm actually doing the same :)  Obviously just not ideal if other changes come though.  Hopefully a better option will come.  👍

**Comment by dotneft** [comment]
Could you check please, do you have /proc/net/if_inet6 file inside of web container?

**Comment by ReaHe** [comment]
I do not have that file inside of my web container, I also have ipv6 disabled via grub and via the "driver_opts" for the docker-compose file. /proc/net/if* comes up with nothing on the host and docker container.

**Comment by dotneft** [comment]
Thank you! I think I fixed it, please wait next minor releases.

**Comment by dotneft** [comment]
Fixed in latest images.
