### ISSUE TITLE
Add UserParameter to zabbix_agent(2) config variable 

### ISSUE THREAD

**Issue by ghost** [zabbix/zabbix-docker#982]
It will be great if we can use UserParameter with the zabbix agent.
Right now it is not available even if it is mentioned in the values like ZBX_USERPARAMETER.

Is it possible to send the script with the HELM chart which will be triggered by ZBX_USERPARAMETER option? 

Life case:
we need to monitor kubernetes certificates lifetime from /etc/kubernetes/pki/*, how we can perform this with the container, and use the following chart https://git.zabbix.com/projects/ZT/repos/kubernetes-helm/browse?at=refs%2Fheads%2Frelease%2F6.0?

**Comment by dotneft** [comment]
As it is possible to have multiple userparameters, it is quite difficult to introduce such env variable. Please mount volume with userparams.
