### ISSUE TITLE
Installing curl in alpine docker container

### ISSUE THREAD

**Issue by bikeusaland** [zabbix/zabbix-docker#983]
I realize this is not a zabbix specific issue, but since many scripts use curl, I was wondering if there was a way to automatically add curl (theoretically other apps) as part of the alpine server container just after startup?  I am trying to avoid building a new image with docker.

Doing the following manually within the container works, but obviously does not scale and avoiding manual steps is the point.

apk update
apk add curl

Unfortunately, it does not seem that the Alpine/curl is being kept up to date, so that is not an option.

**Comment by dotneft** [comment]
why do you need curl in Zabbix server image?

**Comment by bikeusaland** [comment]
I was thinking of using custom alert scripts that having curl would be easier to do posts.

This of course is very old, but was the approach I was thinking:
https://github.com/ericoc/zabbix-slack-alertscript

I am sure I can make the below work, but having curl would make it infinitely flexible.

https://www.zabbix.com/documentation/current/en/manual/config/notifications/media/webhook

Greg

**Comment by dotneft** [comment]
Zabbix has HTTP agent item and HTTP requests in webhooks, so I do not see any reason to add curl. Maybe i miss something?

**Comment by a1ad** [comment]
I want to add nmap for administration script to work.

**Comment by dotneft** [comment]
nmap is not required for Zabbix default installation, but traceroute is required. Will add traceroute.

**Comment by dotneft** [comment]
sorry, nmap is also required :-)

**Comment by a1ad** [comment]
:-) Thanks!

**Comment by a1ad** [comment]
> sorry, nmap is also required :-)

One more thing really important for my use case is "mosquitto_pub" I would like to publish MQTT messages as media type like described here: https://blog.zabbix.com/let-me-subscribe-zabbix-masters-iot-topics/12710/  at the bottom of the page.

It is the 'mosquitto-clients' package.

I know it's not Zabbix default, so I can understand if you do not add MQTT support.

Edit: 
Just for reference, I created a Docker file and build a custom image like this:

Dockerfile:
```
FROM zabbix/zabbix-server-mysql:alpine-6.2-latest
USER root
RUN set -eux && \
    INSTALL_PKGS="mosquitto-clients \
            nmap \
            tcptraceroute" && \
    apk add \
            --no-cache \
            --clean-protected \
        ${INSTALL_PKGS} && \
    rm -rf /var/cache/apk/*
```

Changed the compose file:

```
zabbix-server:
  build:
   context: LOCATION TO DOCKERFILE FOLDER
  image: A1AD/zabbix-server-mysql-custom:alpine-6.2-latest
```

No idea if this is the right way to do it, it works for me tho.

**Comment by dotneft** [comment]
Added nmap and traceroute to server / proxy images. Curl and mosquitto packages are not required for Zabbix default installation.
