### ISSUE TITLE
Add additional CFLAGS/CXXFLAGS & LDFLAGS

### ISSUE THREAD

**Issue by kernbug** [zabbix/zabbix-docker#988]
Suggested options (https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc):
-D_FORTIFY_SOURCE=2
-fexceptions
-O2
-Wl,-z,defs
-pipe

Also nice to have, since official packages are built with it (DEV-1659) (compile + linker):
-flto

**Comment by dotneft** [comment]
done
