### ISSUE TITLE
zabbix-docker_db_data_mysql_1 --> Exited (0)

### ISSUE THREAD

**Issue by zakkymuhammad** [zabbix/zabbix-docker#989]
##### SUMMARY

When building **docker-compose_v3_ubuntu_mysql_latest.yaml using docker compose**, all is passed. But, when check on the running container list **zabbix-docker_db_data_mysql_1** (from busybox image) is not run with status _**Exited (0)**_.

##### OS / ENVIRONMENT / Used docker-compose files

Docker version: 20.10.17, build 100c701
Docker-compose version: 1.29.2, build 5becea4c

Docker desktop MacOS version: 4.10.1

##### STEPS TO REPRODUCE

```
docker-compose -f docker-compose_v3_ubuntu_mysql_latest.yaml using docker compose up -d
```

##### ACTUAL RESULTS

```
Exited (0) 11 minutes ago 
```

**Comment by dotneft** [comment]
it is normal behaviour for db_data container.
