### ISSUE TITLE
Docker build failed，zabbix-build-mysql pull failed

### ISSUE THREAD

**Issue by qx517971976** [zabbix/zabbix-docker#993]
**Sorry, my English is not good，Can't I download zabbix-build-mysql anonymously？**

**Failed to run build.sh**
 _=> ERROR [internal] load metadata for docker.io/library/zabbix-build-mysql:centos-6.2.0                                                                                         39.7s
 => [internal] load metadata for quay.io/centos/centos:stream8                                                                                                                      1.0s
 => [auth] library/zabbix-build-mysql:pull token for registry-1.docker.io                                                                                                           0.0s
------
 > [internal] load metadata for docker.io/library/zabbix-build-mysql:centos-6.2.0:
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to do request: Head "https://registry.docker-cn.com/v2/library/zabbix-build-mysql/manifests/centos-6.2.0?ns=docker.io": dial tcp 106.14.52.175:443: connect: connection refused_

**Running docker build also failed**
_docker build -t zabbix-server-mysql:centos-latest --build-arg VCS_REF=6.2.0 --build-arg BUILD_DATE=2022-07-27T09:29:33Z -f Dockerfile .
Step 4/24 : FROM ${BUILD_BASE_IMAGE} as builder
pull access denied for zabbix-build-mysql, repository does not exist or may require 'docker login': denied: requested access to the resource is denied_

**Comment by dotneft** [comment]
Please check #990.

**Comment by qx517971976** [comment]
> Please check #990.

thanks for your answer,I try to perform the following steps:
1) docker-compose -f docker-compose_v3_ubuntu_mysql_local.yaml build zabbix-build-base
2) docker-compose -f docker-compose_v3_ubuntu_mysql_local.yaml build zabbix-build-mysql
3) docker-compose -f docker-compose_v3_ubuntu_mysql_local.yaml up -d

Step 1:successful，but Step 2 failed.
I can't access ZBX_SOURCES due to network problems.So I cloned this project into my American server and then I could access it.
When executing ./configure to dockerfile,The following error occurred,It seems to be a network problem. Is there any solution:
**_#0 59.71 Making all in go
#0 206.8 go: git.zabbix.com/ap/plugin-support@v0.0.0-20220608100211-35b8bffd7ad0: Get "https://proxy.golang.org/git.zabbix.com/ap/plugin-support/@v/v0.0.0-20220608100211-35b8bffd7ad0.mod": dial tcp 142.251.43.17:443: connect: connection refused_**

**Comment by dotneft** [comment]
looks like container does not have internet access.

**Comment by qx517971976** [comment]
> looks like container does not have internet access.

yes,chinese network
ε(┬┬﹏┬┬)3

**Comment by dotneft** [comment]
you can disable agent2 and web-service compilation, in this case no access to internet will be required

**Comment by qx517971976** [comment]
> you can disable agent2 and web-service compilation, in this case no access to internet will be required

I'll try after work. Thank you

**Comment by qx517971976** [comment]
> you can disable agent2 and web-service compilation, in this case no access to internet will be required

Nice,Successfully built, thank you
