### ISSUE TITLE
Docker Template Containers ID changing

### ISSUE THREAD

**Issue by GrodanEller** [zabbix/zabbix-docker#994]
<I am using Template app docker in 40 servers. the problem i get is that when the container change en get rebooted, the template discover it as a new Container, And the old get remove by the keep lost items rule. That cause me to lost history and trends. Is a way to keep the container identified as the same?

**Comment by dotneft** [comment]
Hm... the issue is not related to Zabbix images. Please check our [forum](http://zabbix.com/forum/) and [bug tracker](https://support.zabbix.com/).
