### ISSUE TITLE
why ZBX_ACTIVESERVERS parameter contains ZBX_SERVER_HOST parameter

### ISSUE THREAD

**Issue by xingmwang** [zabbix/zabbix-docker#996]
##### SUMMARY
 ZBX_ACTIVESERVERS parameter contain ZBX_SERVER_HOST parameter, so when I define ZBX_SERVER_HOST and ZBX_ACTIVESERVERS, then the agent conatiner combine these two parameters. and give me an error: " zabbix_agent2 [8]: ERROR: cannot parse the "ServerActive" parameter: address "192.168.56.11:10051" specified more than once"

##### OS / ENVIRONMENT / Used docker-compose files
OS: Ubunut20.04
Docker: 20.10.9

##### CONFIGURATION
```shell
docker run --name zabbix-agent \
    -e ZBX_HOSTNAME="worker01" \
    -e ZBX_SERVER_HOST="192.168.56.11,192.168.56.12" \
    -e ZBX_SERVER_PORT="10051" \
    -e ZBX_ACTIVESERVERS="192.168.56.11;192.168.56.12" \
    -e ZBX_DEBUGLEVEL='3' \
    -e ZBX_LISTENPORT="10050" \
    -p 10050:10050 \
    --privileged \
    --restart=always \
    --name zabbixs \
    -d zabbix/zabbix-agent2:alpine-6.0-latest
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
running zabbix agent normal

##### ACTUAL RESULTS

```
zabbix_agent2 [8]: ERROR: cannot parse the "ServerActive" parameter: address "192.168.56.11:10051" specified more than once

```

**Comment by dotneft** [comment]
Use ZBX_PASSIVESERVERS instead of ZBX_SERVER_HOST. If you use ZBX_SERVER_HOST, it is applied to both Active and Passive params.
