### ISSUE TITLE
excute ping command no result

### ISSUE THREAD

**Issue by xingmwang** [zabbix/zabbix-docker#998]
##### SUMMARY

ping address has no result

##### OS / ENVIRONMENT / Used docker-compose files

zabbix-agent2:ubuntu-6.0-latest

##### STEPS TO REPRODUCE

```yaml
docker run --rm -it zabbix/zabbix-agent2:alpine-6.0-latest /bin/bash
ping www.google.com
```

##### EXPECTED RESULTS

print ping results

##### ACTUAL RESULTS

```paste below
no result
```

**Comment by dotneft** [comment]
Works fine for me:
<img width="590" alt="Screenshot 2022-08-04 at 11 11 49" src="https://user-images.githubusercontent.com/10911965/182797845-d4c1779f-947a-4556-b095-6be0607faa50.png">

**Comment by xingmwang** [comment]
> Works fine for me: <img alt="Screenshot 2022-08-04 at 11 11 49" width="590" src="https://user-images.githubusercontent.com/10911965/182797845-d4c1779f-947a-4556-b095-6be0607faa50.png">

![image](https://user-images.githubusercontent.com/63380084/183854286-60ec1dbc-2a98-4938-bc89-c55aceca2347.png)
but not works for me

**Comment by dotneft** [comment]
I recommend check possible restrictions on docker / OS level: https://docs.docker.com/engine/security/

**Comment by Ricaz** [comment]
I'm having the same issue with `fping` on `6.2-latest`. It might be an OS issue, but I have no idea where to look.
Any ideas?

**Comment by dotneft** [comment]
Please check the link from my previous comment.
